#!/usr/bin/env python3
"""Generate q_TERMS.js from glossary.js: up to three questions per term: a
situation to recognise (scene -> term), the term's one-line meaning (term ->
gist, short options), and the full definition -> term.
Distractors come from the term's `confuse` list first, then its group. The
second question is `dupOf` the first so one exam paper never carries both."""
import json, random, subprocess, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)
if not os.path.exists('glossary.js'):
    sys.exit('gen_terms.py: glossary.js not found')
js = "const fs=require('fs'),vm=require('vm');process.stdout.write(JSON.stringify(vm.runInNewContext(fs.readFileSync('glossary.js','utf8')+';TERMS',{})))"
TERMS = json.loads(subprocess.run(['node', '-e', js], capture_output=True, text=True, check=True).stdout)
by_id = {t['id']: t for t in TERMS}
groups = {}
for t in TERMS:
    groups.setdefault(t['group'], []).append(t)

def pick_distractors(t, key, k=3, need_longer=False):
    """Distractor terms: confusables first, then the same group, then anywhere."""
    rng = random.Random(t['id'])
    pool = [by_id[c] for c in t.get('confuse', []) if c in by_id and c != t['id']]
    same = [x for x in groups[t['group']] if x['id'] != t['id'] and x not in pool]
    rng.shuffle(same)
    rest = [x for x in TERMS if x['id'] != t['id'] and x not in pool and x not in same]
    rng.shuffle(rest)
    cands = pool + same + rest
    chosen = []
    if need_longer:
        longer = [x for x in cands if len(x[key]) > len(t[key])]
        if not longer:
            return None
        chosen.append(longer[0])
    for x in cands:
        if len(chosen) >= k:
            break
        if x not in chosen:
            chosen.append(x)
    return chosen

qs = []
group_ids = {}
for g in groups:
    group_ids[g] = 'g' + str(len(group_ids) + 1)

for t in TERMS:
    cite = t.get('cite', '')
    base = dict(lecture=t['lecture'], prof='Gottlieb', tier='new', topic='TERMS', sub=group_ids[t['group']],
                skill='term', concept='term-' + t['id'], tags=['term'], source=t.get('src', 'slide'),
                cite=cite, quote=t.get('quote', ''))
    teach = t['def'] + (' ' + t['hook'] if t.get('hook') else '')
    def fig(q):
        if t.get('fig'):
            q['fg'] = t['fig']
        return q
    first = None
    # 1. a situation -> the term (the term named nowhere in the stem)
    if t.get('scene'):
        d = pick_distractors(t, 'term', need_longer=True)
        if d:
            opts = [{'t': t['term'], 'correct': True, 'why': 'This situation is ' + t['term'].lower() + ': ' + (t.get('gist') or t['def'])}]
            for x in d:
                opts.append({'t': x['term'], 'correct': False, 'why': x['term'] + ' would be: ' + (x.get('gist') or x['def'])})
            first = 'T-' + t['id'] + '-1'
            qs.append(fig(dict(base, id=first, stem='Which term fits this situation? ' + t['scene'], options=opts, teach=teach)))
    # 2. the term -> its one-line meaning (short options; a longer wrong gist must exist)
    if t.get('gist'):
        d2 = pick_distractors(t, 'gist', need_longer=True)
        if d2:
            opts = [{'t': t['gist'], 'correct': True, 'why': 'That is ' + t['term'].lower() + '.'}]
            for x in d2:
                opts.append({'t': x['gist'], 'correct': False, 'why': 'That is ' + x['term'].lower() + ', not ' + t['term'].lower() + '.'})
            q2 = fig(dict(base, id='T-' + t['id'] + '-2', stem=t['term'] + ' means:', options=opts, teach=teach))
            if first:
                q2['dupOf'] = first
            else:
                first = q2['id']
            qs.append(q2)
    # 3. the full definition -> the term
    d3 = pick_distractors(t, 'term', need_longer=True)
    if d3:
        opts = [{'t': t['term'], 'correct': True, 'why': 'This is the definition of ' + t['term'] + '.'}]
        for x in d3:
            opts.append({'t': x['term'], 'correct': False, 'why': x['term'] + ': ' + (x.get('gist') or x['def'])})
        q3 = fig(dict(base, id='T-' + t['id'] + '-3', stem='Which term is defined as: ' + t['def'].rstrip('.') + '?', options=opts, teach=teach))
        if first:
            q3['dupOf'] = first
        qs.append(q3)

out = ["TOPICS.push({id:'TERMS', name:'Terminology', prof:'Gottlieb', lecture:'L01',",
       "  cite:'Definitions from the Day 1–5 decks and transcripts',",
       "  subs:[" + ','.join(f"{{id:'{gid}', name:{json.dumps(g)}, cite:'glossary'}}" for g, gid in group_ids.items()) + "]});",
       '/* Generated by gen_terms.py from glossary.js. Edit the glossary, not this file. */',
       'QUESTIONS.push(' + ',\n'.join(json.dumps(q, ensure_ascii=False) for q in qs) + ');']
open('q_TERMS.js', 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print(len(qs), 'term questions from', len(TERMS), 'terms')
