#!/usr/bin/env python3
"""Generate q_TERMS.js from glossary.js: two questions per term, one asking for
the term from its definition and one asking for the definition from the term.
Distractors come from the term's `confuse` list first, then its group. The
second question is `dupOf` the first so one exam paper never carries both."""
import json, random, subprocess, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)
if not os.path.exists('glossary.js'):
    sys.exit('gen_terms.py: glossary.js not found')
js = "const fs=require('fs'),vm=require('vm');process.stdout.write(JSON.stringify(vm.runInNewContext(fs.readFileSync('glossary.js','utf8')+';TERMS',{})))"
TERMS = json.loads(subprocess.run(['node', '-e', js], capture_output=True, text=True, check=True).stdout)
by_id = {t['id']: t for t in TERMS}
groups = {}
for t in TERMS:
    groups.setdefault(t['group'], []).append(t)

def pick_distractors(t, key, k=3, need_longer=False):
    """Distractor terms: confusables first, then the same group, then anywhere."""
    rng = random.Random(t['id'])
    pool = [by_id[c] for c in t.get('confuse', []) if c in by_id and c != t['id']]
    same = [x for x in groups[t['group']] if x['id'] != t['id'] and x not in pool]
    rng.shuffle(same)
    rest = [x for x in TERMS if x['id'] != t['id'] and x not in pool and x not in same]
    rng.shuffle(rest)
    cands = pool + same + rest
    chosen = []
    if need_longer:
        longer = [x for x in cands if len(x[key]) > len(t[key])]
        if not longer:
            return None
        chosen.append(longer[0])
    for x in cands:
        if len(chosen) >= k:
            break
        if x not in chosen:
            chosen.append(x)
    return chosen

qs = []
group_ids = {}
for g in groups:
    group_ids[g] = 'g' + str(len(group_ids) + 1)

for t in TERMS:
    cite = t.get('cite', '')
    base = dict(lecture=t['lecture'], prof='Gottlieb', tier='new', topic='TERMS', sub=group_ids[t['group']],
                skill='term', concept='term-' + t['id'], tags=['term'], source=t.get('src', 'slide'),
                cite=cite, quote=t.get('quote', ''))
    teach = t['def'] + (' ' + t['hook'] if t.get('hook') else '')
    # 1. definition -> term
    d = pick_distractors(t, 'term', need_longer=True)
    if d:
        opts = [{'t': t['term'], 'correct': True, 'why': 'This is the definition of ' + t['term'] + '.'}]
        for x in d:
            opts.append({'t': x['term'], 'correct': False, 'why': x['term'] + ': ' + x['def']})
        q1 = dict(base, id='T-' + t['id'] + '-1', stem='Which term is defined as: ' + t['def'].rstrip('.') + '?',
                  options=opts, teach=teach)
        if t.get('fig'):
            q1['fg'] = t['fig']
        qs.append(q1)
    # 2. term -> definition (only when a longer wrong definition exists)
    d2 = pick_distractors(t, 'def', need_longer=True)
    if d2:
        opts = [{'t': t['def'], 'correct': True, 'why': 'This is the definition of ' + t['term'] + '.'}]
        for x in d2:
            opts.append({'t': x['def'], 'correct': False, 'why': 'That defines ' + x['term'].lower() + '.'})
        q2 = dict(base, id='T-' + t['id'] + '-2', stem='What does the term "' + t['term'] + '" mean?', options=opts, teach=teach)
        if d:
            q2['dupOf'] = 'T-' + t['id'] + '-1'
        if t.get('fig'):
            q2['fg'] = t['fig']
        qs.append(q2)

out = ["TOPICS.push({id:'TERMS', name:'Terminology', prof:'Gottlieb', lecture:'L01',",
       "  cite:'Definitions from the Day 1–3 decks and transcripts',",
       "  subs:[" + ','.join(f"{{id:'{gid}', name:{json.dumps(g)}, cite:'glossary'}}" for g, gid in group_ids.items()) + "]});",
       '/* Generated by gen_terms.py from glossary.js. Edit the glossary, not this file. */',
       'QUESTIONS.push(' + ',\n'.join(json.dumps(q, ensure_ascii=False) for q in qs) + ');']
open('q_TERMS.js', 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print(len(qs), 'term questions from', len(TERMS), 'terms')
