/* Exam 1 glossary — PHAR 4344, Dr. Gottlieb, Days 1–3 (9/22–9/24).
   Definitions come from the lecture decks and transcripts (slide wording first;
   his spoken wording in hook/quote where the two differ). Slide numbers marked ~
   were counted from the deck text and may be off by one or two.
   Groups: 'Drug basics', 'Drug–receptor binding', 'Drug classes',
   'Dose–response curves', 'Receptors and signaling'.
   Figure keys: drc-basic, potency, efficacy, partial, inverse, competitive,
   irreversible, binding-kd, sites, two-state, gpcr, spare. */
const TERMS = [

/* ---------------- Drug basics ---------------- */
{id:'pharmacology', term:'Pharmacology', lecture:'L01', group:'Drug basics',
 def:'The study of the interaction of drugs with biological systems: which drug, what it does and where, and how much (the smallest dose that gives the desired effect). It determines mechanisms of action, dose–response relationships, therapeutic dose, potency, minimal and maximal effect, and safety.',
 hook:'The pharmacology diagram splits it in two: pharmacokinetics (absorption, distribution, metabolism, excretion) and pharmacodynamics (drug–receptor signaling that gives the physiological response).',
 confuse:['pharmacodynamics','pharmacokinetics'],
 quote:'Pharmacology: “the study of the interaction of “Drugs” with biological systems” ... Which, What, & Where? How much? Smallest dose => Desired effect?',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~21–~22; transcript 9/22',
 src:'both'},

{id:'pharmacodynamics', term:'Pharmacodynamics (PD)', lecture:'L02', group:'Drug basics',
 def:'The study of the biochemical and physiological effects of drugs and their mechanisms of action. General rules: the drug must reach the site of action, must bind to and interact with a receptor, and does not create anything but changes the ongoing physiological system.',
 hook:'Spoken definition: “the study of how drugs interact with the biological system.” Its two basic concepts are affinity and efficacy.',
 confuse:['pharmacokinetics','pharmacology'],
 quote:'General rules: 1) Drug must reach the site of action 2) Drug must bind to and interact with a receptor 3) Drug do not create anything, but change the ongoing phys. system',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slide ~31; Pharmacodynamics-Day-1-2026s.pdf slide ~22; transcript 9/23',
 src:'both'},

{id:'pharmacokinetics', term:'Pharmacokinetics (PK)', lecture:'L01', group:'Drug basics',
 def:'The absorption, distribution, metabolism and excretion (ADME) side of the pharmacology diagram: how much of the drug gets to the site of action. It sets the apparent potency of a drug (age, absorption, distribution, elimination, drug–drug interactions).',
 hook:'On the efficacy poll, “the ability of a drug to be absorbed at the level of the GI” is pharmacokinetics, not efficacy.',
 confuse:['pharmacodynamics','apparent-potency'],
 quote:'So pharmokinetics is going to be affecting how much of the drug gets to the site of action. Because that’s how it’s going to produce its effects.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~22–~23, ~27; transcript 9/22',
 src:'both'},

{id:'drug', term:'Drug', lecture:'L01', group:'Drug basics',
 def:'A chemical substance that alters an ongoing physiological or pathological function by interacting with components of a biological system. Drugs initiate, inhibit or modulate a response; they do not create anything new.',
 hook:'Walter Straub: there is only a quantitative difference between a drug and a poison (vitamin A in carrots vs polar bear liver).',
 confuse:['ligand','nds'],
 quote:'drugs don’t create anything new, they just change whatever is happening in the body. Either they are going to enhance the signal or perhaps suppress the signal',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~29–~31; transcript 9/22',
 src:'both'},

{id:'receptor', term:'Receptor', lecture:'L01', group:'Drug basics',
 def:'Regulatory proteins involved in the transfer of chemical information carried by endogenous or exogenous mediators. Classified by the structure of the receptor protein and its transduction components: ion channels, 7-transmembrane (GPCR), 1-transmembrane (tyrosine kinases) and intracellular/nuclear receptors.',
 hook:'His picture: the gatekeeper that senses hormones, neurotransmitters and drugs; the message the receptor creates is the physiological response. Receptors come in two flavors, active or inactive.',
 confuse:['ligand','effector','transducer'],
 quote:'Receptors are regulatory proteins involved in the transfer of chemical information carried by various endogenous/exogenous mediators',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~11, ~34–~36; transcript 9/22',
 src:'both'},

{id:'ligand', term:'Ligand', lecture:'L03', group:'Drug basics',
 def:'A chemical that a receptor recognizes and binds by its shape, size and other properties: endogenous (a hormone or neurotransmitter) or exogenous (a drug, a supplement, something eaten or drunk). A ligand induces a conformational change in the receptor.',
 hook:'Multiple chemicals may bind the same receptor, and one chemical may bind multiple receptors (acetylcholine at nicotinic and muscarinic). Ligand-gated channels are named for it.',
 confuse:['drug','receptor'],
 quote:'Cells have receptors that recognize specific chemicals ... Endogenous as well as exogenous',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~26, ~30; transcript 9/23; transcript 9/24',
 src:'both'},

{id:'moa', term:'Mechanism of action (MOA)', lecture:'L01', group:'Drug basics',
 def:'What the drug does at its receptor: which receptor it binds and whether it activates, inhibits or just binds (e.g., metoprolol: reversible β1 receptor antagonist). The must-know for every drug on Exam 1.',
 hook:'MOA is must-know; site of action (SOA) is should-know; effect, ADR and DDI are predicted from the two. Use, dose, route and brand names are not tested.',
 confuse:['soa'],
 quote:'So which receptor is binding to you, what is it doing to that receptor when it’s bound, is it activating, inhibiting, just binding, where is the receptor located',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~7–~9, ~12, ~33; transcript 9/22',
 src:'both'},

{id:'soa', term:'Site of action (SOA)', lecture:'L01', group:'Drug basics',
 def:'Where the receptor the drug acts on is located (metoprolol: heart, kidneys and brain; thiazides: distal convoluted tubule). Knowing MOA plus SOA lets you predict the effect, side effects and drug–drug interactions without memorizing them.',
 hook:'Classifying a drug by chemical structure (benzothiadiazine ring) predicts little; MOA plus SOA (Na+/Cl− symporter antagonist at the distal tubule) predicts diuresis and hyponatremia.',
 confuse:['moa'],
 quote:'The things that you should know are going to be the sites of actions. Because if you know where the receptor is located and you know what it does to the receptor, now you can predict the effect, the side effect, the drug-drug interaction, contraindication, use.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~7, ~9, ~33; transcript 9/22',
 src:'both'},

{id:'nds', term:'Natural dietary supplement (NDS)', lecture:'L01', group:'Drug basics',
 def:'A product regulated as food, not as a drug, so with less FDA oversight; it stays on the market until it causes harm. Its label cannot state that it treats, cures, diagnoses or prevents disease, and natural does not mean safe or free of drug interactions.',
 hook:'Every option on his NDS poll was incorrect: labels cannot claim cure, the FDA does not test them like prescription drugs, centuries of use does not prove safety and effectiveness, and herbals interact with prescription/OTC drugs.',
 confuse:['drug'],
 quote:'Dietary supplements regulated as food ... Not Drugs (Less FDA oversight) ... until they cause harm',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~15–~16, ~18, ~20; transcript 9/22',
 src:'both'},

{id:'selectivity', term:'Selectivity', lecture:'L01', group:'Drug basics',
 def:'How narrowly a drug binds one receptor type rather than others: loratadine is a selective H1 inverse agonist; diphenhydramine binds H1, H2 and muscarinic receptors and is very non-selective. The less selective a drug is, the more effects and side effects it produces.',
 hook:'The larger the dose gets, the less selective a drug becomes (metoprolol is β1-selective up to about 200 mg, then affects β2). Selectivity is about which receptors are bound; affinity is how tightly.',
 confuse:['affinity','potency'],
 quote:'the larger the dose gets, the less selective a drug becomes ... Metoprolol is a beta 1 selective up to about 200 mg. Once you go above 200, you start to affect the beta 2s, so you start to lose selectivity',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~21, ~29; transcript 9/22; transcript 9/24',
 src:'both'},

/* ---------------- Drug–receptor binding ---------------- */
{id:'affinity', term:'Affinity', lecture:'L02', group:'Drug–receptor binding',
 def:'The attraction of a ligand for the receptor: how likely a drug is to bind and stay bound. It depends on the molecular forces (bonds) the drug forms with the receptor and is measured by Kd: the smaller the Kd, the greater the affinity.',
 hook:'Affinity is read on the x-axis (further left = higher affinity); efficacy on the y-axis. Poll trap: “the ability of a drug to bind and stay bound to a receptor” is affinity, not efficacy.',
 confuse:['efficacy','potency','kd'],
 fig:'binding-kd',
 quote:'Remember, affinity is how likely a drug is to bind and stay bound to a receptor, and the binding of a drug to the receptor is going to be depending on what type of bonds they form covalent bonds, hydrogen bonds, ion bonds.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~31, ~55; Pharmacodynamics-Day-1-2026s.pdf slides ~21, ~37; transcript 9/22; transcript 9/23',
 src:'both'},

{id:'efficacy', term:'Efficacy (intrinsic efficacy)', lecture:'L02', group:'Drug–receptor binding',
 def:'The property of a molecule that causes the receptor to change its behavior: the ability of the drug to change the receptor state, active to inactive or inactive to active. Positive efficacy activates receptors, negative efficacy shuts them down, and zero efficacy is a neutral antagonist.',
 hook:'Read on the y-axis as the height of the curve (Emax). Efficacy cannot be calculated directly; it is a relative measurement between ligands.',
 confuse:['affinity','intrinsic-activity','potency'],
 fig:'efficacy',
 quote:'Efficacy is the ability of that drug to change the receptor behavior. It’s activity, its state from active to inactive or inactive to active, right?',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slide ~31; Pharmacodynamics-Day_3_2026s.pdf slides ~19, ~26; Pharmacodynamics-Day-1-2026s.pdf slide ~38; transcript 9/22; transcript 9/23',
 src:'both'},

{id:'intrinsic-activity', term:'Intrinsic activity', lecture:'L03', group:'Drug–receptor binding',
 def:'Ariëns’ number for the ability of a drug to produce a response, dependent on its chemical structure: full agonist = 1, partial agonist between 0 and 1, antagonist = 0.',
 hook:'It does not account for the tissue (how many receptors are present), so it is incomplete; efficacy is the more comprehensive term. The names and the formula are not tested.',
 confuse:['efficacy','occupancy-theory'],
 quote:'What he did not count was for the tissue, how many receptors are present in that system. So this is an incomplete theory that we can’t really use much',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~24–~26; Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22; transcript 9/24',
 src:'both'},

{id:'kd', term:'Kd (dissociation constant)', lecture:'L02', group:'Drug–receptor binding',
 def:'The coefficient of dissociation (also written Ki, Ka): the drug concentration that binds 50% of the available binding sites. From the law of mass action, Kd = [D][R]/[DR] = K2/K1 (rate of dissociation over rate of association). The smaller the Kd, the greater the affinity: they are inversely proportional.',
 hook:'Kd is read on the x-axis of a binding curve and says nothing about effect; EC50 is 50% of the response. Compare Kd values only after converting units (milli 10^-3, micro 10^-6, nano 10^-9): “the units ... about 10% of you are gonna miss it.”',
 confuse:['ec50','affinity','mass-action'],
 fig:'binding-kd',
 quote:'So the take-home message is that the smaller the coefficient of dissociation is, the more drugs receptors are going to find together, and thus the greater the affinity is going to be.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~45–~50; Pharmacodynamics-Day_3_2026s.pdf slide ~31; transcript 9/24',
 src:'both'},

{id:'binding-curve', term:'Binding curve (Bmax)', lecture:'L02', group:'Drug–receptor binding',
 def:'Percent of receptors bound (0% up to Bmax, 100% of the receptors) plotted against log[concentration]. Kd is the concentration at 50% bound, read on the x-axis; the curve furthest left has the smallest Kd and the highest affinity.',
 hook:'A binding curve shows binding only; a dose–response curve shows effect (Emax, EC50). Drug C “requires less dose to bind 50% of the receptors” so it has the highest affinity.',
 confuse:['drc','kd'],
 fig:'binding-kd',
 quote:'And the further the left you are, the smaller the dose is going to be required, and thus the more affinity a drug is gonna have for the receptor.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slide ~50; Pharmacodynamics-Day_3_2026s.pdf slide ~3; transcript 9/24',
 src:'both'},

{id:'mass-action', term:'Law of mass action', lecture:'L02', group:'Drug–receptor binding',
 def:'The rate of a chemical reaction is proportional to the concentration (mass) of the reactants: the more drug or the more receptors present, the greater the chance of binding. It is the basis of Kd and of dose responsiveness.',
 hook:'More receptors in a tissue make the same dose of norepinephrine appear more potent (curve shifts left) while its Kd, affinity and efficacy are unchanged; what changed is the tissue.',
 confuse:['kd','occupancy-theory'],
 quote:'The more I have either of the receptors or the more I have either the drug, the greater the capacity of binding to something is going to be, right?',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slide ~45; transcript 9/24',
 src:'both'},

{id:'covalent-bond', term:'Covalent (irreversible) bond', lecture:'L02', group:'Drug–receptor binding',
 def:'Two atoms share a pair of electrons; the bond is irreversible at body temperature and gives a long duration of action. Covalent binding is called irreversible, insurmountable or non-competitive, three names for one property; ionic, hydrogen and van der Waals bonds are reversible, surmountable, competitive.',
 hook:'Aspirin, omeprazole and phenoxybenzamine form covalent bonds; a covalent binder has the highest affinity and the smallest Kd. Weak-bond drugs must fit the pocket like a hand in a glove, which is where selectivity comes from.',
 confuse:['irreversible-antagonist','affinity'],
 quote:'They can be classified as irreversible, insurmountable, and non-competitive, which means is They all mean the same thing ... What does that mean? Once they are bound, they’re not coming off, OK?',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~15–~16; transcript 9/23; transcript 9/24',
 src:'both'},

{id:'orthosteric', term:'Orthosteric site', lecture:'L02', group:'Drug–receptor binding',
 def:'The receptor’s own binding pocket, where the endogenous agonist binds. Orthosteric drugs (phenylephrine, prazosin, phenoxybenzamine at α1) compete for that one pocket, so only one can be bound at a time: either one or the other, not both.',
 hook:'Orthosteric: one or the other. Allosteric: one and the other. Spoken as “orthostatic” in the transcripts; the slide term is orthosteric.',
 confuse:['allosteric'],
 fig:'sites',
 quote:'How we define orthostatic. So they compete for the same binding pocket, right? ... with orthostatic, we can have either one or the other, not both at the same time. As with allosteric, we can have one in the other',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~18–~19; transcript 9/23; transcript 9/24',
 src:'both'},

{id:'allosteric', term:'Allosteric site / modulator', lecture:'L02', group:'Drug–receptor binding',
 def:'A different (allotopic) binding site on the receptor. An allosteric drug binds there and can increase or decrease the affinity and/or efficacy of another drug for the receptor, or have no effect; it does not compete for the orthosteric pocket, so both drugs can be bound at once.',
 hook:'“Where the magic in pharmacology is”: they don’t always do things by themselves but make other drugs much better or much worse. Poll traps: allosteric agonists do not compete for the orthosteric pocket and do not have the highest affinity for it.',
 confuse:['orthosteric','indirect-antagonist','allosteric-agonist'],
 fig:'classes',
 quote:'These drugs do not bind or compete for the orthostatic binding pocket. They bind someplace else on the receptor.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~19–~20, ~39, ~44; Pharmacodynamics-Day-1-2026s.pdf slide ~29; transcript 9/22; transcript 9/23',
 src:'both'},

{id:'occupancy-theory', term:'Receptor occupancy theory', lecture:'L01', group:'Drug–receptor binding',
 def:'Clark’s first theory of how drugs work: the response is proportional to the number of receptors occupied, so it rests on affinity alone (D + R ⇄ DR → stimulus). A full agonist occupies all receptors for 100% of the response; a partial agonist occupies a fraction (e.g., 70%) and gives that fraction.',
 hook:'It could not explain antagonists or inverse agonists. Ariëns added intrinsic activity; Stephenson, Furchgott and Nickerson added efficacy and the two-state model. The names are FYI, not tested.',
 confuse:['intrinsic-activity','two-state','mass-action'],
 quote:'a full agonist will produce 100% of the response as a partial may produce a 70% of the response because it can only occupy 70% of the receptors, right? So it’s based on occupancy.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22',
 src:'both'},

{id:'two-state', term:'Two-state model', lecture:'L03', group:'Drug–receptor binding',
 def:'Receptors exist in two states, inactive/resting (R) and active (R*), and move between them on their own; L is the equilibrium constant between [R] and [R*]. Drugs have affinity for R and/or R* (Kd and Kd*) and shift the balance: toward R* is positive efficacy, toward R is negative efficacy.',
 hook:'“This is gonna be home for us.” It explains inverse agonists, which occupancy theory could not. Most receptors sit in the inactive state to save energy.',
 confuse:['occupancy-theory','intrinsic-activity'],
 fig:'two-state',
 quote:'So this two-state model shows that we have receptor two confirmations, active and inactive, and that drugs can shift them once bound to the receptor from one confirmation to the other.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~31; Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22; transcript 9/23',
 src:'both'},

/* ---------------- Drug classes ---------------- */
{id:'full-agonist', term:'Full agonist', lecture:'L03', group:'Drug classes',
 def:'Binds and stabilizes the receptor in the active state (R*): highest affinity for active-state receptors, positive (high) efficacy, and can reach 100% of the system’s maximal response. Examples: norepinephrine, epinephrine, acetylcholine.',
 hook:'Same affinity preference as a partial agonist; the difference is efficacy (100% vs 1–99%). “I do not know of any agonist that is irreversible.”',
 confuse:['partial-agonist','inverse-agonist'],
 fig:'classes',
 quote:'Let’s think about that we can dim, so we have one that can kind of go full bright or just halfway bright, a full agonist or a partial.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~33–~41; Pharmacodynamics-Day_2_2026s copy.pdf slides ~32–~34; transcript 9/23; transcript 9/24',
 src:'both'},

{id:'partial-agonist', term:'Partial agonist', lecture:'L03', group:'Drug classes',
 def:'Positive efficacy but lower than a full agonist (1–99%): it converts inactive receptors to active but cannot reach 100% of the system’s max response (Emax less than 100%) and cannot bring the response all the way to 100% or 0%. Examples: albuterol (β2), varenicline (Nn), pindolol (β1, β2), aripiprazole (D2).',
 hook:'Dual nature: it may act as an agonist or an antagonist depending on the physiological state (varenicline during smoking vs withdrawal). A partial agonist can still be the most potent drug on a graph.',
 confuse:['full-agonist','neutral-antagonist','inverse-agonist'],
 fig:'classes',
 quote:'So sometimes we may use a partial agonist over a full agonist because we don’t need to get the max effect. We just need to get enough of it.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~50–~65; Pharmacodynamics-Day_2_2026s copy.pdf slides ~32–~34; transcript 9/23; transcript 9/24',
 src:'both'},

{id:'inverse-agonist', term:'Inverse agonist', lecture:'L02', group:'Drug classes',
 def:'Has the highest affinity for inactive receptors and negative efficacy: if it binds an active receptor it inhibits it, shifting receptors to the inactive state. Example: the antihistamine loratadine at H1.',
 hook:'Petri dish with 50% of receptors naturally active: an inverse agonist brings cAMP production to zero; a competitive (neutral) antagonist leaves it at 50%.',
 confuse:['neutral-antagonist','partial-agonist'],
 fig:'classes',
 quote:'These drugs love to bind to receptors that are inactive and keep them inactive. But they have what is called negative efficacy, which means is if they bind to a receptor that is already active, producing a signal, once they are bound, they’re going to shut them off.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~35–~36; Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22; transcript 9/23',
 src:'both'},

{id:'neutral-antagonist', term:'Antagonist (neutral, reversible)', lecture:'L02', group:'Drug classes',
 def:'A drug with no efficacy (ε = zero) and equal affinity for receptors in the active and inactive state: it occupies the receptor and keeps agonists from binding but does not change the receptor’s state. All about affinity. Examples: prazosin (α1), metoprolol (β1).',
 hook:'“Just a straight line”: an antagonist does not change the balance of receptors; an inverse agonist wants to keep everybody inactive. Intrinsic activity of an antagonist is zero.',
 confuse:['inverse-agonist','competitive-antagonist','partial-agonist'],
 fig:'classes',
 quote:'Antagonists, they’re neutral. Like they don’t care if the receptor is active or inactive, they have equal affinity for both receptor states.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~37–~38; transcript 9/23; transcript 9/24',
 src:'both'},

{id:'competitive-antagonist', term:'Competitive (reversible) antagonist', lecture:'L02', group:'Drug classes',
 def:'An antagonist held by reversible bonds (ionic, hydrogen, van der Waals): reversible, surmountable and competitive are three names for the same property. It competes with the agonist for the orthosteric pocket, binds and comes off, and can be outcompeted by agonist. Example: prazosin at α1.',
 hook:'Every drug on the Exam 1 drug list is reversible and competitive except phenoxybenzamine (drug-list PDF). The rightward-shift curve is Day 4 material (deck preview slide ~68).',
 confuse:['irreversible-antagonist','neutral-antagonist','indirect-antagonist'],
 fig:'classes',
 quote:'when we think about uh ionic bonds, hydrogen bonds, [van der Waals] bonds, those are going to be reversible, surmountable, competitive. Different words ... they’re gonna bind and they’re gonna come off.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~15–~16, ~18, ~37; transcript 9/23',
 src:'both'},

{id:'irreversible-antagonist', term:'Irreversible (non-competitive) antagonist', lecture:'L02', group:'Drug classes',
 def:'An antagonist that binds by a covalent bond, so once bound it does not come off at body temperature: irreversible, insurmountable, non-competitive. It has the highest affinity (smallest Kd) of the drug classes. Example: phenoxybenzamine (α1 and α2).',
 hook:'Once phenoxybenzamine is bound the receptor has to be internalized and recycled and the body must make new ones. Poll: phenoxybenzamine has higher affinity than prazosin. The reduced-Emax curve is Day 4 material (deck preview slide ~68).',
 confuse:['competitive-antagonist','covalent-bond','inverse-agonist'],
 fig:'classes',
 quote:'This is an irreversible antagonist, non-competitive, insurmountable. So what kind of bo[n]ds does it form? Covalent.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~15, ~18, ~37–~38; transcript 9/23; transcript 9/24',
 src:'both'},

{id:'indirect-antagonist', fig:'classes', term:'Indirect antagonist', lecture:'L02', group:'Drug classes',
 def:'A drug that inhibits the generation of a biological response by binding to components upstream or downstream from the receptor rather than the receptor itself; it can be reversible or irreversible. Examples: caffeine blocking PDE, a cancer drug blocking RAS.',
 hook:'It can raise the response (caffeine on PDE raises cAMP; a norepinephrine transporter blocker makes norepinephrine appear more potent) or lower it (RAS blocker stops cell growth). It is not allosteric: it never touches the receptor.',
 confuse:['allosteric','competitive-antagonist'],
 quote:'So, remember that indirect antagonists can work downstream from the receptor, but also upstream from the receptor, OK?',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~40–~41; transcript 9/23; transcript 9/24',
 src:'both'},

{id:'allosteric-agonist', fig:'classes', term:'Allosteric agonist (PAM)', lecture:'L02', group:'Drug classes',
 def:'Binds at a different site on the receptor and increases the affinity and/or efficacy of another drug for the receptor (positive allosteric modulator, PAM). Diazepam and other benzodiazepines increase the affinity and/or efficacy of GABA at the GABA-A chloride channel.',
 hook:'Diazepam is the allosteric agonist on the drug list “that you have to know for your exam.” A benzodiazepine plus alcohol puts two allosteric agonists on one receptor.',
 confuse:['allosteric-antagonist','full-agonist','allosteric'],
 fig:'classes',
 quote:'Benzos increase the affinity And/or efficacy of GABA For its receptor',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~21–~24, ~42; transcript 9/23',
 src:'both'},

{id:'allosteric-antagonist', fig:'classes', term:'Allosteric antagonist', lecture:'L02', group:'Drug classes',
 def:'Binds at a different site on the receptor and decreases the affinity and/or efficacy of another drug for the receptor.',
 hook:'It does not compete for the orthosteric pocket; a competitive antagonist does. “As far as I know, all allosteric agonists and antagonists are reversible.”',
 confuse:['allosteric-agonist','competitive-antagonist','indirect-antagonist'],
 fig:'classes',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slide ~43; transcript 9/23',
 src:'both'},

/* ---------------- Dose–response curves ---------------- */
{id:'drc', term:'Dose–response curve (DRC / CRC)', lecture:'L03', group:'Dose–response curves',
 def:'A graph relating drug dose (DRC) or concentration (CRC) on the x-axis (independent variable, log units, sigmoid curve) to the intensity of effect on the y-axis (dependent variable, normalized as % of maximum response). It is the model used to predict and compare drugs and determine potency.',
 hook:'DRC: increasing individual doses in vivo (ADME, apparent potency). CRC: increasing concentration in vitro (molar, pharmacological potency). Affinity is on the x-axis, efficacy on the y-axis, potency a combination of the two.',
 confuse:['binding-curve','graded-response'],
 fig:'drc-basic',
 quote:'So my dose is going to be on the bottom, on the X axis. My response is gonna be on the Y axis, which is on the up or down, OK?',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~8–~10, ~16–~18; Pharmacodynamics-Day_2_2026s copy.pdf slide ~56; transcript 9/24',
 src:'both'},

{id:'graded-response', term:'Graded response', lecture:'L03', group:'Dose–response curves',
 def:'A response measured in a single biological unit on a continuous scale that increases by degrees as the dose is raised over a specific range (e.g., 10-fold steps); a graded DRC/CRC relates the dose to the intensity of the effect.',
 hook:'The y-axis is normalized (% of maximum response or response per tissue weight) to eliminate biological variability between individuals: “now I can compare apples with apples.”',
 confuse:['drc','threshold'],
 quote:'Graded response by multiple increases of drug doses over a specific range',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~10, ~16, ~18; transcript 9/24',
 src:'slide'},

{id:'threshold', term:'Threshold', lecture:'L03', group:'Dose–response curves',
 def:'The concentration of the drug below which there is no response: the dose right before something happens. It must be known, with Emax, to calculate the EC50/ED50.',
 hook:'Threshold is where the curve starts; EC50 is the halfway point; Emax is the ceiling.',
 confuse:['ec50','emax','slope'],
 fig:'drc-basic',
 quote:'Remember that the threshold is the dose right before something happens, right? So I know that at any dose below this, no effect.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~20–~21; transcript 9/24',
 src:'both'},

{id:'emax', term:'Emax (maximal response, ceiling)', lecture:'L03', group:'Dose–response curves',
 def:'The plateau of the dose–response curve (ceiling of effect), reached either because all receptors are occupied or because the physiological system has maxed out. The height of Emax reflects efficacy.',
 hook:'Giving more drug past the ceiling does no more good. Curves with equal Emax differ by affinity; when EC50 is equal, greater efficacy makes the drug more potent (Relative Efficacy slide).',
 confuse:['ec50','efficacy','threshold'],
 fig:'drc-basic',
 quote:'What are the two reasons why we have reached the Emacs and we can’t keep going up? All the receptors are occupied or I max out the physiological system, right?',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~11–~14, ~20–~21, ~27; transcript 9/24',
 src:'both'},

{id:'slope', term:'Slope', lecture:'L03', group:'Dose–response curves',
 def:'The linear mid-section of the sigmoid curve, where the greatest change in effect comes from the smallest change in dose. A steep slope means a narrow dose range from no effect to maximum; a shallow slope means a wider range of doses before Emax.',
 hook:'Which is better “depends”: the steep curve goes from no effect to max all at once; the shallow one gives a greater range of doses before a toxic effect.',
 confuse:['threshold','emax','potency'],
 quote:'In that slope in that area of the curve, this is when I’m going to get the most bang for my buck. This is I’m going to get the greatest change in the response with the smallest change in the dose.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~20–~21; transcript 9/24',
 src:'both'},

{id:'ec50', term:'EC50 / ED50', lecture:'L03', group:'Dose–response curves',
 def:'EC50: the effective concentration that produces 50% of a drug’s maximal response (in vitro). ED50: the effective dose that produces 50% of the response (in vivo). It is the indicator of potency: the smaller the EC50/ED50, the greater the potency (inversely proportional).',
 hook:'Kd is the concentration binding 50% of receptors (affinity, no effect); EC50 is 50% of the response (potency). Both are read on the x-axis. “Philosophically identical”: one is a dose, the other a concentration.',
 confuse:['kd','emax','potency'],
 fig:'drc-basic',
 quote:'So, the take-home message that you can’t forget is that the smallest the ED50 is or the [EC]50, the greater the potency is gonna be. They’re inverse proportional.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~57–~58; Pharmacodynamics-Day_3_2026s.pdf slides ~20–~22, ~29; transcript 9/24',
 src:'both'},

{id:'potency', term:'Potency (pharmacological)', lecture:'L03', group:'Dose–response curves',
 def:'Potency = EC50 or ED50: how much drug is needed for a given response, read on the x-axis (further left = more potent). It is a combination of affinity, efficacy and the tissue (cell/tissue/organ/organism, e.g., number of receptors); the Day 1 slide lists tissue sensitivity, receptor number, receptor activity, affinity and efficacy.',
 hook:'Potency ≠ efficacy: the most potent drug (smallest EC50) can be a partial agonist; the most efficacious has the highest Emax. “Affinity is gonna be on the bottom, efficacy is gonna be on the Y axis, and potency is gonna be a combination of the two.”',
 confuse:['efficacy','affinity','apparent-potency'],
 fig:'potency',
 quote:'The take home message over here is that potency is not only going to be defined by the efficacy of the affinity, but also the tissue that is going to be bound to.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~7, ~22, ~27–~29; Pharmacodynamics-Day_2_2026s copy.pdf slides ~52–~54; Pharmacodynamics-Day-1-2026s.pdf slides ~21–~22, ~27; transcript 9/22; transcript 9/23; transcript 9/24',
 src:'both'},

{id:'apparent-potency', term:'Apparent potency', lecture:'L01', group:'Dose–response curves',
 def:'The potency seen in vivo, where pharmacokinetics (age, absorption, distribution, elimination, drug–drug interactions) determines how much drug reaches the site of action. It is “apparent” because it is not the total concentration of the drug that acts; a DRC built in vivo (ED50) shows apparent potency.',
 hook:'Route of administration and first-pass metabolism change apparent potency (IV has 100% bioavailability); they do not change the drug’s affinity or efficacy, which set pharmacological potency.',
 confuse:['potency','pharmacokinetics'],
 quote:'So this is going to give us our apparent potency. Why is apparent? ... It’s only appearing because it’s not the total concentration of the drug.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~23, ~27; Pharmacodynamics-Day_3_2026s.pdf slide ~8; transcript 9/22',
 src:'both'},

{id:'relative-potency', term:'Relative potency', lecture:'L03', group:'Dose–response curves',
 def:'The ratio of two drugs’ ED50 (or EC50) values, ED50B / ED50A. A drug that needs 1000 times less drug to produce an equivalent response is 1000X more potent.',
 hook:'Compare potency at equivalent effects (e.g., 50%), not at 100%, because a partial agonist never reaches 100%. “Math is gonna be minimal.”',
 confuse:['potency','ec50'],
 quote:'We can say that a drug A is 1000 times more potent than drug B because it requires 1000 times less drug to produce equivalent responses.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~23; transcript 9/24',
 src:'both'},

/* ---------------- Receptors and signaling ---------------- */
{id:'signal-transduction', term:'Signal transduction', lecture:'L02', group:'Receptors and signaling',
 def:'The sequence signal (hormone, growth factor, neurotransmitter, agonist drug) → receptor → transducer → effector (signal amplifier) → second messenger → physiological response: the signaling that occurs prior to the response. Drugs can change the activity of these proteins, and many of them can be drug targets.',
 hook:'Exam ask: identify what is a signal, a receptor, a transducer, an effector (“factor system”) and a second messenger in a pathway like epinephrine → β1 → Gαs → AC → cAMP.',
 confuse:['transducer','effector','second-messenger'],
 fig:'gpcr',
 quote:'Signal Transduction: Signal ... Receptor ... Transducer ... Effector (Signal Amplifier) ... 2nd Messenger ... Physiological Response',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~25–~28; transcript 9/23',
 src:'both'},

{id:'transducer', term:'Transducer', lecture:'L02', group:'Receptors and signaling',
 def:'The component that translates, integrates and coordinates the signal from the activated receptor, e.g., the G protein.',
 hook:'“Fancy name for translation.” Transducer = G protein; effector = the enzyme it activates (AC, PLC); second messenger = the small molecule the effector makes (cAMP, IP3).',
 confuse:['effector','second-messenger','g-protein'],
 fig:'gpcr',
 quote:'Our G protein, for example, can understand that change in the receptor. And by understanding and translating that change, it’s going to be called the transducer.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~26–~28; transcript 9/23',
 src:'both'},

{id:'effector', term:'Effector (signal amplifier)', lecture:'L02', group:'Receptors and signaling',
 def:'An enzyme, ion channel or transport protein that creates, moves or degrades a small molecule or ions, e.g., adenylate cyclase (AC), phospholipase C (PLC). It amplifies the signal; frequently the proximal effector protein is not the ultimate physiological target.',
 hook:'Poll trap: “phospholipase C is an example of a second messenger” — no, PLC is the effector (his “factor system”); IP3 is its second messenger.',
 confuse:['second-messenger','transducer'],
 fig:'gpcr',
 quote:'Frequently, the proximal cellular effector protein is not the ultimate physiological target but rather is an enzyme, ion channel, or transport protein that creates, moves, or degrades a small molecule or ions',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~26–~28; transcript 9/23',
 src:'both'},

{id:'second-messenger', term:'Second messenger', lecture:'L02', group:'Receptors and signaling',
 def:'Small molecules created, degraded or moved by an enzyme, ion channel or transport protein (the effector); they diffuse near their site of synthesis and convey information to a variety of targets. Slide examples: cAMP, PKA, PKC, IP3, Ca++.',
 hook:'“If there is cAMP and PKA, then select all ... you shouldn’t be picking the receptor or the AC or the calcium channel.” For the Gq pathway the two to know are IP3 and Ca++.',
 confuse:['effector','transducer'],
 fig:'gpcr',
 quote:'The production of the second messenger, which then is going to activate another 2nd messenger and then another 2nd messenger, just like a domino cascade until I get the physiological response that I want.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slide ~29; Pharmacodynamics-Day-1-2026s.pdf slides ~52–~53; transcript 9/23',
 src:'both'},

{id:'g-protein', term:'G protein (heterotrimeric)', lecture:'L01', group:'Receptors and signaling',
 def:'Heterotrimeric guanine nucleotide binding protein (α, β, γ subunits) coupled to 7-transmembrane receptors, defined and regulated by the α subunit. Cycle: agonist binds, the receptor activates, GDP comes off and GTP comes on, α dissociates and activates the effector (AC or PLC); intrinsic GTPase cleavage of GTP, accelerated by RGS, reverses it.',
 hook:'The G protein is the transducer. Poll trap: G proteins are defined by the α subunit, not the β subunit.',
 confuse:['gpcr','transducer','g-alpha'],
 fig:'gpcr',
 quote:'The GDP, the diphosphate, has to come off, and the G[T]P, as in taxes, the triphosphate has to come in. The removal of the GDP and replacement with the G[T]P is what triggers them to separate from each other.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~49–~55; Pharmacodynamics-Day_2_2026s copy.pdf slide ~3; transcript 9/23',
 src:'both'},

{id:'g-alpha', term:'Gαs, Gαi and Gαq', lecture:'L02', group:'Receptors and signaling',
 def:'The three α subunit types to know. Gαs (stimulation) activates adenylate cyclase and increases cAMP (β1 in the heart, ↑HR). Gαi (inhibition) inhibits adenylate cyclase and decreases cAMP (M2 in the heart, ↓HR; α2 in the CNS). Gαq activates phospholipase C, which converts PIP2 to IP3 and releases Ca++ from the ER (α1 in smooth muscle).',
 hook:'His cue: adenylate cyclase goes with cyclic AMP; αq goes with phospholipase C and IP3. Gαi is the trap: same effector as Gαs, opposite direction.',
 confuse:['g-protein','effector','cross-talk'],
 fig:'gpcr',
 quote:'We know that the alpha S always is going to be associated with the AC and always is going to increase the camp. The alphai, which is the opposite, also is going to be associated with the AC, but in this case it’s going to suppress the camp. And then the alpha Q is going to increase IP3 and calcium.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~3, ~30; Pharmacodynamics-Day-1-2026s.pdf slides ~50–~55; transcript 9/23',
 src:'both'},

{id:'gpcr', term:'G protein–coupled receptor (GPCR, 7-TM)', lecture:'L01', group:'Receptors and signaling',
 def:'7-transmembrane proteins that cross the membrane seven times and couple to a heterotrimeric G protein. The largest single class of pharmacological receptors, interacting with 60% plus of active therapeutic drugs. Examples: α and β adrenergic, 5HT, histamine, muscarinic receptors.',
 hook:'Four receptor classes: ion channels (L-type Ca++, GABA), 7-TM GPCRs, 1-TM (tyrosine kinases), intracellular/nuclear (steroid hormones). “If you know how they work, you’ve got 60% of the drugs in your pocket.”',
 confuse:['rtk','ion-channel','g-protein'],
 fig:'gpcr',
 quote:'About 60 or more% of all drugs in the market target one of kind of these receptors. So if you know how they work, you’ve got 60% of the drugs in your pocket.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~35–~36, ~49; transcript 9/22',
 src:'both'},

{id:'ion-channel', term:'Ion channel (ligand-gated)', lecture:'L01', group:'Receptors and signaling',
 def:'Transmembrane proteins (~232 types, expressed in all cells) that convey their signal by altering membrane potential or ionic composition (Na+, K+, Ca2+, Cl−); classified by the ions they conduct, their architecture and what opens them. Ligand-gated channels are usually closed with the binding pocket located in the channel (acetylcholine at the nicotinic receptor, GABA-A, 5HT3).',
 hook:'Passive: always open (resting potential, funny channel). Voltage-gated: open only at certain membrane potentials (Ca++ channels open as the membrane becomes more positive). Stretch: pressure sensitive (baroreceptors). Pumps: move ions against the gradient (Na+/K+ ATPase).',
 confuse:['gpcr','rtk'],
 quote:'You have a drug, a neurotransmitter, a hormone that is binding to a specific receptor. Once it’s bound, you can open it and allow things to move through it.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~35–~36, ~39–~48; transcript 9/23',
 src:'both'},

{id:'rtk', term:'Receptor tyrosine kinase (RTK, 1-TM)', lecture:'L02', group:'Receptors and signaling',
 def:'A 1-transmembrane receptor linked to an intracellular enzyme: an extracellular binding domain outside and intrinsic enzymatic (catalytic) activity inside. Ligand binding to the inactive monomer induces dimerization, cross-phosphorylation of the kinase domains and docking sites for signaling complexes; a tyrosine phosphatase resets it. Receptors for insulin and growth factors (cell survival, proliferation, differentiation).',
 hook:'Downstream: Grb2 → GEF → RAS → RAF → MEK → ERK → gene transcription; 20–25% of cancers contain a RAS mutation, so a RAS blocker is an indirect antagonist that stops cell growth.',
 confuse:['gpcr','nuclear-receptor','ion-channel'],
 quote:'They have this binding pocket on the outside, and they have this enzymatic activity inside of the cell. Typically those are transcription factors like insulin growth factors.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~4–~11; Pharmacodynamics-Day-1-2026s.pdf slides ~35–~36; transcript 9/23',
 src:'both'},

{id:'nuclear-receptor', term:'Nuclear (intracellular) receptor', lecture:'L02', group:'Receptors and signaling',
 def:'Intracellular receptors and transcriptional regulators: a superfamily of 48 receptor proteins that are transcription factor regulators. Ligands (androgens, estrogens, glucocorticoids, thyroid hormone, vitamin D) bind in the cytosol or nucleus and regulate gene expression (protein synthesis or mRNA turnover); co-repressor bound = inactive, co-activator bound = active.',
 hook:'Aldosterone at the mineralocorticoid receptor codes mRNA for more pumps and channels in the principal cell: sodium saving, potassium wasting. Exam ask: “what is the function of a nuclear receptor? How do they work”.',
 confuse:['rtk','gpcr'],
 quote:'Those are glucocor[tico]steroids. They are nuclear receptors. They affect DNA. They affect messenger RNA production.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~12–~14; Pharmacodynamics-Day-1-2026s.pdf slides ~35–~36; transcript 9/23',
 src:'both'},

{id:'cross-talk', term:'Cross-talk', lecture:'L02', group:'Receptors and signaling',
 def:'Interaction between signal transduction pathways within the same cell that yields a net response. In the heart, M2 (Gαi, ↓cAMP, ↓HR) and β1 (Gαs, ↑cAMP, ↑HR) both act on adenylate cyclase.',
 hook:'Two receptors, two G proteins, one effector (AC): the heart rate is the net of the two.',
 confuse:['g-alpha','second-messenger'],
 quote:'So we have multiple receptors that can be activated at the same time as we talked a little bit about that earlier in our heart, we have two major receptors, the beta 1s, which are sympathetic, and the M2s, muscarinics, which are parasympathetic, right?',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slide ~30; transcript 9/23',
 src:'both'},

{id:'baseline', term:'Baseline (point of reference)', lecture:'L04', group:'Dose–response curves',
 def:'The starting point of a dose–response curve: a reflection of the receptor activity in the system before the drug is added. With most receptors inactive (R > R*) the baseline is 0%; with half active it is 50%. Every drug-drug question starts from the agonist’s own curve as the point of reference.',
 hook:'One "greater than" sign on the exam means about 99% of receptors are inactive and the baseline is zero. Full agonist raises it, inverse agonist lowers it to zero, neutral antagonists leave it alone.',
 confuse:['emax','two-state'],
 fig:'two-state',
 quote:'The baseline is just a reflection of the receptor activity that is happening.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~15, ~45–~46; transcript 9/28',
 src:'both'},

{id:'constitutive-activity', term:'Constitutive activity', lecture:'L04', group:'Receptors and signaling',
 def:'Receptor activity that is present by itself, without any drug, hormone or neurotransmitter. Receptors that have constitutive activity are more sensitive to inverse agonists; it is what an inverse agonist shuts down.',
 hook:'Antihistamines were called antagonists until cell lines with naturally active receptors showed that loratadine and cetirizine bring the activity to zero. Listed receptors: histamine, opioid, cannabinoid, dopamine, bradykinin, adenosine.',
 confuse:['inverse-agonist','neutral-antagonist'],
 fig:'inverse',
 quote:'Receptors that have constitutive activity are more sensitive to inverse agonists',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~23; transcript 9/28',
 src:'both'},

{id:'chemical-antagonist', term:'Chemical antagonist', lecture:'L04', group:'Drug classes',
 def:'A drug that antagonizes by a direct chemical interaction with the agonist (or a toxin), binding the chemical so the body can get rid of it. Example: chelating agents such as dimercaprol for gold, mercury or arsenic poisoning.',
 hook:'No receptor is involved; the antagonist binds the chemical itself. Contrast physiological antagonism (two receptors, opposite effects).',
 confuse:['physiological-antagonist','competitive-antagonist'],
 quote:'Chemical: Direct chemical interaction between the agonist and antagonist. E.g. Chelating agents, dimercaprol',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~35; transcript 9/28',
 src:'both'},

{id:'physiological-antagonist', term:'Physiological antagonist', lecture:'L04', group:'Drug classes',
 def:'Two agonists acting independently of each other at different receptors in the same organ and producing opposing effects. Example of the year: acetylcholine at muscarinic receptors lowers heart rate while epinephrine at β1 raises it.',
 hook:'They are not competing for the same receptor; they are affecting the physiology in opposite directions.',
 confuse:['chemical-antagonist','competitive-antagonist'],
 quote:'They bind to two different receptors in the same organ and producing opposite effects. They’re not competing for the same receptor, they’re just producing different effects.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~35; transcript 9/28',
 src:'both'},

{id:'surmountable', term:'Surmountable / insurmountable', lecture:'L04', group:'Drug classes',
 def:'Surmountable: an antagonist that the agonist can overcome by increasing its concentration, because the antagonist binds and comes off (competitive = reversible = surmountable). Insurmountable: cannot be overcome by increasing the agonist concentration, because the antagonist binds irreversibly (irreversible = insurmountable = nonequilibrium-competitive = non-competitive).',
 hook:'Different names for the same drug. Surmountable drugs never change the Emax; insurmountable ones lower it.',
 confuse:['competitive-antagonist','irreversible-antagonist'],
 fig:'competitive',
 quote:'One is competitive antagonist, also known as reversible antagonists, also known as surmountable antagonists, different names for the same drug. They bind and they come off.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~36; transcript 9/28',
 src:'both'},

{id:'nam', term:'Negative allosteric modulator (NAM)', lecture:'L04', group:'Drug classes',
 def:'The literature name for an allosteric antagonist: binds reversibly at another site in the receptor and decreases the agonist’s affinity, efficacy or both. The positive allosteric modulator (PAM) is the allosteric agonist and does the opposite.',
 hook:'If you know what the positive one does, the negative is the opposite: half of the memorization.',
 confuse:['allosteric-antagonist','allosteric-agonist','inverse-agonist'],
 fig:'classes',
 quote:'Allosteric Ligands: Agonist; Positive allosteric modulators (PAMs). Antagonist; Negative allosteric modulators (NAMs)',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~37; transcript 9/28',
 src:'both'},

{id:'symmetrical-shift', term:'Symmetrical vs asymmetrical shifts', lecture:'L04', group:'Dose–response curves',
 def:'Symmetrical shifts: successive rightward shifts of equal size produced by increasing doses of an orthosteric competitor (competitive antagonist, inverse agonist, irreversible antagonist), because a tenfold increase in one drug needs a tenfold increase in the other. Asymmetrical shifts: shifts of unequal size produced by allosteric agonists and antagonists, whose binding at the other site does not depend on the agonist.',
 hook:'Asymmetrical plus saturable is how an allosteric drug is recognized on a figure.',
 confuse:['saturability','allosteric'],
 fig:'competitive',
 quote:'if I increase the dose by tenfold, I have to increase the dose of the other by tenfold to outcompete them.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~30–~34, ~38, ~48–~50, ~53–~54; transcript 9/28',
 src:'both'},

{id:'saturability', term:'Saturability (allosteric)', lecture:'L04', group:'Dose–response curves',
 def:'The limit to how far an allosteric drug can shift an agonist’s curve: once all the allosteric sites are occupied, higher doses produce no further shift. Orthosteric competitors, by contrast, keep shifting the curve toward infinity as long as more drug can be added.',
 hook:'An allosteric antagonist cannot bring the response all the way to zero; an irreversible antagonist can.',
 confuse:['symmetrical-shift','irreversible-antagonist'],
 quote:'I can keep giving more and more of my allosteric, and he can’t go more to the left. He has maxed out all that he can do to the system.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~30–~34; transcript 9/28',
 src:'both'},

{id:'spare-receptors', term:'Spare receptors', lecture:'L04', group:'Receptors and signaling',
 def:'Receptors beyond the fraction an agonist needs to occupy to produce its maximal response: agonists do not have to occupy 100% of the receptors to produce the maximal effect. With spare receptors an irreversible antagonist first only shifts the agonist’s curve to the right; the Emax falls once the receptors left are fewer than the agonist needs.',
 hook:'Worked example: agonist needs 10%; blocking 75% or 85% still allows the max response at a higher dose; below 10% available the Emax drops toward zero. Full treatment deferred to 9/29 (slides 57–59).',
 confuse:['irreversible-antagonist','emax'],
 fig:'spare',
 quote:'Our agonists don’t have to occupy 100% of the receptors to produce a response. They only have to occupy a certain percentage of those receptors to do so.',
 cite:'transcript 9/28; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~54, ~56',
 src:'transcript'},

{id:'withdrawal-syndrome', term:'Withdrawal syndrome', lecture:'L04', group:'Drug basics',
 def:'The opposite of what the drug produces, appearing when the drug is stopped: if nicotine relaxes, lowers appetite and raises blood pressure, withdrawal brings irritability, overeating and lower blood pressure. A partial agonist such as varenicline raises the inactive receptors enough to remove the cravings without full activation.',
 hook:'The reason people cannot stop smoking; the reason a partial agonist is used for smoking cessation.',
 confuse:['partial-agonist'],
 fig:'partial',
 quote:'Withdrawal syndrome is the opposite of what the drug produces.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~64–~65; transcript 9/28',
 src:'transcript'}
];

