const GUIDE2_HTML = `
<p class="sub">Cites: <i>ANS</i> = Autonomic Nervous System.pdf; <i>NMJ</i> = PCOL-NMJ_PCOL_2026s_pptx.pdf; <i>Chol</i> = PCOL-Cholinergic-26s.pdf; <i>Adr</i> = PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf; <i>RAAS</i> = PCOL-RAAS_26s.pdf; <i>s.N</i> = slide N; <i>(T) 10/7</i> = his words in the lecture transcript of that date; <i>Poll N</i> = PollEV’s Exam 2.pdf, poll N, keyed by the green highlight on his sheet; <i>Jeopardy 10/8</i> = the review game at the end of the 10/8 lecture (stems from the PollEV screens, keys from his words); <i>Review 10/9</i> = his PollEV questions at the 10/9 review session, which was not recorded, so their keys come from his slides and lectures.</p>
<nav class="guidenav">
<a href="#guide2-scope">What Exam 2 tests</a>
<a href="#guide2-1">1 Autonomic layout</a>
<a href="#guide2-2">2 Nicotinic and NMJ drugs</a>
<a href="#guide2-3">3 Cholinesterase inhibitors</a>
<a href="#guide2-4">4 Muscarinic drugs</a>
<a href="#guide2-5">5 Indirect adrenergic drugs</a>
<a href="#guide2-6">6 α1 and α2 drugs</a>
<a href="#guide2-7">7 β drugs, epinephrine, NE</a>
<a href="#guide2-8">8 Reading his tracings</a>
<a href="#guide2-9">9 Nitric oxide</a>
<a href="#guide2-10">10 RAAS</a>
</nav>

<!-- ===================================================================== -->
<section class="guide" id="guide2-scope">
<h3>What Exam 2 tests, in his words</h3>
<p>Every Exam 2 question starts from the drug list: the mechanism of action (MOA: the receptor or enzyme the drug acts on, and what it does there) and the site of action (SOA: the organs where that receptor sits). From those two he expects the effect, the side effects (adverse drug reactions, ADRs) and the drug–drug interactions (DDIs) to be predicted, not memorized.</p>
<ul>
<li>"Exam 2 is knowing your drugs. The mechanism of actions and the side of actions, and you should be able to predict most of the side effects and uh effects the drug is gonna produce as well as drug-drug interactions." <small>(T) 10/5</small></li>
<li>"So if you know your mechanism of action, you should be able to get at least 40% of the questions on the exam. And if you know the mechanism of action and the side of action, you should be able to get at least 70%" <small>(T) 10/5</small></li>
<li>"So that will be about 20% of your questions on your exam will be about effects ... Another 20% will be side effects and perhaps some drug-drug interactions. And then we're gonna have about 10% of those questions that ... hopefully will challenge you a little bit more." <small>(T) 10/7</small></li>
</ul>
<table class="reftab"><thead><tr><th>On the exam</th><th>Not on the exam</th></tr></thead><tbody>
<tr><td>Tissue tracings: "you're gonna get 1 to 2 of these little graphs on your uh test" <small>(T) 10/6</small>; "they're just one effect" <small>(T) 10/8</small></td><td>Dose–response curves: "on your exam too, there will not be any dose response curves" <small>(T) 10/5</small></td></tr>
<tr><td>One 10/5 poll and one 10/6 poll: "I'm gonna use verbatim, word by word on your exam" <small>(T) 10/6</small></td><td>Uses: "I'm not testing you on the use" <small>(T) 10/5</small>; brand names: "you don't need to know brand names for the exam, just generic" <small>(T) 10/5</small></td></tr>
<tr><td>One 10/7 question: "I'm gonna use one of the questions that we asked today in a different shape or form, but very similar" <small>(T) 10/7</small></td><td>Pathophysiology (COPD, myasthenia gravis): "I'm not quizzing you on it" <small>(T) 10/6</small></td></tr>
<tr><td>Curare reversal: "I have a question similar to this in the exam every year" <small>(T) 10/5</small></td><td>Edrophonium, galantamine, cevimeline, M4 and M5, half-lives of the curare-like drugs <small>(T) 10/5</small></td></tr>
<tr><td>RAAS drug effects on the cascade: "at least 1 to 2 questions" <small>(T) 10/8</small></td><td>β-blocker generations; short- vs long-acting β2 agonists; the steps of the nitric oxide cascade; the Nobel scientists' names <small>(T) 10/7</small></td></tr>
<tr><td>The receptor/G-protein quick table may be written on scratch paper from memory: "You just can't do it from your notes." <small>(T) 10/8</small></td><td>The bronchial-tone Jeopardy tracing: "This is not gonna be on the exam." <small>(T) 10/8</small></td></tr>
</tbody></table>
<p>Below, "10/5 pool", "10/6 pool" and "10/7 pool" mark the polls of that day: he said one poll from each of those days will be on the exam (10/5 and 10/6 word for word, 10/7 in a similar form).</p>
<p class="sub">Sources: (T) 10/5, 10/6, 10/7, 10/8; notes PE2, DL2.</p>
</section>

<!-- ===================================================================== -->
<section class="guide" id="guide2-1">
<h3>1. The autonomic layout and predicting an organ effect</h3>
<p>The autonomic nervous system (ANS) is the involuntary part of the peripheral nervous system. It has two divisions: the parasympathetic nervous system (PNS, "rest and digest", conserves energy) and the sympathetic nervous system (SNS, "fight or flight", spends energy). Each division uses two neurons in series. The first (preganglionic) neuron releases acetylcholine (ACh) onto nicotinic neuronal receptors (Nn) in a ganglion in both divisions. The second (postganglionic) neuron releases ACh onto muscarinic receptors (M1, M2, M3) in the PNS, and norepinephrine (NE) onto adrenergic receptors (α1, α2, β1, β2) in the SNS. A PNS preganglionic fiber contacts about one postganglionic neuron (1:1); an SNS fiber contacts many (1:20), so the SNS can act on many organs at once. Skeletal muscle is not autonomic: the somatic motor nerve releases ACh onto nicotinic muscle receptors (Nm). <small>ANS s.10–13, 23, 29; (T) 9/30, 10/1</small></p>
<p>To predict what a drug does to an organ, work in three steps: which receptor sits in that organ, which G protein (the guanine-nucleotide-binding protein that carries the receptor's signal) that receptor uses, and which direction that G protein pushes. Gs stimulates adenylate cyclase (AC), so cyclic AMP (cAMP) rises. Gi inhibits AC, so cAMP falls; at the heart's M2 it also opens K+ channels, which makes the membrane more negative (hyperpolarization) and slows the rate. Gq activates phospholipase C (PLC), which makes inositol trisphosphate (IP3), which releases Ca++; more Ca++ inside the cell means contraction or excitation. An agonist then produces what the receptor does; an antagonist produces the opposite, and only where that receptor has resting tone to remove. <small>ANS s.3–4, 24, 34; Chol s.6–9; (T) 9/30, 10/5</small></p>
<!--FIG:galpha-->
<table class="reftab"><thead><tr><th>Receptor</th><th>G protein</th><th>Main site (his words)</th><th>Agonist effect</th></tr></thead><tbody>
<tr><td>M1</td><td>Gq: PLC → IP3 → ↑Ca++</td><td>Brain</td><td>Excitation (stimulation)</td></tr>
<tr><td>M2</td><td>Gi: AC ↓ → ↓cAMP</td><td>Heart</td><td>Bradycardia, less force</td></tr>
<tr><td>M3</td><td>Gq</td><td>"Everywhere else": eye, lungs, glands, gut, bladder, vessel endothelium</td><td>DUMBBELSS (diarrhea, urination, miosis, bradycardia, bronchial constriction, emesis, lacrimation, salivation, stimulation of the brain; section 4); vasodilation through nitric oxide</td></tr>
<tr><td>α1</td><td>Gq</td><td>Blood vessels, eye, brain</td><td>Vasoconstriction, pupil dilation (mydriasis)</td></tr>
<tr><td>α2</td><td>Gi</td><td>Presynaptic nerve endings, brain</td><td>Less NE release, sedation</td></tr>
<tr><td>β1</td><td>Gs: AC ↑ → ↑cAMP</td><td>Heart, kidney</td><td>Tachycardia, more force; renin release</td></tr>
<tr><td>β2</td><td>Gs</td><td>Smooth muscle (lungs, vessels); typically not innervated</td><td>Bronchodilation, vasodilation</td></tr>
<tr><td>β3</td><td>Gs</td><td>Bladder smooth muscle</td><td>Bladder relaxation (urine retained)</td></tr>
<tr><td>Nn, Nm</td><td>None: ligand-gated ion channels</td><td>Nn: ganglia, brain, adrenal medulla. Nm: skeletal muscle</td><td>Na+ in, depolarization</td></tr>
</tbody></table>
<p class="sub">His "quick table" (ANS s.4, credited to Andrea Vasquez, Class 2013), with ANS s.13 and (T) 9/30. The slide 4 table gives β1 the heart only; slide 13 and the audio add the kidney: use heart and kidney.</p>
<p><b>Who runs each organ.</b> Most organs have both divisions working in opposition (dual innervation): at the heart, ACh on M2 lowers the rate and NE on β1 raises it, and the division with the predominant tone (the one in control of that organ at rest) wins. The exceptions are the questions he asks. The lungs have PNS innervation only (M3: bronchial constriction); the airway β2 receptors have no sympathetic nerve and are reached by epinephrine released from the adrenal medulla into the blood. The blood vessels and the kidneys have SNS innervation only (α1 constriction; β1 renin release, which leads to angiotensin II, aldosterone and Na+ and water retention). The M3 receptors in vessels sit on the endothelium (the inner cell layer), are not innervated, and dilate through nitric oxide (section 9), not through Gq-driven contraction. Two organs have the divisions cooperating: the salivary glands (a sympathetic fiber releases ACh onto M3, so both divisions cause salivation) and the male sex organ ("point and shoot": PNS erection, SNS ejaculation). In the gastrointestinal (GI) tract the SNS acts through α2 (Gi) on the PNS nerve terminal, cutting ACh release, so sympathetic activity slows the gut. The adrenal medulla is a sympathetic exception too: the preganglionic fiber releases ACh onto a nicotinic receptor and the medulla releases epinephrine into the blood. <small>ANS s.4, 13, 30, 35, 37–47; (T) 9/30, 10/1</small></p>
<p><b>The baroreceptor reflex.</b> Baroreceptors are pressure-sensing ion channels (pressoreceptors) in the wall of the carotid sinus (glossopharyngeal nerve, IX; monitors blood going to the brain) and the aortic arch (vagus nerve, X). Their firing rises with blood pressure (BP), and more firing means more PNS and less SNS activity, so BP falls; less firing means more SNS, so BP rises. On standing, blood pools in the legs, venous return falls, the baroreceptors fire less ("go silent"), and the SNS rises to keep blood flowing to the brain. The same reflex makes the heart race after any drug that drops BP (section 8). A vasodilator blunts the sympathetic squeeze of the vessels that standing needs, so BP can fall on standing (orthostatic hypotension) and the patient can faint or fall: "get up slowly, if you feel a little bit uh, you know, dizzy, if you see black, sit back down and then try and do it again after a few seconds" (10/1; falls are a major risk in the elderly). The slide 52 diagram puts a single down-arrow beside "SNS and PNS"; he said the PNS is shut off and the SNS activated: use his version. Short-term BP control integrates three reflexes, his "love triangle" (slides 48, 53): the baroreflex (stimulated by a rise in BP) is inhibitory and works through the PNS; the chemoreflex (senses a fall in PO2 and a rise in PCO2) and the cardiac sympathetic afferent reflex (CSAR, mechanical or chemical stimulation of the heart) are excitatory and work through the SNS: "So typically the sympathetic is exciting the system through the chemo reflex and the heart function as the parasympathetic is through the bare receptors." The two brain nuclei that integrate them (the nucleus tractus solitarius, NTS, and the paraventricular nucleus, PVN) are not tested: "I'm not testing this on the exam." <small>ANS s.48–53; (T) 10/1</small></p>

<h4>How he asks it</h4>
<div class="poll"><b>"Activation of the SNS is most likely to evoke:"</b> Diarrhea / Bronchial constriction / Salivation / Miosis / Increase in Na+ excretion<br>Key: <b>Salivation</b>. "Remember, both parasympathetic and sympathetic causes salivation, right?" The SNS slows the gut, dilates airways and pupils, and retains Na+. <small>Poll 1; (T) 10/1</small></div>
<div class="poll"><b>"Activation of the cholinergic system will most likely produce which of the following?"</b> Dry mouth / Decrease urination / Diarrhea / Mydrasis / Bronchial dilation<br>Key: <b>Diarrhea</b>, the D of DUMBBELSS; every other option is an antagonist (anti-DUMBBELSS) or SNS effect. <small>Poll 2; (T) 10/1</small></div>
<div class="poll"><b>"Which of the following statements is CORRECT?"</b> Direct release of NE in the lungs causes bronchial constriction / Direct release of Ach in the resistance arteries causes vasoconstriction / SNS is the major autonomic nervous system component in the kidneys / PNS activation causes salivation &amp; SNS activation causes dry mouth<br>Key: <b>SNS is the major autonomic nervous system component in the kidneys</b>. "So the sympathetic nerve system is the major autonomic nerve system in the kidneys and in the blood vessels, right? As the parasympathetic, it is on the lungs." <small>Poll 3; (T) 10/1</small></div>
<div class="poll"><b>"Which of the following statements is CORRECT?"</b> Both PNS and SNS release acetylcholine in the ganglionic synapses / cAMP is a second messenger involved in a number of physiological functions / The autonomic nervous system is involuntary &amp; composed of PNS and SNS / Beta 2 adrenergic receptors are typically not innervated by the SNS / All of the above<br>Key: <b>All of the above</b>; each statement is a line from the slides. <small>Poll 4; (T) 9/30</small></div>
<div class="poll"><b>"Which of the following is CORRECT regarding baroreceptors?"</b> Activation of the baroreceptors causes a decrease in BP / Suppression of the baroreceptors causes an increase in BP / Baroreceptors are pressure ion channels / When one stands up, the baroreceptors decrease firing / All of the above<br>Key: <b>All of the above</b>. His test-taking rule: "If you have at least 2 that you know is right, go for all the above, right?" <small>Poll 5; (T) 10/1</small></div>
<div class="poll"><b>"Activation of alpha 1 receptors in the arteries by an agonist will produce which of the following?"</b> Activation of Gi=&gt;inhibition of AC=&gt;vasodilation / Activation of Gs=&gt;activation of AC=&gt;vasodilation / Activation of Gq=&gt;activation of PLC=&gt;vasoconstriction / Opening of Nm receptors=&gt;Increase in Ca++=&gt;Vasoconstriction / Increase pupil dilation<br>Key: <b>Activation of Gq=&gt;activation of PLC=&gt;vasoconstriction</b>. "If you know that alpha 1 is GQ, you already could eliminate ... A and B"; pupil dilation is an α1 effect, but the stem asks about the arteries. Run 9/30 and again 10/6, so it is in the 10/6 word-for-word pool. <small>Poll 17; (T) 9/30, 10/6</small></div>
<div class="poll"><b>Spoken (9/30):</b> the same question for β1 — "If you know your quick stable, you already got a bunch of free points in your exam." Gs → AC → cAMP → tachycardia. <small>(T) 9/30</small></div>
<div class="poll"><b>"Which of the following drugs Inhibits the Gq pathway?"</b> Losartan / Prazosin / Phenoxybenzamine / Atropine / All the above<br>Key: <b>All the above</b>: losartan blocks AT1 (section 10), prazosin and phenoxybenzamine block α1, atropine blocks M1 and M3 — all Gq. <small>Jeopardy 10/8; (T) 10/8</small></div>
<p><b>His cues.</b> "I can't tell you how many times people missed this question in the exam by just not knowing what type of nicotine receptors they are or what the M and the N stand for." (9/30) · "So if you know which ones are the agonists on your drug list and which ones are the antagonists, you know that the agonist is going to cause the dumbbells. The antagonists cause what? Anti dumbbells." (9/30) · "The lungs, only parasympathetic, the blood vessels in the kidney, only sympathetic, OK? Those are the only kind of questions you're gonna get that actually gonna be right if I ask you." (10/1) · "meiosis is the smaller name. Mydrisis is the longer word" (10/1): miosis = small pupil. · "So a way for you to remember that in the exam is just point and shoot" (10/1).</p>
<h4>Traps</h4>
<ul>
<li>"SNS causes dry mouth": both divisions cause salivation (Poll 1, Poll 3).</li>
<li>NE from a nerve opening the airways: no sympathetic nerves reach airway β2; adrenal epinephrine does.</li>
<li>Gq at vascular M3 read as constriction: the endothelial M3 dilates through nitric oxide.</li>
<li>More baroreceptor firing read as more SNS: firing and SNS activity move in opposite directions.</li>
<li>Nn and Nm swapped: N<sub>n</sub> = neuronal (ganglia, brain), N<sub>m</sub> = muscle.</li>
</ul>
<h4>Distinctions</h4>
<table class="reftab"><thead><tr><th>Looks the same</th><th>The one thing to look at</th><th>Answer</th></tr></thead><tbody>
<tr><td>Lungs vs blood vessels and kidneys</td><td>Which division innervates them</td><td>Lungs: PNS only. Vessels, kidneys: SNS only</td></tr>
<tr><td>M3 vs α1 in a blood vessel (both Gq)</td><td>Endothelium or smooth muscle</td><td>Endothelial M3: dilation (nitric oxide). Smooth-muscle α1: constriction</td></tr>
<tr><td>Innervated α1, α2, β1 vs β2</td><td>How NE or epinephrine reaches it</td><td>β2: circulating adrenal epinephrine, not a nerve</td></tr>
<tr><td>Opposition vs cooperation</td><td>The organ</td><td>Salivary glands, male sex organ: both divisions together</td></tr>
<tr><td>Carotid sinus vs aortic arch</td><td>Nerve</td><td>Carotid sinus: IX. Aortic arch: X</td></tr>
</tbody></table>
<p class="sub">Sources: ANS s.3–4, 10–13, 21–53; Chol s.6–9; (T) 9/30, 10/1, 10/6, 10/8; Polls 1–5, 17; Jeopardy 10/8; notes L07.</p>
</section>

<!-- ===================================================================== -->
<section class="guide" id="guide2-2">
<h3>2. Nicotinic receptors and the NMJ drugs</h3>
<p>Nicotinic receptors are ligand-gated ion channels: five protein subunits around a pore; when ACh binds both α subunits the channel opens and Na+ flows in. The neuronal type (Nn) is built from α and β subunits only and sits in the brain (the α4/β2 combination, the one he requires) and in the autonomic ganglia of both divisions, including the adrenal medulla. The muscle type (Nm) has α, β, γ, δ and ε subunits and sits at the neuromuscular junction (NMJ), the synapse between a motor nerve and a skeletal muscle fiber. <small>NMJ s.4, 6, 11; (T) 10/1, 10/5</small></p>
<p>At the NMJ, ACh is released from vesicles, binds Nm, Na+ enters, the end plate (the patch of muscle membrane under the nerve ending that carries the Nm receptors) depolarizes and the muscle contracts. The enzyme acetylcholinesterase (AChE) then splits ACh into choline and acetate, the channel closes and the end plate repolarizes ("re-primes") so it can fire again. Drugs act at two targets: the Nm receptor itself (direct) and AChE (indirect, section 3). His rule for the exam: "if I give an agonist, I can get constriction [contraction], and if I give an antagonist, I get relaxation, paralysis" — with succinylcholine as the agonist that also paralyzes. <small>NMJ s.12–18; (T) 10/1</small></p>
<p><b>Varenicline</b> is a high-affinity partial agonist (activates the receptor, but less than the full agonist) at the α4/β2 Nn receptor in the brain. It competes with nicotine for that receptor, reduces craving and withdrawal, and blunts nicotine's effect. Its site of action is the central nervous system (CNS), so its side effects are nausea and vomiting, headache, insomnia and depression; he added flatulence on 10/5. He said not to memorize the nausea percentages and will not ask its use. <small>NMJ s.7–9; (T) 10/1, 10/5</small></p>
<p><b>Succinylcholine</b> is a depolarizing Nm agonist (structurally two ACh molecules joined). It opens every Nm channel at once and is not broken down effectively, so the end plate stays depolarized and cannot re-prime: phase I, the depolarizing block, and the muscle is paralyzed. With prolonged infusion succinylcholine lodges inside the channel pore and stops Na+/K+ movement: phase II, the channel block. If it stays long enough it reaches the Nn receptors of the ganglia, which gives hypertension and arrhythmias. Its other ADRs are hyperkalemia (muscle cells lose K+; avoid in renally impaired or dehydrated patients), muscle pain (myalgia, from unsynchronized contractions) and hyperthermia. Its DDI: with inhaled anesthetics such as halothane it causes malignant hyperthermia (abnormal Ca++ release from skeletal-muscle stores), treated with dantrolene, a ryanodine-receptor antagonist. <small>NMJ s.19–26; (T) 10/5</small></p>
<p><b>Curare-like drugs</b> (non-depolarizing) are every drug with "cur" in the name: tubocurarine (the prototype), rocuronium, vecuronium, pancuronium, and the related mivacurium and atracurium. All are competitive, reversible Nm antagonists: they occupy both α subunits so ACh cannot open the channel, and the muscle is paralyzed — eyes, jaw and larynx first, then the limbs and trunk, the diaphragm last. Because they are competitive, enough ACh can outcompete them, which is how they are reversed (section 3). They do not cross the blood–brain barrier (BBB), so they have no CNS effect; the dangerous effect is paralysis of the diaphragm. Pancuronium (tachycardia) and atracurium (histamine release: bronchial spasm, marked hypotension) differ in side effects, which he did not set for the exam. <small>NMJ s.19, 27–32; (T) 10/1, 10/5</small></p>
<p><b>Botulinum toxin</b> (Botox) acts before the receptor: it is an enzyme (endopeptidase) that cleaves the SNARE proteins a vesicle needs to fuse, so ACh cannot be released and the muscle relaxes. <small>NMJ s.46–50; (T) 10/5</small></p>

<h4>How he asks it</h4>
<div class="poll"><b>"Which of the following is CORRECT about varenicline?"</b> Is a partial agonist to the alpha4/beta2 nicotinic receptor / It may cause depression in some patients / It compete with nicotine for the Nn receptors in the brain / It decreases withdraw syndrome in pts trying to stop smoking / All of the above<br>Key: <b>All of the above</b>; he affirmed each statement: "we know it's a partial agonist to the alpha 4 beta 2 nicotinic NN receptor. That's the must know information" <small>Poll 6; (T) 10/1</small></div>
<div class="poll"><b>"Which of the following drugs causes paralysis by antagonizing the binding of ACh to the Nm receptor?"</b> Varenicline / Succinycholine / Rocuronium / Norepinephrine<br>Key: <b>Rocuronium</b>. Succinylcholine also paralyzes, but as an agonist: "Why is not B as in boy? ... They're both agonists." 10/5 word-for-word pool; he announced a bonus at this poll. <small>Poll 7; (T) 10/5</small></div>
<div class="poll"><b>"If a patient is administered rocuronium, which of the following is most likely to occur?"</b> diarrhea / increase urination / hypertension / paralysis / bronchial constriction<br>Key: <b>paralysis</b>. An organ needs its own receptor: the gut is muscarinic, the bladder muscarinic or adrenergic, the vessels adrenergic. On histamine release: "you may have two possible right answers, but one is 100% of the time because that's what we use the drug for." 10/5 pool. <small>Poll 8; (T) 10/5</small></div>
<div class="poll"><b>"Which of the following decreases the release of Ach from pre-synaptic neurons?"</b> Varenicline / Succinylcholine / Rocuronium / Rivastigmine / Botox<br>Key: <b>Botox</b>; the other four act at a receptor or the enzyme. "So the only one that decreases the release of acetylcholine would be the Botox toxin." 10/5 pool. <small>Poll 11; (T) 10/5</small></div>
<div class="poll"><b>"Which of the following drugs is a partial agonist to the alpha4/beta2 Nn receptors?"</b> Atropine / Varenicline / Rocuronium / Dobutamine / Clonidine<br>Key: <b>Varenicline</b>; atropine is muscarinic, rocuronium is at Nm, dobutamine at β1, clonidine at α2. <small>Review 10/9; NMJ s.7</small></div>
<div class="poll"><b>Spoken (10/5):</b> "Where are the two locations for the NN receptors?" — "The brain and. On the ganglia of the autonomic nerve system, right?" <small>(T) 10/5</small></div>
<p><b>His cues.</b> "the two things that students get in trouble every year is not just about the mechanism of action of these drugs, it's remembering where the receptors are located." (10/1) · "the one combination that I need you to know is gonna be the alpha 4 beta 2 combination" (10/1) · "any drug that has the CUR in the middle ... that's a karate-like drug" (10/1; "karate" = curare in the transcript) · "all I need you to know is that any karate-like drug is what? A competitive, reversible NM antagonist, and by blocking the NM, what are you gonna get? Paralysis, right?" (10/5) · "You must know that a sucycholine is an agonist that depolarize or open those ion channels." (10/5) · Succinylcholine's uses are "FYI" (10/5).</p>
<h4>Traps</h4>
<ul>
<li>Succinylcholine picked for "antagonizing" Nm: it is the agonist; rocuronium is the antagonist (Poll 7).</li>
<li>Hypertension or bronchial constriction picked for rocuronium: those organs need adrenergic or muscarinic receptors (Poll 8).</li>
<li>Botox placed at the receptor: it stops release before the synapse (Poll 11).</li>
<li>Varenicline placed at Nm or called a full agonist: partial agonist, α4/β2 Nn, brain.</li>
<li>Assuming an agonist must contract: succinylcholine paralyzes by holding the end plate depolarized.</li>
</ul>
<h4>Distinctions</h4>
<table class="reftab"><thead><tr><th>Looks the same</th><th>The one thing to look at</th><th>Answer</th></tr></thead><tbody>
<tr><td>Nn vs Nm</td><td>Location and subunits</td><td>Nn: brain (α4/β2), ganglia. Nm: skeletal muscle (α β γ δ ε)</td></tr>
<tr><td>Succinylcholine vs rocuronium (both paralyze)</td><td>Does it open the channel?</td><td>Opens it: succinylcholine (agonist). Blocks ACh: rocuronium (antagonist)</td></tr>
<tr><td>Phase I vs phase II</td><td>Where succinylcholine sits</td><td>On the receptor, end plate stuck depolarized: I. In the pore: II</td></tr>
<tr><td>Botox vs curare-like vs succinylcholine</td><td>Before or at the receptor</td><td>Botox: presynaptic release. The other two: the Nm receptor</td></tr>
</tbody></table>
<p class="sub">Sources: NMJ s.4–32, 46–50; (T) 10/1, 10/5, 10/6; Polls 6–8, 11; Review 10/9; notes L08.</p>
</section>

<!-- ===================================================================== -->
<section class="guide" id="guide2-3">
<h3>3. Cholinesterase inhibitors and organophosphates</h3>
<p>Acetylcholinesterase (AChE) is the enzyme that breaks down ACh; he also calls it pseudocholinesterase and treats the names as one. A cholinesterase inhibitor binds the enzyme's active site, so ACh is not broken down and builds up "anywhere ACh is released": at muscarinic sites (the DUMBBELSS of section 4), at the NMJ (stronger contraction) and in the ganglia. ACh therefore becomes more potent: "Because I'm not breaking it down, I have more acetylcholine available to bind to the receptor for a longer period of time." The slides call these drugs indirect antagonists because they act somewhere other than the receptor, even though they increase ACh's effect. The name cue is "-stigmine". <small>NMJ s.10–12, 33–37; (T) 10/1, 10/5</small></p>
<p>The reversible inhibitors differ in where they go. <b>Physostigmine</b> is a tertiary amine: it crosses the blood–brain barrier (BBB), acts centrally and peripherally, and is the slide's drug of choice for poisoning by an antimuscarinic such as atropine (Katzung discourages that use; the slide and his words are the exam answer). <b>Neostigmine</b> and <b>pyridostigmine</b> are quaternary amines and do not cross the BBB, so they act only in the periphery: myasthenia gravis (a disease that removes Nm receptors) and reversal of curare-like drugs. For myasthenia gravis he picks neostigmine over physostigmine, which only adds central side effects ("why would you wanna make them they have vomiting and nausea"). <b>Donepezil</b> and <b>rivastigmine</b> are lipophilic, cross the BBB and are used in Alzheimer's disease (they slow the decline but do not reverse it); their ADRs are the DUMBBELSS, with GI and CNS effects (insomnia, agitation, dizziness, falling). A patient with both myasthenia gravis and Alzheimer's disease gets rivastigmine, because it acts in both places. <small>NMJ s.38–41; (T) 10/5</small></p>
<p><b>Reversing curare.</b> Curare-like drugs are competitive, so more ACh at the NMJ outcompetes them. Neostigmine raises ACh at the skeletal-muscle synapse without entering the brain, which is the answer to his yearly question. A second paralytic (succinylcholine, rocuronium) would deepen the paralysis. <small>NMJ s.29, 39; (T) 10/5</small></p>
<p><b>Organophosphates</b> bind the enzyme covalently (they phosphorylate it), a very stable, slow bond: irreversible. They are insecticides (malathion, parathion) and nerve gases (sarin, soman, tabun), highly lipid soluble and absorbed through skin, lungs, gut and conjunctiva. Poisoning gives massive DUMBBELSS, stimulation of the sympathetic ganglia (the slide lists tachycardia and hypertension), stimulation of the NMJ (cramps, weakness, then respiratory paralysis) and CNS effects (agitation, confusion, seizures). On 10/5 he listed bradycardia among the organophosphate DUMBBELSS while the slide lists tachycardia under the ganglia; for a heart-rate question use the slide list. Treatment has two parts: pralidoxime (2-PAM) removes the phosphate and reactivates the enzyme, given early (he said within about an hour of exposure); atropine, a reversible muscarinic antagonist, blocks the muscarinic DUMBBELSS but cannot fix the enzyme. <b>Echothiophate</b> is an organophosphate given as eye drops: more ACh on M3 of the ciliary muscle opens the outflow of aqueous humor and lowers intraocular pressure (glaucoma); ADRs miosis, blurred vision, lacrimation, stinging. <small>NMJ s.42–45; Chol s.20–23; (T) 10/5</small></p>

<h4>How he asks it</h4>
<div class="poll"><b>"While hunting, your friend had an accident and pocked himself with an arrow tip (contain curare). Which of these would you have to do to reverse the effects?"</b> Succinylcholine / Rocuronium / Neostigmine / Varenicline / Tickle your friend<br>Key: <b>Neostigmine</b>. "So neo stigamine, which does not cross the blood brain barrier but can increase the levels of acetylcholine in the synapse of your skeletal muscle, would give you a better chance of outcompeting karate" — "I have a question similar to this in the exam every year, and about 30% of the class misses it." 10/5 pool. <small>Poll 10; (T) 10/5</small></div>
<div class="poll"><b>"Rivastigmine is most likely to produce:"</b> Constipation / Tachycardia / Salivation / Decrease urination / Pupil dilation<br>Key: <b>Salivation</b>, a DUMBBELSS effect; the four others are anti-DUMBBELSS. 10/5 pool. <small>Poll 9; (T) 10/5</small></div>
<div class="poll"><b>Spoken (10/5):</b> "Which one would you pick for your patient if the patient is a family member? Physostigamine or say neostigamine." — "Hopefully the second one, right?" And for myasthenia gravis plus Alzheimer's: "I'll pick the river, right? Because you're targeting two things." (rivastigmine) <small>(T) 10/5</small></div>
<div class="poll"><b>"Patient is going to be tested for MS and IV infused with endrophonium. During the procedure, the patient may experience certain ADRs. Which of the following drugs would decrease the ADR produced by endrophonium?"</b> Pilocarpine / Prazosin / Metoprolol / Atropine / Neostigmine<br>Key: <b>Atropine</b>: "acetocho estase enzyme antagonist or cholinergic agonist is going to cause the dumbbells, so you need an antagonist that calls the anti-dumbbells." Aloud he said myasthenia gravis for "MS". Edrophonium appears only as a cholinesterase inhibitor here. <small>Jeopardy 10/8; (T) 10/8</small></div>
<div class="poll"><b>"Your patient has been taking Rivastigmine (Exelon) for his Alzheimer's and he is most likely complaining of which?"</b> Salivation / Need to go urinate / Nausea / Diarrhea / All the above<br>Key: <b>All the above</b>: "Remember to produce the dumbbells, right?" <small>Jeopardy 10/8; (T) 10/8</small></div>
<div class="poll"><b>"Donepezil"</b> Selective reversible muscarinic agonist / Acetylcholinesterase enzyme inhibitor / Non-selective irreversible nicotinic antagonist / Selective reversible beta 1 antagonist / Selective reversible alpha1 antagonist<br>Key: <b>Acetylcholinesterase enzyme inhibitor</b>. <small>Review 10/9; NMJ s.40</small></div>
<p><b>His cues.</b> "anytime you see a drug that has a stickyine in it, you know it has to do what with the pseudocholinesterase enzyme." (10/5) · "For our exam purpose, I only need you to know rivastigamine and donepezil" (10/5) · Edrophonium: "So for our purpose on the exam, I'm not too worried about androfomia" (10/5).</p>
<h4>Traps</h4>
<ul>
<li>Reversing curare with succinylcholine or rocuronium: both add paralysis; neostigmine adds ACh (Poll 10).</li>
<li>Physostigmine for myasthenia gravis: it enters the brain for nothing; neostigmine stays peripheral.</li>
<li>Assuming every -stigmine reaches the brain: neostigmine and pyridostigmine do not.</li>
<li>Calling echothiophate reversible because it is a therapeutic drug: it is an organophosphate (covalent).</li>
<li>Atropine as the enzyme reactivator: pralidoxime reactivates; atropine only blocks muscarinic receptors.</li>
</ul>
<h4>Distinctions</h4>
<table class="reftab"><thead><tr><th>Looks the same</th><th>The one thing to look at</th><th>Answer</th></tr></thead><tbody>
<tr><td>Physostigmine vs neostigmine</td><td>Crosses the BBB?</td><td>Physostigmine yes (atropine poisoning). Neostigmine no (myasthenia gravis, curare)</td></tr>
<tr><td>Neostigmine vs rivastigmine</td><td>Periphery only or everywhere</td><td>Periphery: neostigmine. Brain and periphery: rivastigmine</td></tr>
<tr><td>Reversible inhibitors vs organophosphates</td><td>Bond to the enzyme</td><td>Covalent, irreversible: organophosphates, echothiophate</td></tr>
<tr><td>Pralidoxime vs atropine in poisoning</td><td>Enzyme or receptor</td><td>Pralidoxime: reactivates AChE. Atropine: blocks muscarinic DUMBBELSS</td></tr>
</tbody></table>
<p class="sub">Sources: NMJ s.10–12, 29, 33–45; Chol s.20–23; (T) 10/1, 10/5, 10/8; Polls 9, 10; Jeopardy 10/8; Review 10/9; notes L08, L09, PE2.</p>
</section>

<!-- ===================================================================== -->
<section class="guide" id="guide2-4">
<h3>4. Muscarinic agonists and antagonists</h3>
<p>Muscarinic receptors are G protein–coupled receptors (GPCRs), not ion channels. His summary: "M1 in the brain, M2 in the heart, M3, everywhere else". M1 (Gq) excites the brain. M2 (Gi) on the sinoatrial (SA) and atrioventricular (AV) nodes lowers cAMP and opens K+ channels, so the heart slows. M3 (Gq, ↑Ca++) contracts the smooth muscle of the gut, bladder, airways and pupil, drives the glands, and on the vessel endothelium releases nitric oxide (dilation, a fall in BP). Most of these organs run on a predominant PNS tone. M4 and M5 have no drugs and are not tested. <small>Chol s.5–10, 13; (T) 10/5, 10/6</small></p>
<p><b>Agonists produce DUMBBELSS</b>: Diarrhea, Urination, Miosis (small pupil), Bradycardia, Bronchial constriction, Emesis (vomiting), Lacrimation, Salivation, Stimulation of the CNS — plus hypotension from endothelial M3. They are contraindicated in asthma, because they constrict the bronchi further. ACh is the only one that binds both nicotinic and muscarinic receptors. Methacholine, carbachol and bethanechol (the "chol" in the name marks a cholinergic agonist) and pilocarpine (the one without "chol" he requires) are non-selective (M1, M2, M3), reversible and muscarinic only; for the exam they are treated as having equal efficacy and affinity. <small>ANS s.24, 27; Chol s.11–15; (T) 9/30, 10/5</small></p>
<p><b>Antagonists produce anti-DUMBBELSS</b>: constipation, urinary retention, mydriasis (large pupil, because the SNS dilator is left unopposed), tachycardia (the resting PNS tone at M2 is removed), bronchial dilation, dry mouth, no tears or sweat, and sedation; at high doses hallucinations, restlessness and coma. Atropine's toxicity on the slide: "dry as a bone, hot as a pistol, red as a beet, blind as a bat, mad as a hatter". All are reversible (competitive) and all block M3; most are non-selective. The name cue is "trop": atropine, ipratropium, tiotropium, trospium, benztropine, tropicamide. <small>Chol s.17–19, 26, 30, 32; (T) 10/5, 10/6</small></p>
<ul>
<li><b>Atropine</b> (natural alkaloid; M1, M2, M3): severe bradycardia, muscarinic-agonist overdose, organophosphate poisoning. <b>Scopolamine</b>: also blocks histamine and serotonin receptors and enters the CNS faster (drowsiness). <small>Chol s.17–20, 24</small></li>
<li><b>Benztropine</b>: more selective for brain M1 than atropine (Parkinson's disease), so fewer anti-DUMBBELSS elsewhere. <b>Tropicamide</b>: blocks pupil M3, SNS unopposed, pupil dilates. <small>Chol s.25–26; (T) 10/5</small></li>
<li><b>Inhaled</b>: ipratropium (short acting, 3–4 times a day) and tiotropium (long acting, once a day), aclidinium and umeclidinium (high M3 affinity, slow dissociation). Inhaled with low bioavailability, they stay in the lungs, where M3 is the only autonomic control, so the bronchi dilate with few systemic effects. <small>Chol s.27–28; (T) 10/5</small></li>
<li><b>Bladder</b> (his three: oxybutynin, trospium, solifenacin): block bladder M3 and reduce urgency, frequency and leakage. All can cause anti-DUMBBELSS, mainly dry mouth and constipation. Oxybutynin is the least selective (M1 and M3, so sedation); solifenacin is the most M3-selective and causes the fewest at therapeutic doses, but "If I give enough of VESIcare, I'm gonna get all the anti-dumbbells." Trospium's rank was not set. The other drug that relaxes the bladder is the β3 agonist mirabegron (section 7). <small>Chol s.29–30; (T) 10/5, 10/7</small></li>
</ul>

<h4>How he asks it</h4>
<div class="poll"><b>"If one overdose on a cholinergic agonist, which of the symptoms is most likely to occur?"</b> Diarrhea / Can't urinate / Miosis / Bradycardia / All of the above<br>Key: <b>All of the above</b>, except "Can't urinate": "it would be all the above with the exception of uh B as in boy, OK?" The agonist squeezes the bladder; the patient urinates more. Last year's version asked which would NOT occur. 10/5 pool. <small>Poll 12; (T) 10/5</small></div>
<div class="poll"><b>"Carbachol is most likely to cause:"</b> Dry mouth / Bradycardia / Constipation / Bronchial dilation / Decrease in vomiting<br>Key: <b>Bradycardia</b> (M2); every other option is anti-DUMBBELSS. 10/5 pool. <small>Poll 13; (T) 10/5</small></div>
<div class="poll"><b>"Atropine:"</b> Activates the M1, M2, and M3 receptors / Block the ability of NE to bind and activate its receptors / Competitively antagonize the activations of muscarinic receptors / Causes severe diarrhea as an ADR / Causes paralysis by blocking Nm receptors<br>Key: <b>Competitively antagonize the activations of muscarinic receptors</b>. A nicotinic option would be false: "these drugs only have affinity for what? Muscarinic receptors". 10/5 pool. <small>Poll 14; (T) 10/5</small></div>
<div class="poll"><b>"Trospium is most likely to:"</b> Cause bronchial constriction / Evoke salivation / Decrease urination / Increase GI motility / Excitation<br>Key: <b>Decrease urination</b>: an M3 antagonist relaxes the bladder; the others are agonist effects. 10/6 pool. <small>Poll 15; (T) 10/6</small></div>
<div class="poll"><b>"If your patient is having severe bradycardia, which of the following drugs would be most beneficial?"</b> Carbachol / Succinylcholine / Atropine / Rocuronium / Neostigmine<br>Key: <b>Atropine</b>, which removes M2 tone. Carbachol and neostigmine slow the heart further ("You're gonna stop their heart"); the two paralytics act at Nm. 10/6 pool. <small>Poll 16; (T) 10/6</small></div>
<div class="poll"><b>"Carbachol will evoke which of the following schemes in the GI?"</b> Gs =&gt; increase AC =&gt; decrease contraction / Gq =&gt; increase PLC =&gt; Increase motility / Gi =&gt; decrease AC =&gt; Decrease cAMP / Nm =&gt; Na+ entry into the cell =&gt; Open voltage gated Ca++ channels<br>Key: <b>Gq =&gt; increase PLC =&gt; Increase motility</b>: gut M3. <small>Review 10/9; Chol s.6, 9, 11–12</small></div>
<div class="poll"><b>"Which of the following would be the least likely side effect of trospium?"</b> Dry mouth / Dilated pupils / Hallucination / Constipation / Increase urination<br>Key: <b>Increase urination</b>, an agonist effect; the other four are anti-DUMBBELSS. <small>Review 10/9; Chol s.18–19, 29–30</small></div>
<div class="poll"><b>"Tiotropium"</b> Selective nicotinic receptor antagonist / Acetylcholinesterase enzyme inhibitor / Non-selective muscarinic agonist / Non-selective reversible muscarinic antagonist / Selective alpha 2 antagonist<br>Key: <b>Non-selective reversible muscarinic antagonist</b> (a "trop"). Slide 28 lists tiotropium as M1 and M3; he called it "less selective"; this is the only antagonist option. <small>Review 10/9; Chol s.17, 28; (T) 10/5</small></div>
<p><b>His cues.</b> "the biggest misconception that students have and questions they miss in the exam is that they think that our muscarinic agonists can also bind to the nicotinic receptors, and they don't." (10/5) · "They're all reversible, so they're all competitive ... So if you know one, you should know them all." (10/5) · "I'm gonna expect you to know pilocarpine as one of the two" (10/5) · Bladder: "those are gonna be the three that are gonna be responsible for me on the exam." (10/5) · "any drug that has a trope in it ... is gonna be what? an antagonist like atropine" (10/5).</p>
<h4>Traps</h4>
<ul>
<li>"Can't urinate" as an agonist effect: the agonist increases urination (Poll 12).</li>
<li>Atropine blocking nicotinic receptors or NE: it binds muscarinic receptors only (Poll 14).</li>
<li>Neostigmine or carbachol for bradycardia: both add ACh action at M2 (Poll 16).</li>
<li>Solifenacin "cannot" cause anti-DUMBBELSS: fewer at therapeutic doses, all of them at high doses.</li>
<li>A "chol" drug read as an antagonist, or a "trop" drug as an agonist.</li>
</ul>
<h4>Distinctions</h4>
<table class="reftab"><thead><tr><th>Looks the same</th><th>The one thing to look at</th><th>Answer</th></tr></thead><tbody>
<tr><td>ACh vs the other muscarinic agonists</td><td>Nicotinic binding</td><td>Only ACh binds Nn and Nm too</td></tr>
<tr><td>Oxybutynin vs solifenacin</td><td>Selectivity</td><td>Oxybutynin: M1 + M3, most side effects. Solifenacin: most M3-selective</td></tr>
<tr><td>Ipratropium vs tiotropium</td><td>Duration</td><td>Ipratropium short (3–4×/day). Tiotropium long (1×/day)</td></tr>
<tr><td>Atropine vs scopolamine</td><td>Other receptors, CNS entry</td><td>Scopolamine also histamine, serotonin; enters CNS faster</td></tr>
<tr><td>Bethanechol vs oxybutynin at the bladder</td><td>Agonist or antagonist</td><td>Bethanechol: more urination. Oxybutynin: less</td></tr>
</tbody></table>
<p class="sub">Sources: ANS s.24, 27; Chol s.5–32; (T) 9/30, 10/5, 10/6; Polls 12–16; Review 10/9; notes L09, PE2.</p>
</section>

<!-- ===================================================================== -->
<section class="guide" id="guide2-5">
<h3>5. Indirect-acting adrenergic drugs</h3>
<p>In the sympathetic nerve ending, tyrosine is made into L-dopa, then dopamine, then norepinephrine (NE), which is stored in vesicles and released onto postsynaptic α1 and β receptors and onto the presynaptic α2 receptor, which brakes further release. NE is then removed in two ways: the NE transporter (NET) takes it back into the nerve and recycles it into the vesicle, and the enzymes monoamine oxidase (MAO) and catechol-O-methyltransferase (COMT) break it down to inactive metabolites. <small>Adr s.8</small></p>
<p>Indirect-acting drugs never bind the adrenergic receptor; they raise the amount of NE at the synapse, so NE does more of what it already does: faster heart, vasoconstriction and higher BP, CNS excitation. There are three ways to do this, and one drug class for each. <small>Adr s.9–15; (T) 10/6</small></p>
<ul>
<li><b>Block reuptake: cocaine.</b> A complete NET antagonist ("cocaine is a 100% inhibitor of the net process"). More NE at the heart, vessels and CNS: tachycardia, intense vasoconstriction (the nosebleeds of users), excitation. <small>Adr s.10; (T) 10/6</small></li>
<li><b>Release NE: the amphetamines</b> (dextroamphetamine, amphetamine, lisdexamfetamine, methylphenidate, dexmethylphenidate). Primary action: stimulate presynaptic release of NE, dopamine (DA) and serotonin (5-HT). Secondary, moderate action: decrease reuptake and block MAO. Effects: better mood, focus and alertness, more energy, less sleep and appetite, faster breathing; tremor and sweating; higher heart rate and BP; hyperthermia. <small>Adr s.11–12; (T) 10/6</small></li>
<li><b>Block breakdown: MAO inhibitors.</b> MAO-A is in the brain, liver and gut (breaks down NE and DA); MAO-B is in the brain's striatum (DA). Phenelzine blocks MAO-A and MAO-B irreversibly; because gut MAO-A is blocked, dietary tyramine from fermented foods (cheese, bread, wine) is not broken down (slide 15: "inability to process tyramine"), and tyramine releases NE from the nerve ending (Katzung Ch 9): a hypertensive crisis, the "cheese effect". Selegiline at low doses blocks MAO-B selectively and irreversibly, so there is no cheese effect. <small>Adr s.13–15; (T) 10/6</small></li>
<li><b>Mixed: ephedrine</b> is a direct agonist at α1, α2, β1 and β2 and also a releasing agent. <small>Adr s.9; (T) 10/6</small></li>
</ul>

<h4>How he asks it</h4>
<div class="poll"><b>"Which of the following drugs increase the potency of NE by blocking the NET?"</b> Amphetamine / Selegiline / Cocaine / Atropine / Rivastigmine<br>Key: <b>Cocaine</b>. "So amphetamine is a weaker inhibitor of the net, but its primary ... mechanism of action is what? Increase the release of norepinephrine". On the exam he would swap amphetamine: "I'll pick something else other than amphetamine". 10/6 pool; he introduced it with "if you get the bonus today, you're gonna go already with two questions on the exam that you know what they are." <small>Poll 19; (T) 10/6</small></div>
<div class="poll"><b>In other polls these drugs are the distractors that raise BP:</b> cocaine in "Which of the following drugs is most likely to decrease blood pressure?" (Poll 21) and as drug B on the NE tracing (Poll 28, section 8); selegiline and dextroamphetamine in "Which of these drugs is most likely to produce vasodilation" (Poll 22). <small>Polls 21, 22, 28</small></div>
<p><b>His cues.</b> "basic knowledge, foundational knowledge, mechanism of action, those, you should be able to get all of them on the exam, hopefully. If you know your drug list. That's 40 points on your exam" (10/6). Cocaine's use with lidocaine was taught but uses are not tested.</p>
<h4>Traps</h4>
<ul>
<li>Amphetamine picked as the NET blocker: its main action is release (Poll 19).</li>
<li>Giving selegiline the cheese effect: only the non-selective phenelzine has it.</li>
<li>Calling MAO the recycling route: the NET recycles; MAO and COMT break down.</li>
<li>Calling either MAO inhibitor reversible: both are irreversible.</li>
</ul>
<h4>Distinctions</h4>
<table class="reftab"><thead><tr><th>Looks the same</th><th>The one thing to look at</th><th>Answer</th></tr></thead><tbody>
<tr><td>Cocaine vs amphetamine</td><td>Primary mechanism</td><td>Cocaine: blocks the NET. Amphetamine: releases NE, DA, 5-HT</td></tr>
<tr><td>Phenelzine vs selegiline</td><td>Which MAO</td><td>Phenelzine: A and B, cheese effect. Selegiline: B only, none</td></tr>
<tr><td>Indirect vs direct agonist</td><td>Does it bind the receptor?</td><td>Indirect: no, raises NE. Ephedrine: both</td></tr>
</tbody></table>
<p class="sub">Sources: Adr s.8–15; (T) 10/6; Poll 19; notes L10.</p>
</section>

<!-- ===================================================================== -->
<section class="guide" id="guide2-6">
<h3>6. α1 and α2 drugs</h3>
<p><b>The pressure formula.</b> Mean arterial pressure (MAP) = cardiac output (CO, which is heart rate × stroke volume) × total peripheral resistance (TPR). Preload is the blood in the ventricle at the end of filling (diastole), set by venous return; afterload is the pressure the ventricle must overcome to open its valve (he equates it with systolic pressure), set by the resistance arteries. His goal for each adrenergic drug: "predict what component of the [MAP] formula is being affected by our drugs". <small>Adr s.4–7; (T) 10/6</small></p>
<p><b>α1</b> is Gq: PLC → IP3 → ↑Ca++ → smooth-muscle contraction. Its sites, in the slide's phrase "I see &amp; smell bloody urine": the eye (radial muscle of the pupil: dilation), the nose (its blood vessels), the blood vessels (arteries set afterload, veins set preload; the SNS is their predominant tone) and the urethra; the slide's text also lists the blood vessels of the sinus and prostate. <b>Phenylephrine</b>, a selective α1 agonist, constricts: nasal decongestion, pupil dilation, higher preload and afterload. ADRs: burning, blurred vision, rebound congestion (not used for more than 3 days), caution in hypertension. <b>Oxymetazoline</b> is a non-selective α1 and α2 agonist decongestant. <small>Adr s.17–19; (T) 10/6</small></p>
<p><b>Prazosin</b> and the other "-osins" (terazosin, doxazosin, tamsulosin and more) are reversible, selective α1 antagonists (about 1000-fold for α1). They dilate arteries and veins, lowering TPR, afterload and preload. Their ADRs follow from the sites: veins dilate, blood pools on standing, and the first dose gives orthostatic hypotension and fainting (syncope, 30–90 minutes after the dose); arteries dilate, BP falls and the baroreceptor reflex gives reflex tachycardia (palpitations); also dizziness, blurred vision, headache, and worse nasal congestion. <b>Phenoxybenzamine</b> blocks α1 and α2 irreversibly (covalent bond). Blocking presynaptic α2 releases more NE, but NE cannot outcompete a covalent block, so phenoxybenzamine drops BP more than prazosin. Its ADRs: orthostatic hypotension, reflex tachycardia and arrhythmias, miosis, and GI stimulation, because the α2 brake on the PNS terminal in the gut is removed and more ACh reaches M3. <small>Adr s.27–30, 34–38; (T) 10/6, 10/7</small></p>
<p><b>α2</b> is Gi: AC ↓ → ↓cAMP, inhibitory. It sits on presynaptic nerve endings (mainly in the CNS), in the GI tract and on the β cells of the pancreas. <b>Clonidine</b> (the "-idines"; clonidine is the prototype) is an α2 agonist: it suppresses NE release and sympathetic tone, so vessels dilate, the heart slows, CO and BP fall. ADRs: sedation, nightmares, depression, dry mouth, constipation (less ACh released onto gut M3), hypotension, bradycardia, sexual dysfunction. The body up-regulates its receptors during chronic use, so stopping abruptly causes a hypertensive crisis; patients must be weaned off. <b>Mirtazapine</b> blocks the presynaptic α2 autoreceptor, so more NE and 5-HT are released (antidepressant: "What happens if I inhibit the inhibitor? I get positive effect."); it also blocks histamine H1 and muscarinic receptors (sedation, drowsiness, dry mouth, constipation) and α1 (peripheral edema); weight gain and higher cholesterol (5-HT) and hypertension (more NE) are on the slide. The drug list attributes the edema to α2 block; the slide and his words give α1: use α1. <small>Adr s.20–24, 26, 31–33; (T) 10/6, 10/7</small></p>

<h4>How he asks it</h4>
<div class="poll"><b>"Phenylephrine can be used as a decongestant because:"</b> it activates muscarinic (M3) receptors, thus activating the Gi pathway / it blocks Nm receptors, which increase Gs activity / It is an alpha4/beta2 partial agonist / it activates alpha 1, which increases Ca++ in smooth muscle<br>Key: <b>it activates alpha 1, which increases Ca++ in smooth muscle</b>: "it's gonna activate the GQ pathway which is gonna increase calcium inside of those smooth muscles which leads to vasoconstriction". 10/6 pool. <small>Poll 20; (T) 10/6</small></div>
<div class="poll"><b>"Which of the following drugs is most likely to decrease blood pressure?"</b> Atropine / Phenylephrine / Clonidine / Rocuronium / Cocaine<br>Key: <b>Clonidine</b>: "clonidine is an agonist to the alpha 2, but it is an inhibitory. Pathway." 10/6 pool. <small>Poll 21; (T) 10/6</small></div>
<div class="poll"><b>"Which of these drugs is most likely to produce vasodilation"</b> Prazosin / Selegiline / Succinylcholine / Dextroamphetamine / Phenylephrine<br>Key: <b>Prazosin</b>, "the selective alpha one antagonist". 10/7 "different shape or form" pool. <small>Poll 22; (T) 10/7</small></div>
<div class="poll"><b>"Which drug produces the greatest drop in blood pressure?"</b> Prazosin / Phenoxybenzamine / Equal potency<br>Key: <b>Phenoxybenzamine</b>: "even though you are increasing the levels of norepinephrine being released, it doesn't matter. It's covalently bound. It's irreversible. You can't outcompete". 10/7 pool. <small>Poll 23; (T) 10/7</small></div>
<div class="poll"><b>"Prazosin:"</b> Selective reversible muscarinic agonist / A non-depolarizing agent / Non-selective irreversible adrenergic antagonist / Selective reversible alpha 1 agonist / Selective reversible alpha1 antagonist<br>Key: <b>Selective reversible alpha1 antagonist</b>; the irreversible, non-selective one is phenoxybenzamine. <small>Jeopardy 10/8; (T) 10/8</small></div>
<div class="poll"><b>"Phenylephrine"</b> Gs =&gt; increased activation of adenylate cyclase =&gt; increased cAMP / Gq =&gt; increased activation of phospholipase C =&gt; increased IP3 / Gi =&gt; decreased activation of adenylate cyclase =&gt; decreased cAMP / Gq =&gt; increased activation of adenylate cyclase =&gt; increased cAMP / None of the above<br>Key: <b>Gq =&gt; increased activation of phospholipase C =&gt; increased IP3</b>; the fourth option pairs Gq with the wrong effector. <small>Review 10/9; Adr s.17–18</small></div>
<div class="poll"><b>Spoken (10/6):</b> "What would you think would be a side effect of taking a drug that antagonizes the alpha one receptor in the vein? ... So, you're gonna Fall off, right?" — and in the arteries: "I'm gonna get reflex tachycardia, so palpitations". A student: "I feel like they are contradicting each other." — "They do. Because alpha 1 agonist constrict, alpha 2 relax". <small>(T) 10/6</small></div>
<p><b>His cues.</b> "For our exam purpose, all I need to know if you see a drug with OC [-osin] is a selective alpha-1 antagonist. And where the alpha ones are in the nose, in the eye, in the blood vessels, in the urethra" (10/6) · "They all have this edine with it ... we're gonna focus on clonidine because that's our prototypical drug." (10/6) · Clonidine weaning: "that's a major consoling point for you guys" (counseling point; 10/6).</p>
<h4>Traps</h4>
<ul>
<li>An α1 antagonist as a decongestant: it worsens congestion; the α1 agonist decongests (Poll 20).</li>
<li>Expecting the extra NE from α2 block to weaken phenoxybenzamine: the covalent block cannot be outcompeted (Poll 23).</li>
<li>An α2 agonist raising sympathetic tone: α2 is Gi, so clonidine lowers it (Poll 21).</li>
<li>Calling prazosin irreversible, or oxymetazoline selective.</li>
<li>Stopping clonidine abruptly: up-regulated receptors give a hypertensive crisis.</li>
</ul>
<h4>Distinctions</h4>
<table class="reftab"><thead><tr><th>Looks the same</th><th>The one thing to look at</th><th>Answer</th></tr></thead><tbody>
<tr><td>α1 vs α2</td><td>G protein</td><td>α1 Gq: constriction. α2 Gi: less NE release</td></tr>
<tr><td>Prazosin vs phenoxybenzamine</td><td>Bond and receptors</td><td>Prazosin: reversible, α1. Phenoxybenzamine: covalent, α1 + α2</td></tr>
<tr><td>α1 block in veins vs arteries</td><td>Preload or afterload</td><td>Veins: orthostatic hypotension. Arteries: reflex tachycardia</td></tr>
<tr><td>Clonidine vs mirtazapine</td><td>Agonist or antagonist at α2</td><td>Clonidine: less NE, ↓BP. Mirtazapine: more NE and 5-HT</td></tr>
<tr><td>-idine vs -osin</td><td>Name ending</td><td>-idine: α2 agonist. -osin: selective α1 antagonist</td></tr>
</tbody></table>
<p class="sub">Sources: Adr s.4–7, 17–38; (T) 10/6, 10/7; Polls 20–23; Jeopardy 10/8; Review 10/9; notes L10, L11, DL2.</p>
</section>

<!-- ===================================================================== -->
<section class="guide" id="guide2-7">
<h3>7. β drugs, β blockers, epinephrine and norepinephrine</h3>
<p>All β receptors are Gs: AC ↑ → ↑cAMP. <b>β1</b> is in the heart (rate, force, rate of relaxation, AV conduction) and the kidney (renin release from the juxtaglomerular cells). <b>β2</b> relaxes smooth muscle (bronchi, the vessels of skeletal muscle) and is in the CNS; it has no sympathetic nerve and is reached by circulating epinephrine. <b>β3</b> relaxes the bladder detrusor muscle. <small>Adr s.3, 39–44; ANS s.13; (T) 10/7</small></p>
<p><b>Agonists.</b> Dobutamine is a selective β1 agonist (intravenous, short term for a failing heart): more force and rate; tolerance develops because the receptors down-regulate, and its ADRs are tachycardia and arrhythmias. The "-terols" (albuterol, levalbuterol, salmeterol, formoterol) are β2 agonists: bronchodilation; systemic effects are faster heart rate, higher BP and agitation. Mirabegron is a β3 agonist: the bladder relaxes and holds more, with no anti-DUMBBELSS, at a higher price. Isoproterenol binds β1 and β2 equally ("iso" = equal): more rate and force, bronchodilation, lower vascular resistance; palpitations, tachycardia and ischemia, which is why albuterol replaced it for asthma. <small>Adr s.40–45; (T) 10/7</small></p>
<p><b>Epinephrine</b> binds with a rank of affinity: β1 and β2 at low doses, then α1, then α2 at high doses. In a blood vessel, a low dose activates β2 and the vessel dilates; a high dose adds α1, which overrides β2, and the vessel constricts. The constriction at a high dose is therefore α1 minus β2. Remove one side and the answer follows: with prazosin first (α1 blocked) epinephrine can only act on β2 and the vessel dilates, so the pressor (BP-raising) response turns into a depressor (BP-lowering) one; with propranolol first (β2 blocked) the constriction is greater. He uses the name <b>epinephrine reversal</b> for both switches: dilation at a low dose against constriction at a high dose, and dilation of the high dose after prazosin ("At high doses, I'm constricting, but if I blocked [alpha ones] or if I give a low dose, I vasodilate"). Phenylephrine (α1 only) gives a larger rise than epinephrine, and after prazosin its response is abolished, not reversed, because it has no β2 action. Patients on an epinephrine infusion must be weaned off (receptors down-regulate). In an epinephrine overdose α1 and β1 predominate, so the α1 antagonist goes first and the β1 blocker second (Poll 24 below). <small>Adr s.47–52; (T) 10/7, 10/8</small></p>
<p><b>Norepinephrine</b> has its highest affinity for α1 and β1 (it can also bind α2 and β2): α1 raises TPR, β1 raises rate and force. Its problems are a higher O2 demand of the heart, less blood flow to other organs, and arrhythmias. Slide 53 lists α1 and β1; slide 84 and ANS s.13 add α2: answer "highest affinity for α1 and β1". <small>Adr s.53, 84; (T) 10/7</small></p>
<p><b>β blockers.</b> Every β blocker blocks β1, so every one lowers rate, force, relaxation, CO and renin release ("because all beta blockers blocks beta ones, who's gonna take over? Parasympathetic."). They differ in what else they block, and that is the must-know. MAN = metoprolol, atenolol, nebivolol: β1-selective. Propranolol (the prototype) and pindolol (a partial agonist): β1 and β2. Carvedilol and labetalol: β1, β2 and α1. Consequences: in asthma, a non-selective blocker closes the airways, so a β1-selective one is chosen (Katzung says β1-selective blockers should also generally be avoided; his answer is metoprolol). In insulin-dependent diabetes, every β blocker masks the racing heart of hypoglycemia; a non-selective one also masks the tremor and nervousness, leaving only sweating, so a β1-selective one is chosen. Propranolol is lipophilic, enters the brain and blocks central β2 (positive feedback on NE release), lowering anxiety. Stopping any β blocker abruptly causes rebound hypertension, because the receptors were up-regulated. <small>Adr s.54–59; (T) 10/7</small></p>
<p><b>Cross-talk in the heart.</b> β1 (Gs, ↑cAMP) and M2 (Gi, ↓cAMP) act on the same adenylate cyclase from opposite sides; the heart rate is the net of both: "whoever has the predominant tone wins that crosstalk". <small>Adr s.61; (T) 10/7</small></p>
<!--FIG:crosstalk-->

<h4>How he asks it</h4>
<div class="poll"><b>"Your pt OD on his epi pen. He shows up to the ER and the physician ask which one should he give it first?"</b> Prazosin / Metoprolol / Doesn't matter<br>Key: <b>Prazosin</b>: "if you give the beta block first. You're slowing down the heart ... but you're still clamped up, so you can't overcome that afterload and pump blood forward". Vasodilate first, then slow the heart. 10/7 pool. <small>Poll 24; (T) 10/7</small></div>
<div class="poll"><b>"Which of the following drugs relax the bladder smooth muscle, thus decreasing urination?"</b> Mirabegron / Selegiline / Dobutamine / Carbachol / Donepezil<br>Key: <b>Mirabegron</b> (β3 agonist). "What if I had to put trosium in there too? ... Now we have a selectol, right?" — both the β3 agonist and the M3 antagonist would be correct. He gave the 10/7 exam cue at this poll. <small>Poll 25; (T) 10/7</small></div>
<div class="poll"><b>"You have a set of four identical twins with same weight, height, diet, and exercise regiment. You ask them to run a 5k lap and give each one a different drug. Who comes 1st?"</b> Propranolol / Metoprolol / Carvedilol / Carbachol / Neostigmine<br>Key: <b>Metoprolol</b>. "The major says E. I say B." All three β blockers lower CO equally, "But at least the metoprolol guy can breathe." The class lost a bonus on it; the student's sheet marks "question similar on exam". <small>Poll 26; (T) 10/7</small></div>
<div class="poll"><b>"Your patient had his adrenal glands removed due to a tumor? Which of the following physiological responses would this pt have difficulty achieving?"</b> Tachycardia / Vasoconstriction / Bronchial dilation / Urinating / Increase in GI motility<br>Key: <b>Bronchial dilation</b>: "Bronchialdilation would be the correct answer. ... the lungs is parasympathetic only." Airway β2 has no nerve and depends on adrenal epinephrine; the heart, vessels, bladder and gut have sympathetic nerves. <small>Jeopardy 10/8; (T) 10/8</small></div>
<div class="poll"><b>"Which of the following drugs can decrease heart rate and afterload?"</b> Carvedilol / Prazosin / Atropine / Phenylephrine / Cocaine<br>Key: <b>Carvedilol</b> (β1 block lowers rate; α1 block lowers afterload: "carvedilol can do it all", 10/6). Prazosin lowers afterload but raises the rate by reflex. <small>Review 10/9; Adr s.7, 54</small></div>
<div class="poll"><b>"Carvedilol will most likely cause:"</b> Bradycardia / Hypotension / Bronchial constriction / Fatigue / All of the above<br>Key: <b>All of the above</b>: β1 (bradycardia), α1 (hypotension), β2 (bronchial constriction). <small>Review 10/9; Adr s.54, 56–59</small></div>
<div class="poll"><b>"If your patient takes albuterol for his asthma, which of the following is most likely to worsen his condition?"</b> Atropine / Formeterol / Propranolol / Ipratropium / Metoprolol<br>Key: <b>Propranolol</b>: it blocks the β2 that albuterol needs; metoprolol is β1-selective; atropine, ipratropium and formoterol all dilate the bronchi. <small>Review 10/9; Adr s.42–43, 54, 59</small></div>
<div class="poll"><b>Spoken (10/7):</b> "what would you predict to happen if I put an alpha one antagonist first and then gave epinephrine? ... A vasodilation, right?" · "if I must choose a beta-blocker to an insulin-dependent diabetic, which one would I pick? I said beta one selective, right?" <small>(T) 10/7</small></div>
<p><b>His cues.</b> "those are gonna be the beta blockers that you need to know from me on the exam, and which one is selective versus which one is not selective." · "How about if we spell man. Man, right? So, we have metoprolol, atenolol, and nabivolol." · "it will be silly for you to miss a question exam but not knowing which of the beta blockers is the selective or not." · "I don't want you to memorize which one is the 1st generation versus the 3rd generation." · "If you know that a terol is a beta2 agonist, that's good for me." (all 10/7)</p>
<h4>Traps</h4>
<ul>
<li>Neostigmine winning the race (the class's pick): DUMBBELSS, including bronchoconstriction and bradycardia (Poll 26).</li>
<li>Metoprolol first in an epinephrine overdose: the arteries stay clamped (Poll 24).</li>
<li>Expecting a β blocker to reverse epinephrine's pressor effect: only an α1 blocker reverses it; propranolol makes it larger.</li>
<li>Calling carvedilol or propranolol cardioselective: only MAN is β1-selective.</li>
<li>Giving norepinephrine the low-dose β2 dilation: that is epinephrine.</li>
</ul>
<h4>Distinctions</h4>
<table class="reftab"><thead><tr><th>Looks the same</th><th>The one thing to look at</th><th>Answer</th></tr></thead><tbody>
<tr><td>Dobutamine, isoproterenol, albuterol, mirabegron</td><td>Which β</td><td>β1; β1 = β2; β2 (-terol); β3 (bladder)</td></tr>
<tr><td>Epinephrine low vs high dose in a vessel</td><td>Which receptor wins</td><td>Low: β2, dilation. High: α1 overrides, constriction</td></tr>
<tr><td>Prazosin vs propranolol before epinephrine</td><td>Which receptor is removed</td><td>Prazosin: dilation (reversal). Propranolol: greater constriction</td></tr>
<tr><td>Epinephrine vs norepinephrine</td><td>Highest affinity</td><td>Epinephrine: β1, β2 first. Norepinephrine: α1, β1</td></tr>
<tr><td>MAN vs propranolol, pindolol vs carvedilol, labetalol</td><td>Receptors blocked</td><td>β1 / β1 + β2 / β1 + β2 + α1</td></tr>
<tr><td>Stopping an agonist vs an antagonist</td><td>Receptor regulation</td><td>Agonist (epinephrine): down-regulated, wean. β blocker: up-regulated, rebound</td></tr>
</tbody></table>
<p class="sub">Sources: Adr s.39–61, 84; ANS s.13; (T) 10/7, 10/8; Polls 24–26; Jeopardy 10/8; Review 10/9; notes L11, DL2, PE2.</p>
</section>

<!-- ===================================================================== -->
<section class="guide" id="guide2-8">
<h3>8. Reading his tracings</h3>
<p>A tracing records one tissue response (gut smooth-muscle tone, vessel constriction, blood pressure or heart rate) against time, with each drug marked by an arrow where it was given. It is not a dose–response curve. "If I'm going up, it's constricting. If I'm going down, it's dilating. OK, it's relaxing." Each exam tracing shows one effect: "I'm not gonna give you a compounding effect of things that you have to figure out along the way." <small>(T) 10/6, 10/8</small></p>
<p>His method, in order: (1) name the known drug and the receptor it acts on; (2) list the receptors in that tissue (gut: M3 contracts, α2 relaxes; vessels: α1 constricts, β2 dilates, M3 on the endothelium is not innervated and is quiet unless a muscarinic drug is given; heart: β1 faster, M2 slower); (3) read what the unknown drug did to the known drug's response — larger, abolished, or reversed; (4) for each option ask "is it helping or not?" and eliminate the ones that help when the response fell, and the ones whose receptor is in another organ. "You've got to know the mechanism of action. You've got to know the receptors, and then through the process of elimination you ask the question, Is it helping or not?" <small>(T) 10/6, 10/7</small></p>

<h4>The GI smooth muscle tracing</h4>
<!--IMG:pe2-gi-tracing-->
<table class="readstrip"><tr><th>Known drug and receptor</th><th>After drug X</th><th>Helping or not?</th><th>Answer</th></tr><tr><td>Pilocarpine on gut M3 (Gq): tone up</td><td>Tone dips slightly; second pilocarpine: no rise</td><td>Hurting: the M3 response is gone</td><td><b>Atropine</b> (a muscarinic antagonist)</td></tr></table>
<p>The small dip at X is the resting PNS tone being removed. Carbachol and neostigmine would help pilocarpine; rocuronium (Nm) and varenicline (brain Nn) have no receptor in gut smooth muscle. <small>Poll 18; (T) 10/6; Chol s.12–19</small></p>
<div class="poll"><b>"The figure below shows tracing of GI smooth muscle in response to pilocarpine before and after drug X. Drug X is most likely to be:"</b> Carbachol / Neostigmine / Rocuronium / Atropine / Varenicline<br>Key: <b>Atropine</b>: "atropine is blocking the ability of pilocarpine to bind and activate those receptors and produce that constriction." He first read the class answer as "C as in cat"; on the sheet atropine is D. 10/6 pool. <small>Poll 18; (T) 10/6</small></div>

<h4>The norepinephrine and drug B tracing</h4>
<!--IMG:pe2-ne-drug-b-->
<table class="readstrip"><tr><th>Known drug and receptor</th><th>After drug B</th><th>Helping or not?</th><th>Answer</th></tr><tr><td>NE (A) on vessel α1 (Gq): constriction rises</td><td>Falls below the starting level</td><td>Hurting: the α1 response is removed</td><td><b>Prazosin</b></td></tr></table>
<p>Phenylephrine (a second α1 agonist) and cocaine (more NE) would help; metoprolol acts on β1 in the heart, "not even near close the blood vessels"; atropine has nothing to block, because "Those M3s in the blood vessels, they're not innervated ... those M3s are quiet." <small>Poll 28; (T) 10/7; Adr s.84–85</small></p>
<div class="poll"><b>"The tracing show the effects of drug A (NE) on BP. Which drug is most likely drug B?"</b> metoprolol / prazosin / atropine / phenylephrine / Cocaine<br>Key: <b>prazosin</b>: "Some says metoprolol, some says prazosin, some atropine. What is the best answer? I would say B as in boy." The drawing's y-axis reads "Constriction"; he read it as BP. 10/7 pool. <small>Poll 28; (T) 10/7</small></div>

<h4>Epinephrine at two receptors in a vessel</h4>
<!--IMG:pe2-epi-two-receptors-->
<table class="readstrip"><tr><th>Concentration</th><th>Receptor bound</th><th>Vessel</th><th>Answer</th></tr><tr><td>Low</td><td>B only</td><td>C: dilated</td><td><b>B = β2</b></td></tr><tr><td>High</td><td>A and B</td><td>D: constricted</td><td><b>A = α1</b> (overrides β2)</td></tr></table>
<p>α2 is inhibitory (Gi) and should not constrict; β1 is in the heart; muscarinic receptors do not fit either response. With propranolol given first, the high dose gives a greater constriction; with prazosin first, it gives dilation (epinephrine reversal, section 7). <small>Poll 29; (T) 10/7, 10/8; Adr s.47–51</small></p>
<div class="poll"><b>"The figure below represents the binding of Epi to two receptors. Receptor A is most likely?"</b> Alpha 2 receptors / Beta 1 receptors / Alpha 1 receptors / Beta 2 receptors / Muscarinic receptors<br>Key: <b>Alpha 1 receptors</b>: "Receptor B is for the beta 2s, receptor A is for the alpha-1 receptors." Run as "our last chance to get a bonus for exam 2". <small>Poll 29; (T) 10/8</small></div>

<h4>Tracings he described in words</h4>
<table class="reftab"><thead><tr><th>Tracing</th><th>Result</th><th>Why</th></tr></thead><tbody>
<tr><td>Acetylcholine (ACh) given intravenously to a rat</td><td>BP falls; heart rate rises</td><td>Endothelial M3 → nitric oxide → dilation; the baroreceptor reflex drives β1 and overrides M2: "So this is a beta one reflex. Tachycardia."</td></tr>
<tr><td>Atropine first, then the same ACh dose</td><td>No fall in BP; heart rate stays high</td><td>Vessel M3 and heart M2 blocked; the SNS is unopposed</td></tr>
<tr><td>Atropine first, then 100 times the ACh dose (5 to 500)</td><td>The fall in BP and the reflex tachycardia return</td><td>Atropine is competitive: enough agonist outcompetes it</td></tr>
</tbody></table>
<p class="sub">Adr s.75–83 (tracing pictures not seen; read from his words); (T) 10/7.</p>

<h4>Epinephrine before and after three compounds</h4>
<!--IMG:pe2-epi-compounds-->
<table class="readstrip"><tr><th>Before epinephrine (E)</th><th>Response to E</th><th>Helping or not?</th><th>Answer</th></tr><tr><td>Nothing</td><td>BP rises: a high dose, α1 minus β2</td><td>—</td><td>Reference response</td></tr><tr><td>Compound 1</td><td>A much larger rise</td><td>Helping: β2, the opponent of α1, is removed</td><td><b>Propranolol</b></td></tr><tr><td>Compound 2</td><td>BP falls</td><td>Reversed: α1 is removed, β2 is left</td><td>Prazosin (epinephrine reversal)</td></tr><tr><td>Compound 3</td><td>No response</td><td>Both α1 and β2 responses are gone</td><td>He did not name it</td></tr></table>
<div class="poll"><b>"The figure below shows the tracing for blood pressure in response to epinephrine before and after 3 different drugs. Compound 1 is most likely to be:"</b> Metoprolol / Propranolol / Atropine / Prazosin / Phenoxybenzamine<br>Key: <b>Propranolol</b>: "by giving compound one, I'm blocking the beta 2s. So I'm taking away the beta 2 now, all I have is what? alpha one effect". Metoprolol spares β2; prazosin and phenoxybenzamine would lower the response. <small>Jeopardy 10/8; (T) 10/8; Adr s.47–51</small></div>

<h4>Skeletal muscle and drug X</h4>
<!--IMG:pe2-skm-drug-x-->
<table class="readstrip"><tr><th>Known drug and receptor</th><th>After drug X</th><th>Helping or not?</th><th>Answer</th></tr><tr><td>ACh on skeletal muscle (SKM) Nm: contraction</td><td>ACh gives no response</td><td>Hurting: the Nm response is gone</td><td><b>Rocuronium</b></td></tr></table>
<div class="poll"><b>"The tracing below shows the effects of Ach in the skeletal muscle alone or in the presence of drug "X." Drug "X" is most likely?"</b> Carbachol / Norepinephrine / Veranicline / Oxybutynin / Rocuronium<br>Key: <b>Rocuronium</b>, a competitive Nm antagonist. Carbachol and oxybutynin act on muscarinic receptors, norepinephrine on adrenergic ones, varenicline on brain Nn. Not recorded; key from NMJ s.19, 27 and (T) 10/5. <small>Review 10/9</small></div>
<p><b>His cues.</b> "And you're gonna get 1 to 2 of these little graphs on your uh test, and this is how you're gonna apply the knowledge, right?" (10/6) · "even if you get to 2, I think 50/50 is better than 1 out of 5" (10/7) · The 4000-point bronchial-tone tracing: "This is not gonna be on the exam. This is for Jeopardy process only." (10/8)</p>
<h4>Traps</h4>
<ul>
<li>Reading the tachycardia after ACh as an M2 effect: it is the β1 reflex to the fall in BP.</li>
<li>Picking a drug that helps the agonist when the response fell (cocaine, phenylephrine, carbachol).</li>
<li>Picking a drug whose receptor is in another organ (metoprolol for a vessel, rocuronium for the gut).</li>
<li>Picking atropine against NE in a vessel: vascular M3 is quiet without a muscarinic drug.</li>
</ul>
<p class="sub">Sources: Polls 18, 28, 29; Jeopardy 10/8; Review 10/9; Adr s.47–51, 75–85; Chol s.12–19; NMJ s.19, 27; (T) 10/5, 10/6, 10/7, 10/8; notes PE2, L11.</p>
</section>

<!-- ===================================================================== -->
<section class="guide" id="guide2-9">
<h3>9. Nitric oxide</h3>
<p>Nitric oxide (NO) is a gas, once thought to be only a pollutant, that the vessel endothelium makes to dilate the vessel. The sequence: a muscarinic agonist acts on M3 on the endothelium (not innervated) → Gq → IP3 → Ca++ released from the endoplasmic reticulum → Ca++–calmodulin activates nitric oxide synthase (NOS), which oxidizes L-arginine to L-citrulline and NO (using NADPH and O2) → NO diffuses into the smooth muscle → it activates soluble guanylyl cyclase (sGC, like adenylate cyclase but floating in the cytoplasm) → GTP becomes cyclic GMP (cGMP) → vasodilation. Phosphodiesterase (PDE) breaks cGMP down and ends the signal; it also breaks down cAMP, the messenger adenylate cyclase makes, and caffeine and theophylline (an old asthma drug) are inhibitors of the PDE that breaks down cAMP (ANS s.7; (T) 9/30). In the Furchgott experiment, ACh dilates a vessel only when the endothelium is intact; with damaged endothelium the vessel stays constricted. <small>Adr s.62–74; (T) 10/7</small></p>
<p>Two drug groups act on this pathway. The nitrates (nitroglycerin, nitroprusside, isosorbide dinitrate and mononitrate) are NO donors: they release NO, which bypasses M3, Ca++ and NOS and goes straight to sGC. The PDE inhibitors (sildenafil, tadalafil) block the breakdown of cGMP, so "PDE inhibitors increase the potency of NO". Given together, cGMP keeps rising and BP drops unsafely: marked hypotension. Cross-talk: β2 (cAMP) and NO (cGMP) both dilate, and PDE breaks down both messengers, so the two dilations add. The drug list gives "Endothelium of blood vessels (M3)" as the nitrates' site; he said their NO bypasses M3: do not answer M3 for the nitrates. <small>Adr s.62, 67–74; (T) 10/7</small></p>
<p>What he needs: "I need you to know that if you either activate the M3s on the endothelium or if you take nitroglycerin, you're going to be either producing nitric oxide, and nitric oxide is a powerful vasodilator" — and "I'm never going to ask you to walk through every single one of these steps." The scientists' names are "just for information". <small>(T) 10/7</small></p>

<h4>How he asks it</h4>
<div class="poll"><b>"Which of the following drugs may cause marked hypotension if mixed with nitroglycerine?"</b> phenylephrine / Atropine / Sildenafil / Metoprolol / Amphetamine<br>Key: <b>Sildenafil</b>: "Hopefully you pick C as in cat, so then it fail because you block the PDE enzyme. And you continue to make it and donate nitric oxide". The transcript says "hypertension"; the sheet says hypotension. 10/7 pool. <small>Poll 27; (T) 10/7</small></div>
<div class="poll"><b>"Which statement is INCORRECT about nitric oxide?"</b> NO effects is opposed by phosphodiesterase enzyme (PDE) / NO is synthesized from L-arginine by the nitric oxide synthase (NOS) / NO is a gas involved in the regulation of vascular tone via increasing cGMP / NO is synthesized in the smooth muscle where it can activate sGC<br>Key: <b>NO is synthesized in the smooth muscle where it can activate sGC</b>: NO is made in the endothelium and diffuses into the smooth muscle. <small>Review 10/9; Adr s.63, 67–74</small></div>
<div class="poll"><b>Spoken (10/7):</b> "So what do you think is going to happen if I give a drug that blocks the PDE? What is going to happen to the potency of nitric oxide? It's gonna increase." <small>(T) 10/7</small></div>
<p><b>His cue.</b> "But the key thing over here is we have a very bad drug-drug interaction. And I would like for you to tell me on an exam is why it's bad to take Sadenophil with a nitric oxide donor" (10/7).</p>
<h4>Traps</h4>
<ul>
<li>Sildenafil as an NO donor: it blocks the breakdown of cGMP.</li>
<li>NO raising cAMP: NO raises cGMP; β2 raises cAMP.</li>
<li>Vascular M3 (Gq) read as constriction: it makes NO and dilates.</li>
<li>Nitrates needing M3 or NOS: their NO goes straight to sGC.</li>
</ul>
<h4>Distinctions</h4>
<table class="reftab"><thead><tr><th>Looks the same</th><th>The one thing to look at</th><th>Answer</th></tr></thead><tbody>
<tr><td>Nitrate vs PDE inhibitor</td><td>Makes cGMP or saves it</td><td>Nitrate: donates NO, more cGMP made. PDE inhibitor: less broken down</td></tr>
<tr><td>β2 vs NO dilation</td><td>Second messenger</td><td>β2: cAMP. NO: cGMP. Both broken down by PDE</td></tr>
<tr><td>Endothelial M3 vs smooth-muscle α1</td><td>Which cell has the Ca++ rise</td><td>Endothelium: NO, dilation. Smooth muscle: constriction</td></tr>
</tbody></table>
<p class="sub">Sources: Adr s.62–74; (T) 10/7; Poll 27; Review 10/9; notes L11, DL2.</p>
</section>

<!-- ===================================================================== -->
<section class="guide" id="guide2-10">
<h3>10. The renin–angiotensin–aldosterone system</h3>
<p><b>The cascade, first to last.</b> Angiotensinogen, a long peptide from the liver, is cut by renin, an enzyme from the granular juxtaglomerular cells of the kidney's afferent arteriole, into angiotensin I (Ang I, inactive). Angiotensin-converting enzyme (ACE) converts Ang I into angiotensin II (Ang II, active); ACE also breaks down bradykinin, a potent vasodilator. Ang II binds two receptors. AT1 (Gq, ↑Ca++) constricts arteries and veins (higher TPR, afterload and preload), increases Na+ and water reabsorption, releases aldosterone, lowers renal blood flow and drives remodeling (hypertrophy of heart and vessel cells). AT2 (Gi, ↓cAMP) does the opposite — dilation, Na+ excretion, less remodeling — and is the physiological antagonist of AT1. He said Ang II has much higher affinity for AT1; Katzung says it binds both equally: use his version. Aldosterone binds the mineralocorticoid receptor (MR), a nuclear receptor in the late distal tubule and collecting duct, so the cells make more Na+ channels, K+ channels and Na+/K+-ATPase pumps: Na+ and water are retained and K+ is lost ("a potassium wasting hormone"). On 10/1 he said renin converts Ang I to Ang II; the RAAS slides and his 10/8 lecture give renin → Ang I and ACE → Ang II: use 10/8. <small>RAAS s.3, 5, 9, 15–18, 20–21; (T) 10/8</small></p>
<p><b>Renin release</b> has three controls. Within the kidney, the macula densa senses Na+ Cl−: low sodium → more renin. The intrarenal baroreceptor senses pressure: low pressure → more renin. Through the CNS, sympathetic activity on β1 (Gs) of the juxtaglomerular cells: more sympathetic → more renin. "So we have one direct. Proportional and two inverse proportional relationships". Renin is the rate-limiting enzyme: block it and everything downstream falls. <small>RAAS s.5–8; (T) 10/8</small></p>
<p><b>The drugs</b> (slides 24–25: captopril, losartan, aliskiren, metoprolol, spironolactone; his acronym is CLAMS, one letter per drug). The rule for every one: "downstream goes down, upstream goes up". <b>Aliskiren</b> is a reversible renin inhibitor: Ang I, Ang II, AT1 and AT2 activation and aldosterone all fall. The "-prils" (captopril, enalapril, lisinopril and others) are reversible, selective ACE inhibitors: the primary effect is less Ang II; the secondary effect is more bradykinin. Ang I builds up, and AT1 and AT2 activation both fall because there is less agonist. The "-sartans" (losartan, valsartan and others) are angiotensin II receptor blockers (ARBs), 10,000-fold selective for AT1 over AT2: the body raises everything upstream (renin, Ang I, Ang II), AT1 activation falls, and the extra Ang II activates AT2, which opposes AT1 ("the cherry on top"). <b>Spironolactone</b> and <b>eplerenone</b> block aldosterone at the MR (potassium-sparing diuretics): Na+ is lost, K+ is spared; spironolactone also weakly blocks the androgen receptor and testosterone synthesis (gynecomastia and impotence, not with the kidney-selective eplerenone), plus diarrhea and drowsiness. <b>Metoprolol</b> blocks β1 on the juxtaglomerular cells and suppresses renin release, but does not abolish it, because the sodium and baroreceptor controls remain. <small>RAAS s.4, 8–14, 21–28; (T) 10/8</small></p>
<table class="reftab"><thead><tr><th>Drug</th><th>Angiotensinogen</th><th>Renin</th><th>Ang I</th><th>Ang II</th><th>Bradykinin</th><th>AT1 activation</th><th>AT2 activation</th><th>Aldosterone</th></tr></thead><tbody>
<tr><td>Lisinopril (ACE inhibitor)</td><td>↑</td><td>↑</td><td>↑</td><td>↓</td><td>↑</td><td>↓</td><td>↓</td><td>↓</td></tr>
<tr><td>Losartan (ARB)</td><td>↑</td><td>↑</td><td>↑</td><td>↑</td><td>not stated</td><td>↓</td><td>↑</td><td>↓</td></tr>
<tr><td>Aliskiren (renin inhibitor)</td><td>↑</td><td>↓ activity (slide 8); the body tries to make more</td><td>↓</td><td>↓</td><td>not stated</td><td>↓</td><td>↓</td><td>↓</td></tr>
<tr><td>Metoprolol (β1 blocker)</td><td colspan="8">Less renin released (suppressed, not abolished), so the steps after renin are lower</td></tr>
<tr><td>Spironolactone (MR antagonist)</td><td colspan="8">Acts after the cascade, at aldosterone's receptor: Na+ lost, K+ spared</td></tr>
</tbody></table>
<p class="sub">Slide 29 is a blank prediction table; the arrows are his spoken answers on 10/8. Renin rises with lisinopril and losartan because the body compensates upstream ("my body is gonna be compensating by trying to upstream, make more renin, angiotensinogen"); slide 8 says aliskiren reduces plasma renin activity. He gave no direction for bradykinin with losartan or aliskiren.</p>
<p><b>Adverse effects.</b> Shared by the renin inhibitor, ACE inhibitors and ARBs: hyperkalemia (especially with kidney disease), first-dose hypotension, and harm to the fetus. Only the ACE inhibitors raise bradykinin, which gives a dry cough and angioedema; a patient with either can be switched to an ARB, because there is no cross-class effect — but not for hyperkalemia or pregnancy, which the ARB shares. The three cascade blockers cause hyperkalemia because each lowers aldosterone, the hormone that wastes K+; spironolactone causes it by blocking aldosterone's receptor. Kidney disease raises the risk. Blood potassium normally runs about 3 to 5; a patient who starts an ACE inhibitor or ARB already at 5 to 5.5 is pushed into the hyperkalemic range, with a higher risk of arrhythmias. <small>RAAS s.19–22; (T) 10/8</small></p>

<h4>How he asks it</h4>
<div class="poll"><b>"Lisinopril:"</b> Decreases renin plasma level / Decreases AngI plasma level / Decreases AngII plasma level / Increase aldosterone plasma level / Increase the activation of AT1 receptors<br>Key: <b>Decreases AngII plasma level</b>: "it's not gonna decrease renin, that's upstream from the inhibition point. It's not gonna decrease angiotensin 1, actually it's gonna increase" <small>Poll 30; (T) 10/8</small></div>
<div class="poll"><b>"Valsartan:"</b> Decreases plasma levels of angiotensin II / Decrease activation of AT1 receptors / Decrease activation of AT2 receptors / Decrease production of angiotensin I / All of the above<br>Key: <b>Decrease activation of AT1 receptors</b>: "It will not decrease the plasma of angiotensin 2 ... It's not gonna decrease the activation of AT2. Actually it's gonna enhance it ... and of course it's not all the above" <small>Poll 31; (T) 10/8</small></div>
<div class="poll"><b>"Which of the following drugs may causes hyperkalemia?"</b> Captopril / Losartan / Aliskiren / Spironolactone / All of the above<br>Key: <b>All of the above</b>: "both the ACEs, the ARBs, and the RAIN inhibitors can also cause hyperkalemia." — "If you get that on the exam, you should be smiling, right?" <small>Poll 32; (T) 10/8</small></div>
<div class="poll"><b>"Losartan"</b> causes vasodilation by direct inhibition of AT1 receptors / produces dry cough by increasing levels of bradykinin / is an antagonist to the rate limiting enzyme, renin / causes hyperkalemia by antagonism of the MR receptor / It blocks the secretion of renin via a beta 1 receptor antagonism<br>Key: <b>causes vasodilation by direct inhibition of AT1 receptors</b>; each wrong option describes another RAAS drug (an ACE inhibitor such as lisinopril, aliskiren, spironolactone, metoprolol). <small>Review 10/9; RAAS s.13–14, 24–25</small></div>
<div class="poll"><b>"Lisinopril decrease blood pressure by:"</b> Decreasing the conversion of of Ang I to Ang II / Indirect decrease of AT1 activation / Increase plasma level of bradykinin / Increase plasma level of angiotensin 1-7 / All the above<br>Key: <b>All the above</b>, as written. Angiotensin 1-7 is on the drug list only, not on his slides or in the 10/8 lecture; the other three are his primary and secondary mechanisms. <small>Review 10/9; RAAS s.9, 12</small></div>
<div class="poll"><b>Spoken (10/8):</b> "So if I block the 81 [AT1], who goes up? ... So I already told you 82 [AT2] goes up. What else goes up? Will angiotensin 2 levels goes up." · ACE inhibitors' two mechanisms: "This makes a fantastic selectto question because it gives me more than one right answer to ask you, right?" <small>(T) 10/8</small></div>
<p><b>His cues.</b> "my goal is for you to have this little cascade of peptides and enzymes tattooed in your head because you're gonna need it for the exam too ... You should be able to tell me what comes first and what comes last, and how our drugs gonna modify their concentration or activity in our system." · Slide 29: "I guarantee you you're gonna have at least 1 to 2 questions on the effects of these drugs in the cascade." · "anything with the Perl [-pril] doesn't matter which of the 11 ACE inhibitors that you have, it's gonna be what? AC ACE inhibitor" · ARBs: "I don't care if you know their brand name. I don't care if you know which one is the most potent." · The AT1 signalling wheel: "I don't expect you to memorize any of them other than increasing calcium" (all 10/8).</p>
<h4>Traps</h4>
<ul>
<li>Lisinopril lowering renin or Ang I: both are upstream and rise (Poll 30).</li>
<li>Valsartan lowering Ang II or AT2 activation: Ang II rises and AT2 activation rises (Poll 31).</li>
<li>Giving ACE inhibitors the AT2 "bonus": less Ang II means less AT2 activation too.</li>
<li>Switching to an ARB for hyperkalemia or pregnancy: the ARB shares both; switch only for cough or angioedema.</li>
<li>Metoprolol abolishing renin, or aldosterone sparing K+: suppressed, not abolished; aldosterone wastes K+.</li>
</ul>
<h4>Distinctions</h4>
<table class="reftab"><thead><tr><th>Looks the same</th><th>The one thing to look at</th><th>Answer</th></tr></thead><tbody>
<tr><td>Renin vs ACE</td><td>Which step</td><td>Renin: angiotensinogen → Ang I. ACE: Ang I → Ang II, breaks down bradykinin</td></tr>
<tr><td>AT1 vs AT2</td><td>G protein</td><td>AT1 Gq: constriction, Na+ kept. AT2 Gi: dilation, Na+ lost</td></tr>
<tr><td>Aliskiren vs lisinopril</td><td>Ang I</td><td>Aliskiren: falls. Lisinopril: builds up</td></tr>
<tr><td>Lisinopril vs losartan</td><td>AT2 activation</td><td>Lisinopril: falls. Losartan: rises</td></tr>
<tr><td>Spironolactone vs eplerenone</td><td>Androgen effects</td><td>Spironolactone: gynecomastia, impotence. Eplerenone: none</td></tr>
<tr><td>Metoprolol vs aliskiren</td><td>Renin release or renin itself</td><td>Metoprolol: less released. Aliskiren: renin blocked</td></tr>
</tbody></table>
<p class="sub">Sources: RAAS s.3–30; (T) 10/1, 10/8; Polls 30–32; Review 10/9; notes L12, DL2, PE2.</p>
</section>
`;
