TOPICS.push({id:'FG', name:'Figure drills: his PollEV, Jeopardy and review figures', prof:'Gottlieb', lecture:'FG',
  cite:'PollEV_s.pdf; Pharmacodynamics reviews.pdf; Jeopardy 9/30; Part 3',
  subs:[
    {id:'read', name:'Read the figure', cite:'PollEV_s.pdf pages 2–5; Jeopardy 9/30'},
    {id:'which', name:'Which curve, which drug', cite:'PollEV_s.pdf pages 3 and 5; Pharmacodynamics reviews.pdf pages 5–11'},
    {id:'why', name:'Which feature rules a class in or out', cite:'Pharmacodynamics reviews.pdf pages 5–11'},
    {id:'predict', name:'Predict the curve for a different drug', cite:'PollEV_s.pdf; Pharmacodynamics reviews.pdf'}
  ]});
QUESTIONS.push(
/* ---------------- Four coloured curves A–D (PollEV_s.pdf page 4) ---------------- */
{id:'FG-001', fg:'potency', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'four-drug-potency-efficacy', tags:['poll','figure-drill'], source:'both',
 img:'pollev-four-drc-potency', imgAlt:'Four coloured dose-response curves A (black), B (red), C (blue) and D (green), response % against log[A] from .01 to 100 M', imgCap:'Response % vs Log[A] M; four drugs, one receptor',
 stem:'The DRCs below represent the DRC of four different drugs acting on the same receptor. Which drug is the most efficacious?',
 options:[
  {t:'A', correct:false, miss:'efficacy', why:'A is the most potent (farthest left), but its plateau sits below C.'},
  {t:'B', correct:false, miss:'efficacy', why:'B plateaus below both A and C.'},
  {t:'C', correct:true, why:'C reaches the highest response on the y-axis: the most efficacious, even though it is the least potent.'},
  {t:'D', correct:false, miss:'read', why:'D plateaus lowest of the four: the least efficacious.'}],
 teach:'Efficacy is up and down, the height of the plateau. C rises highest, so C is the most efficacious; it is also the farthest right, the least potent. Potency (A) and efficacy (C) are two separate readings of the same figure.',
 quote:'When we think about efficacy ... Up and down, and our potency is gonna be a combination of the left and right and the up and down',
 cite:'PollEV_s.pdf page 4; transcript 9/29, 9/30'},

{id:'FG-002', fg:'potency', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'four-drug-potency-efficacy', tags:['poll','figure-drill'], source:'both',
 img:'pollev-four-drc-potency', imgAlt:'Four coloured dose-response curves A (black), B (red), C (blue) and D (green), response % against log[A] from .01 to 100 M', imgCap:'Response % vs Log[A] M; four drugs, one receptor',
 stem:'The DRCs below represent the DRC of four different drugs acting on the same receptor. Which statement is CORRECT?',
 options:[
  {t:'A is the most potent drug', correct:false, miss:'read', why:'Correct (A has the smallest ED50), but not the only correct statement.'},
  {t:'C is the most efficacious drug', correct:false, miss:'read', why:'Correct (C reaches the highest response), but not the only correct statement.'},
  {t:'D is the least efficacious drug', correct:false, miss:'read', why:'Correct (D plateaus lowest), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'Potency from the ED50 (A), efficacy from the plateau (C highest, D lowest): all three readings are right.'}],
 teach:'Three readings from one figure: the smallest ED50 is A (most potent), the highest plateau is C (most efficacious), the lowest plateau is D (least efficacious). When every statement checks out, choose all of the above.',
 quote:'If it requires the smallest amount of drug to produce equivalent responses, right? Another way of doing it is if you can find the ED50',
 cite:'PollEV_s.pdf page 4; transcript 9/29'},

/* ---------------- A–E response figure, B is the agonist alone (PollEV_s.pdf pages 3 and 5) ---------------- */
{id:'FG-003', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'figure',
 concept:'allosteric-agonist-affinity-only', tags:['poll','figure-drill','diazepam','drug-list'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'DRC B is the DRC of GABA alone at its receptor. Which DRC best represents GABA in the presence of diazepam, an allosteric agonist that affects only affinity?',
 options:[
  {t:'A', correct:true, why:'Diazepam helps GABA: more affinity means a shift to the left, and affinity only means the top stays at 100%. A is the one curve left of B.'},
  {t:'B', correct:false, miss:'shift', why:'B is GABA alone, the point of reference; the allosteric agonist moves the curve.'},
  {t:'C', correct:false, miss:'direction', why:'C is to the right with a lower top: a drug making life more difficult, not a helper.'},
  {t:'D', correct:false, miss:'direction', why:'D is to the right of B: GABA was made less potent; diazepam helps.'},
  {t:'None of the above', correct:false, miss:'shift', why:'A shows the left shift at the same top that an allosteric agonist on affinity produces.'}],
 teach:'Diazepam is the allosteric agonist on the drug list: it binds the GABA receptor at its own site and helps GABA. Helping means more potent, a shift to the left; affinity only means the ability to produce the effect is untouched, so the top stays. From B that is A.',
 quote:'Help, which means you’re gonna make the drug more potent, right? And it because it only affects affinity, you’re not affecting the ability to produce its effect, is moving to the left.',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'FG-004', fg:'inverse', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'figure',
 concept:'competitive-vs-inverse-baseline-zero', tags:['poll','figure-drill','loratadine','drug-list'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'DRC B is the DRC of histamine alone at the H1 receptor. Which DRC best represents histamine in the presence of loratadine?',
 options:[
  {t:'A', correct:false, miss:'direction', why:'A is a shift to the left: histamine was helped. Loratadine competes with it.'},
  {t:'B', correct:false, miss:'shift', why:'B is histamine alone; loratadine moves the curve.'},
  {t:'C', correct:false, miss:'emax', why:'C has lost its top; loratadine is reversible and never lowers the Emax.'},
  {t:'D', correct:true, why:'Loratadine competes with histamine (shift to the right) and is reversible (same Emax); with the baseline already at 0 it has nothing to bring down, so it looks like a competitive antagonist: D.'},
  {t:'E', correct:false, miss:'emax', why:'E is to the right with a lower top: the irreversible pattern, and loratadine is reversible.'}],
 teach:'Loratadine is the inverse agonist: it competes with histamine (shift to the right), it is reversible (no change to the Emax), and it wants the baseline at 0. On this figure the baseline is already 0, so the inverse agonist and the competitive antagonist give the same picture, and the curve is D.',
 quote:'Because my baseline is 0, the inverse wants to keep at 0, and the competitive doesn’t care',
 cite:'PollEV_s.pdf page 5; transcript 9/29, 9/30'},

{id:'FG-005', fg:'competitive', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'figure',
 concept:'competitive-antagonist-shift', tags:['poll','figure-drill','prazosin','drug-list'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'DRC B is the DRC of NE alone at the α1 receptor. Which DRC best represents NE in the presence of prazosin?',
 options:[
  {t:'A', correct:false, miss:'direction', why:'A is a left shift: NE was helped. Prazosin blocks α1.'},
  {t:'B', correct:false, miss:'shift', why:'B is NE alone; an antagonist moves the curve.'},
  {t:'C', correct:false, miss:'emax', why:'C has lost its top; prazosin is reversible and the Emax is unchanged.'},
  {t:'D', correct:true, why:'Prazosin is a reversible α1 antagonist: right shift, same baseline, same Emax. D is the one curve right of B at 100%.'},
  {t:'E', correct:false, miss:'emax', why:'E is right and lower: that is phenoxybenzamine, the irreversible α antagonist, not prazosin.'}],
 teach:'Prazosin binds α1 without activating it and blocks NE there reversibly: every drug on the list is reversible and competitive except phenoxybenzamine. A competitive antagonist shifts NE to the right with no change to the baseline or the Emax, so from B the answer is D; C or E would be phenoxybenzamine.',
 quote:'If it was just like a competitive antagonist. ... OK, so D would be the best answer for that.',
 cite:'PollEV_s.pdf page 5; transcript 9/29'},

/* ---------------- Figure 1, 50% baseline (PollEV_s.pdf page 3) ---------------- */
{id:'FG-006', fg:'partial', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'partial-agonist-table', tags:['poll','figure-drill','aripiprazole','drug-list'], source:'both',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises below 100%, C stays flat at 50%, D falls part way, E falls to 0%', imgCap:'Figure 1: five drugs given alone, each starting from the 50% baseline',
 stem:'The DRCs below represent the individual DRC of 5 different drugs at the dopamine D2 receptor. DRC "B" most likely represents the DRC of:',
 options:[
  {t:'Dopamine', correct:false, miss:'emax', why:'Dopamine is a full agonist; alone it goes all the way up to 100% (curve A).'},
  {t:'Aripiprazole', correct:true, why:'Curve B rises from the baseline but stops short of 100%: a partial agonist, and aripiprazole is the partial agonist at D2 on the drug list.'},
  {t:'Loratadine', correct:false, miss:'baseline', why:'Loratadine is the inverse agonist; it takes the baseline down to 0 (curve E), and it acts at H1, not D2.'},
  {t:'Metoprolol', correct:false, miss:'baseline', why:'Metoprolol is a neutral antagonist; alone it leaves the baseline flat (curve C).'},
  {t:'Phenoxybenzamine', correct:false, miss:'baseline', why:'Phenoxybenzamine is an antagonist; antagonists do not change the baseline.'}],
 teach:'Classify first, then match the drug list. B goes up from the 50% baseline but stops below 100%: a partial agonist. At the D2 receptor the partial agonist on the list is aripiprazole; dopamine, the full agonist, would be A. Antagonists stay flat, and only the inverse agonist goes down to 0.',
 quote:'B and D will be a partial agonist ... albuterol',
 cite:'PollEV_s.pdf page 3; transcript 9/28, 9/30'},

{id:'FG-007', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'baseline-reflects-receptor-activity', tags:['poll','figure-drill','phenylephrine','drug-list'], source:'both',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises below 100%, C stays flat at 50%, D falls part way, E falls to 0%', imgCap:'Figure 1: five drugs given alone, each starting from the 50% baseline',
 stem:'The DRCs below represent the individual DRC of 5 different drugs at the α1 receptor. DRC "A" most likely represents the DRC of:',
 options:[
  {t:'Phenylephrine', correct:true, why:'Curve A goes from the 50% baseline all the way to 100%: a full agonist, and phenylephrine is the α1 agonist on the drug list.'},
  {t:'Prazosin', correct:false, miss:'baseline', why:'Prazosin is a reversible α1 antagonist: affinity but no efficacy, flat at the baseline (curve C).'},
  {t:'Pindolol', correct:false, miss:'emax', why:'Pindolol is a partial agonist (at β receptors); a partial agonist stops short of 100% (curve B).'},
  {t:'Loratadine', correct:false, miss:'baseline', why:'Loratadine is the inverse agonist; it brings the baseline down to 0 (curve E).'},
  {t:'Diphenhydramine', correct:false, miss:'baseline', why:'Diphenhydramine is a histamine receptor antagonist; an antagonist alone does not move the baseline.'}],
 teach:'A full agonist starts at the baseline and goes all the way to 100%: curve A. At the α1 receptor the full agonist on the list is phenylephrine. Prazosin and diphenhydramine are antagonists (flat), pindolol is a partial agonist (stops short), loratadine is the inverse agonist (down to 0).',
 quote:'Where would I start? I start at 50 because that’s where my baseline is now, right?',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

/* ---------------- Dotted line, three right shifts, same top (PollEV_s.pdf page 3) ---------------- */
{id:'FG-008', fg:'competitive', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'drug-x-metoprolol', tags:['poll','figure-drill','diphenhydramine','drug-list'], source:'both',
 img:'pollev-dotted-x', imgAlt:'A dotted concentration-response curve and three solid curves shifted progressively to the right, all reaching 100%', imgCap:'Dotted line: agonist alone; solid lines: agonist with increasing doses of drug X',
 stem:'The dotted line represents the DRC of histamine alone and the solid lines represent the DRC of histamine in the presence of increasing doses of drug "X." Drug X is most likely:',
 options:[
  {t:'Epinephrine', correct:false, miss:'class', why:'Epinephrine is a full agonist at α and β receptors; it does not compete with histamine at its receptor.'},
  {t:'Histamine', correct:false, miss:'direction', why:'More histamine is the same drug: it would not shift its own curve to the right.'},
  {t:'Diazepam', correct:false, miss:'class', why:'Diazepam is the allosteric agonist at the GABA receptor; it helps, it does not make life more difficult.'},
  {t:'Diphenhydramine', correct:true, why:'The figure shows a reversible, competitive antagonist (right shift, same baseline and Emax), and diphenhydramine is the histamine receptor antagonist on the drug list.'},
  {t:'Phenoxybenzamine', correct:false, miss:'emax', why:'Phenoxybenzamine is the only irreversible drug on the list; it would lower the Emax, which stays at 100% here.'}],
 teach:'Read the class first: shift to the right, no change to the baseline, no change to the Emax, symmetrical shifts: a competitive, reversible antagonist. Then match the list at the histamine receptor: diphenhydramine binds H1 and H2 and blocks histamine reversibly. Phenoxybenzamine would drop the Emax; diazepam and epinephrine do not act at this receptor.',
 quote:'Benadryl not only binds to the H1, it binds to the H2. It binds to muscarinic receptors. It’s very non-selective.',
 cite:'PollEV_s.pdf page 3; transcript 9/22, 9/28'},

/* ---------------- Dotted line with the falling baseline (PollEV_s.pdf page 5) ---------------- */
{id:'FG-009', fg:'inverse', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'fa-plus-inverse-agonist', tags:['poll','figure-drill','loratadine'], source:'both',
 img:'pollev-dotted-inverse', imgAlt:'A dotted concentration-response curve starting near 40% and rising to about 90%, and four solid curves shifted progressively to the right whose starting points fall toward 0% while their maximum stays the same', imgCap:'Dotted line: agonist alone; solid lines: agonist with increasing doses of drug X',
 stem:'The dotted line is the agonist alone and the solid lines are the agonist with increasing doses of drug X. Which statement is CORRECT about drug X?',
 options:[
  {t:'It shifts the agonist to the right', correct:false, miss:'read', why:'Correct (each dose needs more agonist: X competes with it), but not the only correct statement.'},
  {t:'It lowers the baseline toward 0', correct:false, miss:'read', why:'Correct (the starting points fall with each dose: negative efficacy), but not the only correct statement.'},
  {t:'It does not change the Emax', correct:false, miss:'read', why:'Correct (every solid curve reaches the same top: X is reversible), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'Right shift, falling baseline, unchanged Emax: the three readings that make X an inverse agonist, loratadine.'}],
 teach:'The three questions on this figure: is it shifting? Yes, to the right, so X competes with the agonist. Is the Emax changing? No, so X is reversible. Is the baseline changing? Yes, down to 0, so X has negative efficacy. All three statements hold, and together they name the inverse agonist.',
 quote:'Because it’s bringing the baseline down to zero. It’s competing with my agonist, so it’s shifting to the right, and it’s reversible, so it’s not affecting the ability of my agonist to get to the max response.',
 cite:'PollEV_s.pdf page 5; transcript 9/29'},

/* ---------------- Kd table (PollEV_s.pdf pages 1–2) ---------------- */
{id:'FG-010', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'apply',
 concept:'kd-compare-receptors', tags:['poll','figure-drill','kd'], source:'both',
 img:'pollev-kd-table', imgAlt:'Table of Kd values for Drug A and Drug B at beta-1, beta-2 and M1 receptors', imgCap:'Dissociation constants (Kd) of two drugs at three receptors',
 stem:'Which statement is CORRECT about the two drugs in the table?',
 options:[
  {t:'Drug B has the greater affinity for the β1 receptor', correct:false, miss:'read', why:'Correct (100 nM is smaller than 30 µM), but not the only correct statement.'},
  {t:'The two drugs have equal affinity for the M1 receptor', correct:false, miss:'read', why:'Correct (both 250 nM), but not the only correct statement.'},
  {t:'Drug A binds M1 with greater affinity than it binds β1 or β2', correct:false, miss:'read', why:'Correct (250 nM is smaller than 30 µM and 1 mM), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'Convert the units and every statement holds: nano is smaller than micro is smaller than milli.'}],
 teach:'The smaller the Kd, the greater the affinity, and the units decide: nano 10^-9, micro 10^-6, milli 10^-3. At β1, 100 nM (B) beats 30 µM (A). At M1 both are 250 nM. Down the Drug A column, 250 nM at M1 is its smallest Kd. All three statements are correct.',
 quote:'So if you only focus on the number, you’re going to miss the question in the exam. You’ve got to look at the units as well.',
 cite:'PollEV_s.pdf pages 1–2; transcript 9/24'},

/* ---------------- Two hearts (PollEV_s.pdf page 2) ---------------- */
{id:'FG-011', fg:'spare', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'apply',
 concept:'receptor-number-potency', tags:['poll','figure-drill','potency'], source:'both',
 img:'pollev-two-hearts', imgAlt:'Two dishes, one with 10 receptors and one with 100 receptors, each receiving 1000 nM of drug', imgCap:'Same dose of norepinephrine, two receptor numbers',
 stem:'The same 1000 nM dose of NE is given to a dish with 10 receptors and to a dish with 100 receptors. Which statement is CORRECT?',
 options:[
  {t:'NE appears more potent in the dish with 100 receptors', correct:false, miss:'read', why:'Correct (more receptors, more binding by the law of mass action), but not the only correct statement.'},
  {t:'The Kd of NE is the same in both dishes', correct:false, miss:'read', why:'Correct (the Kd belongs to the drug–receptor pair, which did not change), but not the only correct statement.'},
  {t:'The curve for the 100-receptor dish sits to the left', correct:false, miss:'read', why:'Correct (more potent means a shift to the left), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'The tissue changed, not the drug: potency rises and the curve shifts left while Kd, affinity and efficacy stay the same.'}],
 teach:'More receptors mean a greater statistical chance of binding, so fewer NE molecules are needed to occupy the same number of receptors: NE appears more potent and its curve shifts to the left. The drug did not change, so its Kd, affinity and efficacy are the same in both dishes. Potency is affinity, efficacy and the tissue.',
 quote:'So the more receptors you have based on the laws of mass action, the greater the statistical probability of binding something ... Then it’s going to appear to have a greater potency than it does with less receptors.',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'FG-012', fg:'spare', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'predict', skill:'apply',
 concept:'receptor-number-potency', tags:['poll','figure-drill','regulation'], source:'both',
 img:'pollev-two-hearts', imgAlt:'Two dishes, one with 10 receptors and one with 100 receptors, each receiving 1000 nM of drug', imgCap:'Same dose of norepinephrine, two receptor numbers',
 stem:'A heart that had 100 receptors down-regulates them to 10 after chronic exposure to an agonist. What happens to the potency of NE in that heart?',
 options:[
  {t:'Increase', correct:false, miss:'potency', why:'Fewer receptors mean more NE is needed to bind the same number; potency goes down, not up.'},
  {t:'Decrease', correct:true, why:'Decreasing the number of receptors decreases the potency of an agonist: the curve shifts to the right.'},
  {t:'No change', correct:false, miss:'potency', why:'Affinity and efficacy do not change, but potency also depends on the tissue, and the tissue lost receptors.'}],
 teach:'The two-hearts figure read the other way: going from 100 receptors to 10, NE needs a higher dose for the same effect, so its potency decreases and the curve shifts to the right. The body does this itself: too much activation by an agonist down-regulates the receptors.',
 quote:'Decreasing the number of receptors may lead to decrease in the potency of an agonist',
 cite:'PollEV_s.pdf pages 2 and 5; transcript 9/24, 9/29'},

/* ---------------- Gs cascade (PollEV_s.pdf page 1) ---------------- */
{id:'FG-013', fg:'gpcr-steps', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'effector-ac-plc', tags:['poll','figure-drill','gpcr'], source:'both',
 img:'pollev-gs-cascade', imgAlt:'Norepinephrine, beta-1 receptor, Gs, adenylate cyclase, cAMP, PKA and calcium in a heart cell', imgCap:'Norepinephrine at the β1 receptor of a heart cell',
 stem:'In the pathway shown, which component is the effector system, the signal amplifier?',
 options:[
  {t:'NE (norepinephrine), the first messenger', correct:false, miss:'steps', why:'Norepinephrine is the signal.'},
  {t:'β1 receptor', correct:false, miss:'steps', why:'The receptor receives the signal.'},
  {t:'Gs protein', correct:false, miss:'steps', why:'Gs is the transducer that translates the change in the receptor.'},
  {t:'AC (adenylate cyclase)', correct:true, why:'Adenylate cyclase is the effector: the enzyme the α subunit activates, which makes the second messenger cAMP from ATP.'},
  {t:'cAMP', correct:false, miss:'steps', why:'cAMP is the second messenger that AC makes.'}],
 teach:'Signal: NE. Receptor: β1. Transducer: Gs, defined by its α subunit. Effector: adenylate cyclase (AC), the amplifier that makes cAMP from ATP. Second messenger: cAMP. There are two effector systems for the α subunits, AC and PLC.',
 quote:'A signal amplifier is going to be our factor system such as AC or PLC. Those are the enzymes that are going to be making a camp or IP3 and carry on the signal inside',
 cite:'PollEV_s.pdf page 1; transcript 9/23, 9/30'},

/* ---------------- Quantal curves (PollEV_s.pdf page 5) ---------------- */
{id:'FG-014', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'therapeutic-index-calc', tags:['poll','figure-drill','therapeutic-index'], source:'both',
 img:'pollev-quantal-ti', imgAlt:'Two quantal curves, percentage of individuals responding against dose in µg/kg: hypnosis on the left with ED50 at 100 and ED99 at 200; death on the right with LD1 at about 200 and LD50 at 400', imgCap:'Quantal dose-response curves for hypnosis and death; dose in µg/kg',
 stem:'Which statement is CORRECT about the drug in the figure?',
 options:[
  {t:'Its ED50 is 100 µg/kg', correct:false, miss:'read', why:'Correct (the hypnosis curve crosses 50% at 100), but not the only correct statement.'},
  {t:'Its LD50 is 400 µg/kg', correct:false, miss:'read', why:'Correct (the death curve crosses 50% at 400), but not the only correct statement.'},
  {t:'Its therapeutic index is 4', correct:false, miss:'read', why:'Correct (400 divided by 100), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'ED50 100, LD50 400, TI = LD50 / ED50 = 4: every statement holds.'}],
 teach:'Draw a line at 50% of individuals responding: the hypnosis curve gives the ED50, 100 µg/kg, and the death curve gives the LD50, 400 µg/kg. The therapeutic index is the lethal dose that kills 50% divided by the effective dose that treats 50%: 400 / 100 = 4.',
 quote:'So you know how to calculate the TI, right? The lethal dose that kills 50% divided by the effective dose that treats 50% of the population',
 cite:'PollEV_s.pdf page 5; transcript 9/29'},

{id:'FG-015', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'predict', skill:'calc',
 concept:'therapeutic-index-calc', tags:['poll','figure-drill','therapeutic-index'], source:'both',
 img:'pollev-quantal-ti', imgAlt:'Two quantal curves, percentage of individuals responding against dose in µg/kg: hypnosis on the left with ED50 at 100 and ED99 at 200; death on the right with LD1 at about 200 and LD50 at 400', imgCap:'Quantal dose-response curves for hypnosis and death; dose in µg/kg',
 stem:'A second drug has an ED50 of 10 µg/kg and an LD50 of 160 µg/kg. Compared with the drug in the figure, the second drug is:',
 options:[
  {t:'Safer', correct:true, why:'160 / 10 = 16, against 400 / 100 = 4 for the drug in the figure; the larger the TI, the safer the drug.'},
  {t:'More toxic', correct:false, miss:'ti', why:'A TI of 16 is larger than 4; larger is safer, not more toxic.'},
  {t:'Equally safe', correct:false, miss:'ti', why:'The two therapeutic indexes differ: 16 against 4.'},
  {t:'Cannot be compared without the ED99', correct:false, miss:'ti', why:'The therapeutic index is LD50 / ED50; both numbers are given for each drug.'}],
 teach:'TI = LD50 / ED50. The figure gives 400 / 100 = 4; the second drug gives 160 / 10 = 16. The larger the therapeutic index, the safer the drug, so the second drug is safer. This is the only math on the exam: whole numbers, divide.',
 quote:'the larger the TI is, the therapeutic index, the safer a drug is going to be',
 cite:'PollEV_s.pdf page 5; transcript 9/29'},

/* ---------------- Jeopardy: A dashed, A + B in four equal steps (IMG_3014) ---------------- */
{id:'FG-016', fg:'competitive', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'drug-x-metoprolol', tags:['poll','figure-drill','metoprolol','drug-list'], source:'both',
 img:'jeop-a-plus-b', imgAlt:'Response percent of control against agonist concentration from 10^-9 to 10^-3 M: a dashed red curve A on the left, then four solid curves A + [B], A + 10x[B], A + 100x[B] and A + 1000x[B] shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'Dotted: drug A alone; solid: A with increasing concentrations of B',
 stem:'Drug A is norepinephrine at the β1 receptor. Drug B is most likely:',
 options:[
  {t:'Epinephrine', correct:false, miss:'direction', why:'Epinephrine is a full agonist; it would shift norepinephrine to the left.'},
  {t:'Albuterol', correct:false, miss:'baseline', why:'Albuterol is the partial agonist; it has efficacy and would change the baseline.'},
  {t:'Phenoxybenzamine', correct:false, miss:'emax', why:'Phenoxybenzamine is irreversible; four doses would bring the top down, and the top never moves here.'},
  {t:'Metoprolol', correct:true, why:'Right shifts in equal steps with the baseline and the top unchanged: a competitive, reversible antagonist, and metoprolol is the β1 antagonist on the list.'},
  {t:'Diazepam', correct:false, miss:'class', why:'Diazepam is the allosteric agonist at the GABA receptor; it would help, not hinder.'}],
 teach:'Read the class first: B shifts A to the right without affecting the baseline or the Emax, in equal steps, so B is a competitive antagonist. Then the list: metoprolol is the competitive β1 antagonist; epinephrine helps, albuterol has efficacy, phenoxybenzamine lowers the top, diazepam is an allosteric agonist.',
 quote:'It’s shifting the dose to the right without affecting the baseline or the Emax. Thus cannot be irreversible. It can’t be allosteric agonist or full agonist or partial agonist, so it has to be competitive antagonist.',
 cite:'Jeopardy 9/30 (IMG_3014); transcript 9/28, 9/30'},

{id:'FG-017', fg:'irreversible', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'irreversible-antagonist-curve', tags:['poll','figure-drill','phenoxybenzamine'], source:'both',
 img:'jeop-a-plus-b', imgAlt:'Response percent of control against agonist concentration from 10^-9 to 10^-3 M: a dashed red curve A on the left, then four solid curves A + [B], A + 10x[B], A + 100x[B] and A + 1000x[B] shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'Dotted: drug A alone; solid: A with increasing concentrations of B',
 stem:'Which feature of the figure rules out phenoxybenzamine as drug B?',
 options:[
  {t:'The shift to the right with each tenfold dose of B', correct:false, miss:'emax', why:'An irreversible antagonist also shifts the agonist to the right; the shift does not rule it out.'},
  {t:'The baseline staying at 0 on every curve', correct:false, miss:'emax', why:'No antagonist changes the baseline, irreversible or not.'},
  {t:'The top staying the same across four doses of B', correct:true, why:'An irreversible antagonist removes receptors, so the Emax falls as the dose goes up; four doses with no drop in the top rule it out.'},
  {t:'The dashed curve being drug A alone', correct:false, miss:'read', why:'The dashed curve is the point of reference; it says nothing about what B is.'}],
 teach:'Phenoxybenzamine is the one irreversible drug on the list: it forms covalent bonds and chemically down-regulates the receptors, so the agonist loses its ability to reach the Emax. Here B was given at four doses, up to 1000 times, and the top never dropped, so B is not irreversible.',
 quote:'Fenoxbenzammine is the only irreversible that is on your list',
 cite:'Jeopardy 9/30 (IMG_3014); transcript 9/28, 9/30'},

{id:'FG-018', fg:'competitive', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'competitive-antagonist-shift', tags:['poll','figure-drill'], source:'both',
 img:'jeop-a-plus-b', imgAlt:'Response percent of control against agonist concentration from 10^-9 to 10^-3 M: a dashed red curve A on the left, then four solid curves A + [B], A + 10x[B], A + 100x[B] and A + 1000x[B] shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'Dotted: drug A alone; solid: A with increasing concentrations of B',
 stem:'Each solid curve sits one equal step to the right of the last as the dose of B goes up tenfold. What does the equal spacing tell you about B?',
 options:[
  {t:'B is competitive: ten times more B needs ten times more A', correct:true, why:'Symmetrical shifts follow the law of mass action: to outcompete ten times the antagonist, the agonist dose has to go up ten times, with no limit.'},
  {t:'B is allosteric: its shifts saturate', correct:false, miss:'symmetry', why:'An allosteric drug gives unequal shifts that stop once its own sites are full; these steps are equal.'},
  {t:'B is irreversible: the receptors it binds are being removed', correct:false, miss:'emax', why:'Removing receptors would bring the top down with each dose; the top is unchanged.'},
  {t:'B is a partial agonist: it adds a little efficacy', correct:false, miss:'baseline', why:'A drug with efficacy would move the baseline; the baseline stays at 0.'}],
 teach:'A competitive antagonist and the agonist compete for the same site, so if the antagonist dose goes up ten times, the agonist dose has to go up ten times to outcompete it. That gives symmetrical shifts with no limit. Unequal, saturating shifts would be allosteric; a falling top would be irreversible.',
 quote:'So what would happen if I give now 10 times the dose of my antagonist? Well, I have to increase the dose of my agonist by 10 times in order to outcompete that drug.',
 cite:'Jeopardy 9/30 (IMG_3014); transcript 9/28'},

{id:'FG-019', fg:'competitive', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'recall',
 concept:'antagonist-synonyms', dupOf:'PE-048', tags:['poll','figure-drill','competitive'], source:'both',
 img:'jeop-a-plus-b', imgAlt:'Response percent of control against agonist concentration from 10^-9 to 10^-3 M: a dashed red curve A on the left, then four solid curves A + [B], A + 10x[B], A + 100x[B] and A + 1000x[B] shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'Dotted: drug A alone; solid: A with increasing concentrations of B',
 stem:'Dotted line is Drug A alone, solid lines is A in the presence of increasing concentrations of B. Which statement is CORRECT about B?',
 options:[
  {t:'It is reversible', correct:false, miss:'read', why:'Correct (it binds and comes off, which is why the top never drops), but not the only correct statement.'},
  {t:'It is surmountable', correct:false, miss:'read', why:'Correct (enough A overcomes every dose of B), but not the only correct statement.'},
  {t:'It competes with A for the same site', correct:false, miss:'read', why:'Correct (orthosteric competition gives the equal steps), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'Competitive, reversible and surmountable are three names for the same drug.'}],
 teach:'The figure shows a competitive antagonist: four right shifts, same baseline, same top. Competitive, reversible and surmountable are different names for the same drug: it competes with the agonist for the same site, binds and comes off, and a higher dose of agonist overcomes it.',
 quote:'One is competitive antagonist, also known as reversible antagonists, also known as surmountable antagonists, different names for the same drug. They bind and they come off.',
 cite:'Jeopardy 9/30 (IMG_3014); transcript 9/28'},

/* ---------------- Jeopardy: A–E, Effect vs Log [Agonist] (IMG_3015, IMG_9316, IMG_9320) ---------------- */
{id:'FG-020', fg:'partial', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure', multi:true,
 concept:'five-drug-classification', tags:['poll','figure-drill','full-agonist'], source:'both',
 img:'jeop-abcde-effect', imgAlt:'Five dose-response curves A to E, effect from 0.0 to 100% against log agonist; left to right A, B, C, D, E; B and E reach 100%, C plateaus at about 85%, D at about 70%, A at about 65%', imgCap:'Effect vs Log [Agonist]',
 stem:'The five curves are five different drugs acting on the same receptor. Which of these drugs are full agonists? Select all that apply.',
 options:[
  {t:'A', correct:false, miss:'efficacy', why:'A is the most potent but plateaus at about 65%; a drug that cannot reach 100% is a partial agonist.'},
  {t:'B', correct:true, why:'B reaches 100% of the effect.'},
  {t:'C', correct:false, miss:'efficacy', why:'C plateaus at about 85%: a partial agonist.'},
  {t:'D', correct:false, miss:'efficacy', why:'D plateaus at about 70%: a partial agonist.'},
  {t:'E', correct:true, why:'E also reaches 100%, at the highest dose: full efficacy, lowest affinity.'}],
 teach:'Full against partial is decided on the y-axis: only curves that reach 100% are full agonists. On this figure B and E reach the top; A, C and D stop short, so they are partial agonists no matter how far left they sit. A is the most potent drug and still a partial agonist; E is the least potent and still a full agonist.',
 quote:'If you can’t get your 100%, you’re not a full agonist, right?',
 cite:'Jeopardy 9/30 (IMG_3015); transcript 9/24 (his rule on the Day 3 five-curve figure)'},

{id:'FG-021', fg:'irreversible', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'figure', multi:true,
 concept:'irreversible-antagonist-curve', tags:['poll','figure-drill','phenoxybenzamine','drug-list'], source:'both',
 img:'jeop-abcde-effect', imgAlt:'Five dose-response curves A to E, effect from 0.0 to 100% against log agonist; left to right A, B, C, D, E; B and E reach 100%, C plateaus at about 85%, D at about 70%, A at about 65%', imgCap:'Effect vs Log [Agonist]; B is norepinephrine alone',
 stem:'DRC "B" is the DRC of NE alone. Which DRCs could represent NE in the presence of phenoxybenzamine? Select all that apply.',
 options:[
  {t:'A', correct:false, miss:'direction', why:'A is to the left: NE was helped. Phenoxybenzamine is an antagonist.'},
  {t:'C', correct:true, why:'Right of B with a lower top (about 85%): an irreversible antagonist while spare receptors still soften the drop.'},
  {t:'D', correct:true, why:'Right of B with a lower top (about 70%): the irreversible pattern he keyed for phenoxybenzamine on this figure.'},
  {t:'E', correct:false, miss:'emax', why:'E is to the right but still reaches 100%: a competitive antagonist (metoprolol), not an irreversible one.'}],
 teach:'Phenoxybenzamine is the only irreversible antagonist on the list: it shifts NE to the right and, once the spare receptors are gone, lowers the Emax. From B, both C and D are right and lower; he said an irreversible antagonist could be either of two such curves depending on how many spare receptors the tissue has. E keeps 100% and is the competitive pattern.',
 quote:'If it was an irreversible, it could be either C or E, right, depending on how much spare receptors they would have.',
 cite:'Jeopardy 9/30 (IMG_9320); transcript 9/29, 9/30'},

{id:'FG-022', fg:'partial', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'five-curve-lowest-efficacy', tags:['poll','figure-drill','efficacy'], source:'both',
 img:'jeop-abcde-effect', imgAlt:'Five dose-response curves A to E, effect from 0.0 to 100% against log agonist; left to right A, B, C, D, E; B and E reach 100%, C plateaus at about 85%, D at about 70%, A at about 65%', imgCap:'Effect vs Log [Agonist]',
 stem:'Which drug is the least efficacious?',
 options:[
  {t:'A', correct:true, why:'A plateaus lowest, at about 65%: the least efficacious drug, even though it is the most potent.'},
  {t:'B', correct:false, miss:'read', why:'B reaches 100%: a full agonist.'},
  {t:'C', correct:false, miss:'efficacy', why:'C plateaus at about 85%, above A.'},
  {t:'D', correct:false, miss:'efficacy', why:'D plateaus at about 70%, above A.'},
  {t:'E', correct:false, miss:'potency', why:'E is the least potent (farthest right) but reaches 100%: a full agonist. Least potent is not least efficacious.'}],
 teach:'Efficacy is the height of the plateau. On this figure A, the farthest-left curve, plateaus lowest, so A is the least efficacious drug and at the same time the most potent. E is the least potent, a different question. The trap is reading potency when the question asks for efficacy.',
 quote:'Affinity is gonna be on the bottom, efficacy is gonna be on the Y axis, and potency is gonna be a combination of the two',
 cite:'Jeopardy 9/30 (IMG_9316); transcript 9/24, 9/30'},

/* ---------------- Part 3: therapeutic efficacy ---------------- */
{id:'FG-023', fg:'potency', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'therapeutic-efficacy-figure', tags:['poll','figure-drill'], source:'both',
 img:'p3-therapeutic-efficacy', imgAlt:'Analgesic effect against log dose for three drugs: morphine and meperidine rise to the same high plateau, morphine to the left of meperidine; ibuprofen sits to the right and plateaus much lower', imgCap:'Analgesic effect vs log dose: morphine, meperidine, ibuprofen',
 stem:'The curves show the analgesic effect of three drugs against log dose. Which statement is CORRECT?',
 options:[
  {t:'Morphine is the most potent of the three', correct:false, miss:'read', why:'Correct (farthest left), but not the only correct statement.'},
  {t:'Morphine and meperidine have the same therapeutic efficacy', correct:false, miss:'read', why:'Correct (same plateau), but not the only correct statement.'},
  {t:'Ibuprofen has the lowest therapeutic efficacy', correct:false, miss:'read', why:'Correct (lowest plateau), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'Potency from left to right, efficacy from the plateau: all three statements hold.'}],
 teach:'Left to right is potency: morphine is the farthest left, the most potent. Up and down is therapeutic efficacy: morphine and meperidine reach the same high plateau, ibuprofen a much lower one. All three statements are correct.',
 quote:'If you got a boo boo that is just, you know, you’re working in the backyard and you hurt your feet, maybe ibuprofen might cut. You may not need to go to morphine',
 cite:'Pharmacodynamics-Day_4_&_5_2026s_Part 3.pdf page 2; transcript 9/30'},

{id:'FG-024', fg:'potency', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'apply',
 concept:'therapeutic-efficacy-figure', tags:['poll','figure-drill'], source:'both',
 img:'p3-therapeutic-efficacy', imgAlt:'Analgesic effect against log dose for three drugs: morphine and meperidine rise to the same high plateau, morphine to the left of meperidine; ibuprofen sits to the right and plateaus much lower', imgCap:'Analgesic effect vs log dose: morphine, meperidine, ibuprofen',
 stem:'A patient with a broken leg needs the highest level of pain relief on the figure. Which drug could NOT provide it at any dose?',
 options:[
  {t:'Morphine', correct:false, miss:'efficacy', why:'Morphine reaches the high plateau.'},
  {t:'Meperidine', correct:false, miss:'efficacy', why:'Meperidine reaches the same high plateau as morphine; it only needs a larger dose.'},
  {t:'Ibuprofen', correct:true, why:'Ibuprofen plateaus far below the opioids: no dose takes it to the higher level of relief.'},
  {t:'All three can reach it', correct:false, miss:'read', why:'The plateaus differ; ibuprofen never reaches the opioid level.'}],
 teach:'Therapeutic efficacy is the plateau: the maximal relief a drug can give no matter the dose. Ibuprofen plateaus lower, enough for a small hurt but not for a broken leg; morphine and meperidine both reach the higher level, morphine at the smaller dose.',
 quote:'Some patients, if you broke your leg, probably will be begging for morphine.',
 cite:'Pharmacodynamics-Day_4_&_5_2026s_Part 3.pdf page 2; transcript 9/30'},

/* ---------------- Review page 5: Rt figure, irreversible ---------------- */
{id:'FG-025', fg:'irreversible', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'three-questions-irreversible', tags:['poll','figure-drill'], source:'both',
 img:'rev-rt-figure', imgAlt:'Fractional maximum response against log agonist: the leftmost curve, labelled Rt = 1, reaches 1.0; the curves to its right, labelled x10^-1, x10^-2 and x10^-3, shift progressively right and plateau lower and lower; a dashed line through the half-maximal points curves down to a point marked KA', imgCap:'Drug A alone (left) and drug A with increasing concentrations of drug C (right)',
 stem:'The curve on the left is drug A alone; the curves on the right are A with increasing concentrations of drug C. Which of the three questions identifies C as an irreversible antagonist?',
 options:[
  {t:'Is it shifting? Yes, to the right with each dose of C', correct:false, miss:'emax', why:'The right shift only removes the helpers; competitive and inverse agonists shift right too.'},
  {t:'Is the baseline changing? No', correct:false, miss:'emax', why:'The baseline is at 0 and does not help here.'},
  {t:'Is the Emax changing? Yes, it falls with each dose', correct:true, why:'Only an irreversible antagonist (or an allosteric antagonist on efficacy) lowers the Emax; the competitive and inverse drugs never touch it.'},
  {t:'Are the shifts symmetrical? Yes', correct:false, miss:'emax', why:'Symmetry separates competitive from allosteric; it does not identify the irreversible antagonist.'}],
 teach:'Shift? Yes, right: the agonists are out. Baseline? No change, and at 0 it cannot help. Emax? Yes, it goes down with every dose of C: both the inverse agonist and the reversible antagonist are competitive and never affect the Emax, so C is irreversible.',
 quote:'Is the Emax changing. Definitely. Where is it going? It’s going down. So if it’s going down, who can it be? Irreversible, right? Because both inverse and reversible are competitive. They will never affect the Emax.',
 cite:'Pharmacodynamics reviews.pdf page 5; transcript 9/30'},

{id:'FG-026', fg:'irreversible', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'drug-x-phenoxybenzamine', tags:['poll','figure-drill','phenoxybenzamine','drug-list'], source:'both',
 img:'rev-rt-figure', imgAlt:'Fractional maximum response against log agonist: the leftmost curve, labelled Rt = 1, reaches 1.0; the curves to its right, labelled x10^-1, x10^-2 and x10^-3, shift progressively right and plateau lower and lower; a dashed line through the half-maximal points curves down to a point marked KA', imgCap:'Drug A alone (left) and drug A with increasing concentrations of drug C (right)',
 stem:'Drug A is norepinephrine. The curve on the left is NE alone; the curves on the right are NE with increasing concentrations of drug C. Drug C is most likely:',
 options:[
  {t:'Metoprolol', correct:false, miss:'emax', why:'Metoprolol is competitive and reversible; it would shift NE right with the Emax unchanged.'},
  {t:'Loratadine', correct:false, miss:'emax', why:'Loratadine is the inverse agonist; it is reversible and never lowers the Emax, and it acts at H1.'},
  {t:'Phenoxybenzamine', correct:true, why:'Right shift with the Emax falling at every dose: receptors are being removed, and phenoxybenzamine is the one irreversible antagonist on the list.'},
  {t:'Epinephrine', correct:false, miss:'direction', why:'Epinephrine is a full agonist; it would shift NE to the left.'},
  {t:'None of the above', correct:false, miss:'class', why:'One drug on the list is irreversible, and the figure shows its pattern.'}],
 teach:'A falling Emax across several doses can only be an irreversible antagonist (or an allosteric antagonist on efficacy). On the drug list the one irreversible drug is phenoxybenzamine: covalent bonds that are not reversed, so the receptors it binds are gone. Metoprolol and loratadine are reversible and keep the Emax; diazepam and epinephrine help.',
 quote:'If you see something that it lowers the Emacs, you know that has to be either an irreversible antagonist or an allosteric antagonist that affects efficacy, right?',
 cite:'Pharmacodynamics reviews.pdf page 5; transcript 9/28, 9/30'},

{id:'FG-027', fg:'irreversible', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure', multi:true,
 concept:'three-questions-irreversible', tags:['poll','figure-drill'], source:'both',
 img:'rev-rt-figure', imgAlt:'Fractional maximum response against log agonist: the leftmost curve, labelled Rt = 1, reaches 1.0; the curves to its right, labelled x10^-1, x10^-2 and x10^-3, shift progressively right and plateau lower and lower; a dashed line through the half-maximal points curves down to a point marked KA', imgCap:'Drug A alone (left) and drug A with increasing concentrations of drug C (right)',
 stem:'The curve on the left is drug A alone; the curves on the right are A with increasing concentrations of drug C. Which classes can be ruled OUT as drug C? Select all that apply.',
 options:[
  {t:'Competitive (reversible) antagonist', correct:true, why:'Competitive drugs never lower the Emax; here it falls.'},
  {t:'Inverse agonist', correct:true, why:'Also competitive: right shift, same Emax. The falling top rules it out.'},
  {t:'Full agonist', correct:true, why:'A full agonist would move the curve to the left.'},
  {t:'Allosteric agonist that affects efficacy', correct:true, why:'An agonist of any kind helps; these curves need higher and higher doses.'},
  {t:'Irreversible antagonist', correct:false, miss:'emax', why:'This is the answer, not a drug to rule out: right shift, same baseline, falling Emax.'}],
 teach:'Work the eliminations: the right shift rules out the full agonist and the allosteric agonist; the falling Emax rules out the competitive antagonist and the inverse agonist, which are both competitive and never change the Emax. What is left is the irreversible antagonist.',
 quote:'so who can I eliminate? For agonists and an allosteric agonist that affects efficacy, right? ... So right there, you went from have a best of 5 to a best of 3.',
 cite:'Pharmacodynamics reviews.pdf page 5; transcript 9/30'},

{id:'FG-028', fg:'potency', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'three-questions-irreversible', tags:['poll','figure-drill','potency'], source:'both',
 img:'rev-rt-figure', imgAlt:'Fractional maximum response against log agonist: the leftmost curve, labelled Rt = 1, reaches 1.0; the curves to its right, labelled x10^-1, x10^-2 and x10^-3, shift progressively right and plateau lower and lower; a dashed line through the half-maximal points curves down to a point marked KA', imgCap:'Drug A alone (left) and drug A with increasing concentrations of drug C (right)',
 stem:'As the concentration of drug C goes up, what happens to the potency and the ED50 of drug A?',
 options:[
  {t:'Potency falls and the ED50 rises', correct:true, why:'Each curve needs a higher dose for the same response: a larger ED50 is a lower potency.'},
  {t:'Potency rises and the ED50 falls', correct:false, miss:'direction', why:'That is a shift to the left, a drug helping A; these curves move to the right.'},
  {t:'Potency falls and the ED50 falls', correct:false, miss:'potency', why:'Potency and ED50 move in opposite directions: the smaller the ED50, the greater the potency.'},
  {t:'Neither changes; only the Emax changes', correct:false, miss:'shift', why:'The curves have shifted to the right as well as down; the ED50 has moved.'}],
 teach:'The red note on the slide: shift? Yes, lower potency, which is the same as a higher ED50. The smaller the ED50, the greater the potency; they are inversely proportional. Here each dose of C pushes A to the right (ED50 up, potency down) and also brings the Emax down.',
 quote:'the take-home message that you can’t forget is that the smallest the ED50 is or the EC50, the greater the potency is gonna be. They’re inverse proportional.',
 cite:'Pharmacodynamics reviews.pdf page 5; transcript 9/24, 9/30'},

{id:'FG-029', fg:'irreversible', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'irreversible-lowers-emax', tags:['poll','figure-drill'], source:'both',
 img:'rev-rt-figure', imgAlt:'Fractional maximum response against log agonist: the leftmost curve, labelled Rt = 1, reaches 1.0; the curves to its right, labelled x10^-1, x10^-2 and x10^-3, shift progressively right and plateau lower and lower; a dashed line through the half-maximal points curves down to a point marked KA', imgCap:'Drug A alone (left) and drug A with increasing concentrations of drug C (right)',
 stem:'Why does the Emax of drug A fall with each concentration of drug C?',
 options:[
  {t:'C binds covalently and takes receptors out of use', correct:true, why:'Receptors bound by an irreversible antagonist are gone for the agonist; once the spare receptors are used up, A cannot reach its maximum.'},
  {t:'C has negative efficacy and pulls the baseline down', correct:false, miss:'baseline', why:'The baseline stays at 0 on every curve; negative efficacy is the inverse agonist, which does not lower the Emax.'},
  {t:'C is an allosteric agonist that raises the affinity of A', correct:false, miss:'direction', why:'That would move the curve to the left with the same top; these curves move right and down.'},
  {t:'C competes with A at the orthosteric site and comes off', correct:false, miss:'emax', why:'A drug that comes off can be outcompeted and the Emax is reached; this Emax is not.'}],
 teach:'An irreversible antagonist forms covalent bonds and chemically down-regulates the receptors: the ones it binds are out of use. Like the chair game with glue on the chair, once C sits it cannot get out, so A has fewer receptors to work with; the curve shifts right and, when the spare receptors are gone, the Emax falls.',
 quote:'It will decrease the ability of agonists to get to the Emax because you’re removing, you’re down regulating the receptors chemically',
 cite:'Pharmacodynamics reviews.pdf page 5; transcript 9/28, 9/30'},

/* ---------------- Review page 6: equal shifts from 0 ---------------- */
{id:'FG-030', fg:'competitive', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'drug-x-metoprolol', tags:['poll','figure-drill','metoprolol','drug-list'], source:'both',
 img:'rev-shifts-base0', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A on the left starting at 0 and reaching 1.0, then three solid curves A + B, A + 10X B and A + 100X B shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'A alone (dashed) and A with increasing concentrations of B',
 stem:'Drug A is norepinephrine at the β1 receptor. The dashed curve is NE alone; the solid curves are NE with B, 10X B and 100X B. Drug B is most likely:',
 options:[
  {t:'Metoprolol', correct:true, why:'Equal right shifts with the baseline and the top unchanged: a competitive, reversible antagonist, and metoprolol is the β1 antagonist on the list.'},
  {t:'Epinephrine', correct:false, miss:'direction', why:'Epinephrine is a full agonist; it would shift NE to the left.'},
  {t:'Albuterol', correct:false, miss:'baseline', why:'Albuterol is the partial agonist; it has efficacy and would move the baseline.'},
  {t:'Phenoxybenzamine', correct:false, miss:'emax', why:'Phenoxybenzamine is irreversible; three doses would bring the top down, and it never moves.'},
  {t:'Diazepam', correct:false, miss:'class', why:'Diazepam is the allosteric agonist at the GABA receptor; it would help, not hinder.'}],
 teach:'Shift right, baseline unchanged, Emax unchanged, symmetrical steps: a competitive antagonist. On the list, metoprolol is the competitive β1 antagonist; epinephrine helps, albuterol has efficacy, phenoxybenzamine lowers the top, diazepam is an allosteric agonist elsewhere.',
 quote:'Hopefully you pick D as in David, metoprolol, because epinephrine is a full agonist. Albuterol is your partial ... Fenoxbenzammine is the only irreversible that is on your list, and diazepam is your allosteric agonist.',
 cite:'Pharmacodynamics reviews.pdf page 6; transcript 9/28, 9/30'},

{id:'FG-031', fg:'competitive', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'three-questions-competitive', tags:['poll','figure-drill'], source:'both',
 img:'rev-shifts-base0', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A on the left starting at 0 and reaching 1.0, then three solid curves A + B, A + 10X B and A + 100X B shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'A alone (dashed) and A with increasing concentrations of B',
 stem:'The dashed curve is agonist A alone; the solid curves are A with B, 10X B and 100X B. Which statement is CORRECT?',
 options:[
  {t:'B shifts A to the right', correct:false, miss:'read', why:'Correct (higher doses of A are needed), but not the only correct statement.'},
  {t:'B does not change the Emax of A', correct:false, miss:'read', why:'Correct (every curve reaches the same top), but not the only correct statement.'},
  {t:'The shifts are symmetrical', correct:false, miss:'read', why:'Correct (equal steps for each tenfold dose), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'Right shift, same Emax, equal steps: the competitive antagonist, with nothing allosteric or irreversible about it.'}],
 teach:'Shift? Right. Baseline? Unchanged (at 0). Emax? Unchanged across three doses. Symmetrical? Yes. Every statement is true of the figure, and together they describe the competitive antagonist, the best single answer here.',
 quote:'Very symmetrical shifts with no change to the baseline, no change to the Emacs, just shifting to the right.',
 cite:'Pharmacodynamics reviews.pdf page 6; transcript 9/28, 9/30'},

{id:'FG-032', fg:'irreversible', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'three-questions-competitive', tags:['poll','figure-drill'], source:'both',
 img:'rev-shifts-base0', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A on the left starting at 0 and reaching 1.0, then three solid curves A + B, A + 10X B and A + 100X B shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'A alone (dashed) and A with increasing concentrations of B',
 stem:'The dashed curve is agonist A alone; the solid curves are A with B, 10X B and 100X B. Why can an irreversible antagonist be ruled out as B?',
 options:[
  {t:'Across three doses of B the Emax has not dropped at all', correct:true, why:'An irreversible antagonist removes receptors, so with more and more of it the top comes down; three doses with the same top rule it out.'},
  {t:'The curves shift to the right', correct:false, miss:'emax', why:'An irreversible antagonist also shifts the agonist to the right.'},
  {t:'The baseline stays at 0', correct:false, miss:'emax', why:'No antagonist changes the baseline; this does not separate them.'},
  {t:'An irreversible antagonist would shift the curves to the left', correct:false, miss:'direction', why:'Any antagonist makes life more difficult and shifts right, never left.'}],
 teach:'The Emax question is what rules out the irreversible antagonist: multiple shifts and the top has not dropped. One shift would not be enough (spare receptors could hide the drop), but here B was given at three doses up to 100X and A still reaches its maximum.',
 quote:'Is the Emax changing? No, so I can get rid of irreversible because you know I have multiple shifts, right, and it hasn’t dropped at all',
 cite:'Pharmacodynamics reviews.pdf page 6; transcript 9/30'},

{id:'FG-033', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'predict', skill:'figure',
 concept:'allosteric-agonist-affinity-only', tags:['poll','figure-drill','diazepam','drug-list'], source:'both',
 img:'rev-shifts-base0', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A on the left starting at 0 and reaching 1.0, then three solid curves A + B, A + 10X B and A + 100X B shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'A alone (dashed) and A with increasing concentrations of B',
 stem:'Drug A is GABA. If drug B were diazepam instead of the drug shown, where would the solid curves sit?',
 options:[
  {t:'To the left of the dashed curve', correct:true, why:'Diazepam is an allosteric agonist: it helps GABA, so GABA appears more potent and its curve moves to the left; the top, already at 1.0, stays.'},
  {t:'To the right in equal steps, as shown', correct:false, miss:'direction', why:'Right shifts are a drug making life more difficult; diazepam helps GABA.'},
  {t:'To the right with a falling top', correct:false, miss:'direction', why:'That is the irreversible antagonist; all allosterics in this course are reversible and diazepam is an agonist.'},
  {t:'Starting from a baseline above 0', correct:false, miss:'baseline', why:'Diazepam has no effect on its own; it only changes what GABA does, so the baseline stays at 0.'}],
 teach:'Diazepam is the allosteric agonist on the drug list, at the GABA receptor. It helps GABA: more affinity, a shift to the left, with the top unchanged (the curve is already at 1.0, so any effect on efficacy could not be seen). The right shifts in the figure belong to a competitive antagonist.',
 quote:'Help, which means you’re gonna make the drug more potent, right? ... is moving to the left.',
 cite:'Pharmacodynamics reviews.pdf page 6; transcript 9/28, 9/30'},

/* ---------------- Review page 7: baseline 50% falling to 0 ---------------- */
{id:'FG-034', fg:'inverse', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'fa-plus-inverse-agonist', tags:['poll','figure-drill','loratadine','drug-list'], source:'both',
 img:'rev-shifts-base50', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A starts at about 0.5 and reaches 1.0; solid curves A + B, A + 10X B and A + 100X B are shifted to the right and start lower and lower, from about 0.3, about 0.1 and 0, all reaching the same top', imgCap:'A alone (dashed, from a 50% baseline) and A with increasing concentrations of B',
 stem:'The dashed curve is agonist A alone, starting from a baseline of about 50%; the solid curves are A with B, 10X B and 100X B. Drug B is most likely:',
 options:[
  {t:'Loratadine', correct:true, why:'Right shift, same Emax, and the baseline falls to 0 with each dose: the inverse agonist, and loratadine is the one inverse agonist on the list.'},
  {t:'Metoprolol', correct:false, miss:'baseline', why:'Metoprolol is a neutral competitive antagonist; it would shift A right but leave the baseline at 50%.'},
  {t:'Albuterol', correct:false, miss:'direction', why:'Albuterol is a partial agonist; it would not shift A right in three symmetrical steps and would not take the baseline to 0.'},
  {t:'Phenoxybenzamine', correct:false, miss:'emax', why:'Phenoxybenzamine is irreversible: it lowers the Emax and never changes the baseline.'},
  {t:'Epinephrine', correct:false, miss:'direction', why:'Epinephrine is a full agonist; it would shift A to the left.'}],
 teach:'Shift right: B competes with A. Emax unchanged: B is reversible. Baseline falling to 0: B shuts off the receptors that were active on their own. That is the inverse agonist, and there is only one on the drug list, the antihistamine loratadine.',
 quote:'there’s only one inverse agonist you need to know. It’s gonna be an antihistamine. If you know what loratadine is, you know that’s the inverse agonist',
 cite:'Pharmacodynamics reviews.pdf page 7; transcript 9/28, 9/30'},

{id:'FG-035', fg:'inverse', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'competitive-vs-inverse-baseline-zero', tags:['poll','figure-drill'], source:'both',
 img:'rev-shifts-base50', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A starts at about 0.5 and reaches 1.0; solid curves A + B, A + 10X B and A + 100X B are shifted to the right and start lower and lower, from about 0.3, about 0.1 and 0, all reaching the same top', imgCap:'A alone (dashed, from a 50% baseline) and A with increasing concentrations of B',
 stem:'The dashed curve is agonist A alone from a 50% baseline; the solid curves are A with B, 10X B and 100X B. Which feature of the figure rules out a competitive antagonist as B?',
 options:[
  {t:'The baseline falls to 0 with each dose of B', correct:true, why:'A neutral antagonist does not change the balance of active and inactive receptors; only an inverse agonist brings the baseline down.'},
  {t:'The curves shift to the right', correct:false, miss:'baseline', why:'A competitive antagonist also shifts the agonist right.'},
  {t:'The Emax is unchanged across the three doses', correct:false, miss:'baseline', why:'A competitive antagonist also leaves the Emax alone; it is reversible.'},
  {t:'The dashed curve starts at about 50%', correct:false, miss:'read', why:'The starting point describes the system (half the receptors active), not drug B.'}],
 teach:'A competitive antagonist and an inverse agonist both shift the agonist to the right with the same Emax. The one thing that tells them apart is the baseline: the neutral antagonist leaves it where it is, the inverse agonist brings it to 0. Here it falls to 0, so B is not a competitive antagonist.',
 quote:'Is a change in the baseline? Yes. Where is it going? To 0. What it means is, it’s an inverse agonist.',
 cite:'Pharmacodynamics reviews.pdf page 7; transcript 9/30'},

{id:'FG-036', fg:'inverse', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'three-questions-inverse', tags:['poll','figure-drill'], source:'both',
 img:'rev-shifts-base50', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A starts at about 0.5 and reaches 1.0; solid curves A + B, A + 10X B and A + 100X B are shifted to the right and start lower and lower, from about 0.3, about 0.1 and 0, all reaching the same top', imgCap:'A alone (dashed, from a 50% baseline) and A with increasing concentrations of B',
 stem:'The dashed curve is agonist A alone from a 50% baseline; the solid curves are A with B, 10X B and 100X B. Which statement is CORRECT about drug B?',
 options:[
  {t:'It competes with A and shifts its curve to the right', correct:false, miss:'read', why:'Correct (each dose of B needs more A), but not the only correct statement.'},
  {t:'It brings the baseline down to 0', correct:false, miss:'read', why:'Correct (the starting points fall with each dose), but not the only correct statement.'},
  {t:'It does not change the Emax of A', correct:false, miss:'read', why:'Correct (every curve reaches the same top; B is reversible), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'Right shift, baseline to 0, Emax unchanged: the three readings that make B an inverse agonist.'}],
 teach:'The inverse agonist has the highest affinity for inactive receptors and wants to keep them inactive. Given with an agonist from a 50% baseline it does three things: competes (shift right), lowers the baseline (down to 0) and, being reversible, leaves the Emax alone.',
 quote:'It would decrease the baseline because that’s what the inverse wants to do. And we shifted those responses of my agonist to the right, because they are competing with each other',
 cite:'Pharmacodynamics reviews.pdf page 7; transcript 9/30'},

{id:'FG-037', fg:'two-state', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'baseline-reflects-receptor-activity', tags:['poll','figure-drill'], source:'both',
 img:'rev-shifts-base50', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A starts at about 0.5 and reaches 1.0; solid curves A + B, A + 10X B and A + 100X B are shifted to the right and start lower and lower, from about 0.3, about 0.1 and 0, all reaching the same top', imgCap:'A alone (dashed, from a 50% baseline) and A with increasing concentrations of B',
 stem:'The dashed curve, agonist A alone, starts at about 0.5 instead of 0. What does that starting point tell you?',
 options:[
  {t:'Half the receptors are active on their own', correct:true, why:'The baseline is the activity of the system before any drug: R = R*, so the response starts at 50%.'},
  {t:'Drug A is a partial agonist with 50% efficacy', correct:false, miss:'read', why:'A rises from 0.5 all the way to 1.0: a full agonist. The 0.5 is where the system starts, not where A stops.'},
  {t:'Drug B has already been given at a low dose', correct:false, miss:'read', why:'The dashed curve is A alone; B only appears on the solid curves.'},
  {t:'The system has half the normal number of receptors', correct:false, miss:'baseline', why:'Receptor number would change potency (left or right), not the starting level of the response.'}],
 teach:'Where the curve starts is the baseline, the activity of the receptors with nothing bound. If one sign shows R greater than R*, most receptors are inactive and the baseline is 0; if R = R*, half are active and the baseline is 50%. That is what gives an inverse agonist something to bring down.',
 quote:'My starting point is 50%. I have receptors that are 50% active by themselves and 50% inactive',
 cite:'Pharmacodynamics reviews.pdf page 7; transcript 9/28, 9/30'},

/* ---------------- Review page 8: dashed to the left ---------------- */
{id:'FG-038', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'fa-plus-fa', tags:['poll','figure-drill','epinephrine','drug-list'], source:'both',
 img:'rev-dotted-left', imgAlt:'Response percent of control against agonist concentration: a solid curve on the right is the agonist alone; a dashed curve labelled X+Y sits to its left with a red arrow pointing left; both start at 0 and reach the same top', imgCap:'Solid: agonist alone; dashed: agonist in the presence of drug X',
 stem:'The solid line is norepinephrine alone at the β1 receptor. The dotted line is norepinephrine in the presence of drug X. Drug X is most likely:',
 options:[
  {t:'Metoprolol', correct:false, miss:'direction', why:'Metoprolol competes with NE and shifts it to the right; this curve moved left.'},
  {t:'Epinephrine', correct:true, why:'Two full agonists at the same receptor help each other: NE appears more potent, a shift to the left with the same top.'},
  {t:'Loratadine', correct:false, miss:'direction', why:'Loratadine is an inverse agonist; it makes life more difficult and shifts right.'},
  {t:'Phenoxybenzamine', correct:false, miss:'direction', why:'Phenoxybenzamine shifts right and lowers the top; this curve moved left at the same top.'},
  {t:'Prazosin', correct:false, miss:'direction', why:'Prazosin is an α1 antagonist; an antagonist never helps.'}],
 teach:'A shift to the left is a drug helping: the slide keys a full agonist or an allosteric agonist that affects affinity. At the β1 receptor the full agonist on the list is epinephrine: whichever of the two is bound does the same thing, so NE appears more potent. Every antagonist on the list would move the curve the other way.',
 quote:'hopefully you’ll pick A again because we have two full agonists, norepinephrine and Epi, that binds to the same receptor ... And thus shifting to the left.',
 cite:'Pharmacodynamics reviews.pdf page 8; transcript 9/28, 9/30'},

{id:'FG-039', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'transporter-blocker-increases-apparent-potency', tags:['poll','figure-drill','duloxetine','drug-list'], source:'both',
 img:'rev-dotted-left', imgAlt:'Response percent of control against agonist concentration: a solid curve on the right is the agonist alone; a dashed curve labelled X+Y sits to its left with a red arrow pointing left; both start at 0 and reach the same top', imgCap:'Solid: agonist alone; dashed: agonist in the presence of drug X',
 stem:'The solid line is norepinephrine alone. The dotted line is norepinephrine in the presence of drug X. Drug X is most likely:',
 options:[
  {t:'Duloxetine', correct:true, why:'Blocking the norepinephrine transporter leaves NE in the synapse longer, so NE appears more potent: a shift to the left with the same top.'},
  {t:'Metoprolol', correct:false, miss:'direction', why:'Metoprolol competes with NE and shifts it right.'},
  {t:'Loratadine', correct:false, miss:'direction', why:'Loratadine is the inverse agonist; it shifts right and wants the baseline down.'},
  {t:'Phenoxybenzamine', correct:false, miss:'direction', why:'Phenoxybenzamine is irreversible: right shift and a lower top.'}],
 teach:'The first question: is drug X helping or making life more difficult? Left means helping. Duloxetine does not bind the receptor; it blocks the norepinephrine transporter, so more NE floats around for longer and less is needed: an indirect drug that makes NE appear more potent. The antagonists all shift right.',
 quote:'we’re blocking the reuptake of norepinephrine, which means we’re gonna have norepinephrine floating around for a longer period of time in that synapse and thus make it norepinephrine more potent, shifting to the left.',
 cite:'Pharmacodynamics reviews.pdf page 8; transcript 9/29, 9/30'},

{id:'FG-040', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'allosteric-agonist-affinity-only', tags:['poll','figure-drill','diazepam','drug-list'], source:'both',
 img:'rev-dotted-left', imgAlt:'Response percent of control against agonist concentration: a solid curve on the right is the agonist alone; a dashed curve labelled X+Y sits to its left with a red arrow pointing left; both start at 0 and reach the same top', imgCap:'Solid: agonist alone; dashed: agonist in the presence of drug X',
 stem:'The solid line is GABA alone at its receptor. The dotted line is GABA in the presence of drug X. Drug X is most likely:',
 options:[
  {t:'Diazepam', correct:true, why:'Diazepam is the allosteric agonist on the list: it binds the GABA receptor at its own site and raises the affinity of GABA, a shift to the left with the same top.'},
  {t:'Loratadine', correct:false, miss:'direction', why:'Loratadine makes life more difficult (right shift) and acts at the H1 receptor.'},
  {t:'Metoprolol', correct:false, miss:'direction', why:'Metoprolol is an antagonist (right shift) and acts at β1.'},
  {t:'Phenoxybenzamine', correct:false, miss:'direction', why:'Phenoxybenzamine is an irreversible antagonist: right shift, lower top.'}],
 teach:'Left shift, same top: the slide keys a full agonist or an allosteric agonist that affects affinity. At the GABA receptor the helper on the drug list is diazepam, the allosteric agonist he put on the list for the exam. On its own it does nothing; with GABA bound it makes GABA more potent.',
 quote:'on your drug list, I put diazepam as our known allosteric agonist that you have to know for your exam',
 cite:'Pharmacodynamics reviews.pdf page 8; transcript 9/23, 9/30'},

{id:'FG-041', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure', multi:true,
 concept:'left-shift-two-answers', tags:['poll','figure-drill'], source:'both',
 img:'rev-dotted-left', imgAlt:'Response percent of control against agonist concentration: a solid curve on the right is the agonist alone; a dashed curve labelled X+Y sits to its left with a red arrow pointing left; both start at 0 and reach the same top', imgCap:'Solid: agonist alone; dashed: agonist in the presence of drug X',
 stem:'The solid line is the agonist alone and the dotted line is the agonist in the presence of drug X. Which classes can be ruled OUT as drug X? Select all that apply.',
 options:[
  {t:'Competitive antagonist', correct:true, why:'It would shift the curve to the right.'},
  {t:'Inverse agonist', correct:true, why:'It would shift right and want the baseline down.'},
  {t:'Irreversible antagonist', correct:true, why:'It would shift right and lower the top.'},
  {t:'Allosteric antagonist that affects affinity and efficacy', correct:true, why:'It would shift right and bring the top down.'},
  {t:'Full agonist', correct:false, miss:'direction', why:'A second full agonist moves the curve left at the same top: one of the two answers that stay open.'},
  {t:'Allosteric agonist that affects affinity', correct:false, miss:'direction', why:'More affinity moves the curve left with no change in the top: the other answer that stays open.'}],
 teach:'Is it shifting? Yes, to the left, so it is helping: the competitive antagonist, the inverse agonist, the irreversible antagonist and the allosteric antagonist are all out at once. Baseline and Emax do not change. Two answers remain, a full agonist or an allosteric agonist that affects affinity.',
 quote:'because we’re shifting to the left, I can get rid of the competitive antagonist and the inverse ... two possible answers. It’s either full agonist. Or an allosteric agonist that affecting what, affinity.',
 cite:'Pharmacodynamics reviews.pdf page 8; transcript 9/30'},

/* ---------------- Review page 9: one shift to the right ---------------- */
{id:'FG-042', fg:'competitive', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'one-right-shift-rule-out', tags:['poll','figure-drill','metoprolol','drug-list'], source:'both',
 img:'rev-dotted-right', imgAlt:'Response percent of control against agonist concentration: a dashed curve on the left is the agonist alone; one solid curve sits to its right with a red arrow pointing right; both start at 0 and reach the same top', imgCap:'Dashed: agonist alone; solid: agonist in the presence of drug X (one shift)',
 stem:'The dotted line is norepinephrine alone at the β1 receptor and the solid line is norepinephrine in the presence of drug X. Drug X is most likely:',
 options:[
  {t:'Epinephrine', correct:false, miss:'direction', why:'A full agonist would shift NE to the left.'},
  {t:'Albuterol', correct:false, miss:'baseline', why:'A partial agonist has efficacy of its own and would not simply shift NE right at the same top.'},
  {t:'Metoprolol', correct:true, why:'One shift to the right with the baseline and the top unchanged: for one best answer, the competitive antagonist, and metoprolol is the β1 antagonist on the list.'},
  {t:'Diazepam', correct:false, miss:'direction', why:'An allosteric agonist helps and shifts left (and acts at GABA receptors).'},
  {t:'Duloxetine', correct:false, miss:'direction', why:'Blocking NE reuptake makes NE more potent: a shift to the left.'}],
 teach:'Shift right rules out everything that helps: epinephrine, diazepam, duloxetine. A partial agonist is out too. Baseline is at 0 and the top is unchanged, so with one best answer it is the competitive antagonist, metoprolol. With one shift an irreversible antagonist could not be excluded on a select-all, but it is not among the choices here.',
 quote:'If this was one best answer ... no way it would be irreversible, right? If you had to pick. It has to be either competitive or inverse.',
 cite:'Pharmacodynamics reviews.pdf page 9; transcript 9/30'},

{id:'FG-043', fg:'spare', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'one-right-shift-select-all', tags:['poll','figure-drill'], source:'both',
 img:'rev-dotted-right', imgAlt:'Response percent of control against agonist concentration: a dashed curve on the left is the agonist alone; one solid curve sits to its right with a red arrow pointing right; both start at 0 and reach the same top', imgCap:'Dashed: agonist alone; solid: agonist in the presence of drug X (one shift)',
 stem:'The dotted line is the agonist alone and the solid line is the agonist with drug X: one shift to the right, same top. Why can an irreversible antagonist NOT be ruled out on this figure?',
 options:[
  {t:'With spare receptors, the first dose only shifts the curve and the drop in the top comes later', correct:true, why:'If the agonist needs only a fraction of the receptors for its maximum, an irreversible antagonist can remove some without lowering the Emax; more shifts are needed to see the drop.'},
  {t:'An irreversible antagonist never lowers the Emax', correct:false, miss:'emax', why:'It does, once the spare receptors are gone; that is its signature.'},
  {t:'An irreversible antagonist shifts the curve to the left', correct:false, miss:'direction', why:'Every antagonist makes life more difficult and shifts right.'},
  {t:'The baseline is at 0, which only an irreversible antagonist that has removed receptors can produce', correct:false, miss:'baseline', why:'No antagonist changes the baseline; a baseline of 0 says the receptors are mostly inactive on their own.'}],
 teach:'One shift is not enough information. A tissue with spare receptors can lose some receptors to an irreversible antagonist and still reach its maximum, so the first dose looks like a competitive shift. Only more shifts, with the top eventually dropping, can prove or disprove it; for one best answer, pick competitive.',
 quote:'What if this drug has high efficacy? You only need 1% of the receptors to produce the max response ... Could I get some shift before I see that drop happening? Yes',
 cite:'Pharmacodynamics reviews.pdf page 9; transcript 9/30'},

{id:'FG-044', fg:'potency', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'one-right-shift-rule-out', tags:['poll','figure-drill','potency'], source:'both',
 img:'rev-dotted-right', imgAlt:'Response percent of control against agonist concentration: a dashed curve on the left is the agonist alone; one solid curve sits to its right with a red arrow pointing right; both start at 0 and reach the same top', imgCap:'Dashed: agonist alone; solid: agonist in the presence of drug X (one shift)',
 stem:'The dotted line is the agonist alone and the solid line is the agonist in the presence of drug X. In the presence of X, the ED50 of the agonist has:',
 options:[
  {t:'Increased', correct:true, why:'The solid curve needs a higher concentration for the same response: a larger ED50, a less potent agonist.'},
  {t:'Decreased', correct:false, miss:'direction', why:'A smaller ED50 would be a shift to the left, a drug helping the agonist.'},
  {t:'Not changed', correct:false, miss:'shift', why:'The curve has moved; the dose that gives 50% of the response is now higher.'},
  {t:'Dropped to 0', correct:false, miss:'read', why:'An ED50 of 0 would mean an effect with no drug; the curve still rises with dose.'}],
 teach:'Shift to the right means the agonist needs a higher dose for the same effect: its ED50 goes up and its potency goes down. Affinity, efficacy and the tissue have not changed; what changed is that X is making life more difficult for the agonist.',
 quote:'what would you think was going to happen to the dose response curve shift to the left where it becomes more potent, or to the right where it becomes less potent? It’s gonna be moved to the right.',
 cite:'Pharmacodynamics reviews.pdf page 9; transcript 9/28, 9/30'},

/* ---------------- Review page 10: unequal shifts, allosteric antagonist ---------------- */
{id:'FG-045', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'allosteric-antagonist-unequal-shifts', tags:['poll','figure-drill'], source:'both',
 img:'rev-allo-ant', imgAlt:'Response percent of control against agonist concentration: a dashed curve on the left is the agonist alone; three solid curves to its right with a red arrow pointing right; the spacing between the solid curves is not equal; all start at 0 and reach the same top', imgCap:'Dashed: agonist alone; solid: agonist with increasing concentrations of drug X (unequal spacing)',
 stem:'The dotted line is the agonist alone; the solid lines are the agonist with increasing concentrations of drug X. Which observation tells you that drug X is allosteric?',
 options:[
  {t:'The shifts are to the right of the dashed curve', correct:false, miss:'symmetry', why:'Direction says antagonist or agonist, not allosteric or orthosteric; competitive antagonists shift right too.'},
  {t:'The spacing between the shifts is not equal', correct:true, why:'Allosteric binding saturates, so the shifts are unsymmetrical; a competitive drug gives equal steps with no limit.'},
  {t:'The top does not change', correct:false, miss:'symmetry', why:'The unchanged top says affinity rather than efficacy; a competitive antagonist keeps the top too.'},
  {t:'The baseline stays at 0', correct:false, miss:'symmetry', why:'No antagonist changes the baseline; this does not separate allosteric from competitive.'}],
 teach:'If the shifts on a figure are not symmetric, you already know it is allosteric. Then decide the rest: shifting right makes it an antagonist, the unchanged top makes it affinity only. A competitive antagonist or an inverse agonist would give symmetrical shifts.',
 quote:'So if you see a figure in your exam that the shifts are not symmetric, you already know it’s allosteric. You just gotta be able to figure out, is that an agonist or an antagonist? Does it affect affinity or efficacy or both',
 cite:'Pharmacodynamics reviews.pdf page 10; transcript 9/30'},

{id:'FG-046', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'allosteric-antagonist-unequal-shifts', tags:['poll','figure-drill'], source:'both',
 img:'rev-allo-ant', imgAlt:'Response percent of control against agonist concentration: a dashed curve on the left is the agonist alone; three solid curves to its right with a red arrow pointing right; the spacing between the solid curves is not equal; all start at 0 and reach the same top', imgCap:'Dashed: agonist alone; solid: agonist with increasing concentrations of drug X (unequal spacing)',
 stem:'The shifts on this figure are unequal, so drug X is allosteric. Why is X an allosteric antagonist and not an allosteric agonist?',
 options:[
  {t:'The curves move to the right', correct:true, why:'Right means making life more difficult: the agonist needs more drug for the same effect. An allosteric agonist would move it to the left.'},
  {t:'The top does not change from curve to curve', correct:false, miss:'direction', why:'That says affinity only, and would be true of an allosteric agonist on affinity as well.'},
  {t:'The shifts saturate', correct:false, miss:'direction', why:'Saturation is what makes it allosteric; both allosteric agonists and antagonists saturate.'},
  {t:'The baseline is at 0', correct:false, miss:'direction', why:'An allosteric drug has no effect on its own in either case; the baseline does not decide.'}],
 teach:'Allosteric drugs, agonist or antagonist, give unsymmetrical, saturating shifts. The direction decides which: an allosteric agonist helps (left), an allosteric antagonist makes life more difficult (right). Here the curves move right, so X is an allosteric antagonist, and the unchanged top says it affects affinity.',
 quote:'an allosteric antagonist would compete for an orthosteric site. No, they bind someplace else ... Can decrease the affinity of an agonist for its receptor. Probably so.',
 cite:'Pharmacodynamics reviews.pdf page 10; transcript 9/30'},

{id:'FG-047', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'allosteric-antagonist-effects', tags:['poll','figure-drill'], source:'both',
 img:'rev-allo-ant', imgAlt:'Response percent of control against agonist concentration: a dashed curve on the left is the agonist alone; three solid curves to its right with a red arrow pointing right; the spacing between the solid curves is not equal; all start at 0 and reach the same top', imgCap:'Dashed: agonist alone; solid: agonist with increasing concentrations of drug X (unequal spacing)',
 stem:'Drug X is an allosteric antagonist. Which feature of the figure shows that it affects only affinity, and not affinity and efficacy?',
 options:[
  {t:'Every curve still reaches the same top', correct:true, why:'An allosteric antagonist on efficacy would bring the maximal response down; affinity only moves the curve right without touching the Emax.'},
  {t:'The spacing between the shifts is unequal', correct:false, miss:'emax', why:'Unequal shifts say allosteric; they do not say which property is affected.'},
  {t:'The curves move to the right', correct:false, miss:'emax', why:'Right says antagonist; an allosteric antagonist on affinity and efficacy also moves right.'},
  {t:'The baseline does not move', correct:false, miss:'emax', why:'The baseline is at 0 and neither version of the allosteric antagonist would change it.'}],
 teach:'Whatever the allosteric agonist does, the allosteric antagonist does the opposite. Affinity only: shift to the right without affecting the ability to get the maximal response. Affinity and efficacy: right and down. On this figure the top never changes, so X affects affinity only.',
 quote:'what would happen to the dose response curve of this agonist in the presence of an allosteric antagonist that only affects affinity? ... It’s gonna shift to the right. Without affecting the ability to get the max response.',
 cite:'Pharmacodynamics reviews.pdf page 10; transcript 9/28, 9/30'},

{id:'FG-048', fg:'classes', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'predict', skill:'figure',
 concept:'allosteric-antagonist-unequal-shifts', tags:['poll','figure-drill'], source:'both',
 img:'rev-allo-ant', imgAlt:'Response percent of control against agonist concentration: a dashed curve on the left is the agonist alone; three solid curves to its right with a red arrow pointing right; the spacing between the solid curves is not equal; all start at 0 and reach the same top', imgCap:'Dashed: agonist alone; solid: agonist with increasing concentrations of drug X (unequal spacing)',
 stem:'Drug X is an allosteric antagonist that affects affinity. If still higher doses of X were added, what would happen to the shifts?',
 options:[
  {t:'The shifts get smaller and then stop', correct:true, why:'Once all the allosteric sites are occupied, that is all X can do to the system: the shifts saturate.'},
  {t:'The shifts keep going to the right without limit', correct:false, miss:'symmetry', why:'That is the competitive antagonist, which competes for the same site and can always be given more.'},
  {t:'The top starts to fall', correct:false, miss:'emax', why:'X affects affinity, not efficacy; the Emax stays.'},
  {t:'The baseline rises', correct:false, miss:'baseline', why:'An antagonist has no efficacy of its own; the baseline does not move.'}],
 teach:'Allosteric drugs are saturable: give higher and higher doses, but once every allosteric site is occupied there are no more shifts; it has hit the wall. That is why the shifts are unequal, and the opposite of a competitive antagonist, whose shifts go on symmetrically with each tenfold dose.',
 quote:'it’s going to be saturable, which means is I can give higher and higher doses, but once I occupy all the allosteric sites, that’s it, that’s all my drug can do to the system. I have maxed out it.',
 cite:'Pharmacodynamics reviews.pdf page 10; transcript 9/28, 9/30'},

/* ---------------- Review page 11: pindolol ---------------- */
{id:'FG-049', fg:'partial', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'read', skill:'figure',
 concept:'pindolol-partial-agonist-two-baselines', tags:['poll','figure-drill','pindolol'], source:'both',
 img:'rev-pindolol', imgAlt:'Response percent of control against agonist concentration with two dashed curves: an upper curve starts at 100% and falls to about 50%; a lower curve starts at 0 and rises to about 50%; both meet at about 50% at high concentration', imgCap:'One drug in two systems: starting at 100% (R < R*) and starting at 0',
 stem:'One drug is given to two systems: from 100% it brings the response down to about 50%, and from 0 it brings the response up to about 50%. Which statement is CORRECT about this drug?',
 options:[
  {t:'It has efficacy', correct:false, miss:'read', why:'Correct (it brings the low system up), but not the only correct statement.'},
  {t:'It is not an inverse agonist', correct:false, miss:'read', why:'Correct (it does not take the high system to 0), but not the only correct statement.'},
  {t:'It is a partial agonist', correct:false, miss:'read', why:'Correct (it wants the system at about 50%, not 100%), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'Efficacy yes, 0 no, 100% no: a partial agonist, and all three statements hold.'}],
 teach:'Does the drug have efficacy? Yes, it brings things up, so the neutral antagonists are out. Did it go to 0? No, so the inverse agonist is out. Did it change the efficacy to 100%? No, it wants about 50%. That is a partial agonist, and every statement is correct.',
 quote:'does this drug has efficacy? Yes, it’s bringing things up ... Did it go to 0? No, so we get rid of an inverse agonist ... Did it change the efficacy to 100%. Definitely not. They want you about 50%, so that is a partial agonist',
 cite:'Pharmacodynamics reviews.pdf page 11; transcript 9/30'},

{id:'FG-050', fg:'partial', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'which', skill:'drug',
 concept:'pindolol-partial-agonist-two-baselines', tags:['poll','figure-drill','pindolol','drug-list'], source:'both',
 img:'rev-pindolol', imgAlt:'Response percent of control against agonist concentration with two dashed curves: an upper curve starts at 100% and falls to about 50%; a lower curve starts at 0 and rises to about 50%; both meet at about 50% at high concentration', imgCap:'One drug in two systems: starting at 100% (R < R*) and starting at 0',
 stem:'One drug at the β1 receptor is given to two systems: from 100% it brings the response down to about 50%, and from 0 it brings the response up to about 50%. This drug is most likely:',
 options:[
  {t:'Metoprolol', correct:false, miss:'baseline', why:'Metoprolol is a neutral antagonist: no efficacy, so it would leave both baselines where they are.'},
  {t:'Pindolol', correct:true, why:'A partial β-blocker: it has partial efficacy, so it brings a fully active system down and an inactive system up, toward about 50%.'},
  {t:'Loratadine', correct:false, miss:'baseline', why:'Loratadine is the inverse agonist and acts at H1; an inverse agonist would take the upper system down to 0.'},
  {t:'Phenoxybenzamine', correct:false, miss:'baseline', why:'Phenoxybenzamine is an irreversible α antagonist; antagonists do not change the baseline.'},
  {t:'Epinephrine', correct:false, miss:'emax', why:'Epinephrine is a full agonist; it would take the lower system all the way to 100%, not stop at 50%.'}],
 teach:'A drug that moves both systems toward the same middle level has efficacy of its own, less than a full agonist and more than none: a partial agonist. At the β1 receptor that is pindolol, the partial β-blocker: if the heart rate is too low it brings it up, if it is too high it brings it down.',
 quote:'Pindolol, which is a partial beta blocker, if your heart is too low, it’s gonna bring things up. If it’s too high, it’s gonna bring things down.',
 cite:'Pharmacodynamics reviews.pdf page 11; transcript 9/30'},

{id:'FG-051', fg:'inverse', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'pindolol-partial-agonist-two-baselines', tags:['poll','figure-drill'], source:'both',
 img:'rev-pindolol', imgAlt:'Response percent of control against agonist concentration with two dashed curves: an upper curve starts at 100% and falls to about 50%; a lower curve starts at 0 and rises to about 50%; both meet at about 50% at high concentration', imgCap:'One drug in two systems: starting at 100% (R < R*) and starting at 0',
 stem:'Which feature of the figure rules out an inverse agonist?',
 options:[
  {t:'The upper curve goes down from 100% as the concentration rises', correct:false, miss:'baseline', why:'An inverse agonist also brings a fully active system down; going down alone does not rule it out.'},
  {t:'The upper curve stops at about 50% instead of going to 0', correct:true, why:'An inverse agonist brings everything down to 0 or keeps it at 0; this drug stops half way, so it has efficacy of its own.'},
  {t:'Both curves are dashed', correct:false, miss:'read', why:'Dashed only marks the drug being studied; it says nothing about its class.'},
  {t:'The two curves are the same drug', correct:false, miss:'read', why:'The same drug in two systems is the set-up of the figure, not what separates the classes.'}],
 teach:'Did it go to 0? No. An inverse agonist wants all the receptors inactive, so from 100% it would take the response to 0. This drug stops at about 50% from above and comes up to about 50% from below: it has its own level of efficacy, a partial agonist.',
 quote:'Did it go to 0? No, so we get rid of an inverse agonist, because an inverse ago will bring everything down to 0 or keep at 0 if it’s 0.',
 cite:'Pharmacodynamics reviews.pdf page 11; transcript 9/30'},

{id:'FG-052', fg:'partial', lecture:'FG', prof:'Gottlieb', tier:'new', topic:'FG', sub:'why', skill:'figure',
 concept:'pindolol-partial-agonist-two-baselines', tags:['poll','figure-drill','metoprolol'], source:'both',
 img:'rev-pindolol', imgAlt:'Response percent of control against agonist concentration with two dashed curves: an upper curve starts at 100% and falls to about 50%; a lower curve starts at 0 and rises to about 50%; both meet at about 50% at high concentration', imgCap:'One drug in two systems: starting at 100% (R < R*) and starting at 0',
 stem:'Which feature of the figure rules out a neutral antagonist such as metoprolol?',
 options:[
  {t:'The drug moves the response in both systems', correct:true, why:'A neutral antagonist has affinity but no efficacy: it does not change the balance of active and inactive receptors, so both baselines would stay flat.'},
  {t:'The upper curve goes down from 100% toward 50%', correct:false, miss:'baseline', why:'Going down alone could be read as blocking; what matters is that the lower curve also goes up, which needs efficacy.'},
  {t:'The curves meet at about 50%', correct:false, miss:'baseline', why:'The meeting point tells you the level of the partial agonist, not why an antagonist is excluded.'},
  {t:'The upper system starts at 100%', correct:false, miss:'read', why:'The starting point describes the system (fully active), not the drug.'}],
 teach:'Does this drug have efficacy? Yes, it brings the low system up and the high system down. A neutral antagonist is neutral: it does not change the baseline in either system. So metoprolol, with no efficacy, is out; pindolol, a partial agonist, fits.',
 quote:'So we got rid of those guys that are neutral because they will not change the baseline.',
 cite:'Pharmacodynamics reviews.pdf page 11; transcript 9/30'}
);
