TOPICS.push({id:'JP', name:'Jeopardy questions (9/30)', prof:'Gottlieb', lecture:'JP', cite:'Jeopardy 9/30 screenshots (his keys from the transcript)',
  subs:[{id:'verbatim', name:'His Jeopardy stems, word for word, with the keys he gave in class', cite:'Jeopardy 9/30 (IMG_3010–3018, IMG_9313–9321); PollEV_s.pdf page 6'}]});
QUESTIONS.push(
{id:'JP-001', fg:'two-state', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'figure',
 concept:'baseline50-classify-five', dupOf:'L04-026', tags:['poll','pollev','jeopardy'], source:'both',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises to about 80%, C stays flat at 50%, D falls to about 25%, E falls to 0%', imgCap:'Figure 1: five drugs given alone, each starting from the 50% baseline',
 stem:'Which of these DRC would best represent the DRC of an antagonist?',
 options:[
  {t:'A', correct:false, miss:'baseline', why:'A goes to the maximal response: a full agonist.'},
  {t:'B', correct:false, miss:'baseline', why:'B rises but stops short of the maximum: a partial agonist.'},
  {t:'C', correct:true, why:'C stays at the 50% baseline: a competitive or irreversible antagonist is neutral and does not change the baseline.'},
  {t:'D', correct:false, miss:'baseline', why:'D falls part way: a partial agonist with about 25% efficacy, below the baseline.'},
  {t:'E', correct:false, miss:'baseline', why:'E brings everything down to 0: an inverse agonist, not a neutral antagonist.'}],
 teach:'The baseline is at 50% and C stays at 50%. Competitive and irreversible antagonists are neutral: they do not change the baseline. E is not the answer: a drug that takes the response to 0 is an inverse agonist.',
 note:'Earlier in the same class, reading the review slide with this figure, he first called E "irreversible"; on this Jeopardy question he keyed E as the inverse agonist and said antagonists do not change the baseline. E is keyed as the inverse agonist.',
 quote:'Why is not E? Because that will be an inverse agonist that brings everything down to zero. Competitive antagonists or irreversible neutral, they don’t change the baseline. My baseline is at 50%, it’s staying at 50%',
 cite:'Jeopardy 9/30 (IMG_3010); transcript 9/30'},

{id:'JP-002', fg:'partial', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'figure',
 concept:'five-curve-lowest-efficacy', dupOf:'PE-018', tags:['poll','pollev','jeopardy'], source:'both',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E, effect against log dose, with a dotted horizontal line Y; B reaches the top; A, C and E plateau at the same middle height; D plateaus lowest; left to right A, B, C, D, E', imgCap:'Five drugs, one receptor; Y is a dotted horizontal line',
 stem:'Which drug has the lowest efficacy',
 options:[
  {t:'A', correct:false, miss:'efficacy', why:'A plateaus at the middle height, the same as C and E.'},
  {t:'B', correct:false, miss:'read', why:'B reaches the top: the highest efficacy.'},
  {t:'C', correct:false, miss:'efficacy', why:'C plateaus at the middle height.'},
  {t:'D', correct:true, why:'D plateaus lowest of the five.'},
  {t:'E', correct:false, miss:'efficacy', why:'E plateaus at the middle height, the same as A and C.'},
  {t:'Two correct answers', correct:false, miss:'read', why:'On this figure only D sits at the lowest plateau; the tie between two lowest curves belongs to the recap figure, not this one.'}],
 teach:'Efficacy is the height of the plateau. On this figure D plateaus lowest, so D is the single lowest-efficacy drug. The extra option "Two correct answers" was left over from a version of the question on a figure where two curves tie at the lowest plateau.',
 note:'The on-screen stem carried the option "Two correct answers" (on the recap figure C and E tie). On this figure D is the single lowest and he keyed D: "I changed the question".',
 quote:'Everybody chose D. Is that the correct answer? It is. So D as in David, right? Uh, I changed the question, so ... D as in dog was the lowest one',
 cite:'Jeopardy 9/30 (IMG_3011); transcript 9/30'},

{id:'JP-003', fg:'classes', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'drug',
 concept:'baseline50-drug-c-metoprolol', tags:['poll','pollev','jeopardy','metoprolol','drug-list'], source:'both',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises to about 80%, C stays flat at 50%, D falls to about 25%, E falls to 0%', imgCap:'Figure 1: five drugs given alone, each starting from the 50% baseline',
 stem:'Drug C is most likely:',
 options:[
  {t:'Norepinephrine', correct:false, miss:'baseline', why:'Norepinephrine is a full agonist: that would be A.'},
  {t:'Loratadine', correct:false, miss:'baseline', why:'Loratadine is the inverse agonist: that would be E.'},
  {t:'Diazepam', correct:false, miss:'class', why:'Diazepam is the GABA allosteric agonist; on its own it does not move this curve.'},
  {t:'Metoprolol', correct:true, why:'On the information given, C is a competitive antagonist, and metoprolol is the competitive β1 antagonist on the list.'},
  {t:'Histamine', correct:false, miss:'baseline', why:'Histamine is a full agonist: that would be A.'}],
 teach:'Work the figure first, then the drug list. A is a full agonist (norepinephrine or histamine), B and D are partial agonists (B about 80%, D about 25%; albuterol is the partial agonist on the list), E goes to 0 (loratadine, the inverse agonist), and C, flat at the baseline, is a competitive antagonist: metoprolol. Diazepam, an allosteric agonist, would have no effect by itself.',
 quote:'Diazepam is your GABA allosteric agonist, which will not have an effect. Histamine and Norepinephrine will be your full agonist, will be A. Loratadine will be E, the inverse agonist. So C, based on information, will be a competitive antagonist, metoprolol would be the best answer.',
 cite:'Jeopardy 9/30 (IMG_3012); transcript 9/30'},

{id:'JP-004', fg:'potency', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'figure',
 concept:'full-plus-full-left-shift', dupOf:'PE-020', tags:['poll','pollev','jeopardy'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'This figure shows 4 DRCs for 1 drug (X) alone or in the presence of another drug. If curve B is drug X alone, which curve would be X in the presence of an agonist with equal efficacy?',
 options:[
  {t:'A', correct:true, why:'Two full agonists together move the curve to the left: more potent, same maximum.'},
  {t:'B', correct:false, miss:'shift', why:'B is X alone; a second agonist changes the curve.'},
  {t:'C', correct:false, miss:'direction', why:'C is to the right and lower: a drug making life harder, not a second full agonist.'},
  {t:'D', correct:false, miss:'direction', why:'D is a right shift with the same maximum: the competitive antagonist pattern.'},
  {t:'All the above', correct:false, miss:'shift', why:'Only one curve shows the left shift at full height.'}],
 teach:'B reaches the maximal response, so X is a full agonist. A drug with equal efficacy is another full agonist, and two full agonists together shift the curve to the left, making it more potent. That is A.',
 quote:'if it’s two full agonist, it’s gonna move to the left, which is going to make it more potent.',
 note:'His stem says 4 DRCs but the figure on screen is the five-curve recap figure (A–E); only A–D are offered as options. Curve E is not part of the question.',
 cite:'Jeopardy 9/30 (IMG_3013); transcript 9/30'},

{id:'JP-005', fg:'competitive', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'figure',
 concept:'competitive-antagonist-shift', dupOf:'PE-026', tags:['poll','pollev','jeopardy'], source:'both',
 img:'jeop-a-plus-b', imgAlt:'Response percent of control against agonist concentration from 10^-9 to 10^-3 M: a dashed red curve A on the left, then four solid curves A + [B], A + 10x[B], A + 100x[B] and A + 1000x[B] shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'Dotted: drug A alone; solid: A with increasing concentrations of B',
 stem:'Dotted line is Drug A alone, solid lines is A in the presence of increasing concentrations of B. B is:',
 options:[
  {t:'Competitive antagonist', correct:true, why:'Shift to the right without a change in the baseline or the Emax, in equal steps.'},
  {t:'Irreversible antagonist', correct:false, miss:'emax', why:'Four shifts and the Emax never drops.'},
  {t:'Full agonist', correct:false, miss:'direction', why:'A full agonist would shift the curve to the left.'},
  {t:'Allosteric agonist', correct:false, miss:'direction', why:'An allosteric agonist helps; this drug makes life harder.'},
  {t:'Partial agonist', correct:false, miss:'baseline', why:'A partial agonist would pull the top toward its own efficacy; the top is unchanged.'}],
 teach:'The dose is shifting to the right without any change in the baseline or the Emax, so it cannot be irreversible. It cannot be an allosteric agonist, a full agonist or a partial agonist, which would help or change the top. So it has to be a competitive antagonist.',
 quote:'It’s shifting the dose to the right without affecting the baseline or the Emax. Thus cannot be irreversible. It can’t be allosteric agonist or full agonist or partial agonist, so it has to be competitive antagonist.',
 cite:'Jeopardy 9/30 (IMG_3014); transcript 9/30'},

{id:'JP-006', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'figure',
 concept:'five-curve-lowest-affinity', dupOf:'PE-030', tags:['poll','pollev','jeopardy'], source:'both',
 img:'jeop-abcde-effect', imgAlt:'Five dose-response curves A to E, effect from 0.0 to 100% against log agonist; left to right A, B, C, D, E; B and E reach 100%, C plateaus at about 85%, D at about 70%, A at about 65%', imgCap:'Effect vs Log [Agonist]',
 stem:'Which drug has the lowest affinity?',
 options:[
  {t:'A', correct:false, miss:'affinity', why:'A is the farthest left: the highest affinity.'},
  {t:'B', correct:false, miss:'affinity', why:'B is second from the left.'},
  {t:'C', correct:false, miss:'affinity', why:'C is in the middle.'},
  {t:'D', correct:false, miss:'affinity', why:'D is to the right of C but left of E.'},
  {t:'E', correct:true, why:'E is the farthest to the right: it needs the highest concentration to bind, the lowest affinity.'}],
 teach:'Affinity is read left to right on the x-axis. The curve farthest to the right needs the highest concentration to produce its effect, so it has the lowest affinity: E.',
 quote:'E as in elephant ... that’s a concept everybody seems to get',
 cite:'Jeopardy 9/30 (IMG_3015); transcript 9/30'},

{id:'JP-007', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'recall',
 concept:'affinity-needed-to-bind', tags:['poll','pollev','jeopardy'], source:'both',
 stem:'In order to bind to a receptor, a drug needs:',
 options:[
  {t:'Affinity', correct:true, why:'Affinity is the ability to bind and stay bound; it is the requirement for binding.'},
  {t:'Efficacy', correct:false, why:'Efficacy is what the drug does once bound; an antagonist binds with no efficacy.'},
  {t:'Positive charges', correct:false, why:'Charge is one way to form a bond, not a requirement for binding.'},
  {t:'Be metabolized', correct:false, why:'Metabolism is what happens to the drug, not what it needs to bind.'},
  {t:'Be an orthosteric agonist', correct:false, why:'Antagonists and allosteric drugs bind too.'}],
 teach:'To bind a receptor a drug needs affinity; efficacy is a separate property that decides what happens after binding. Antagonists have affinity without efficacy; allosteric drugs bind at a second site.',
 cite:'Jeopardy 9/30 (IMG_3016); transcript 9/30'},

{id:'JP-008', fg:'irreversible', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'recall',
 concept:'irreversible-lowers-emax', dupOf:'L04-037', tags:['poll','pollev','jeopardy'], source:'both',
 stem:'An irreversible antagonist is more likely:',
 options:[
  {t:'To only form hydrogen bonds', correct:false, why:'Irreversible binding is covalent; hydrogen bonds are reversible.'},
  {t:'Enhance the potency of a partial agonist', correct:false, why:'An antagonist never enhances an agonist.'},
  {t:'Increase the baseline and shift the DRC to the left', correct:false, why:'That is a second agonist; an antagonist shifts right and does not raise the baseline.'},
  {t:'Decrease the ability of an agonist to reach Emax', correct:true, why:'By binding covalently it removes receptors, chemically down-regulating them, so the agonist can no longer reach its maximum.'}],
 teach:'An irreversible antagonist forms covalent bonds and takes receptors out of use: it chemically down-regulates them. The agonist is shifted to the right and, once the spare receptors are gone, can no longer reach its Emax.',
 quote:'It will decrease the ability of agonists to get to the Emax because you’re removing, you’re down regulating the receptors chemically',
 cite:'Jeopardy 9/30 (IMG_3017); transcript 9/30'},

{id:'JP-009', fg:'gpcr-steps', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'recall', type:'match',
 concept:'gpcr-forward-steps', dupOf:'L06-034', tags:['poll','pollev','jeopardy'], source:'both',
 stem:'Walk me through the G-protein signaling pathway (norepinephrine at the β1 receptor). Match each step number to what happens going forward.',
 left:['Step 1', 'Step 2', 'Step 3', 'Step 4', 'Step 5', 'Step 6', 'Step 7', 'Step 8'],
 right:['Norepinephrine binds the β1 receptor', 'The receptor changes conformation', 'GDP comes off and GTP comes on', 'αs leaves β and γ', 'αs activates adenylate cyclase', 'ATP is converted into cAMP, the second messenger', 'cAMP does the cell signalling', 'Physiological response'],
 pairs:[
  {l:'Step 1', r:'Norepinephrine binds the β1 receptor', why:'The signal binds the receptor.'},
  {l:'Step 2', r:'The receptor changes conformation', why:'The activated receptor changes shape.'},
  {l:'Step 3', r:'GDP comes off and GTP comes on', why:'The diphosphate is displaced and replaced with the triphosphate.'},
  {l:'Step 4', r:'αs leaves β and γ', why:'The α subunit dissociates; β and γ stay together.'},
  {l:'Step 5', r:'αs activates adenylate cyclase', why:'The transducer activates the effector.'},
  {l:'Step 6', r:'ATP is converted into cAMP, the second messenger', why:'The effector makes the second messenger.'},
  {l:'Step 7', r:'cAMP does the cell signalling', why:'The second messenger carries the signal inside the cell.'},
  {l:'Step 8', r:'Physiological response', why:'The end of the pathway: the heart rate goes up.'}],
 teach:'Forward: norepinephrine binds β1; the receptor changes conformation; GDP comes off and GTP comes on; αs leaves β and γ; αs activates adenylate cyclase; ATP is converted to cAMP, the second messenger; cAMP does the cell signalling; physiological response. Backward: PDE breaks down cAMP; the extra phosphate is removed (GTP to GDP); α reassembles with β and γ; the receptor resets.',
 note:'This was an open-answer round (each team member gave one step forward, then backward). The team said the α subunit binds adenylyl cyclase and then β and γ bind to another receptor; he accepted the gist, but the slides have β and γ staying together while the α subunit carries the signal. The slide version is used here.',
 quote:'so we got the displacement of the GDP, the diphosphate, and it’s replaced with GTP ... ATP gets converted into cAMP, which is our second messenger and then cAMP is going to do what, cell signaling and then that’s going to cause a physiological response.',
 cite:'Jeopardy 9/30 (IMG_3018); transcript 9/30'},

{id:'JP-010', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'tell',
 concept:'efficacy-definition', dupOf:'PE-006', tags:['poll','pollev','jeopardy'], source:'both',
 stem:'Efficacy:',
 options:[
  {t:'Is a measure of the chemical bonds a drug-receptor forms', correct:false, why:'The bonds define affinity, not efficacy.'},
  {t:'Is measured in the X-axis', correct:false, why:'The x-axis (left and right) is affinity and potency; efficacy is up and down.'},
  {t:'Is inversely proportional to the Kd', correct:false, why:'The Kd is an affinity measure; a smaller Kd means a greater affinity, and it says nothing about efficacy.'},
  {t:'Is a stimulus measured in the Y-axis', correct:true, why:'Efficacy is the stimulus the bound drug produces, read up and down on the y-axis.'}],
 teach:'Efficacy is the stimulus a bound drug produces, measured on the y-axis. Affinity is based on the bonds the drug forms and is read on the x-axis; the Kd belongs to affinity, not efficacy.',
 quote:'efficacy is the stimulus measure in the Y-axis, right?',
 cite:'Jeopardy 9/30 (IMG_9313); transcript 9/30'},

{id:'JP-011', fg:'classes', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'figure',
 concept:'transporter-blocker-increases-apparent-potency', dupOf:'L05-011', tags:['poll','pollev','jeopardy'], source:'both',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E, effect against log dose, with a dotted horizontal line Y; B reaches the top; A, C and E plateau at the same middle height; D plateaus lowest; left to right A, B, C, D, E', imgCap:'Five drugs, one receptor; Y is a dotted horizontal line',
 stem:'DRC "C" is the DRC of an 5HT alone, which DRC would represent "5HT" in the presence of prozac, a 5HT transporter antagonist (SERT)?',
 options:[
  {t:'A', correct:true, why:'Same plateau as C, moved to the left: more serotonin in the synapse makes it more potent, and it is still the same drug on the same receptors, so the top does not change.'},
  {t:'B', correct:false, miss:'emax', why:'B reaches a higher top; blocking the transporter changes the concentration of serotonin, not its efficacy or the number of receptors.'},
  {t:'C', correct:false, miss:'shift', why:'C is serotonin alone; more serotonin moves the curve.'},
  {t:'D', correct:false, miss:'direction', why:'D is to the right and lower: less potent, less efficacious, the opposite of more transmitter.'},
  {t:'E', correct:false, miss:'direction', why:'E is to the right: less potent, the opposite of what more serotonin does.'}],
 teach:'Prozac blocks the serotonin transporter, so the serotonin level goes up and serotonin looks more potent: C, D and E are out. Why A and not B: Prozac is an indirect antagonist binding the transporter, not the receptor, and it is still the same serotonin on the same number of receptors. If serotonin was a partial agonist alone it is still a partial agonist, so the plateau stays and only the concentration changed.',
 note:'He said "the stem for this question is wrong": Prozac is an SSRI, a reuptake inhibitor acting on the transporter, not an antagonist at the serotonin receptor. The stem is kept as shown on screen.',
 quote:'Prozac is binding to the transporter, so it’s not directly affecting the receptor signal, and it’s still serotonin. You didn’t change the drug. So if serotonin was a partial agonist here, it’s going to be a partial agonist there too, because you didn’t change the number of receptors. You just changed the concentration of the drug.',
 cite:'Jeopardy 9/30 (IMG_9314); transcript 9/30'},

{id:'JP-012', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'apply',
 concept:'smallest-kd-irreversible', dupOf:'PE-053', tags:['poll','pollev','jeopardy'], source:'both',
 stem:'Which of the following is most likely an irreversible antagonist?',
 options:[
  {t:'Drug A (Kd =100 nmol)', correct:true, why:'Nano is 10 to the -9: the smallest Kd, the greatest affinity, which is what covalent bonds give.'},
  {t:'Drug B (Kd =50 μmol)', correct:false, why:'Micro is 10 to the -6: a larger Kd than nanomolar, a weaker bond.'},
  {t:'Drug C (Kd =2 mmol)', correct:false, why:'Milli is 10 to the -3: weaker still.'},
  {t:'Drug D (Kd =300 mol)', correct:false, why:'Whole moles: the largest Kd, the lowest affinity.'}],
 teach:'An irreversible antagonist forms covalent bonds, the strongest bonds, so it has the smallest Kd. Compare the units first: nano (10^-9) is smaller than micro (10^-6), milli (10^-3) and moles. Drug A has the smallest Kd.',
 quote:'It’s irreversible. It’s gonna form covalent bonds, which means it’s gonna get the what, the smallest Kd, right? ... If you have a nano, it’s 10 to the -9, which would be the correct answer.',
 cite:'Jeopardy 9/30 (IMG_9315); transcript 9/30'},

{id:'JP-013', fg:'potency', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'figure',
 concept:'four-drug-potency-efficacy', dupOf:'L03-044', tags:['poll','pollev','jeopardy'], source:'both',
 img:'jeop-abcde-effect', imgAlt:'Five dose-response curves A to E, effect from 0.0 to 100% against log agonist; left to right A, B, C, D, E; B and E reach 100%, C plateaus at about 85%, D at about 70%, A at about 65%', imgCap:'Effect vs Log [Agonist]',
 stem:'Which drug is the most potent?',
 options:[
  {t:'A', correct:true, why:'A has the smallest ED50: it requires the smallest dose to produce equivalent responses.'},
  {t:'B', correct:false, miss:'potency', why:'B reaches 100% but its ED50 is to the right of A’s; more efficacious, less potent.'},
  {t:'C', correct:false, miss:'potency', why:'C reaches 100% in the middle of the axis; a larger ED50 than A or B.'},
  {t:'D', correct:false, miss:'potency', why:'D is to the right; a larger ED50.'},
  {t:'E', correct:false, miss:'potency', why:'E is the farthest right: the least potent.'}],
 teach:'Potency is the ED50, read left to right. A has the smallest ED50 and requires the smallest dose to produce equivalent responses, so A is the most potent even though B and C reach a higher maximum.',
 quote:'A is the most potent. Why A is the most potent? Because it has the smallest ED 50. It does require the smallest dose to produce equivalent responses.',
 cite:'Jeopardy 9/30 (IMG_9316); transcript 9/30'},

{id:'JP-014', fg:'classes', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'tell',
 concept:'allosteric-antagonist-vs-indirect', tags:['poll','pollev','jeopardy'], source:'both',
 stem:'An allosteric antagonist',
 options:[
  {t:'Competes for the orthosteric site', correct:false, why:'An allosteric drug binds someplace else on the receptor, not the orthosteric site.'},
  {t:'Can increase the efficacy of a partial agonist', correct:false, why:'It is an antagonist: it decreases, it does not make the agonist better.'},
  {t:'Can decrease the affinity of an agonist for its receptor', correct:true, why:'Binding at its own site on the receptor, it can lower the agonist’s affinity: "Probably so."'},
  {t:'Is a drug the binds downstram from the receptor and decreases the response', correct:false, why:'A drug that binds downstream or upstream of the receptor is an indirect antagonist; the allosteric antagonist binds the receptor itself at a different site.'}],
 teach:'An allosteric antagonist binds the receptor at a site other than the orthosteric site, so it does not compete there, and being an antagonist it lowers the agonist’s affinity or efficacy, never raises it. A drug that binds downstream or upstream of the receptor is an indirect antagonist, not an allosteric one.',
 quote:'Is a drug that binds downstream, that will be an indirect antagonist, right? Drugs that bind downstream or upstream from the receptor, those are indirect antagonists. Allosteric binds to the receptor but at a different site of it.',
 cite:'Jeopardy 9/30 (IMG_9317); transcript 9/30'},

{id:'JP-015', fg:'gpcr-steps', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'recall',
 concept:'g-protein-defined-by-alpha', dupOf:'PE-009', tags:['poll','pollev','jeopardy'], source:'both',
 stem:'Which of the following is CORRECT?',
 options:[
  {t:'cAMP is an example of an effector system', correct:false, why:'cAMP is a second messenger; the effector is the enzyme that makes it (adenylate cyclase).'},
  {t:'G-proteins are defined and regulated by the alpha subunit', correct:true, why:'G proteins are defined by the alpha subunit: alpha S, alpha I, alpha Q.'},
  {t:'PLC is an example of a second messanger', correct:false, why:'Phospholipase C is an effector system; its second messenger is IP3.'},
  {t:'In order for g-proteins to dissociate from the receptor, the GTP has to be released', correct:false, why:'It is the GDP that comes off and the GTP that comes in; the extra phosphate is what makes them dissociate.'}],
 teach:'A G protein is defined by its alpha subunit: αs, αi, αq. cAMP is a second messenger, not an effector; PLC is an effector, not a second messenger. Dissociation happens when the diphosphate (GDP) comes off and the triphosphate (GTP) comes in: more phosphate, more energy.',
 quote:'a G protein, remember they’re gonna be defined by the alpha subunit. It’s alpha S, alpha I, alpha Q ... G protein dissociation from the receptor is not the GTP, it’s the GDP, right? It’s the diphosphate comes off, the triphosphate comes in',
 cite:'Jeopardy 9/30 (IMG_9318); transcript 9/30'},

{id:'JP-016', fg:'inverse', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'apply',
 concept:'inverse-plus-full-agonist-50', tags:['poll','pollev','jeopardy'], source:'both',
 stem:'What effect an inverse agonist would have on a full agonist DRC? Assume that the tissue has 50% of receptor present in the active state (R = R*).',
 options:[
  {t:'It would decrease the ability of a full agonist to reach its Emax', correct:false, why:'An inverse agonist is competitive; enough agonist still reaches the Emax.'},
  {t:'It would decrease the baseline and shift the DRC to the right', correct:true, why:'The inverse agonist pulls the 50% baseline down, and by competing with the agonist it makes a higher dose necessary: a right shift.'},
  {t:'It would shift the DRC of the agonist to the left and increase the baseline', correct:false, why:'That is a second agonist helping, the opposite of an inverse agonist.'},
  {t:'It would decrease the ED50 value of the agonist, but it will increase its efficacy', correct:false, why:'A smaller ED50 means more potent; an inverse agonist makes the agonist less potent and does not change its efficacy.'},
  {t:'It would evoke non-symmetrical shifts to the right and change the efficacy of an agonist', correct:false, why:'Non-symmetrical shifts are allosteric; an inverse agonist competes at the orthosteric site and gives symmetrical shifts with no change in efficacy.'}],
 teach:'In a tissue where 50% of the receptors are active, the baseline is 50%. Alone, the full agonist goes up and the inverse agonist goes down to 0. Together, the inverse agonist decreases the baseline (that is what it wants to do) and shifts the agonist to the right (they compete, so a higher dose is needed to overcome it). The Emax is not affected.',
 quote:'It would decrease the baseline because that’s what the inverse wants to do. And we shifted those responses of my agonist to the right, because they are competing with each other, it’s gonna require a higher dose to overcome that drug.',
 cite:'Jeopardy 9/30 (IMG_9319); transcript 9/30'},

{id:'JP-017', fg:'irreversible', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'drug',
 concept:'irreversible-antagonist-curve', dupOf:'L04-037', tags:['poll','pollev','jeopardy','phenoxybenzamine','drug-list'], source:'both',
 img:'jeop-abcde-effect', imgAlt:'Five dose-response curves A to E, effect from 0.0 to 100% against log agonist; left to right A, B, C, D, E; B and E reach 100%, C plateaus at about 85%, D at about 70%, A at about 65%', imgCap:'Effect vs Log [Agonist]; B is norepinephrine alone, D is norepinephrine with phenoxybenzamine',
 stem:'If the DRC "B" is the DRC of NE alone and DRC "D" is the agonist in the presence of phenoxybenzamine, drug "X" is most likely:',
 options:[
  {t:'Competitive antagonist', correct:false, miss:'emax', why:'A competitive antagonist shifts right but keeps the Emax; D is lower than B.'},
  {t:'Irreversible antagonist', correct:true, why:'Shift to the right with a lower Emax; and phenoxybenzamine is the one irreversible antagonist on the drug list.'},
  {t:'Full agonist', correct:false, miss:'direction', why:'A full agonist would shift the curve to the left.'},
  {t:'Allosteric agonist', correct:false, miss:'direction', why:'An allosteric agonist helps; D is to the right and lower.'},
  {t:'Partial agonist', correct:false, miss:'baseline', why:'A partial agonist would raise the baseline in a system with activity, and it does not shift a full agonist to the right at a lower top this way.'}],
 teach:'B to D is a shift to the right with a lower Emax: not competitive (Emax kept), not a full agonist, not allosteric agonist, not partial (the baseline is not raised). That leaves the irreversible antagonist. Knowing the drug list bypasses the figure: phenoxybenzamine is irreversible.',
 quote:'this drug is shifting to the right and lowering the Emax, which it means it can’t be a competitive, it can’t be a full, it can’t be allosteric, and it can’t be a partial because it’s not raising the baseline ... if you knew that phenoxybenzamine is an irreversible antagonist, you could bypass all that',
 cite:'Jeopardy 9/30 (IMG_9320); transcript 9/30'},

{id:'JP-018', fg:'two-state', lecture:'JP', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'recall',
 concept:'inverse-agonist-affinity-inactive', dupOf:'L02-025', tags:['poll','pollev','jeopardy'], source:'both',
 stem:'Which of the following drugs would have the highest affinity for receptors present in the inactive state?',
 options:[
  {t:'Full agonist', correct:false, why:'A full agonist has the highest affinity for active receptors; it wants to keep them active.'},
  {t:'Partial agonist', correct:false, why:'A partial agonist leans toward the active state, with less efficacy than a full agonist.'},
  {t:'Inverse agonist', correct:true, why:'The inverse agonist has the highest affinity for inactive receptors and wants to keep them inactive.'},
  {t:'Competitive antagonist', correct:false, why:'A neutral antagonist binds active and inactive receptors alike and changes nothing.'},
  {t:'Indirect antagonist', correct:false, why:'An indirect antagonist does not bind the receptor at all.'}],
 teach:'A full agonist has the highest affinity for receptors that are active and keeps them active. The inverse agonist has the highest affinity for receptors that are inactive and keeps them inactive. The class got this flip-flopped in the game.',
 quote:'full agonist has the highest affinity for that receptor that are active because they wanna keep them active. The inverse has the highest affinity for receptor that are inactive, and they wanna keep them inactive, right?',
 cite:'Jeopardy 9/30 (IMG_9321); transcript 9/30'},

{id:'JP-019', fg:'irreversible', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'JP', sub:'verbatim', skill:'drug',
 concept:'phenoxybenzamine-irreversible', dupOf:'L02-012', tags:['poll','pollev','phenoxybenzamine','drug-list'], source:'both',
 stem:'Which of the following is an irreversible antagonist?',
 options:[
  {t:'Phenylephrine', correct:false, why:'Phenylephrine is an α1 agonist.'},
  {t:'Prazosin', correct:false, why:'Prazosin is a reversible α1 antagonist.'},
  {t:'Diazepam', correct:false, why:'Diazepam is the GABA receptor allosteric agonist; all allosterics in this course are reversible.'},
  {t:'Phenoxybenzamine', correct:true, why:'Phenoxybenzamine is the only irreversible antagonist on the list: α1 and α2, covalent.'},
  {t:'None of the above', correct:false, why:'One of them is irreversible.'}],
 teach:'Phenoxybenzamine is the one irreversible drug on the Exam 1 list, an α1 and α2 antagonist that binds covalently. Prazosin blocks α1 reversibly, phenylephrine is an α1 agonist, and diazepam is a reversible allosteric agonist.',
 quote:'100% say phenoxybenzamine, that’s the only one that is irreversible, right, that you have to learn so far.',
 cite:'PollEV_s.pdf page 6 (run 9/30 before the review); transcript 9/30'}
);
