TOPICS.push({id:'L04', name:'Drug–receptor interactions I: two-state model, inverse agonists, allosterics, antagonists', prof:'Gottlieb', lecture:'L04',
  cite:'Day 4 (9/28) — Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf (Part 1) and the Day 3 recap slides',
  subs:[
    {id:'recap', name:'Two-state recap: full agonist, partial agonist, FA + FA, FA + PA', cite:'Day 3 deck slides ~31–~65 (lectured 9/28); Day 4 deck slide ~3'},
    {id:'ia', name:'Inverse agonist alone and full agonist + inverse agonist', cite:'slides ~4–~24'},
    {id:'allo', name:'Allosteric agonists and antagonists', cite:'slides ~25–~34, ~36–~42'},
    {id:'antag', name:'Kinds of antagonism and antagonist names', cite:'slides ~35–~37'},
    {id:'comp', name:'Competitive antagonist', cite:'slides ~43–~50, ~55'},
    {id:'irrev', name:'Irreversible antagonist, Emax rule and spare receptors', cite:'slides ~51–~56'}
  ]});
QUESTIONS.push(
{id:'L04-001', fg:'two-state', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'tell',
 concept:'full-vs-partial-agonist-summary', tags:[], source:'transcript',
 stem:'In the two-state model, which property do a full agonist and a partial agonist share?',
 options:[
  {t:'Highest affinity for active-state receptors', correct:true, why:'Both bind active receptors best and keep them active; both also have positive efficacy and are reversible.'},
  {t:'The ability to reach 100% of the system’s response', correct:false, why:'Only the full agonist reaches 100%; the partial agonist plateaus below that.'},
  {t:'Negative efficacy', correct:false, why:'Both have positive efficacy; negative efficacy belongs to the inverse agonist.'},
  {t:'Equal affinity for active and inactive receptors', correct:false, why:'Equal affinity for both states describes the neutral competitive antagonist.'}],
 teach:'Full and partial agonists are alike in the two-state model: both have the highest affinity for receptors in the active state, both can bind an inactive receptor and turn it on (positive efficacy), and both are reversible. They differ only in how much efficacy they carry: the full agonist reaches 100%, the partial agonist plateaus between 1% and 99%.',
 quote:'So when we think about full and partial agonists, the first thing that should come to mind is they love receptors that are active, and if they bind to, they’re gonna have the highest affinity for those receptors. However, if they bind to receptors that are inactive, they can shut, they can turn them on, right?',
 cite:'transcript 9/28; Pharmacodynamics-Day_3_2026s.pdf slides ~32–~41',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'Full agonists shift the conformational equilibrium of receptors more strongly than partial agonists do.'}]},

{id:'L04-002', fg:'two-state', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'apply',
 concept:'baseline-reflects-receptor-activity', tags:[], source:'transcript',
 stem:'A full agonist is given to a cell in which 50% of the receptors are active on their own. Where does its dose–response curve start and where does it end?',
 options:[
  {t:'Starts at 50%, ends at 100%', correct:true, why:'The baseline reflects the receptors already active; a full agonist has 100% efficacy, so it goes to 100% from wherever it starts.'},
  {t:'Starts at 0% and ends at 100%', correct:false, why:'A baseline of 0% belongs to a system in which nearly all receptors are inactive (R > R*).'},
  {t:'Starts at 50%, ends at 50%', correct:false, why:'A flat line at the baseline is what a neutral antagonist gives, not a full agonist.'},
  {t:'Starts at 50%, ends at 0%', correct:false, why:'Going down to 0% is the inverse agonist’s curve.'}],
 teach:'The baseline is a reflection of the receptor activity in the system before any drug is given. With most receptors inactive (R > R*, one sign on the exam means about 99% inactive) the baseline is 0%. With half the receptors active it is 50%. A full agonist goes to 100% independently of where it starts; if all receptors are already active the curve is a flat line at 100%.',
 quote:'It, the baseline is just a reflection of the receptor activity that is happening. But when I go from 50, I go all the way to 100.',
 cite:'transcript 9/28; Pharmacodynamics-Day_3_2026s.pdf slides ~37–~40'},

{id:'L04-003', fg:'partial', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'figure', multi:true,
 concept:'partial-agonist-range', tags:[], source:'transcript',
 stem:'Five drugs at the same receptor reach these maximal effects on their own: drug A 80%, drug B 75%, drug C 25%, drug D 5% and drug E 100%. Which are partial agonists? Select all that apply.',
 options:[
  {t:'Drug A (80%)', correct:true, why:'Any effect between 1% and 99% is a partial agonist; 80% is close to the top but not 100%.'},
  {t:'Drug B (75%)', correct:true, why:'75% lies between 1% and 99%.'},
  {t:'Drug C (25%)', correct:true, why:'25% lies between 1% and 99%.'},
  {t:'Drug D (5%)', correct:true, why:'5% is a weak but positive effect, so the drug is still a partial agonist.'},
  {t:'Drug E (100%)', correct:false, why:'A drug that reaches 100% is a full agonist, not a partial agonist.'}],
 teach:'A partial agonist is any drug that produces an effect between 1% and 99% of the system’s maximum: equal to or greater than 1 and equal to or less than 99. At 100% it is a full agonist; at 0% it is not a partial agonist. A curve that gets close to 100% but does not reach it is still partial.',
 quote:'a partial agonist is going to be any drug that produce an effect between 1 and 99, right? Has to be equal or greater than 1, and equal or less than 99.',
 cite:'transcript 9/28; Pharmacodynamics-Day_3_2026s.pdf slides ~50–~52',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists', t:'Partial agonists produce a lower response at full receptor occupancy than full agonists do.'}]},

{id:'L04-004', fg:'drc-basic', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'figure',
 concept:'fa-plus-fa', tags:[], source:'transcript',
 stem:'Norepinephrine and Levophed (synthetic norepinephrine) are full agonists at the same receptor. A pretreatment dose of Levophed that by itself produces 40% of the maximal effect is given, then a norepinephrine dose–response curve is built. How does norepinephrine’s curve change?',
 options:[
  {t:'Starts at 40%, shifts left, still reaches 100%', correct:true, why:'Levophed has already activated enough receptors for 40%, norepinephrine needs fewer receptors of its own (shift left), and both drugs reach the same Emax.'},
  {t:'Starts at 0%, shifts right, still reaches 100%', correct:false, why:'A second full agonist helps; a right shift belongs to drugs that compete against the agonist.'},
  {t:'Starts at 40%, shifts left, plateaus at 60%', correct:false, why:'Emax does not change: the heart cannot beat faster than its maximum whether one or two full agonists are present.'},
  {t:'Starts at 0%, no shift, reaches 100%', correct:false, why:'A dose that already produces 40% raises the starting point, and the shared work shifts the curve left.'}],
 teach:'A full agonist in the presence of another full agonist: the second drug activates some receptors on the first drug’s behalf, so the first drug appears more potent (shift left, apparent affinity increased); a pretreatment dose that already produces an effect raises the baseline; and Emax is unchanged since both are reversible and both want the same maximal effect.',
 quote:'now norepinephrine still goes to 100%, but it’s further to the left and the baseline has going up, right? Because levofed has efficacy, positive efficacy.',
 cite:'transcript 9/28; Pharmacodynamics-Day_3_2026s.pdf slides ~42–~49'},

{id:'L04-005', fg:'potency', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'figure',
 concept:'fa-plus-fa', tags:['poll'], source:'both',
 stem:'Dose–response curve B is norepinephrine binding to the β1 receptor alone. Curve A lies to the left of B with the same maximum; the remaining curves lie to the right of B or below it. Which curve best represents norepinephrine in the presence of epinephrine?',
 options:[
  {t:'A', correct:true, why:'Norepinephrine and epinephrine are both full agonists at β1; each makes the other appear more potent, so the curve moves left.'},
  {t:'B', correct:false, why:'B is the point of reference (norepinephrine alone); a second full agonist changes the curve.'},
  {t:'C', correct:false, why:'A curve to the right means the agonist appears less potent, which is what a competing drug does, not a helping one.'},
  {t:'D', correct:false, why:'A lower or right-shifted curve would mean epinephrine made norepinephrine’s life harder; two full agonists help each other.'},
  {t:'None of the above', correct:false, why:'One curve (A) does show the left shift produced by a second full agonist.'}],
 teach:'The first question to ask is whether the second drug helps the agonist or makes its life more difficult. A second full agonist helps, so the only possible answers are curves to the left; curves to the right or below are eliminated. Norepinephrine makes epinephrine more potent and epinephrine makes norepinephrine more potent.',
 quote:'we have two full agonists, norepinephrine and Epi, that binds to the same receptor and depending on who is bound to it, they’re going to do the same effect. And thus shifting to the left.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~3; transcript 9/28'},

{id:'L04-006', fg:'partial', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'apply',
 concept:'fa-plus-pa-aripiprazole', tags:[], source:'transcript',
 stem:'A manic patient has a high level of dopamine (full agonist, Emax 100%) at the dopamine D2 receptor. Therapy with aripiprazole, a D2 partial agonist with an Emax of 60%, is started. What happens to the response as aripiprazole occupies more receptors than dopamine?',
 options:[
  {t:'It falls toward 60%', correct:true, why:'Both drugs are reversible; whichever has the higher concentration occupies more receptors, and receptors occupied by aripiprazole can only produce its 60%.'},
  {t:'It rises to 100%', correct:false, why:'Adding a partial agonist to a system already at 100% cannot add efficacy; it competes and brings the response down.'},
  {t:'It falls to 0%', correct:false, why:'Only an inverse agonist brings the response to 0%; a partial agonist brings it to its own efficacy.'},
  {t:'It stays unchanged at 100%', correct:false, why:'Once aripiprazole outcompetes dopamine by mass action, the occupied receptors signal at 60%, so the response changes.'}],
 teach:'Dopamine and aripiprazole compete for the same D2 binding pocket and both are reversible, so by the law of mass action the drug with the higher concentration occupies more receptors. Receptors occupied by aripiprazole signal at its efficacy of 60%, so in a manic (high dopamine) patient the response is brought down to about 60%; in a depressed patient (low baseline) the same drug brings the response up.',
 quote:'as long as I’m occupying enough receptors, more than dopamine is, I can outcompete dopamine and bring that baseline to about 60%. So that my patient is not manic anymore.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~54–~58; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists', t:'A partial agonist cannot cause a maximal response even when it saturates all receptors, so it competitively inhibits the responses produced by a full agonist at the same receptor.'}]},

{id:'L04-007', fg:'inverse', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'tell',
 concept:'partial-vs-inverse-endpoint', tags:[], source:'transcript',
 stem:'A system starts at 100% activity. A partial agonist with 75% efficacy is given to one preparation and an inverse agonist to another, each in high enough dose to occupy most receptors. Where does each response end?',
 options:[
  {t:'Partial agonist 75%; inverse agonist 0%', correct:true, why:'A partial agonist brings the response to whatever its own efficacy is; an inverse agonist brings it to 0%.'},
  {t:'Partial agonist 100%; inverse agonist 0%', correct:false, why:'A partial agonist never reaches 100%, not alone and not when competing with a full agonist.'},
  {t:'Partial agonist 75%; inverse agonist 25%', correct:false, why:'The inverse agonist has negative efficacy and ends at 0% regardless of the starting point.'},
  {t:'Partial agonist 0%; inverse agonist 0%', correct:false, why:'A partial agonist has positive efficacy; once it occupies the receptors the response is its 75%, not zero.'}],
 teach:'A partial agonist has a dual nature: from a low baseline it raises the response (agonist behavior) and from a high baseline it competes the response down (antagonist behavior), but in every case the endpoint is its own efficacy (75% goes to 75%, 30% to 30%). An inverse agonist ends at 0% whether the baseline was 25%, 50% or 100%.',
 quote:'The key difference over here when we compare to inverse agonist is that a partial agonist is only going to bring the dose response curve to whatever its efficacy is. If it’s 75%, everything finishes at 75%.',
 cite:'transcript 9/28; Pharmacodynamics-Day_3_2026s.pdf slides ~59–~63; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~12'},

{id:'L04-008', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'apply',
 concept:'partial-agonist-dual-nature', tags:['varenicline'], source:'transcript',
 stem:'A patient taking varenicline (Chantix), a nicotinic partial agonist, for smoking cessation smokes one cigarette. Compared with smoking before therapy, what does that cigarette do?',
 options:[
  {t:'Produces less effect than before', correct:true, why:'Varenicline is present at a concentration high enough to outcompete the nicotine from one cigarette, so the receptors signal at the partial agonist’s level.'},
  {t:'Produces a larger effect than before', correct:false, why:'A partial agonist occupying receptors competes with nicotine; it does not add to a full agonist’s effect.'},
  {t:'Produces the same effect as before', correct:false, why:'Receptors occupied by varenicline cannot give nicotine’s full response.'},
  {t:'Brings the response to 0%', correct:false, why:'A partial agonist has positive efficacy; bringing everything to 0% is the inverse agonist.'}],
 teach:'Varenicline serves two purposes. In withdrawal (no nicotine, receptors inactive) it activates some nicotinic receptors and removes the cravings without opening the ion channel 100%. If the patient smokes, varenicline outcompetes the nicotine of a cigarette, so the cigarette does little; only nonstop smoking could outcompete varenicline. Which behavior appears depends on the physiological state.',
 quote:'If they start to smoke and they’re taking Chantix, now Chantix is gonna outcompete nicotine, so that one cigarette, it’s not gonna do much for them.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~64–~65; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Variation in Drug Responsiveness', t:'A partial agonist may exhibit dramatically different responses depending on the amount of endogenous full agonist present, acting as an agonist when it is low and as an antagonist when it is high.'}]},

{id:'L04-009', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'recall',
 concept:'partial-agonist-table', tags:['poll','albuterol'], source:'both',
 stem:'Which of the following drugs is a partial agonist?',
 options:[
  {t:'Albuterol', correct:true, why:'Albuterol is the β2 partial agonist on the drug list; it opens the airways enough for an asthma patient to breathe without opening them 100%.'},
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist.'},
  {t:'Histamine', correct:false, why:'Histamine is the body’s full agonist at histamine receptors.'},
  {t:'Acetylcholine', correct:false, why:'Acetylcholine is a full agonist.'},
  {t:'Metoprolol', correct:false, why:'Metoprolol is a competitive antagonist at β1.'}],
 teach:'From the drug list, albuterol is the partial agonist; the others in this poll are agonists (epinephrine, histamine, acetylcholine) or an antagonist (metoprolol). A partial agonist is used when the maximal response is not needed: albuterol opens the airways just enough for an asthma patient to breathe better.',
 quote:'If your patient has asthma, albuterol, which is a partial agonist, is going to open up your airways just enough for you to breathe better in and out. You don’t have to open your lungs 100%.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~3; transcript 9/28'},

{id:'L04-010', fg:'inverse', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'recall', multi:true,
 concept:'inverse-agonist-two-state', tags:[], source:'both',
 stem:'Which statements describe an inverse agonist in the two-state model? Select all that apply.',
 options:[
  {t:'Highest affinity for receptors in the inactive state', correct:true, why:'It binds and stabilizes the receptor in the inactive state.'},
  {t:'Negative efficacy', correct:true, why:'If it binds an active receptor it shuts it off, shifting DR* to DR.'},
  {t:'Reversible', correct:true, why:'All inverse agonists on the market are reversible: they bind and come off.'},
  {t:'Highest affinity for receptors in the active state', correct:false, why:'Preference for active receptors belongs to full and partial agonists.'},
  {t:'Ends the curve between 1% and 99%', correct:false, why:'An inverse agonist brings the curve all the way to 0%; the 1–99% plateau is the partial agonist.'}],
 teach:'An inverse agonist has the highest affinity for receptors in the inactive state and keeps them inactive; if it binds a receptor that is active, its negative efficacy shuts that receptor off. It lowers the dose–response curve all the way to 0%. Like every other orthosteric agonist class in this course, it is reversible.',
 quote:'Binds and stabilize the receptor in an inactive state ↑ Affinity. Evoke a change in the receptor - Efficacy.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~4–~12; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Some antagonists show inverse agonist activity: they reduce receptor activity below the basal level observed in the absence of any agonist.'}]},

{id:'L04-011', fg:'inverse', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'apply',
 concept:'inverse-agonist-needs-raised-baseline', tags:[], source:'both',
 stem:'An inverse agonist is given in increasing doses to a system in which nearly all receptors are inactive (baseline 0%). What does its dose–response curve look like?',
 options:[
  {t:'A flat line at 0%', correct:true, why:'The receptors are already inactive, which is what the inverse agonist wants; there is nothing to bring down.'},
  {t:'A curve falling from 0% to below 0%', correct:false, why:'Zero is the floor; a response cannot go lower than no effect.'},
  {t:'A curve rising to 100%', correct:false, why:'Rising to 100% is the full agonist; the inverse agonist has negative efficacy.'},
  {t:'A curve falling from 100% to 0%', correct:false, why:'That is the inverse agonist’s curve only when the baseline has been raised, for example in a cell line whose receptors are naturally active.'}],
 teach:'To see what an inverse agonist does, the baseline must be raised: the drug must be put into a system whose receptors are active by themselves (for example a cancer cell line in which 100% of the receptors are active). Then the curve goes from the baseline down to 0%. At a baseline of 0% every dose gives a straight line at 0%.',
 quote:'in order for us to see what an inverse actually does, we need to raise the baseline. We need to put that drug in a system that receptors are naturally active by themselves.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~9–~11; transcript 9/28'},

{id:'L04-012', fg:'inverse', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'figure', multi:true,
 concept:'fa-plus-inverse-agonist', tags:['histamine','loratadine'], source:'both',
 stem:'Histamine (full agonist) dose–response curves are built in a system with 50% of receptors active, first alone and then after increasing pretreatment doses of loratadine (Claritin), an inverse agonist. Which changes appear in histamine’s curve? Select all that apply.',
 options:[
  {t:'Baseline decreases', correct:true, why:'Each loratadine dose shuts off more of the receptors that were active on their own, lowering the starting point toward 0%.'},
  {t:'Shift to the right', correct:true, why:'Histamine must reach a higher concentration to outcompete loratadine, so it appears less potent.'},
  {t:'No change to Emax', correct:true, why:'Loratadine is reversible; with enough histamine the inverse agonist is outcompeted and the maximal response is reached.'},
  {t:'Shift to the left', correct:false, why:'A left shift means the second drug helped the agonist; loratadine competes against histamine.'},
  {t:'Emax decreases', correct:false, why:'Only an irreversible antagonist or an allosteric antagonist affecting efficacy lowers the Emax.'}],
 teach:'Take-home message for a full agonist in the presence of an inverse agonist: apparent affinity of the agonist decreases (shift to the right, appears less potent), basal activity of the receptors is reduced (baseline goes down, eventually to 0%), and there is no effect on Emax because the inverse agonist is reversible and can always be outcompeted.',
 quote:'So, take home message over here, it’s gonna bring the baseline down to 0, and it’s gonna shift to the right with no change to the Emax, right?',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~13–~22; transcript 9/28',
 note:'Slide ~22 says "No Effect on Emax against a high efficacy agonist"; in class the rule was stated without the qualifier: histamine, a full agonist, always gets back to Emax because loratadine is reversible. For the exam, use the class rule: reversible drugs never change the Emax of a full agonist.'},

{id:'L04-013', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'recall',
 concept:'fa-plus-inverse-emax-why', tags:['histamine','loratadine'], source:'both',
 stem:'In the presence of loratadine, histamine still reaches its maximal response if enough histamine is released. Which property of loratadine makes this possible?',
 options:[
  {t:'It is reversible', correct:true, why:'Loratadine binds and comes off, so whichever drug has the higher concentration wins the receptors; enough histamine outcompetes it.'},
  {t:'It has positive efficacy', correct:false, why:'Loratadine has negative efficacy; efficacy is not what lets histamine reach Emax.'},
  {t:'It binds an allosteric site', correct:false, why:'Loratadine competes for the same orthosteric pocket as histamine.'},
  {t:'It forms covalent bonds', correct:false, why:'Covalent binding would make it irreversible and would lower the Emax instead.'}],
 teach:'Any drug that is reversible, competitive and surmountable can be outcompeted: the agonist only has to be present at a higher concentration than the inverse agonist. That is why the inverse agonist changes potency (shift right) and baseline but never the ability of the full agonist to reach Emax. A higher loratadine dose simply requires more histamine to outcompete it.',
 quote:'They are reversible. As long as I can outcompete them because they’re going to bind and they’re going to come off, whoever has the highest concentration is going to occupy the most receptors to it.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~14, ~21; transcript 9/28'},

{id:'L04-014', fg:'classes', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'tell',
 concept:'inverse-vs-competitive-need-baseline', tags:[], source:'both',
 stem:'A full agonist’s curve is built with the baseline at 0%, then rebuilt after pretreatment with drug B. B shifts the curve to the right with no change to the baseline or the Emax. Which classification of B cannot be ruled out from this figure alone?',
 options:[
  {t:'Inverse agonist or competitive antagonist', correct:true, why:'At a baseline of 0% an inverse agonist has nothing to lower, so it looks exactly like a neutral competitive antagonist; a raised baseline is needed to tell them apart.'},
  {t:'Full agonist or allosteric agonist', correct:false, why:'Both would help the agonist and shift the curve to the left.'},
  {t:'Partial agonist or full agonist', correct:false, why:'A partial agonist has positive efficacy and would change the baseline; a full agonist shifts left.'},
  {t:'Irreversible antagonist or allosteric antagonist affecting efficacy', correct:false, why:'Both lower the Emax, which is unchanged here.'}],
 teach:'The system must have receptors in the active state (R = R*) to distinguish a full agonist plus inverse agonist from a full agonist plus competitive antagonist. With the baseline already at 0% both give a right shift with no change in baseline or Emax. Antihistamines were classed as antagonists until cell lines with naturally active receptors showed that they shut activity down.',
 quote:'if I give you that figure in the right, you can’t differentiate between a competitive and an inverse because you’re at 0 and there’s no change. I have to give you something different for you to see a change to occur.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~15, ~22; transcript 9/28'},

{id:'L04-015', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'recall',
 concept:'constitutive-activity-inverse', tags:['loratadine'], source:'both',
 stem:'Which receptors are more sensitive to inverse agonists?',
 options:[
  {t:'Receptors with constitutive activity', correct:true, why:'Receptors that are active on their own give the inverse agonist something to shut down; antihistamines such as loratadine and cetirizine act this way.'},
  {t:'Receptors held entirely in the inactive state', correct:false, why:'With every receptor inactive an inverse agonist produces a flat line at 0%.'},
  {t:'Receptors bound by an irreversible antagonist', correct:false, why:'Covalently blocked receptors are not available to any other drug.'},
  {t:'Receptors with no orthosteric site', correct:false, why:'Inverse agonists in this course are orthosteric and compete for the binding pocket.'}],
 teach:'Receptors that have constitutive activity (active by themselves, without any drug, hormone or neurotransmitter) are more sensitive to inverse agonists. The antihistamines cetirizine and loratadine are the classic inverse agonists; histamine, opioid, cannabinoid, dopamine, bradykinin and adenosine receptors are listed as showing this. Loratadine is the one inverse agonist to know on the drug list.',
 quote:'Receptors that have constitutive activity are more sensitive to inverse agonists.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~23; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Inverse agonist activity means the drug reduces receptor activity below the basal level seen with no agonist present at all.'}]},

{id:'L04-016', fg:'classes', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'figure',
 concept:'five-curve-e-loratadine', tags:['poll','loratadine'], source:'both',
 stem:'Five dose–response curves (A–E) of five different drugs are drawn in a system with an elevated baseline. Curve E starts at the baseline and falls to 0% as the dose increases. Curve E most likely represents the curve of which drug?',
 options:[
  {t:'Loratadine', correct:true, why:'A curve that brings the baseline to 0% is an inverse agonist, and loratadine is the inverse agonist on the drug list.'},
  {t:'Norepinephrine', correct:false, why:'Norepinephrine is a full agonist; its curve rises to 100%.'},
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist; its curve rises to a plateau below 100%.'},
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist; its curve rises to 100%.'}],
 teach:'Two steps: first classify curve E (it lowers the baseline to zero, so it is an inverse agonist), then find the drug on the list that belongs to that class (loratadine, an antihistamine). Knowing the classifications without knowing the drugs, or the drugs without the classifications, leaves the question unanswerable.',
 quote:'Because it’s bringing the baseline to zero. The next step is which of these drugs would fall into the category of being an inverse agonist.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~24; transcript 9/28'},

{id:'L04-017', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'recall',
 concept:'allosteric-two-things', tags:[], source:'both',
 stem:'What are the two things to know about an allosteric agonist?',
 options:[
  {t:'Two drugs bound at once; affects affinity or efficacy or both', correct:true, why:'It binds a different site, so the agonist can be bound at the same time, and it changes the pocket in a way that alters affinity, efficacy or both.'},
  {t:'Competes for the orthosteric pocket; has positive efficacy of its own', correct:false, why:'An allosteric drug binds someplace else and does not compete for the pocket.'},
  {t:'Forms covalent bonds; lowers the receptor pool', correct:false, why:'Covalent, pool-lowering binding is the irreversible antagonist; all allosterics in this course are reversible.'},
  {t:'Binds only inactive receptors; has negative efficacy', correct:false, why:'That describes the inverse agonist.'}],
 teach:'Allosteric drugs are the exception to one-or-the-other binding: two drugs can be bound to the receptor at the same time. The allosteric agonist binds someplace else in the receptor and changes the orthosteric pocket so the agonist binds more easily, increasing its affinity, its efficacy or both. For this course all allosterics are reversible.',
 quote:'Allosteric: 2 Things you should know - Two drugs bound at the same time - Affinity or Efficacy or Both.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~25–~28; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Allosteric modulators bind a site on the receptor separate from the orthosteric site bound by the agonist, so they modify receptor activity without blocking agonist binding.'}]},

{id:'L04-018', fg:'potency', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure',
 concept:'allosteric-agonist-affinity-only', tags:['poll'], source:'both',
 stem:'Dose–response curve B is a full agonist alone. Curve A lies to the left of B with the same maximum, D lies to the right with the same maximum, and C and E have a lower maximum. Which curve best represents agonist B in the presence of an allosteric agonist that affects only the affinity?',
 options:[
  {t:'A', correct:true, why:'An allosteric agonist helps, so the curve moves left; affinity-only means the maximal response is untouched.'},
  {t:'B', correct:false, why:'B is the point of reference; an allosteric agonist changes the agonist’s curve.'},
  {t:'C', correct:false, why:'A changed maximum means efficacy was affected, which the stem rules out.'},
  {t:'D', correct:false, why:'A right shift with the same maximum is an allosteric antagonist affecting affinity.'},
  {t:'E', correct:false, why:'A changed maximum means efficacy was affected, which the stem rules out.'}],
 teach:'An allosteric agonist that affects only affinity shifts the agonist’s curve to the left (more potent) with no change to the efficacy. Curves whose maximum changed (C, E) involve efficacy; a curve to the right (D) means the agonist was made less potent, which is an allosteric antagonist affecting affinity.',
 quote:'Help, which means you’re gonna make the drug more potent, right? And it because it only affects affinity, you’re not affecting the ability to produce its effect, is moving to the left.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~26, ~42; transcript 9/28'},

{id:'L04-019', fg:'efficacy', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure',
 concept:'allosteric-agonist-efficacy-only', tags:[], source:'both',
 stem:'Drug A alone plateaus at 60% (a partial agonist). An allosteric agonist that affects only the efficacy of drug A is added. How does A’s curve change?',
 options:[
  {t:'Rises to a higher maximum with no shift left or right', correct:true, why:'Efficacy is read on the y-axis: the partial agonist now behaves like a full agonist, while its EC50 position is unchanged.'},
  {t:'Shifts left with the same 60% maximum', correct:false, why:'A pure left shift is an affinity effect, not an efficacy effect.'},
  {t:'Shifts right with a lower maximum', correct:false, why:'A right shift plus lower maximum is an allosteric antagonist affecting both affinity and efficacy.'},
  {t:'Shifts left and also rises to a higher maximum than before', correct:false, why:'Both changes together mean affinity and efficacy were affected; the stem says efficacy only.'}],
 teach:'An allosteric agonist affecting efficacy only does not move the curve left or right; it moves it up, so a partial agonist can be converted into a full agonist. Affecting affinity only shifts the curve left. Affecting both shifts left and raises the maximum. A full agonist already at 100% cannot show an efficacy effect, so only the affinity shift is visible.',
 quote:'I have that drug in the presence of an allosteric agonist that affects efficacy only now it’s not moving left or right, it’s moving what up ... It went from being a partial agonist to a full agonist, right?',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~27–~29; transcript 9/28'},

{id:'L04-020', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure', multi:true,
 concept:'allosteric-characteristics', tags:[], source:'both',
 stem:'A full agonist’s curve is rebuilt after each of several increasing doses of an allosteric agonist. Which features are seen? Select all that apply.',
 options:[
  {t:'Shifts to the left', correct:true, why:'The allosteric agonist increases the agonist’s affinity, so it appears more potent.'},
  {t:'Shifts of unequal size', correct:true, why:'Binding at the allosteric site is non-competitive and does not depend on the agonist, so each dose occupies an unpredictable fraction; the shifts are asymmetrical.'},
  {t:'Shifts stop growing at high doses', correct:true, why:'Once all allosteric sites are occupied the drug has done all it can; the effect is saturable.'},
  {t:'Emax rises above 100%', correct:false, why:'A full agonist is already at 100%, so no efficacy effect can be seen.'},
  {t:'Shifts of equal size', correct:false, why:'Equal (symmetrical) shifts belong to orthosteric competition, for example a competitive antagonist.'}],
 teach:'Four characteristics of a full agonist with multiple doses of an allosteric agonist: affinity affected (yes, shift left), efficacy affected (no, already at 100%), symmetrical shifts (no, the shifts differ in size), saturability (yes, after a certain number of shifts there is a limit to how much the allosteric drug can affect the system). Asymmetrical, saturable shifts are how an allosteric drug is recognized.',
 quote:'I can keep giving more and more of my allosteric, and he can’t go more to the left. He has maxed out all that he can do to the system.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~30–~34; transcript 9/28'},

{id:'L04-021', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'antag', skill:'tell',
 concept:'chemical-vs-physiological-antagonism', tags:[], source:'both',
 stem:'Acetylcholine at muscarinic receptors lowers heart rate while epinephrine at β1 receptors raises it. What kind of antagonism is this?',
 options:[
  {t:'Physiological', correct:true, why:'Two agonists acting independently at different receptors in the same organ produce opposing effects.'},
  {t:'Chemical', correct:false, why:'Chemical antagonism is a direct chemical interaction between the agonist and the antagonist, as with chelating agents such as dimercaprol.'},
  {t:'Competitive (orthosteric)', correct:false, why:'The two drugs bind different receptors; they do not compete for the same pocket.'},
  {t:'Allosteric', correct:false, why:'Neither drug binds another site on the other’s receptor.'}],
 teach:'Chemical antagonism: a direct chemical interaction between the agonist and the antagonist, for example chelating agents such as dimercaprol used to treat gold, mercury or arsenic poisoning. Physiological antagonism: two agonists acting independently of each other on different receptors and producing opposing effects, for example acetylcholine and epinephrine in the heart. The pharmacological antagonists (competitive, irreversible, allosteric) are the focus.',
 quote:'Physiological: Two agonist acting independent of each other producing opposing effects. Ach and Epi in the heart.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~35; transcript 9/28'},

{id:'L04-022', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'antag', skill:'recall',
 concept:'antagonist-synonyms', tags:[], source:'both',
 stem:'Which term is another name for a competitive antagonist?',
 options:[
  {t:'Surmountable', correct:true, why:'Competitive, reversible and surmountable are different names for the same drug: it binds and comes off, and the agonist can outcompete it.'},
  {t:'Insurmountable', correct:false, why:'Insurmountable names the irreversible antagonist, which cannot be overcome by more agonist.'},
  {t:'Non-equilibrium', correct:false, why:'Non-equilibrium names the irreversible antagonist; there is no balance between binding and unbinding.'},
  {t:'Non-competitive', correct:false, why:'Non-competitive covers the irreversible antagonist (binds and does not come off) and the allosteric antagonist (binds someplace else).'}],
 teach:'Pharmacological antagonisms: competitive (orthosteric) = surmountable = reversible, the most common in clinical practice, agonist and antagonist competing for the same receptor site; nonequilibrium-competitive (orthosteric) = irreversible = insurmountable, cannot be overcome by increasing the agonist concentration; allosteric antagonist = non-competitive, reduces the agonist’s affinity and/or efficacy from another site.',
 quote:'One is competitive antagonist, also known as reversible antagonists, also known as surmountable antagonists, different names for the same drug. They bind and they come off.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~36; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Sufficiently high concentrations of agonist can surmount the effect of a given concentration of a competitive antagonist, whereas agonists cannot surmount a noncompetitive antagonist irrespective of their concentration.'}]},

{id:'L04-023', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'antag', skill:'recall',
 concept:'pam-nam', tags:[], source:'both',
 stem:'In the literature, what is a negative allosteric modulator (NAM)?',
 options:[
  {t:'An allosteric antagonist', correct:true, why:'A NAM binds another site and reduces the agonist’s affinity and/or efficacy.'},
  {t:'An allosteric agonist', correct:false, why:'The allosteric agonist is the positive allosteric modulator (PAM).'},
  {t:'An inverse agonist', correct:false, why:'An inverse agonist is orthosteric with negative efficacy, not an allosteric ligand.'},
  {t:'An irreversible antagonist', correct:false, why:'The irreversible antagonist binds the orthosteric pocket covalently.'}],
 teach:'Allosteric ligands: the allosteric agonist is a positive allosteric modulator (PAM); the allosteric antagonist is a negative allosteric modulator (NAM). Whatever the positive one does (raises affinity, efficacy or both), the negative one does the opposite.',
 quote:'we can also call allosteric agonists PAMs, positive allosteric modulators, you see that in the literature, or NAMs, negative allosteric modulators, but the key thing is if you know what the positive does, the negative is the opposite.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~37; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Negative allosteric modulators bind an allosteric site to reduce receptor activity; positive allosteric modulators bind an allosteric site to increase it.'}]},

{id:'L04-024', fg:'efficacy', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure',
 concept:'allosteric-antagonist-effects', tags:['poll'], source:'both',
 stem:'Dose–response curve D is a full agonist alone. Curve E lies to the right of D with a lower maximum; curve C lies to the left of D with a lower maximum; A and B lie to the left with the same maximum. Which curve best represents agonist D in the presence of an allosteric antagonist that affects both the affinity and the efficacy of D?',
 options:[
  {t:'E', correct:true, why:'Lower affinity shifts the curve right and lower efficacy brings the maximum down.'},
  {t:'C', correct:false, why:'C moves left (affinity improved) but drops the maximum (efficacy reduced); no drug does that.'},
  {t:'A', correct:false, why:'A left shift means the agonist was helped; an antagonist makes its life harder.'},
  {t:'B', correct:false, why:'A left shift with the same maximum would be an allosteric agonist affecting affinity.'},
  {t:'D', correct:false, why:'D is the point of reference; the allosteric antagonist changes the curve.'}],
 teach:'An allosteric antagonist is the opposite of the allosteric agonist. Affinity only: shift to the right, Emax still reached at higher doses. Efficacy only: no shift, the full agonist behaves like a partial agonist. Both: shift right and a lower maximum. The shifts are asymmetrical and the drug is non-competitive (it binds someplace else). A curve that moves left while losing its maximum has no matching drug.',
 quote:'it’s affecting the affinity, so it’s gonna shift to the right and it’s affecting the efficacy, so it’s gonna bring it down. So E would be the best answer.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~38–~42; transcript 9/28'},

{id:'L04-025', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'tell',
 concept:'noncompetitive-two-reasons', tags:[], source:'both',
 stem:'Irreversible antagonists and allosteric antagonists are both called non-competitive. What makes each one non-competitive?',
 options:[
  {t:'Irreversible: binds and does not come off; allosteric: binds a different site', correct:true, why:'No competition is possible with a drug that never leaves the pocket, or with a drug that never enters it.'},
  {t:'Both bind the orthosteric pocket covalently', correct:false, why:'Only the irreversible antagonist forms covalent bonds; allosterics are reversible in this course.'},
  {t:'Both have negative efficacy', correct:false, why:'Negative efficacy is the inverse agonist; these antagonists have no pharmacological efficacy of their own.'},
  {t:'Irreversible: binds a different site; allosteric: binds and does not come off', correct:false, why:'The reasons are reversed.'}],
 teach:'Two different reasons give the same label. The irreversible antagonist forms covalent bonds in the orthosteric pocket and never comes off, so there is no equilibrium or competition. The allosteric antagonist binds reversibly at another site in the receptor, so it is not competing for the pocket at all; the agonist cannot overcome it and the shifts it causes are asymmetrical.',
 quote:'One because one binds and doesn’t come off, the other one because it binds someplace else. There’s no competition with it along the way.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~36, ~41; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Once a receptor is bound by a noncompetitive antagonist, agonists cannot surmount the inhibition; some noncompetitive antagonists bind irreversibly, others bind reversibly at a separate allosteric site.'}]},

{id:'L04-026', fg:'two-state', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'apply',
 concept:'competitive-antagonist-neutral-alone', tags:[], source:'both',
 stem:'A competitive antagonist alone is given in increasing doses to a system in which 50% of the receptors are active. What does its own dose–response curve show?',
 options:[
  {t:'A flat line at 50%', correct:true, why:'The antagonist has equal affinity for active and inactive receptors and no efficacy, so it leaves the balance where it found it.'},
  {t:'A curve falling from 50% to 0%', correct:false, why:'Bringing active receptors down to zero requires negative efficacy, which is the inverse agonist.'},
  {t:'A curve rising from 50% to 100%', correct:false, why:'Rising to 100% requires positive efficacy, which the antagonist lacks.'},
  {t:'A flat line at 0%', correct:false, why:'The antagonist does not change the baseline; the system stays at the 50% it started with.'}],
 teach:'A competitive antagonist is neutral in the two-state model: it does not care whether the receptor is active or inactive, has equal affinity for both states (R = affinity = R*), and does not evoke a change in the receptor. It has affinity but no pharmacological efficacy. Alone, it keeps the baseline wherever it is: 0 stays 0, 50 stays 50, 100 stays 100.',
 quote:'they don’t care what the receptor is, active or inactive, they hang out with both types. They don’t discriminate as such, they don’t change the balance of the receptor activity.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~43–~44; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Receptor antagonists bind to receptors but do not activate them; their primary action is to reduce the effects of agonists that normally activate the receptor.'}]},

{id:'L04-027', fg:'competitive', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'figure', multi:true,
 concept:'competitive-antagonist-shift', tags:[], source:'both',
 stem:'Drug A is a full agonist and drug B is a competitive antagonist at the same receptor. A’s curve is rebuilt after increasing doses of B. Which statements describe the result? Select all that apply.',
 options:[
  {t:'Shift to the right', correct:true, why:'A must reach a higher concentration to outcompete B for the receptors, so its ED50 rises and it appears less potent.'},
  {t:'No change to the baseline', correct:true, why:'B is neutral: it has no efficacy, so it neither raises nor lowers the starting point.'},
  {t:'No change to Emax', correct:true, why:'B is reversible, so with enough A the antagonist is outcompeted and the maximal response is reached.'},
  {t:'Symmetrical shifts', correct:true, why:'Each tenfold increase in B needs a tenfold increase in A; the shifts are the same size.'},
  {t:'Emax decreases', correct:false, why:'A lower Emax is the mark of an irreversible antagonist or an allosteric antagonist affecting efficacy.'},
  {t:'Baseline decreases', correct:false, why:'A falling baseline is the inverse agonist; a competitive antagonist has no efficacy.'}],
 teach:'Full agonist plus competitive antagonist: shift to the right (A can outcompete B, but needs a higher dose), no change to the baseline (B has no efficacy), no change to Emax (B is reversible), and symmetrical shifts (one or the other occupies the pocket, and a tenfold increase in antagonist needs a tenfold increase in agonist). The shifts can continue toward infinity.',
 quote:'Very symmetrical shifts with no change to the baseline, no change to the Emax, just shifting to the right.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~45–~50; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'A competitive antagonist increases the agonist concentration required for a given response, shifting the agonist curve to the right, while the Emax for the agonist stays the same at any fixed antagonist concentration.'}]},

{id:'L04-028', fg:'competitive', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'calc',
 concept:'competitive-tenfold-rule', tags:[], source:'both',
 stem:'A full agonist’s curve has been shifted to the right by one dose of a competitive antagonist. The antagonist dose is then increased 10 times. By how much must the agonist dose increase to outcompete the antagonist again?',
 options:[
  {t:'10 times', correct:true, why:'By the law of mass action, whoever has the greater concentration occupies more receptors; matching a tenfold antagonist increase takes a tenfold agonist increase, giving symmetrical shifts.'},
  {t:'2 times', correct:false, why:'A twofold increase would leave the antagonist with the higher concentration.'},
  {t:'100 times', correct:false, why:'A hundredfold increase would be more than the competition requires; the shifts are proportional.'},
  {t:'It cannot outcompete the antagonist', correct:false, why:'A competitive antagonist is reversible, so the agonist can always outcompete it with enough drug.'}],
 teach:'Competition for one orthosteric pocket follows the law of mass action: the drug with the greater concentration occupies the most receptors. If the antagonist dose is increased tenfold, the agonist dose must be increased tenfold to outcompete it, so successive shifts are symmetrical. A competitive antagonist raises the agonist’s ED50, so the agonist appears less potent.',
 quote:'if I increase the dose by tenfold, I have to increase the dose of the other by tenfold to outcompete them.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~47–~49; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'The agonist concentration needed for a given effect in the presence of a competitive antagonist is greater than without it, and the ratio of the two concentrations depends on the antagonist concentration.'}]},

{id:'L04-029', fg:'irreversible', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'recall',
 concept:'irreversible-antagonist-mechanism', tags:[], source:'both',
 stem:'Why does an irreversible antagonist lower the maximal response (Emax) of a full agonist?',
 options:[
  {t:'It removes receptors from the available pool permanently', correct:true, why:'Covalent bonds lock the antagonist on, so the receptors it occupies are gone; once too few remain, the agonist cannot reach Emax no matter the dose.'},
  {t:'It has negative efficacy', correct:false, why:'The irreversible antagonist is neutral, with no pharmacological efficacy; it does not change receptor state.'},
  {t:'It changes the shape of the orthosteric pocket from another site', correct:false, why:'Changing the pocket from another site is the allosteric antagonist.'},
  {t:'It has the lowest affinity of the drug classes', correct:false, why:'It has the greatest affinity (smallest Kd) of any class.'}],
 teach:'An irreversible antagonist forms covalent bonds that cannot be reversed under normal metabolic function, so it has the greatest affinity (smallest Kd) and once bound it does not come off. That lowers the number of receptors available. With fewer receptors the agonist cannot outcompete it, so it cannot reach the maximal effect, and at high enough antagonist doses the response can be abolished completely.',
 quote:'There’s a lowering of my receptor pool availability because some of them are going to be permanently bound to the irreversible antagonist. And because I don’t have enough receptors available and I can’t outcompete it, I can put all the drug I want, I cannot outcompete those guys.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~51–~53; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'After an irreversible antagonist occupies some proportion of receptors, the number of unoccupied receptors may be too low for the agonist, even at high concentrations, to produce the previous maximal response.'}]},

{id:'L04-030', fg:'irreversible', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'figure',
 concept:'irreversible-antagonist-curve', tags:[], source:'both',
 stem:'A full agonist’s curve is rebuilt after increasing doses of an irreversible antagonist. Which set of changes is seen?',
 options:[
  {t:'Shift right, Emax falls, baseline unchanged', correct:true, why:'Fewer receptors remain, so a higher agonist dose is needed and the maximum drops, eventually to zero; the neutral antagonist does not move the baseline.'},
  {t:'Shift right, Emax unchanged, baseline unchanged', correct:false, why:'An unchanged Emax is the competitive antagonist; an irreversible one is not outcompeted.'},
  {t:'Shift right, Emax unchanged, baseline falls', correct:false, why:'A falling baseline belongs to the inverse agonist.'},
  {t:'Shift left, Emax unchanged, baseline rises', correct:false, why:'That is a second full agonist helping the first.'}],
 teach:'Take-home message for the irreversible antagonist: no change to the baseline (it is neutral, no efficacy), shift to the right (competition for the same pocket, symmetrical), and a decrease in Emax that can go all the way to 0 and abolish the curve completely. The agonist appears both less potent (higher ED50) and less efficacious.',
 quote:'IrA = ↑ED50 FA = Appears less Potent. ↓ Emax FA = Appears less efficacious.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~53–~54; transcript 9/28',
 note:'Katzung states an irreversible antagonist reduces the maximal effect "although it may not change its EC50"; the slides and class say the curve shifts to the right with a higher ED50 as well as a lower Emax. The exam is written from the lecture: shift right and reduced Emax.',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'An irreversible antagonist reduces the maximal effect the agonist can achieve, and high agonist concentrations cannot overcome it.'}]},

{id:'L04-031', fg:'classes', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'tell', multi:true,
 concept:'emax-lowering-classes', tags:[], source:'transcript',
 stem:'Which drug classes can lower the Emax of a full agonist? Select all that apply.',
 options:[
  {t:'Irreversible antagonist', correct:true, why:'It permanently removes receptors, so the agonist cannot outcompete it to reach the maximum.'},
  {t:'Allosteric antagonist that affects efficacy', correct:true, why:'It changes the pocket so the agonist signals less, lowering the maximum without competition.'},
  {t:'Competitive antagonist', correct:false, why:'Reversible, so the agonist always outcompetes it; Emax is unchanged.'},
  {t:'Inverse agonist', correct:false, why:'Reversible, so the agonist always outcompetes it; it lowers the baseline, not the Emax.'},
  {t:'Allosteric agonist', correct:false, why:'It helps the agonist; it raises efficacy or affinity rather than lowering the maximum.'}],
 teach:'Concrete exam rule: anything that lowers the Emax has to be either an irreversible antagonist or an allosteric antagonist that affects efficacy. Every other class is reversible and competitive, so the Emax is unchanged. The difference between the two: the allosteric antagonist saturates and cannot bring the response all the way down, while the irreversible antagonist can abolish the response completely.',
 quote:'If you see something that it lowers the Emax, you know that has to be either an irreversible antagonist or an allosteric antagonist that affects efficacy, right? Those are the only two that can affect the Emax.',
 cite:'transcript 9/28; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~39–~41, ~53–~54'},

{id:'L04-032', fg:'competitive', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'figure',
 concept:'dotted-line-drug-x-competitive', tags:['poll'], source:'both',
 stem:'The dotted line represents the dose–response curve of an agonist alone and the solid lines represent the curve of the agonist in the presence of increasing doses of drug "X." The solid lines are shifted to the right with no change in the baseline or the maximal response. Drug X is most likely:',
 options:[
  {t:'A competitive antagonist', correct:true, why:'Right shift with the baseline and the Emax unchanged is the competitive antagonist’s signature.'},
  {t:'A full agonist', correct:false, why:'A full agonist would help and move the curve to the left.'},
  {t:'A partial agonist', correct:false, why:'A partial agonist has efficacy and would change the baseline.'},
  {t:'An irreversible antagonist', correct:false, why:'An irreversible antagonist lowers the Emax; here the maximum is unchanged.'},
  {t:'An allosteric agonist', correct:false, why:'An allosteric agonist would help the agonist and shift it to the left.'}],
 teach:'Process of elimination: drugs that help the agonist (full agonist, allosteric agonist) move it left, so they are out. A partial agonist has efficacy and would affect the baseline. An irreversible antagonist would lower the Emax. What remains, a right shift with the baseline and Emax unchanged, is the competitive antagonist. With too few shifts an irreversible antagonist may look competitive at first.',
 quote:'Who can you eliminate right away? A full agonist because they’ll move you to the left or an allosteric agonist, right?',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~55; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'In the presence of a competitive antagonist, higher agonist concentrations are required to produce a given effect, so the agonist curve is shifted to the right and high agonist concentrations overcome the inhibition.'}]},

{id:'L04-033', fg:'competitive', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'apply',
 concept:'drug-x-metoprolol', tags:['poll','metoprolol'], source:'both',
 stem:'The dotted line represents the dose–response curve of norepinephrine alone and the solid lines represent the curve of norepinephrine in the presence of increasing doses of drug "X." The solid lines are shifted to the right with no change to the baseline or the maximal response. Drug X is most likely:',
 options:[
  {t:'Metoprolol', correct:true, why:'The figure shows a competitive, reversible, surmountable antagonist, and metoprolol is the β1 competitive antagonist on the drug list.'},
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist and would shift norepinephrine to the left.'},
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist and would change the baseline.'},
  {t:'Phenoxybenzamine', correct:false, why:'Phenoxybenzamine is the only irreversible antagonist on the list; it would lower the Emax.'},
  {t:'Diazepam', correct:false, why:'Diazepam is the allosteric agonist on the list and would help the agonist.'}],
 teach:'Same classes of drugs, just different drug names: first read the figure (competitive antagonist), then match it to the drug list. Epinephrine is a full agonist, albuterol the partial agonist, phenoxybenzamine the only irreversible antagonist on the list, diazepam the allosteric agonist, and metoprolol the competitive reversible surmountable antagonist.',
 quote:'So same classes of drugs. Just different drug names.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~55; transcript 9/28'},

{id:'L04-034', fg:'spare', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'apply',
 concept:'spare-receptors-irreversible', tags:[], source:'transcript',
 stem:'An agonist needs to occupy only 10% of a tissue’s receptors to produce its maximal response. An irreversible antagonist that blocks 75% of the receptors is given. Can the agonist still produce its maximal response?',
 options:[
  {t:'Yes, at a higher agonist dose', correct:true, why:'25% of the receptors remain, more than the 10% needed, so the maximum is reached once enough agonist is given to occupy them.'},
  {t:'No, the Emax falls to 25%', correct:false, why:'Emax only falls once the receptors available drop below the fraction the agonist needs.'},
  {t:'No, the response is abolished', correct:false, why:'Abolishing the response takes blockade of essentially all the receptors.'},
  {t:'Yes, at the same agonist dose', correct:false, why:'With fewer receptors available the agonist appears to have less affinity and a higher dose is required.'}],
 teach:'Agonists do not have to occupy 100% of the receptors to produce a response; the rest are spare receptors. If the agonist needs 10% and the irreversible antagonist leaves 25% or 15% available, the maximum is still reached with more agonist (the curve shifts right); once fewer than 10% remain the Emax falls, all the way to zero if all receptors are blocked.',
 quote:'Our agonists don’t have to occupy 100% of the receptors to produce a response. They only have to occupy a certain percentage of those receptors to do so.',
 cite:'transcript 9/28; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~54, ~56',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'Receptors are spare when a maximal response can be produced at an agonist concentration that does not occupy all available receptors. With spare receptors, a lower dose of irreversible antagonist can leave enough receptors for the maximal response, though a higher agonist concentration is required.'}]},

{id:'L04-035', fg:'classes', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'tell', multi:true,
 concept:'helps-or-hinders-direction', tags:[], source:'transcript',
 stem:'A full agonist’s dose–response curve is rebuilt in the presence of a second drug. Which second drugs shift the agonist’s curve to the left? Select all that apply.',
 options:[
  {t:'Another full agonist', correct:true, why:'It activates receptors on the agonist’s behalf, so less agonist is needed.'},
  {t:'An allosteric agonist that affects affinity', correct:true, why:'It makes the pocket more accessible, so the agonist binds more easily and appears more potent.'},
  {t:'A competitive antagonist', correct:false, why:'It competes for the pocket, so more agonist is needed: shift right.'},
  {t:'An inverse agonist', correct:false, why:'It competes and pulls receptors inactive, so more agonist is needed: shift right.'},
  {t:'An irreversible antagonist', correct:false, why:'It removes receptors, so more agonist is needed and the maximum falls.'}],
 teach:'Before looking at any figure, ask whether the second drug helps the agonist or makes its life more difficult. Helpers (another full agonist, an allosteric agonist) make the agonist appear more potent: shift to the left. Drugs that compete or block (competitive antagonist, inverse agonist, irreversible antagonist, allosteric antagonist affecting affinity) make it appear less potent: shift to the right. That one question eliminates most of the options.',
 quote:'would you assume that this other drug is gonna help or is gonna make the life more difficult for your agonist? And that should allow you to eliminate a lot of the answers.',
 cite:'transcript 9/28; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~3, ~22, ~42, ~50'}
);
