TOPICS.push({id:"L07", name:"Day 7: signal transduction and the autonomic nervous system", prof:"Gottlieb", lecture:"L07",
  cite:"Day 7 (9/30 second half, 10/1) — Autonomic Nervous System.pdf",
  subs:[
    {id:"gprot", name:"G proteins and the receptor quick table", cite:"slides 3–4"},
    {id:"messenger", name:"Signal amplifiers and second messengers", cite:"slides 6–9"},
    {id:"organize", name:"Autonomic vs somatic; receptors and where they are", cite:"slides 10–13"},
    {id:"neurotrans", name:"Five steps of neurotransmission; drug targets", cite:"slides 14–20"},
    {id:"pns", name:"Parasympathetic system and DUMBBELSS", cite:"slides 21–27"},
    {id:"sns", name:"Sympathetic system, its exceptions and organ effects", cite:"slides 28–35"},
    {id:"innerv", name:"Dual and single innervation; the caveats", cite:"slides 36–47"},
    {id:"baro", name:"Baroreceptors and short-term control of blood pressure", cite:"slides 48–53"}
  ]});
QUESTIONS.push(
/* ---------------- G proteins and the quick table (slides 3–4) ---------------- */
{id:"L07-001", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"gprot", skill:"apply",
 concept:"alpha1-gq-plc-ip3", dupOf:"PE2-029", tags:["poll"], source:"both",
 stem:"Norepinephrine, an agonist, activates an α1 adrenergic receptor. Which of the following is most likely to occur in that cell?",
 options:[
  {t:"Gq activates PLC; IP3 and Ca++ rise", correct:true, why:"α1 is coupled to Gq, which activates phospholipase C (PLC) and raises inositol triphosphate (IP3) and calcium; in an artery that calcium contracts the smooth muscle (vasoconstriction)."},
  {t:"Gs activates AC; cAMP rises", correct:false, why:"Gs, adenylate cyclase (AC) and a rise in cyclic AMP (cAMP) are the β receptor pathway; α1 is on the Gq row and works through PLC, not AC."},
  {t:"Gi inhibits AC; cAMP falls", correct:false, why:"Gi inhibits adenylate cyclase and lowers cAMP; that is the α2 and M2 pathway. α1 is on the Gq row, so it raises IP3 and Ca++ instead."},
  {t:"An ion channel opens and Na+ enters the cell", correct:false, why:"Na+ entry through a channel that the ligand opens is how a nicotinic receptor works; α1 is a G protein–coupled receptor that signals through Gq."}],
 teach:"On the quick table, α1 sits on the Gq row: effector phospholipase C (PLC), second messenger inositol triphosphate (IP3), and a rise in Ca++. A rise in calcium is, as a general rule, a signal for something positive: contraction, neurotransmitter release, excitation. Knowing the receptor and its G protein lets you predict the effect without memorizing it.",
 quote:"So, what is alpha 1 Kappa 2 on your quick stable? I would say GQ. If it's GQ, who is activating PLC and increasing IP3 and calcium, right?",
 note:"His spoken 9/30 wording of the bonus clicker question. The poll sheet words it as \"Activation of alpha 1 receptors in the arteries by an agonist will produce which of the following?\" and keys Activation of Gq=>activation of PLC=>vasoconstriction.",
 cite:"Autonomic Nervous System.pdf slide 4; transcript 9/30"},

{id:"L07-002", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"gprot", skill:"apply",
 concept:"beta1-gs-tachycardia", tags:["poll"], source:"both",
 stem:"An agonist activates β1 adrenergic receptors in the heart. Which of the following is most likely to occur?",
 options:[
  {t:"Bradycardia from a fall in cAMP", correct:false, why:"A fall in cyclic AMP (cAMP) and slowing of the heart is the M2 (Gi) result, not β1."},
  {t:"Tachycardia from a rise in cAMP", correct:true, why:"β1 is Gs; Gs activates adenylate cyclase, cAMP rises in the heart, and heart rate goes up."},
  {t:"Bradycardia from a rise in IP3", correct:false, why:"Inositol triphosphate (IP3) is the Gq messenger; β1 is Gs and works through adenylate cyclase and cAMP, and its effect in the heart is to speed it up."},
  {t:"No change; β1 is not innervated", correct:false, why:"β1 receptors in the heart are innervated (a sympathetic nerve releases norepinephrine onto them), and an agonist activates the receptor either way; β2 is the receptor without a nerve."}],
 teach:"All β receptors are coupled to Gs. In the heart, β1 activation turns on adenylate cyclase (AC), raises cAMP, and causes tachycardia and more contractile force. The opposite heart receptor is M2, coupled to Gi, which lowers cAMP and slows the heart.",
 quote:"So, if it's beta one receptors, which G protein is, GS GS is gonna be AC in camp, which is gonna cause heart rate to go up. So, in this case, it's gonna cause tachycardia by increasing the camp inside of the heart.",
 cite:"Autonomic Nervous System.pdf slide 4; transcript 9/30"},

{id:"L07-003", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"gprot", skill:"recall",
 concept:"gq-receptors", tags:[], source:"slide", multi:true,
 stem:"Which of the following receptors are coupled to Gq, so that activation increases inositol triphosphate (IP3) and Ca++? Select all that apply.",
 options:[
  {t:"M1", correct:true, why:"M1 (brain) is on the Gq row: PLC, IP3, ↑Ca++."},
  {t:"M2", correct:false, why:"M2 (heart) is Gi: it inhibits adenylate cyclase and lowers cAMP."},
  {t:"M3", correct:true, why:"M3 (everywhere else) is Gq: PLC, IP3, ↑Ca++."},
  {t:"α1", correct:true, why:"α1 is Gq: PLC, IP3, ↑Ca++."},
  {t:"α2", correct:false, why:"α2 is Gi: it lowers cAMP."},
  {t:"β2", correct:false, why:"β2 is Gs: it raises cAMP through adenylate cyclase."}],
 teach:"The quick table has three Gq receptors (M1, M3, α1), two Gi receptors (M2, α2) and the Gs receptors (β1, β2, β3). Gq works through phospholipase C (PLC) to raise IP3 and calcium; Gi and Gs both act on adenylate cyclase, Gi lowering cAMP and Gs raising it.",
 quote:"Q M1 PLC IP3 ↑Ca++ · I M2 AC cAMP↓ · Q M3 PLC IP3 ↑Ca++ · Q α1 PLC IP3 ↑Ca++ · I α2 AC cAMP↓ · S β1 AC cAMP↑ · S β2 AC cAMP↑ · S β3 AC cAMP↑",
 cite:"Autonomic Nervous System.pdf slide 4"},

{id:"L07-004", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"gprot", skill:"tell",
 concept:"m3-endothelium-no-vasodilation", tags:["nitric-oxide"], source:"both",
 stem:"M3 receptors are coupled to Gq and raise Ca++, a signal that usually causes smooth muscle to contract. Why does M3 activation in blood vessels cause vasodilation instead?",
 options:[
  {t:"M3 in vascular smooth muscle is coupled to Gi instead of Gq", correct:false, why:"M3 is Gq everywhere; the exception is where the receptor sits, not which G protein it uses."},
  {t:"M3 sits on endothelium; Ca++ drives NOS to make NO", correct:true, why:"The M3 receptor sits on the endothelium; the calcium rise activates nitric oxide synthase (NOS), and nitric oxide (NO) relaxes the smooth muscle."},
  {t:"Ca++ relaxes vascular smooth muscle directly", correct:false, why:"Calcium is a signal for contraction; the relaxation comes from nitric oxide, not from calcium acting on the muscle."},
  {t:"Acetylcholine blocks α1 receptors in vessels", correct:false, why:"Acetylcholine does not act on α1 receptors; the dilation is through M3, NOS and NO."}],
 teach:"This is the exception to the rule that Gq and a rise in Ca++ mean contraction. The M3 receptor in blood vessels is on the endothelial cells that line the smooth muscle, not on the smooth muscle itself. Gq raises Ca++ in the endothelium, which activates nitric oxide synthase (NOS); the nitric oxide (NO) gas then relaxes the neighboring smooth muscle, so the vessel dilates.",
 quote:"even though the M3 receptor, which is coupled to GQ and increased calcium. That's going to cause vasodilation, not vasoconstriction. And the reason being is that the M3 receptor is located on the endothelium cells around your, your smooth muscle",
 reading:[{src:"Katzung 16e, Ch. 6", sec:"Autonomic Receptors, Table 6–2", t:"Katzung lists M3 receptors in exocrine glands and in vessels, both in the smooth muscle and in the endothelium, with the same result of binding as M1: formation of IP3 and DAG and increased intracellular calcium. Its organ table lists activation of NO synthase as the parasympathetic (M3) effect on vascular endothelium."}],
 cite:"Autonomic Nervous System.pdf slide 4; transcript 9/30"},

{id:"L07-005", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"gprot", skill:"apply",
 concept:"m1-agonist-antagonist-brain", tags:[], source:"transcript",
 stem:"M1 receptors in the brain are coupled to Gq. What does an M1 antagonist most likely produce?",
 options:[
  {t:"Excitation and better memory", correct:false, why:"Excitation and better memory are what an M1 agonist produces through Gq and ↑Ca++."},
  {t:"Sedation and fatigue", correct:true, why:"Blocking the Gq-coupled M1 removes the excitatory signal, so the patient is sedated, sleepy and fatigued."},
  {t:"Tachycardia", correct:false, why:"Heart rate is set by M2 and β1 in the heart, not by M1 in the brain."},
  {t:"Bronchial constriction", correct:false, why:"Airway constriction is an M3 agonist effect, not an M1 antagonist effect."}],
 teach:"M1 is in the brain and is Gq: an agonist raises Ca++ and causes excitation and better memory, which is why patients with dementia or Alzheimer’s disease receive drugs that stimulate these receptors. An antagonist does the opposite: sedation, sleep, fatigue. Knowing the receptor, its G protein and the drug’s class predicts the effect.",
 quote:"if I have an agonist that is gonna activate the M1? I'm gonna get excited, I'm gonna remember better. As if I have an antagonist that blocks the name once, now I get sedated, I go to sleep, I get fatigued",
 cite:"transcript 9/30 (Autonomic Nervous System.pdf slide 4)"},

/* ---------------- Second messengers (slides 6–9) ---------------- */
{id:"L07-006", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"messenger", skill:"tell",
 concept:"amplifier-vs-second-messenger", tags:[], source:"both",
 stem:"Which of the following pairs are signal amplifiers (effector enzymes)?",
 options:[
  {t:"Cyclic AMP (cAMP) and inositol triphosphate", correct:false, why:"Cyclic AMP and inositol triphosphate (IP3) are second messengers: they are the products the amplifier enzymes make, and they carry the signal inside the cell."},
  {t:"Adenylate cyclase and phospholipase C", correct:true, why:"Adenylate cyclase (AC) and phospholipase C (PLC) are the effector enzymes: once the Gα subunit activates one, it makes many second-messenger molecules (cAMP or IP3), which amplifies the signal."},
  {t:"β1 adrenergic and M2 muscarinic receptors", correct:false, why:"β1 and M2 are receptors: they receive the signal (the drug or neurotransmitter) at the membrane and hand it to the G protein; they do not make second messengers."},
  {t:"The Gαs and Gαi subunits", correct:false, why:"Gα subunits are the transducers: they translate the receptor's signal and pass it to the amplifier enzyme, which is the step after them."}],
 teach:"The chain is: signal (the drug), receptor (the G protein–coupled receptor), transducer (Gαs, Gαi or Gαq), signal amplifier or effector system (adenylate cyclase or phospholipase C), and second messenger (cAMP or IP3), which carries the message through the cell. Each amplifier enzyme makes many second-messenger molecules, so the signal is amplified. He named this exact kind of question: which item is a second messenger, which is the effector, which is the transducer, which is the signal. For the exam, cAMP and IP3 are the two second messengers to know.",
 quote:"A signal amplifier is going to be our factor system such as AC or PLC. Those are the enzymes that are going to be making a camp or IP3 and carry on the signal inside.",
 cite:"Autonomic Nervous System.pdf slide 6; transcript 9/30"},

{id:"L07-007", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"messenger", skill:"recall",
 concept:"camp-regulation-pde", tags:[], source:"both",
 stem:"Intracellular cyclic AMP (cAMP) is made by adenylate cyclase. Which enzymes break it down, and are the target of caffeine and theophylline?",
 options:[
  {t:"Phosphodiesterases (PDE)", correct:true, why:"cAMP is made by adenylate cyclase and broken down by PDE; caffeine and theophylline inhibit PDE."},
  {t:"Phospholipase C (PLC)", correct:false, why:"PLC is the Gq effector that makes IP3; it does not break down cAMP."},
  {t:"Monoamine oxidase (MAO) enzymes", correct:false, why:"MAO breaks down neurotransmitters such as norepinephrine, not cAMP."},
  {t:"Protein kinase A (PKA)", correct:false, why:"PKA is activated downstream of cAMP; it does not degrade it."}],
 teach:"cAMP levels are set by two enzymes: adenylate cyclase makes it and phosphodiesterases (PDE) break it down. Caffeine is a PDE inhibitor, and theophylline, an old asthma drug with many drug–drug interactions, is the other example on the slide. cAMP is involved in feeding, water homeostasis, sleep, heart rate and contractility, and endocrine and neural processes.",
 quote:"Remember, we're either gonna make it through the AC or we're gonna break it down through the PDE. So, those are the two ways that we can do. And we can have drugs that can target that PD. So, we talk about caffeine as a PD inhibitor.",
 cite:"Autonomic Nervous System.pdf slide 7; transcript 9/30"},

{id:"L07-008", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"messenger", skill:"recall",
 concept:"ip3-calcium-excitation", tags:[], source:"both",
 stem:"Which statement about inositol triphosphate (IP3) as a second messenger is CORRECT?",
 options:[
  {t:"High IP3 = high Ca++ = excitation", correct:true, why:"Gq activates phospholipase C, which makes IP3; IP3 raises Ca++ inside the cell, and more Ca++ drives the excitatory (positive) effects: contraction, release, excitation."},
  {t:"High IP3 means low Ca++ and relaxation", correct:false, why:"IP3 raises intracellular Ca++; a fall in Ca++ with relaxation is the opposite of what the Gq pathway does."},
  {t:"IP3 is made by adenylate cyclase", correct:false, why:"IP3 is made through phospholipase C (PLC), the Gq effector; adenylate cyclase is the Gs and Gi effector and makes cAMP."},
  {t:"IP3 is found only in animal neurons", correct:false, why:"IP3 is used widely: by many receptors and in all animals, many plants and fungi, not only in neurons."}],
 teach:"IP3 is used by many receptors (α1, 5-HT3, histamine) and is found in all animals, many plants and fungi. It is linked to cell growth and proliferation and regulates Ca++-dependent enzymes (PKC), receptors, ion channels and muscle contraction. He does not test its chemical structure; the point is ↑IP3 = ↑Ca++ = excitation.",
 quote:"The key thing that I would like for you to remember is that when IP3 is high, calcium is high, and the more calcium we have, the more positive things are going to happen.",
 cite:"Autonomic Nervous System.pdf slides 8–9; transcript 9/30"},

/* ---------------- Organization, receptors (slides 10–13) ---------------- */
{id:"L07-009", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"organize", skill:"tell",
 concept:"nn-vs-nm", tags:[], source:"both",
 stem:"Acetylcholine (ACh) is released both in autonomic ganglia and at skeletal muscle. Which pairing of site and receptor is correct?",
 options:[
  {t:"Ganglia: Nm; skeletal muscle: Nn", correct:false, why:"Reversed: N with subscript N is neuronal (ganglia); N with subscript M is muscle."},
  {t:"Ganglia: Nn; skeletal muscle: Nm", correct:true, why:"Ganglia of both divisions use ACh on neuronal nicotinic (Nn); somatic nerves use ACh on muscle nicotinic (Nm)."},
  {t:"Ganglia: M2; skeletal muscle: Nm", correct:false, why:"Ganglionic transmission is nicotinic: acetylcholine opens Nn ion channels on the postganglionic neuron. M2 is a G protein–coupled receptor in the heart."},
  {t:"Ganglia: Nn; skeletal muscle: M3", correct:false, why:"Skeletal muscle has nicotinic Nm receptors (ion channels); M3 is the muscarinic receptor on smooth muscle and glands."}],
 teach:"In the ganglia, whether parasympathetic or sympathetic, acetylcholine binds nicotinic receptors of the neuronal type, Nn (N as in Nancy, for neuronal). At the somatic neuromuscular junction, acetylcholine binds the muscle type, Nm (M as in muscle). He warns that students miss exam questions just by not knowing what the N and M stand for.",
 quote:"So we have NN as in Nancy for neuronal and NM as in muscle for the skeletal muscle, the somatic, right?",
 reading:[{src:"Katzung 16e, Ch. 6", sec:"Neurotransmitter Chemistry of the Autonomic Nervous System", t:"Fibers that synthesize and release acetylcholine are cholinergic; these include all preganglionic efferent autonomic fibers and the somatic motor fibers to skeletal muscle. Katzung’s receptor table places Nn receptors on postganglionic neurons and Nm receptors at skeletal muscle neuromuscular end plates."}],
 cite:"Autonomic Nervous System.pdf slides 12, 23; transcript 9/30"},

{id:"L07-010", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"organize", skill:"tell",
 concept:"autonomic-vs-somatic", tags:[], source:"both",
 stem:"Which feature belongs to the somatic nervous system rather than the autonomic nervous system?",
 options:[
  {t:"Distal ganglia outside the cerebrospinal axis", correct:false, why:"Distal ganglia are an autonomic feature: the autonomic pathway has two neurons with a ganglion between them, while the somatic nerve runs straight from the spinal cord to the muscle."},
  {t:"Involuntary control of smooth muscle", correct:false, why:"Involuntary control of organs, vasculature and smooth muscle is the autonomic system."},
  {t:"A single myelinated fiber to skeletal muscle", correct:true, why:"Somatic nerves run straight from the spinal cord to skeletal muscle as single, myelinated, fast-conducting fibers."},
  {t:"Mostly non-myelinated postganglionic fibers", correct:false, why:"Non-myelinated postganglionic fibers are an autonomic feature; somatic fibers are myelinated, which is why they conduct faster."},
  {t:"Spontaneous activity without innervation", correct:false, why:"Some spontaneous activity independent of intact innervation is listed as an autonomic feature."}],
 teach:"Somatic: voluntary, a single myelinated efferent fiber straight from the spinal cord to skeletal muscle (fast, for reflexes such as pulling a hand off a hot stove). Autonomic: involuntary, supplies every innervated structure except skeletal muscle, has distal ganglia outside the cerebrospinal axis, mostly non-myelinated postganglionic fibers, and some spontaneous activity.",
 quote:"The major difference over here is that our somatic are myelinated, which means that we have a faster conduction of that actual potential through the neuron.",
 cite:"Autonomic Nervous System.pdf slides 11–12; transcript 9/30"},

{id:"L07-011", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"organize", skill:"recall",
 concept:"enteric-third-branch", tags:[], source:"both",
 stem:"Which statement about the enteric nervous system is correct?",
 options:[
  {t:"It is part of the somatic nervous system", correct:false, why:"The enteric system is grouped with the autonomic system, not the voluntary somatic system."},
  {t:"The gut cannot move without PNS or SNS input", correct:false, why:"A normal bowel movement can occur without parasympathetic or sympathetic contribution."},
  {t:"It is a third branch of the autonomic system", correct:true, why:"Some consider the enteric (gut) system a third autonomic branch, since the gut can work without PNS or SNS input."},
  {t:"It has fewer neurons than the spinal cord", correct:false, why:"The gut has more neuron connections than the spinal cord, which is why it can run a bowel movement without PNS or SNS input."}],
 teach:"The autonomic system has the parasympathetic (PNS) and sympathetic (SNS) branches, and some add the enteric nervous system (the gut) as a third. The gut can have a normal bowel movement without PNS or SNS input, but they influence it: rest and digest increases motility and tone, fight or flight decreases it.",
 quote:"some people may even go farther to say that we have the enteric nerve system, which is your gut, as a third branch of that autonomic nervous system. Because we can have a normal bowel movement without any contribution from the parasympathetic and the sympathetic.",
 reading:[{src:"Katzung 16e, Ch. 6", sec:"Anatomy of the Autonomic Nervous System — enteric nervous system", t:"The enteric nervous system is a large, organized collection of neurons in the walls of the gastrointestinal tract, with more than 150 million neurons, and is sometimes considered a third division of the ANS. It is involved in motor and secretory activity of the gut and is particularly important in control of colon motility."}],
 cite:"Autonomic Nervous System.pdf slide 10; transcript 9/30"},

{id:"L07-012", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"organize", skill:"tell",
 concept:"adrenergic-receptor-locations", tags:[], source:"both", multi:true,
 stem:"Which pairings of adrenergic receptor and its main site of action are correct? Select all that apply.",
 options:[
  {t:"α1: blood vessels", correct:true, why:"Blood vessels are the α1 receptors’ number one job (blood pressure, decongestion)."},
  {t:"α2: central nervous system", correct:true, why:"α2 is primarily in the central nervous system, coupled to Gi."},
  {t:"β1: heart and kidney", correct:true, why:"The two crucial β1 sites are the heart and the kidney."},
  {t:"β2: smooth muscle of vessels, lungs, gut", correct:true, why:"β2 is on smooth muscle all over: blood vessels, lungs, gut."},
  {t:"α2: heart", correct:false, why:"The heart’s adrenergic receptor is β1; α2 is mainly in the central nervous system."},
  {t:"β1: bronchial smooth muscle", correct:false, why:"The airway receptor is β2; β1 is heart and kidney."}],
 teach:"α1: blood vessels (decongestion, blood pressure). α2: central nervous system, coupled to Gi, part of the negative feedback on sympathetic activity. β1: heart and kidney. β2: smooth muscle of blood vessels, lungs and gut. α1, α2 and β1 are innervated; β2 is not.",
 quote:"Are beta 1s, there's two major sites for the beta 1s, the heart and the kidney. Yes, they're in the eye, yes, they are in other places in the brain, but the heart and the kidney is crucial for those receptors, OK?",
 cite:"Autonomic Nervous System.pdf slide 13; transcript 9/30"},

{id:"L07-013", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"organize", skill:"apply",
 concept:"beta2-not-innervated", tags:[], source:"both",
 stem:"β2 receptors in the lungs have no sympathetic nerve releasing norepinephrine onto them. How are they activated during a fight-or-flight response?",
 options:[
  {t:"By acetylcholine from the vagus nerve", correct:false, why:"Vagal acetylcholine acts on M3 (Gq) and constricts the airways; it does not bind β2, which is an adrenergic receptor."},
  {t:"By circulating epinephrine from the adrenal gland", correct:true, why:"The adrenal gland releases epinephrine (and norepinephrine) into the blood, which reaches the β2 receptors."},
  {t:"By mechanical stretch of the airway", correct:false, why:"Stretch and pressure receptors send signals that change autonomic tone through reflexes; they release no ligand onto the airway β2 receptors."},
  {t:"By norepinephrine released from postganglionic fibers", correct:false, why:"Postganglionic norepinephrine reaches only innervated receptors (α1, α2, β1); airway β2 receptors have no sympathetic nerve, so they depend on circulating epinephrine."}],
 teach:"α1, α2 and β1 have a sympathetic nerve releasing norepinephrine directly onto the organ. β2 receptors are not innervated. In fight or flight the adrenal gland, sitting on top of the kidney, releases epinephrine and norepinephrine into the blood; the circulating hormone reaches β2 receptors, opening the airways and dilating skeletal muscle blood vessels.",
 quote:"Our beta 2s are not innervated. They don't have a nerve activating them.",
 cite:"Autonomic Nervous System.pdf slides 13, 35; transcript 9/30"},

{id:"L07-014", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"organize", skill:"recall",
 concept:"muscarinic-locations", tags:[], source:"both",
 stem:"Which statement about muscarinic receptor locations is correct?",
 options:[
  {t:"M1 heart, M2 brain, M3 everywhere else", correct:false, why:"M1 and M2 are reversed: M1 is the brain, M2 is the heart."},
  {t:"M1 brain, M2 heart, M3 everywhere else", correct:true, why:"Scan the body from the top: M1 brain, M2 heart, M3 everywhere else."},
  {t:"M1 brain, M2 everywhere else, M3 heart", correct:false, why:"M3 is the widespread one, not M2."},
  {t:"M1, M2 and M3 are only in the brain", correct:false, why:"Muscarinic receptors are in most organs; nicotinic receptors are the ones limited to nerve and skeletal muscle."}],
 teach:"Muscarinic receptors control most organs through the parasympathetic system. Scan the body: M1 in the brain (Gq), M2 in the heart (Gi), M3 everywhere else (Gq). If you have to guess an organ’s muscarinic receptor, M3 is a good guess. Nicotinic receptors are limited to nerve (Nn) and skeletal muscle (Nm).",
 quote:"So, M1 is in the CNS, M2 is in the heart, M3s everywhere else. I can switch the everywhere from a 3 to a, from an E to a 3 so that you can remember that M3s are the most widespread",
 cite:"Autonomic Nervous System.pdf slides 13, 24; transcript 9/30"},

{id:"L07-015", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"organize", skill:"recall",
 concept:"innervated-receptors", tags:[], source:"both", multi:true,
 stem:"Which adrenergic receptors are typically innervated, with a sympathetic nerve releasing norepinephrine directly onto them? Select all that apply.",
 options:[
  {t:"α1", correct:true, why:"α1 receptors (blood vessels) are innervated."},
  {t:"α2", correct:true, why:"α2 receptors are innervated."},
  {t:"β1", correct:true, why:"β1 receptors (heart, kidney) are innervated."},
  {t:"β2", correct:false, why:"β2 receptors are typically not innervated; circulating epinephrine activates them."}],
 teach:"On the receptor slide, α1, α2 and β1 hang under norepinephrine, and β2 is marked “typically not innervated”. That is why β2 effects such as bronchodilation and skeletal muscle vasodilation depend on epinephrine from the adrenal gland.",
 quote:"Now, most of those receptors, alpha 1, alpha 2, and beta 1, they are innervated. What I mean is you have here, say, the heart and you have a sympathetic nerve directly innervating that organ, releasing norepinephrine activating.",
 cite:"Autonomic Nervous System.pdf slide 13; transcript 9/30"},

/* ---------------- Neurotransmission (slides 14–20) ---------------- */
{id:"L07-016", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"neurotrans", skill:"recall",
 concept:"release-calcium-dependent", tags:[], source:"both",
 stem:"An action potential reaches a nerve terminal. Which event directly triggers the vesicles to fuse with the membrane and release neurotransmitter?",
 options:[
  {t:"Na+ entry through nicotinic receptors", correct:false, why:"Nicotinic sodium entry is a postsynaptic event in ganglia and muscle, not the release trigger in the terminal."},
  {t:"Ca++ entry through voltage-gated channels", correct:true, why:"The action potential opens voltage-gated calcium channels; calcium entry moves the vesicles to the membrane for exocytosis."},
  {t:"Breakdown of the transmitter by enzymes", correct:false, why:"Enzymatic metabolism removes transmitter after release; it does not trigger release."},
  {t:"Reuptake of the transmitter through transporters", correct:false, why:"Transporters remove transmitter from the cleft after release."}],
 teach:"Five key steps: synthesis from a precursor by enzymes; storage in vesicles; release into the cleft, which is Ca++ dependent; binding to post- and/or presynaptic receptors; removal by transporters or by enzymes. The action potential depolarizes the terminal, voltage-gated Ca++ channels open, and calcium drives vesicle fusion and exocytosis.",
 quote:"As I open calcium channels, which is a voltage dependent ion channel, that's gonna allow calcium to come in, that's gonna be the trigger to move those vesicles to the membrane. They're gonna fuse and then now through exocytosis release everything into the synapse as needed.",
 cite:"Autonomic Nervous System.pdf slides 14, 17; transcript 9/30"},

{id:"L07-017", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"neurotrans", skill:"recall",
 concept:"neurotransmission-drug-targets", tags:[], source:"both",
 stem:"Which of the following in a synapse can be drug targets that enhance or decrease a neurotransmitter’s effect?",
 options:[
  {t:"Postsynaptic receptors only", correct:false, why:"Postsynaptic receptors are targets, but so are presynaptic receptors, transporters and enzymes."},
  {t:"Pre- and postsynaptic receptors only", correct:false, why:"Transporters (Prozac blocks one) and breakdown enzymes (COMT, MAO) are also targets."},
  {t:"Receptors, transporters and enzymes", correct:true, why:"Pre- and postsynaptic receptors, transporters and the breakdown enzymes can all be blocked or activated."},
  {t:"Transporters and enzymes, not receptors", correct:false, why:"Receptors, pre- and postsynaptic, are drug targets too: agonists activate them and antagonists block them."}],
 teach:"He asked the class which parts of the synapse are drug targets: postsynaptic receptors, presynaptic receptors, the enzymes that break down transmitter (COMT, MAO) and the transporters (Prozac blocks one). Drugs do not create anything new; they modulate the ongoing physiological system.",
 quote:"Which of these are gonna be drug targets for us? What do you think? Post-synaptic receptors, pre-synaptic receptors, the enzymes that break down our neurotransmitters, the transporters, right? All those we can utilize to either enhance or decrease the effect of our drugs",
 cite:"Autonomic Nervous System.pdf slide 20; transcript 9/30"},

/* ---------------- Parasympathetic (slides 21–27) ---------------- */
{id:"L07-018", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"pns", skill:"tell",
 concept:"pns-vs-sns-fiber-ratio", tags:[], source:"both",
 stem:"How do parasympathetic and sympathetic fibers differ?",
 options:[
  {t:"PNS: short preganglionic, 1:20; SNS: long preganglionic, 1:1", correct:false, why:"Reversed: the parasympathetic (PNS) is the long-preganglionic, 1:1 system."},
  {t:"PNS: long preganglionic, 1:1; SNS: short preganglionic, 1:20", correct:true, why:"PNS ganglia are near the organ (long then short fiber, 1:1); SNS ganglia diverge one-to-many (short then long, 1:20)."},
  {t:"Both: long preganglionic fibers, 1:1", correct:false, why:"Only the parasympathetic is 1:1; the sympathetic is one-to-many."},
  {t:"Both use norepinephrine in the ganglia", correct:false, why:"Both use acetylcholine on Nn receptors in the ganglia."}],
 teach:"Parasympathetic (PNS): a very long preganglionic fiber that synapses near or at the target organ, then a short one, typically 1:1. Sympathetic (SNS): a short preganglionic fiber, then a long one to the organ, one-to-many (1:20 on the slide), so fight or flight can activate many organs at once.",
 quote:"The sympathetic is different. You have a short fiber and then a long fiber to the organ. Most of it, the parasympathetic is typically like 1 to 1. ... The sympathetic is one to many.",
 cite:"Autonomic Nervous System.pdf slides 21, 23, 29; transcript 10/1"},

{id:"L07-019", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"pns", skill:"recall",
 concept:"dumbbelss-members", tags:[], source:"both",
 stem:"A patient has overactivation of the cholinergic system (a cholinergic crisis). Which of the following is NOT expected?",
 options:[
  {t:"Miosis", correct:false, why:"Miosis (small pupils) is the M3 (Gq) effect in the eye; it is the M of DUMBBELSS."},
  {t:"Bradycardia", correct:false, why:"M2 (Gi) in the heart lowers cAMP and slows the rate: bradycardia, the first B of DUMBBELSS."},
  {t:"Mydriasis", correct:true, why:"Mydriasis (pupil dilation) comes from α1 (sympathetic) or from blocking M3 (antimuscarinic); cholinergic overactivation gives the opposite, miosis."},
  {t:"Bronchial constriction", correct:false, why:"M3 (Gq) in the airways raises Ca++ and constricts them: bronchial constriction, the second B."},
  {t:"Lacrimation", correct:false, why:"M3 (Gq) on the glands increases tear secretion: lacrimation, the L."}],
 teach:"DUMBBELSS: Diarrhea, Urination, Miosis, Bradycardia, Bronchial constriction, Emesis, Lacrimation, Salivation, Stimulation. M1 (central nervous system, Gq) gives stimulation, M2 (heart, Gi) gives bradycardia, and M3 (everywhere else, Gq) gives the rest. His memory aid: miosis is the shorter word for the smaller pupil; mydriasis is the longer word for the larger pupil.",
 quote:"And if you're confused on the exam between meiosis and midriasis, meiosis is the smaller name. Mydrisis is the longer word, so large pupils, small pupils, right?",
 cite:"Autonomic Nervous System.pdf slides 24, 27; transcript 9/30, 10/1"},

{id:"L07-020", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"pns", skill:"apply",
 concept:"anti-dumbbelss", tags:[], source:"both", multi:true,
 stem:"A patient overdoses on a muscarinic antagonist. Which effects are expected? Select all that apply.",
 options:[
  {t:"Constipation", correct:true, why:"Blocking M3 in the gut removes motility and tone: the anti-D."},
  {t:"Urinary retention", correct:true, why:"Blocking M3 in the bladder relaxes it, so the patient cannot urinate."},
  {t:"Pupil dilation", correct:true, why:"Blocking M3 in the eye gives mydriasis, the opposite of miosis."},
  {t:"Tachycardia", correct:true, why:"Blocking M2 in the heart removes the brake, so heart rate rises."},
  {t:"Bronchial constriction", correct:false, why:"Bronchial constriction is the M3 agonist (DUMBBELSS) effect in the airways; blocking M3 removes the constricting tone instead."},
  {t:"Salivation", correct:false, why:"Salivation is the M3 agonist effect on the glands; blocking M3 gives dry mouth."}],
 teach:"An agonist overdose gives DUMBBELSS (cholinergic crisis); an antagonist overdose gives the anti-DUMBBELSS: cannot poop, cannot pee, cannot see because the pupils dilate, and tachycardia. Knowing whether a drug is an agonist or antagonist and where M1, M2 and M3 are predicts the profile.",
 quote:"The antagonists cause what? Anti dumbbells. You can't poop, can't pee, can't see because your pupils dilate. You get tachycardia. You get the opposite effect.",
 cite:"Autonomic Nervous System.pdf slide 24; transcript 9/30"},

{id:"L07-021", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"pns", skill:"apply",
 concept:"m3-bladder-agonist", tags:["muscarinic"], source:"both",
 stem:"A patient cannot urinate. Which drug type would most likely help by contracting the bladder smooth muscle?",
 options:[
  {t:"M3 agonist", correct:true, why:"M3 is Gq; an agonist raises Ca++, contracts the bladder smooth muscle and causes urination."},
  {t:"M2 agonist", correct:false, why:"M2 (Gi) is the heart receptor; activating it slows the heart and does not contract the bladder."},
  {t:"β3 agonist", correct:false, why:"β3 relaxes the bladder so that it retains urine: the opposite of what is needed."},
  {t:"M3 antagonist", correct:false, why:"An M3 antagonist blocks the Gq signal in the bladder and relaxes it; that suits patients who cannot control their bladder, the opposite of this patient."}],
 teach:"In the bladder, M3 (Gq, ↑Ca++) squeezes the smooth muscle: an agonist causes urination and helps patients who cannot urinate, while an antagonist relaxes the bladder for patients who cannot control it. The sympathetic β3 receptor in the bladder relaxes it so urine is retained.",
 quote:"If it's the bladder on the smooth muscle, we have M3s, we increase calcium, we're going to squeeze the bladder, so patients going to urinate. Those are going to be good for patients who may have a problem urinating, and then we can use an antagonist to patients who can't control their bladder.",
 cite:"Autonomic Nervous System.pdf slide 27; transcript 10/1"},

{id:"L07-022", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"pns", skill:"apply",
 concept:"antimuscarinic-antiemetic", tags:[], source:"transcript",
 stem:"A patient with a stomach virus has severe vomiting and diarrhea. Which drug class would most likely stop both?",
 options:[
  {t:"A muscarinic agonist", correct:false, why:"An agonist activates the vomiting center and the gut: more emesis and diarrhea."},
  {t:"A muscarinic antagonist", correct:true, why:"Blocking muscarinic receptors in the vomiting center and the gut stops emesis and diarrhea (and causes drowsiness)."},
  {t:"A β1 agonist", correct:false, why:"β1 is in the heart and kidney; it does not control vomiting or gut motility."},
  {t:"A cholinesterase inhibitor", correct:false, why:"Blocking acetylcholine breakdown increases acetylcholine and causes DUMBBELSS, including emesis and diarrhea."}],
 teach:"The vomiting center in the hindbrain is activated by a muscarinic agonist (the E in DUMBBELSS), and M3 in the gut increases motility (the D). When he had rotavirus, the emergency room gave him an antimuscarinic that stopped the vomiting and diarrhea and put him to sleep. Agonists and antagonists of the same system are both used.",
 quote:"So what they do is they gave me an antimuscarinic drug that not only put me to sleep, but it stopped the vomiting, stop the, the diarrhea",
 cite:"transcript 10/1 (Autonomic Nervous System.pdf slide 27)"},

{id:"L07-023", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"pns", skill:"recall",
 concept:"lungs-pns-only", tags:[], source:"both",
 stem:"Which statement about autonomic control of bronchial smooth muscle is correct?",
 options:[
  {t:"Sympathetic nerves release norepinephrine onto it", correct:false, why:"There is no sympathetic innervation of airway smooth muscle; β2 is reached by circulating epinephrine."},
  {t:"It has only parasympathetic innervation", correct:true, why:"Lungs: PNS only. Acetylcholine acts on M3 and constricts the airway."},
  {t:"It has dual innervation like the heart", correct:false, why:"The heart has dual innervation (M2 and β1); the lungs are the exception, with parasympathetic nerves only."},
  {t:"Acetylcholine relaxes it through M2", correct:false, why:"Acetylcholine acts on M3 (Gq, ↑Ca++) in the airway and constricts it; M2 is the heart receptor."}],
 teach:"An exception to the dual-innervation rule: control of airway smooth muscle is only parasympathetic. Acetylcholine binds M3 (Gq) and constricts the airway all the time; when needed, epinephrine from the adrenal gland reaches β2 and dilates. He notes that “only” is usually wrong on a test, but here it is right.",
 quote:"So one of our exceptions that we're going to have to a rule is that in the lungs control of smooth muscle is only parasympathetic. There's no sympathetic involvement or innervation in that process, OK? And I know as a test taker, anytime you see only, always, never typically is incorrect, but this is right.",
 cite:"Autonomic Nervous System.pdf slides 23, 42; transcript 9/30"},

/* ---------------- Sympathetic (slides 28–35) ---------------- */
{id:"L07-024", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"sns", skill:"tell",
 concept:"sns-exceptions-adrenal-salivary", tags:[], source:"both",
 stem:"At most sympathetic end organs, norepinephrine (NE) acts on an adrenergic receptor. Which pairing describes the two sympathetic exceptions? (ACh = acetylcholine; Nn = neuronal nicotinic receptor)",
 options:[
  {t:"Adrenal medulla: ACh on Nn; salivary glands: ACh on M3", correct:true, why:"Both exceptions release acetylcholine: on a nicotinic receptor at the adrenal medulla and on M3 at the salivary glands."},
  {t:"Adrenal medulla: NE on β1; salivary glands: NE on α1", correct:false, why:"NE on an adrenergic receptor is the usual sympathetic pattern; the exceptions are the two sites where the sympathetic fiber releases ACh instead."},
  {t:"Adrenal medulla: ACh on M3; salivary glands: ACh on Nn", correct:false, why:"Reversed: the adrenal medulla has the nicotinic receptor; the salivary glands have M3."},
  {t:"Adrenal medulla: NE on Nn; salivary glands: NE on M3", correct:false, why:"Nicotinic and muscarinic receptors respond to acetylcholine, not norepinephrine."}],
 teach:"Sympathetic exceptions: at the adrenal medulla the sympathetic fiber releases acetylcholine onto a nicotinic receptor, and the gland releases epinephrine into the blood. At the salivary glands a sympathetic fiber releases acetylcholine onto M3. Because of this, both the parasympathetic and the sympathetic systems cause salivation.",
 quote:"So acetylcholine is being released and it's activating a nicotinic receptor. So that's kind of different. ... And then on the salivary gland, we also have a sympathetic fiber that is actually releasing acetylcholine and activating a muscarinic receptor as well.",
 reading:[{src:"Katzung 16e, Ch. 6", sec:"Neurotransmitter Chemistry of the Autonomic Nervous System", t:"Adrenal medullary cells are embryologically analogous to postganglionic sympathetic neurons; they receive input from preganglionic sympathetic nerves and release a mixture of epinephrine and norepinephrine into the circulation. Some sympathetic postganglionic fibers release acetylcholine rather than norepinephrine."}],
 cite:"Autonomic Nervous System.pdf slides 30, 35; transcript 10/1"},

{id:"L07-025", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"sns", skill:"tell",
 concept:"sns-organ-receptor", tags:[], source:"both",
 stem:"Which pairing of a sympathetic effect and the receptor that mediates it is correct?",
 options:[
  {t:"Mydriasis: β1", correct:false, why:"Pupil dilation (mydriasis) is α1 (Gq) in the eye; β1 is the heart and kidney receptor."},
  {t:"Decreased GI activity: α2", correct:true, why:"α2 (Gi) sits on the parasympathetic nerve in the gastrointestinal (GI) tract; it cuts acetylcholine release onto M3, so motility falls (constipation)."},
  {t:"Bladder relaxation: α1", correct:false, why:"The bladder smooth muscle relaxes through β3; α1 is listed with the sphincter."},
  {t:"Tachycardia in the heart: β2", correct:false, why:"Tachycardia is β1 (Gs) in the heart; β2 relaxes smooth muscle (airways, skeletal muscle vessels)."},
  {t:"Sedation: β1", correct:false, why:"Sedation is α2 (Gi) in the central nervous system; α1 and β receptors there cause excitation."}],
 teach:"Activation of the adrenergic system: central nervous system excitation (α1, β), sedation (α2); tachycardia (β1); mydriasis (α1); vasoconstriction of arteries and veins (α1); dilation of bronchial and skeletal muscle blood vessel smooth muscle (β2); bladder relaxation (β3); Na+ and water retention (β1, kidney); decreased GI activity (α2).",
 quote:"And uh on the gut, uh, we have alpha juice, which also inhibitory, which is gonna cause constipation. So the parasympathetic cause diarrhea, the sympathetic causes constipation.",
 cite:"Autonomic Nervous System.pdf slides 31, 35; transcript 10/1"},

{id:"L07-026", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"sns", skill:"apply",
 concept:"sns-activation-effects", tags:[], source:"both", multi:true,
 stem:"A person is being chased by a dog, and the sympathetic nervous system is fully activated. Which effects are expected? Select all that apply.",
 options:[
  {t:"Mydriasis", correct:true, why:"α1 in the eye dilates the pupil."},
  {t:"Tachycardia", correct:true, why:"β1 (Gs) in the heart increases rate and force."},
  {t:"Bronchial dilation", correct:true, why:"Circulating epinephrine reaches β2 in the lungs."},
  {t:"Retention of Na+ and water", correct:true, why:"β1 in the kidney leads to renin release and Na+ and water retention."},
  {t:"Increased GI motility", correct:false, why:"α2 suppresses GI activity: constipation."},
  {t:"Increased urination", correct:false, why:"β3 relaxes the bladder so urine is retained."}],
 teach:"The sympathetic response is roughly the anti-DUMBBELSS with a few differences: pupils dilate (α1), the heart speeds up (β1), arteries and veins constrict (α1), skeletal muscle vessels and airways dilate (β2, from adrenal epinephrine), the bladder relaxes (β3), the kidney retains Na+ and water (β1), the gut slows (α2). Salivation still occurs through the sympathetic M3 exception.",
 quote:"So it's kind of sort of an anti-dumbbells with just a few minor difference that we have before.",
 cite:"Autonomic Nervous System.pdf slides 31, 34–35; transcript 10/1"},

{id:"L07-027", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"sns", skill:"apply",
 concept:"alpha2-agonist-sedation", tags:[], source:"both",
 stem:"Clonidine is an α2 agonist. What does it most likely produce in the brain?",
 options:[
  {t:"Excitation", correct:false, why:"Excitation comes from α1 (Gq) and β (Gs) receptors in the brain; α2 is Gi and inhibits."},
  {t:"Sedation", correct:true, why:"α2 is Gi, part of the negative feedback that limits sympathetic activity: an agonist inhibits, and the patient is sedated."},
  {t:"Mydriasis", correct:false, why:"Mydriasis is an α1 (Gq) effect in the eye; clonidine activates α2, not α1."},
  {t:"Seizures", correct:false, why:"α2 is an inhibitory (Gi) receptor; activating it lowers brain activity, the opposite of a seizure."}],
 teach:"In the brain, activating α1 and β receptors causes excitation; activating α2 (Gi) causes sedation, because α2 is part of the negative feedback that limits sympathetic activation. Clonidine is the α2 agonist he names from the drug list.",
 quote:"If we start in the brain, if I activate the alpha 1s and the betas, now I get excitation. If I activate the alpha 2, now I get sedation. And on your drug list, you're gonna find alpha-2 agonists, such as clonidine",
 cite:"Autonomic Nervous System.pdf slide 34; transcript 10/1"},

{id:"L07-028", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"sns", skill:"apply",
 concept:"propranolol-exercise", tags:[], source:"transcript",
 stem:"A patient takes propranolol and then tries to run a mile. Which outcome is most likely?",
 options:[
  {t:"Running is easier: β blockade dilates the airways", correct:false, why:"Blocking β2 prevents bronchodilation; it does not open the airways."},
  {t:"Running is hard: output and bronchodilation blocked", correct:true, why:"Propranolol blocks β1 and β2: β1 block keeps cardiac output from rising and β2 block prevents bronchodilation, so exercise capacity falls."},
  {t:"No change: β receptors play no part in exercise capacity", correct:false, why:"β1 (heart) and β2 (lungs) are the receptors that raise output and open airways during exercise."},
  {t:"Running is easier: the person is more excited", correct:false, why:"β receptors in the brain are Gs and stimulate; blocking them makes the person less excited, which is why it is given before public speaking."}],
 teach:"Propranolol is a non-selective β blocker (β1 and β2) that is lipid soluble and crosses the blood–brain barrier. β receptors are Gs and stimulate, so blocking them works in three places: in the brain the patient is less excited (it is given for anxiety before public speaking), in the heart cardiac output cannot rise, and in the lungs the airways cannot dilate. His bet: on propranolol you can walk a mile but not run one.",
 quote:"But the reason being is because you block the heart, your heart can increase the cardiac output. You block the lungs, you can't bronchodilate, right? So, you can't maintain that exercise capacity.",
 note:"On 10/1 he described propranolol as very lipid soluble and crossing the blood–brain barrier (the transcript reads \"which is a non active\"); non-selective (β1 and β2) is from the Exam 2 drug list, page 7.",
 cite:"transcript 10/1 (Autonomic Nervous System.pdf slide 29); Pharmacology_Exam_2_Drug_List.pdf page 7"},

{id:"L07-029", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"sns", skill:"tell",
 concept:"alpha1-vs-beta2-vessels", tags:[], source:"both",
 stem:"During fight or flight, why do skeletal muscle blood vessels dilate while most arteries and veins constrict?",
 options:[
  {t:"α1 constricts most; β2 dilates skeletal muscle vessels", correct:true, why:"α1 (Gq) constricts arteries and veins; β2 (Gs), reached by epinephrine, is predominant in skeletal muscle vessels and dilates them."},
  {t:"M3 constricts most vessels; α2 dilates skeletal muscle vessels", correct:false, why:"Blood vessels have no parasympathetic innervation, so M3 is not driving the constriction, and α2 does not dilate skeletal muscle vessels."},
  {t:"β1 constricts most vessels; α1 dilates skeletal muscle vessels", correct:false, why:"β1 is the heart and kidney receptor and does not constrict vessels; α1 (Gq) constricts, it does not dilate."},
  {t:"The parasympathetic system dilates skeletal muscle vessels", correct:false, why:"Blood vessels have sympathetic innervation only; the skeletal muscle dilation comes from epinephrine on β2."}],
 teach:"Vasoconstriction is the predominant sympathetic tone, through α1, to shunt blood to the heart and brain. β2 receptors oppose this and are predominant in the blood vessels of skeletal muscle, so more blood reaches the muscles to run faster and longer.",
 quote:"The alpha ones will be opposed by the beta 2s. The beta is gonna try to relax a little, but the beta 2s are gonna be predominant on the blood vessels to your skeletal muscle. So you get more blood flow to your skeletal muscle, you can run faster and longer, OK?",
 cite:"Autonomic Nervous System.pdf slides 28, 35; transcript 10/1"},

/* ---------------- Dual / single innervation (slides 36–47) ---------------- */
{id:"L07-030", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"innerv", skill:"recall",
 concept:"single-innervation-exceptions", tags:[], source:"both", multi:true,
 stem:"Which of the following are exceptions to dual innervation, with only one autonomic division in control? Select all that apply.",
 options:[
  {t:"Lungs: parasympathetic only", correct:true, why:"Airway smooth muscle has only parasympathetic innervation."},
  {t:"Blood vessels: sympathetic only", correct:true, why:"Resistance arteries and veins have only sympathetic innervation."},
  {t:"Kidneys: sympathetic only", correct:true, why:"The kidneys have only sympathetic innervation."},
  {t:"Heart: sympathetic only", correct:false, why:"The heart is the model of dual innervation: M2 slows it, β1 speeds it."},
  {t:"Eye: parasympathetic only", correct:false, why:"The eye has both: parasympathetic miosis and sympathetic (α1) mydriasis."}],
 teach:"Most end organs have dual innervation, with the two divisions opposing each other (heart: ACh on M2 lowers heart rate, NE on β1 raises it). The single-innervation exceptions: lungs only parasympathetic; blood vessels and kidneys only sympathetic. He says these “only” statements are the ones that will be right if he asks.",
 quote:"So we have here our exceptions. The lungs, only parasympathetic, the blood vessels in the kidney, only sympathetic, OK? Those are the only kind of questions you're gonna get that actually gonna be right if I ask you.",
 cite:"Autonomic Nervous System.pdf slides 37, 43–44; transcript 10/1"},

{id:"L07-031", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"innerv", skill:"apply",
 concept:"lungs-tone-infection", tags:[], source:"transcript",
 stem:"Why is the resting tone of the airways constriction, and what common side effect follows from bronchodilator drugs?",
 options:[
  {t:"Wide airways let pathogens deeper: airway infections", correct:true, why:"The larger the airways, the deeper things get; airway infections are a common side effect of bronchodilators."},
  {t:"Constriction saves oxygen: hypoxia", correct:false, why:"Bronchodilators let more air in, not less; the side effect that follows from wider airways is infection, because allergens, viruses and bacteria reach deeper."},
  {t:"The sympathetic tone constricts airways: bradycardia", correct:false, why:"Airway tone is parasympathetic (acetylcholine on M3); there is no sympathetic innervation of airway smooth muscle, and bradycardia is not a bronchodilator effect."},
  {t:"β2 receptors constrict: tachycardia", correct:false, why:"β2 receptors dilate the airways (Gs); the constricting tone is M3."}],
 teach:"The parasympathetic (M3) is the physiological tone in the lungs: constrict all the time, relax when needed. Keeping the airways tight protects against allergens, viruses and bacteria. When a β2 agonist or a muscarinic antagonist opens the airways, airway infections become a common side effect.",
 quote:"You know what is one of the most common, uh, uh, side effects of taking a bronchodilator, such as a beta2 agonist or muscarinic antagonist. Airway infections, right? The bigger your airways are, more things can get deeper and thus you start to get airway infections.",
 cite:"transcript 10/1 (Autonomic Nervous System.pdf slides 39–42)"},

{id:"L07-032", lecture:"L07", prof:"Gottlieb", tier:"new", level:1, topic:"L07", sub:"innerv", skill:"recall",
 concept:"kidney-sns-renin", tags:[], source:"both",
 stem:"The sympathetic nervous system is the only autonomic input to the kidney. What does sympathetic activation of the kidney lead to?",
 options:[
  {t:"Renin, Ang II, aldosterone: Na+ and water retained", correct:true, why:"Sympathetic input causes renin release; angiotensin II and aldosterone lead to Na+ and water reabsorption."},
  {t:"Increased Na+ excretion and a rise in urine output", correct:false, why:"Sympathetic activation (β1, renin) retains Na+ and water and decreases urine output; it does not increase excretion."},
  {t:"Parasympathetic M3 activation of the renal tubules", correct:false, why:"The kidney has sympathetic innervation only; there is no parasympathetic M3 input to the tubules."},
  {t:"Decreased renin release and a fall in blood pressure", correct:false, why:"Sympathetic input raises renin release, which leads to angiotensin II and aldosterone, raising blood volume and pressure."}],
 teach:"On the kidney slide, sympathetic input causes vasoconstriction and renin release; angiotensin II and aldosterone then drive Na+ and water reabsorption, and water follows sodium. The goal is to raise blood volume when pressure is too low. The full renin–angiotensin system comes later in the module.",
 quote:"If I increase sympathetic to my kidneys, I'm gonna retain more sodium because I make the ras system, which is gonna cause the retention of sodium and water.",
 cite:"Autonomic Nervous System.pdf slide 43; transcript 10/1"},

{id:"L07-033", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"innerv", skill:"recall",
 concept:"cooperative-innervation", tags:[], source:"both",
 stem:"In which organ do the parasympathetic and sympathetic systems work together rather than in opposition, with the parasympathetic producing erection and the sympathetic producing ejaculation?",
 options:[
  {t:"Heart", correct:false, why:"In the heart they oppose each other (M2 vs β1)."},
  {t:"Male sex organ", correct:true, why:"“Point and shoot”: point is parasympathetic, shoot is sympathetic."},
  {t:"Urinary bladder smooth muscle", correct:false, why:"In the bladder M3 contracts and β3 relaxes: opposition."},
  {t:"Eye", correct:false, why:"In the eye miosis (parasympathetic) opposes mydriasis (α1)."}],
 teach:"The two divisions oppose each other in most organs. Two exceptions work in concert: the salivary glands (both cause salivation: parasympathetic gives fluid saliva, sympathetic gives thick saliva) and the male sex organ, where the parasympathetic produces erection and the sympathetic produces ejaculation (point and shoot).",
 quote:"The parasympathetic is involved in producing the action as the sympathetic is involved in producing the ejaculation, OK? So a way for you to remember that in the exam is just point and shoot, right.",
 cite:"Autonomic Nervous System.pdf slide 44; transcript 10/1"},

{id:"L07-034", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"innerv", skill:"apply",
 concept:"gi-alpha2-presynaptic", tags:[], source:"both",
 stem:"In the gastrointestinal (GI) tract, where is the α2 receptor that the sympathetic system uses to reduce motility, and how does it work?",
 options:[
  {t:"On GI smooth muscle; Gq raises Ca++ and relaxes it", correct:false, why:"α2 is Gi, not Gq, and it is not on the smooth muscle; Gq and a Ca++ rise would contract, not relax, smooth muscle."},
  {t:"On the parasympathetic nerve; Gi cuts ACh release", correct:true, why:"Norepinephrine hits α2 (Gi) on the parasympathetic terminal, so less acetylcholine (ACh) is released onto M3 and motility falls."},
  {t:"On GI smooth muscle; Gi lowers cAMP and relaxes it", correct:false, why:"The α2 is on the parasympathetic nerve, not on the gut muscle."},
  {t:"On the sympathetic nerve; Gs raises NE release", correct:false, why:"α2 is Gi and inhibits; on the parasympathetic nerve it lowers ACh release, it does not raise norepinephrine (NE) release."}],
 teach:"A dual-innervation caveat: the parasympathetic nerve releases acetylcholine onto M3 (Gq, ↑Ca++), increasing GI motility and secretion. The sympathetic fiber innervates the parasympathetic nerve, not the gut: norepinephrine activates α2 (Gi, ↓cAMP) on that nerve, inhibiting acetylcholine release, so M3 activation and motility fall.",
 quote:"So the alpha-2 is not on the gut, the alpha-2 actually is on the nerve of the parasympathetic system. So by doing that, I can decrease the release of acetylcholine, which is going to decrease the activation of the M3s and thus less motility, less tone, right?",
 cite:"Autonomic Nervous System.pdf slides 45–47; transcript 10/1"},

/* ---------------- Baroreceptors (slides 48–53) ---------------- */
{id:"L07-035", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"baro", skill:"tell",
 concept:"baroreceptor-sites-nerves", tags:[], source:"slide",
 stem:"Which pairing of baroreceptor site and the nerve that carries its signal is correct?",
 options:[
  {t:"Carotid sinus: vagus nerve (X)", correct:false, why:"The carotid sinus, which monitors blood going to the central nervous system, is carried by the glossopharyngeal nerve (IX); the vagus (X) carries the aortic arch."},
  {t:"Aortic arch: glossopharyngeal nerve (IX), near the heart", correct:false, why:"The aortic arch, close to the heart, is carried by the vagus nerve (X); the glossopharyngeal nerve (IX) carries the carotid sinus."},
  {t:"Carotid sinus: glossopharyngeal nerve (IX)", correct:true, why:"The carotid sinus, where the carotid splits into internal and external, is carried by nerve IX."},
  {t:"Aortic arch: phrenic nerve", correct:false, why:"The aortic arch baroreceptors send their signal through the vagus nerve (X), not the phrenic nerve."}],
 teach:"Baroreceptors are pressoreceptors embedded in the vessel wall. Carotid sinus: where the common carotid splits into internal and external carotid, monitoring blood going to the central nervous system, glossopharyngeal nerve (IX). Aortic arch: close to the heart, vagus nerve (X).",
 quote:"Carotid Sinus – Where it split into internal and external carotid – Monitor blood going to the CNS – Glossopharyngeal Nerve (IX); Aortic Arch – Close to the Heart – Vagus Nerve (X)",
 cite:"Autonomic Nervous System.pdf slide 49"},

{id:"L07-036", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"baro", skill:"figure",
 concept:"baroreceptor-sigmoid", tags:[], source:"slide",
 stem:"A graph plots baroreceptor nerve firing rate (y-axis) against blood pressure (x-axis, mmHg). The curve is sigmoidal: flat near zero at low pressure, steepest around the normal mean arterial pressure, and flat at its maximum at high pressure. At about what pressure is the baroreceptor most sensitive to a change?",
 options:[
  {t:"Below 50 mmHg", correct:false, why:"Below 50 mmHg there is no firing at all."},
  {t:"About 93 mmHg", correct:true, why:"Maximum sensitivity (the steepest part of the curve) is at about 93 mmHg, near the normal mean arterial pressure."},
  {t:"About 180 mmHg", correct:false, why:"About 180 mmHg is maximum firing, where the curve is flat and further rises change little."},
  {t:"About 150 mmHg", correct:false, why:"150 mmHg is on the upper bend toward the plateau, not the steepest point."}],
 teach:"The firing–pressure relationship is sigmoidal: below 50 mmHg there is no firing, about 180 mmHg gives maximum firing, and about 93 mmHg (normal mean arterial pressure) is the point of maximum sensitivity. Firing is greatest while pressure is increasing, less at constant pressure, least while pressure is decreasing.",
 quote:"Sigmoidal Relationship · BP < 50 mmHg = 0 firing · BP ≈ 180 mmHg = Max Firing · BP = 93 mmHg => Max Sensitivity",
 note:"The numbers (0 firing below 50 mmHg, maximum firing near 180 mmHg, maximum sensitivity at 93 mmHg) are on slides 50–51; he did not read them aloud on 10/1. This is a pressure–firing curve, not a dose–response curve (he said Exam 2 has no dose–response curves).",
 cite:"Autonomic Nervous System.pdf slides 50–51"},

{id:"L07-037", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"baro", skill:"apply",
 concept:"baroreceptor-inverse-sns", tags:[], source:"both",
 stem:"A student’s blood pressure rises from 100 to about 145 mmHg from exam stress. What do the baroreceptors and the autonomic system most likely do?",
 options:[
  {t:"Firing falls; sympathetic activity rises", correct:false, why:"Falling firing with rising sympathetic activity is the response to a drop in pressure; a rise in pressure stretches the receptors and increases firing."},
  {t:"Firing rises; parasympathetic rises, sympathetic falls", correct:true, why:"Stretch increases firing, which enhances the parasympathetic and shuts off the sympathetic to bring pressure down."},
  {t:"Firing rises; sympathetic activity rises", correct:false, why:"Baroreceptor firing is inversely related to sympathetic activity: more firing turns the sympathetic down, not up."},
  {t:"Firing is unchanged; only the chemoreflex responds to it", correct:false, why:"Rising pressure stretches the baroreceptors, so they fire more (full blast); the baroreflex responds, not only the chemoreflex."}],
 teach:"Rule of thumb: baroreceptor firing is inversely proportional to sympathetic activity (↑ firing = SNS activity ↓). High pressure stretches the receptors, firing goes up, the parasympathetic takes over and the sympathetic is shut down to protect the organs. Low pressure silences the nerve, and the unopposed sympathetic raises pressure.",
 quote:"So, the rule of thumb that we're gonna have is that the barrel receptor firing is gonna be inverse proportional to the sympathetic activity. The more inspiring, the less sympathetic I have, the more parasympathetic tone I'm gonna get.",
 reading:[{src:"Katzung 16e, Ch. 6", sec:"Integration of Autonomic Function — A. Integration of Cardiovascular Function", t:"Increased firing of the baroreceptor nerves of the carotid sinus and aortic arch decreases central sympathetic outflow and increases vagal outflow. For this reason a pressor dose of norepinephrine in a person with intact reflexes raises mean arterial pressure but often slows the heart, a reflex response opposite to the drug’s direct cardiac action."}],
 cite:"Autonomic Nervous System.pdf slide 50; transcript 10/1"},

{id:"L07-038", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"baro", skill:"apply",
 concept:"standing-baroreflex", tags:[], source:"both",
 stem:"A person lying supine stands up quickly. Blood pools in the leg veins. Which sequence is expected with intact baroreceptors?",
 options:[
  {t:"More venous return; firing rises; sympathetic falls", correct:false, why:"Standing pools blood in the leg veins and reduces venous return, so the receptors are less stretched and fire less."},
  {t:"Less venous return; firing falls; sympathetic rises", correct:true, why:"Less filling and stroke volume mean less stretch and firing; the parasympathetic shuts off and the sympathetic squeezes the veins."},
  {t:"Less venous return; firing rises; parasympathetic rises", correct:false, why:"Less stretch reduces firing; a parasympathetic rise would worsen the drop in pressure."},
  {t:"No change; gravity does not affect blood pressure", correct:false, why:"Gravity pools blood in the feet; without the reflex the person faints."}],
 teach:"Upright: peripheral venous pooling ↑, venous return ↓, ventricular filling ↓, stroke volume and blood pressure ↓. The baroreceptors are less stretched and fire less, the parasympathetic is shut off and the sympathetic is activated, so SVR, venous return and stroke volume rise and the brain stays perfused. If the reflex fails, as in some elderly patients, the person faints (syncope).",
 quote:"So the barrels are gonna be less stretched. They're going to fire less. We're going to shut off the s the parasympathetic, and we're going to activate the sympathetics, right?",
 note:"Slide 52 shows a single ↓ next to “SNS and PNS”; in the lecture he says the parasympathetic is shut off and the sympathetic is activated. The key follows the lecture.",
 cite:"Autonomic Nervous System.pdf slide 52; transcript 10/1"},

{id:"L07-039", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"baro", skill:"apply",
 concept:"vasodilator-orthostatic-counsel", tags:[], source:"transcript",
 stem:"An elderly patient starts a vasodilator. Based on the baroreceptor reflex, what should the patient be told?",
 options:[
  {t:"Take it at bedtime to avoid trouble sleeping", correct:false, why:"Bedtime dosing is not the issue the baroreflex raises; the risk is that dilated veins pool blood when the patient stands, so brain perfusion drops."},
  {t:"Stand up slowly; sit back down if dizzy", correct:true, why:"Getting up too fast can drop brain perfusion and cause a fall, the leading worry in the elderly."},
  {t:"Avoid caffeine with each dose", correct:false, why:"Caffeine is not the risk here; the risk is a drop in brain blood flow on standing, which the patient manages by getting up slowly."},
  {t:"Stop it at once if dizzy", correct:false, why:"Stopping the drug is not needed; the dizziness on standing passes if the patient sits back down and tries again after a few seconds."}],
 teach:"Vasodilators blunt the squeeze of the veins that the sympathetic system uses when a person stands. Counsel the patient: get up slowly; if you feel dizzy or see black, sit back down and try again after a few seconds. Falls are a leading cause of death in the elderly, because a bed-bound patient’s problems compound.",
 quote:"So when we give drugs to our patients and those drugs are classified as vasodilators, the one thing that you need to educate them about is what if you're sitting down, get up slowly, if you feel a little bit uh, you know, dizzy, if you see black, sit back down and then try and do it again after a few seconds, right?",
 cite:"transcript 10/1 (Autonomic Nervous System.pdf slide 52)"},

{id:"L07-040", lecture:"L07", prof:"Gottlieb", tier:"new", topic:"L07", sub:"baro", skill:"tell",
 concept:"baroreflex-vs-chemoreflex", tags:[], source:"both",
 stem:"Short-term control of blood pressure integrates three reflexes. Which pairing is correct?",
 options:[
  {t:"Baroreflex: excitatory, sympathetic", correct:false, why:"The baroreflex is stimulated by a rise in pressure and works through the inhibitory, parasympathetic side to bring pressure down."},
  {t:"Chemoreflex: senses ↓PO2 and ↑PCO2; excitatory", correct:true, why:"The chemoreflex responds to falling oxygen and rising carbon dioxide and drives the excitatory (sympathetic) side."},
  {t:"Chemoreflex: senses stretch of the aortic arch", correct:false, why:"Stretch is sensed by the baroreceptors; the chemoreflex senses O2 and CO2."},
  {t:"CSAR: inhibitory, parasympathetic", correct:false, why:"The cardiac sympathetic afferent reflex (CSAR) is on the excitatory side, stimulated mechanically or chemically."}],
 teach:"The “love triangle”: the baroreflex (stimulated by ↑BP) is inhibitory and works through the parasympathetic; the chemoreflex (↓PO2, ↑PCO2) and the cardiac sympathetic afferent reflex (CSAR, mechanical or chemical stimulation) are excitatory and work through the sympathetic. All feed central integration, which sends output to peripheral organs. He does not test the NTS and PVN anatomy.",
 quote:"So typically the sympathetic is exciting the system through the chemo reflex and the heart function as the parasympathetic is through the bare receptors.",
 cite:"Autonomic Nervous System.pdf slides 48, 53; transcript 10/1"}
);
