TOPICS.push({id:'L04', name:'Drug–receptor interactions I: two-state model, inverse agonists, allosterics, antagonists', prof:'Gottlieb', lecture:'L04',
  cite:'Day 4 (9/28) — Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf (Part 1) and the Day 3 recap slides',
  subs:[
    {id:'recap', name:'Two-state recap: full agonist, partial agonist, FA + FA, FA + PA', cite:'Day 3 deck slides ~31–~65 (lectured 9/28); Day 4 deck slide ~3'},
    {id:'ia', name:'Inverse agonist alone and full agonist + inverse agonist', cite:'slides ~4–~24'},
    {id:'allo', name:'Allosteric agonists and antagonists', cite:'slides ~25–~34, ~36–~42'},
    {id:'antag', name:'Kinds of antagonism and antagonist names', cite:'slides ~35–~37'},
    {id:'comp', name:'Competitive antagonist', cite:'slides ~43–~50, ~55'},
    {id:'irrev', name:'Irreversible antagonist, Emax rule and spare receptors', cite:'slides ~51–~56'}
  ]});
QUESTIONS.push(
{id:'L04-001', fg:'two-state', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'tell',
 concept:'full-vs-partial-agonist-summary', tags:[], source:'transcript',
 stem:'In the two-state model, which property do a full agonist and a partial agonist share?',
 options:[
  {t:'Highest affinity for active-state receptors', correct:true, why:'Both bind active receptors best and keep them active; both also have positive efficacy and are reversible.'},
  {t:'The ability to reach 100% of the system’s response', correct:false, why:'Only the full agonist reaches 100%; the partial agonist plateaus below that.'},
  {t:'Negative efficacy', correct:false, why:'Both have positive efficacy; negative efficacy belongs to the inverse agonist.'},
  {t:'Equal affinity for active and inactive receptors', correct:false, why:'Equal affinity for both states describes the neutral competitive antagonist.'}],
 teach:'Full and partial agonists are alike in the two-state model: both have the highest affinity for receptors in the active state, both can bind an inactive receptor and turn it on (positive efficacy), and both are reversible. They differ only in how much efficacy they carry: the full agonist reaches 100%, the partial agonist plateaus between 1% and 99%.',
 quote:'So when we think about full and partial agonists, the first thing that should come to mind is they love receptors that are active, and if they bind to, they’re gonna have the highest affinity for those receptors. However, if they bind to receptors that are inactive, they can shut, they can turn them on, right?',
 cite:'transcript 9/28; Pharmacodynamics-Day_3_2026s.pdf slides ~32–~41',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'Full agonists shift the conformational equilibrium of receptors more strongly than partial agonists do.'}]},

{id:'L04-002', fg:'two-state', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'apply',
 concept:'baseline-reflects-receptor-activity', tags:[], source:'transcript',
 stem:'A full agonist is given to a cell in which 50% of the receptors are active on their own. Where does its dose–response curve start and where does it end?',
 options:[
  {t:'Starts at 50%, ends at 100%', correct:true, why:'The baseline reflects the receptors already active; a full agonist has 100% efficacy, so it goes to 100% from wherever it starts.'},
  {t:'Starts at 0% and ends at 100%', correct:false, why:'A baseline of 0% belongs to a system in which nearly all receptors are inactive (R > R*).'},
  {t:'Starts at 50%, ends at 50%', correct:false, why:'A flat line at the baseline is what a neutral antagonist gives, not a full agonist.'},
  {t:'Starts at 50%, ends at 0%', correct:false, why:'Going down to 0% is the inverse agonist’s curve.'}],
 teach:'The baseline is a reflection of the receptor activity in the system before any drug is given. With most receptors inactive (R > R*, one sign on the exam means about 99% inactive) the baseline is 0%. With half the receptors active it is 50%. A full agonist goes to 100% independently of where it starts; if all receptors are already active the curve is a flat line at 100%.',
 quote:'It, the baseline is just a reflection of the receptor activity that is happening. But when I go from 50, I go all the way to 100.',
 cite:'transcript 9/28; Pharmacodynamics-Day_3_2026s.pdf slides ~37–~40'},

{id:'L04-003', fg:'partial', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'figure', multi:true,
 concept:'partial-agonist-range', tags:['poll'], source:'transcript',
 stem:'Five drugs at the same receptor are plotted as dose–response curves, A–E, each given on its own. Which of these drugs are partial agonists? Select all that apply.',
 graph:{curves:[{label:'A', ec:-1.2, emax:80}, {label:'B', ec:0.2, emax:75}, {label:'C', ec:-0.4, emax:25}, {label:'D', ec:0.6, emax:5}, {label:'E', ec:-0.5, emax:100}], base:0, x:'log dose', y:'% of maximal response'},
 options:[
  {t:'Drug A (80%)', correct:true, why:'Any effect between 1% and 99% is a partial agonist; 80% is close to the top but not 100%.'},
  {t:'Drug B (75%)', correct:true, why:'75% lies between 1% and 99%.'},
  {t:'Drug C (25%)', correct:true, why:'25% lies between 1% and 99%.'},
  {t:'Drug D (5%)', correct:true, why:'5% is a weak but positive effect, so the drug is still a partial agonist.'},
  {t:'Drug E (100%)', correct:false, why:'A drug that reaches 100% is a full agonist, not a partial agonist.'}],
 teach:'A partial agonist is any drug that produces an effect between 1% and 99% of the system’s maximum: equal to or greater than 1 and equal to or less than 99. At 100% it is a full agonist; at 0% it is not a partial agonist. A curve that gets close to 100% but does not reach it is still partial.',
 quote:'a partial agonist is going to be any drug that produce an effect between 1 and 99, right? Has to be equal or greater than 1, and equal or less than 99.',
 cite:'transcript 9/28; Pharmacodynamics-Day_3_2026s.pdf slides ~50–~52',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists', t:'Partial agonists produce a lower response at full receptor occupancy than full agonists do.'}]},

{id:'L04-004', fg:'drc-basic', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'figure',
 concept:'fa-plus-fa', tags:[], source:'transcript',
 stem:'Levophed is synthetic norepinephrine. The dotted line is norepinephrine alone. A pretreatment dose of Levophed that by itself produces 40% of the maximal effect is given, then the norepinephrine dose–response curve is rebuilt. Which solid curve shows the result?',
 graph:{curves:[{label:'NE', ec:0, emax:100, dashed:true}, {label:'A', ec:-1, emax:100, base:40}, {label:'B', ec:1, emax:100}, {label:'C', ec:-1, emax:60, base:40}, {label:'D', ec:1, emax:100, base:40}], base:0, x:'log dose norepinephrine', y:'% of maximal response'},
 options:[
  {t:'A: starts at 40%, shifts left, still reaches 100%', correct:true, why:'Levophed has already activated enough receptors for 40%, norepinephrine needs fewer receptors of its own (shift left), and both drugs reach the same Emax.'},
  {t:'B: starts at 0%, shifts right, still reaches 100%', correct:false, why:'A second full agonist helps; a right shift belongs to drugs that compete against the agonist.'},
  {t:'C: starts at 40%, shifts left, plateaus at 60%', correct:false, why:'Emax does not change: the heart cannot beat faster than its maximum whether one or two full agonists are present.'},
  {t:'D: starts at 40%, shifts right, reaches 100%', correct:false, why:'The raised starting point is right, but a right shift means norepinephrine was made less potent; a second full agonist shares the work and shifts the curve left.'}],
 teach:'A full agonist in the presence of another full agonist: the second drug activates some receptors on the first drug’s behalf, so the first drug appears more potent (shift left, apparent affinity increased); a pretreatment dose that already produces an effect raises the baseline; and Emax is unchanged since both are reversible and both want the same maximal effect.',
 quote:'now norepinephrine still goes to 100%, but it’s further to the left and the baseline has going up, right? Because levofed has efficacy, positive efficacy.',
 cite:'transcript 9/28; Pharmacodynamics-Day_3_2026s.pdf slides ~42–~49'},

{id:'L04-005', fg:'potency', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'figure',
 concept:'fa-plus-fa', tags:['poll'], source:'both',
 stem:'If DRC B is the DRC of norepinephrine binding to the β1 receptor alone, which DRC best represents the DRC of norepinephrine in the presence of epinephrine?',
 graph:{curves:[{label:'A', ec:-1, emax:100}, {label:'B', ec:0, emax:100}, {label:'C', ec:1, emax:100}, {label:'D', ec:1, emax:50}], base:0, x:'log dose norepinephrine', y:'% of maximal response'},
 options:[
  {t:'A', correct:true, why:'Norepinephrine and epinephrine are both full agonists at β1; each makes the other appear more potent, so the curve moves left.'},
  {t:'B', correct:false, why:'B is the point of reference (norepinephrine alone); a second full agonist changes the curve.'},
  {t:'C', correct:false, why:'A curve to the right means the agonist appears less potent, which is what a competing drug does, not a helping one.'},
  {t:'D', correct:false, why:'A lower or right-shifted curve would mean epinephrine made norepinephrine’s life harder; two full agonists help each other.'},
  {t:'None of the above', correct:false, why:'One curve (A) does show the left shift produced by a second full agonist.'}],
 teach:'The first question to ask is whether the second drug helps the agonist or makes its life more difficult. A second full agonist helps, so the only possible answers are curves to the left; curves to the right or below are eliminated. Norepinephrine makes epinephrine more potent and epinephrine makes norepinephrine more potent.',
 quote:'we have two full agonists, norepinephrine and Epi, that binds to the same receptor and depending on who is bound to it, they’re going to do the same effect. And thus shifting to the left.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~3; transcript 9/28'},

{id:'L04-006', fg:'partial', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'apply',
 concept:'fa-plus-pa-aripiprazole', tags:[], source:'transcript',
 stem:'A manic patient has a high level of dopamine (full agonist, Emax 100%) at the dopamine D2 receptor. Therapy with aripiprazole, a D2 partial agonist with an Emax of 60%, is started. What happens to the response as aripiprazole occupies more receptors than dopamine?',
 options:[
  {t:'It falls toward 60%', correct:true, why:'Both drugs are reversible; whichever has the higher concentration occupies more receptors, and receptors occupied by aripiprazole can only produce its 60%.'},
  {t:'It rises to 100%', correct:false, why:'Adding a partial agonist to a system already at 100% cannot add efficacy; it competes and brings the response down.'},
  {t:'It falls to 0%', correct:false, why:'Only an inverse agonist brings the response to 0%; a partial agonist brings it to its own efficacy.'},
  {t:'It stays unchanged at 100%', correct:false, why:'Once aripiprazole outcompetes dopamine by mass action, the occupied receptors signal at 60%, so the response changes.'}],
 teach:'Dopamine and aripiprazole compete for the same D2 binding pocket and both are reversible, so by the law of mass action the drug with the higher concentration occupies more receptors. Receptors occupied by aripiprazole signal at its efficacy of 60%, so in a manic (high dopamine) patient the response is brought down to about 60%; in a depressed patient (low baseline) the same drug brings the response up.',
 quote:'as long as I’m occupying enough receptors, more than dopamine is, I can outcompete dopamine and bring that baseline to about 60%. So that my patient is not manic anymore.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~54–~58; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists', t:'A partial agonist cannot cause a maximal response even when it saturates all receptors, so it competitively inhibits the responses produced by a full agonist at the same receptor.'}]},

{id:'L04-007', fg:'inverse', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'tell',
 concept:'partial-vs-inverse-endpoint', tags:[], source:'transcript',
 stem:'A system starts at 100% activity. A partial agonist with 75% efficacy is given to one preparation and an inverse agonist to another, each in high enough dose to occupy most receptors. Where does each response end?',
 options:[
  {t:'Partial agonist 75%; inverse agonist 0%', correct:true, why:'A partial agonist brings the response to whatever its own efficacy is; an inverse agonist brings it to 0%.'},
  {t:'Partial agonist 100%; inverse agonist 0%', correct:false, why:'A partial agonist never reaches 100%, not alone and not when competing with a full agonist.'},
  {t:'Partial agonist 75%; inverse agonist 25%', correct:false, why:'The inverse agonist has negative efficacy and ends at 0% regardless of the starting point.'},
  {t:'Partial agonist 0%; inverse agonist 0%', correct:false, why:'A partial agonist has positive efficacy; once it occupies the receptors the response is its 75%, not zero.'}],
 teach:'A partial agonist has a dual nature: from a low baseline it raises the response (agonist behavior) and from a high baseline it competes the response down (antagonist behavior), but in every case the endpoint is its own efficacy (75% goes to 75%, 30% to 30%). An inverse agonist ends at 0% whether the baseline was 25%, 50% or 100%.',
 quote:'The key difference over here when we compare to inverse agonist is that a partial agonist is only going to bring the dose response curve to whatever its efficacy is. If it’s 75%, everything finishes at 75%.',
 cite:'transcript 9/28; Pharmacodynamics-Day_3_2026s.pdf slides ~59–~63; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~12'},

{id:'L04-008', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'apply',
 concept:'partial-agonist-dual-nature', tags:['varenicline'], source:'transcript',
 stem:'A patient taking varenicline for smoking cessation smokes one cigarette. Compared with smoking before therapy, what does that cigarette do?',
 options:[
  {t:'Produces less effect than before', correct:true, why:'Varenicline is present at a concentration high enough to outcompete the nicotine from one cigarette, so the receptors signal at the partial agonist’s level.'},
  {t:'Produces a larger effect than before', correct:false, why:'A partial agonist occupying receptors competes with nicotine; it does not add to a full agonist’s effect.'},
  {t:'Produces the same effect as before', correct:false, why:'Receptors occupied by varenicline cannot give nicotine’s full response.'},
  {t:'Brings the response to 0%', correct:false, why:'A partial agonist has positive efficacy; bringing everything to 0% is the inverse agonist.'}],
 teach:'Varenicline serves two purposes. In withdrawal (no nicotine, receptors inactive) it activates some nicotinic receptors and removes the cravings without opening the ion channel 100%. If the patient smokes, varenicline outcompetes the nicotine of a cigarette, so the cigarette does little; only nonstop smoking could outcompete varenicline. Which behavior appears depends on the physiological state.',
 quote:'If they start to smoke and they’re taking Chantix, now Chantix is gonna outcompete nicotine, so that one cigarette, it’s not gonna do much for them.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~64–~65; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Variation in Drug Responsiveness', t:'A partial agonist may exhibit dramatically different responses depending on the amount of endogenous full agonist present, acting as an agonist when it is low and as an antagonist when it is high.'}]},

{id:'L04-009', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'recall',
 concept:'partial-agonist-table', tags:['poll','albuterol'], source:'both',
 stem:'Which of the following drugs is a partial agonist?',
 options:[
  {t:'Albuterol', correct:true, why:'Albuterol is the β2 partial agonist on the drug list; it opens the airways enough for an asthma patient to breathe without opening them 100%.'},
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist.'},
  {t:'Histamine', correct:false, why:'Histamine is the body’s full agonist at histamine receptors.'},
  {t:'Acetylcholine', correct:false, why:'Acetylcholine is a full agonist.'},
  {t:'Metoprolol', correct:false, why:'Metoprolol is a competitive antagonist at β1.'}],
 teach:'From the drug list, albuterol is the partial agonist; the others in this poll are agonists (epinephrine, histamine, acetylcholine) or an antagonist (metoprolol). A partial agonist is used when the maximal response is not needed: albuterol opens the airways just enough for an asthma patient to breathe better.',
 quote:'If your patient has asthma, albuterol, which is a partial agonist, is going to open up your airways just enough for you to breathe better in and out. You don’t have to open your lungs 100%.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~3; transcript 9/28'},

{id:'L04-010', fg:'inverse', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'recall', multi:true,
 concept:'inverse-agonist-two-state', tags:[], source:'both',
 stem:'Which statements describe an inverse agonist in the two-state model? Select all that apply.',
 options:[
  {t:'Highest affinity for receptors in the inactive state', correct:true, why:'It binds and stabilizes the receptor in the inactive state.'},
  {t:'Negative efficacy', correct:true, why:'If it binds an active receptor it shuts it off, shifting DR* to DR.'},
  {t:'Reversible', correct:true, why:'All inverse agonists on the market are reversible: they bind and come off.'},
  {t:'Highest affinity for receptors in the active state', correct:false, why:'Preference for active receptors belongs to full and partial agonists.'},
  {t:'Ends the curve between 1% and 99%', correct:false, why:'An inverse agonist brings the curve all the way to 0%; the 1–99% plateau is the partial agonist.'}],
 teach:'An inverse agonist has the highest affinity for receptors in the inactive state and keeps them inactive; if it binds a receptor that is active, its negative efficacy shuts that receptor off. It lowers the dose–response curve all the way to 0%. Like every other orthosteric agonist class in this course, it is reversible.',
 quote:'Binds and stabilize the receptor in an inactive state ↑ Affinity. Evoke a change in the receptor - Efficacy.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~4–~12; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Some antagonists show inverse agonist activity: they reduce receptor activity below the basal level observed in the absence of any agonist.'}]},

{id:'L04-011', fg:'inverse', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'apply',
 concept:'inverse-agonist-needs-raised-baseline', tags:[], source:'both',
 stem:'An inverse agonist is given alone, in increasing doses, to a tissue in which the receptors are mostly in the inactive state (R > R*). What would its DRC look like?',
 options:[
  {t:'A flat line at 0%', correct:true, why:'The receptors are already inactive, which is what the inverse agonist wants; there is nothing to bring down.'},
  {t:'A flat line at 100%', correct:false, why:'A flat line at 100% is the starting point of a system in which every receptor is active (R <<< R*) before the drug is added; the inverse agonist would bring it down, not leave it there.'},
  {t:'A curve rising to 100%', correct:false, why:'Rising to 100% is the full agonist; the inverse agonist has negative efficacy.'},
  {t:'A sigmoid curve falling from 100% to 0%', correct:false, why:'That is the inverse agonist’s curve only when the baseline has been raised, for example in a cell line whose receptors are naturally active (R <<< R*).'}],
 teach:'To see what an inverse agonist does, the baseline must be raised: the drug must be put into a system whose receptors are active by themselves (for example a cancer cell line in which 100% of the receptors are active). Then the curve goes from the baseline down to 0%. At a baseline of 0% every dose gives a straight line at 0%.',
 quote:'if I give you my inverse agonist, where all the receptors are inactive, what would be my baseline? 0. What would it do to that baseline? Stays at zero because it\'s already doing what I want.',
 note:'His Jeopardy form of this idea (J16): "What effect an inverse agonist would have on a full agonist DRC? Assume that the tissue has 50% of receptor present in the active state (R = R*)", keyed "decrease the baseline and shift the DRC to the right". Expect the receptor state to be given as R > R*, R = R* or R <<< R*, as on Day 4 slides 7–11.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~7–~11; transcript 9/28'},

{id:'L04-012', fg:'inverse', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'figure', multi:true,
 concept:'fa-plus-inverse-agonist', tags:['histamine','loratadine'], source:'both',
 stem:'Histamine dose–response curves are built in a system with 50% of receptors active, first alone (dotted line) and then after increasing pretreatment doses of loratadine. Which changes appear in histamine’s curve? Select all that apply.',
 graph:{curves:[{label:'H', ec:-0.5, emax:100, dashed:true}, {label:'+L', ec:0.5, emax:100, base:25}, {label:'+10L', ec:1.5, emax:100, base:3}], base:50, x:'log dose histamine', y:'% of maximal response'},
 options:[
  {t:'Baseline decreases', correct:true, why:'Each loratadine dose shuts off more of the receptors that were active on their own, lowering the starting point toward 0%.'},
  {t:'Shift to the right', correct:true, why:'Histamine must reach a higher concentration to outcompete loratadine, so it appears less potent.'},
  {t:'No change to Emax', correct:true, why:'Loratadine is reversible; with enough histamine the inverse agonist is outcompeted and the maximal response is reached.'},
  {t:'Shift to the left', correct:false, why:'A left shift means the second drug helped the agonist; loratadine competes against histamine.'},
  {t:'Emax decreases', correct:false, why:'Only an irreversible antagonist or an allosteric antagonist affecting efficacy lowers the Emax.'}],
 teach:'Take-home message for a full agonist in the presence of an inverse agonist: apparent affinity of the agonist decreases (shift to the right, appears less potent), basal activity of the receptors is reduced (baseline goes down, eventually to 0%), and there is no effect on Emax because the inverse agonist is reversible and can always be outcompeted.',
 quote:'So, take home message over here, it’s gonna bring the baseline down to 0, and it’s gonna shift to the right with no change to the Emax, right?',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~13–~22; transcript 9/28',
 note:'Slide ~22 says "No Effect on Emax against a high efficacy agonist"; in class the rule was stated without the qualifier: histamine, a full agonist, always gets back to Emax because loratadine is reversible. For the exam, use the class rule: reversible drugs never change the Emax of a full agonist.'},

{id:'L04-013', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'recall',
 concept:'fa-plus-inverse-emax-why', tags:['histamine','loratadine'], source:'both',
 stem:'In the presence of loratadine, histamine still reaches its maximal response if enough histamine is released. Which property of loratadine makes this possible?',
 options:[
  {t:'It is reversible', correct:true, why:'Loratadine binds and comes off, so whichever drug has the higher concentration wins the receptors; enough histamine outcompetes it.'},
  {t:'It has positive efficacy', correct:false, why:'Loratadine has negative efficacy; efficacy is not what lets histamine reach Emax.'},
  {t:'It binds an allosteric site', correct:false, why:'Loratadine competes for the same orthosteric pocket as histamine.'},
  {t:'It forms covalent bonds', correct:false, why:'Covalent binding would make it irreversible and would lower the Emax instead.'}],
 teach:'Any drug that is reversible, competitive and surmountable can be outcompeted: the agonist only has to be present at a higher concentration than the inverse agonist. That is why the inverse agonist changes potency (shift right) and baseline but never the ability of the full agonist to reach Emax. A higher loratadine dose simply requires more histamine to outcompete it.',
 quote:'They are reversible. As long as I can outcompete them because they’re going to bind and they’re going to come off, whoever has the highest concentration is going to occupy the most receptors to it.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~14, ~21; transcript 9/28'},

{id:'L04-014', fg:'classes', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'tell',
 concept:'inverse-vs-competitive-need-baseline', tags:[], source:'both',
 stem:'A full agonist’s curve is built with the baseline at 0%, then rebuilt after pretreatment with drug B. B shifts the curve to the right with no change to the baseline or the Emax. Which classification of B cannot be ruled out from this figure alone?',
 graph:{curves:[{label:'A alone', ec:-0.5, emax:100, dashed:true}, {label:'A + B', ec:0.7, emax:100}], base:0, x:'log dose agonist', y:'% of maximal response'},
 options:[
  {t:'Inverse agonist or competitive antagonist', correct:true, why:'At a baseline of 0% an inverse agonist has nothing to lower, so it looks exactly like a neutral competitive antagonist; a raised baseline is needed to tell them apart.'},
  {t:'Full agonist or allosteric agonist', correct:false, why:'Both would help the agonist and shift the curve to the left.'},
  {t:'Partial agonist or full agonist', correct:false, why:'A partial agonist has positive efficacy and would change the baseline; a full agonist shifts left.'},
  {t:'Irreversible antagonist or allosteric antagonist affecting efficacy', correct:false, why:'An allosteric antagonist affecting efficacy always lowers the Emax, so this pair is out; the irreversible antagonist is only excluded once enough shifts are drawn without a drop (spare receptors can delay it).'}],
 teach:'The system must have receptors in the active state (R = R*) to distinguish a full agonist plus inverse agonist from a full agonist plus competitive antagonist. With the baseline already at 0% both give a right shift with no change in baseline or Emax. Antihistamines were classed as antagonists until cell lines with naturally active receptors showed that they shut activity down.',
 quote:'if I give you that figure in the right, you can’t differentiate between a competitive and an inverse because you’re at 0 and there’s no change. I have to give you something different for you to see a change to occur.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~15, ~22; transcript 9/28'},

{id:'L04-015', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'recall',
 concept:'constitutive-activity-inverse', tags:['loratadine'], source:'both',
 stem:'Which receptors are more sensitive to inverse agonists?',
 options:[
  {t:'Receptors with constitutive activity', correct:true, why:'Receptors that are active on their own give the inverse agonist something to shut down; antihistamines such as loratadine and cetirizine act this way.'},
  {t:'Receptors held entirely in the inactive state', correct:false, why:'With every receptor inactive an inverse agonist produces a flat line at 0%.'},
  {t:'Receptors bound by an irreversible antagonist', correct:false, why:'Covalently blocked receptors are not available to any other drug.'},
  {t:'Receptors with no orthosteric site', correct:false, why:'Inverse agonists in this course are orthosteric and compete for the binding pocket.'}],
 teach:'Receptors that have constitutive activity (active by themselves, without any drug, hormone or neurotransmitter) are more sensitive to inverse agonists. The antihistamines cetirizine and loratadine are the classic inverse agonists; histamine, opioid, cannabinoid, dopamine, bradykinin and adenosine receptors are listed as showing this. Loratadine is the one inverse agonist to know on the drug list.',
 quote:'Receptors that have constitutive activity are more sensitive to inverse agonists.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~23; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Inverse agonist activity means the drug reduces receptor activity below the basal level seen with no agonist present at all.'}]},

{id:'L04-016', fg:'classes', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'figure',
 concept:'five-curve-e-loratadine', tags:['poll','loratadine'], source:'both',
 stem:'The DRCs below represent the individual DRCs of five different drugs. DRC E most likely represents the DRC of:',
 graph:{curves:[{label:'A', ec:-1, emax:100}, {label:'B', ec:0.6, emax:100}, {label:'C', ec:0, emax:75}, {label:'D', ec:0, emax:50}, {label:'E', ec:0, emax:0}], base:50, x:'log dose', y:'% of maximal response'},
 options:[
  {t:'Loratadine', correct:true, why:'A curve that brings the baseline to 0% is an inverse agonist, and loratadine is the inverse agonist on the drug list.'},
  {t:'Norepinephrine', correct:false, why:'Norepinephrine is a full agonist; its curve rises to 100%.'},
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist; its curve rises to a plateau below 100%.'},
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist; its curve rises to 100%.'}],
 teach:'Two steps: first classify curve E (it lowers the baseline to zero, so it is an inverse agonist), then find the drug on the list that belongs to that class (loratadine, an antihistamine). Knowing the classifications without knowing the drugs, or the drugs without the classifications, leaves the question unanswerable.',
 quote:'Because it’s bringing the baseline to zero. The next step is which of these drugs would fall into the category of being an inverse agonist.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~24; transcript 9/28'},

{id:'L04-017', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'recall',
 concept:'allosteric-two-things', tags:[], source:'both',
 stem:'What are the two things to know about an allosteric agonist?',
 options:[
  {t:'Two drugs bound at once; affects affinity or efficacy or both', correct:true, why:'It binds a different site, so the agonist can be bound at the same time, and it changes the pocket in a way that alters affinity, efficacy or both.'},
  {t:'Competes for the orthosteric pocket; has positive efficacy of its own', correct:false, why:'An allosteric drug binds someplace else and does not compete for the pocket.'},
  {t:'Forms covalent bonds; lowers the receptor pool', correct:false, why:'Covalent, pool-lowering binding is the irreversible antagonist; all allosterics in this course are reversible.'},
  {t:'Binds only inactive receptors; has negative efficacy', correct:false, why:'That describes the inverse agonist.'}],
 teach:'Allosteric drugs are the exception to one-or-the-other binding: two drugs can be bound to the receptor at the same time. The allosteric agonist binds someplace else in the receptor and changes the orthosteric pocket so the agonist binds more easily, increasing its affinity, its efficacy or both. For this course all allosterics are reversible.',
 quote:'Allosteric: 2 Things you should know - Two drugs bound at the same time - Affinity or Efficacy or Both.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~25–~28; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Allosteric modulators bind a site on the receptor separate from the orthosteric site bound by the agonist, so they modify receptor activity without blocking agonist binding.'}]},

{id:'L04-018', fg:'potency', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure',
 concept:'allosteric-agonist-affinity-only', tags:['poll'], source:'both',
 stem:'If DRC B is the DRC of an agonist alone, which curve would best represent agonist B in the presence of an allosteric agonist that affects only the affinity?',
 graph:{curves:[{label:'A', ec:-1.2, emax:100}, {label:'B', ec:0, emax:100}, {label:'C', ec:-0.6, emax:60}, {label:'D', ec:1.2, emax:100}, {label:'E', ec:1, emax:45}], base:0, x:'log dose', y:'% of maximal response'},
 options:[
  {t:'A', correct:true, why:'An allosteric agonist helps, so the curve moves left; affinity-only means the maximal response is untouched.'},
  {t:'B', correct:false, why:'B is the point of reference; an allosteric agonist changes the agonist’s curve.'},
  {t:'C', correct:false, why:'A changed maximum means efficacy was affected, which the stem rules out.'},
  {t:'D', correct:false, why:'A right shift with the same maximum is an allosteric antagonist affecting affinity.'},
  {t:'E', correct:false, why:'A changed maximum means efficacy was affected, which the stem rules out.'}],
 teach:'An allosteric agonist that affects only affinity shifts the agonist’s curve to the left (more potent) with no change to the efficacy. Curves whose maximum changed (C, E) involve efficacy; a curve to the right (D) means the agonist was made less potent, which is an allosteric antagonist affecting affinity.',
 quote:'Help, which means you’re gonna make the drug more potent, right? And it because it only affects affinity, you’re not affecting the ability to produce its effect, is moving to the left.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~26, ~42; transcript 9/28'},

{id:'L04-019', fg:'efficacy', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure',
 concept:'allosteric-agonist-efficacy-only', tags:[], source:'both',
 stem:'The dotted line is drug A alone, which plateaus at 60% (a partial agonist). An allosteric agonist that affects only the efficacy of drug A is added. Which solid curve shows the result?',
 graph:{curves:[{label:'A', ec:0, emax:60, dashed:true}, {label:'W', ec:0, emax:100}, {label:'X', ec:-1.2, emax:60}, {label:'Y', ec:1.2, emax:35}, {label:'Z', ec:-1.2, emax:100}], base:0, x:'log dose drug A', y:'% of maximal response'},
 options:[
  {t:'W: rises to a higher maximum with no shift left or right', correct:true, why:'Efficacy is read on the y-axis: the partial agonist now behaves like a full agonist, while its EC50 position is unchanged.'},
  {t:'X: shifts left with the same 60% maximum', correct:false, why:'A pure left shift is an affinity effect, not an efficacy effect.'},
  {t:'Y: shifts right with a lower maximum', correct:false, why:'A right shift plus lower maximum is an allosteric antagonist affecting both affinity and efficacy.'},
  {t:'Z: shifts left and also rises to a higher maximum than before', correct:false, why:'Both changes together mean affinity and efficacy were affected; the stem says efficacy only.'}],
 teach:'An allosteric agonist affecting efficacy only does not move the curve left or right; it moves it up, so a partial agonist can be converted into a full agonist. Affecting affinity only shifts the curve left. Affecting both shifts left and raises the maximum. A full agonist already at 100% cannot show an efficacy effect, so only the affinity shift is visible.',
 quote:'I have that drug in the presence of an allosteric agonist that affects efficacy only now it’s not moving left or right, it’s moving what up ... It went from being a partial agonist to a full agonist, right?',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~27–~29; transcript 9/28'},

{id:'L04-020', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure', multi:true,
 concept:'allosteric-characteristics', tags:[], source:'both',
 stem:'A full agonist’s curve (dotted line) is rebuilt after each of several increasing doses of an allosteric agonist (solid lines, 1×, 10× and 100×). Which features are seen? Select all that apply.',
 graph:{curves:[{label:'alone', ec:0.6, emax:100, dashed:true}, {label:'1×', ec:-0.3, emax:100}, {label:'10×', ec:-1.1, emax:100}, {label:'100×', ec:-1.7, emax:100}], base:0, x:'log dose agonist', y:'% of maximal response'},
 options:[
  {t:'Shifts to the left', correct:true, why:'The allosteric agonist increases the agonist’s affinity, so it appears more potent.'},
  {t:'Shifts of unequal size', correct:true, why:'Binding at the allosteric site is non-competitive and does not depend on the agonist, so each dose occupies an unpredictable fraction; the shifts are asymmetrical.'},
  {t:'Shifts stop growing at high doses', correct:true, why:'Once all allosteric sites are occupied the drug has done all it can; the effect is saturable.'},
  {t:'Emax rises above 100%', correct:false, why:'A full agonist is already at 100%, so no efficacy effect can be seen.'},
  {t:'Shifts of equal size', correct:false, why:'Equal (symmetrical) shifts belong to orthosteric competition, for example a competitive antagonist.'}],
 teach:'Four characteristics of a full agonist with multiple doses of an allosteric agonist: affinity affected (yes, shift left), efficacy affected (no, already at 100%), symmetrical shifts (no, the shifts differ in size), saturability (yes, after a certain number of shifts there is a limit to how much the allosteric drug can affect the system). Asymmetrical, saturable shifts are how an allosteric drug is recognized.',
 quote:'I can keep giving more and more of my allosteric, and he can’t go more to the left. He has maxed out all that he can do to the system.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~30–~34; transcript 9/28'},

{id:'L04-021', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'antag', skill:'tell',
 concept:'chemical-vs-physiological-antagonism', tags:[], source:'both',
 stem:'Acetylcholine at muscarinic receptors lowers heart rate while epinephrine at β1 receptors raises it. What kind of antagonism is this?',
 options:[
  {t:'Physiological', correct:true, why:'Two agonists acting independently at different receptors in the same organ produce opposing effects.'},
  {t:'Chemical', correct:false, why:'Chemical antagonism is a direct chemical interaction between the agonist and the antagonist, as with chelating agents such as dimercaprol.'},
  {t:'Competitive (orthosteric)', correct:false, why:'The two drugs bind different receptors; they do not compete for the same pocket.'},
  {t:'Allosteric', correct:false, why:'Neither drug binds another site on the other’s receptor.'}],
 teach:'Chemical antagonism: a direct chemical interaction between the agonist and the antagonist, for example chelating agents such as dimercaprol used to treat gold, mercury or arsenic poisoning. Physiological antagonism: two agonists acting independently of each other on different receptors and producing opposing effects, for example acetylcholine and epinephrine in the heart. The pharmacological antagonists (competitive, irreversible, allosteric) are the focus.',
 quote:'Physiological: Two agonist acting independent of each other producing opposing effects. Ach and Epi in the heart.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~35; transcript 9/28'},

{id:'L04-022', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'antag', skill:'recall',
 concept:'antagonist-synonyms', tags:[], source:'both',
 stem:'Which term is another name for a competitive antagonist?',
 options:[
  {t:'Surmountable', correct:true, why:'Competitive, reversible and surmountable are different names for the same drug: it binds and comes off, and the agonist can outcompete it.'},
  {t:'Insurmountable', correct:false, why:'Insurmountable names the irreversible antagonist, which cannot be overcome by more agonist.'},
  {t:'Non-equilibrium', correct:false, why:'Non-equilibrium names the irreversible antagonist; there is no balance between binding and unbinding.'},
  {t:'Non-competitive', correct:false, why:'Non-competitive covers the irreversible antagonist (binds and does not come off) and the allosteric antagonist (binds someplace else).'}],
 teach:'Pharmacological antagonisms: competitive (orthosteric) = surmountable = reversible, the most common in clinical practice, agonist and antagonist competing for the same receptor site; nonequilibrium-competitive (orthosteric) = irreversible = insurmountable, cannot be overcome by increasing the agonist concentration; allosteric antagonist = non-competitive, reduces the agonist’s affinity and/or efficacy from another site.',
 quote:'One is competitive antagonist, also known as reversible antagonists, also known as surmountable antagonists, different names for the same drug. They bind and they come off.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~36; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Sufficiently high concentrations of agonist can surmount the effect of a given concentration of a competitive antagonist, whereas agonists cannot surmount a noncompetitive antagonist irrespective of their concentration.'}]},

{id:'L04-023', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'antag', skill:'recall',
 concept:'pam-nam', tags:[], source:'both',
 stem:'In the literature, what is a negative allosteric modulator (NAM)?',
 options:[
  {t:'An allosteric antagonist', correct:true, why:'A NAM binds another site and reduces the agonist’s affinity and/or efficacy.'},
  {t:'An allosteric agonist', correct:false, why:'The allosteric agonist is the positive allosteric modulator (PAM).'},
  {t:'An inverse agonist', correct:false, why:'An inverse agonist is orthosteric with negative efficacy, not an allosteric ligand.'},
  {t:'An irreversible antagonist', correct:false, why:'The irreversible antagonist binds the orthosteric pocket covalently.'}],
 teach:'Allosteric ligands: the allosteric agonist is a positive allosteric modulator (PAM); the allosteric antagonist is a negative allosteric modulator (NAM). Whatever the positive one does (raises affinity, efficacy or both), the negative one does the opposite.',
 quote:'we can also call allosteric agonists PAMs, positive allosteric modulators, you see that in the literature, or NAMs, negative allosteric modulators, but the key thing is if you know what the positive does, the negative is the opposite.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~37; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Negative allosteric modulators bind an allosteric site to reduce receptor activity; positive allosteric modulators bind an allosteric site to increase it.'}]},

{id:'L04-024', fg:'efficacy', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure',
 concept:'allosteric-antagonist-effects', tags:['poll'], source:'both',
 stem:'If DRC D is the DRC of an agonist alone, which curve would best represent agonist D in the presence of an allosteric antagonist that affects the affinity and efficacy of D?',
 graph:{curves:[{label:'A', ec:-1.6, emax:100}, {label:'B', ec:-0.8, emax:100}, {label:'C', ec:-1, emax:55}, {label:'D', ec:0, emax:100}, {label:'E', ec:1.1, emax:55}], base:0, x:'log dose', y:'% of maximal response'},
 options:[
  {t:'E', correct:true, why:'Lower affinity shifts the curve right and lower efficacy brings the maximum down.'},
  {t:'C', correct:false, why:'C moves left (affinity improved) but drops the maximum (efficacy reduced); no drug does that.'},
  {t:'A', correct:false, why:'A left shift means the agonist was helped; an antagonist makes its life harder.'},
  {t:'B', correct:false, why:'A left shift with the same maximum would be an allosteric agonist affecting affinity.'},
  {t:'D', correct:false, why:'D is the point of reference; the allosteric antagonist changes the curve.'}],
 teach:'An allosteric antagonist is the opposite of the allosteric agonist. Affinity only: shift to the right, Emax still reached at higher doses. Efficacy only: no shift, the full agonist behaves like a partial agonist. Both: shift right and a lower maximum. The shifts are asymmetrical and the drug is non-competitive (it binds someplace else). A curve that moves left while losing its maximum has no matching drug.',
 quote:'it’s affecting the affinity, so it’s gonna shift to the right and it’s affecting the efficacy, so it’s gonna bring it down. So E would be the best answer.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~38–~42; transcript 9/28'},

{id:'L04-025', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'tell',
 concept:'noncompetitive-two-reasons', tags:[], source:'both',
 stem:'Irreversible antagonists and allosteric antagonists are both called non-competitive. What makes each one non-competitive?',
 options:[
  {t:'Irreversible: binds and does not come off; allosteric: binds a different site', correct:true, why:'No competition is possible with a drug that never leaves the pocket, or with a drug that never enters it.'},
  {t:'Both bind the orthosteric pocket covalently', correct:false, why:'Only the irreversible antagonist forms covalent bonds; allosterics are reversible in this course.'},
  {t:'Both have negative efficacy', correct:false, why:'Negative efficacy is the inverse agonist; these antagonists have no pharmacological efficacy of their own.'},
  {t:'Irreversible: binds a different site; allosteric: binds and does not come off', correct:false, why:'The reasons are reversed.'}],
 teach:'Two different reasons give the same label. The irreversible antagonist forms covalent bonds in the orthosteric pocket and never comes off, so there is no equilibrium or competition. The allosteric antagonist binds reversibly at another site in the receptor, so it is not competing for the pocket at all; the agonist cannot overcome it and the shifts it causes are asymmetrical.',
 quote:'One because one binds and doesn’t come off, the other one because it binds someplace else. There’s no competition with it along the way.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~36, ~41; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Once a receptor is bound by a noncompetitive antagonist, agonists cannot surmount the inhibition; some noncompetitive antagonists bind irreversibly, others bind reversibly at a separate allosteric site.'}]},

{id:'L04-026', fg:'two-state', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'apply',
 concept:'competitive-antagonist-neutral-alone', tags:[], source:'both',
 stem:'A competitive antagonist alone is given in increasing doses to a system in which 50% of the receptors are active. What does its own dose–response curve show?',
 options:[
  {t:'A flat line at 50%', correct:true, why:'The antagonist has equal affinity for active and inactive receptors and no efficacy, so it leaves the balance where it found it.'},
  {t:'A curve falling from 50% to 0%', correct:false, why:'Bringing active receptors down to zero requires negative efficacy, which is the inverse agonist.'},
  {t:'A curve rising from 50% to 100%', correct:false, why:'Rising to 100% requires positive efficacy, which the antagonist lacks.'},
  {t:'A flat line at 0%', correct:false, why:'The antagonist does not change the baseline; the system stays at the 50% it started with.'}],
 teach:'A competitive antagonist is neutral in the two-state model: it does not care whether the receptor is active or inactive, has equal affinity for both states (R = affinity = R*), and does not evoke a change in the receptor. It has affinity but no pharmacological efficacy. Alone, it keeps the baseline wherever it is: 0 stays 0, 50 stays 50, 100 stays 100.',
 quote:'they don’t care what the receptor is, active or inactive, they hang out with both types. They don’t discriminate as such, they don’t change the balance of the receptor activity.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~43–~44; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Receptor antagonists bind to receptors but do not activate them; their primary action is to reduce the effects of agonists that normally activate the receptor.'}]},

{id:'L04-027', fg:'competitive', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'figure', multi:true,
 concept:'competitive-antagonist-shift', tags:[], source:'both',
 stem:'Drug A is a full agonist and drug B is a competitive antagonist at the same receptor. A’s curve (dotted line) is rebuilt after increasing doses of B (solid lines). Which statements describe the result? Select all that apply.',
 graph:{curves:[{label:'A', ec:-1.5, emax:100, dashed:true}, {label:'+B', ec:-0.5, emax:100}, {label:'+10B', ec:0.5, emax:100}, {label:'+100B', ec:1.5, emax:100}], base:0, x:'log dose drug A', y:'% of maximal response'},
 options:[
  {t:'Shift to the right', correct:true, why:'A must reach a higher concentration to outcompete B for the receptors, so its ED50 rises and it appears less potent.'},
  {t:'No change to the baseline', correct:true, why:'B is neutral: it has no efficacy, so it neither raises nor lowers the starting point.'},
  {t:'No change to Emax', correct:true, why:'B is reversible, so with enough A the antagonist is outcompeted and the maximal response is reached.'},
  {t:'Symmetrical shifts', correct:true, why:'Each tenfold increase in B needs a tenfold increase in A; the shifts are the same size.'},
  {t:'Emax decreases', correct:false, why:'A lower Emax is the mark of an irreversible antagonist or an allosteric antagonist affecting efficacy.'},
  {t:'Baseline decreases', correct:false, why:'A falling baseline is the inverse agonist; a competitive antagonist has no efficacy.'}],
 teach:'Full agonist plus competitive antagonist: shift to the right (A can outcompete B, but needs a higher dose), no change to the baseline (B has no efficacy), no change to Emax (B is reversible), and symmetrical shifts (one or the other occupies the pocket, and a tenfold increase in antagonist needs a tenfold increase in agonist). The shifts can continue toward infinity.',
 quote:'Very symmetrical shifts with no change to the baseline, no change to the Emax, just shifting to the right.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~45–~50; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'A competitive antagonist increases the agonist concentration required for a given response, shifting the agonist curve to the right, while the Emax for the agonist stays the same at any fixed antagonist concentration.'}]},

{id:'L04-028', fg:'competitive', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'calc',
 concept:'competitive-tenfold-rule', tags:[], source:'both',
 stem:'A full agonist’s curve has been shifted to the right by one dose of a competitive antagonist. The antagonist dose is then increased 10 times. By how much must the agonist dose increase to outcompete the antagonist again?',
 options:[
  {t:'10 times', correct:true, why:'By the law of mass action, whoever has the greater concentration occupies more receptors; matching a tenfold antagonist increase takes a tenfold agonist increase, giving symmetrical shifts.'},
  {t:'2 times', correct:false, why:'A twofold increase would leave the antagonist with the higher concentration.'},
  {t:'100 times', correct:false, why:'A hundredfold increase would be more than the competition requires; the shifts are proportional.'},
  {t:'It cannot outcompete the antagonist', correct:false, why:'A competitive antagonist is reversible, so the agonist can always outcompete it with enough drug.'}],
 teach:'Competition for one orthosteric pocket follows the law of mass action: the drug with the greater concentration occupies the most receptors. If the antagonist dose is increased tenfold, the agonist dose must be increased tenfold to outcompete it, so successive shifts are symmetrical. A competitive antagonist raises the agonist’s ED50, so the agonist appears less potent.',
 quote:'if I increase the dose by tenfold, I have to increase the dose of the other by tenfold to outcompete them.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~47–~49; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'The agonist concentration needed for a given effect in the presence of a competitive antagonist is greater than without it, and the ratio of the two concentrations depends on the antagonist concentration.'}]},

{id:'L04-029', fg:'irreversible', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'recall',
 concept:'irreversible-antagonist-mechanism', tags:[], source:'both',
 stem:'Why does an irreversible antagonist lower the maximal response (Emax) of a full agonist?',
 options:[
  {t:'It removes receptors from the available pool permanently', correct:true, why:'Covalent bonds lock the antagonist on, so the receptors it occupies are gone; once too few remain, the agonist cannot reach Emax no matter the dose.'},
  {t:'It has negative efficacy', correct:false, why:'The irreversible antagonist is neutral, with no pharmacological efficacy; it does not change receptor state.'},
  {t:'It changes the shape of the orthosteric pocket from another site', correct:false, why:'Changing the pocket from another site is the allosteric antagonist.'},
  {t:'It has the lowest affinity of the drug classes', correct:false, why:'It has the greatest affinity (smallest Kd) of any class.'}],
 teach:'An irreversible antagonist forms covalent bonds that cannot be reversed under normal metabolic function, so it has the greatest affinity (smallest Kd) and once bound it does not come off. That lowers the number of receptors available. With fewer receptors the agonist cannot outcompete it, so it cannot reach the maximal effect, and at high enough antagonist doses the response can be abolished completely.',
 quote:'There’s a lowering of my receptor pool availability because some of them are going to be permanently bound to the irreversible antagonist. And because I don’t have enough receptors available and I can’t outcompete it, I can put all the drug I want, I cannot outcompete those guys.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~51–~53; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'After an irreversible antagonist occupies some proportion of receptors, the number of unoccupied receptors may be too low for the agonist, even at high concentrations, to produce the previous maximal response.'}]},

{id:'L04-030', fg:'irreversible', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'figure',
 concept:'irreversible-antagonist-curve', tags:[], source:'both',
 stem:'A full agonist’s curve (dotted line) is rebuilt after increasing doses of an irreversible antagonist (solid lines). Which set of changes is seen?',
 graph:{curves:[{label:'alone', ec:-1.5, emax:100, dashed:true}, {label:'1×', ec:-0.5, emax:100}, {label:'10×', ec:0.4, emax:65}, {label:'100×', ec:1, emax:25}], base:0, x:'log dose agonist', y:'% of maximal response'},
 options:[
  {t:'Shift right, Emax falls, baseline unchanged', correct:true, why:'Fewer receptors remain, so a higher agonist dose is needed and the maximum drops, eventually to zero; the neutral antagonist does not move the baseline.'},
  {t:'Shift right, Emax unchanged, baseline unchanged', correct:false, why:'An unchanged Emax is the competitive antagonist; an irreversible one is not outcompeted.'},
  {t:'Shift right, Emax unchanged, baseline falls', correct:false, why:'A falling baseline belongs to the inverse agonist.'},
  {t:'Shift left, Emax unchanged, baseline rises', correct:false, why:'That is a second full agonist helping the first.'}],
 teach:'Take-home message for the irreversible antagonist: no change to the baseline (it is neutral, no efficacy), shift to the right (competition for the same pocket, symmetrical), and a decrease in Emax that can go all the way to 0 and abolish the curve completely. The agonist appears both less potent (higher ED50) and less efficacious.',
 quote:'IrA = ↑ED50 FA = Appears less Potent. ↓ Emax FA = Appears less efficacious.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~53–~54; transcript 9/28',
 note:'Katzung states an irreversible antagonist reduces the maximal effect "although it may not change its EC50"; the slides and class say the curve shifts to the right with a higher ED50 as well as a lower Emax. The exam is written from the lecture: shift right and reduced Emax.',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'An irreversible antagonist reduces the maximal effect the agonist can achieve, and high agonist concentrations cannot overcome it.'}]},

{id:'L04-031', fg:'classes', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'tell', multi:true,
 concept:'emax-lowering-classes', tags:[], source:'transcript',
 stem:'Which drug classes can lower the Emax of a full agonist? Select all that apply.',
 options:[
  {t:'Irreversible antagonist', correct:true, why:'It permanently removes receptors, so the agonist cannot outcompete it to reach the maximum.'},
  {t:'Allosteric antagonist that affects efficacy', correct:true, why:'It changes the pocket so the agonist signals less, lowering the maximum without competition.'},
  {t:'Competitive antagonist', correct:false, why:'Reversible, so the agonist always outcompetes it; Emax is unchanged.'},
  {t:'Inverse agonist', correct:false, why:'Reversible, so the agonist always outcompetes it; it lowers the baseline, not the Emax.'},
  {t:'Allosteric agonist', correct:false, why:'It helps the agonist; it raises efficacy or affinity rather than lowering the maximum.'}],
 teach:'Concrete exam rule: anything that lowers the Emax has to be either an irreversible antagonist or an allosteric antagonist that affects efficacy. Every other class is reversible and competitive, so the Emax is unchanged. The difference between the two: the allosteric antagonist saturates and cannot bring the response all the way down, while the irreversible antagonist can abolish the response completely.',
 quote:'If you see something that it lowers the Emax, you know that has to be either an irreversible antagonist or an allosteric antagonist that affects efficacy, right? Those are the only two that can affect the Emax.',
 cite:'transcript 9/28; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~39–~41, ~53–~54'},

{id:'L04-032', fg:'competitive', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'figure',
 concept:'dotted-line-drug-x-competitive', tags:['poll'], source:'both',
 stem:'The dotted line represents the DRC of the agonist alone and the solid lines represent the DRC of the agonist in the presence of increasing doses of drug "X." Drug X is most likely:',
 graph:{curves:[{label:'alone', ec:-1.5, emax:100, dashed:true}, {label:'X', ec:-0.5, emax:100}, {label:'10X', ec:0.5, emax:100}, {label:'100X', ec:1.5, emax:100}], base:0, x:'log dose agonist', y:'% of maximal response'},
 options:[
  {t:'A competitive antagonist', correct:true, why:'Right shift with the baseline and the Emax unchanged is the competitive antagonist’s signature.'},
  {t:'A full agonist', correct:false, why:'A full agonist would help and move the curve to the left.'},
  {t:'A partial agonist', correct:false, why:'A partial agonist has efficacy and would change the baseline.'},
  {t:'An irreversible antagonist', correct:false, why:'An irreversible antagonist lowers the Emax; here the maximum is unchanged.'},
  {t:'An allosteric agonist', correct:false, why:'An allosteric agonist would help the agonist and shift it to the left.'}],
 teach:'Process of elimination: drugs that help the agonist (full agonist, allosteric agonist) move it left, so they are out. A partial agonist has efficacy and would affect the baseline. An irreversible antagonist would lower the Emax. What remains, a right shift with the baseline and Emax unchanged, is the competitive antagonist. With too few shifts an irreversible antagonist may look competitive at first.',
 quote:'Who can you eliminate right away? A full agonist because they’ll move you to the left or an allosteric agonist, right?',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~55; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'In the presence of a competitive antagonist, higher agonist concentrations are required to produce a given effect, so the agonist curve is shifted to the right and high agonist concentrations overcome the inhibition.'}]},

{id:'L04-033', fg:'competitive', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'apply',
 concept:'drug-x-metoprolol', tags:['poll','metoprolol'], source:'both',
 stem:'The dotted line represents the DRC of norepinephrine alone and the solid lines represent the DRC of norepinephrine in the presence of increasing doses of drug "X." Drug X is most likely:',
 graph:{curves:[{label:'NE', ec:-1.5, emax:100, dashed:true}, {label:'X', ec:-0.5, emax:100}, {label:'10X', ec:0.5, emax:100}, {label:'100X', ec:1.5, emax:100}], base:0, x:'log dose norepinephrine', y:'% of maximal response'},
 options:[
  {t:'Metoprolol', correct:true, why:'The figure shows a competitive, reversible, surmountable antagonist, and metoprolol is the β1 competitive antagonist on the drug list.'},
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist and would shift norepinephrine to the left.'},
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist and would change the baseline.'},
  {t:'Phenoxybenzamine', correct:false, why:'Phenoxybenzamine is the only irreversible antagonist on the list; it would lower the Emax.'},
  {t:'Diazepam', correct:false, why:'Diazepam is the allosteric agonist on the list and would help the agonist.'}],
 teach:'Same classes of drugs, just different drug names: first read the figure (competitive antagonist), then match it to the drug list. Epinephrine is a full agonist, albuterol the partial agonist, phenoxybenzamine the only irreversible antagonist on the list, diazepam the allosteric agonist, and metoprolol the competitive reversible surmountable antagonist.',
 quote:'So same classes of drugs. Just different drug names.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slide ~55; transcript 9/28'},

{id:'L04-034', fg:'spare', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'apply',
 concept:'spare-receptors-irreversible', tags:[], source:'transcript',
 stem:'An agonist needs to occupy only 10% of a tissue’s receptors to produce its maximal response. An irreversible antagonist that blocks 75% of the receptors is given. Can the agonist still produce its maximal response?',
 options:[
  {t:'Yes, at a higher agonist dose', correct:true, why:'25% of the receptors remain, more than the 10% needed, so the maximum is reached once enough agonist is given to occupy them.'},
  {t:'No, the Emax falls to 25%', correct:false, why:'Emax only falls once the receptors available drop below the fraction the agonist needs.'},
  {t:'No, the response is abolished', correct:false, why:'Abolishing the response takes blockade of essentially all the receptors.'},
  {t:'Yes, at the same agonist dose', correct:false, why:'With fewer receptors available the agonist appears to have less affinity and a higher dose is required.'}],
 teach:'Agonists do not have to occupy 100% of the receptors to produce a response; the rest are spare receptors. If the agonist needs 10% and the irreversible antagonist leaves 25% or 15% available, the maximum is still reached with more agonist (the curve shifts right); once fewer than 10% remain the Emax falls, all the way to zero if all receptors are blocked.',
 quote:'Our agonists don’t have to occupy 100% of the receptors to produce a response. They only have to occupy a certain percentage of those receptors to do so.',
 cite:'transcript 9/28; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~54, ~56',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'Receptors are spare when a maximal response can be produced at an agonist concentration that does not occupy all available receptors. With spare receptors, a lower dose of irreversible antagonist can leave enough receptors for the maximal response, though a higher agonist concentration is required.'}]},

{id:'L04-035', fg:'classes', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'tell', multi:true,
 concept:'helps-or-hinders-direction', tags:[], source:'transcript',
 stem:'A full agonist’s dose–response curve is rebuilt in the presence of a second drug. Which second drugs shift the agonist’s curve to the left? Select all that apply.',
 options:[
  {t:'Another full agonist', correct:true, why:'It activates receptors on the agonist’s behalf, so less agonist is needed.'},
  {t:'An allosteric agonist that affects affinity', correct:true, why:'It makes the pocket more accessible, so the agonist binds more easily and appears more potent.'},
  {t:'A competitive antagonist', correct:false, why:'It competes for the pocket, so more agonist is needed: shift right.'},
  {t:'An inverse agonist', correct:false, why:'It competes and pulls receptors inactive, so more agonist is needed: shift right.'},
  {t:'An irreversible antagonist', correct:false, why:'It removes receptors, so more agonist is needed and the maximum falls.'}],
 teach:'Before looking at any figure, ask whether the second drug helps the agonist or makes its life more difficult. Helpers (another full agonist, an allosteric agonist) make the agonist appear more potent: shift to the left. Drugs that compete or block (competitive antagonist, inverse agonist, irreversible antagonist, allosteric antagonist affecting affinity) make it appear less potent: shift to the right. That one question eliminates most of the options.',
 quote:'would you assume that this other drug is gonna help or is gonna make the life more difficult for your agonist? And that should allow you to eliminate a lot of the answers.',
 cite:'transcript 9/28; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~3, ~22, ~42, ~50'},

{id:'L04-036', fg:'competitive', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'figure',
 concept:'competitive-antagonist-shift', tags:['poll','metoprolol'], source:'both',
 stem:'If DRC B is the DRC of norepinephrine binding to the β1 receptor alone, which DRC best represents the DRC of norepinephrine in the presence of metoprolol?',
 graph:{curves:[{label:'A', ec:-1, emax:100}, {label:'B', ec:0, emax:100}, {label:'C', ec:1, emax:55}, {label:'D', ec:1, emax:100}], base:0, x:'log dose norepinephrine', y:'% of maximal response'},
 options:[
  {t:'A', correct:false, why:'A moved left: norepinephrine was helped. Metoprolol competes for the β1 receptor, so it makes norepinephrine’s life harder, not easier.'},
  {t:'B', correct:false, why:'B is the point of reference (norepinephrine alone); an antagonist that competes for the same receptor changes the curve.'},
  {t:'C', correct:false, why:'C lost its maximum. Metoprolol is reversible, so enough norepinephrine outcompetes it and Emax is unchanged; only an irreversible or efficacy-lowering allosteric antagonist drops the Emax.'},
  {t:'D', correct:true, why:'Metoprolol is a competitive, reversible β1 antagonist: shift to the right (norepinephrine appears less potent), no change to the baseline and no change to the Emax.'},
  {t:'None of the above', correct:false, why:'D shows exactly the competitive antagonist’s signature: right shift, same baseline, same maximum.'}],
 teach:'First ask whether metoprolol helps norepinephrine or makes its life more difficult: it competes for the β1 receptor, so the curves to the left are out. Then apply the competitive antagonist rule: shift to the right, no change to the baseline (no efficacy), no change to Emax (reversible, so norepinephrine can outcompete it). A lower maximum would need an irreversible antagonist.',
 quote:'One is competitive antagonist, also known as reversible antagonists, also known as surmountable antagonists, different names for the same drug. They bind and they come off.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~3, ~45–~50, ~55; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'A competitive antagonist increases the agonist concentration required for a given response, shifting the agonist curve to the right, while the Emax for the agonist stays the same at any fixed antagonist concentration.'}]},

{id:'L04-037', fg:'irreversible', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'figure',
 concept:'irreversible-antagonist-curve', tags:['poll','phenoxybenzamine'], source:'both',
 stem:'If DRC B is the DRC of norepinephrine alone, which DRC best represents the DRC of norepinephrine in the presence of phenoxybenzamine?',
 graph:{curves:[{label:'A', ec:-1, emax:100}, {label:'B', ec:0, emax:100}, {label:'C', ec:1, emax:55}, {label:'D', ec:1, emax:100}], base:0, x:'log dose norepinephrine', y:'% of maximal response'},
 options:[
  {t:'A', correct:false, why:'A moved left, which means norepinephrine was helped; an antagonist makes its life more difficult.'},
  {t:'B', correct:false, why:'B is the point of reference (norepinephrine alone); an antagonist that removes receptors changes the curve.'},
  {t:'C', correct:true, why:'Phenoxybenzamine is the only irreversible antagonist on the drug list: covalent bonds remove receptors from the pool, so the curve shifts right and the Emax falls.'},
  {t:'D', correct:false, why:'D keeps its maximum, which is the competitive (reversible) antagonist; norepinephrine cannot outcompete a drug that never comes off.'},
  {t:'None of the above', correct:false, why:'C shows the irreversible antagonist’s two changes: shift to the right and a lower Emax.'}],
 teach:'Phenoxybenzamine forms covalent bonds that cannot be reversed under normal metabolic function, so the receptors it occupies are gone. Norepinephrine needs a higher dose for the receptors that remain (shift right) and, once too few remain, cannot reach the maximal response (Emax falls). Anything that lowers the Emax has to be an irreversible antagonist or an allosteric antagonist affecting efficacy.',
 quote:'If you see something that it lowers the Emacs, you know that has to be either an irreversible antagonist or an allosteric antagonist that affects efficacy, right? Those are the only two that can affect the Emacs.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~3, ~51–~55; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'After an irreversible antagonist occupies some proportion of receptors, the number of unoccupied receptors may be too low for the agonist, even at high concentrations, to produce the previous maximal response.'}]},

{id:'L04-038', dupOf:'L04-018', fg:'potency', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure',
 concept:'allosteric-agonist-affinity-only', tags:['poll'], source:'both',
 stem:'If DRC C is the DRC of norepinephrine binding to the β1 receptor alone, which DRC best represents the DRC of norepinephrine in the presence of an allosteric agonist that affects only the affinity?',
 graph:{curves:[{label:'A', ec:1, emax:100}, {label:'B', ec:-1, emax:60}, {label:'C', ec:0, emax:100}, {label:'D', ec:-1, emax:100}], base:0, x:'log dose norepinephrine', y:'% of maximal response'},
 options:[
  {t:'A', correct:false, why:'A moved to the right, so norepinephrine was made less potent; that is an allosteric antagonist affecting affinity, not an agonist.'},
  {t:'B', correct:false, why:'B moved left but lost its maximum, so efficacy was affected; the stem says affinity only, and no drug raises affinity while lowering efficacy.'},
  {t:'C', correct:false, why:'C is the point of reference (norepinephrine alone); an allosteric agonist changes the curve.'},
  {t:'D', correct:true, why:'An allosteric agonist helps: it makes the pocket easier to bind, so norepinephrine appears more potent (shift left) and, affinity only, the Emax is untouched.'},
  {t:'None of the above', correct:false, why:'D shows the affinity-only allosteric agonist: shift to the left with the same maximum.'}],
 teach:'Same poll, different point of reference. An allosteric agonist binds someplace else on the receptor and helps the agonist, so only curves to the left are possible. Affinity only means the ability to produce the effect is untouched: the maximum does not move. A curve whose maximum changed (B) involves efficacy; a curve to the right (A) means the agonist was made less potent.',
 quote:'Help, which means you’re gonna make the drug more potent, right? And it because it only affects affinity, you’re not affecting the ability to produce its effect, is moving to the left.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~26, ~42; transcript 9/28'},

{id:'L04-039', fg:'classes', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'figure',
 concept:'competitive-antagonist-neutral-alone', tags:['poll','metoprolol'], source:'both',
 stem:'The DRCs below represent the individual DRCs of five different drugs given on their own to a system in which half the receptors are active. DRC C most likely represents the DRC of:',
 graph:{curves:[{label:'A', ec:-1, emax:100}, {label:'B', ec:0, emax:0}, {label:'C', ec:0, emax:50}, {label:'D', ec:0.4, emax:100}, {label:'E', ec:0.6, emax:80}], base:50, x:'log dose', y:'% of maximal response'},
 options:[
  {t:'Loratadine', correct:false, why:'Loratadine is the inverse agonist; alone it brings a raised baseline down to 0%, which is curve B, not C.'},
  {t:'Metoprolol', correct:true, why:'A flat line at the baseline is a drug with affinity but no efficacy: the neutral competitive antagonist. Metoprolol is the competitive antagonist on the list.'},
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist; alone it rises from the baseline to 100%.'},
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist; alone it goes up or down from the 50% baseline to its own efficacy. (A partial agonist with exactly 50% efficacy would also sit flat, but with no more information a flat line is read as the competitive antagonist.)'}],
 teach:'Two steps: classify curve C, then match the class to the drug list. A competitive antagonist has equal affinity for active and inactive receptors and does not evoke a change, so alone it leaves the balance where it found it: 50 stays 50. Full and partial agonists go up from the baseline; an inverse agonist goes down to 0%. Metoprolol is the competitive antagonist.',
 quote:'they don’t care what the receptor is, active or inactive, they hang out with both types. They don’t discriminate as such, they don’t change the balance of the receptor activity.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~24, ~43–~44; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Receptor antagonists bind to receptors but do not activate them; their primary action is to reduce the effects of agonists that normally activate the receptor.'}]},

{id:'L04-040', fg:'partial', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'figure',
 concept:'partial-agonist-table', tags:['poll','albuterol'], source:'both',
 stem:'The DRCs below represent the individual DRCs of five different drugs. DRC B most likely represents the DRC of:',
 graph:{curves:[{label:'A', ec:0, emax:100}, {label:'B', ec:0.3, emax:60}, {label:'C', ec:-1, emax:100}, {label:'D', ec:0, emax:0}, {label:'E', ec:1, emax:100}], base:0, x:'log dose', y:'% of maximal response'},
 options:[
  {t:'Norepinephrine', correct:false, why:'Norepinephrine is a full agonist and would reach 100%, like A, C or E.'},
  {t:'Loratadine', correct:false, why:'Loratadine is the inverse agonist; with the baseline already at 0% it gives a flat line at zero, like D.'},
  {t:'Albuterol', correct:true, why:'A curve that rises but plateaus between 1% and 99% is a partial agonist, and albuterol is the partial agonist on the drug list.'},
  {t:'Metoprolol', correct:false, why:'Metoprolol has no efficacy; alone it gives a flat line at the baseline, like D.'},
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist and would reach 100%.'}],
 teach:'Classify first, then match. Curve B produces a positive effect but plateaus at 60%, which makes it a partial agonist (any maximum from 1% to 99%). On the drug list the partial agonist is albuterol, which opens the airways just enough for an asthma patient without opening them 100%. Full agonists reach 100%; drugs with no positive efficacy stay flat at a 0% baseline.',
 quote:'If your patient has asthma, albuterol, which is a partial agonist, is going to open up your airways just enough for you to breathe better in and out. You don’t have to open your lungs 100%.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~3, ~24; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists', t:'Partial agonists produce a lower response at full receptor occupancy than full agonists do.'}]},

{id:'L04-041', fg:'irreversible', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'figure',
 concept:'irreversible-antagonist-curve', tags:['poll'], source:'both',
 stem:'The dotted line represents the DRC of the agonist alone and the solid lines represent the DRC of the agonist in the presence of increasing doses of drug "X." Drug X is most likely:',
 graph:{curves:[{label:'alone', ec:-1.5, emax:100, dashed:true}, {label:'X', ec:-0.5, emax:100}, {label:'10X', ec:0.4, emax:65}, {label:'100X', ec:1, emax:25}], base:0, x:'log dose agonist', y:'% of maximal response'},
 options:[
  {t:'A full agonist', correct:false, why:'A full agonist would help and move the curve to the left.'},
  {t:'A partial agonist', correct:false, why:'A partial agonist has efficacy and would raise the baseline; here the baseline never moves.'},
  {t:'A competitive (reversible) antagonist', correct:false, why:'A competitive antagonist shifts right but is reversible, so the Emax would be unchanged; here the maximum keeps falling.'},
  {t:'An irreversible antagonist', correct:true, why:'Shift to the right, no change to the baseline and an Emax that falls with each dose: fewer receptors remain, so the agonist cannot outcompete it.'},
  {t:'An allosteric agonist', correct:false, why:'An allosteric agonist would help the agonist and shift it to the left.'}],
 teach:'Process of elimination. Helpers (full agonist, allosteric agonist) move the curve left, so they are out. A partial agonist would change the baseline. That leaves the two antagonists that shift right; only one lowers the Emax. Anything that lowers the Emax has to be an irreversible antagonist or an allosteric antagonist affecting efficacy, and only the irreversible one can abolish the response completely.',
 quote:'What could this be, uh, irreversible? It’s not changing, right? The Emacs is staying the same, so the best answer here is what? ... If you see something that it lowers the Emacs, you know that has to be either an irreversible antagonist or an allosteric antagonist that affects efficacy.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~53–~55; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'An irreversible antagonist reduces the maximal effect the agonist can achieve, and high agonist concentrations cannot overcome it.'}]},

{id:'L04-042', fg:'irreversible', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'figure',
 concept:'drug-x-phenoxybenzamine', tags:['poll','phenoxybenzamine'], source:'both',
 stem:'The dotted line represents the DRC of norepinephrine alone and the solid lines represent the DRC of norepinephrine in the presence of increasing doses of drug "X." Drug X is most likely:',
 graph:{curves:[{label:'NE', ec:-1.5, emax:100, dashed:true}, {label:'X', ec:-0.5, emax:100}, {label:'10X', ec:0.4, emax:65}, {label:'100X', ec:1, emax:25}], base:0, x:'log dose norepinephrine', y:'% of maximal response'},
 options:[
  {t:'Epinephrine (adrenaline)', correct:false, why:'Epinephrine is a full agonist and would shift norepinephrine to the left.'},
  {t:'Albuterol', correct:false, why:'Albuterol is the partial agonist; it has efficacy and would change the baseline.'},
  {t:'Phenoxybenzamine', correct:true, why:'The figure shows an irreversible antagonist (shift right, falling Emax), and phenoxybenzamine is the only irreversible antagonist on the drug list.'},
  {t:'Metoprolol', correct:false, why:'Metoprolol is a competitive, reversible antagonist: it would shift the curve right without lowering the Emax.'},
  {t:'Diazepam', correct:false, why:'Diazepam is the allosteric agonist on the list and would help norepinephrine, shifting it left.'}],
 teach:'Same figure, now with drug names. First read the class: right shift with a falling Emax is an irreversible antagonist. Then match the list: epinephrine is a full agonist, albuterol the partial agonist, metoprolol the competitive reversible surmountable antagonist, diazepam the allosteric agonist, and phenoxybenzamine the only irreversible antagonist on the list.',
 quote:'Fenoxbenzammine is the only irreversible that is on your list, and diazepam is your allosteric agonist.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~53–~55; transcript 9/28'},

{id:'L04-043', fg:'drc-basic', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'figure',
 concept:'fa-plus-fa', tags:['poll'], source:'both',
 stem:'The dotted line represents the DRC of norepinephrine alone and the solid lines represent the DRC of norepinephrine in the presence of increasing doses of drug "X." Drug X is most likely:',
 graph:{curves:[{label:'NE', ec:0, emax:100, dashed:true}, {label:'X', ec:-0.7, emax:100, base:20}, {label:'10X', ec:-1.4, emax:100, base:45}, {label:'100X', ec:-2.1, emax:100, base:70}], base:0, x:'log dose norepinephrine', y:'% of maximal response'},
 options:[
  {t:'Epinephrine', correct:true, why:'Two full agonists at the same receptor help each other: each dose of epinephrine activates receptors on norepinephrine’s behalf, raising the baseline and shifting the curve left with the same Emax.'},
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist: it would raise the baseline only to its own efficacy and, competing for the pocket, make norepinephrine’s life harder rather than easier; a baseline climbing toward 100% with a left shift is two full agonists.'},
  {t:'Phenoxybenzamine', correct:false, why:'Phenoxybenzamine is the irreversible antagonist; it would shift the curve right and lower the Emax.'},
  {t:'Metoprolol', correct:false, why:'Metoprolol competes for the receptor and would shift the curve to the right with no change to the baseline.'},
  {t:'Loratadine', correct:false, why:'Loratadine is the inverse agonist; it would shift the curve right and bring the baseline down, not up.'}],
 teach:'A drug that shifts the agonist to the left is a helper. Because drug X has positive efficacy of its own, each pretreatment dose also raises the starting point, and because both drugs are full agonists at the same receptor every curve still reaches 100%. On the drug list the full agonist is epinephrine: norepinephrine makes epinephrine more potent and epinephrine makes norepinephrine more potent.',
 quote:'now norepinephrine still goes to 100%, but it’s further to the left and the baseline has going up, right? Because levofed has efficacy, positive efficacy.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~3, ~55; Pharmacodynamics-Day_3_2026s.pdf slides ~42–~49; transcript 9/28'},

{id:'L04-044', fg:'inverse', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'ia', skill:'figure',
 concept:'fa-plus-inverse-agonist', tags:['poll','histamine','loratadine'], source:'both',
 stem:'The dotted line represents the DRC of histamine alone in a system in which half the receptors are active, and the solid lines represent the DRC of histamine in the presence of increasing doses of drug "X." Drug X is most likely:',
 graph:{curves:[{label:'H', ec:-0.5, emax:100, dashed:true}, {label:'X', ec:0.3, emax:100, base:25}, {label:'10X', ec:1, emax:100, base:8}, {label:'100X', ec:1.7, emax:100, base:1}], base:50, x:'log dose histamine', y:'% of maximal response'},
 options:[
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist; a helper would raise the baseline and shift the curve left.'},
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist with positive efficacy; it cannot bring a baseline down toward 0%.'},
  {t:'Loratadine', correct:true, why:'Baseline falling toward 0%, shift to the right and no change to the Emax: an inverse agonist that histamine can still outcompete. Loratadine is the inverse agonist on the list.'},
  {t:'Metoprolol', correct:false, why:'A competitive antagonist would shift the curve right but has no efficacy, so the baseline would not move.'},
  {t:'Phenoxybenzamine', correct:false, why:'The irreversible antagonist leaves the baseline alone and lowers the Emax; here the Emax is unchanged.'}],
 teach:'Read the three changes: baseline down (negative efficacy shuts off receptors that were active on their own), shift to the right (histamine must outcompete the drug, so it appears less potent) and no change to the Emax (the drug is reversible). Only an inverse agonist lowers the baseline, and the one inverse agonist to know is loratadine, an antihistamine.',
 quote:'So, take home message over here, it’s gonna bring the baseline down to 0, and it’s gonna shift to the right with no change to the Emax, right?',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~13–~24, ~55; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Some antagonists show inverse agonist activity: they reduce receptor activity below the basal level observed in the absence of any agonist.'}]},

{id:'L04-045', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure',
 concept:'allosteric-characteristics', tags:['poll'], source:'both',
 stem:'The dotted line represents the DRC of the agonist alone and the solid lines represent the DRC of the agonist in the presence of increasing doses of drug "X" (1×, 10× and 100×). Drug X is most likely:',
 graph:{curves:[{label:'alone', ec:0.6, emax:100, dashed:true}, {label:'1×', ec:-0.3, emax:100}, {label:'10×', ec:-1.1, emax:100}, {label:'100×', ec:-1.7, emax:100}], base:0, x:'log dose agonist', y:'% of maximal response'},
 options:[
  {t:'A full agonist', correct:false, why:'A second full agonist also shifts left, but as an orthosteric drug its shifts would be symmetrical and keep going; here the shifts are unequal and stop growing, which is allosteric.'},
  {t:'A partial agonist', correct:false, why:'A partial agonist has efficacy and would change the baseline.'},
  {t:'A competitive antagonist', correct:false, why:'A competitive antagonist makes the agonist less potent: shift to the right, in equal (symmetrical) steps.'},
  {t:'An allosteric agonist', correct:true, why:'Shift to the left with the same Emax, shifts of unequal size that stop growing at high doses (saturable) and no change to the baseline: the drug binds someplace else and only raises the agonist’s affinity.'},
  {t:'An inverse agonist', correct:false, why:'An inverse agonist makes the agonist’s life harder: shift to the right and, with active receptors present, a lower baseline.'}],
 teach:'The curve moved left, so drug X helps. Then look at the shifts: they are asymmetrical (unequal sizes) and saturable (the 100× dose barely moves the curve beyond the 10× dose), which is how an allosteric drug is recognized on a figure; an orthosteric competitor keeps shifting in equal steps. Emax is unchanged because a full agonist is already at 100%, so only affinity can be seen.',
 quote:'I can keep giving more and more of my allosteric, and he can’t go more to the left. He has maxed out all that he can do to the system.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~30–~34, ~55; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Allosteric modulators bind a site on the receptor separate from the orthosteric site bound by the agonist, so they modify receptor activity without blocking agonist binding.'}]},

{id:'L04-046', fg:'two-state', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'recap', skill:'recall',
 concept:'full-vs-partial-agonist-summary', tags:['poll'], source:'transcript',
 stem:'Which of the following is CORRECT about a full agonist?',
 options:[
  {t:'Its Emax is 100% of the system’s response', correct:false, why:'True, but not the only true statement; a full agonist gets all the way up to the maximal response.'},
  {t:'It has the highest affinity for receptors in the active state', correct:false, why:'True, but not the only true statement; full agonists love receptors that are active.'},
  {t:'If it binds a receptor that is inactive, it can activate it', correct:false, why:'True, but not the only true statement; that is its positive efficacy.'},
  {t:'It shifts the DRC of another full agonist to the left', correct:false, why:'True, but not the only true statement; two full agonists help each other.'},
  {t:'All of the above', correct:true, why:'Every statement is correct: Emax of 100%, highest affinity for active receptors, positive efficacy on inactive receptors, and a left shift of another full agonist’s curve.'}],
 teach:'Four facts that all hold for a full agonist: its Emax is 100% (it gets all the way up to the response); it has the highest affinity for receptors in the active state; if it binds a receptor that is inactive, it can activate it (positive efficacy); and it shifts the dose–response curve of another full agonist to the left because the two help each other. When every statement is right, the answer is all of the above.',
 quote:'I have all the above. Is that the correct answer? Yes, right. It’s Emacs is 100%. It gets all the way up to the response. It has the highest affinity for receptors on the active state. However, if you bind into receptors that are inactive, it can activate them, right? And a full agonist will shift the dose response curve on another full agonist to the left because they’re gonna be helping each other.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~33–~49 (lectured 9/28); transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'Full agonists shift the conformational equilibrium of receptors more strongly than partial agonists do.'}]},

{id:'L04-047', fg:'competitive', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'comp', skill:'recall',
 concept:'competitive-antagonist-shift', tags:['poll'], source:'both',
 stem:'Which statement is INCORRECT about a competitive antagonist?',
 options:[
  {t:'It has equal affinity for receptors in the active and inactive states', correct:false, why:'This is correct: the competitive antagonist is neutral (R = affinity = R*).'},
  {t:'It has affinity but no pharmacological efficacy', correct:false, why:'This is correct: it binds but does not evoke a change in the receptor.'},
  {t:'It shifts a full agonist’s DRC to the right in symmetrical steps', correct:false, why:'This is correct: a tenfold increase in antagonist needs a tenfold increase in agonist.'},
  {t:'It lowers the Emax of a full agonist', correct:true, why:'This is the incorrect statement: a competitive antagonist is reversible, so enough agonist outcompetes it and the Emax is unchanged. Only an irreversible antagonist or an allosteric antagonist affecting efficacy lowers the Emax.'}],
 teach:'The competitive antagonist is neutral in the two-state model (equal affinity for both states, affinity but no efficacy) and reversible. In the presence of a full agonist it shifts the curve to the right in symmetrical steps with no change to the baseline and no change to the Emax, because the agonist can always outcompete it. A lower Emax points to an irreversible antagonist or an allosteric antagonist affecting efficacy.',
 quote:'Everybody else is competitive. Everybody else is reversible, no change to the Emacs.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~43–~50; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Sufficiently high concentrations of agonist can surmount the effect of a given concentration of a competitive antagonist, whereas agonists cannot surmount a noncompetitive antagonist irrespective of their concentration.'}]},

{id:'L04-048', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'recall',
 concept:'noncompetitive-two-reasons', tags:['poll'], source:'both',
 stem:'An allosteric antagonist binds irreversibly to the receptor. True / False',
 options:[
  {t:'True', correct:false, why:'The allosteric antagonist binds reversibly, at another site in the receptor; it is called non-competitive because it binds someplace else, not because it never comes off.'},
  {t:'False', correct:true, why:'An allosteric antagonist binds reversibly to the receptor at another site. Only the irreversible antagonist forms covalent bonds; all allosterics are reversible.'}],
 teach:'Two different reasons give the same non-competitive label. The irreversible antagonist forms covalent bonds in the orthosteric pocket and never comes off. The allosteric antagonist binds reversibly at another site in the receptor, so the agonist cannot overcome it by competition, the shifts are asymmetrical, and there is no irreversible binding: every allosteric drug is reversible.',
 quote:'For a purpose in this class, all allosterics are reversible. There is no that forms irreversible binding.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~36, ~38–~41; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Once a receptor is bound by a noncompetitive antagonist, agonists cannot surmount the inhibition; some noncompetitive antagonists bind irreversibly, others bind reversibly at a separate allosteric site.'}]},

{id:'L04-049', dupOf:'L04-034', fg:'spare', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'irrev', skill:'apply',
 concept:'spare-receptors-irreversible', tags:[], source:'transcript',
 stem:'An agonist has to occupy 10% of a tissue’s receptors to produce its maximal response. A dose of an irreversible antagonist that blocks 75% of the receptors is given. What effect would that have on the Emax of the agonist?',
 options:[
  {t:'Would lower it', correct:false, why:'Emax only falls once fewer receptors remain than the agonist needs; 25% are still available and the agonist needs 10%.'},
  {t:'Would increase it', correct:false, why:'An irreversible antagonist has no efficacy and removes receptors; it can never raise the maximal response.'},
  {t:'No effect', correct:true, why:'25% of the receptors remain, more than the 10% required, so the maximal response is still reached; only a higher agonist dose is needed (shift to the right).'}],
 teach:'Agonists do not have to occupy 100% of the receptors to produce a response; the rest are spare receptors. If the agonist needs 10% and the irreversible antagonist leaves 25% available, the maximum is still reached with more agonist (the curve only shifts right). Once fewer than 10% remain the Emax falls, all the way to zero if every receptor is blocked.',
 quote:'if I give a dose of the irreversible that blocks 75% of the receptors, but I still have 25 available, can I still make the max response? Yes, because I want to require what? 10.',
 cite:'transcript 9/28; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~54, ~56',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'With spare receptors, a lower dose of irreversible antagonist can leave enough receptors for the maximal response, though a higher agonist concentration is required.'}]},

{id:'L04-050', fg:'efficacy', lecture:'L04', prof:'Gottlieb', tier:'new', topic:'L04', sub:'allo', skill:'figure',
 concept:'allosteric-antagonist-effects', tags:['poll'], source:'both',
 stem:'If DRC D is the DRC of an agonist alone, which curve would best represent agonist D in the presence of an allosteric antagonist that affects only the affinity of D?',
 graph:{curves:[{label:'A', ec:-1, emax:100}, {label:'B', ec:1.1, emax:55}, {label:'C', ec:1.2, emax:100}, {label:'D', ec:0, emax:100}, {label:'E', ec:0, emax:55}], base:0, x:'log dose', y:'% of maximal response'},
 options:[
  {t:'A', correct:false, why:'A moved to the left, which means the agonist was helped; an antagonist makes its life more difficult.'},
  {t:'B', correct:false, why:'B moved right and lost its maximum, so both affinity and efficacy were affected; the stem says affinity only.'},
  {t:'C', correct:true, why:'Affinity only: the agonist appears less potent (shift to the right) but can still reach the maximal response at higher doses.'},
  {t:'D', correct:false, why:'D is the point of reference; an allosteric antagonist changes the curve.'},
  {t:'E', correct:false, why:'E did not move but lost its maximum, which is an allosteric antagonist affecting efficacy only.'}],
 teach:'Whatever the allosteric agonist does, the allosteric antagonist does the opposite. Affinity only: shift to the right, Emax still reached at higher doses. Efficacy only: no shift, the maximum falls (a full agonist behaves like a partial agonist). Both: right and down. Since the stem says affinity only, any curve whose maximum changed is out, and a curve to the left was helped.',
 quote:'what would happen to the dose response curve of this agonist in the presence of an allosteric antagonist that only affects affinity? What would you predict to do? It’s gonna shift to the right. Without affecting the ability to get the max response.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf slides ~38–~42; transcript 9/28',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Negative allosteric modulators bind an allosteric site to reduce receptor activity; positive allosteric modulators bind an allosteric site to increase it.'}]}
);
