TOPICS.push({id:'L01', name:'Pharmacodynamics intro: drugs, receptors, potency', prof:'Gottlieb', lecture:'L01',
  cite:'Day 1 (9/22) — Pharmacodynamics-Day-1-2026s.pdf',
  subs:[
    {id:'intro', name:'Must know vs should know; relevance', cite:'slides ~7–~12'},
    {id:'nds', name:'Drug discovery and natural dietary supplements', cite:'slides ~13–~20'},
    {id:'potency', name:'Affinity, efficacy and potency', cite:'slides ~21–~27, ~37–~38'},
    {id:'theory', name:'Receptor theories and the two-state model', cite:'slides ~28–~29'},
    {id:'drugs', name:'Drugs, selectivity and drug classes', cite:'slides ~29–~33'},
    {id:'receptors', name:'Receptor classes', cite:'slides ~34–~36'},
    {id:'ion', name:'Ion channels', cite:'slides ~39–~48'},
    {id:'gpcr', name:'G protein–coupled receptors', cite:'slides ~49–~55'}
  ]});
QUESTIONS.push(
{id:'L01-001', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'tell',
 concept:'must-know-moa-should-know-soa', tags:['moa','soa'], source:'both',
 stem:'For drugs in this course, which pairing matches the item that must be known with the item that should be known?',
 options:[
  {t:'Must: mechanism of action (MOA); should: site of action (SOA)', correct:true, why:'The MOA (what the drug does to which receptor) is the must-know; the SOA (where the receptor is) is the should-know that lets you predict the rest.'},
  {t:'Must: site of action (SOA); should: mechanism of action (MOA)', correct:false, why:'Reverses the two tiers; the MOA is the starting point that must be known.'},
  {t:'Must: brand name; should: dose', correct:false, why:'Brand names and dose are listed as things Exam 1 will not test.'},
  {t:'Must: adverse drug reactions; should: route', correct:false, why:'Adverse reactions are predicted from MOA plus SOA; route is listed as not tested.'}],
 teach:'The must-know for every drug is its mechanism of action: which receptor it binds and whether it activates, inhibits or just binds. The should-know is the site of action, where that receptor is located. Knowing both lets you predict the effect, side effects, drug–drug interactions, contraindications and use without memorizing them.',
 quote:'there are going to be things that are going to tell you that you must know, and for this particular class in therapeutics it’s going to be the mechanism of action of the drugs... The things that you should know are going to be the sites of actions.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~7; transcript 9/22'},

{id:'L01-002', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'apply',
 concept:'metoprolol-predict-effect', tags:['metoprolol','beta1'], source:'both',
 stem:'Metoprolol is a reversible β1 receptor antagonist, and β1 receptors are located in the heart. What effect on the heart is predicted when a patient takes it?',
 options:[
  {t:'Slower heart rate', correct:true, why:'Blocking the heart’s β1 receptors slows the heart rate; this is the prediction he asked the class to make.'},
  {t:'Faster heart rate', correct:false, why:'Treats an antagonist as if it were an agonist at β1.'},
  {t:'No change in heart rate', correct:false, why:'Ignores that the blocked receptor is located in the heart.'},
  {t:'Increased urination', correct:false, why:'Confuses the β1 blocker with the thiazide diuretic example.'}],
 teach:'If you know the mechanism of action (β1-selective antagonist) and the site of action (β1 receptors in the heart), the effect follows: the heart rate slows. The same reasoning predicts side effects such as bradycardia.',
 quote:'If I give you metoprolol, which is a beta 1 selective antagonist, and beta ones are in the heart, what kind of effect is it going to produce? ... Slow down the heart rate.',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2 Major autonomic receptor types; Table 6–3 Direct effects of autonomic nerve activity; Table 6–5', t:'Table 6–2 places beta-1 (β1) adrenoceptors on postsynaptic effector cells “especially heart”, where ligand binding stimulates adenylyl cyclase and raises cyclic adenosine monophosphate (cAMP). Table 6–3 lists the sinoatrial node as accelerated by sympathetic activity through β1 and β2 receptors, and Table 6–5 describes a β-blocker (propranolol) as a drug that binds β receptors and prevents their activation. Removing the sympathetic acceleration at the sinoatrial node is what a β1 antagonist does, so the predicted effect is a slower heart rate.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~9; transcript 9/22'},

{id:'L01-003', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'apply', multi:true,
 concept:'metoprolol-predict-adr', tags:['metoprolol','adr'], source:'both',
 stem:'Metoprolol is a β1 receptor antagonist; its sites of action include the heart, kidneys and brain. Which adverse drug reactions (ADRs) fit this mechanism and site? Select all that apply.',
 options:[
  {t:'Bradycardia', correct:true, why:'Blocking β1 in the heart can slow it too much; bradycardia is listed as an ADR.'},
  {t:'Fatigue', correct:true, why:'Fatigue is listed as an ADR and he ties it to β1 receptors in the brain.'},
  {t:'Tachycardia', correct:false, why:'A β1 antagonist slows the heart; tachycardia reverses the effect.'},
  {t:'Hyponatremia', correct:false, why:'Hyponatremia was the thiazide diuretic example, from losing sodium.'}],
 teach:'Metoprolol blocks β1 receptors. In the heart that slows the rate, and too much slowing is bradycardia. β1 receptors are also in the brain, which he links to fatigue and patients forgetting things.',
 quote:'ADR - Bradycardia, fatigue, etc…',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2 Major autonomic receptor types; Integration of Cardiovascular Function', t:'Table 6–2 lists the typical locations of β1 adrenoceptors as postsynaptic effector cells “especially heart, lipocytes, brain”, plus presynaptic nerve terminals and the juxtaglomerular apparatus of the kidney. Because the sinoatrial node is accelerated through β1 receptors (Table 6–3), blocking them slows the heart, and slowing it too far is bradycardia. In the intact resting human the heart rate is already dominated by parasympathetic (vagal) tone, which holds it at 70–80 beats per minute, so removing sympathetic drive lowers it further.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~9; transcript 9/22'},

{id:'L01-004', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'recall',
 concept:'drugs-alter-ongoing-system', tags:['definition'], source:'both',
 stem:'Which statement describes what drugs do to a biological system?',
 options:[
  {t:'They alter an ongoing function', correct:true, why:'Drugs change an ongoing physiological or pathological function; they initiate, inhibit or modulate.'},
  {t:'They create a new physiological pathway', correct:false, why:'He states drugs do not create anything new.'},
  {t:'They only block receptors', correct:false, why:'Drugs can also initiate or modulate a signal.'},
  {t:'They only mimic hormones', correct:false, why:'Some drugs mimic body products; others are unique. Either way they alter an existing system.'}],
 teach:'Drugs are chemical substances that alter an ongoing physiological or pathological function by interacting with components of the biological system. They can initiate, inhibit or modulate a signal, but they do not create a new pathway.',
 quote:'drugs don’t create anything new, they just change whatever is happening in the body.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'The Nature of Drugs; Pharmacology (opening definition)', t:'A drug is defined “in the most general sense” as any substance that brings about a change in biologic function through its chemical actions. In most cases the drug molecule interacts as an agonist (activator) or antagonist (inhibitor) with a target molecule that already plays a regulatory role in the biologic system; that target is called a receptor. Pharmacology is defined as the study of substances that bind regulatory molecules and thereby activate or inhibit normal body processes, which is the same idea as altering an ongoing function rather than creating a new one.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~11, ~31; transcript 9/22'},

{id:'L01-005', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'recall',
 concept:'receptor-message-physiological-response', tags:['receptor'], source:'both',
 stem:'Norepinephrine binds β1 receptors and cardiac output increases. In receptor terms, what is the increase in cardiac output?',
 options:[
  {t:'The physiological response', correct:true, why:'The message a drug–receptor interaction creates is seen as the physiological response.'},
  {t:'The affinity of norepinephrine for β1', correct:false, why:'Affinity is how well the drug binds, not the response produced.'},
  {t:'The site of action', correct:false, why:'The site of action is where the receptor is (the heart), not the response.'},
  {t:'The apparent potency', correct:false, why:'Apparent potency concerns how much drug reaches the site; it is not the response itself.'}],
 teach:'Receptors sense signals such as hormones, neurotransmitters and drugs. The message the receptor creates after binding is what we observe as the physiological response, for example increased cardiac output when norepinephrine binds β1.',
 quote:'The message that the receptor creates is the physiological response.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Pharmacodynamic Principles; Receptors and Inert Binding Sites', t:'Drug binding is only the first step in a sequence: drug plus receptor forms a drug–receptor complex, which may act through a coupling molecule and an effector molecule, and the final change in function is accomplished by that effector mechanism. To count as a receptor, an endogenous molecule must change its function upon binding so that the function of the cell or tissue is altered; binding to a nonregulatory molecule such as plasma albumin produces no detectable change and is called an inert binding site. The rise in cardiac output is the altered function at the end of that sequence, the effect, not the binding itself.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~11; transcript 9/22'},

{id:'L01-006', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'apply',
 concept:'curare-not-absorbed', tags:['curare','absorption'], source:'both',
 stem:'Curare (Strychnos toxifera) is a very large, positively charged molecule used as a paralytic agent. Why does eating the plant produce no effect?',
 options:[
  {t:'It cannot be absorbed', correct:true, why:'A large, charged molecule is not absorbed, so eating it does nothing.'},
  {t:'It has no affinity', correct:false, why:'Curare paralyzes fish through the gills, so it does act once it reaches its target.'},
  {t:'It is a partial agonist', correct:false, why:'Its lack of oral effect is about absorption, not intrinsic activity.'},
  {t:'Stomach acid adds a charge', correct:false, why:'The charge is a property of the molecule itself.'}],
 teach:'Curare is a large molecule with a positive charge, so it is not absorbed when eaten. It was discovered when fish, whose gills are outside the body, became paralyzed and floated up. It was later used as a paralyzing agent for surgery.',
 quote:'if you eat this plant, nothing happens because karate is a very large positive charge molecule. What does that tell you to be large and have a charge to it, positive or negative? You can’t absorb, right?',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Drug Size; Ionization of Weak Acids and Weak Bases', t:'Most drugs have molecular weights between 100 and 1000; molecules much larger than 1000 do not diffuse readily between body compartments and often must be given directly into the compartment where they act. Separately, the electrostatic charge of an ionized molecule attracts water dipoles and makes it water-soluble and lipid-insoluble, so ionization may markedly reduce permeation across membranes, and quaternary amines are permanently charged and always in the poorly lipid-soluble form. A large, permanently charged molecule therefore fails both the size and the charge requirements for absorption from the gut.'},
         {src:'Katzung 16e, Ch. 6', sec:'Table 6–5 Steps in autonomic transmission', t:'Tubocurarine is listed as acting at neuromuscular end plates, where it prevents activation of nicotinic receptors. That is the paralytic mechanism once the drug reaches skeletal muscle; the missing oral effect is a matter of the drug never reaching that site.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~14; transcript 9/22'},

{id:'L01-007', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'recall', multi:true,
 concept:'nds-regulation', tags:['nds'], source:'both',
 stem:'Which statements about natural dietary supplements (NDS) are correct? Select all that apply.',
 options:[
  {t:'They are regulated as food', correct:true, why:'NDS are regulated as food, not as drugs.'},
  {t:'They have less FDA oversight', correct:true, why:'Because they are not drugs, the FDA oversees them less; they stay on the market until they cause harm.'},
  {t:'Labels cannot claim they cure', correct:true, why:'Labels cannot state that the product treats, cures, diagnoses or prevents a disease.'},
  {t:'They are tested like Rx drugs', correct:false, why:'The label states the claims have not been evaluated by the FDA.'},
  {t:'Being natural makes them safe', correct:false, why:'He answered this with cyanide and lead: natural does not mean safe.'}],
 teach:'NDS are regulated as food, so they receive less FDA oversight and remain on the market until they cause harm. Their labels cannot claim to treat, cure, diagnose or prevent disease. Natural does not mean safe.',
 quote:'when we look at natural dietary supplements, they are treated as food, which means they have less oversight by the FDA. Which means that until they cause harm, they’re still in the market',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Table 1–6 Some major legislation pertaining to drugs in the USA; The History of Pharmacology', t:'The Dietary Supplement Health and Education Act of 1994 established standards for dietary supplements but prohibited full Food and Drug Administration (FDA) review of supplements and botanicals as drugs; its labeling rules classify them as part of the food supply while allowing unregulated advertising. Substances promoted for health, but not promoted specifically as drugs, have thereby avoided meeting FDA standards. It also states that all substances can be toxic under some circumstances and that the chemicals in botanicals are no different from those in manufactured drugs except for a greater proportion of impurities.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~15–~16; transcript 9/22'},

{id:'L01-008', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'recall',
 concept:'nds-incorrect-poll', tags:['nds','poll'], source:'both',
 stem:'Which statement is INCORRECT about natural dietary supplements (NDS)?',
 options:[
  {t:'Most NDS labels state they cure diseases', correct:false, why:'This is incorrect, but so are the other statements; select the option that covers all of them.'},
  {t:'NDS are tested by the FDA like Rx drugs', correct:false, why:'This is incorrect, but it is not the only incorrect statement.'},
  {t:'NDS have been used for centuries, so they are safe', correct:false, why:'This is incorrect, but it is not the only incorrect statement.'},
  {t:'NDS are natural, so interaction risk is low', correct:false, why:'This is incorrect, but it is not the only incorrect statement.'},
  {t:'All of the above', correct:true, why:'Every statement is incorrect: labels cannot claim cures, NDS are not FDA-tested like drugs, and natural or old does not mean safe or interaction-free.'}],
 teach:'All four statements are wrong. NDS labels cannot claim to cure, they are not tested by the FDA like prescription drugs, long use does not prove safety, and herbals can interact with prescription and OTC drugs. His test tip: if two answers other than a select-all are definitely correct, choose all of the above.',
 quote:'90% says all the above. What is the correct answer? I would say all the above, right?',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'The History of Pharmacology (general principles); Table 1–6', t:'Three principles to remember: all substances can under certain circumstances be toxic; the chemicals in herbs and plant extracts (“nutraceuticals”) are no different from the chemicals in manufactured drugs except for more impurities; and all dietary supplements should meet the same standards of efficacy and safety as conventional drugs, ideally through the same randomized controlled trials. Under the Dietary Supplement Health and Education Act of 1994 they do not: full Food and Drug Administration (FDA) review of supplements as drugs is prohibited and advertising is unregulated. Each of the four statements contradicts one of these points, which is why none of them is correct.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~18; transcript 9/22'},

{id:'L01-009', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'recall',
 concept:'fish-oil-evidence', tags:['nds','fish-oil'], source:'both',
 stem:'Which statement about omega-3 fish oil is correct?',
 options:[
  {t:'Lowers triglycerides; reduces cardiac death', correct:true, why:'Omega-3s lower triglycerides and reduce the risk of cardiac death, though not the risk of a cardiovascular event.'},
  {t:'Reduces the risk of having a cardiovascular event', correct:false, why:'The slide states omega-3s do not reduce the risk of a cardiovascular event.'},
  {t:'Has no role in fetal development', correct:false, why:'Omega-3s are important for fetal development.'},
  {t:'Has no effect on triglycerides', correct:false, why:'Omega-3s can lower triglycerides.'}],
 teach:'Omega-3s are important for fetal development and can lower triglycerides. They do not reduce the risk of a cardiovascular event, but appear to reduce the risk of cardiac death if an event occurs.',
 quote:'Although omega-3s can lower triglycerides, they don’t reduce the risk of cardiovascular event but reduce the risk of Cardiac death.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~19; transcript 9/22'},

{id:'L01-010', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'apply',
 concept:'nds-report-interactions', tags:['nds','ddi'], source:'both',
 stem:'A patient on several prescription drugs says she takes an herbal supplement but did not mention it because it is natural. What is the concern?',
 options:[
  {t:'The herbal can interact with her drugs', correct:true, why:'Herbals have active ingredients that can interact with prescription and OTC drugs.'},
  {t:'Herbals lack active ingredients', correct:false, why:'He cites aspirin, digoxin and warfarin as drugs from natural sources; herbals do have active ingredients.'},
  {t:'Only prescription drugs can cause interactions', correct:false, why:'Herbals can interact with both prescription and OTC drugs.'},
  {t:'Herbals are fully FDA-tested', correct:false, why:'Supplements have not been fully tested.'}],
 teach:'Most patients do not consider supplements pertinent and do not report them. Herbals have active ingredients, can interact with prescription or OTC drugs, and can produce side effects because they have not been fully tested.',
 quote:'Herbal can interact with prescription/OTC drugs',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'The History of Pharmacology (general principles); Confounding Factors in Clinical Trials; The Food & Drug Administration', t:'The chemicals in botanicals are no different from the chemicals in manufactured drugs apart from a greater proportion of impurities, so an herbal product carries active chemicals like any drug. In describing clinical trials it notes that other drugs and some foods alter the pharmacokinetics of many drugs, and that a proper pharmacologic history must include over-the-counter drugs and “supplements”. It also reports that so-called food supplements have been found to contain active drugs, for example sildenafil analogs in “energy food” supplements.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~20; transcript 9/22'},

{id:'L01-011', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'apply',
 concept:'dose-selectivity', tags:['selectivity','metoprolol'], source:'transcript',
 stem:'Metoprolol is β1-selective at lower doses. What happens as the dose rises above about 200 mg?',
 options:[
  {t:'It starts to affect β2 receptors', correct:true, why:'The larger the dose, the less selective the drug; above about 200 mg metoprolol affects β2.'},
  {t:'It becomes more β1-selective', correct:false, why:'Reverses the rule; selectivity falls as dose rises.'},
  {t:'It stops binding the β1 receptors entirely', correct:false, why:'It still binds β1; it adds binding at β2.'},
  {t:'It becomes a β1 agonist', correct:false, why:'Dose changes selectivity, not whether the drug activates or blocks.'}],
 teach:'One rule he gave: the larger the dose, the less selective the drug. Starting with the smallest dose that gives the desired effect keeps the drug at one receptor. Metoprolol is β1-selective up to about 200 mg and begins to affect β2 above that.',
 quote:'Metoprolol is a beta 1 selective up to about 200 mg. Once you go above 200, you start to affect the beta 2s, so you start to lose selectivity',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~21; transcript 9/22'},

{id:'L01-012', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'recall', multi:true,
 concept:'potency-determinants', tags:['potency','affinity','efficacy'], source:'both',
 stem:'The potency of a drug depends on which factors? Select all that apply.',
 options:[
  {t:'Affinity', correct:true, why:'Affinity is one of the two factors intrinsic to the drug.'},
  {t:'Efficacy', correct:true, why:'Efficacy is the other factor intrinsic to the drug.'},
  {t:'The individual or tissue', correct:true, why:'Tissues differ in receptor expression, which changes potency.'},
  {t:'The brand name', correct:false, why:'Brand names have no role in potency and are not tested on Exam 1.'},
  {t:'The drug’s chemical class name', correct:false, why:'A class name is a label; potency depends on the individual or tissue, affinity and efficacy.'}],
 teach:'Potency depends on three things: the individual (tissue, organ or cell line, which differ in receptor expression), and two properties intrinsic to the drug, affinity and efficacy.',
 quote:'the potency of a drug is going to be dependent on three major things. One is... the individual, the tissue... But the two things that are intrinsic to the drug is going to be the affinity and the efficacy of that drug.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~21; transcript 9/22'},

{id:'L01-013', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'recall',
 concept:'affinity-chemical-bonds', tags:['affinity','poll'], source:'both',
 stem:'Affinity of a drug for the receptor is dependent on:',
 options:[
  {t:'The type of chemical bonds it makes', correct:true, why:'Covalent, hydrogen, ionic and van der Waals bonds give stronger or weaker binding, which sets affinity.'},
  {t:'The route of administration of the drug', correct:false, why:'Route changes how much drug reaches the site (apparent potency), not how well it binds.'},
  {t:'The first-pass effect in the liver', correct:false, why:'First-pass metabolism lowers bioavailability; it is pharmacokinetics, not binding.'},
  {t:'Whether it activates the receptor', correct:false, why:'Changing receptor activity is efficacy; a drug can have affinity with no activity.'}],
 teach:'Affinity is how well a drug attaches to the receptor and stays bound. The kind of bonds formed (covalent, hydrogen, ionic, van der Waals) makes binding stronger or weaker.',
 quote:'depending on what kind of bonds they form, covalent bonds, hydrogen bonds, ion bonds, van der Waal bonds, they may have stronger or weaker binding',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Drug Reactivity & Drug-Receptor Bonds', t:'Drugs interact with receptors through chemical bonds of three major types: covalent, electrostatic and hydrophobic. Covalent bonds are very strong and often not reversible under biologic conditions (the acetyl group of aspirin stays bound to cyclooxygenase until new enzyme is made); electrostatic bonds range from relatively strong ionic linkages to weaker hydrogen bonds and very weak van der Waals forces, and are much more common than covalent bonds; hydrophobic bonds are usually quite weak. Drugs binding through weak bonds are generally more selective, because weak bonds require a very precise fit to the receptor.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~37; transcript 9/22'},

{id:'L01-014', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'tell',
 concept:'efficacy-definition', tags:['efficacy','poll'], source:'both',
 stem:'Efficacy:',
 options:[
  {t:'Is the ability of a drug to bind and stay bound to a receptor', correct:false, why:'This defines affinity, not efficacy.'},
  {t:'Is the ability of a cell to increase its number of receptors', correct:false, why:'Receptor number is a tissue factor, not the drug’s efficacy.'},
  {t:'Is the ability of a drug to change receptor activity/state', correct:true, why:'Efficacy is the drug’s effect on the receptor: positive (activating) or negative (shutting down).'},
  {t:'Is the ability of a drug to be absorbed at the level of the GI', correct:false, why:'Absorption is pharmacokinetics.'}],
 teach:'Affinity is binding and staying bound; efficacy is what the bound drug does to the receptor. Drugs that activate receptors have positive efficacy; drugs that shut receptors down have negative efficacy.',
 quote:'Some drugs are going to be activating receptors so they have positive efficacy. Others are going to be shutting down the receptors so they have negative efficacy.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Agonists, Partial Agonists, and Inverse Agonists; Receptors and Inert Binding Sites', t:'Full agonists shift almost the whole receptor pool into the active drug-bound (Ra–D) form; partial agonists bind the same receptors but do not stabilize the active conformation as fully, leaving a fraction in the inactive drug-bound (Ri–D) pool, and are said to have low intrinsic efficacy. Inverse agonists stabilize the inactive form and reduce constitutive activity, producing effects opposite to agonists. Intrinsic efficacy is independent of affinity as usually measured, which separates the ability to change receptor state (efficacy) from the ability to bind (affinity).'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~38; transcript 9/22'},

{id:'L01-015', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'tell',
 concept:'pharmacological-vs-apparent-potency', tags:['potency','pk'], source:'both',
 stem:'Two patients get the same drug. One takes it orally and has first-pass metabolism; the other gets it IV. Which type of potency accounts for the difference in effect?',
 options:[
  {t:'Apparent potency', correct:true, why:'Apparent potency includes pharmacokinetics: route, absorption, metabolism, elimination, age and DDIs.'},
  {t:'Intrinsic activity', correct:false, why:'Intrinsic activity is a drug property from Ariens’ theory, unchanged by route.'},
  {t:'Affinity', correct:false, why:'Affinity is fixed by the drug’s bonds with the receptor, not by the route.'},
  {t:'Efficacy', correct:false, why:'Efficacy is the drug’s effect on receptor state, not how much reaches it.'}],
 teach:'Pharmacological potency comes from the drug–receptor side: tissue sensitivity, receptor number and activity, affinity and efficacy. Apparent potency adds pharmacokinetics: age, absorption, distribution, elimination and DDIs, which set how much drug reaches the site of action. IV has 100% bioavailability and bypasses first-pass metabolism.',
 quote:'pharmokinetics is going to be affecting how much of the drug gets to the site of action. Because that’s how it’s going to produce its effects.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Drug-Body Interactions; Pharmacokinetic Principles; Drug Screening', t:'The actions of the drug on the body are pharmacodynamic processes; the actions of the body on the drug are pharmacokinetic processes, which govern absorption, distribution and elimination and are of great practical importance in choosing and administering a drug for a particular patient. A drug given by mouth must be absorbed into the blood from its site of administration and distributed to its site of action, permeating the barriers between compartments, whereas only rarely can a drug be applied directly to its target. In drug screening, oral administration studies may show a drug to be poorly absorbed or rapidly metabolized in the liver, prompting changes to improve bioavailability. The difference between the oral and intravenous patients lies on this pharmacokinetic side.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~23, ~27; transcript 9/22',
 note:'Slide ~27 lists absorption, distribution, elimination, age and DDIs under apparent potency. In the transcript he answers yes to whether ADME affects pharmacological potency and says pharmacological potency depends on absorption and metabolism. The slide grouping (apparent potency) is keyed.'},

{id:'L01-016', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'recall',
 concept:'potency-correct-poll', tags:['potency','poll'], source:'both',
 stem:'Which statement is CORRECT?',
 options:[
  {t:'Route of administration can affect a drug’s potency', correct:false, why:'True, but not the only true statement.'},
  {t:'Drugs can bind one receptor with higher affinity than others', correct:false, why:'True, but not the only true statement.'},
  {t:'Ability to reach the site of action can affect potency', correct:false, why:'True, but not the only true statement.'},
  {t:'Ion channels are typically expressed on cell membranes', correct:false, why:'True, but not the only true statement.'},
  {t:'All the above', correct:true, why:'Every statement is correct; the class answered 100% all the above.'}],
 teach:'Route and the ability to reach the site of action change apparent potency; drugs bind some receptors with higher affinity than others; ion channels are transmembrane proteins on the cell membrane.',
 quote:'We have 100%, says that it is all the above, uh, that’s the correct answer, right?',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~24; transcript 9/22'},

{id:'L01-017', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'apply',
 concept:'safety-vs-efficacy', tags:['efficacy','poll'], source:'both',
 stem:'If your patient has fungal pneumonia, which would you choose?',
 options:[
  {t:'A very efficacious drug that is less safe', correct:true, why:'A very safe drug that does nothing leaves the patient to die of fungal pneumonia.'},
  {t:'A very safe drug that is not very efficacious', correct:false, why:'A safe topical antifungal would not treat fungal pneumonia.'},
  {t:'Neither drug', correct:false, why:'Leaving fungal pneumonia untreated does not protect the patient.'},
  {t:'Either one; they are equal', correct:false, why:'He ranks efficacy first when the safe drug does not work.'}],
 teach:'His answer: choose the efficacious drug if nothing safer works, because a safe drug that does not work wastes the patient’s health and money. If two drugs have equal efficacy, pick the safer one. Cancer drugs are the same case: toxic but needed.',
 quote:'Perhaps if I’m your patient, please choose the most efficacious drug. If there’s nothing else that is safer than that',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Preclinical Safety & Toxicity Testing; The Food & Drug Administration; New Drug Development', t:'“All chemicals are toxic in some individuals at some dose”, and no chemical can be certified as completely safe; the objective is to estimate the risk of a drug candidate “in the context of therapeutic needs” and the likely duration of use. Highly toxic drugs that are nevertheless considered valuable in lethal diseases may be approved for restricted use by specially trained practitioners. Thalidomide is the example given: despite its fetal toxicity it is now approved for limited use as an immunoregulatory agent and for certain forms of leprosy, because even the most serious toxicities may be avoided or managed if understood. A drug with no efficacy against a lethal infection offers no therapeutic benefit to weigh against its safety.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~25–~26; transcript 9/22'},

{id:'L01-018', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'tell', multi:true,
 concept:'pharmacological-potency-factors', tags:['potency'], source:'slide',
 stem:'In relating dose to effect, which factors belong to pharmacological potency rather than apparent potency? Select all that apply.',
 options:[
  {t:'Tissue sensitivity', correct:true, why:'Listed under pharmacological potency: how sensitive the tissue is belongs to the drug–receptor (pharmacodynamic) side.'},
  {t:'Receptor number', correct:true, why:'Listed under pharmacological potency, together with receptor activity; how many receptors the tissue expresses sets how much response the drug can produce.'},
  {t:'Affinity', correct:true, why:'Listed under pharmacological potency, together with efficacy; affinity and efficacy are the two factors intrinsic to the drug.'},
  {t:'Absorption', correct:false, why:'Absorption is a pharmacokinetic factor under apparent potency.'},
  {t:'Age', correct:false, why:'Age is listed under apparent potency.'},
  {t:'Elimination by the kidney or liver', correct:false, why:'Elimination is a pharmacokinetic factor under apparent potency.'}],
 teach:'Pharmacological potency (pharmacodynamics): tissue sensitivity, receptor number, receptor activity, affinity, efficacy. Apparent potency (pharmacokinetics): age, absorption, distribution, elimination, DDIs.',
 quote:'Apparent Potency - Age - Absorption - Distribution - Elimination - DDI; Pharmacological Potency - Tissue sensitivity - Receptor # - Receptor Activity - Affinity - Efficacy',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Drug-Body Interactions; Confounding Factors in Clinical Trials', t:'Drug–body interactions fall into two classes: pharmacodynamic processes, the actions of the drug on the body, and pharmacokinetic processes, the actions of the body on the drug. Pharmacokinetic processes govern absorption, distribution and elimination, and a patient with impaired renal function is given as the case where they decide drug choice; age, gender and pregnancy are also said to influence the pharmacokinetics of some drugs. Absorption, elimination and age therefore fall on the pharmacokinetic side, while tissue sensitivity, receptor number and affinity concern the drug–receptor interaction described under pharmacodynamics.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~27',
 note:'In the transcript he says pharmacological potency depends on absorption, metabolism and age; the slide places these under apparent potency. The slide grouping is keyed.'},

{id:'L01-019', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'recall',
 concept:'clark-occupancy', tags:['theory','affinity'], source:'both',
 stem:'Under the occupancy theory, why does a partial agonist give only part of the maximal response?',
 options:[
  {t:'It occupies only part of the receptors', correct:true, why:'In the occupancy theory response depends on how many receptors are occupied; a partial agonist occupies a percentage.'},
  {t:'It shifts receptors to inactive', correct:false, why:'Shifting to the inactive state is negative efficacy from the later two-state model.'},
  {t:'It has zero intrinsic activity', correct:false, why:'Zero intrinsic activity is Ariens’ antagonist.'},
  {t:'It binds an allosteric site on the receptor', correct:false, why:'Allosteric binding is not part of the occupancy theory.'}],
 teach:'The first theory was based only on affinity: the more receptors a drug occupies, the greater the response. A full agonist occupies all receptors for 100% of the response; a partial agonist occupies, for example, 70% and gives 70%. It introduced affinity and full versus partial agonists but could not explain how all drugs work.',
 quote:'a full agonist will produce 100% of the response as a partial may produce a 70% of the response because it can only occupy 70% of the receptors, right? So it’s based on occupancy.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Agonists, Partial Agonists, and Inverse Agonists', t:'Partial agonists are described as drugs that bind the same receptors as full agonists and activate them in the same way, “but do not evoke as great a response, no matter how high the concentration”. In the two-state model of Figure 1–3 this is explained by the partial agonist not stabilizing the active conformation as fully as a full agonist, so a significant fraction of drug-bound receptors stays inactive; such drugs are said to have low intrinsic efficacy. That later model attributes the submaximal response to the fraction of bound receptors held in the inactive state rather than to the fraction of receptors occupied, which is the older occupancy explanation. Because they occupy the same site, partial agonists can also block full agonists: pindolol acts as an agonist when no full agonist is present and as an antagonist when epinephrine is present.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22'},

{id:'L01-020', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'recall',
 concept:'intrinsic-activity-antagonist', tags:['theory','antagonist'], source:'both',
 stem:'Changing one functional group changed a drug from a full agonist to one that binds but produces no effect. What is its intrinsic activity?',
 options:[
  {t:'Zero', correct:true, why:'An antagonist has affinity but zero intrinsic activity; it binds and does nothing to the receptor.'},
  {t:'One', correct:false, why:'An intrinsic activity of one (100%) is a full agonist.'},
  {t:'Between zero and one', correct:false, why:'That range is a partial agonist.'},
  {t:'Negative', correct:false, why:'Negative efficacy came later with the two-state model, not from intrinsic activity.'}],
 teach:'Changing R1 or R2 functional groups could turn a full agonist into a partial agonist or into something with no effect. This led to intrinsic activity: full agonist 100%, partial agonist 1–99%, antagonist zero. Antagonists have affinity but do nothing to the receptor.',
 quote:'my antagonist, there are zero intrinsic activity. They have affinity, they can bind the receptor, but they don’t do anything to the receptor.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Agonists, Partial Agonists, and Inverse Agonists; Types of Drug-Receptor Interactions', t:'Conventional antagonists are described as having equal affinity for the inactive and active receptor forms, so they fix the drug-bound fractions in the same proportions as in the absence of drug: “no change in activity will be observed, so the drug will appear to be without effect”. Their presence at the receptor site still blocks access of agonists, which is termed neutral antagonism. Pharmacologic antagonists such as atropine compete with and prevent binding by agonists, and their action can be overcome by increasing the agonist dose. A drug that binds but changes nothing about receptor activity is what an intrinsic activity of zero describes.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22'},

{id:'L01-021', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'recall',
 concept:'two-state-model-l', tags:['theory','two-state'], source:'both',
 stem:'In the two-state model (D + R ⇄ DR resting; D + R* ⇄ DR* active), what does the constant L determine?',
 options:[
  {t:'How likely a receptor is active vs inactive', correct:true, why:'L sets how likely a receptor is found in the inactive versus the active state without drug.'},
  {t:'How tightly the drug binds', correct:false, why:'Binding strength is affinity, not L.'},
  {t:'How many receptors the drug is able to occupy', correct:false, why:'Occupancy is Clark’s idea.'},
  {t:'How much drug reaches the site', correct:false, why:'That is pharmacokinetics.'}],
 teach:'In the two-state model receptors exist as active or inactive. L determines how likely a receptor is in the inactive versus the active state, and cells can move receptors back and forth and change receptor number. Drugs bound to the receptor shift this balance.',
 quote:'this L constant over here. Determines how likely a receptor should be found on the inactive versus the active state.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Agonists, Partial Agonists, and Inverse Agonists (Figure 1–3)', t:'In the Figure 1–3 model the receptor can assume two conformations: an inactive form (Ri) that produces no effect even when a drug is bound, and an active form (Ra) that can activate downstream mechanisms. Thermodynamic considerations mean some of the receptor pool is in the Ra form some of the time even without agonist, producing constitutive or basal activity; in the absence of drugs the two isoforms are in equilibrium and the Ri form is favored. The constant asked about sets that drug-free balance between inactive and active receptors, and drugs act by shifting it: agonists have much higher affinity for Ra and inverse agonists for Ri.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22'},

{id:'L01-022', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'apply',
 concept:'negative-efficacy-inverse-agonist', tags:['two-state','inverse-agonist'], source:'both',
 stem:'A drug binds active receptors and shifts them toward the inactive state. Which kind of drug does the two-state model use this to explain?',
 options:[
  {t:'Inverse agonist', correct:true, why:'Shifting receptors to the inactive state is negative efficacy, which explains inverse agonists.'},
  {t:'Full agonist', correct:false, why:'A full agonist has positive efficacy, shifting receptors to active.'},
  {t:'Partial agonist', correct:false, why:'A partial agonist has positive efficacy.'},
  {t:'Antagonist', correct:false, why:'An antagonist binds but does not change receptor state.'}],
 teach:'Drugs that shift receptors toward the active state have positive efficacy; drugs that shift them toward the inactive state have negative efficacy. The two-state model lets us explain inverse agonists.',
 quote:'Are the drugs bound to receptors who are active and shift them to the negative or inactive state, does have a negative efficacy... And that allows us to explain inverse agonists',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Agonists, Partial Agonists, and Inverse Agonists', t:'A drug with much stronger affinity for the inactive (Ri) than the active (Ra) receptor state stabilizes a large fraction in the inactive drug-bound pool, reduces any constitutive activity, and produces effects opposite to those of conventional agonists; such drugs are termed inverse agonists. The example given is the gamma-aminobutyric acid type A (GABA-A) receptor chloride channel: benzodiazepine agonists enhance chloride entry and sedate, the neutral antagonist flumazenil reverses that sedation, and inverse agonists cause anxiety and agitation, the inverse of sedation. Inverse agonists have also been found for β adrenoceptors and histamine H1 and H2 receptors.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22'},

{id:'L01-023', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'tell',
 concept:'loratadine-vs-diphenhydramine', tags:['selectivity','histamine'], source:'both',
 stem:'Loratadine and diphenhydramine both act at the histamine H1 receptor. What separates them?',
 options:[
  {t:'Loratadine is selective; diphenhydramine is not', correct:true, why:'Loratadine is a selective H1 inverse agonist; diphenhydramine also binds H2 and muscarinic receptors.'},
  {t:'Diphenhydramine is selective; loratadine is not', correct:false, why:'Reverses the pair.'},
  {t:'Both are selective for H1', correct:false, why:'Diphenhydramine binds H1, H2 and muscarinic receptors.'},
  {t:'Neither binds the H1 receptor', correct:false, why:'Both bind H1.'}],
 teach:'Drugs can be selective or non-selective. Loratadine is a selective H1 inverse agonist. Diphenhydramine binds H1, H2 and muscarinic receptors and is very non-selective; it is the ingredient in nighttime products and puts 9 of 10 people to sleep.',
 quote:'What is loratadine? It’s Claritin, which is a selective H1 inverse agonist... What about diphenhydramine?... Benadryl not only binds to the H1, it binds to the H2. It binds to muscarinic receptors. It’s very non-selective.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Drug Size; Drug Reactivity & Drug-Receptor Bonds; Agonists, Partial Agonists, and Inverse Agonists', t:'To have a good fit to only one type of receptor, a drug molecule must be sufficiently unique in shape, charge and other properties to prevent its binding to other receptors, and drugs that bind through weak bonds are generally more selective because weak bonds require a very precise fit. Inverse agonists have been found for histamine H1 and H2 receptors, the class to which a selective H1 inverse agonist belongs. A drug whose structure fits several receptor types (H1, H2, muscarinic) is by this definition non-selective.'},
         {src:'Katzung 16e, Ch. 6', sec:'Introduction (chemical transmission and autonomic drugs)', t:'“A very large number of drugs used for other purposes (eg, allergies, mental illness) have unwanted effects on autonomic function”. Muscarinic cholinoceptors are among the autonomic receptors it describes, so an allergy drug that also binds muscarinic receptors is the situation that sentence covers.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~29; transcript 9/22'},

{id:'L01-024', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'recall',
 concept:'allosteric-drugs', tags:['allosteric','classes'], source:'both',
 stem:'Which drug class does not always act by itself but can make other drugs much better or much worse by changing their potency?',
 options:[
  {t:'Allosteric drugs', correct:true, why:'Allosterics are "where the magic in pharmacology is": they affect the potency of other drugs.'},
  {t:'Full agonists', correct:false, why:'Full agonists act by themselves with positive efficacy.'},
  {t:'Irreversible antagonists', correct:false, why:'Antagonists block receptors; they are not described as changing other drugs’ potency.'},
  {t:'Inverse agonists', correct:false, why:'Inverse agonists act by themselves with negative efficacy.'}],
 teach:'Drug classes by mechanism: agonists (full, partial, inverse), antagonists (direct or indirect; reversible or irreversible), and allosterics (agonist or antagonist). Allosterics do not always act alone but can make other drugs much better or much worse.',
 quote:'we have over here where the magic in pharmacology is, allosterics. These drugs, they don’t do things by themselves all the time, but they can make other drugs much, much better or much, much worse.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Types of Drug-Receptor Interactions (Figure 1–2)', t:'Drugs that bind to the same receptor molecule as the agonist but do not prevent the agonist from binding are said to act allosterically, and they may enhance or inhibit the action of the agonist molecule. Allosteric activators may increase the efficacy of the agonist or its binding affinity, which in Figure 1–2 appears as a higher maximal response or a leftward shift of the agonist dose–response curve; allosteric inhibitors lower the response, and allosteric inhibition is usually not overcome by increasing the agonist dose. Changing the potency or efficacy of another drug, rather than competing with it, is what sets allosteric drugs apart from agonists and antagonists.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~29; transcript 9/22'},

{id:'L01-025', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'recall',
 concept:'drug-vs-poison-dose', tags:['dose'], source:'both',
 stem:'Carrots are good for eyesight because of vitamin A, but polar bear liver has so much vitamin A that eating it kills. Which statement does this illustrate?',
 options:[
  {t:'Drug and poison differ only in quantity', correct:true, why:'Walter Straub: there is only a quantitative difference between a drug and a poison.'},
  {t:'Natural sources are always safe', correct:false, why:'The example shows a natural source that is lethal.'},
  {t:'Vitamin A has no toxicity', correct:false, why:'Polar bear liver vitamin A is described as a poison.'},
  {t:'Selectivity rises as the dose is increased', correct:false, why:'Reverses the rule; selectivity falls as dose rises.'}],
 teach:'Everything is dose dependent. Walter Straub stated there is only a quantitative difference between a drug and a poison: vitamin A helps eyesight but is lethal at polar bear liver amounts.',
 quote:'Walter Straub: there is only a quantitative difference between a drug and a poison',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'The Nature of Drugs; The History of Pharmacology (general principles)', t:'Poisons are defined as drugs that have almost exclusively harmful effects, and Paracelsus’s statement follows that “the dose makes the poison”, meaning that any substance can be harmful if taken in the wrong dosage. Toxins are poisons of biologic origin, synthesized by plants or animals. Among the general principles the student should remember, the first is that all substances can under certain circumstances be toxic. The same quantitative rule is attributed to Paracelsus (1493–1541).'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~29; transcript 9/22'},

{id:'L01-026', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'apply',
 concept:'thiazide-moa-predict', tags:['thiazide','moa','classification'], source:'both',
 stem:'A thiazide diuretic blocks the Na+/Cl− symporter in the distal convoluted tubule. Which side effect does this mechanism predict?',
 options:[
  {t:'Hyponatremia', correct:true, why:'Blocking sodium reabsorption loses sodium; losing too much makes the patient hyponatremic.'},
  {t:'Decreased urination', correct:false, why:'Water follows sodium, so urination increases.'},
  {t:'Increased blood volume', correct:false, why:'Losing water lowers blood volume and blood pressure.'},
  {t:'Bradycardia', correct:false, why:'Bradycardia was the metoprolol example.'}],
 teach:'Classifying by chemical structure (benzothiadiazine ring) does not predict much. Classifying by MOA does: blocking the Na+/Cl− symporter at the distal tubule means sodium is lost, water follows, urination increases, blood volume and pressure fall (antihypertensive use), and losing too much sodium causes hyponatremia.',
 quote:'It makes you lose water because it makes you lose sodium. And if you lose too much sodium, you become hyponatremic. That’s a side effect.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~32–~33; transcript 9/22'},

{id:'L01-027', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'receptors', skill:'tell',
 concept:'receptor-class-examples', tags:['receptor-classes'], source:'slide',
 stem:'Which receptor class includes α and β adrenergic, 5HT and histamine receptors?',
 options:[
  {t:'7-transmembrane (GPCR)', correct:true, why:'The G protein–coupled receptor (GPCR) row lists α and β adrenergic, 5HT and histamine.'},
  {t:'1-transmembrane', correct:false, why:'This row lists tyrosine kinases.'},
  {t:'Ion channels', correct:false, why:'This row lists L-type Ca++ channels and GABA.'},
  {t:'Intracellular receptors', correct:false, why:'This row lists steroid hormones.'}],
 teach:'Four receptor classes: ion channels (L-type Ca++ channels, GABA), 7-transmembrane G protein–coupled receptors (α and β adrenergic, 5HT, histamine), 1-transmembrane proteins (tyrosine kinases) and intracellular receptors / transcriptional regulators (steroid hormones).',
 quote:'Protein coupled receptors(GPCR) α & β adrenergic, 5HT, Histamine, etc…',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2 Major autonomic receptor types; Presynaptic Regulation', t:'Table 6–2 gives the result of ligand binding for each autonomic receptor: α1 adrenoceptors form inositol trisphosphate (IP3) and diacylglycerol (DAG) and raise intracellular calcium; α2 receptors inhibit adenylyl cyclase and lower cyclic adenosine monophosphate (cAMP); β1, β2 and β3 receptors stimulate adenylyl cyclase and raise cAMP; muscarinic and dopamine receptors use the same IP3/DAG, adenylyl-cyclase or potassium-channel routes. The presynaptic α2 effect is called a “G protein–mediated” effect. Nicotinic receptors are the contrast: pentameric proteins whose ligand binding directly opens sodium and potassium channels, which is the ion-channel class rather than a coupled receptor.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~36'},

{id:'L01-028', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'ion', skill:'recall', multi:true,
 concept:'ion-channel-properties', tags:['ion-channels'], source:'slide',
 stem:'Which statements about ion channels are correct? Select all that apply.',
 options:[
  {t:'They are expressed in all cells', correct:true, why:'The ion channel slide lists them as transmembrane proteins expressed in all cells, with about 232 distinct types.'},
  {t:'They alter membrane potential', correct:true, why:'They convey their signal by altering membrane potential or ionic composition.'},
  {t:'The lipid bilayer lets ions through', correct:false, why:'The lipid bilayer is impermeable to anions and cations.'},
  {t:'There are about 7 distinct ones', correct:false, why:'There are about 232 distinct ion channels.'}],
 teach:'Ion channels are transmembrane proteins with various subunit combinations, expressed in all cells, about 232 distinct types. They are classified by the ions they conduct, their architecture and the mechanism that opens them (ligand, voltage or stretch). They signal by altering membrane potential or ionic composition (Na+, K+, Ca2+, Cl−), because the lipid bilayer is impermeable to ions.',
 quote:'Convey their signal by altering cell membrane potential or ionic composition (Na+, K+, Ca2+, and Cl–)',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2; Postsynaptic Regulation (Figure 6–8); Table 6–5', t:'Ion-channel signaling is expressed as changes in membrane potential: nicotinic receptor activation opens sodium and potassium channels and depolarizes the postganglionic cell, producing a fast excitatory postsynaptic potential (EPSP) that fires an action potential if threshold is reached, while M2 muscarinic receptors open potassium channels and hyperpolarize the cell, producing a slow inhibitory postsynaptic potential (IPSP). Transmitter release depends on calcium entering through voltage-sensitive calcium channels in the nerve terminal, and local anesthetics act by blocking voltage-gated sodium channels in axons. Channels for several ions thus appear in axons, nerve terminals, ganglion cells and muscle.'},
         {src:'Katzung 16e, Ch. 1', sec:'Ionization of Weak Acids and Weak Bases; Lipid diffusion; Special carriers', t:'The electrostatic charge of an ionized molecule attracts water dipoles and produces a polar, water-soluble and lipid-insoluble complex, so charged species do not readily cross lipid membranes; lipid diffusion is the most important limiting factor for permeation because lipid barriers separate the aqueous compartments of the body. Substances too large or too insoluble in lipid to diffuse passively cross by way of special carrier molecules, so the bilayer itself is not what lets charged ions through.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~39'},

{id:'L01-029', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'ion', skill:'tell',
 concept:'ion-channel-types', tags:['ion-channels'], source:'slide',
 stem:'Which type of ion channel is usually closed and has its binding pocket located in the channel, as in the nicotinic acetylcholine receptor?',
 options:[
  {t:'Ligand-gated channel', correct:true, why:'Ligand-gated channels are usually closed and bind acetylcholine, GABA-A or 5HT3 in the channel.'},
  {t:'Passive channel', correct:false, why:'Passive channels are always open and set resting membrane potential.'},
  {t:'Voltage-gated channel', correct:false, why:'These open at certain membrane potentials, e.g., calcium channels.'},
  {t:'Pump', correct:false, why:'Pumps move ions against the concentration gradient.'}],
 teach:'Passive channels are always open (resting membrane potential). Voltage-gated channels are highly selective and open only at certain membrane potentials (calcium channels). Stretch channels are pressure sensitive. Ligand-gated channels are usually closed with the binding pocket in the channel (acetylcholine at nicotinic, GABA-A, 5HT3). Pumps move ions against the concentration gradient (Na+/K+ ATPase).',
 quote:'Ligand Gated: Usually Closed; The Binding Pocket Located in the Channel; Acetylcholine, GABAA, Serotonin (5HT3), etc…',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2 Major autonomic receptor types; Table 6–5 Steps in autonomic transmission', t:'Nicotinic cholinoceptors are pentameric receptors: the neuronal type (NN) typically contains α- and β-type subunits, and the muscle type (NM) at skeletal neuromuscular end plates contains two α1 and β1 subunits plus γ and δ subunits. The result of ligand binding at both is “opening of Na+, K+ channels, depolarization”, and Table 6–5 states that nicotine binds nicotinic receptors and opens the ion channel in the postsynaptic membrane while tubocurarine prevents their activation. The channel opens when the ligand binds the receptor, which is the ligand-gated pattern; voltage-gated examples are the axonal sodium channels blocked by local anesthetics and the terminal calcium channels that open when an action potential arrives.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~40–~47'},

{id:'L01-030', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'ion', skill:'recall',
 concept:'baroreceptor-stretch', tags:['ion-channels','baroreceptor'], source:'slide',
 stem:'Baroreceptors in the carotid sinus and aortic arch use stretch channels. What happens to nerve firing when stretch increases?',
 options:[
  {t:'Nerve firing increases', correct:true, why:'The slide states increase stretch = increase nerve firing.'},
  {t:'Nerve firing decreases', correct:false, why:'Reverses the relationship.'},
  {t:'Nerve firing does not change', correct:false, why:'Stretch channels are pressure sensitive, so firing changes.'},
  {t:'The channel closes permanently', correct:false, why:'No such behavior is described.'}],
 teach:'Stretch channels are pressure sensitive and embedded in blood vessel walls (baroreceptors). The carotid sinus (glossopharyngeal nerve) monitors blood going to the brain and the aortic arch (vagus nerve) is close to the heart. Increased stretch increases nerve firing.',
 quote:'Increase Stretch = Increase Nerve Firing',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Integration of Cardiovascular Function; Functional Organization of Autonomic Activity', t:'The sensory carotid sinus baroreceptor fibers travel in the glossopharyngeal nerve and have a major influence on sympathetic outflow from the vasomotor center. When mean arterial pressure rises, for example during a norepinephrine infusion, the compensatory response “is mediated by increased firing by the baroreceptor nerves of the carotid sinus and the aortic arch”; increased baroreceptor activity causes decreased central sympathetic outflow and increased vagal (parasympathetic) outflow to the sinoatrial node, so the heart often slows even though the drug itself stimulates it. Higher pressure stretching the vessel wall means more baroreceptor firing.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~43'},

{id:'L01-031', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'ion', skill:'apply',
 concept:'nicotinic-sequence', tags:['nicotinic','ion-channels'], source:'slide',
 stem:'Acetylcholine binds the 2 α subunits of the nicotinic receptor, the channel opens and Na+ flows in while K+ flows out. What is the next step?',
 options:[
  {t:'The membrane depolarizes', correct:true, why:'Step 3: depolarization of membrane potential (less negative).'},
  {t:'The Na+/K+ ATPase restores potential', correct:false, why:'That is the last step, after contraction.'},
  {t:'Intracellular Ca++ falls', correct:false, why:'Intracellular Ca++ increases once voltage-sensitive Ca++ channels open.'},
  {t:'The membrane becomes more negative', correct:false, why:'Na+ influx makes the membrane less negative.'}],
 teach:'Sequence: (1) acetylcholine binds 2 α subunits; (2) the channel opens, increasing Na+ influx and K+ outflow; (3) the membrane depolarizes (less negative); (4) voltage-sensitive Ca++ channels open; (5) intracellular Ca++ rises, increasing contraction; (6) the Na+/K+ ATPase restores membrane potential.',
 quote:'3. Depolarization of membrane potential (less negative) 4. Open Voltage Sensitive Ca++ Channels',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2; Postsynaptic Regulation (Figure 6–8); Cholinergic Transmission; Case Study Answer', t:'Ligand binding at nicotinic receptors results in “opening of Na+, K+ channels, depolarization”; the muscle-type receptor contains two α1 subunits along with β1, γ and δ subunits. In the ganglion the resulting fast excitatory postsynaptic potential (EPSP) evokes a propagated action potential if threshold is reached. Contraction of skeletal muscle is triggered by exocytotic release of acetylcholine from motor nerves, and that release follows calcium influx through voltage-sensitive calcium channels once an action potential reaches the terminal. Depolarization is the immediate consequence of the channel opening, before any calcium-dependent step.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~48'},

{id:'L01-032', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'gpcr', skill:'recall',
 concept:'gpcr-largest-class', tags:['gpcr'], source:'both',
 stem:'Which statement about G protein–coupled receptors (GPCRs) is correct?',
 options:[
  {t:'They interact with 60% plus of drugs', correct:true, why:'The slide states GPCRs interact with 60% plus of active therapeutic drugs.'},
  {t:'They cross the membrane once', correct:false, why:'GPCRs are 7-transmembrane proteins.'},
  {t:'Their G protein has one subunit', correct:false, why:'The G protein is heterotrimeric: α, β and γ.'},
  {t:'They are the smallest receptor class', correct:false, why:'They are the largest single class of pharmacological receptors.'}],
 teach:'GPCRs are 7-transmembrane proteins coupled to a heterotrimeric guanine nucleotide binding protein (α, β, γ). They are the largest single class of pharmacological receptors and interact with 60% plus of active therapeutic drugs. The G protein acts as the translator that dictates the signal.',
 quote:'about 60 or more% of all drugs in the market target one of kind of these receptors. So if you know how they work, you’ve got 60% of the drugs in your pocket.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~49; transcript 9/22'},

{id:'L01-033', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'gpcr', skill:'apply',
 concept:'gs-cascade-heart', tags:['gpcr','gs','beta1'], source:'slide',
 stem:'Norepinephrine binds β1 receptors in the heart. After GDP release and GTP binding, what does the αs subunit activate?',
 options:[
  {t:'Adenylate cyclase', correct:true, why:'αs activates adenylate cyclase (AC), which converts ATP to cAMP.'},
  {t:'Phospholipase C', correct:false, why:'Phospholipase C (PLC) is activated by αq at α1 receptors.'},
  {t:'Phosphodiesterase', correct:false, why:'Phosphodiesterase (PDE) breaks down cAMP; it ends the signal.'},
  {t:'The Na+/K+ ATPase', correct:false, why:'That pump restores membrane potential in the nicotinic sequence.'}],
 teach:'At β1 in the heart: norepinephrine binds, GDP is released, GTP binds, and αs activates adenylate cyclase (AC). AC converts ATP to cAMP (amplification), the second messenger, leading to the physiological response of increased heart rate.',
 quote:'NE β1 ... αs ATP AC ... ATP cAMP ... Physiological Response (Increase in Heart Rate)',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2; Table 6–3; Table 6–5', t:'For β1 adrenoceptors, located on postsynaptic effector cells “especially heart”, the result of ligand binding is “stimulation of adenylyl cyclase, increased cAMP” (cyclic adenosine monophosphate). Table 6–3 lists the sinoatrial node as accelerated and contractility as increased by sympathetic activity through β1 and β2 receptors, and Table 6–5 describes the β agonist isoproterenol as binding β receptors and activating adenylyl cyclase. Adenylyl cyclase is the enzyme downstream of the β1 receptor; formation of IP3 belongs to α1 and M1/M3 receptors, and inhibition of adenylyl cyclase to α2 and M2.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~51–~53'},

{id:'L01-034', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'gpcr', skill:'recall', multi:true,
 concept:'gs-termination', tags:['gpcr','rgs','pde'], source:'slide',
 stem:'Which processes end the β1–Gs signal? Select all that apply.',
 options:[
  {t:'Intrinsic GTPase hydrolysis of GTP', correct:true, why:'GTPase-mediated dissociation is the intrinsic process that cleaves GTP to GDP.'},
  {t:'RGS proteins speeding GTP hydrolysis', correct:true, why:'Regulators of G protein signaling (RGS) greatly accelerate GTP hydrolysis.'},
  {t:'Phosphodiesterase breaking down cAMP', correct:true, why:'cAMP phosphodiesterase (PDE) removes the second messenger.'},
  {t:'GDP release from the αs subunit after binding', correct:false, why:'GDP release is an activating step; GTP then binds.'},
  {t:'Adenylate cyclase making cAMP', correct:false, why:'This produces the signal; it does not end it.'}],
 teach:'Activation: binding, GDP release, GTP binding, α-mediated activation of adenylate cyclase, ATP to cAMP. Deactivation: intrinsic GTPase cleavage of GTP, RGS-enhanced dissociation (RGS proteins greatly accelerate GTP hydrolysis), and cAMP phosphodiesterase (PDE).',
 quote:'Regulators of G protein signaling (RGSs) - RGS proteins greatly accelerate the hydrolysis of GTP',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~54'},

{id:'L01-035', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'gpcr', skill:'tell',
 concept:'gq-alpha1-plc', tags:['gpcr','gq','alpha1'], source:'slide',
 stem:'Norepinephrine binds α1 receptors on smooth muscle. Which pathway follows?',
 options:[
  {t:'αq, phospholipase C, PIP2 to IP3', correct:true, why:'α1 couples to αq, which activates phospholipase C (PLC); PIP2 gives IP3, releasing Ca2+ from the ER.'},
  {t:'αs, adenylate cyclase, ATP to cAMP', correct:false, why:'That is the β1 pathway in the heart.'},
  {t:'Na+ influx through the receptor channel', correct:false, why:'That is the nicotinic ligand-gated channel.'},
  {t:'Enzymatic activity of the receptor', correct:false, why:'That describes 1-transmembrane receptors.'}],
 teach:'At α1 receptors on smooth muscle, norepinephrine or epinephrine activates αq, which activates phospholipase C (PLC). PLC converts PIP2 to IP3, and IP3 releases stored Ca2+ from the endoplasmic reticulum (ER).',
 quote:'α1 ... αq PLC e.g., Smooth Muscle PIP2 ... IP3 ... Ca2+ ER ... NE, Epi',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2; Table 6–3; Table 6–5', t:'α1 adrenoceptors sit on postsynaptic effector cells, “especially smooth muscle”, and the result of ligand binding is “formation of IP3 and DAG, increased intracellular calcium” (inositol trisphosphate and diacylglycerol). Table 6–5 lists norepinephrine as binding and activating α receptors and causing contraction, and Table 6–3 shows skin and splanchnic vessels, the iris radial muscle and the gastrointestinal and bladder sphincters contracting through α receptors. The same IP3/DAG/calcium result is listed for M1, M3 and M5 muscarinic receptors, whereas β receptors act through adenylyl cyclase and cAMP.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~55'}
);
