TOPICS.push({id:"L09", name:"Day 9: muscarinic receptors, agonists and antagonists", prof:"Gottlieb", lecture:"L09",
  cite:"Day 9 (10/6) — PCOL-Cholinergic-26s.pdf",
  subs:[
    {id:"overview", name:"Cholinergic system overview", cite:"slides 1–4"},
    {id:"loc", name:"M1, M2, M3: where they are", cite:"slides 5, 10"},
    {id:"transd", name:"Gq vs Gi signal transduction", cite:"slides 6–9"},
    {id:"agon", name:"Muscarinic agonists and their uses", cite:"slides 11–12, 14"},
    {id:"dumb", name:"DUMBBELSS and agonist ADRs", cite:"slides 13–15"},
    {id:"atrop", name:"Atropine, scopolamine and organophosphate poisoning", cite:"slides 17–24"},
    {id:"uses", name:"Antimuscarinic uses: Parkinson, eye, lungs", cite:"slides 25–28"},
    {id:"bladder", name:"Overactive bladder antimuscarinics and anti-DUMBBELSS", cite:"slides 29–32"}
  ]});
QUESTIONS.push(
{id:"L09-001", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"overview", skill:"recall",
 concept:"lungs-pns-only-m3", tags:[], source:"both",
 stem:"Which autonomic division and receptor control bronchial smooth muscle?",
 options:[
  {t:"Parasympathetic only, M3", correct:true, why:"The lungs are marked PNS only, and the receptor drawn on the lungs and on bronchial smooth muscle is M3."},
  {t:"Sympathetic only, α1", correct:false, why:"α1 appears on the eye in the same diagram, not on the lungs; the lungs are marked PNS only."},
  {t:"Both divisions, M2", correct:false, why:"M2 is the heart receptor, and the lungs receive direct input from the PNS only."},
  {t:"Parasympathetic only, Nn", correct:false, why:"Nicotinic receptors sit at the ganglia; the receptor on bronchial smooth muscle is muscarinic M3."},
  {t:"Sympathetic only, M1", correct:false, why:"M1 is drawn on the brain, and the lungs are PNS only."}],
 teach:"The lungs receive direct autonomic input from the parasympathetic nervous system (PNS) only, and the receptor on bronchial smooth muscle is M3. This is the rationale for muscarinic antagonists in asthma and chronic obstructive pulmonary disease (COPD): blocking M3 removes the PNS bronchoconstrictor signal.",
 quote:"in the lungs, one of our exceptions is only parasympathetic, right? Innervation. We have the beta 2 there, but we don't have a sympathetic nerve going to.",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Organ System Effects — 4. Respiratory system","t":"Both smooth muscle and secretory glands of the airway receive vagal innervation and contain muscarinic receptors. Even in normal individuals, atropine can cause some bronchodilation and reduce secretion, and the effect is more significant in patients with airway disease."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 3; slide 27; transcript 10/5"},

{id:"L09-002", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"overview", skill:"tell",
 concept:"muscarinic-vs-nicotinic-sites", tags:[], source:"slide",
 stem:"Which site carries nicotinic, not muscarinic, cholinergic receptors?",
 options:[
  {t:"Autonomic ganglion cells", correct:true, why:"Nicotinic receptors are listed at the neuromuscular junction and on autonomic ganglion cells."},
  {t:"Heart", correct:false, why:"The heart is listed under muscarinic receptors (heart and smooth muscle)."},
  {t:"Smooth muscle of the GI tract", correct:false, why:"Smooth muscle is listed under muscarinic receptors."},
  {t:"Glands", correct:false, why:"Glands are grouped with endothelium under muscarinic receptors."},
  {t:"Endothelium", correct:false, why:"Endothelium is grouped with glands under muscarinic receptors."}],
 teach:"Cholinergic receptors split into two families. Muscarinic receptors are on nerve, heart and smooth muscle, and glands and endothelium. Nicotinic receptors are at the neuromuscular junction and on autonomic ganglion cells.",
 quote:"Muscarinic: Nerve / Heart and Smooth Muscle / Glands and Endothelium. Nicotinic: Neuromuscular Junction / Autonomic Ganglion cells",
 cite:"PCOL-Cholinergic-26s.pdf slide 4"},

{id:"L09-003", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"overview", skill:"recall",
 concept:"direct-vs-indirect-acting", tags:[], source:"both",
 stem:"How do indirect-acting cholinergic receptor stimulants activate muscarinic and nicotinic receptors?",
 options:[
  {t:"By raising acetylcholine levels", correct:true, why:"Indirect-acting drugs work through an increase in acetylcholine (ACh), which then activates both receptor families."},
  {t:"By binding the receptor directly", correct:false, why:"Binding the receptor is what direct-acting drugs (alkaloids and choline esters) do."},
  {t:"By blocking the M2 receptor", correct:false, why:"Blocking a receptor is antagonism, not stimulation."},
  {t:"By acting as choline esters", correct:false, why:"Choline esters are a group of direct-acting drugs, not indirect-acting ones."}],
 teach:"Receptor stimulants are direct-acting or indirect-acting. Direct-acting drugs are alkaloids or choline esters and act on the receptors themselves. Indirect-acting drugs, reversible or irreversible, raise acetylcholine (ACh), and the extra ACh activates both muscarinic and nicotinic receptors.",
 quote:"We have receptor drugs that can directly bind to the orthostatic site of those receptors and activate them or block, and we have indirect antagonists just like we talked about that in in the neuromuscular junction.",
 cite:"PCOL-Cholinergic-26s.pdf slide 4; transcript 10/5"},

{id:"L09-004", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"loc", skill:"tell",
 concept:"m-subtype-locations", tags:[], source:"both",
 stem:"Which pairing of muscarinic receptor subtype and location is CORRECT?",
 options:[
  {t:"M2: atrioventricular and sinoatrial nodes", correct:true, why:"M2 is the heart receptor, at the atrioventricular (AV) and sinoatrial (SA) nodes."},
  {t:"M1: bladder smooth muscle", correct:false, why:"Bladder smooth muscle is listed under M3 (everywhere else)."},
  {t:"M3: atrioventricular node", correct:false, why:"The AV node is an M2 site, not M3."},
  {t:"M2: salivary glands", correct:false, why:"Glands carry M3, not M2."},
  {t:"M3: brain neurons (Alzheimer disease target)", correct:false, why:"The brain receptor with a role in Alzheimer disease treatment is M1."}],
 teach:"M1 is drawn on the brain and has an important role in the treatment of Alzheimer disease. M2 is on the heart, at the atrioventricular (AV) and sinoatrial (SA) nodes. M3 is everywhere else: smooth muscle of the gut and bladder, airway, eyes, and glands.",
 quote:"We have M1s are gonna be in the brain, M2s in the heart, M3s everywhere else. ... M2s are gonna be primarily present on the AV and the on the assay node.",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Table 8–1 Muscarinic receptor subgroups","t":"M1 receptors are on nerves (central neurons, autonomic postganglionic cell bodies and presynaptic sites). M2 receptors are in the heart, nerves and smooth muscle. M3 receptors are most common on glands, smooth muscle and endothelium."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 10; slide 5; transcript 10/5"},

{id:"L09-005", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"loc", skill:"recall",
 concept:"m3-endothelium-non-innervated", tags:[], source:"slide",
 stem:"Which muscarinic receptor subtype is on the endothelium, and is that site innervated?",
 options:[
  {t:"M3; not innervated", correct:true, why:"M3 is listed on smooth muscle (gut), glands, eyes and endothelia, with the endothelia marked non-innervated."},
  {t:"M2; innervated", correct:false, why:"M2 is listed for heart and smooth muscle (GI sphincter), not endothelium."},
  {t:"M1; innervated", correct:false, why:"M1 is the brain receptor (the Alzheimer disease site), not the endothelial receptor."},
  {t:"M3; innervated by PNS", correct:false, why:"The receptor is right, but the endothelial M3 site is marked non-innervated."}],
 teach:"M3 receptors are on gut smooth muscle, glands, eyes and the endothelium. The endothelial M3 receptors are non-innervated: no parasympathetic nerve ends on them. When a muscarinic agonist reaches them, M3 mediates the release of nitric oxide and vasodilation.",
 quote:"Muscarinic Receptor Type 3 (M3) Smooth Muscle (gut), Glands, eyes and Endothelia (non-innervated)",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Organ System Effects — 3. Cardiovascular system","t":"Most blood vessels receive no direct parasympathetic innervation, but almost all vessels contain endothelial muscarinic receptors that mediate vasodilation. These receptors are readily blocked by antimuscarinic drugs."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 5"},

{id:"L09-006", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"loc", skill:"recall",
 concept:"m1-location", tags:[], source:"both",
 stem:"Which of the following is CORRECT about the M1 muscarinic receptor?",
 options:[
  {t:"It has a role in Alzheimer disease treatment", correct:true, why:"M1, drawn on the brain, is stated to have an important role in the treatment of Alzheimer disease."},
  {t:"It is the receptor at the SA node", correct:false, why:"The sinoatrial (SA) node carries M2, the heart receptor."},
  {t:"It couples to the Gi protein", correct:false, why:"M1 couples to Gq; Gi belongs to M2 (and M4)."},
  {t:"It mediates bronchial smooth muscle constriction", correct:false, why:"Bronchial constriction is an M3 effect."}],
 teach:"M1 is the brain receptor: M1s in the brain, M2s in the heart, M3s everywhere else. M1 has an important role as a site of action for the treatment of Alzheimer disease. It couples to Gq, like M3, so an agonist stimulates the central nervous system (CNS) and an antagonist sedates.",
 quote:"M1s are gonna be very important as a side of action for the treatment of Alzheimer's disease, OK?",
 note:"One deck slide lists M1 under 'Enteric Nervous System and Neuron Ganglia'; in the audio he places M1 in the brain every time. The question keys the brain/Alzheimer point.",
 cite:"PCOL-Cholinergic-26s.pdf slide 5; slide 10; transcript 10/5"},

{id:"L09-007", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"recall",
 concept:"gq-subtypes", tags:[], multi:true, source:"both",
 stem:"Which cholinergic receptors couple to the Gq protein? Select all that apply.",
 options:[
  {t:"M1", correct:true, why:"M1 is Gq: it raises IP3 and Ca2+ and stimulates the cell."},
  {t:"M2", correct:false, why:"M2 is Gαi (inhibitory); it lowers cAMP."},
  {t:"M3", correct:true, why:"M3 is Gq, the same as M1."},
  {t:"Nn", correct:false, why:"Nicotinic receptors are ion channels, not G protein–coupled receptors."},
  {t:"Nm", correct:false, why:"Nm at the neuromuscular junction is an ion channel, not a G protein–coupled receptor."}],
 teach:"Muscarinic receptors are seven-transmembrane G protein–coupled receptors; nicotinic receptors (Nn, Nm) are ion channels. M1 and M3 couple to Gq, which raises inositol trisphosphate (IP3) and Ca2+ (a stimulatory effect). M2 couples to Gαi, which lowers cyclic AMP (cAMP) (an inhibitory effect). M4 and M5 exist, but no drugs target them.",
 quote:"So we know that M1 and M3 are GQ. ... So, ion channels are nicotinic receptors. These guys are G protein coupled receptors, so that's different.",
 cite:"PCOL-Cholinergic-26s.pdf slide 9; transcript 10/5"},

{id:"L09-008", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"apply",
 concept:"gq-predict-effect", tags:[], source:"both",
 stem:"M3 receptors on gastrointestinal (GI) smooth muscle couple to Gq. What does a muscarinic agonist produce there?",
 options:[
  {t:"↑ Ca2+; increased motility and tone", correct:true, why:"Gq raises IP3 and Ca2+, and a rise in Ca2+ gives a positive effect: in the GI tract, more motility and tone."},
  {t:"↓ cAMP; decreased motility and tone", correct:false, why:"Lowering cyclic AMP (cAMP) is the Gαi (M2) pathway, and the M3 effect in the gut is stimulation, not suppression."},
  {t:"↑ cAMP; smooth muscle relaxation", correct:false, why:"Gs raising cAMP belongs to the β receptor, not to M3."},
  {t:"K+ efflux; hyperpolarization", correct:false, why:"Opening K+ channels is the M2 (Gαi, βγ) action in the heart."}],
 teach:"The rule is to predict the effect from the G protein. Gq (M1, M3) raises inositol trisphosphate (IP3), IP3 releases Ca2+ from the endoplasmic reticulum, and more Ca2+ gives a positive effect: smooth muscle contraction, more neurotransmitter release in the brain, more motility and tone in the gut, miosis in the eye. Gαi (M2) gives a negative effect.",
 quote:"If it's in the M3, depending where it is, let's say it's on the GI tract, I'm gonna increase motility and tone. If it is in the eyes, I'm gonna squeeze those circular muscles and cause meiosis. So everything is gonna be sort of a positive effect, OK?",
 note:"The ordered cascade (GDP/GTP, PLC, PIP2, IP3 receptor) was rewritten out: he will not ask what comes in and out of the G protein or what AC does; he asks you to predict the effect from the G protein.",
 cite:"PCOL-Cholinergic-26s.pdf slide 6; slide 9; transcript 10/5"},

{id:"L09-009", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"apply",
 concept:"m2-gi-heart", tags:[], multi:true, source:"both",
 stem:"Acetylcholine binds M2 receptors on the heart. Which effects follow? Select all that apply.",
 options:[
  {t:"Inhibition of adenylyl cyclase", correct:true, why:"αi inhibits adenylyl cyclase (AC), labeled #1 in the M2 figure."},
  {t:"Decrease in cAMP", correct:true, why:"With AC inhibited, less ATP is converted to cyclic AMP (cAMP)."},
  {t:"Membrane hyperpolarization via K+", correct:true, why:"The βγ subunits open a K+ channel (#2), and K+ leaving hyperpolarizes the membrane."},
  {t:"Rise in IP3 and Ca2+", correct:false, why:"IP3 and Ca2+ belong to the Gq pathway of M1 and M3."},
  {t:"Increase in heart rate", correct:false, why:"M2 lowers heart rate and contractility; NE on the β receptor (Gαs) raises them."}],
 teach:"M2 couples to Gαi. Action #1: αi inhibits adenylyl cyclase (AC), so cyclic AMP (cAMP) falls. Action #2: the βγ subunits open a K+ channel, and K+ leaving hyperpolarizes the membrane. Both lower heart rate and contractility, opposing norepinephrine (NE) acting through a Gαs-coupled β receptor that raises cAMP.",
 quote:"So, our M2s are gonna produce that decrease in contactile force and heart rate by two mechanisms of actions. One is through the alpha, by suppressing camp production, two, by opening potassium channels.",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Table 8–1 Muscarinic receptor subgroups","t":"The dominant effector system of M2 (and M4) receptors is a decrease in cAMP and an increase in K+ channel current. M1, M3 and M5 receptors act through increases in IP3 and diacylglycerol (DAG)."}],
 cite:"PCOL-Cholinergic-26s.pdf slides 7–8; transcript 10/5"},

{id:"L09-010", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"tell",
 concept:"m2-vs-beta-heart", tags:[], source:"both",
 stem:"In a cardiac cell, acetylcholine acts on M2 and norepinephrine acts on a β receptor. Which statement is CORRECT?",
 options:[
  {t:"M2 uses Gαi; β uses Gαs", correct:true, why:"M2 couples to Gαi and lowers cAMP; the β receptor couples to Gαs and raises it, so the two oppose each other."},
  {t:"Both use Gαq", correct:false, why:"Gαq belongs to M1 and M3, not to M2 or the β receptor."},
  {t:"M2 uses Gαs; β uses Gαi", correct:false, why:"This reverses the two: M2 is Gαi, the β receptor is Gαs."},
  {t:"Both raise heart rate", correct:false, why:"M2 lowers heart rate and contractility; the β receptor raises them."}],
 teach:"Adenylyl cyclase (AC) in the heart is pushed in two directions. Norepinephrine (NE) on a β receptor activates Gαs, raising cyclic AMP (cAMP) and heart rate and contractility. Acetylcholine (ACh) on M2 activates Gαi, inhibiting AC and lowering cAMP, heart rate and contractility.",
 quote:"So if I have my beta activation over here, it sculpture GS, so it's going to stimulate the heart. M2s are cou to the alpha I, which is going to suppress camp and it's going to cause a decrease in the heart function. So they're going to oppose each other to that process.",
 note:"The M2 figure labels the norepinephrine receptor on the heart cell 'β2' (Gαs); in the audio he says only 'beta' for the heart, and the Exam 1 drug list treats metoprolol, a β1 antagonist, as the cardiac β drug. The question avoids the subtype.",
 cite:"PCOL-Cholinergic-26s.pdf slides 7–8; transcript 10/5"},

{id:"L09-011", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"recall",
 concept:"m-excite-vs-suppress", tags:[], source:"both",
 stem:"Of the M1, M2 and M3 muscarinic receptors, which one suppresses its target cell when activated?",
 options:[
  {t:"M2", correct:true, why:"M2 couples to Gαi (inhibitory) and lowers cAMP, a negative effect; M1 and M3 (Gq) excite."},
  {t:"M1", correct:false, why:"M1 is Gq: Ca2+ rises and the brain is stimulated."},
  {t:"M3", correct:false, why:"M3 is Gq: Ca2+ rises, for example smooth muscle contraction."},
  {t:"None of the three", correct:false, why:"Two excite (M1, M3) and one suppresses (M2)."}],
 teach:"Two muscarinic receptors excite and one suppresses. M1 and M3 couple to Gq: inositol trisphosphate (IP3) and Ca2+ rise, a positive effect. M2 couples to Gαi (I for inhibition): cyclic AMP (cAMP) falls, a negative effect such as bradycardia. M4 and M5 exist, but no drugs target them.",
 quote:"the key thing for you to understand is two of them typically gonna excite and one of them is gonna suppress, right?",
 note:"Rewritten from an M4 (CNS, Gi) item: he said M4 and M5 have no drugs targeting them and 'we're not gonna worry about it'.",
 cite:"PCOL-Cholinergic-26s.pdf slide 9; transcript 10/5"},

{id:"L09-012", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"recall",
 concept:"muscarinic-agonist-moa", tags:[], source:"both",
 stem:"Which of the following describes the mechanism of action of methacholine, carbachol, bethanechol and pilocarpine?",
 options:[
  {t:"Non-selective, reversible M1–M3 agonists", correct:true, why:"All of them are non-selective agonists at M1, M2 and M3 and are reversible, with similar effects, side effects and drug–drug interactions."},
  {t:"Selective, reversible M3 agonists", correct:false, why:"They are non-selective across M1, M2 and M3."},
  {t:"Non-selective, irreversible agonists", correct:false, why:"They are reversible."},
  {t:"Agonists at both nicotinic and muscarinic receptors", correct:false, why:"These drugs bind only muscarinic receptors; acetylcholine is the only agonist that binds both nicotinic and muscarinic receptors."}],
 teach:"The muscarinic agonists (methacholine, carbachol, bethanechol, pilocarpine) are non-selective for M1, M2 and M3 and reversible, so they are competitive and an overdose can be outcompeted. They share similar effects, side effects and drug–drug interactions: know one and you know them all. Acetylcholine is the only agonist that also activates nicotinic (Nn, Nm) receptors.",
 quote:"Well, for these drugs, all of them are gonna be non-selective agonists to the M1s, M2s, and M3s. ... They're all reversible, so they're all competitive, they're gonna bind, and they're gonna come off.",
 cite:"PCOL-Cholinergic-26s.pdf slide 11; slide 12; transcript 10/5"},

{id:"L09-013", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"recall",
 concept:"chol-nomenclature", tags:[], source:"both",
 stem:"Methacholine, carbachol and bethanechol all contain \"chol\" in their names. What does that signal about their mechanism?",
 options:[
  {t:"Muscarinic receptor agonist", correct:true, why:"The 'chol' is for cholinergic: each acts like acetylcholine at muscarinic receptors."},
  {t:"Muscarinic receptor antagonist", correct:false, why:"Antagonists like atropine carry 'trop' in the name, not 'chol'."},
  {t:"Acetylcholinesterase inhibitor", correct:false, why:"These drugs bind the muscarinic receptor directly; they do not act on the enzyme."},
  {t:"Nicotinic receptor agonist", correct:false, why:"Only acetylcholine among the cholinergic agonists also binds nicotinic receptors."}],
 teach:"Methacholine, carbachol and bethanechol carry 'chol' for cholinergic, so the name predicts the mechanism: direct, non-selective, reversible muscarinic (M1–M3) agonists. Pilocarpine is the agonist without 'chol' in its name that must be known. The uses and brand names are given for information; the exam asks mechanism of action, site of action and effects.",
 quote:"So, I have over here methylcholine, carbacol, Bethenacol, so they all have that call for cholinergic, right? That's what the call comes from. So by understanding the nomenclature of this drug in the system, we can predict what it's gonna do.",
 note:"Rewritten from a drug–use pairing item: for the agonists he said 'I'm not testing you on the use' and 'no brand name'.",
 cite:"PCOL-Cholinergic-26s.pdf slide 11; transcript 10/5"},

{id:"L09-014", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"apply",
 concept:"agonist-bladder-urination", tags:[], source:"both",
 stem:"Bethanechol activates M3 receptors on the urinary bladder. What is the expected effect?",
 options:[
  {t:"Increased urination", correct:true, why:"Activating the bladder squeezes it, so urination increases (micturition)."},
  {t:"Urinary retention", correct:false, why:"Retention (cannot pee) is the antagonist effect, anti-DUMBBELSS."},
  {t:"Bladder relaxation", correct:false, why:"Relaxing the bladder is what the overactive bladder antagonists (oxybutynin, solifenacin) do."},
  {t:"No effect on the bladder", correct:false, why:"The bladder is under parasympathetic (PNS) tone through M3, so an agonist acts there."}],
 teach:"The urinary bladder is under parasympathetic (PNS) tone through M3 (Gq). A muscarinic agonist such as bethanechol squeezes the bladder and increases urination (micturition), one of the DUMBBELSS effects. Muscarinic antagonists do the opposite: they relax the bladder.",
 quote:"Remember that if you activate the bladder, you're gonna squeeze the bladder, you're gonna increase urination.",
 note:"Rewritten from 'which agonist is used for urinary retention': for the agonists he tests mechanism, site of action and effects, not the use.",
 cite:"PCOL-Cholinergic-26s.pdf slide 13; slide 11; transcript 10/5"},

{id:"L09-015", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"apply",
 concept:"pilocarpine-salivation-m3", tags:[], source:"both",
 stem:"Radiation destroyed a patient's salivary glands, and pilocarpine is given to help the patient salivate. Through which receptor and G protein does pilocarpine cause salivation?",
 options:[
  {t:"M3, Gq", correct:true, why:"Salivary gland = M3 = Gq; Gq raises Ca2+, and the effect is salivation."},
  {t:"M2, Gαi", correct:false, why:"M2 (Gαi) is the heart receptor; activating it gives bradycardia."},
  {t:"M1, Gαi", correct:false, why:"M1 is the brain receptor, and it couples to Gq, not Gαi."},
  {t:"Nn, ion channel", correct:false, why:"Pilocarpine does not bind or activate nicotinic receptors."}],
 teach:"Pilocarpine is a non-selective, reversible muscarinic agonist. At the salivary gland it acts on M3, which couples to Gq and raises Ca2+, so the patient salivates. Patients whose salivary glands were damaged by radiation can use it to salivate. Because it is non-selective, it also acts on M2 in the heart (bradycardia).",
 quote:"they get radiation and it destroyed their salivary glands. So by using pilocarpine kind of helps them to salivate, right? ... If it is salivary glands, that's M3s, M3s are GQ, GQ increased calcium, salivation.",
 note:"Rewritten from a select-all on the uses of pilocarpine and cevimeline: he expects pilocarpine (not cevimeline) on the exam and tests mechanism and effects, not uses. The word 'Radiation' beside pilocarpine refers to patients whose salivary glands were destroyed by radiation.",
 cite:"PCOL-Cholinergic-26s.pdf slide 14; slide 11; transcript 10/5"},

{id:"L09-016", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"tell",
 concept:"ach-only-nicotinic-and-muscarinic", tags:["exam-cue"], source:"both",
 stem:"Which cholinergic agonist activates both nicotinic and muscarinic receptors?",
 options:[
  {t:"Acetylcholine", correct:true, why:"Acetylcholine is the only agonist here that binds both nicotinic (Nn, Nm) and muscarinic receptors."},
  {t:"Pilocarpine", correct:false, why:"Pilocarpine has affinity only for muscarinic receptors."},
  {t:"Carbachol", correct:false, why:"Carbachol binds only muscarinic receptors; thinking muscarinic agonists also bind nicotinic receptors is the common exam mistake."},
  {t:"Methacholine", correct:false, why:"Methacholine binds only muscarinic receptors."},
  {t:"Succinylcholine", correct:false, why:"Succinylcholine is a depolarizing agent at the Nm receptors of the neuromuscular junction, not a muscarinic agonist."}],
 teach:"Acetylcholine is less selective than the drugs: it activates muscarinic (M1–M3) and nicotinic (Nn, Nm) receptors. Methacholine, carbachol, bethanechol and pilocarpine bind only muscarinic receptors. The common exam mistake is to think the muscarinic agonists also bind nicotinic receptors.",
 quote:"the biggest misconception that students have and questions they miss in the exam is that they think that our muscarinic agonists can also bind to the nicotinic receptors, and they don't. They are selective to the muscarinic receptors. The only one that can bind to both is gonna be acetylcholine.",
 note:"Rewritten from the hydrolysis-by-AChE ratings: he called alkaloid and hydrolysis status FYI ('I don't care if you know that it is an alkaloid, that is not hydrolyzed').",
 cite:"PCOL-Cholinergic-26s.pdf slide 11; slide 12; slide 14; transcript 10/5"},

{id:"L09-017", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"apply",
 concept:"carbachol-pilocarpine-affinity", tags:["in-class"], lowYield:true, source:"both",
 stem:"At equal concentrations, carbachol and pilocarpine have similar effects on the gut, bladder and eye, but at the heart pilocarpine acts as a full agonist and carbachol as a partial agonist. What explains the difference?",
 options:[
  {t:"Different affinity for M2 than for M3", correct:true, why:"The heart has M2 and the gut, bladder and eye have M3; carbachol has lower affinity for the heart's M2, so a lower effect."},
  {t:"Different bioavailability", correct:false, why:"The premise is equal concentrations reaching the heart."},
  {t:"Carbachol also binds nicotinic receptors", correct:false, why:"Carbachol binds only muscarinic receptors."},
  {t:"Carbachol binds irreversibly", correct:false, why:"All the muscarinic agonists are reversible."}],
 teach:"The heart carries M2; the gut, bladder and eye carry M3. Different receptors, different affinities: from its chemical structure, pilocarpine has a high affinity for the heart's M2, while carbachol has a lower affinity and so a lower effect there. For exam purposes, the muscarinic agonists are treated as having equal efficacies and affinities.",
 quote:"Yes. Affinity, right, which receptors are in the heart. M2s, which receptors are in the gut or in the bladder or in the eye, M3s, right? So, different receptors, different affinities.",
 note:"Rewritten from the heart-rate ratings table (carbachol +, pilocarpine +++) into his in-class question. He added: 'for exam purpose, we're gonna assume they all have equal efficacies, OK, and affinities', so the ratings themselves are low yield.",
 cite:"PCOL-Cholinergic-26s.pdf slide 12; transcript 10/5"},

{id:"L09-018", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"recall",
 concept:"pilocarpine-alkaloid", tags:["exam-cue"], source:"both",
 stem:"Which of the following is CORRECT about pilocarpine?",
 options:[
  {t:"It does not activate nicotinic receptors", correct:true, why:"Pilocarpine has affinity only for muscarinic receptors; it does not bind or activate nicotinic receptors."},
  {t:"It activates Nn and Nm nicotinic receptors", correct:false, why:"Only acetylcholine activates both nicotinic and muscarinic receptors."},
  {t:"It is a selective M3 agonist", correct:false, why:"Pilocarpine is a non-selective muscarinic agonist (M1, M2, M3)."},
  {t:"It binds irreversibly", correct:false, why:"Pilocarpine is reversible, so it can be outcompeted."},
  {t:"It is a muscarinic antagonist", correct:false, why:"Pilocarpine is an agonist and produces DUMBBELSS."}],
 teach:"Pilocarpine does not bind or activate nicotinic receptors; it has affinity only for muscarinic receptors. Its mechanism is a non-selective (M1, M2, M3), reversible muscarinic agonist, so it produces DUMBBELSS. That it is an alkaloid that is not hydrolyzed is background information.",
 quote:"What I need you to know is that it does not bind or activate the nicotinic receptors. It only has affinity for the muscarinics. That's going to be a very key information for you, so try not to get confused between that, OK.",
 note:"Key changed from 'an alkaloid not hydrolyzed by AChE' to 'does not activate nicotinic receptors': he called the alkaloid/hydrolysis point FYI and the nicotinic point key.",
 cite:"PCOL-Cholinergic-26s.pdf slide 14; transcript 10/5"},

{id:"L09-019", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"agonist-organ-effects", tags:[], source:"both",
 stem:"A muscarinic agonist is given systemically. Which effect is most likely?",
 options:[
  {t:"Increased peristalsis", correct:true, why:"In the GI tract the PNS is the predominant tone, and a muscarinic agonist increases peristalsis and secretion."},
  {t:"Mydriasis", correct:false, why:"An agonist causes miosis; mydriasis is an antagonist (anti-DUMBBELSS) effect."},
  {t:"Dry mouth", correct:false, why:"An agonist causes salivation; dry mouth comes from blocking M3."},
  {t:"Bronchial smooth muscle dilation", correct:false, why:"An agonist causes bronchial constriction through M3."},
  {t:"Tachycardia", correct:false, why:"An agonist causes bradycardia through M2."}],
 teach:"Muscarinic agonists reproduce parasympathetic nervous system (PNS) effects, summarized as DUMBBELSS: GI tract, increased peristalsis and secretion; urinary bladder, micturition; eye, miosis; heart, bradycardia; lungs, bronchial constriction; CNS, vomiting; glands, salivation and lacrimation. Vasodilation also occurs through nitric oxide.",
 quote:"We're gonna increase motilage in tone, so diarrhea, cramping, increased urination, uh, meiosis, which makes your pupil small, bradycardia, bronchial constriction, emesis, uh, secretion, salivation, lachrymation, uh, and, uh, stimulation of the CNS.",
 cite:"PCOL-Cholinergic-26s.pdf slide 13; transcript 10/5"},

{id:"L09-020", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"dumbbelss-select", tags:[], multi:true, source:"both",
 stem:"Which effects are expected after a muscarinic agonist such as bethanechol? Select all that apply.",
 options:[
  {t:"Micturition", correct:true, why:"Urinary bladder: PNS tone; the agonist effect is micturition."},
  {t:"Miosis", correct:true, why:"Eye (iris): PNS tone; the agonist effect is miosis."},
  {t:"Bradycardia", correct:true, why:"Heart: PNS tone; the agonist effect is bradycardia."},
  {t:"Lacrimation", correct:true, why:"Glands: secretion, salivation and lacrimation."},
  {t:"Constipation", correct:false, why:"Constipation is an antagonist effect; the agonist increases peristalsis."},
  {t:"Bronchial dilation", correct:false, why:"The agonist constricts the bronchi through M3."}],
 teach:"Every muscarinic agonist is non-selective, so each can produce the full DUMBBELSS picture: increased GI peristalsis and secretion, micturition, miosis, bradycardia, bronchial constriction, vomiting, and salivation and lacrimation. Bethanechol is one of the agonists listed with similar effects and adverse reactions.",
 quote:"So when we give an agonist, we're gonna produce what the dumbbells, right? We're gonna increase motilage in tone, so diarrhea, cramping, increased urination, uh, meiosis, which makes your pupil small, bradycardia",
 cite:"PCOL-Cholinergic-26s.pdf slide 13; slide 11; transcript 10/5"},

{id:"L09-021", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"pilocarpine-receptor-map", tags:[], source:"both",
 stem:"A patient taking pilocarpine vomits. Which receptor and G protein most likely mediate this effect?",
 options:[
  {t:"M1 in the CNS, Gq", correct:true, why:"CNS = M1 = Gq = emesis."},
  {t:"M2 in the heart, Gi", correct:false, why:"M2 on the heart through Gi lowers heart rate; it does not cause emesis."},
  {t:"M3 on salivary gland, Gq", correct:false, why:"M3 on the salivary gland through Gq causes salivation."},
  {t:"M2 in the CNS, Gs", correct:false, why:"No muscarinic receptor is listed as Gs; emesis is M1 through Gq."}],
 teach:"Pilocarpine is a non-selective, reversible muscarinic agonist, so its effects follow receptor location: heart = M2 = Gi = ↓ heart rate; salivary gland = M3 = Gq = salivation; bronchial smooth muscle = M3 = Gq = bronchial constriction; central nervous system (CNS) = M1 = Gq = emesis.",
 quote:"If it is salivary glands, that's M3s, M3s are GQ, GQ increased calcium, salivation. ... CNS M1s GQ MSS, right?",
 note:"The transcript renders 'emesis' as 'MSS' in 'CNS M1s GQ MSS'; the slide reads 'CNS = M1 = Gq = Emesis'.",
 cite:"PCOL-Cholinergic-26s.pdf slide 14; transcript 10/5"},

{id:"L09-022", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"pilocarpine-heart-m2", tags:[], source:"both",
 stem:"Pilocarpine is given for dry mouth. What does it most likely do to the heart, and through which receptor?",
 options:[
  {t:"Decreases heart rate through M2 (Gi)", correct:true, why:"Heart = M2 = Gi = ↓ heart rate; pilocarpine is non-selective, so it reaches M2 as well as M3."},
  {t:"Increases heart rate through M2 (Gi)", correct:false, why:"Activating M2 lowers heart rate; raising it is the antagonist (atropine) effect."},
  {t:"Decreases heart rate through M3 (Gq)", correct:false, why:"The heart receptor is M2 (Gi), not M3."},
  {t:"No effect; it is M3-selective", correct:false, why:"Pilocarpine is non-selective, and its heart effect is rated +++."}],
 teach:"Pilocarpine is used for its M3 effect on the salivary gland, but it is a non-selective muscarinic agonist, so it also activates M2 on the heart. M2 couples to Gi and lowers heart rate. In the agonist table, pilocarpine's cardiovascular (↓ heart rate) rating is +++.",
 quote:"So for example, if it's the heart, we get what? M2s, M2s G alpha I is inhibitory, so I get what? bradycardia. Your heart becomes much slower.",
 cite:"PCOL-Cholinergic-26s.pdf slide 14; slide 12; transcript 10/5"},

{id:"L09-023", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"agonist-hypotension-no", tags:[], source:"both",
 stem:"A muscarinic agonist lowers blood pressure. Which mechanism is responsible?",
 options:[
  {t:"M3-mediated release of nitric oxide", correct:true, why:"Hypotension is listed as an adverse reaction from M3-mediated release of nitric oxide (NO)."},
  {t:"M2 activation in vascular smooth muscle", correct:false, why:"The vascular effect is assigned to M3 and NO, not to M2."},
  {t:"Parasympathetic nerves on arteries", correct:false, why:"The endothelial M3 receptors are non-innervated."},
  {t:"Blockade of α1 receptors", correct:false, why:"A muscarinic agonist does not act on α1 receptors."}],
 teach:"Endothelial M3 receptors are non-innervated, but a circulating muscarinic agonist reaches them. M3 activation releases nitric oxide (NO), which produces vasodilation and hypotension. Hypotension is listed with miosis-related difficulty in visual accommodation and bronchial constriction as agonist adverse drug reactions (ADRs).",
 quote:"They may get hypertension due to the release of nitric oxide, which is a vasodilator, so that's a little bit of an exception to the rule",
 note:"The transcript has 'hypertension' here, but in the same sentence he calls nitric oxide a vasodilator, and the slide lists 'Hypotension: M3 mediated release of Nitric Oxide'. Keyed to hypotension (likely a transcription error).",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Organ System Effects — 3. Cardiovascular system","t":"Almost all vessels contain endothelial muscarinic receptors that mediate vasodilation, and these receptors are readily blocked by antimuscarinic drugs. The cardiovascular effects of administered direct-acting muscarinic agonists are easily prevented by atropine."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 15; slide 13; slide 5; transcript 10/5"},

{id:"L09-024", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"recall",
 concept:"agonist-adr-accommodation", tags:[], source:"both",
 stem:"A patient using a muscarinic agonist reports difficulty in visual accommodation. Which effect underlies this?",
 options:[
  {t:"Miosis through M3", correct:true, why:"Difficulty in visual accommodation is listed with miosis, an M3 effect on the eye."},
  {t:"Mydriasis through M3", correct:false, why:"Mydriasis follows M3 blockade; the agonist constricts the pupil."},
  {t:"Miosis through M2", correct:false, why:"The eye receptor is M3; M2 is the heart."},
  {t:"Hypotension through M2", correct:false, why:"Hypotension is a separate ADR, mediated by M3 release of nitric oxide."}],
 teach:"The listed adverse drug reactions (ADRs) of muscarinic agonists are DUMBBELSS, difficulty in visual accommodation (miosis, M3 on the eye), hypotension (M3-mediated release of nitric oxide) and bronchial constriction (M3 → Gq → phospholipase C (PLC) → inositol trisphosphate (IP3) → Ca2+).",
 quote:"We're gonna get the meiosis, so patients are gonna complain they can't see at night because it's too dark, not enough light get inside of their pupils.",
 cite:"PCOL-Cholinergic-26s.pdf slide 15; transcript 10/5"},

{id:"L09-025", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"recall",
 concept:"atropine-scopolamine-class", tags:[], source:"both",
 stem:"Which of the following is CORRECT about atropine and scopolamine?",
 options:[
  {t:"Naturally occurring, reversible alkaloids", correct:true, why:"Both are naturally occurring alkaloids, non-selective and reversible muscarinic antagonists."},
  {t:"Synthetic antagonists selective for the M3 receptor", correct:false, why:"They are natural alkaloids and non-selective."},
  {t:"Irreversible muscarinic antagonists", correct:false, why:"They are reversible."},
  {t:"Synthetic agonists at M1, M2 and M3", correct:false, why:"They are antagonists; atropine blocks M1, M2 and M3."}],
 teach:"Atropine and scopolamine are naturally occurring alkaloids. Both are non-selective, reversible muscarinic antagonists: atropine blocks M1, M2 and M3. Scopolamine is also an antagonist at histamine and serotonin receptors.",
 quote:"let's talk about our muscarinic antagonists. Those are gonna be naturally occurring. ... This drug is going to be also reversible as well.",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Pharmacodynamics — A. Mechanism of Action","t":"Atropine causes reversible (surmountable) blockade of cholinomimetic actions at muscarinic receptors: a small dose of atropine can be overcome by a larger concentration of acetylcholine. Atropine does not distinguish among the M1–M5 subgroups."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 17; transcript 10/5"},

{id:"L09-026", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"tell",
 concept:"scopolamine-extra-receptors", tags:[], source:"both",
 stem:"Besides muscarinic receptors, scopolamine is an antagonist at which receptors?",
 options:[
  {t:"Histamine and serotonin", correct:true, why:"Scopolamine is an antagonist to the muscarinic, histamine and serotonin receptors."},
  {t:"Nicotinic Nn and Nm", correct:false, why:"No nicotinic action is listed for scopolamine."},
  {t:"α1 and β1", correct:false, why:"No adrenergic action is listed for scopolamine."},
  {t:"Dopamine and GABA receptors", correct:false, why:"Dopamine and GABA appear on the Parkinson (benztropine) slide, not as scopolamine targets."}],
 teach:"Atropine is listed as blocking M1, M2 and M3. Scopolamine is listed as an antagonist at muscarinic, histamine and serotonin receptors. Scopolamine penetrates the central nervous system (CNS) more rapidly and is used for motion sickness.",
 quote:"That one is really non-selective. That not only blocks all the muscarinics, but also histamine and serotonin receptors. So you're gonna have a much broader effect.",
 cite:"PCOL-Cholinergic-26s.pdf slide 17; transcript 10/5"},

{id:"L09-027", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"apply",
 concept:"atropine-toxicity", tags:[], multi:true, source:"both",
 stem:"A child eats berries of Atropa belladonna. Which findings are expected? Select all that apply.",
 options:[
  {t:"Dry mouth and skin", correct:true, why:"Dry as a bone: secretion is blocked."},
  {t:"Hot, red skin", correct:true, why:"Hot as a pistol and red as a beet."},
  {t:"Blurred vision with mydriasis", correct:true, why:"Blind as a bat; the pupil (M3) dilates."},
  {t:"Confusion", correct:true, why:"Mad as a hatter: atropine acts centrally as well as peripherally."},
  {t:"Bradycardia", correct:false, why:"Blocking M2 on the heart raises heart rate; bradycardia is an agonist effect."},
  {t:"Diarrhea", correct:false, why:"Blocking M3 in the GI tract causes constipation."}],
 teach:"Atropine comes from Atropa belladonna and Angel's Trumpet Flower and acts centrally and peripherally in a dose-dependent way. Toxicity: dry as a bone, hot as a pistol, red as a beet, blind as a bat, mad as a hatter. An overdose of a muscarinic antagonist is anti-DUMBBELSS: ↑ heart rate (M2), mydriasis (M3) and constipation (M3).",
 quote:"dry as a bone. You can't sweat, you can't salivate. And then you become hot as a pistol because you can't lose heat, you become very red, uh, red as a beet, uh, blind as a bat, you can't see, and then eventually as the dose get higher and higher, you start to get mad as a header.",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Adverse Effects","t":"Atropine-poisoned individuals show dry mouth, mydriasis, tachycardia, hot and flushed skin, agitation and delirium, often with elevated body temperature. Infants and children are especially sensitive to the hyperthermic effects of atropine."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 18; slide 19; transcript 10/5"},

{id:"L09-028", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"apply",
 concept:"atropine-heart-m2", tags:[], source:"both",
 stem:"Why does atropine increase heart rate?",
 options:[
  {t:"It blocks M2, and PNS tone predominates", correct:true, why:"Heart = M2 = Gi = ↑ heart rate with atropine, because the PNS is the predominant tone at the heart."},
  {t:"It activates β receptors on the SA node", correct:false, why:"Atropine is a muscarinic antagonist with no stated β action."},
  {t:"It blocks M3 on the SA node", correct:false, why:"The SA node receptor is M2."},
  {t:"It activates M2 through the Gs protein", correct:false, why:"Atropine blocks M2; M2 is Gi, not Gs."}],
 teach:"At rest the heart is under predominant parasympathetic (PNS) tone through M2 (Gi), which slows it. Atropine blocks M2, removing that brake, so heart rate rises. The same logic gives mydriasis (M3 on the pupil, Gq) and constipation (M3 in the GI tract, Gq).",
 quote:"If I'm looking over here in the heart, who is the predominant tone, the parasympathetic. So if I block the M2s, now the sympathetic is unopposed, I'm going to get what? tachycardia.",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Organ System Effects — 3. Cardiovascular system","t":"The sinoatrial node is very sensitive to muscarinic blockade, and moderate to high doses of atropine cause tachycardia by blocking vagal slowing. Lower doses often cause an initial bradycardia, attributed to block of prejunctional M1 autoreceptors."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 19; transcript 10/5"},

{id:"L09-029", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"recall",
 concept:"atropine-uses", tags:[], source:"both",
 stem:"Which of the following is a use of atropine?",
 options:[
  {t:"Muscarinic agonist overdose", correct:true, why:"Atropine treats muscarinic agonist overdose (bradycardia or atrioventricular nodal block) and organophosphate poisoning."},
  {t:"Glaucoma", correct:false, why:"Glaucoma is treated with the agonists carbachol and pilocarpine."},
  {t:"Urinary retention after surgery", correct:false, why:"Urinary retention is treated with the agonist bethanechol; atropine would worsen it."},
  {t:"Xerostomia", correct:false, why:"Xerostomia is treated with pilocarpine or cevimeline; atropine causes dry mouth."}],
 teach:"Atropine uses: treatment of muscarinic agonist overdose (bradycardia or atrioventricular nodal block), and organophosphate poisoning if the organophosphate is short acting, 2–5 mg every 10–15 min.",
 quote:"patients with severe low heart rate so we can give atropine to bring their heart rate up or perhaps they have what is called an AV block ... we can give atropine to alleviate the dumbbells.",
 note:"Dose: the slide gives 2–5 mg every 10–15 min; Katzung Ch. 8 gives 1–2 mg atropine sulfate IV every 5–15 minutes. He did not give a dose in the audio, so the dose is not tested.",
 cite:"PCOL-Cholinergic-26s.pdf slide 20; transcript 10/5"},

{id:"L09-030", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"apply",
 concept:"organophosphate-atropine", tags:[], source:"both",
 stem:"A patient sprays an organophosphate insecticide on his food and arrives at the hospital with severe DUMBBELSS. Why is atropine given?",
 options:[
  {t:"It blocks the muscarinic receptors", correct:true, why:"Atropine outcompetes the excess acetylcholine at muscarinic receptors and opposes its effects."},
  {t:"It breaks the organophosphate's bond to the enzyme", correct:false, why:"Atropine cannot fix the binding to the cholinesterase enzyme; it only blocks the muscarinic effects."},
  {t:"It inhibits acetylcholinesterase", correct:false, why:"Inhibiting the enzyme is what the organophosphate does; that is the cause of the excess acetylcholine."},
  {t:"It blocks nicotinic receptors at the NMJ", correct:false, why:"Atropine has affinity only for muscarinic receptors, not the neuromuscular junction (NMJ) nicotinic receptors."}],
 teach:"Organophosphates form covalent bonds with the cholinesterase enzyme, so they are irreversible and acetylcholine accumulates: DUMBBELSS 'on steroids'. Atropine cannot fix the binding to the enzyme, but it is a reversible muscarinic antagonist that outcompetes acetylcholine at muscarinic receptors and so manages the DUMBBELSS.",
 quote:"Remember those drugs are irreversible. They form covalent bonds, which means that now we have too much acetylcholine going around. ... So how can we manage the dumbbells? By giving atropine. Atropine is gonna. Oppose the effects of those cholinergic.",
 note:"Rewritten from a dose–response curve item (organophosphate shifts the ACh curve left, atropine shifts it back right): dose–response curves will not be on Exam 2.",
 cite:"PCOL-Cholinergic-26s.pdf slides 20–23; transcript 10/5"},

{id:"L09-031", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"tell",
 concept:"scopolamine-cns-motion", tags:[], source:"both",
 stem:"Which muscarinic antagonist penetrates the CNS more rapidly and is used for motion sickness?",
 options:[
  {t:"Scopolamine", correct:true, why:"Scopolamine penetrates the central nervous system (CNS) more rapidly and is used for motion sickness."},
  {t:"Ipratropium", correct:false, why:"Ipratropium is inhaled for the lungs, with less systemic effect."},
  {t:"Tropicamide", correct:false, why:"Tropicamide is used in the eye for pupil dilation."},
  {t:"Trospium", correct:false, why:"Trospium is an overactive bladder drug in the group with the fewest CNS effects."},
  {t:"Benztropine", correct:false, why:"Benztropine is the drug used in Parkinson's patients treated with L-Dopa for tremor and rigidity."}],
 teach:"Scopolamine penetrates the central nervous system (CNS) more rapidly than atropine. It is used for motion sickness, and its CNS effects include drowsiness, euphoria and amnesia, on top of the peripheral anti-DUMBBELSS effects.",
 quote:"So scopolamine is a non-selective muscarinic antagonist, uh, most times we use for motion sickness.",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Chemistry & Pharmacokinetics — C. Distribution; Therapeutic Applications — Motion sickness","t":"Scopolamine is rapidly and fully distributed into the CNS, where it has greater effects than most other antimuscarinic drugs. It is one of the oldest remedies for seasickness and can be given by injection, by mouth or as a transdermal patch."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 24; transcript 10/5"},

{id:"L09-032", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"apply",
 concept:"benztropine-parkinson", tags:[], source:"both",
 stem:"A patient with Parkinson's disease on L-Dopa still has tremor and rigidity. Benztropine is added. What is the basis for this?",
 options:[
  {t:"Dopaminergic loss leaves striatal ACh unopposed", correct:true, why:"With the dopamine neurons lost, acetylcholine activity in the striatum is too high, and benztropine, an M1 antagonist, blocks it."},
  {t:"Benztropine is a dopamine agonist", correct:false, why:"Benztropine is an atropine analog, a muscarinic (M1) antagonist, not a dopamine agonist."},
  {t:"Benztropine activates M1 in the striatum", correct:false, why:"Benztropine blocks M1 in the brain; it does not activate it."},
  {t:"Benztropine restores the lost striatal GABA neuron output", correct:false, why:"GABA neurons appear in the striatal diagram, but benztropine acts on the cholinergic side."}],
 teach:"In Parkinson's disease the dopamine neurons to the basal ganglia are destroyed (symptoms appear after about 70–80% loss). Dopamine normally acts on D2 receptors (Gαi, inhibitory) to restrain acetylcholine; without it there is too much acetylcholine activity. Benztropine (Cogentin), an atropine analog that is more selective for M1 in the brain, is adjunct therapy to L-Dopa to decrease rigidity and tremor, with fewer anti-DUMBBELSS effects elsewhere.",
 quote:"So the benzotropine can be used as adjunct therapy to the L-dopa to help decrease some of the rigidity and some of the tremor associated with the Parkinson's disease ... benzotropine is more selective to the beta 1s in the to the M1s in the brain, and it's gonna have less of those anti-dumbbells",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Organ System Effects — 1. Central nervous system","t":"Parkinsonian tremor and rigidity seem to result from a relative excess of cholinergic activity because of a deficiency of dopaminergic activity in the basal ganglia–striatum system. Combining an antimuscarinic agent with levodopa can sometimes give more effective therapy than either drug alone."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 25; transcript 10/5"},

{id:"L09-033", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"apply",
 concept:"tropicamide-mydriasis", tags:[], source:"both",
 stem:"Tropicamide drops are placed in the eye before an exam. Why does the pupil dilate?",
 options:[
  {t:"M3 is blocked, leaving SNS dilation unopposed", correct:true, why:"Blocking M3 removes PNS pupil constriction, so SNS dilation is unopposed and mydriasis results."},
  {t:"It activates α1 receptors on the pupil dilator muscle", correct:false, why:"Tropicamide is a muscarinic antagonist; it does not act on α1."},
  {t:"It blocks M2 on the iris", correct:false, why:"The pupil constrictor pathway is M3 (Gq)."},
  {t:"It activates M3 through Gq", correct:false, why:"Activating M3 causes miosis; tropicamide blocks M3."}],
 teach:"The sympathetic nervous system (SNS) dilates the pupil and the parasympathetic nervous system (PNS) constricts it through M3 → Gq → PLC → IP3 and Ca2+ (miosis). Tropicamide blocks M3, so SNS dilation is unopposed and the pupil dilates (mydriasis); its use is optical, for pupil dilation.",
 quote:"So if I block the M3s, which are in the eye and typically cause Kapuchi GQ, I can't take away the constriction and what I'm gonna get the dilation, right?",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Organ System Effects — 2. Eye; Table 8–2","t":"The pupillary constrictor muscle depends on M3 activation; topical antimuscarinics block it and leave sympathetic dilator activity unopposed, giving mydriasis. Tropicamide has the shortest duration of the ophthalmic antimuscarinics, 15–60 minutes."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 26; transcript 10/5"},

{id:"L09-034", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"tell",
 concept:"ipratropium-vs-tiotropium", tags:[], source:"both",
 stem:"Which of the following is CORRECT about ipratropium and tiotropium?",
 options:[
  {t:"Ipratropium is a SAMA; tiotropium a LAMA", correct:true, why:"Ipratropium (Atrovent) is a short-acting muscarinic antagonist (SAMA), 3–4 times a day; tiotropium (Spiriva) is a long-acting muscarinic antagonist (LAMA), once a day."},
  {t:"Ipratropium is a LAMA; tiotropium a SAMA", correct:false, why:"This reverses them."},
  {t:"Both are muscarinic agonists", correct:false, why:"Both carry 'trop' and are atropine-like muscarinic antagonists."},
  {t:"Both are taken orally", correct:false, why:"Both are inhaled, which gives less systemic effect."}],
 teach:"Inhaled muscarinic antagonists stay mainly in the airways. Ipratropium (Atrovent) is a short-acting muscarinic antagonist (SAMA), dosed 3–4 times a day for relief through the day. Tiotropium (Spiriva) is a long-acting muscarinic antagonist (LAMA), dosed once a day. Both have 'trop' in the name, like atropine, and both are less selective than aclidinium and umeclidinium.",
 quote:"So we have what is called SAA, short acting muscarinic antagonist, and we have the lemmas, the long acting muscarinic antagonist. ... ipratropium, that's the short acting called SAA, right? Or the teotropin-like drugs, which are called the lemmas.",
 note:"One deck slide lists ipratropium as M1, M2 and M3 and tiotropium as M1 and M3; Katzung lists tiotropium among M3 antagonists; in the audio he calls both 'less selective' and able to reach M2 if they get systemic. The question avoids tiotropium's subtypes.",
 cite:"PCOL-Cholinergic-26s.pdf slide 28; transcript 10/5"},

{id:"L09-035", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"recall",
 concept:"aclidinium-umeclidinium", tags:[], source:"both",
 stem:"Aclidinium and umeclidinium are best described by which of the following?",
 options:[
  {t:"High M3 affinity, slow dissociation", correct:true, why:"They have high affinity for M3 and are reversible but dissociate slowly."},
  {t:"Irreversible M3 antagonists", correct:false, why:"They are reversible, though slow to dissociate."},
  {t:"Oral antimuscarinics for overactive bladder", correct:false, why:"They are in the inhaled lung group with ipratropium and tiotropium."},
  {t:"Inhaled M3 agonists", correct:false, why:"They are muscarinic antagonists; an M3 agonist would constrict the bronchi."}],
 teach:"Aclidinium and umeclidinium are inhaled muscarinic antagonists with high affinity for M3. They are reversible but dissociate slowly from the receptor. Blocking M3 on bronchial smooth muscle removes PNS bronchial constriction in asthma and chronic obstructive pulmonary disease (COPD).",
 quote:"So they have a very high tight binding, so a very high affinity, and they're more selective to the M3s.",
 reading:[{"src":"Katzung 16e, Ch. 8","sec":"Therapeutic Applications — C. Respiratory Disorders","t":"Ipratropium, tiotropium, aclidinium and umeclidinium are synthetic atropine analogs used by inhalation in COPD, alone or with a long-acting β agonist. Tiotropium and umeclidinium can be given once daily because they dissociate slowly from M3 receptors; aclidinium is given twice daily."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 28; transcript 10/5"},

{id:"L09-036", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"apply",
 concept:"copd-rationale", tags:[], source:"both",
 stem:"Why does an inhaled muscarinic antagonist relieve airflow obstruction in chronic obstructive pulmonary disease (COPD)?",
 options:[
  {t:"It blocks M3-driven bronchial constriction", correct:true, why:"The lungs are PNS only, and M3 → Gq → PLC → IP3 and Ca2+ constricts bronchial smooth muscle; blocking M3 stops it."},
  {t:"It blocks M2 on bronchial smooth muscle", correct:false, why:"The bronchial smooth muscle receptor is M3."},
  {t:"It activates sympathetic nerve fibers in the lung", correct:false, why:"The lungs are marked PNS only."},
  {t:"It raises IP3 in the airway", correct:false, why:"IP3 and Ca2+ drive constriction; the antagonist prevents the rise."}],
 teach:"COPD involves chronic inflammation with reduced airflow and mucus production (obstruction). The lungs receive parasympathetic nervous system (PNS) input only, and on bronchial smooth muscle M3 → Gq → phospholipase C (PLC) → inositol trisphosphate (IP3) and Ca2+ produces bronchial constriction. Blocking M3 removes that signal; inhalation gives less systemic effect.",
 quote:"if the lungs are only parasympathetic and they have M3s, M3s are GQ and increased calcium, thus by blocking that constriction, I'm going to get what? dilation, right?",
 cite:"PCOL-Cholinergic-26s.pdf slide 27; slide 28; transcript 10/5"},

{id:"L09-037", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"bladder", skill:"recall",
 concept:"oab-moa", tags:[], multi:true, source:"both",
 stem:"Which statements are CORRECT about the overactive bladder antimuscarinics oxybutynin, trospium and solifenacin? Select all that apply.",
 options:[
  {t:"More selective toward bladder M3", correct:true, why:"They are more selective toward the M3 receptors in the bladder."},
  {t:"Hepatic metabolism by 3A4 or 2D6", correct:true, why:"The mechanism line lists hepatic metabolism (3A4 or 2D6)."},
  {t:"4–10× the antispasmodic effect of atropine", correct:true, why:"They have 4–10× the antispasmodic effect, with 1/5 the anticholinergic effect of atropine."},
  {t:"Irreversible receptor binding", correct:false, why:"They are reversible."},
  {t:"Goal: increase bladder emptying", correct:false, why:"The goal is to decrease urgency, frequency and leakage; emptying is the bethanechol use."}],
 teach:"Oxybutynin (Ditropan) is the oldest and cheapest; trospium has 'trop' in the name (atropine-like); solifenacin (Vesicare) is newer, more expensive and more selective. They are reversible and hepatically metabolized (3A4 or 2D6), and are designed to be more selective toward bladder M3: 1/5 the anticholinergic effect of atropine and 4–10× the antispasmodic effect. Blocking bladder M3 relaxes the bladder to decrease urgency, frequency and leakage.",
 quote:"these drugs, they are designed, bless you, to be more selective to the M3s in the bladder",
 cite:"PCOL-Cholinergic-26s.pdf slide 29; transcript 10/5"},

{id:"L09-038", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"bladder", skill:"apply",
 concept:"oab-cns-order", tags:[], source:"both",
 stem:"An older patient on oxybutynin for overactive bladder becomes confused and drowsy. Which drug is in the group least likely to cause these central nervous system (CNS) effects?",
 options:[
  {t:"Solifenacin", correct:true, why:"Solifenacin (Vesicare) is the most M3-selective, at the bottom of his ranking: less M1 binding in the brain, fewer anti-DUMBBELSS effects."},
  {t:"Atropine", correct:false, why:"Atropine is non-selective (M1, M2, M3) and acts centrally."},
  {t:"Scopolamine", correct:false, why:"Scopolamine penetrates the CNS more rapidly and causes drowsiness and amnesia."},
  {t:"Benztropine", correct:false, why:"Benztropine is more selective for M1 in the brain, the receptor behind these CNS effects."}],
 teach:"Oxybutynin is at the top of the ranking: the oldest, least selective, blocking M1 and M3, so it reaches M1 in the brain and causes sedation, fatigue and slower thinking. The newer, more expensive drugs bind M1 less and M3 more at therapeutic doses; solifenacin (Vesicare) at the bottom is the most M3-selective, with the fewest anti-DUMBBELSS effects. All are dose-dependent.",
 quote:"The ones on the top are very non-selective, as the one in the bottom, like VESIcare is more selective than M3, less anti-dumbbell side effects, OK?",
 note:"Exam drugs are oxybutynin, trospium and solifenacin. One deck slide ranks CNS effects oxybutynin (M1 & M3) > tolterodine, fesoterodine (M1 & M3) > solifenacin, darifenacin, trospium (M3); in the audio he ranks only oxybutynin (top, least selective) and Vesicare (bottom, most selective) and does not place trospium. Katzung calls trospium nonselective. Trospium's rank is not keyed.",
 cite:"PCOL-Cholinergic-26s.pdf slide 30; transcript 10/5"},

{id:"L09-039", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"bladder", skill:"recall",
 concept:"oab-xerostomia-m3", tags:[], source:"both",
 stem:"Which adverse effects occur with all the overactive bladder antimuscarinics, and through which receptor?",
 options:[
  {t:"Dry mouth and constipation; M3", correct:true, why:"Xerostomia (dry mouth) and constipation are M3 effects and occur with all muscarinic antagonists."},
  {t:"Confusion and drowsiness; M3 receptor", correct:false, why:"Confusion and drowsiness come from M1 blockade in the brain and are greatest with oxybutynin, not shared equally."},
  {t:"Bradycardia and miosis; M2", correct:false, why:"Bradycardia and miosis are agonist effects."},
  {t:"Diarrhea and salivation; M3", correct:false, why:"These are DUMBBELSS (agonist) effects; antagonists cause the opposite."}],
 teach:"All the bladder antimuscarinics can cause anti-DUMBBELSS. Xerostomia (dry mouth) and constipation come from M3 blockade and occur with all muscarinic antagonists. Central nervous system (CNS) effects differ by drug and track M1 blockade.",
 quote:"But all those dependent, right? If I give enough of VESIcare, I'm gonna get all the anti-dumbbells.",
 note:"The student drug list says solifenacin, darifenacin and trospium are least likely to cause anti-DUMBBELSS. In the audio he agrees that the more M3-selective drug (Vesicare) has fewer anti-DUMBBELSS effects at therapeutic doses, but says all are dose-dependent: enough of any of them gives all the anti-DUMBBELSS.",
 cite:"PCOL-Cholinergic-26s.pdf slide 30; transcript 10/5"},

{id:"L09-040", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"bladder", skill:"apply",
 concept:"anti-dumbbelss-effects", tags:[], multi:true, source:"both",
 stem:"Which pharmacological effects are expected from a muscarinic antagonist? Select all that apply.",
 options:[
  {t:"Tachycardia", correct:true, why:"Cardiovascular: tachycardia, from M2 blockade."},
  {t:"Bronchial dilation", correct:true, why:"Respiratory: bronchial dilation."},
  {t:"Pupil dilation", correct:true, why:"Eye: pupil dilation."},
  {t:"Hallucinations and restlessness", correct:true, why:"CNS: hallucinations, restlessness and coma, from M1 blockade, dose-dependent."},
  {t:"Miosis", correct:false, why:"Miosis is an agonist effect."},
  {t:"Increased salivation", correct:false, why:"Antagonists cause dry mouth."}],
 teach:"Muscarinic antagonists are reversible and mostly non-selective, and all have affinity for M3. Their effects are anti-DUMBBELSS: dry mouth and constipation, tachycardia (M2), bronchial dilation, pupil dilation, and central nervous system (CNS) hallucinations, restlessness and coma (M1). These depend on dose and selectivity.",
 quote:"The anti-dumbbells, if it is for diarrhea, you get constipation. You for urination, you can't pee. Meiosis, you get the midriasis. Your pupils dilate, instead of getting the bronchial constriction, you get bronchial dilation.",
 cite:"PCOL-Cholinergic-26s.pdf slide 32; transcript 10/5"},

{id:"L09-042", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"cholinergic-overdose-not-occur", tags:["variant"], source:"both",
 stem:"If one overdoses on a cholinergic agonist, which of the following symptoms would NOT occur?",
 options:[
  {t:"Decreased urination", correct:true, why:"The agonist squeezes the bladder, so urination increases; decreased urination would not occur."},
  {t:"Diarrhea", correct:false, why:"Diarrhea occurs: more gut motility and tone."},
  {t:"Miosis", correct:false, why:"Miosis occurs: M3 (Gq) squeezes the circular muscle of the pupil."},
  {t:"Bradycardia", correct:false, why:"Bradycardia occurs: M2 (Gαi) slows the heart."},
  {t:"Bronchial constriction", correct:false, why:"Bronchial constriction occurs through M3 in the lungs."}],
 teach:"A cholinergic agonist overdose produces the DUMBBELSS: diarrhea, more urination, miosis, bradycardia, bronchial constriction, emesis, salivation and lacrimation. Decreased urination is the opposite (anti-DUMBBELSS) effect of an antagonist.",
 quote:"B is you urinate more, it's not that you can't urinate. ... it would be all the above with the exception of uh B as in boy, OK? Maybe last year was which of these would not occur and that was the right answer",
 note:"Not this year's poll. This year's 10/5 poll asked which symptom is most likely to occur (Diarrhea / Can't urinate / Miosis / Bradycardia / All of the above) and he keyed all of the above with the exception of B, can't urinate; he then said, \"Maybe last year was which of these would not occur and that was the right answer\". This item asks that NOT version, with decreased urination (can't urinate) as the answer.",
 cite:"PCOL-Cholinergic-26s.pdf slide 13; transcript 10/5 (last year's version of the 10/5 poll)"},

{id:"L09-045", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"agonist-asthma-contraindication", tags:["in-class"], source:"both",
 stem:"Which patient would be contraindicated to receive a muscarinic agonist?",
 options:[
  {t:"A patient with asthma", correct:true, why:"A muscarinic agonist constricts the bronchi through M3 and would squeeze the airway even more."},
  {t:"A patient with dry mouth", correct:false, why:"Salivation is an agonist effect; dry mouth is what pilocarpine is given for."},
  {t:"A patient with urinary retention", correct:false, why:"An agonist squeezes the bladder and increases urination, which helps retention."},
  {t:"A patient with tachycardia", correct:false, why:"An agonist slows the heart through M2, which lowers a fast heart rate."}],
 teach:"Bronchial constriction (M3 → Gq → phospholipase C (PLC) → inositol trisphosphate (IP3) → Ca2+) is one of the main side effects of muscarinic agonists. In a patient with asthma it squeezes the bronchi even more, so asthma is a contraindication that follows directly from the mechanism and site of action.",
 quote:"So who do you think would be contraindicated to get a muscarinic agonist? Patients with asthma, they can't breathe, you're gonna squeeze the bronchus even more.",
 cite:"PCOL-Cholinergic-26s.pdf slide 15; transcript 10/5"},

{id:"L09-046", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"apply",
 concept:"m2-k-hyperpolarization", tags:["in-class"], source:"both",
 stem:"In the heart, the βγ subunits released by M2 activation open potassium (K+) channels. Which describes what follows?",
 options:[
  {t:"K+ leaves; membrane hyperpolarizes", correct:true, why:"K+ is high inside, so it flows out; the membrane becomes more negative and voltage-gated Ca2+ channels cannot open."},
  {t:"K+ enters; membrane depolarizes", correct:false, why:"K+ is high inside the cell, so it leaves, not enters."},
  {t:"K+ leaves; membrane depolarizes", correct:false, why:"Positive charge leaving makes the membrane more negative: hyperpolarization."},
  {t:"K+ enters; membrane hyperpolarizes", correct:false, why:"K+ moves out of the cell, down its gradient."}],
 teach:"Potassium is high inside the cell, so opening K+ channels lets K+ leave and the membrane becomes very negative (hyperpolarization). Voltage-gated Ca2+ channels then cannot open, so less Ca2+ enters. This is M2's second mechanism; the first is Gαi inhibiting adenylyl cyclase so cyclic AMP (cAMP) falls. Both give bradycardia and less contractile force.",
 quote:"Is potassium high inside or outside of the cell? Inside, so where it wants to go outside, the more potassium it gets out, the more negative the membrane becomes, and is that what is called hyper polarization.",
 cite:"PCOL-Cholinergic-26s.pdf slide 8; transcript 10/5"},

{id:"L09-047", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"recall",
 concept:"d2-gi-parkinson", tags:["in-class"], source:"both",
 stem:"In the basal ganglia, dopamine acts on D2 receptors to restrain acetylcholine. Which G protein does the D2 receptor couple to?",
 options:[
  {t:"Gαi, inhibitory", correct:true, why:"Like α2 and M2, D2 couples to Gαi and is inhibitory, which restrains acetylcholine."},
  {t:"Gαq, stimulatory", correct:false, why:"Gαq belongs to M1, M3 and α1."},
  {t:"Gαs, stimulatory", correct:false, why:"Gαs belongs to the β receptors."},
  {t:"None; D2 is an ion channel", correct:false, why:"D2 is a G protein–coupled receptor; the cholinergic ion channels are nicotinic."}],
 teach:"Receptors numbered 2 are often Gαi: α2, M2 and D2. With healthy dopamine neurons, dopamine on D2 (inhibitory) restrains acetylcholine and allows fine-tuned movement. As dopamine neurons are lost in Parkinson's disease, acetylcholine activity becomes too high, so an M1 antagonist such as benztropine is added to L-Dopa.",
 quote:"Now if we have to guess, why do you think a D2 is going to be copper 2? Remember, the two alpha 2s are G alpha I, M2s or G alphaI, D2, G alpha I, right? So, most of the chews, not all of them, but a lot of them are alpha I. So, they're gonna be inhibitory.",
 cite:"PCOL-Cholinergic-26s.pdf slide 25; transcript 10/5"},

{id:"L09-048", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"bladder", skill:"apply",
 concept:"oxybutynin-m1-sedation", tags:["in-class"], source:"both",
 stem:"Oxybutynin blocks M1 as well as M3 receptors. Which effect follows from the M1 blockade?",
 options:[
  {t:"Sedation", correct:true, why:"M1 is in the brain; blocking it gives sedation, fatigue and slower thinking."},
  {t:"Dry mouth", correct:false, why:"Dry mouth comes from M3 blockade at the salivary glands."},
  {t:"Constipation", correct:false, why:"Constipation comes from M3 blockade in the gut."},
  {t:"Tachycardia", correct:false, why:"Tachycardia comes from M2 blockade at the heart."}],
 teach:"Oxybutynin is the oldest, least selective overactive bladder antimuscarinic: it blocks M1 and M3. M1 is in the brain, so blocking it causes sedation, fatigue and slower thinking. An M1 agonist stimulates; an M1 antagonist sedates.",
 quote:"They can affect the M1s and they can affect the M3s. What effect they would have by affecting the M1s? What would be the site of action? The brain, right? So they'll cause sedation. A little bit of fatigue, thought process may be a little bit slower.",
 cite:"PCOL-Cholinergic-26s.pdf slide 30; transcript 10/5"},

{id:"L09-049", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"recall",
 concept:"trop-nomenclature", tags:["exam-cue"], source:"both",
 stem:"Ipratropium, tiotropium, trospium and benztropine all contain \"trop\" in their names. What does that suggest?",
 options:[
  {t:"Atropine-like muscarinic antagonist", correct:true, why:"Any drug with 'trop' in it is an antagonist like atropine."},
  {t:"Cholinergic muscarinic agonist", correct:false, why:"The agonists carry 'chol' (methacholine, carbachol, bethanechol)."},
  {t:"Acetylcholinesterase inhibitor", correct:false, why:"These drugs block the muscarinic receptor; they do not act on the enzyme."},
  {t:"Nicotinic Nn receptor partial agonist", correct:false, why:"A nicotinic Nn partial agonist is varenicline, a different class."}],
 teach:"The name predicts the mechanism. 'Chol' marks the cholinergic (muscarinic) agonists: methacholine, carbachol, bethanechol. 'Trop' marks the atropine-like muscarinic antagonists: atropine, ipratropium, tiotropium, trospium, benztropine, tropicamide.",
 quote:"Our prototypical agent over here is gonna be atropine. So, any drug that has a trope in it, atropine, tiotropium, ipratropium, is gonna be what? an antagonist like atropine, right?",
 cite:"PCOL-Cholinergic-26s.pdf slides 17, 25, 28, 29; transcript 10/5"},

{id:"L09-050", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"apply",
 concept:"dramamine-anticholinergic", tags:["in-class"], source:"transcript",
 stem:"Dramamine, used for nausea and motion sickness, blocks muscarinic and some histamine receptors. A patient taking it to fall asleep reports constipation. Which explains the constipation?",
 options:[
  {t:"Muscarinic blockade in the gut", correct:true, why:"Blocking gut muscarinic (M3) receptors removes PNS motility: anti-DUMBBELSS constipation."},
  {t:"Muscarinic activation in the gut", correct:false, why:"Activating gut muscarinic receptors increases motility (diarrhea)."},
  {t:"Nicotinic blockade at the NMJ", correct:false, why:"Nicotinic receptors at the neuromuscular junction (NMJ) control skeletal muscle, not gut motility."},
  {t:"Histamine receptor activation", correct:false, why:"Dramamine blocks, not activates, histamine receptors."}],
 teach:"Dramamine is a non-selective drug that blocks muscarinic and some histamine receptors; it is used for nausea and motion sickness and sedates most people. Blocking muscarinic receptors in the gut gives anti-DUMBBELSS constipation, a problem for many elderly patients.",
 quote:"What typically do we use Dramamine for? Nausea, right? So drama means a non-selective drug that can seem to bind and block not only muscarinics but also some histamines and it's gonna knock out most people ... as a pharmacologist, let me tell you, this is what is causing the constipation, right? So that can be a problem for a lot of your elderly patients.",
 cite:"transcript 10/5 (no slide)"},

{id:"L09-051", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"apply",
 concept:"inhaled-low-bioavailability", tags:["in-class"], source:"both",
 stem:"Ipratropium and tiotropium are less selective muscarinic antagonists. Why do they cause few systemic anti-DUMBBELSS effects when inhaled?",
 options:[
  {t:"Low bioavailability keeps them in the lungs", correct:true, why:"Their structure was changed so bioavailability is very low; they stay primarily in the airways."},
  {t:"They bind only the M3 receptors of the bronchi", correct:false, why:"They are less selective; they can affect M2 or M3 if they get systemic."},
  {t:"They are muscarinic agonists", correct:false, why:"They are atropine-like antagonists ('trop')."},
  {t:"They bind irreversibly in the airway", correct:false, why:"They are reversible antagonists."}],
 teach:"For a patient with chronic obstructive pulmonary disease (COPD) using an inhaler, the drug should act in the lungs. Ipratropium and tiotropium are less selective, but their chemical structure gives very low bioavailability: swallowed drug is broken down in the gut and liver, so they stay in the airways. Aclidinium and umeclidinium are more selective for M3.",
 quote:"The ipratropium and the tiotropium are less selective, but what we have done for them is change their chemical structure so that they have very low bioavailability, so they stay primarily within the lungs.",
 cite:"PCOL-Cholinergic-26s.pdf slide 28; transcript 10/5"},

{id:"L09-052", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"bladder", skill:"tell",
 concept:"oxybutynin-vs-solifenacin", tags:[], multi:true, source:"both",
 stem:"Which statements are CORRECT about oxybutynin and solifenacin? Select all that apply.",
 options:[
  {t:"Oxybutynin is the oldest and least selective", correct:true, why:"Oxybutynin is the oldest and cheapest, at the non-selective top of the ranking."},
  {t:"Solifenacin is more selective for M3", correct:true, why:"Solifenacin (Vesicare) is at the bottom of the ranking: more M3-selective."},
  {t:"Enough solifenacin causes anti-DUMBBELSS", correct:true, why:"The effects are dose-dependent: enough Vesicare gives all the anti-DUMBBELSS."},
  {t:"Solifenacin sedates more than oxybutynin", correct:false, why:"Oxybutynin binds M1 in the brain more; solifenacin binds M1 less."},
  {t:"Oxybutynin blocks only M3", correct:false, why:"Oxybutynin affects M1 and M3."}],
 teach:"His ranking of the bladder antimuscarinics runs from non-selective at the top to M3-selective at the bottom. Oxybutynin (oldest, cheapest) blocks M1 and M3 and causes the most anti-DUMBBELSS, including sedation. Solifenacin (Vesicare, newer, more expensive) is more M3-selective, with fewer anti-DUMBBELSS effects at therapeutic doses, but a high enough dose gives them all.",
 quote:"So what I have done for here is rank it up for you, the level of non-selectivity. The ones on the top are very non-selective, as the one in the bottom, like VESIcare is more selective than M3, less anti-dumbbell side effects, OK? But all those dependent, right? If I give enough of VESIcare, I'm gonna get all the anti-dumbbells.",
 cite:"PCOL-Cholinergic-26s.pdf slides 29–30; transcript 10/5"},

{id:"L09-053", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"apply",
 concept:"scopolamine-side-effects", tags:[], multi:true, source:"both",
 stem:"A traveler takes scopolamine to prevent vomiting from motion sickness. Which effects are also expected? Select all that apply.",
 options:[
  {t:"Dry mouth", correct:true, why:"Blocking the salivary glands gives a dry mouth."},
  {t:"Constipation", correct:true, why:"Blocking gut M3 gives constipation."},
  {t:"Inability to urinate", correct:true, why:"Blocking bladder M3 makes urination difficult."},
  {t:"Drowsiness", correct:true, why:"Scopolamine penetrates the central nervous system (CNS) rapidly and causes drowsiness."},
  {t:"Diarrhea", correct:false, why:"Diarrhea is an agonist (DUMBBELSS) effect."},
  {t:"Miosis", correct:false, why:"A muscarinic antagonist dilates the pupil (mydriasis)."}],
 teach:"Scopolamine is a non-selective muscarinic antagonist (it also blocks histamine and serotonin receptors) used for motion sickness to block emesis. It is taken before travel as a preventive. The other anti-DUMBBELSS effects cannot be avoided: constipation, inability to urinate and dry mouth, along with drowsiness.",
 quote:"So the goal over here is to block the emesis, the vomiting, right? But you can't avoid the other dumbbells. You're still gonna get the constipation. The inability to urinate, the dry mouth, and the other components.",
 cite:"PCOL-Cholinergic-26s.pdf slide 24; transcript 10/5"},

{id:"L09-054", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"apply",
 concept:"agonist-reversible-outcompete", tags:["exam-cue"], source:"both",
 stem:"A patient overdoses on bethanechol. Why can a muscarinic antagonist reverse the effects?",
 options:[
  {t:"Bethanechol binds reversibly", correct:true, why:"The muscarinic agonists are reversible and competitive, so the opposite drug can outcompete them."},
  {t:"Bethanechol binds covalently", correct:false, why:"Covalent binding would be irreversible; the muscarinic agonists are reversible."},
  {t:"The antagonist inhibits acetylcholinesterase", correct:false, why:"Inhibiting the enzyme would raise acetylcholine and worsen the DUMBBELSS."},
  {t:"Bethanechol acts at nicotinic receptors", correct:false, why:"Bethanechol binds only muscarinic receptors."}],
 teach:"All the muscarinic agonists are reversible, so they are competitive: they bind and come off. In an overdose, the opposite drug (a muscarinic antagonist such as atropine) can outcompete them at the receptor. Atropine also treats muscarinic agonist overdose with bradycardia or atrioventricular nodal block.",
 quote:"They're all reversible, so they're all competitive, they're gonna bind, and they're gonna come off. So if we have an overdose, we can always give the opposite to try to outcompete them, OK?",
 cite:"PCOL-Cholinergic-26s.pdf slide 11; slide 20; transcript 10/5"}
);
