TOPICS.push({id:'L06', name:'Day 6 review: how to read a curve question; desired vs undesired effects', prof:'Gottlieb', lecture:'L06',
  cite:'Day 6 (9/30) — Pharmacodynamics reviews.pdf, Part 3',
  subs:[
    {id:'p3', name:'Part 3: desired vs undesired effects; therapeutic efficacy', cite:'Part 3 pages 1–2'},
    {id:'recap', name:'Recap figure A–E: potency, efficacy, affinity, and what a second drug does', cite:'reviews page 3'},
    {id:'base50', name:'The 50% baseline figure: classify the five drugs', cite:'reviews page 4'},
    {id:'method', name:'The three questions for any curve figure: shift, baseline, Emax (and symmetry)', cite:'reviews pages 5–11'},
    {id:'signal', name:'Signal transduction in his words: signal, transducer, effector, second messenger, the steps', cite:'transcript 9/30'}
  ]});
QUESTIONS.push(
/* ---------------- Part 3: desired vs undesired effects (pages 1–2) ---------------- */
{id:'L06-001', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'p3', skill:'apply',
 concept:'dose-selectivity-undesired-effects', tags:[], source:'both',
 stem:'A ligand produces its desired effect at a low dose and undesired effects at a higher dose. Why does raising the dose bring on the undesired effects?',
 options:[
  {t:'The ligand loses its selectivity and binds two or more receptor types', correct:true, why:'Most ligands produce multiple effects: as the dose goes up they lose their selectivity, bind more than one receptor type, and the different effects have different dose–response curves.'},
  {t:'The ligand turns from an agonist into an antagonist', correct:false, why:'Dose does not change the class of a drug; it changes how many receptor types the drug reaches.'},
  {t:'The receptors for the desired effect are down-regulated during the first dose', correct:false, why:'Down-regulation is a long-term change after chronic exposure; it is not why a higher single dose adds effects.'},
  {t:'The therapeutic index of the ligand rises with the dose', correct:false, why:'The therapeutic index is a ratio of two population doses; it is how safety is measured, not something that moves with each dose.'}],
 teach:'Most ligands produce multiple effects, through multiple receptor types and different target sensitivity. Different effects often have different dose–response curves: the desired effect at a low dose, undesired effects at a higher dose, as the drug loses its selectivity. The goal is to give only the lowest effective dose, and safety is measured with the therapeutic index.',
 quote:'drugs, ligands, they can be selective, but as we increase the dose, they lose their selectivity',
 cite:'Pharmacodynamics-Day_4_&_5_2026s_Part 3.pdf page 1; transcript 9/30'},

{id:'L06-002', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'p3', skill:'recall',
 concept:'lowest-effective-dose-ti', tags:['poll'], source:'both',
 stem:'Which statement is CORRECT about desired and undesired drug effects?',
 options:[
  {t:'Most ligands produce more than one effect', correct:false, why:'Correct statement (multiple receptor types, different target sensitivity), but not the only correct one.'},
  {t:'The goal is to give only the lowest effective dose', correct:false, why:'Correct statement: start low and go slow, so that the desired effect comes without the higher-dose undesired effects. Not the only correct one.'},
  {t:'Safety is measured with the therapeutic index', correct:false, why:'Correct statement: the larger the therapeutic index, the safer the drug. Not the only correct one.'},
  {t:'All of the above', correct:true, why:'All three statements are on the desired vs undesired effects slide.'}],
 teach:'Desired vs undesired effects: most ligands produce multiple effects; the desired effect usually comes at a low dose and the undesired at a higher dose; so the goal is to give only the lowest effective dose. Safety is measured with the therapeutic index, and when the therapeutic index looks large the safety index is checked as well.',
 quote:'what is the rule of thumb when comparing two drugs based on their therapeutic index. The larger the number is, the safer the drug is going to be',
 cite:'Pharmacodynamics-Day_4_&_5_2026s_Part 3.pdf page 1; transcript 9/30'},

{id:'L06-003', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'p3', skill:'figure',
 concept:'therapeutic-efficacy-figure', tags:['poll'], source:'both',
 img:'p3-therapeutic-efficacy', imgAlt:'Analgesic effect against log dose for three drugs: morphine and meperidine rise to the same high plateau, morphine to the left of meperidine; ibuprofen sits to the right and plateaus much lower', imgCap:'Analgesic effect vs log dose: morphine, meperidine, ibuprofen',
 stem:'The curves show the analgesic effect of three drugs against log dose. Which drug has the lowest therapeutic efficacy?',
 options:[
  {t:'Morphine', correct:false, why:'Morphine reaches the highest plateau; its therapeutic efficacy is the highest, not the lowest.'},
  {t:'Meperidine', correct:false, why:'Meperidine reaches the same high plateau as morphine; it is less potent than morphine, not less efficacious.'},
  {t:'Ibuprofen', correct:true, why:'Ibuprofen plateaus far below the two opioids: the lowest therapeutic efficacy, enough for a small hurt but not for a broken leg.'},
  {t:'They are all equal', correct:false, why:'The plateaus differ: two high, one low. Efficacy is read from the height of the curve.'}],
 teach:'Therapeutic efficacy is read on the y-axis, the height of the plateau. Morphine and meperidine both reach the higher plateau; ibuprofen reaches a lower one. The choice depends on the effect you need: for a small hurt in the backyard ibuprofen may be enough; for a broken leg the patient needs the higher efficacy of morphine.',
 quote:'If you got a boo boo that is just, you know, you’re working in the backyard and you hurt your feet, maybe ibuprofen might cut. You may not need to go to morphine',
 cite:'Pharmacodynamics-Day_4_&_5_2026s_Part 3.pdf page 2; transcript 9/30'},

{id:'L06-004', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'p3', skill:'figure', multi:true,
 concept:'therapeutic-efficacy-figure', tags:['poll'], source:'both',
 img:'p3-therapeutic-efficacy', imgAlt:'Analgesic effect against log dose for three drugs: morphine and meperidine rise to the same high plateau, morphine to the left of meperidine; ibuprofen sits to the right and plateaus much lower', imgCap:'Analgesic effect vs log dose: morphine, meperidine, ibuprofen',
 stem:'Which of these drugs have the same therapeutic efficacy? Select all that apply.',
 options:[
  {t:'Morphine', correct:true, why:'Morphine reaches the higher plateau.'},
  {t:'Meperidine', correct:true, why:'Meperidine reaches the same higher plateau as morphine; it only needs a larger dose to get there.'},
  {t:'Ibuprofen', correct:false, why:'Ibuprofen plateaus lower than both opioids; its efficacy is not equal to theirs.'}],
 teach:'Equal efficacy means equal plateau height. Morphine and meperidine both reach the higher analgesic plateau, so their therapeutic efficacy is the same; what differs between them is potency (morphine is to the left). Ibuprofen plateaus lower and has the lower therapeutic efficacy.',
 cite:'Pharmacodynamics-Day_4_&_5_2026s_Part 3.pdf page 2; transcript 9/30'},

{id:'L06-005', fg:'potency', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'p3', skill:'figure',
 concept:'therapeutic-efficacy-figure', tags:['poll'], source:'both',
 img:'p3-therapeutic-efficacy', imgAlt:'Analgesic effect against log dose for three drugs: morphine and meperidine rise to the same high plateau, morphine to the left of meperidine; ibuprofen sits to the right and plateaus much lower', imgCap:'Analgesic effect vs log dose: morphine, meperidine, ibuprofen',
 stem:'Which of these three analgesics is the most potent?',
 options:[
  {t:'Morphine', correct:true, why:'Morphine is the farthest left: it reaches a given analgesic effect at the smallest dose, the smallest ED50.'},
  {t:'Meperidine', correct:false, why:'Meperidine reaches the same plateau as morphine but needs a larger dose; it is equally efficacious and less potent.'},
  {t:'Ibuprofen', correct:false, why:'Ibuprofen is the farthest right and the lowest; it is the least potent and the least efficacious.'},
  {t:'Potency cannot be read from this figure', correct:false, why:'Potency is read left to right on the dose axis; the figure has a log dose axis.'}],
 teach:'Potency is the left–right position, the ED50; efficacy is the up–down position, the plateau. Morphine is the most potent (farthest left) and shares the highest efficacy with meperidine. Ibuprofen is both the least potent and the least efficacious of the three.',
 quote:'when it comes to affinity, what would you be measuring affinity at? ... The X axis, right, left and right. When we think about efficacy ... Up and down, and our potency is gonna be a combination of the left and right and the up and down',
 cite:'Pharmacodynamics-Day_4_&_5_2026s_Part 3.pdf page 2; transcript 9/30'},

/* ---------------- Recap figure (page 3) ---------------- */
{id:'L06-006', fg:'potency', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'recap', skill:'figure',
 concept:'recap-highest-potency', tags:['poll'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'The five curves are five different drugs acting on the same receptor. Which drug has the highest potency?',
 options:[
  {t:'A', correct:true, why:'A has the smallest ED50, the farthest to the left: the most potent drug.'},
  {t:'B', correct:false, why:'B reaches the full response but its ED50 is to the right of A’s.'},
  {t:'C', correct:false, why:'C is to the right of A and B and only reaches about 75%.'},
  {t:'D', correct:false, why:'D reaches the full response but sits far to the right; a large ED50.'},
  {t:'E', correct:false, why:'E is the farthest right and plateaus at about 75%: the least potent drug.'}],
 teach:'Potency is read from the ED50: whoever has the smallest ED50 is the most potent. A is the farthest left, so A is the most potent and E, the farthest right, the least potent. Efficacy is a separate reading, the height of the plateau.',
 quote:'whoever has the smallest ED 50. It’s gonna be the most potent ... A being your most potent drug, E being your least potent drug',
 cite:'Pharmacodynamics reviews.pdf page 3; transcript 9/30'},

{id:'L06-007', fg:'partial', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'recap', skill:'figure', multi:true,
 concept:'recap-lowest-efficacy', tags:['poll'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'The five curves are five different drugs acting on the same receptor. Which drugs have the lowest efficacy? Select all that apply.',
 options:[
  {t:'A', correct:false, why:'A reaches the full response; highest potency, full efficacy.'},
  {t:'B', correct:false, why:'B reaches the full response.'},
  {t:'C', correct:true, why:'C plateaus at about 75%: the same lowest efficacy as E, with a greater affinity than E.'},
  {t:'D', correct:false, why:'D reaches the full response; it is only less potent.'},
  {t:'E', correct:true, why:'E plateaus at about 75%, the same height as C: the two lowest-efficacy drugs.'}],
 teach:'Efficacy is the up–down reading. C and E both plateau at the same lower level, so they share the lowest efficacy; the difference between them is affinity (C is to the left of E). When two curves tie at the lowest plateau the question becomes a select-all.',
 quote:'C and E, right? They’re both producing the same effect ... However, C has a great affinity than E does',
 cite:'Pharmacodynamics reviews.pdf page 3; transcript 9/30'},

{id:'L06-008', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'recap', skill:'figure',
 concept:'recap-highest-affinity', tags:['poll'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'The five curves are five different drugs acting on the same receptor. Which drug has the highest affinity?',
 options:[
  {t:'A', correct:true, why:'Affinity is read left to right; A is the farthest to the left, so it binds at the lowest concentration.'},
  {t:'B', correct:false, why:'B is to the right of A; its affinity is lower.'},
  {t:'C', correct:false, why:'C is right of B; lower affinity, and lower efficacy as well.'},
  {t:'D', correct:false, why:'D is right of C; it needs a higher concentration to bind.'},
  {t:'E', correct:false, why:'E is the farthest right: the lowest affinity on the figure.'}],
 teach:'Affinity is measured on the x-axis, left and right: the further to the left a curve sits, the lower the concentration at which the drug binds, the higher its affinity. Affinity is based on the bonds the drug forms; efficacy, up and down, is how the drug changes the receptor.',
 quote:'Affinity is based on the bonds that the drug is gonna form. Efficacy is how we change that receptor.',
 cite:'Pharmacodynamics reviews.pdf page 3; transcript 9/30'},

{id:'L06-009', fg:'competitive', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'recap', skill:'figure',
 concept:'competitive-antagonist-shift', tags:['poll'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'Curve B is the agonist alone. Which curve best represents B in the presence of a reversible antagonist?',
 options:[
  {t:'A', correct:false, why:'A is a shift to the left: a drug that helps the agonist, not an antagonist.'},
  {t:'B', correct:false, why:'B is the drug alone; an antagonist moves the curve.'},
  {t:'C', correct:false, why:'C has lost part of the Emax; a reversible, surmountable antagonist never lowers the Emax.'},
  {t:'D', correct:true, why:'D is shifted to the right with no change in the Emax: the reversible, competitive, surmountable antagonist pattern.'},
  {t:'E', correct:false, why:'E is shifted right and lower; a lower Emax points to an irreversible antagonist.'}],
 teach:'First eliminate A, which is helping. C, D and E are all less potent. C and E also show a drop in the ability to reach the maximal response, and a reversible antagonist is competitive and surmountable: enough agonist overcomes it. So D, with no change to the Emax, is the best answer.',
 quote:'because this drug is reversible, it’s competitive, it’s surmountable ... D as in David would be the best answer because there’s no change to the Emax',
 cite:'Pharmacodynamics reviews.pdf page 3; transcript 9/30'},

{id:'L06-010', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'recap', skill:'figure',
 concept:'allosteric-agonist-affinity-only', tags:['poll'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'Curve E is a partial agonist alone. Which curve best represents E in the presence of an allosteric agonist that affects only affinity?',
 options:[
  {t:'A', correct:false, why:'A reaches the full response; a change in affinity alone cannot raise E’s plateau.'},
  {t:'B', correct:false, why:'B also reaches the full response, so efficacy would have had to change.'},
  {t:'C', correct:true, why:'C is E moved to the left with the same plateau: more affinity, same efficacy.'},
  {t:'D', correct:false, why:'D is a full-height curve to the left of E; the plateau has changed, which affinity alone cannot do.'},
  {t:'E', correct:false, why:'E is the partial agonist alone; the allosteric agonist moves it.'}],
 teach:'E is the drug alone, a partial agonist. An allosteric agonist that affects only affinity moves E to the left without touching the plateau, so the one best answer is C. If the allosteric agonist also affected efficacy, the partial agonist could become a full agonist and A, B and D would all become possible.',
 quote:'if I say an allosteric agonist that only affects affinity. Now there’s one best answer which is C, right? I’m just moving to the left.',
 cite:'Pharmacodynamics reviews.pdf page 3; transcript 9/30'},

{id:'L06-011', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'recap', skill:'figure', multi:true,
 concept:'allosteric-agonist-affinity-efficacy', tags:['poll'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'Curve E is a partial agonist alone. Which curves could represent E in the presence of an allosteric agonist that affects both affinity and efficacy? Select all that apply.',
 options:[
  {t:'A', correct:true, why:'Shifted left and raised from partial to full: both affinity and efficacy went up.'},
  {t:'B', correct:true, why:'Also left of E and at full height.'},
  {t:'C', correct:false, why:'C is only a left shift at the same plateau; that is the affinity-only answer.'},
  {t:'D', correct:true, why:'D is left of E and at full height, so it too fits a gain in affinity and efficacy.'},
  {t:'E', correct:false, why:'E is the drug alone.'}],
 teach:'When the allosteric agonist affects affinity and efficacy, the partial agonist E can shift to the left and rise from a partial to a full response. A, B and D have all shifted to the left and reach the full response, so all three are right answers; C only moved left at the same height, which is the affinity-only pattern.',
 quote:'If I say that affects affinity and efficacy, now A, B, and D would be a right answer. So select all ... both A, B, and D has shifted to the left and also went from being a partial to a full agonist',
 cite:'Pharmacodynamics reviews.pdf page 3; transcript 9/30'},

{id:'L06-012', fg:'irreversible', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'recap', skill:'figure', multi:true,
 concept:'right-shift-lower-emax-two-answers', tags:['poll'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'Curve D is a full agonist alone and curve E is the same agonist in the presence of drug X. Which could drug X be? Select all that apply.',
 options:[
  {t:'Irreversible antagonist', correct:true, why:'Right shift with a lower Emax: the receptors it binds are lost to the agonist.'},
  {t:'Allosteric antagonist that affects affinity and efficacy', correct:true, why:'Lower affinity moves the curve right; lower efficacy drops the plateau. Both changes are on the figure.'},
  {t:'Competitive antagonist', correct:false, why:'A competitive antagonist shifts right but never changes the Emax.'},
  {t:'Inverse agonist', correct:false, why:'An inverse agonist would move the baseline toward 0 and leaves the Emax alone; the baseline here is already 0 and the Emax has dropped.'},
  {t:'Allosteric agonist that affects only affinity', correct:false, why:'An allosteric agonist shifts the curve to the left; E is to the right of D.'}],
 teach:'D to E is a shift to the right together with a drop in the Emax. A right shift rules out everything that helps the agonist; the drop in the Emax rules out the competitive antagonist and the inverse agonist, which never change the Emax. What is left is an irreversible antagonist or an allosteric antagonist that affects affinity and efficacy.',
 quote:'could be irreversible or an allosteric antagonist that affects affinity and efficacy',
 cite:'Pharmacodynamics reviews.pdf page 3; transcript 9/30'},

/* ---------------- 50% baseline figure (page 4) ---------------- */
{id:'L06-013', fg:'two-state', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'base50', skill:'figure', type:'match',
 concept:'baseline50-classify-five', tags:['poll'], source:'both',
 img:'pollev-figure1', imgAlt:'Five curves A to E starting from a 50% baseline; A rises to 100%, B rises to about 80%, C stays flat at 50%, D falls to about 25%, E falls to 0%', imgCap:'Five drugs given alone, each starting from the 50% baseline (R = R*)',
 stem:'The receptors in this system are 50% active and 50% inactive on their own (R = R*), and each drug is given separately. Match each drug to its class.',
 left:['Drug A', 'Drug B', 'Drug C', 'Drug D', 'Drug E'],
 right:['Full agonist', 'Partial agonist with about 75–80% efficacy', 'Antagonist', 'Partial agonist with about 25% efficacy', 'Inverse agonist'],
 pairs:[
  {l:'Drug A', r:'Full agonist', why:'A takes the response from 50% to the maximal 100%.'},
  {l:'Drug B', r:'Partial agonist with about 75–80% efficacy', why:'B rises above the baseline but stops short of 100%.'},
  {l:'Drug C', r:'Antagonist', why:'C stays flat at 50%: it does not change the balance between active and inactive receptors, so it has no efficacy here.'},
  {l:'Drug D', r:'Partial agonist with about 25% efficacy', why:'D goes down to about 25%: a partial agonist whose efficacy is below the 50% baseline, so it behaves as an antagonist against the system’s own activity.'},
  {l:'Drug E', r:'Inverse agonist', why:'E brings everything down to 0: the inverse agonist.'}],
 teach:'Start at the baseline: 50% of the receptors are active by themselves. A gets to the maximal response (full agonist). B stops at about 75–80% (partial agonist). C does not move the balance between active and inactive receptors (antagonist, no efficacy). D falls to about 25%: a partial agonist with 25% efficacy, which pulls the system down toward its own level and so behaves as an antagonist here. E goes to 0: the inverse agonist.',
 note:'While reading this slide he first called E "irreversible"; on the Jeopardy question with the same figure he keyed E as the inverse agonist ("that will be an inverse agonist that brings everything down to zero"), and an irreversible antagonist never changes the baseline. E is keyed as the inverse agonist.',
 quote:'My starting point is 50%. I have receptors that are 50% active by themselves and 50% inactive ... I’m going to give each drug separately.',
 cite:'Pharmacodynamics reviews.pdf page 4; transcript 9/30'},

{id:'L06-014', fg:'partial', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'base50', skill:'tell',
 concept:'flat-curve-antagonist-or-partial-50', tags:['poll'], source:'both',
 img:'pollev-figure1', imgAlt:'Five curves A to E starting from a 50% baseline; A rises to 100%, B rises to about 80%, C stays flat at 50%, D falls to about 25%, E falls to 0%', imgCap:'Five drugs given alone, each starting from the 50% baseline (R = R*)',
 stem:'In this system 50% of the receptors are active on their own and drug C stays flat at 50%. Could C be a partial agonist?',
 options:[
  {t:'Yes, if its efficacy is 50%', correct:true, why:'A partial agonist with 50% efficacy does whatever the system is already doing: bound or unbound, the response stays at 50%, which looks the same as an antagonist here.'},
  {t:'No, a partial agonist always moves the curve away from the baseline', correct:false, why:'Only when its efficacy differs from the baseline; at exactly 50% efficacy in a 50% system it does not move.'},
  {t:'No, a flat curve means the drug has no affinity', correct:false, why:'Affinity is not the issue; C binds, and the flat line is about efficacy matching the baseline.'},
  {t:'Yes, every flat curve is a partial agonist', correct:false, why:'A flat curve is also what an antagonist with no efficacy produces; the figure alone cannot say which.'}],
 teach:'Could C be a partial agonist with an efficacy of 50%? Yes: whether it is bound or unbound, it does what the system is already doing and the line stays flat. With only this figure you cannot tell such a partial agonist from an antagonist, so on the information given, C is called the competitive antagonist. A second figure in a cell line where most receptors are inactive would settle it.',
 quote:'Could it be a partial agonist who has efficacy of 50%? So it doesn’t matter if he’s bound or unbound, he’s doing whatever the system is doing',
 cite:'Pharmacodynamics reviews.pdf page 4; transcript 9/30'},

{id:'L06-015', fg:'partial', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'base50', skill:'figure', multi:true,
 concept:'two-figures-partial-agonists', tags:['poll'], source:'transcript',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises to about 80%, C stays flat at 50%, D falls to about 25%, E falls to 0%', imgCap:'Figure 1: the same five drugs; Figure 2 (described in the stem) is the same drugs in a cell line where most receptors are inactive',
 stem:'Figure 1 shows five drugs in a system in which 50% of the receptors are active and 50% inactive. Figure 2 shows the same five drugs in a different cell line in which most receptors are inactive, and there drug C rises from the baseline to 50%, B rises to about 80% and D rises to about 25%. Which of these drugs are partial agonists? Select all that apply.',
 options:[
  {t:'A', correct:false, why:'A reaches 100% in both systems: a full agonist.'},
  {t:'B', correct:true, why:'B rises above the baseline but stops short of 100% in both figures.'},
  {t:'C', correct:true, why:'Flat at the 50% baseline in Figure 1, but it rises to 50% when the system starts inactive: a partial agonist with 50% efficacy.'},
  {t:'D', correct:true, why:'Down to 25% in the 50% system and up to 25% in the inactive system: a partial agonist with 25% efficacy.'},
  {t:'E', correct:false, why:'E brings the response to 0: an inverse agonist, not a partial agonist.'}],
 teach:'With a second figure in a cell line where the majority of the receptors are inactive, C now rises to 50%, so it can be said with certainty that C is a partial agonist: it has efficacy, just 50% of it. B (about 80%) and D (about 25%) are also partial agonists. Without the second figure, C has to be called a competitive antagonist on the information given.',
 quote:'If I ask you in your exam and I give you that figure and say which of these drugs are partial agonists, select all B, C, and D, right? You can’t say on the one on the left, if I don’t give you more information.',
 cite:'transcript 9/30 (his two-figure version of Pharmacodynamics reviews.pdf page 4)'},

{id:'L06-016', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'base50', skill:'tell',
 concept:'flat-curve-antagonist-or-partial-50', tags:['poll'], source:'both',
 img:'pollev-figure1', imgAlt:'Five curves A to E starting from a 50% baseline; A rises to 100%, B rises to about 80%, C stays flat at 50%, D falls to about 25%, E falls to 0%', imgCap:'Five drugs given alone, each starting from the 50% baseline (R = R*)',
 stem:'With only this figure, why is drug C best called an antagonist?',
 options:[
  {t:'It does not change the balance between active and inactive receptors', correct:true, why:'C leaves the system where it found it: no efficacy shown, which on the information given is a neutral, competitive antagonist.'},
  {t:'It binds without affinity, so its curve cannot move away from the 50% baseline', correct:false, why:'A drug without affinity does not bind at all; C binds, and what the flat line shows is a lack of visible efficacy.'},
  {t:'It brings the response down to 0', correct:false, why:'That is E, the inverse agonist. C stays at 50%.'},
  {t:'It has the highest affinity of the five', correct:false, why:'Affinity is read left to right, and the question is about C’s class, which is read from whether the curve moves up or down.'}],
 teach:'An antagonist is neutral: it has affinity but no efficacy, so it does not change the balance between active and inactive receptors and the response stays at the baseline. A partial agonist with exactly 50% efficacy would draw the same flat line, which is why the figure alone cannot tell them apart and C is keyed as the competitive antagonist on the information given.',
 quote:'this drug is not changing the balance between active and inactive receptors ... it’s kinda neutral, so that’s probably an antagonist ... has no efficacy at this point',
 cite:'Pharmacodynamics reviews.pdf page 4; transcript 9/30'},

/* ---------------- The three questions (pages 5–11) ---------------- */
{id:'L06-017', fg:'irreversible', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'figure',
 concept:'three-questions-irreversible', tags:['poll'], source:'both',
 img:'rev-rt-figure', imgAlt:'Fractional maximum response against log agonist: the leftmost curve, labelled Rt = 1, reaches 1.0; the curves to its right, labelled x10^-1, x10^-2 and x10^-3, shift progressively right and plateau lower and lower; a dashed line through the half-maximal points curves down to a point marked KA', imgCap:'Drug A alone (left) and drug A with increasing concentrations of drug C (right)',
 stem:'The curve on the left is drug A alone; the curves on the right are drug A in the presence of increasing concentrations of drug C. Drug C is:',
 options:[
  {t:'Competitive (reversible) antagonist', correct:false, why:'Shift right fits, but a competitive antagonist never lowers the Emax, and here the Emax keeps falling.'},
  {t:'Inverse agonist', correct:false, why:'An inverse agonist is also competitive: it shifts right and leaves the Emax alone. The baseline here is at 0 and cannot help either way.'},
  {t:'Irreversible antagonist', correct:true, why:'Shift right (lower potency, higher ED50), no change in the baseline, Emax going down with each dose: the receptors are being removed.'},
  {t:'Allosteric agonist that affects efficacy', correct:false, why:'An agonist of any kind would help; these curves need higher and higher doses.'},
  {t:'Full agonist', correct:false, why:'A second full agonist shifts the curve to the left and keeps the full response.'}],
 teach:'Question 1, is it shifting? Yes, to the right: higher and higher doses are needed, so the full agonist and the allosteric agonist that affects efficacy are out. Question 2, is the baseline changing? No, and with the baseline at 0 it cannot help. Question 3, is the Emax changing? Yes, it is going down, and both the inverse agonist and the reversible antagonist are competitive and never affect the Emax. That leaves the irreversible antagonist.',
 quote:'Is the Emax changing. Definitely. Where is it going? It’s going down. So if it’s going down, who can it be? Irreversible, right? Because both inverse and reversible are competitive. They will never affect the Emax.',
 cite:'Pharmacodynamics reviews.pdf page 5; transcript 9/30'},

{id:'L06-018', fg:'competitive', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'figure',
 concept:'three-questions-competitive', tags:['poll'], source:'both',
 img:'rev-shifts-base0', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A on the left starting at 0 and reaching 1.0, then three solid curves A + B, A + 10X B and A + 100X B shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'A alone (dashed) and A with increasing concentrations of B',
 stem:'The dashed curve is agonist A alone; the solid curves are A with B, A with 10X B and A with 100X B. Drug B is most likely:',
 options:[
  {t:'Competitive antagonist', correct:true, why:'Shift right in equal steps, no change in the baseline, no change in the Emax: surmountable with more agonist.'},
  {t:'Inverse agonist', correct:false, why:'Also a right shift with the same Emax, but with the baseline already at 0 the figure cannot show the drop an inverse agonist wants to make; competitive is the best single answer.'},
  {t:'Irreversible antagonist', correct:false, why:'Three shifts and the Emax has not dropped at all.'},
  {t:'Allosteric antagonist that affects only affinity', correct:false, why:'An allosteric drug saturates and gives unequal shifts; these steps are symmetrical.'},
  {t:'Allosteric agonist that affects only affinity', correct:false, why:'An agonist of any kind would shift the curve to the left.'}],
 teach:'Shift? To the right, so the two agonists are out. Baseline? No change (and it is at 0, so it cannot separate the inverse agonist from the competitive antagonist). Emax? No change, so the irreversible antagonist and the allosteric antagonist that affects efficacy are out. Are the shifts symmetrical? Yes, equal steps, so it is not allosteric. The best answer is the competitive antagonist.',
 quote:'What is it that I can’t differentiate here between those two? ... Because my baseline is 0, the inverse wants to keep at 0, and the competitive doesn’t care',
 cite:'Pharmacodynamics reviews.pdf page 6; transcript 9/30'},

{id:'L06-019', fg:'inverse', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'tell',
 concept:'competitive-vs-inverse-baseline-zero', tags:['poll'], source:'both',
 img:'rev-shifts-base0', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A on the left starting at 0 and reaching 1.0, then three solid curves A + B, A + 10X B and A + 100X B shifted to the right in equal steps, all starting at 0 and reaching the same top', imgCap:'A alone (dashed) and A with increasing concentrations of B',
 stem:'On this figure the agonist shifts to the right in equal steps with no change in the Emax. Why can the baseline question not separate a competitive antagonist from an inverse agonist here?',
 options:[
  {t:'The baseline is already at 0, so there is nothing for an inverse agonist to bring down', correct:true, why:'The inverse agonist wants to keep the baseline at 0 and the competitive antagonist does not care; at a baseline of 0 both leave the same picture.'},
  {t:'The Emax does not change, and an inverse agonist always lowers the Emax of an agonist', correct:false, why:'An inverse agonist is competitive; it never lowers the Emax. The Emax question rules out the irreversible antagonist, not the inverse agonist.'},
  {t:'The shifts are symmetrical, and an inverse agonist always gives unequal shifts', correct:false, why:'Unequal, saturating shifts belong to an allosteric drug; an inverse agonist gives surmountable, symmetrical shifts.'},
  {t:'An inverse agonist never shifts an agonist’s curve to the right', correct:false, why:'It does: an inverse agonist competes with the agonist and shifts its curve to the right, which is why the two are confusable here.'}],
 teach:'Baseline to 0 is the tell for an inverse agonist, but only when the system starts above 0. On a figure whose baseline is already 0, the inverse agonist and the competitive antagonist both give symmetrical right shifts with no change in the Emax, and the figure cannot tell them apart. He keys the competitive antagonist as the best single answer; the same shifts drawn from a 50% baseline that falls to 0 would be the inverse agonist.',
 quote:'Because my baseline is 0, the inverse wants to keep at 0, and the competitive doesn’t care',
 cite:'Pharmacodynamics reviews.pdf page 6; transcript 9/30'},

{id:'L06-020', fg:'inverse', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'figure',
 concept:'three-questions-inverse', tags:['poll'], source:'both',
 img:'rev-shifts-base50', imgAlt:'Response 0 to 1.0 against log [A]: a dashed curve A starts at about 0.5 and reaches 1.0; solid curves A + B, A + 10X B and A + 100X B are shifted to the right and start lower and lower, from about 0.3, about 0.1 and 0, all reaching the same top', imgCap:'A alone (dashed, from a 50% baseline) and A with increasing concentrations of B',
 stem:'The dashed curve is agonist A alone, starting from a baseline of about 50%; the solid curves are A with B, A with 10X B and A with 100X B. Drug B is most likely:',
 options:[
  {t:'Competitive antagonist', correct:false, why:'A competitive antagonist shifts right but does not move the baseline; here the baseline falls to 0.'},
  {t:'Inverse agonist', correct:true, why:'Shift right, same Emax, and the baseline goes down to 0 with each dose: the inverse agonist is shutting off the receptors that were active on their own.'},
  {t:'Irreversible antagonist', correct:false, why:'The Emax is unchanged across three shifts, and an irreversible antagonist does not change the baseline.'},
  {t:'Allosteric antagonist that affects efficacy', correct:false, why:'The Emax is not changing, so nothing that affects efficacy fits.'},
  {t:'Partial agonist', correct:false, why:'A partial agonist in a 50% system would move the baseline toward its own efficacy, not to 0, and would not need three symmetrical right shifts.'}],
 teach:'Is it shifting? Yes, to the right. Is it changing the Emax? No, so the irreversible antagonist and any drug that affects efficacy are out. Is the baseline changing? Yes, it is going to 0. A drug that competes with the agonist and takes the baseline to 0 is an inverse agonist.',
 quote:'Is it shifting? Yes ... Is it changing the Emax? No, so irreversible and any drug that affects efficacy is out. Is a change in the baseline? Yes. Where is it going? To 0. What it means is, it’s an inverse agonist.',
 cite:'Pharmacodynamics reviews.pdf page 7; transcript 9/30'},

{id:'L06-021', fg:'classes', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'figure', multi:true,
 concept:'left-shift-two-answers', tags:['poll'], source:'both',
 img:'rev-dotted-left', imgAlt:'Response percent of control against agonist concentration: a solid curve on the right is the agonist alone; a dashed curve labelled X+Y sits to its left with a red arrow pointing left; both start at 0 and reach the same top', imgCap:'Solid: agonist alone; dashed: agonist in the presence of drug X',
 stem:'The solid line is the agonist alone. The dotted line is the agonist in the presence of drug X. Which could drug X be? Select all that apply.',
 options:[
  {t:'Full agonist', correct:true, why:'A second agonist with equal efficacy adds to the first: the curve moves left at the same top.'},
  {t:'Allosteric agonist that affects affinity', correct:true, why:'More affinity for the agonist moves its curve to the left with no change in the Emax.'},
  {t:'Competitive antagonist', correct:false, why:'Anything that makes life harder shifts the curve to the right.'},
  {t:'Inverse agonist', correct:false, why:'An inverse agonist shifts right and would bring a baseline down; this curve moved left.'},
  {t:'Irreversible antagonist', correct:false, why:'It shifts right and lowers the Emax; this curve moved left at the same top.'},
  {t:'Allosteric antagonist that affects affinity and efficacy', correct:false, why:'It shifts right, not left.'}],
 teach:'Is it shifting? Yes, to the left, so it is helping: the irreversible antagonist, the allosteric antagonist, the competitive antagonist and the inverse agonist are all out. Is the baseline changing? No (it is at 0). Is the Emax changing? No. Two answers are left: a full agonist, or an allosteric agonist that affects affinity. An allosteric agonist that also affected efficacy would need a plateau to raise, and this one is already at the top.',
 quote:'because we’re shifting to the left, I can get rid of the competitive antagonist and the inverse ... two possible answers. It’s either full agonist. Or an allosteric agonist that affecting what, affinity.',
 cite:'Pharmacodynamics reviews.pdf page 8; transcript 9/30'},

{id:'L06-022', fg:'competitive', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'figure',
 concept:'one-right-shift-rule-out', tags:['poll'], source:'both',
 img:'rev-dotted-right', imgAlt:'Response percent of control against agonist concentration: a dashed curve on the left is the agonist alone; one solid curve sits to its right with a red arrow pointing right; both start at 0 and reach the same top', imgCap:'Dashed: agonist alone; solid: agonist in the presence of drug X (one shift)',
 stem:'The dotted line is the agonist alone and the solid line is the agonist in the presence of drug X: one shift to the right, same baseline, same top. Which of these can be ruled OUT as drug X?',
 options:[
  {t:'Full agonist', correct:true, why:'A full agonist would shift the curve to the left; this one moved right, so every agonist that helps is out.'},
  {t:'Competitive antagonist', correct:false, why:'A right shift with the same Emax fits a competitive antagonist; it stays in.'},
  {t:'Inverse agonist', correct:false, why:'With the baseline at 0, an inverse agonist gives the same picture as a competitive antagonist; it cannot be ruled out.'},
  {t:'Irreversible antagonist', correct:false, why:'With only one shift and spare receptors, an irreversible antagonist can still look like this; more shifts would be needed to rule it out.'}],
 teach:'With one right shift, the full agonist, the partial agonist and the allosteric agonists are gone (they would help). The baseline is already at 0, so it cannot tell. The Emax has not changed on the information given, but with only one shift an irreversible antagonist in a tissue with spare receptors is still possible. If a single best answer is required it is the competitive antagonist, not the irreversible one.',
 quote:'full agonists and allosteric [agonists] are gone. Is changing the baseline. I’m already at 0, so I won’t be able to tell ... partial agonists are out',
 cite:'Pharmacodynamics reviews.pdf page 9; transcript 9/30'},

{id:'L06-023', fg:'spare', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'figure', multi:true,
 concept:'one-right-shift-select-all', tags:['poll'], source:'both',
 img:'rev-dotted-right', imgAlt:'Response percent of control against agonist concentration: a dashed curve on the left is the agonist alone; one solid curve sits to its right with a red arrow pointing right; both start at 0 and reach the same top', imgCap:'Dashed: agonist alone; solid: agonist in the presence of drug X (one shift)',
 stem:'The dotted line is the agonist alone and the solid line is the agonist in the presence of drug X: one shift to the right, same baseline, same top. Which could drug X be? Select all that apply.',
 options:[
  {t:'Competitive antagonist', correct:true, why:'Right shift, same Emax: the classic competitive picture.'},
  {t:'Inverse agonist', correct:true, why:'With the baseline at 0 the inverse agonist cannot be told from the competitive antagonist.'},
  {t:'Irreversible antagonist in a tissue with spare receptors', correct:true, why:'If the agonist needs only a small fraction of the receptors, the first doses of an irreversible antagonist only shift the curve; the drop in the Emax would come with more antagonist.'},
  {t:'Allosteric antagonist that affects only affinity', correct:true, why:'A single shift cannot show whether the shifts are symmetrical, so an allosteric antagonist on affinity stays open.'},
  {t:'Full agonist', correct:false, why:'It would shift the curve to the left.'},
  {t:'Partial agonist', correct:false, why:'A partial agonist added to a full agonist pulls the top down toward its own efficacy; the top here is unchanged, and it would not shift the curve right at full height.'}],
 teach:'One shift is not enough information. Shift right rules out everything that helps. Baseline at 0 cannot tell. The Emax has not dropped, but an irreversible antagonist with spare receptors could give a shift before the drop, and an allosteric antagonist on affinity cannot be ruled out without several shifts to test symmetry. As a select-all, competitive, inverse, irreversible (with spare receptors) and allosteric antagonist on affinity all stay open; as one best answer, competitive.',
 quote:'But if it’s a select all, now I open up the possibilities. I just need more shifts to be able to prove that it is or it is not.',
 cite:'Pharmacodynamics reviews.pdf page 9; transcript 9/30'},

{id:'L06-024', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'figure',
 concept:'allosteric-antagonist-unequal-shifts', tags:['poll'], source:'both',
 img:'rev-allo-ant', imgAlt:'Response percent of control against agonist concentration: a dashed curve on the left is the agonist alone; three solid curves to its right with a red arrow pointing right; the spacing between the solid curves is not equal; all start at 0 and reach the same top', imgCap:'Dashed: agonist alone; solid: agonist with increasing concentrations of drug X (unequal spacing)',
 stem:'The dotted line is the agonist alone; the solid lines are the agonist with increasing concentrations of drug X. The shifts are to the right, the top does not change, and the spacing between the shifts is not equal. Drug X is most likely:',
 options:[
  {t:'Competitive antagonist', correct:false, why:'A competitive antagonist gives symmetrical, equal shifts with no limit; these shifts are unequal.'},
  {t:'Irreversible antagonist', correct:false, why:'Multiple shifts and the Emax has not dropped at all.'},
  {t:'Allosteric antagonist (affinity)', correct:true, why:'Shifts right that are not symmetrical, with no change in the baseline or the Emax: an allosteric antagonist affecting affinity.'},
  {t:'Allosteric antagonist (affinity and efficacy)', correct:false, why:'Efficacy is untouched: the top is the same on every curve.'},
  {t:'Inverse agonist', correct:false, why:'An inverse agonist is competitive and gives symmetrical shifts; the baseline is at 0 and the shifts here are unequal.'}],
 teach:'Is the Emax changing? No, so the irreversible antagonist and any allosteric that affects efficacy are out. Is it shifting? Yes, to the right, so the full agonist and the allosteric agonist are out. Is the baseline changing? No. Are the shifts symmetrical? No. Unequal shifts mean an allosteric drug; here an antagonist, affecting affinity. If the shifts on a figure are not symmetrical, it is allosteric; then decide agonist or antagonist, affinity or efficacy or both.',
 quote:'So if you see a figure in your exam that the shifts are not symmetric, you already know it’s allosteric. You just gotta be able to figure out, is that an agonist or an antagonist? Does it affect affinity or efficacy or both',
 cite:'Pharmacodynamics reviews.pdf page 10; transcript 9/30'},

{id:'L06-025', fg:'partial', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'figure',
 concept:'pindolol-partial-agonist-two-baselines', tags:['poll','pindolol'], source:'both',
 img:'rev-pindolol', imgAlt:'Response percent of control against agonist concentration with two dashed curves: an upper curve starts at 100% and falls to about 50%; a lower curve starts at 0 and rises to about 50%; both meet at about 50% at high concentration', imgCap:'One drug in two systems: starting at 100% (R < R*) and starting at 0',
 stem:'One drug is given to two systems. When the system starts at 100% activity the drug brings the response down to about 50%; when the system starts at 0 it brings the response up to about 50%. This drug is:',
 options:[
  {t:'Full agonist', correct:false, why:'A full agonist would take the lower system all the way to 100%; this drug stops at about 50%.'},
  {t:'Partial agonist', correct:true, why:'It has efficacy (it brings the low system up), it does not go to 0 (not inverse), and it does not reach 100%: it wants the system at about 50%, from either direction.'},
  {t:'Inverse agonist', correct:false, why:'An inverse agonist would take the upper system down to 0, not stop at 50%.'},
  {t:'Competitive antagonist', correct:false, why:'A neutral antagonist does not change the baseline in either system; this drug moves both.'},
  {t:'Irreversible antagonist', correct:false, why:'An antagonist has no efficacy; this drug raises the response in the low system.'}],
 teach:'Does the drug have efficacy? Yes, it brings the low system up, so the neutral antagonists are out. Did it bring the response to 0? No, so the inverse agonist is out. Did it change the efficacy to 100%? No, it wants about 50%. That is a partial agonist: pindolol, a partial β-blocker, brings a low heart rate up and a high heart rate down.',
 quote:'does this drug has efficacy? Yes, it’s bringing things up ... Did it go to 0? No, so we get rid of an inverse agonist ... Did it change the efficacy to 100%. Definitely not. They want you about 50%, so that is a partial agonist',
 cite:'Pharmacodynamics reviews.pdf page 11; transcript 9/30'},

{id:'L06-026', fg:'partial', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'apply',
 concept:'pindolol-low-heart-rate', tags:['poll','pindolol'], source:'both',
 stem:'A hypertensive patient has a naturally low heart rate. Why might pindolol be chosen over a full β-blocker?',
 options:[
  {t:'It brings a low heart rate up and a high heart rate down', correct:true, why:'A partial agonist pulls the system toward its own level, about 50%, from either direction; it will not take a slow heart to a stop the way a full blocker might.'},
  {t:'It has a higher affinity for the β1 receptor than a full β-blocker', correct:false, why:'The reason is efficacy, not affinity: pindolol has partial efficacy where the full blocker has none.'},
  {t:'It is an inverse agonist that cannot stop the heart', correct:false, why:'Pindolol is a partial agonist; an inverse agonist would push the heart rate further down.'},
  {t:'It has no efficacy at the β receptor, so the heart rate is untouched', correct:false, why:'No efficacy describes a neutral β-blocker, which in a patient with a low heart rate is the risk being avoided.'}],
 teach:'A full β-blocker in a patient whose heart rate is already low can push the rate lower and raise the risk of stopping the heart. Pindolol is a partial β-blocker, a partial agonist: if the heart rate is too low it brings it up, if it is too high it brings it down, toward about 50%. That makes it a drug for hypertension in a patient with a very low heart rate.',
 quote:'Pindolol, which is a partial beta blocker, if your heart is too low, it’s gonna bring things up. If it’s too high, it’s gonna bring things down. So this is a drug that we can use for the treatment of hypertension with patients who have a very low heart rate.',
 cite:'Pharmacodynamics reviews.pdf page 11; transcript 9/30'},

{id:'L06-027', fg:'classes', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'recall',
 concept:'three-questions-order', tags:['poll'], source:'transcript',
 stem:'A figure shows an agonist alone and the same agonist in the presence of another drug. After finding the reference curve, which question do you ask first?',
 options:[
  {t:'Is it shifting, left or right?', correct:true, why:'Left means the drug is helping (agonists, allosteric agonists, an indirect antagonist that raises the signal); right means it is making life harder. That one answer removes about half the options.'},
  {t:'Is the Emax changing, up or down?', correct:false, why:'This is the third question; it separates the irreversible antagonist (Emax down) from the competitive ones.'},
  {t:'Is the baseline changing?', correct:false, why:'The second question; a baseline that falls to 0 is the inverse agonist.'},
  {t:'Are the shifts symmetrical?', correct:false, why:'A fourth question, asked only when several shifts are drawn; unequal shifts mean allosteric.'}],
 teach:'The order: find the point of reference (the drug alone). Then ask: is it shifting, and is the shift helping (left) or making life more difficult (right)? Then: is the baseline changing? Then: is the Emax changing? When several shifts are drawn, add: are the shifts symmetrical? Each answer eliminates classes until one, or a select-all set, is left.',
 quote:'Remember that I asked you to ask 3 questions. What are those questions? In fact, ED 50, you got baseline and shifts, right? So let’s help answer this question. Is this drug shifting?',
 cite:'Pharmacodynamics reviews.pdf pages 5–10; transcript 9/30'},

{id:'L06-028', fg:'classes', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'tell', type:'match',
 concept:'three-questions-what-each-answer-means', tags:['poll'], source:'transcript',
 stem:'Match each observation on a curve figure to the class it points to.',
 left:['The baseline drops to 0', 'The Emax drops', 'The shifts are not symmetrical', 'The curve shifts to the left'],
 right:['Inverse agonist', 'Irreversible antagonist', 'An allosteric drug', 'A drug that raises the signal (full agonist, allosteric agonist, or an indirect antagonist that increases the second messenger)'],
 pairs:[
  {l:'The baseline drops to 0', r:'Inverse agonist', why:'Only the inverse agonist shuts off receptors that were active on their own.'},
  {l:'The Emax drops', r:'Irreversible antagonist', why:'The receptors are removed; the competitive antagonist and the inverse agonist never touch the Emax. An allosteric antagonist on efficacy also lowers it, with unequal shifts.'},
  {l:'The shifts are not symmetrical', r:'An allosteric drug', why:'Allosteric binding saturates; then decide agonist or antagonist, affinity or efficacy.'},
  {l:'The curve shifts to the left', r:'A drug that raises the signal (full agonist, allosteric agonist, or an indirect antagonist that increases the second messenger)', why:'Left means helping: a second agonist, an allosteric agonist, more receptors, or more second messenger.'}],
 teach:'Baseline down to 0: inverse agonist. Emax down: irreversible antagonist (or an allosteric antagonist on efficacy). Shifts not symmetrical: allosteric. Shift to the left: something that helps the agonist, a full agonist, an allosteric agonist, up-regulated receptors, or an indirect antagonist such as a phosphodiesterase inhibitor that raises the second messenger. Shift to the right with nothing else changed: competitive antagonist, or an inverse agonist when the baseline is already 0.',
 quote:'the key thing for you to be able to do this day in and day out on my exam is knowing what affinity is being modulated and efficacy and what this drug is gonna do. If you can do that, you got like 40 points on the exam already just by deduction processes alone.',
 cite:'Pharmacodynamics reviews.pdf pages 5–10; transcript 9/30'},

{id:'L06-029', fg:'gpcr', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'method', skill:'figure',
 concept:'mysterious-drug-y-all-of-the-above', tags:['poll'], source:'transcript',
 graph:{curves:[{label:'agonist alone', ec:0.5, emax:50}, {label:'+ drug Y', ec:-1, emax:100, dashed:true}], base:0, x:'log dose of the agonist', y:'response (%)', caption:'Solid: the agonist alone (partial response). Dashed: the agonist with drug Y, to the left and up to the full response.'},
 stem:'The solid line is the agonist alone. The dotted line is the agonist in the presence of a mysterious drug Y: it has moved to the left and risen from a partial to the full response. Drug Y is most likely:',
 options:[
  {t:'An indirect antagonist that increases the second messenger levels', correct:false, why:'Possible: a phosphodiesterase (PDE) inhibitor raises cyclic AMP (cAMP), the signal gets bigger, and a partial agonist can become a full one. Not the only possible answer.'},
  {t:'An allosteric agonist that affects affinity and efficacy', correct:false, why:'Possible: more affinity moves the curve left, more efficacy raises the top. Not the only possible answer.'},
  {t:'Diazepam', correct:false, why:'Possible: diazepam is an allosteric agonist that could affect the affinity and efficacy of the agonist. Not the only possible answer.'},
  {t:'The same drug in a cell that has high expression of receptors', correct:false, why:'Possible: more receptors make the drug more potent, and a cell that lacked the receptors to reach the maximum now reaches it. Not the only possible answer.'},
  {t:'All of the above', correct:true, why:'Each option can move a partial agonist to the left and up to the full response; once two of them are known to be right, the answer is all of the above.'}],
 teach:'A left shift with a rise from partial to full response is a signal that got bigger. A PDE inhibitor that raises cAMP does it downstream; an allosteric agonist that affects affinity and efficacy (diazepam is one) does it at the receptor; a cell with more receptors does it by making the drug more potent. When at least two answers are known to be right, the answer is all of the above.',
 note:'This poll was run in class after the review slides and is not in the PollEV PDF or the review deck; the option wording is his reading of the options.',
 quote:'What happens when we increase the number of receptors? We increase the potency of a drug ... But if you knew at least 2 of those answers, you go where? All the above.',
 cite:'transcript 9/30 (poll after the review slides)'},

/* ---------------- Signal transduction in his words ---------------- */
{id:'L06-030', fg:'gpcr-steps', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'signal', skill:'recall', multi:true,
 concept:'second-messenger-select-all', dupOf:'L02-019', tags:['poll'], source:'transcript',
 stem:'Which of these is a second messenger? (cAMP = cyclic adenosine monophosphate; IP3 = inositol trisphosphate; PKA = protein kinase A; AC = adenylate cyclase; PLC = phospholipase C) Select all that apply.',
 options:[
  {t:'cAMP', correct:true, why:'Made by AC from ATP; the second messenger of the Gs pathway.'},
  {t:'IP3', correct:true, why:'Made by PLC; the second messenger of the Gq pathway.'},
  {t:'Ca++', correct:true, why:'Listed with the second messengers on the Day 2 slide: a small molecule moved by the effector.'},
  {t:'PKA', correct:true, why:'Listed with the second messengers on the Day 2 slide: activated by cAMP and carried on inside the cell.'},
  {t:'AC', correct:false, why:'Adenylate cyclase is the effector, the enzyme that makes the second messenger.'},
  {t:'PLC', correct:false, why:'Phospholipase C is the effector of the Gq pathway, not a second messenger.'},
  {t:'Gs', correct:false, why:'The G protein is the transducer.'}],
 teach:'For Exam 1, the two major second messengers are cAMP and IP3; the Day 2 slide also lists PKA, PKC and Ca++. AC and PLC are not second messengers: they are the effectors, the signal amplifiers that make the second messenger. The G protein (αs, αi, αq) is the transducer.',
 quote:'For purpose on exam one, you need to know cyclic AMP and IP3. Those are two major second messengers that we talked about.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~26–29; transcript 9/30'},

{id:'L06-031', fg:'gpcr-steps', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'signal', skill:'recall', multi:true,
 concept:'effector-ac-plc', tags:['poll'], source:'transcript',
 stem:'Which of these is an effector, the signal amplifier that the α subunit activates? (AC = adenylate cyclase; PLC = phospholipase C; cAMP = cyclic adenosine monophosphate; IP3 = inositol trisphosphate) Select all that apply.',
 options:[
  {t:'AC', correct:true, why:'Adenylate cyclase: the effector for αs (and αi), the enzyme that makes cAMP.'},
  {t:'PLC', correct:true, why:'Phospholipase C: the effector for αq, the enzyme that makes IP3.'},
  {t:'cAMP', correct:false, why:'cAMP is the second messenger that AC makes.'},
  {t:'IP3', correct:false, why:'IP3 is the second messenger that PLC makes.'},
  {t:'The β1 receptor', correct:false, why:'The receptor receives the signal; it is not the amplifier.'}],
 teach:'A signal amplifier is the effector system, such as AC or PLC: the enzymes that make cAMP or IP3 and carry the signal inside the cell. There are two effector systems for the α subunits, PLC and AC. The second messenger is what the effector makes.',
 quote:'A signal amplifier is going to be our factor system such as AC or PLC. Those are the enzymes that are going to be making a camp or IP3 and carry on the signal inside',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~26–28; transcript 9/30'},

{id:'L06-032', fg:'gpcr-steps', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'signal', skill:'recall',
 concept:'transducer-g-protein', dupOf:'L02-020', tags:['poll'], source:'transcript',
 stem:'In the pathway norepinephrine → β1 receptor → αs → adenylate cyclase (AC) → cyclic adenosine monophosphate (cAMP), which component is the transducer?',
 options:[
  {t:'Norepinephrine', correct:false, why:'Norepinephrine is the signal.'},
  {t:'The β1 receptor', correct:false, why:'The receptor receives the signal; the transducer translates the change in the receptor.'},
  {t:'αs (the G protein)', correct:true, why:'The α subunit, αs, αi or αq, is the transducer that translates the activated receptor to the effector.'},
  {t:'Adenylate cyclase (AC)', correct:false, why:'AC is the effector, the signal amplifier.'},
  {t:'cAMP', correct:false, why:'cAMP is the second messenger.'}],
 teach:'Signal: norepinephrine. Receptor: β1. Transducer: the G protein, defined by its α subunit (αs, αi or αq), which translates the change in the receptor. Effector: AC or PLC, the amplifier. Second messenger: cAMP or IP3. Knowing which is which is what he asks about this pathway.',
 quote:'Which one is the transducer that translates that. It’s gonna be your alpha S, alpha I or alpha Q, and then we’re gonna amplify that message to the second messenger system.',
 cite:'Pharmacodynamics-Day_2_2026s copy.pdf slides ~26–28; transcript 9/30'},

{id:'L06-033', fg:'gpcr-steps', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'signal', skill:'recall',
 concept:'signal-is-the-ligand', tags:['poll'], source:'transcript',
 stem:'In the pathway norepinephrine → β1 receptor → αs → adenylate cyclase (AC) → cyclic adenosine monophosphate (cAMP) → increase in heart rate, which component is the signal?',
 options:[
  {t:'Norepinephrine', correct:true, why:'The signal is the ligand, the drug or neurotransmitter that binds the receptor.'},
  {t:'The β1 receptor', correct:false, why:'The receptor receives the signal.'},
  {t:'αs', correct:false, why:'αs is the transducer.'},
  {t:'cAMP', correct:false, why:'cAMP is the second messenger; it carries the signal inside the cell but is not the signal.'},
  {t:'The increase in heart rate', correct:false, why:'That is the physiological response at the end of the pathway.'}],
 teach:'The signal is the ligand that starts the pathway, norepinephrine at the β1 receptor of the heart. The receptor receives it, the transducer (G protein) translates it, the effector (AC) amplifies it into the second messenger (cAMP), and the cell signalling ends in the physiological response, a faster heart.',
 quote:'What I’d like for you to take a step further for your exam one is knowing what is the signal, which one is the receptor, which one is the second messenger, which one is the factor system',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~51–53; transcript 9/30'},

{id:'L06-034', fg:'gpcr-steps', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'signal', skill:'recall', type:'match',
 concept:'gpcr-forward-steps', dupOf:'L02-049', tags:['poll'], source:'transcript',
 stem:'Put the G protein pathway for norepinephrine at the β1 receptor in order: match each step number to what happens.',
 left:['Step 1', 'Step 2', 'Step 3', 'Step 4', 'Step 5', 'Step 6', 'Step 7', 'Step 8'],
 right:['Norepinephrine binds the β1 receptor', 'The receptor changes conformation', 'GDP comes off and GTP comes on', 'αs leaves β and γ', 'αs activates adenylate cyclase (AC)', 'AC converts ATP to cAMP, the second messenger', 'cAMP drives cell signalling', 'The physiological response (heart rate goes up)'],
 pairs:[
  {l:'Step 1', r:'Norepinephrine binds the β1 receptor', why:'Binding is always the first step.'},
  {l:'Step 2', r:'The receptor changes conformation', why:'The activated receptor changes shape, which is what the G protein reads.'},
  {l:'Step 3', r:'GDP comes off and GTP comes on', why:'The diphosphate is displaced and replaced with the triphosphate: more phosphate, more energy.'},
  {l:'Step 4', r:'αs leaves β and γ', why:'The extra phosphate makes the α subunit dissociate; β and γ stay together.'},
  {l:'Step 5', r:'αs activates adenylate cyclase (AC)', why:'The transducer turns on the effector.'},
  {l:'Step 6', r:'AC converts ATP to cAMP, the second messenger', why:'The effector amplifies the signal into the second messenger.'},
  {l:'Step 7', r:'cAMP drives cell signalling', why:'The second messenger carries the signal inside the cell.'},
  {l:'Step 8', r:'The physiological response (heart rate goes up)', why:'The end of the pathway.'}],
 teach:'Forward: norepinephrine binds β1, the receptor changes conformation, GDP comes off and GTP comes on, αs leaves β and γ, αs activates adenylate cyclase, AC converts ATP into cAMP (the second messenger), cAMP does the cell signalling, and that causes the physiological response. The team in the Jeopardy game walked this forward one step each.',
 note:'In the game the team said the α subunit binds adenylyl cyclase and then β and γ bind to another receptor; the slides have β and γ staying together while the α subunit carries the signal to the effector. The slide version is used here.',
 quote:'so we got the displacement of the GDP, the diphosphate, and it’s replaced with GTP ... ATP gets converted into cAMP, which is our second messenger and then cAMP is going to do what, cell signaling and then that’s going to cause a physiological response.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~51–54; transcript 9/30'},

{id:'L06-035', fg:'gpcr-steps', lecture:'L06', prof:'Gottlieb', tier:'new', topic:'L06', sub:'signal', skill:'recall', type:'match',
 concept:'gpcr-reverse-steps', tags:['poll'], source:'transcript',
 stem:'Turning the G protein signal off: match each event to what it does.',
 left:['Removes the second messenger', 'Turns the α subunit off', 'Re-forms the G protein trimer', 'Resets the receptor'],
 right:['Phosphodiesterase (PDE) breaks down cAMP', 'GTP loses its extra phosphate and becomes GDP (sped up by RGS)', 'The α subunit reassociates with β and γ', 'The agonist comes off the receptor'],
 pairs:[
  {l:'Removes the second messenger', r:'Phosphodiesterase (PDE) breaks down cAMP', why:'The two ways to regulate cAMP: make it through AC, or break it down through PDE (caffeine is a PDE inhibitor).'},
  {l:'Turns the α subunit off', r:'GTP loses its extra phosphate and becomes GDP (sped up by RGS)', why:'The phosphate is removed, GTP back to GDP; the RGS protein accelerates it.'},
  {l:'Re-forms the G protein trimer', r:'The α subunit reassociates with β and γ', why:'With GDP back on, α rejoins β and γ.'},
  {l:'Resets the receptor', r:'The agonist comes off the receptor', why:'With the agonist gone the receptor pops back to its resting shape.'}],
 teach:'Reverse: PDE breaks down cAMP (the other way to regulate cAMP besides making it with AC; caffeine inhibits PDE); the extra phosphate is removed so GTP becomes GDP, sped up by RGS; the α subunit reassembles with β and γ; and the agonist comes off so the receptor resets.',
 quote:'How do we reverse that? ... PDE breaking down the cAMP ... the actual phosphate is removed. So we go from a GTP to a GDP ... the alpha reassemble with the beta and the gamma and the receptor kind of pops up',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~52–54; transcript 9/30'}
);
