TOPICS.push({id:"L08", name:"Nicotinic receptors and NMJ pharmacology", prof:"Gottlieb", lecture:"L08",
  cite:"Day 8 (10/5) — PCOL-NMJ_PCOL_2026s_pptx.pdf (slides 1–18 were started 10/1)",
  subs:[
    {id:"nnm", name:"Nn vs Nm receptors: location, subunits, SOA", cite:"slides 3–6, 11"},
    {id:"nnag", name:"Nn agonists: ACh, nicotine, varenicline", cite:"slides 7–10"},
    {id:"nmj", name:"NMJ agents and NMJ signaling", cite:"slides 11–19"},
    {id:"sch", name:"Succinylcholine: phase I/II, ADRs, DDI", cite:"slides 19–26"},
    {id:"curare", name:"Curare-like (non-depolarizing) drugs", cite:"slides 27–32"},
    {id:"ache", name:"Reversible cholinesterase inhibitors", cite:"slides 33–41"},
    {id:"op", name:"Organophosphates, antidote, echothiophate", cite:"slides 42–45"},
    {id:"botox", name:"Botulinum toxin", cite:"slides 46–50"}
  ]});
QUESTIONS.push(
{id:"L08-001", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"recall",
 concept:"nn-location", tags:[], source:"both",
 stem:"Where are neuronal nicotinic (Nn) receptors located?",
 options:[
  {t:"Brain and autonomic ganglia", correct:true, why:"Nn receptors are in the brain and in the autonomic ganglia, where they activate postganglionic neurons; the adrenal medulla also has Nn receptors."},
  {t:"Skeletal neuromuscular junction", correct:false, why:"The skeletal neuromuscular junction carries the muscle-type nicotinic (Nm) receptor, not Nn."},
  {t:"Heart and smooth muscle", correct:false, why:"Heart and smooth muscle respond to acetylcholine through muscarinic receptors (for example M2 in the heart), not Nn."},
  {t:"Salivary glands", correct:false, why:"Salivary glands are reached by postganglionic fibers acting on M3 muscarinic receptors."},
  {t:"Skeletal muscle and brain", correct:false, why:"Skeletal muscle has Nm receptors; only the brain half of this pairing is Nn."}],
 teach:"N stands for nicotinic; the subscript N is neuronal and the subscript M is muscular. Nn receptors sit in the brain and in the autonomic ganglia of both the sympathetic and parasympathetic systems, and also at the adrenal medulla. Nm receptors sit at the skeletal neuromuscular junction of the somatic system.",
 quote:"Neuronal Nicotinic Receptor (NN): Brain; Autonomic Ganglia. Muscle Nicotinic Receptor (NM): Skeletal Neuromuscular Junction",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 4; transcript 10/1"},

{id:"L08-002", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"tell",
 concept:"nn-vs-nm-subunits", tags:[], source:"slide",
 stem:"Which statement correctly contrasts the subunits of neuronal nicotinic (Nn) and muscle nicotinic (Nm) receptors?",
 options:[
  {t:"Nn: only α and β; Nm: α, β, γ, δ and ε", correct:true, why:"Nn receptors are built only from α (α2–α9) and β (β2–β4) subunits; Nm receptors have 5 protein subunits, α, β, γ, δ and ε."},
  {t:"Nn: α, β, γ, δ and ε; Nm: only α and β", correct:false, why:"This reverses the two receptors; the five-subunit set belongs to the muscle receptor."},
  {t:"Both: only α4 and β2", correct:false, why:"α4/β2 is the brain Nn combination; ganglionic Nn is α3/β4 and α3/β2, and Nm has five kinds of subunits."},
  {t:"Nn: α3 and β4 only; Nm: α4 and β2 only", correct:false, why:"α3/β4 is a ganglionic Nn combination and α4/β2 is the brain Nn combination; neither describes Nm."},
  {t:"Nn: γ and ε; Nm: α and δ", correct:false, why:"γ and ε are found in Nm, and Nn is made only of α and β subunits."}],
 teach:"Nn receptors are composed only of α subunits (α2 to α9) and β subunits (β2 to β4); the brain combination is α4/β2 and the ganglionic combinations are α3/β4 and α3/β2. The Nm receptor at the skeletal neuromuscular junction is made of 5 protein subunits: α, β, γ, δ and ε. Both are ion channels that let Na+ in.",
 quote:"Composed of only α and β Subunits; α (α2- α9); β (β2- β4) … Skeletal Neuromuscular Junction in the Somatic System: 5 protein subunits (α, β, γ, δ, and ε)",
 note:"In the 10/1 audio he said NN is \"only beta and gammas\"; the slide reads α and β, and the slide is used here.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 6, 11"},

{id:"L08-003", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"recall",
 concept:"nn-alpha4beta2-brain", tags:[], source:"both",
 stem:"Which neuronal nicotinic (Nn) subunit combination is found in the brain?",
 options:[
  {t:"α3/β4", correct:false, why:"α3/β4 is a ganglionic combination."},
  {t:"α4/β2", correct:true, why:"The brain Nn receptor is the α4/β2 combination, the site of action of varenicline."},
  {t:"α3/β2", correct:false, why:"α3/β2 is the other ganglionic combination."},
  {t:"α, β, γ, δ, ε", correct:false, why:"That five-subunit set is the muscle nicotinic (Nm) receptor."}],
 teach:"Nn receptors differ by subunit combination and location: α4/β2 in the brain, α3/β4 and α3/β2 in the autonomic ganglia. The α4/β2 combination is the one to know because it is where varenicline acts. A drug selective for α4/β2 leaves ganglionic Nn and skeletal Nm receptors alone.",
 quote:"SOA: Brain α4/β2. Ganglia: Activate post-ganglionic neurons of both SNS and PNS α3/β4 and α3/β2",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 6; transcript 10/1"},

{id:"L08-004", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"recall", multi:true,
 concept:"nm-features", tags:[], source:"both",
 stem:"Which statements describe the muscle nicotinic (Nm) receptor? Select all that apply.",
 options:[
  {t:"It is at the skeletal neuromuscular junction", correct:true, why:"Nm is the receptor at the skeletal neuromuscular junction of the somatic system."},
  {t:"It has five subunits: α, β, γ, δ, ε", correct:true, why:"Nm is made of 5 protein subunits: α, β, γ, δ and ε."},
  {t:"Opening it lets Na+ in and depolarizes the cell", correct:true, why:"Acetylcholine opens the Nm channel; more Na+ enters than K+ leaves, so the membrane becomes more positive."},
  {t:"It is made only of α and β subunits", correct:false, why:"Only α and β is the neuronal Nn receptor."},
  {t:"It activates postganglionic SNS and PNS neurons", correct:false, why:"Activating postganglionic neurons of both systems is the job of ganglionic Nn receptors (α3/β4, α3/β2)."},
  {t:"Its main subtype is α4/β2 in the brain", correct:false, why:"α4/β2 is the brain Nn receptor."}],
 teach:"The Nm receptor is the nicotinic receptor of skeletal muscle in the somatic system, built from α, β, γ, δ and ε subunits. Acetylcholine binding opens it, Na+ enters and K+ leaves, the end plate depolarizes, voltage-gated Ca2+ channels open and the muscle contracts. Nn receptors (only α and β) are the ones in brain and ganglia. SNS = sympathetic nervous system; PNS = parasympathetic nervous system.",
 quote:"Skeletal Neuromuscular Junction in the Somatic System; 5 protein subunits (α, β, γ, δ, and ε); Skeletal Muscle Contraction",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 11, 13–15; transcript 10/1"},

{id:"L08-005", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"apply",
 concept:"ganglionic-nn-second-effects", tags:[], source:"slide",
 stem:"A nicotinic agonist activates neuronal nicotinic (Nn) receptors in the autonomic ganglia. Heart rate and salivation change even though the drug does not bind cardiac or glandular receptors. What explains these organ effects?",
 options:[
  {t:"Postganglionic neurons act on organ receptors", correct:true, why:"Ganglionic Nn activates postganglionic neurons of both the SNS and PNS, which then act on organ receptors such as M2, β, α1 and M3; these are secondary effects."},
  {t:"The drug binds M2 receptors in the heart directly, bypassing the ganglia", correct:false, why:"A nicotinic agonist acts on nicotinic receptors; M2 activation here is downstream of the ganglion."},
  {t:"The drug blocks acetylcholinesterase in the organs", correct:false, why:"That is the mechanism of an indirect-acting drug, not of a direct Nn agonist."},
  {t:"Muscle nicotinic (Nm) receptors are on the heart", correct:false, why:"Nm receptors are at the skeletal neuromuscular junction only."},
  {t:"Only the PNS ganglia carry Nn receptors", correct:false, why:"Nn receptors activate postganglionic neurons of both the SNS and the PNS."}],
 teach:"Nicotinic drugs act directly where Nn or Nm receptors are: brain, autonomic ganglia, adrenal medulla and skeletal muscle. Because ganglionic Nn receptors drive the postganglionic neurons of both the sympathetic nervous system (SNS) and parasympathetic nervous system (PNS), a ganglionic drug produces 2nd effects in organs through M2 (heart), β, α1 (vessels) and M3 (salivary gland) receptors. Predict the organ effect from where the receptor is.",
 quote:"Ganglia: Activate post-ganglionic neurons of both SNS and PNS … 2nd Effects",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Basic & Clinical Pharmacology of the Ganglion-Blocking Drugs — Mechanism of Action (p. 11 of 14)", t:"Ganglion-blocking drugs act at neuronal nicotinic receptors of both parasympathetic and sympathetic ganglia, so they can block all autonomic outflow. Nicotine itself, and acetylcholine amplified with a cholinesterase inhibitor, can produce depolarizing ganglion block. Organ effects of ganglionic drugs follow from which autonomic division dominates each tissue."}],
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 5–6"},

{id:"L08-006", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"apply",
 concept:"adrenal-medulla-nn", tags:[], source:"both",
 stem:"Nicotine reaches the adrenal medulla. Which receptor does acetylcholine or nicotine act on at this site?",
 options:[
  {t:"Muscle nicotinic (Nm) receptor", correct:false, why:"Nm is the skeletal neuromuscular junction receptor."},
  {t:"Neuronal nicotinic (Nn)", correct:true, why:"At the adrenal medulla a sympathetic fiber releases acetylcholine onto an Nn receptor; this is the exception to the adrenergic rule."},
  {t:"M3 muscarinic receptor", correct:false, why:"M3 is the salivary gland and smooth muscle receptor reached by postganglionic fibers."},
  {t:"α1 adrenergic", correct:false, why:"α1 receptors are on vascular smooth muscle and respond to norepinephrine, not acetylcholine."}],
 teach:"The adrenal medulla is the exception in the sympathetic system: the fiber that reaches it releases acetylcholine onto a neuronal nicotinic (Nn) receptor rather than releasing norepinephrine onto an adrenergic receptor. Anything that activates or blocks Nn receptors therefore also acts at the adrenal medulla. Nm receptors are only at skeletal muscle.",
 quote:"Ach NN Adrenal Medulla",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 4–5; transcript 10/1"},

{id:"L08-007", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"tell",
 concept:"direct-vs-indirect-acting", tags:[], source:"both",
 stem:"Which pairing of cholinergic receptor stimulant type and its action is correct? (ACh = acetylcholine)",
 options:[
  {t:"Direct-acting: block the enzyme that breaks down ACh", correct:false, why:"Blocking the enzyme is the indirect route; direct-acting drugs bind the receptor."},
  {t:"Indirect-acting: increase synaptic ACh", correct:true, why:"Indirect-acting drugs, reversible or irreversible, raise ACh at the synapse by blocking its breakdown."},
  {t:"Indirect-acting: alkaloids and choline esters", correct:false, why:"Alkaloids and choline esters are the two groups of direct-acting drugs."},
  {t:"Direct-acting: only act at muscarinic receptors", correct:false, why:"Direct-acting drugs act at muscarinic and nicotinic receptors."},
  {t:"Indirect-acting: bind the nicotinic receptor", correct:false, why:"Binding the receptor is the direct route."}],
 teach:"Receptor stimulants are divided into direct-acting drugs (alkaloids and choline esters), which bind muscarinic or nicotinic receptors themselves, and indirect-acting drugs (reversible or irreversible), which increase acetylcholine (ACh) by blocking its breakdown. Nicotinic receptors are either Nn in autonomic ganglion cells or Nm at the neuromuscular junction. An indirect drug affects the receptor by binding somewhere other than the receptor.",
 quote:"Direct-acting drugs: Alkaloids, Choline esters … ↑ Ach ← Indirect-acting drugs: Reversible, Irreversible",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 3; transcript 10/1"},

{id:"L08-008", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnag", skill:"recall",
 concept:"varenicline-moa", tags:["druglist"], source:"both",
 stem:"Varenicline (Chantix) is best described as:",
 options:[
  {t:"A competitive antagonist at muscle nicotinic (Nm) receptors", correct:false, why:"Competitive Nm antagonism is the curare-like (non-depolarizing) mechanism."},
  {t:"A full agonist at ganglionic α3/β4 receptors", correct:false, why:"Varenicline is selective for α4/β2 and is a partial agonist; it leaves ganglionic receptors alone."},
  {t:"A partial agonist at α4/β2 Nn receptors", correct:true, why:"Varenicline is a high-affinity, selective partial agonist at the central α4/β2 neuronal nicotinic (Nn) receptor."},
  {t:"An acetylcholinesterase inhibitor", correct:false, why:"Enzyme inhibitors are indirect drugs such as the -stigmines; varenicline binds the receptor directly."},
  {t:"A depolarizing agent at the NMJ", correct:false, why:"The depolarizing agent at the neuromuscular junction (NMJ) is succinylcholine."}],
 teach:"Varenicline has high affinity and partial agonist activity at the α4/β2 central nicotinic (Nn) receptor; its site of action (SOA) is the central nervous system. With low nicotine (withdrawal) it activates the receptor and decreases craving and withdrawal; in a smoker it competes with nicotine and blunts the nicotine effect. He called the α4/β2 partial agonist mechanism the must-know fact.",
 quote:"High affinity and Partial Agonist at the α4/β2 central nicotinic (NN) receptor",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 7–8; transcript 10/1"},

{id:"L08-009", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnag", skill:"apply", multi:true,
 concept:"varenicline-effects", tags:["druglist"], source:"both",
 stem:"A patient trying to stop smoking starts varenicline. Which effects follow from its mechanism? Select all that apply.",
 options:[
  {t:"Decreased craving and withdrawal", correct:true, why:"Partial activation of α4/β2 receptors relieves craving and withdrawal when nicotine is low."},
  {t:"A blunted effect of smoked nicotine", correct:true, why:"Its high affinity lets it compete with nicotine, and its lower efficacy blunts the nicotine effect."},
  {t:"Action in the central nervous system", correct:true, why:"Its site of action is the CNS (central α4/β2 receptors)."},
  {t:"Skeletal muscle paralysis", correct:false, why:"Varenicline leaves Nm receptors at skeletal muscle alone; paralysis is the effect of succinylcholine or curare-like drugs."},
  {t:"Block of all autonomic ganglia", correct:false, why:"Varenicline is selective for α4/β2 and leaves ganglionic Nn receptors alone."}],
 teach:"Varenicline is a selective, high-affinity partial agonist at central α4/β2 neuronal nicotinic receptors. A partial agonist behaves as an agonist when the baseline is low (withdrawal) and as an antagonist when a full agonist is present (it competes with nicotine). Its selectivity means ganglionic Nn and skeletal Nm receptors are not targeted. CNS = central nervous system.",
 quote:"Decrease craving and withdrawal; Blunt nicotine effect; SOA: CNS",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 8; transcript 10/1"},

{id:"L08-010", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnag", skill:"recall",
 concept:"varenicline-adr", tags:["druglist"], source:"both",
 stem:"Which is among the most common adverse drug reactions (ADRs) of varenicline?",
 options:[
  {t:"Hyperkalemia", correct:false, why:"Hyperkalemia is a succinylcholine ADR."},
  {t:"Histamine release with bronchial spasm", correct:false, why:"Histamine release is an ADR of some curare-like drugs, mainly atracurium."},
  {t:"Nausea", correct:true, why:"Nausea (16–40%) and vomiting are the most common GI effects; headache, insomnia and depression are the CNS effects."},
  {t:"Miosis and blurred vision", correct:false, why:"Miosis and blurred vision are ADRs of echothiophate in the eye."},
  {t:"Respiratory paralysis", correct:false, why:"Respiratory paralysis is an ADR of curare-like drugs."}],
 teach:"The most common side effects of varenicline are GI (nausea, 16–40%, and vomiting) and CNS (headache, insomnia, depression). Its site of action is the brain, so most of its side effects are central. He said not to memorize the percentage; it shows how frequent nausea is. GI = gastrointestinal; CNS = central nervous system.",
 quote:"Most common: GI: Nausea (16-40%) & Vomiting; CNS: Headache, Insomnia, Depression",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 9; transcript 10/1"},

{id:"L08-011", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nmj", skill:"recall",
 concept:"nmj-agent-goal", tags:[], source:"slide",
 stem:"What is the primary goal of neuromuscular junction (NMJ) agents?",
 options:[
  {t:"Act at Nm receptors with little or no effect at ganglionic Nn", correct:true, why:"NMJ agents aim to affect transmission at muscle nicotinic (Nm) receptors with no or little effect at neuronal nicotinic (Nn) receptors in the autonomic ganglia."},
  {t:"Act at ganglionic Nn receptors with no effect on skeletal muscle", correct:false, why:"This reverses the target; NMJ agents are aimed at skeletal muscle Nm receptors."},
  {t:"Block muscarinic receptors in the heart", correct:false, why:"Cardiac muscarinic effects are side effects to avoid, not the goal."},
  {t:"Activate α4/β2 receptors in the brain", correct:false, why:"α4/β2 is the varenicline target."},
  {t:"Prevent ACh synthesis in the nerve", correct:false, why:"NMJ agents act at the receptor or at the enzyme that breaks down acetylcholine (ACh)."}],
 teach:"NMJ agents should affect synaptic transmission at the muscle nicotinic (Nm) receptor while sparing neuronal nicotinic (Nn) receptors at the autonomic ganglia. They come in two types: direct (bind Nm; depolarizing agonists or non-depolarizing antagonists) and indirect (bind acetylcholinesterase and raise acetylcholine). Loss of this selectivity explains ganglionic side effects such as pancuronium tachycardia or succinylcholine cardiovascular effects.",
 quote:"The primary goal is to affect synaptic transmission at the nicotinic receptors at NMJ (NM) with no or little effect at nicotinic receptors at autonomic ganglion (NN)",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Chapter introduction (p. 3 of 14)", t:"Antinicotinic drugs are divided into ganglion blockers and neuromuscular junction blockers. Ganglion blockers have little clinical use, while neuromuscular blockers are heavily used."}],
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 12"},

{id:"L08-012", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nmj", skill:"tell",
 concept:"nmj-three-classes", tags:[], source:"both",
 stem:"Which pairing of a neuromuscular junction (NMJ) drug class with its mechanism is correct?",
 options:[
  {t:"Depolarizing agents: direct antagonists", correct:false, why:"Depolarizing agents are direct agonists (acetylcholine, succinylcholine); they open the channel."},
  {t:"Non-depolarizing: direct antagonists", correct:true, why:"Non-depolarizing agents (curare-like drugs) bind the muscle nicotinic receptor with affinity but no efficacy."},
  {t:"Cholinesterase inhibitors: direct Nm agonists", correct:false, why:"Cholinesterase inhibitors are indirect; they bind the enzyme, not the receptor."},
  {t:"Non-depolarizing agents: enzyme inhibitors", correct:false, why:"Enzyme inhibition is the indirect class; non-depolarizing agents bind the receptor."},
  {t:"Depolarizing agents: lower synaptic ACh", correct:false, why:"Depolarizing agents open the channel; they do not lower acetylcholine (ACh)."}],
 teach:"Three classes act on the NMJ. Depolarizing agents are nicotinic receptor agonists (acetylcholine, succinylcholine): opening the channel lets Na+ in and makes the membrane more positive. Non-depolarizing agents are nicotinic receptor antagonists (curare-like drugs) that bind and sit with no efficacy. Cholinesterase inhibitors are indirect antagonists that bind the enzyme and raise synaptic acetylcholine.",
 quote:"Depolarizing agents: Nicotinic Receptors Agonists; Non-depolarizing agents: Nicotinic Receptors Antagonist; Cholinesterase Enzyme Inhibitors: Indirect Antagonists",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 11–12; transcript 10/1"},

{id:"L08-013", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nmj", skill:"recall",
 concept:"nm-activation-sequence", tags:[], source:"both",
 stem:"Acetylcholine opens the muscle nicotinic (Nm) channel at the skeletal muscle cell. What happens next that leads to contraction?",
 options:[
  {t:"Depolarization opens voltage-gated Ca2+ channels", correct:true, why:"More Na+ enters than K+ leaves, the membrane becomes more positive, and voltage-gated Ca2+ channels open; Ca2+ allows actin and myosin to contract."},
  {t:"The membrane hyperpolarizes and K+ channels close", correct:false, why:"Opening the Nm channel makes the membrane more positive, not more negative."},
  {t:"Gαq activates phospholipase C", correct:false, why:"The Nm receptor is a ligand-gated ion channel, not a G protein–coupled receptor."},
  {t:"The Na+/K+ ATPase pumps Na+ into the cell", correct:false, why:"The pump moves Na+ out and K+ in; it restores the resting state during recovery."},
  {t:"Acetylcholinesterase releases more acetylcholine", correct:false, why:"Acetylcholinesterase breaks acetylcholine down into choline and acetate."}],
 teach:"At rest, acetylcholine sits in vesicles. After release it binds the α subunits of the Nm ion channel; Na+ comes in and K+ goes out, the membrane depolarizes, voltage-gated Ca2+ channels open, and Ca2+ drives actin–myosin contraction. Recovery: acetylcholinesterase splits acetylcholine into choline and acetate, the channel closes, and the Na+/K+ ATPase restores the ion gradients.",
 quote:"Nicotinic Receptors (NM) (1) At Rest … (2) ACh Release … (3) Activation … (4) Recovery",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 13–17; transcript 10/1"},

{id:"L08-014", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"tell",
 concept:"depolarizing-vs-nondepolarizing", tags:[], source:"slide",
 stem:"Succinylcholine and rocuronium both cause paralysis. Which statement correctly separates them?",
 options:[
  {t:"Succinylcholine opens the channel; rocuronium keeps it shut", correct:true, why:"Succinylcholine is a depolarizing agonist; rocuronium is a non-depolarizing competitive antagonist."},
  {t:"Succinylcholine stops channels from opening; rocuronium opens them", correct:false, why:"This reverses the two; the depolarizing drug is succinylcholine."},
  {t:"Both are competitive antagonists at muscle nicotinic (Nm) receptors", correct:false, why:"Only rocuronium is a competitive antagonist; succinylcholine is an agonist."},
  {t:"Both inhibit acetylcholinesterase", correct:false, why:"Neither acts on the enzyme; both bind the muscle nicotinic (Nm) receptor."},
  {t:"Succinylcholine blocks ACh release; rocuronium is an agonist", correct:false, why:"Blocking acetylcholine (ACh) release is botulinum toxin; rocuronium is an antagonist."}],
 teach:"Both NMJ agents cause paralysis. Depolarizing: succinylcholine (IV; Anectine) is an agonist that opens nicotinic ion channels. Non-depolarizing: curare (prototype), mivacurium, vecuronium, rocuronium and pancuronium are competitive antagonists that stop the nicotinic ion channels from opening. Drugs with -cur- in the name are curare-like.",
 quote:"Both Drugs Causes Paralysis … Depolarizing = Open nicotinic ion channels, Agonist … Non-depolarizing = Stop the nicotinic ion channels from opening, Competitive Antagonist",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 19"},

{id:"L08-015", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"recall",
 concept:"sch-structure-use", tags:["druglist"], source:"both",
 stem:"Which statement about succinylcholine (SCh) is CORRECT?",
 options:[
  {t:"It resembles two ACh molecules joined end to end", correct:true, why:"SCh resembles two acetylcholine (ACh) molecules joined at the alkyl ends, so it acts as an agonist."},
  {t:"It has a slow onset and long duration", correct:false, why:"SCh has a rapid onset and short duration."},
  {t:"It is a competitive antagonist at Nm", correct:false, why:"SCh depolarizes the neuromuscular junction; it is a depolarizing agonist."},
  {t:"It is given orally for the treatment of myasthenia gravis", correct:false, why:"SCh is given IV for rapid intubation and as an adjunct to general anesthesia; myasthenia gravis is treated with pyridostigmine or neostigmine."},
  {t:"It only acts in the central nervous system", correct:false, why:"SCh acts at the neuromuscular junction and, at higher doses, at autonomic ganglia."}],
 teach:"Succinylcholine looks like two acetylcholine molecules joined at the alkyl ends, so it is a depolarizing agonist at the neuromuscular junction (NMJ). It has a rapid onset and short duration and is used IV for rapid intubation and as an adjunct to general anesthesia. At increased doses it also stimulates ganglia and therefore the PNS and SNS.",
 quote:"SCh resembles two molecules of Ach joined at the alkyl ends; Depolarize at the NMJ; Rapid onset and short duration; Use: Rapid intubation, Adjunct to general anesthesia",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 20; transcript 10/1"},

{id:"L08-016", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"apply",
 concept:"sch-ganglia-high-dose", tags:[], source:"slide",
 stem:"A patient receives a high dose of succinylcholine (SCh). Besides the neuromuscular junction, which site can SCh stimulate, producing cardiovascular effects?",
 options:[
  {t:"Autonomic ganglia (PNS and SNS)", correct:true, why:"At increased doses SCh stimulates ganglia, and thus the parasympathetic (PNS) and sympathetic (SNS) systems; downstream M2, β1 and α1 receptors change heart and vessels."},
  {t:"α4/β2 receptors in the brain", correct:false, why:"α4/β2 is the varenicline site, not the succinylcholine site."},
  {t:"Acetylcholinesterase in cardiac tissue", correct:false, why:"SCh is a receptor agonist, not an enzyme inhibitor."},
  {t:"Presynaptic SNARE proteins", correct:false, why:"SNARE proteins are cleaved by botulinum toxin."}],
 teach:"Succinylcholine is selective for the muscle nicotinic (Nm) receptor at clinical doses, but at increased doses it stimulates neuronal nicotinic (Nn) receptors in autonomic ganglia, activating both the parasympathetic and sympathetic outflow. The downstream receptors (M2 and β1 in the heart, α1 on vessels) account for hypertension and arrhythmias listed among its ADRs.",
 quote:"SCh will stimulate ganglia and thus PNS & SNS ↑ Doses",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 20, 25"},

{id:"L08-017", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"tell",
 concept:"sch-phase1-vs-phase2", tags:[], source:"both",
 stem:"Which statement correctly contrasts phase I and phase II succinylcholine block?",
 options:[
  {t:"Phase I: end plate cannot reprime; phase II: channel block", correct:true, why:"In phase I the agonist keeps the end plate depolarized so it cannot repolarize; in phase II channel blockade prevents Na+/K+ movement and prolongs paralysis."},
  {t:"Phase I: channel blockade; phase II: prolonged depolarization", correct:false, why:"This reverses the phases."},
  {t:"Phase I: competitive antagonism; phase II: acetylcholinesterase inhibition", correct:false, why:"Succinylcholine is an agonist in phase I and a channel blocker in phase II; neither phase is competitive antagonism or enzyme inhibition."},
  {t:"Phase I: rapid breakdown by acetylcholinesterase; phase II: release", correct:false, why:"Succinylcholine is not metabolized effectively at the synapse; that is why phase I occurs."},
  {t:"Both phases are a non-depolarizing block", correct:false, why:"Phase I is a depolarizing block."}],
 teach:"Normal transmission needs repetitive firing, rapid breakdown of acetylcholine, and repolarization of the motor end plate (re-priming). Phase I (depolarizing) block: succinylcholine opens the channel but is not metabolized effectively, so the end plate stays depolarized, cannot reprime, and the muscle is paralyzed. Phase II block: succinylcholine blocks the channel, preventing Na+/K+ movement and prolonging the paralysis.",
 quote:"Phase I block (depolarizing) … Excitation-contraction coupling requires end plate repolarization (“repriming”) and repetitive firing to maintain muscle tension, thus causing paralysis. Phase II block: Channel blockade prevent movement of Na+/K+ and prolongs the paralysis",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 21–24; transcript 10/1"},

{id:"L08-018", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"recall", multi:true,
 concept:"sch-phase1-features", tags:[], source:"slide",
 stem:"Which features describe the state of depolarizing blockade (phase I) produced by succinylcholine? Select all that apply.",
 options:[
  {t:"Longer synaptic half-life than acetylcholine", correct:true, why:"Succinylcholine is not broken down quickly at the synapse, so its synaptic half-life is longer."},
  {t:"Prolonged depolarization of the motor end plate", correct:true, why:"The end plate stays depolarized and cannot be re-primed."},
  {t:"Blocks downstream channels and shields the rest of the muscle", correct:true, why:"The sustained depolarization blocks downstream channels and shields the rest of the muscle."},
  {t:"Competes with acetylcholine without opening the channel", correct:false, why:"Binding without opening the channel describes curare-like (non-depolarizing) drugs."},
  {t:"Rapid metabolism of the drug at the synapse", correct:false, why:"Rapid metabolism is a feature of acetylcholine; succinylcholine is not metabolized effectively at the synapse."}],
 teach:"Acetylcholine produces muscle tension through repetitive firing, is quickly metabolized, and lets the motor end plate repolarize (re-prime). Succinylcholine has a longer synaptic half-life, so it causes a prolonged depolarization of the motor end plate that blocks downstream channels and shields the rest of the muscle: this is the state of depolarizing blockade.",
 quote:"State of Depolarizing Blockade: 1) Longer synaptic T1/2; 2) Prolonged depolarization of the motor end plate; 3) Blocks downstream channels & shields the rest of the muscle",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 21–22"},

{id:"L08-019", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"recall", multi:true,
 concept:"sch-adrs", tags:["druglist"], source:"slide",
 stem:"Which are adverse drug reactions (ADRs) of succinylcholine? Select all that apply.",
 options:[
  {t:"Hyperkalemia", correct:true, why:"Muscle cells lose K+ and gain Ca++ and Na+, raising plasma K+."},
  {t:"Hypertension and arrhythmias", correct:true, why:"Cardiovascular ADRs follow ganglionic stimulation of the SNS and PNS."},
  {t:"Post-operative muscle pain", correct:true, why:"Myalgia follows the unsynchronized contractions."},
  {t:"Histamine release with marked hypotension", correct:false, why:"Histamine release is an ADR of curare-like drugs, most of all atracurium."},
  {t:"Nausea and depression", correct:false, why:"Nausea and depression are varenicline ADRs."}],
 teach:"Succinylcholine ADRs: hyperkalemia (muscle cells lose K+ and gain Ca++ and Na+), cardiovascular effects (hypertension and arrhythmias, from stimulation of ganglia), and post-operative muscle pain (myalgia from unsynchronized contractions). Because of the hyperkalemia risk, it is avoided in renal-deficient and dehydrated patients.",
 quote:"Hyperkalemia: Muscle cell loss of K+ & gain of Ca++, & Na+; Cardiovascular: Hypertension & Arrhythmias; Post-operative muscle pain: Myalgia; Unsynchronized contractions",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 25"},

{id:"L08-020", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"apply",
 concept:"sch-halothane-mh-dantrolene", tags:[], source:"slide",
 stem:"During surgery a patient receives halothane and succinylcholine and develops a rising body temperature from skeletal muscle heat production. Which drug is given, and how does it act?",
 options:[
  {t:"Dantrolene: ryanodine receptor antagonist", correct:true, why:"The drug–drug interaction (DDI) causes malignant hyperthermia from abnormal Ca++ release; dantrolene blocks the ryanodine receptor and decreases intracellular Ca++."},
  {t:"Neostigmine: acetylcholinesterase inhibitor", correct:false, why:"Neostigmine reverses curare-like drugs; it does not treat malignant hyperthermia."},
  {t:"Atropine: M1, M2 and M3 antagonist", correct:false, why:"Atropine treats muscarinic excess (organophosphates), not Ca++ release in muscle."},
  {t:"Pralidoxime: cholinesterase reactivator", correct:false, why:"Pralidoxime reactivates the enzyme after organophosphate poisoning."},
  {t:"Rocuronium: competitive Nm antagonist", correct:false, why:"A non-depolarizing blocker does not stop the abnormal Ca++ release from muscle stores."}],
 teach:"Succinylcholine with inhaled anesthetics such as halothane is a drug–drug interaction that can cause malignant hyperthermia. It is caused by abnormal release of Ca++ from stores in skeletal muscle and skeletal muscle heat production. Dantrolene is an antagonist at the ryanodine receptor and decreases intracellular Ca++.",
 quote:"Inhaled anesthetics (e.g., halothane): Malignant hyperthermia … Dantrolene - Antagonist to the Ryanodine receptor - => ↓ intracellular Ca++",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 26"},

{id:"L08-021", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"curare", skill:"apply",
 concept:"curare-no-anesthesia", tags:[], source:"both",
 stem:"A patient is given rocuronium during surgery, but the general anesthetic is omitted. What is the patient most likely to experience?",
 options:[
  {t:"Paralysis while still awake", correct:true, why:"Curare-like drugs relax skeletal muscle and have no CNS effect; without the anesthetic the patient is paralyzed but can feel and hear."},
  {t:"Sleep without muscle relaxation", correct:false, why:"Rocuronium does not put the patient to sleep; it acts at skeletal muscle."},
  {t:"Muscle cramps and hyperkalemia", correct:false, why:"Hyperkalemia and unsynchronized contractions are succinylcholine effects."},
  {t:"Sleep and paralysis", correct:false, why:"Rocuronium produces paralysis only; it is not an anesthetic."}],
 teach:"Non-depolarizing agents (curare-like drugs) are used as an adjuvant in surgical anesthesia to relax skeletal muscle, not as anesthetics, and have no central nervous system (CNS) effect. Given alone they leave a patient paralyzed, unable to move, talk or blink, while still able to feel and hear. He described lawsuits in which the anesthetic was forgotten.",
 quote:"Used as an adjuvant in surgical anesthesia to obtain relaxation of skeletal muscle (Not as anesthetic)",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 27, 32; transcript 10/1"},

{id:"L08-022", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"curare", skill:"recall", multi:true,
 concept:"curare-like-members", tags:["druglist"], source:"both",
 stem:"Which drugs are non-depolarizing (curare-like) competitive antagonists at the muscle nicotinic (Nm) receptor? Select all that apply.",
 options:[
  {t:"Mivacurium", correct:true, why:"Mivacurium is listed with the non-depolarizing agents; it carries -cur-."},
  {t:"Vecuronium", correct:true, why:"Vecuronium is a curare-like drug."},
  {t:"Pancuronium", correct:true, why:"Pancuronium is a curare-like drug (it also blocks autonomic ganglia)."},
  {t:"Succinylcholine", correct:false, why:"Succinylcholine is the depolarizing agonist."},
  {t:"Neostigmine", correct:false, why:"Neostigmine is a reversible cholinesterase inhibitor used to reverse curare-like drugs."},
  {t:"Edrophonium", correct:false, why:"Edrophonium is a short-acting cholinesterase inhibitor."}],
 teach:"Curare (tubocurarine) is the prototype. Mivacurium, vecuronium, rocuronium, pancuronium (and atracurium, cisatracurium in the comparison table) are curare-like: any drug with -cur- in the middle has the same mechanism and site of action. They are competitive antagonists that stop nicotinic ion channels from opening, causing paralysis.",
 quote:"Non-depolarizing: Curare (prototype), Mivacurium, Vecuronium, Rocuronium, Pancuronium … Competitive Antagonist",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 19, 27; transcript 10/1"},

{id:"L08-023", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"curare", skill:"figure",
 concept:"curare-curve-right", tags:[], source:"slide",
 stem:"A dose–response curve for acetylcholine (ACh) on skeletal muscle is drawn alone, then again in the presence of curare. The curare curve is shifted to the right and reaches the same maximum. Curare is acting as:",
 options:[
  {t:"A competitive antagonist", correct:true, why:"A rightward shift with the same maximum means more ACh can overcome the block: competitive, reversible antagonism."},
  {t:"An irreversible antagonist", correct:false, why:"An irreversible antagonist lowers the maximum response."},
  {t:"A depolarizing agonist", correct:false, why:"An agonist like succinylcholine opens the channel; curare stops it from opening."},
  {t:"An acetylcholinesterase inhibitor", correct:false, why:"Inhibiting the enzyme raises ACh and shifts its curve to the left."},
  {t:"A full agonist", correct:false, why:"A full agonist would add to ACh and shift the curve left, not right."}],
 teach:"Curare binds the α subunits of the muscle nicotinic receptor at the acetylcholine site and has affinity but no efficacy. Because the block is competitive and reversible, a higher acetylcholine dose produces the same maximum: the curve moves right without a drop in Emax. Contrast: an acetylcholinesterase inhibitor shifts the acetylcholine curve left.",
 quote:"MOA: Curve Shift — ACh / ACH + Curare",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 28–29"},

{id:"L08-024", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"curare", skill:"tell",
 concept:"pancuronium-ganglia-tachycardia", tags:[], source:"slide",
 stem:"Which non-depolarizing agent blocks autonomic ganglia and is linked to tachycardia?",
 options:[
  {t:"Pancuronium", correct:true, why:"In the comparison table only pancuronium has a ganglionic block (+ Block), and tachycardia is listed under pancuronium."},
  {t:"Rocuronium", correct:false, why:"Rocuronium has no effect on autonomic ganglia."},
  {t:"Vecuronium", correct:false, why:"Vecuronium has no effect on autonomic ganglia."},
  {t:"Atracurium", correct:false, why:"Atracurium has no ganglionic effect; its notable ADR is histamine release."},
  {t:"Cisatracurium", correct:false, why:"Cisatracurium has no effect on autonomic ganglia."}],
 teach:"The non-depolarizing agents differ in duration of action, site of action and side effects. Pancuronium (half-life 92 min) blocks autonomic ganglia and is the curare-like drug listed with tachycardia. Atracurium, cisatracurium, rocuronium and vecuronium have no effect on the ganglia.",
 quote:"Pancuronium 92 mins + Block … Tachycardia: Pancuronium",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Ganglion-Blocking Drugs — Organ System Effects: Cardiovascular system (p. 11 of 14)", t:"Ganglionic blockade causes a moderate tachycardia because the sinoatrial node is usually dominated by the parasympathetic nervous system. Blood pressure can fall because sympathetic vasoconstrictor tone to blood vessels is lost."}],
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 30, 32"},

{id:"L08-025", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"curare", skill:"tell",
 concept:"atracurium-histamine", tags:[], source:"slide",
 stem:"Which curare-like drug has the greatest histamine release, causing bronchial spasm and marked hypotension?",
 options:[
  {t:"Atracurium", correct:true, why:"Atracurium has +++ histamine release; the others have +."},
  {t:"Vecuronium", correct:false, why:"Vecuronium is rated + for histamine release."},
  {t:"Pancuronium", correct:false, why:"Pancuronium is rated +; its notable effect is ganglionic block with tachycardia."},
  {t:"Cisatracurium", correct:false, why:"Cisatracurium is rated + for histamine release."},
  {t:"Rocuronium", correct:false, why:"Rocuronium is rated + for histamine release."}],
 teach:"Histamine release by curare-like drugs causes bronchial spasms and marked hypotension, listed as an allergic reaction. Atracurium is the one with the most histamine release (+++). Pancuronium is the one that blocks ganglia (tachycardia). Curare-like drugs also cause respiratory paralysis and have no CNS effect.",
 quote:"Histamine Release: - Bronchial spasms - Marked Hypotension … Atracurium 45 mins No Effect +++",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 30, 32"},

{id:"L08-026", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"recall", multi:true,
 concept:"ache-inhibitor-moa-uses", tags:[], source:"slide",
 stem:"Cholinesterase inhibitors bind the active site of acetylcholinesterase and antagonize the enzyme. Which effects are they used for? Select all that apply.",
 options:[
  {t:"Increasing transmission", correct:true, why:"Blocking breakdown potentiates acetylcholine and increases transmission."},
  {t:"Increasing PNS tone", correct:true, why:"More acetylcholine increases parasympathetic (PNS) tone."},
  {t:"Reversing curare effects", correct:true, why:"Raising acetylcholine outcompetes curare-like drugs at the Nm receptor."},
  {t:"Decreasing central cholinergic activity", correct:false, why:"They increase central cholinergic activity (the Alzheimer's use)."},
  {t:"Blocking acetylcholine release", correct:false, why:"Blocking release is botulinum toxin."}],
 teach:"Cholinesterase inhibitors bind to the active site of acetylcholinesterase and antagonize the enzyme. They differ in their pharmacokinetics (volume of distribution, duration of action). They potentiate acetylcholine: increasing transmission, increasing PNS tone, increasing central cholinergic activity, and reversing curare effects.",
 quote:"Bind to the active site and antagonizes enzyme … Used to potentiate the actions of Ach: Increasing transmission; Increase PNS tone; Increase central cholinergic activity; Reverse curare effects",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 33–34"},

{id:"L08-027", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"figure",
 concept:"ache-inhibitor-curve-left", tags:["poll"], source:"both",
 stem:"An acetylcholinesterase (AChE) inhibitor is added. What happens to the dose–response curve of acetylcholine at the muscle nicotinic receptor?",
 options:[
  {t:"Shifts right; acetylcholine is less potent", correct:false, why:"A rightward shift is what curare does."},
  {t:"Shifts left; acetylcholine is more potent", correct:true, why:"Acetylcholine is not broken down, so more stays at the receptor for longer; less dose gives the same response."},
  {t:"Maximum falls; acetylcholine loses efficacy", correct:false, why:"Lowering the maximum is irreversible antagonism; the enzyme inhibitor helps acetylcholine."},
  {t:"No change; the drug acts on the enzyme", correct:false, why:"Acting on the enzyme is exactly why acetylcholine potency changes; it is an indirect effect."}],
 teach:"With AChE inhibited, acetylcholine is not split into choline and acetate, so more acetylcholine is available at the receptor for longer and contraction is greater. The acetylcholine curve moves to the left (greater potency). This is the rationale for AChE inhibitors in myasthenia gravis, where patients are losing nicotinic receptors.",
 quote:"MOA: AChE Inhibited",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 35–36; transcript 10/1"},

{id:"L08-028", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"apply",
 concept:"ache-site-anywhere", tags:[], source:"slide",
 stem:"Where do acetylcholinesterase inhibitors act?",
 options:[
  {t:"Only at the neuromuscular junction", correct:false, why:"They also act in the CNS (few synapses) and anywhere else acetylcholine is released."},
  {t:"Only in the brain", correct:false, why:"They also act in the periphery, including the neuromuscular junction."},
  {t:"Anywhere acetylcholine is released", correct:true, why:"Ganglia, muscarinic organs, the neuromuscular junction and some CNS synapses all have acetylcholine and the enzyme."},
  {t:"Only at adrenergic synapses", correct:false, why:"Adrenergic synapses release norepinephrine, not acetylcholine."}],
 teach:"Acetylcholinesterase inhibitors act at synapses in the central nervous system (CNS) (few), in the periphery at the neuromuscular junction, and anywhere acetylcholine is released, including autonomic ganglia and muscarinic organs. That is why their ADRs are those of excess acetylcholine (DUMBBELSS) plus GI and CNS effects.",
 quote:"Synapses in the CNS (few); Periphery at the Neuromuscular Junction; Anywhere Ach is released",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 37"},

{id:"L08-029", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"recall",
 concept:"edrophonium-mg-diagnosis", tags:["druglist"], source:"slide",
 stem:"Edrophonium is used for:",
 options:[
  {t:"Diagnosis of myasthenia gravis", correct:true, why:"Edrophonium is short-acting and readily reversible; the Tensilon test measures a transient increase in grip strength."},
  {t:"Long-term treatment of Alzheimer's disease", correct:false, why:"Alzheimer's disease is treated with donepezil, rivastigmine or galantamine."},
  {t:"Glaucoma", correct:false, why:"Echothiophate is used for glaucoma."},
  {t:"Rapid intubation", correct:false, why:"Rapid intubation uses succinylcholine or curare-like drugs."},
  {t:"Atropine poisoning", correct:false, why:"Physostigmine is the drug of choice for anti-muscarinic poisoning."}],
 teach:"Edrophonium is a cholinesterase inhibitor with a short duration of action that is readily reversible. It is used to diagnose myasthenia gravis or to decide whether the medication needs to be adjusted. Untreated patients have muscular weakness; the Tensilon test measures a transient increase in grip strength.",
 quote:"Short duration of action; Readily reversible; Use in the diagnosis of myasthenia gravis or if the medication need to be adjusted … Tensilon Test: Measure transient increase in grip strength",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 38"},

{id:"L08-030", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"tell",
 concept:"physo-vs-neo-bbb", tags:["druglist"], source:"slide",
 stem:"Which statement correctly separates physostigmine from neostigmine and pyridostigmine?",
 options:[
  {t:"Only physostigmine, a tertiary amine, crosses the blood–brain barrier", correct:true, why:"Physostigmine readily penetrates the central nervous system (CNS); neostigmine and pyridostigmine are quaternary amines that do not cross the blood–brain barrier (BBB)."},
  {t:"Physostigmine is quaternary; the others are tertiary and enter the CNS", correct:false, why:"This reverses the structures."},
  {t:"Physostigmine is irreversible; the others are reversible", correct:false, why:"All three are reversible cholinesterase inhibitors with longer duration of action."},
  {t:"All three cross the BBB equally", correct:false, why:"Only physostigmine readily penetrates the CNS."},
  {t:"Physostigmine is a direct Nm agonist; the others inhibit the enzyme instead", correct:false, why:"All three inhibit acetylcholinesterase."}],
 teach:"Physostigmine (Antilirium) is a tertiary amine that readily penetrates the CNS; it is the drug of choice for poisoning by anti-muscarinic agents such as atropine. Pyridostigmine (Mestinon) and neostigmine (Prostigmin) are quaternary amines that do not cross the BBB; they treat myasthenia gravis and reverse curare-like overdose. All three are reversible with a longer duration of action than edrophonium.",
 quote:"Physostigmine (Antilirium): Tertiary amine and readily Penetrate the CNS … PyriDOstigmine (Mestinon) & Neostigmine (Prostigmin): Quaternary amine and DO NOT cross the BBB",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Cholinesterase regenerator compounds; Ganglion-Blocking Drugs — Central nervous system (p. 10–11 of 14)", t:"Drugs with positively charged quaternary ammonium groups, such as pralidoxime, do not enter the central nervous system. Tertiary or secondary amines such as atropine and mecamylamine cross the blood–brain barrier and act centrally."}],
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 39"},

{id:"L08-031", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"apply",
 concept:"physostigmine-antimuscarinic-poisoning", tags:["druglist"], source:"slide",
 stem:"A patient has poisoning from an anti-muscarinic agent (atropine), with central and peripheral signs. Which drug is the drug of choice?",
 options:[
  {t:"Neostigmine", correct:false, why:"Neostigmine is quaternary and does not cross the blood–brain barrier, so it misses the central signs."},
  {t:"Physostigmine", correct:true, why:"Physostigmine is a tertiary amine that readily penetrates the CNS; it is the drug of choice for anti-muscarinic poisoning."},
  {t:"Pralidoxime", correct:false, why:"Pralidoxime reactivates the enzyme after organophosphate poisoning."},
  {t:"Edrophonium", correct:false, why:"Edrophonium is short-acting and used for diagnosis of myasthenia gravis."},
  {t:"Pyridostigmine", correct:false, why:"Pyridostigmine is quaternary and does not cross the blood–brain barrier."}],
 teach:"Raising acetylcholine with a cholinesterase inhibitor overcomes muscarinic blockade by atropine. Physostigmine is chosen because, as a tertiary amine, it penetrates the central nervous system (CNS) and reaches the central effects as well. Neostigmine and pyridostigmine are quaternary and stay outside the brain.",
 quote:"Physostigmine (Antilirium): Tertiary amine and readily Penetrate the CNS; Drug of choice for treating poisoning due to anti-muscarinic agents (e.g., atropine)",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Adverse Effects (p. 10 of 14)", t:"Atropine overdose causes dry mouth, mydriasis, tachycardia, hot flushed skin, agitation and delirium. Katzung states that poison control experts discourage physostigmine for atropine overdose and prefer symptomatic management; when physostigmine is used, small doses are given slowly IV."}],
 note:"Katzung Ch. 8 says poison control experts discourage physostigmine for atropine overdose; the slide calls physostigmine the drug of choice. The exam is written from the slide.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 39"},

{id:"L08-032", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"apply",
 concept:"neostigmine-reverse-curare-mg", tags:["druglist"], source:"both",
 stem:"After surgery, a patient still has muscle weakness from a curare-like overdose. Which drug reverses it?",
 options:[
  {t:"Succinylcholine", correct:false, why:"Succinylcholine is a depolarizing blocker; it adds paralysis."},
  {t:"Dantrolene", correct:false, why:"Dantrolene treats malignant hyperthermia by blocking the ryanodine receptor."},
  {t:"Neostigmine", correct:true, why:"Neostigmine (with pyridostigmine) is used to reverse curare-like overdose and to treat myasthenia gravis."},
  {t:"Botulinum toxin", correct:false, why:"Botulinum toxin blocks acetylcholine release and causes muscle relaxation."},
  {t:"Donepezil", correct:false, why:"Donepezil is a lipophilic cholinesterase inhibitor used for Alzheimer's disease."}],
 teach:"Curare-like drugs are competitive and reversible, so raising acetylcholine at the muscle nicotinic receptor overcomes the block. Neostigmine and pyridostigmine are quaternary cholinesterase inhibitors that act peripherally (no BBB crossing), used to reverse curare-like overdose and to treat myasthenia gravis.",
 quote:"Uses: Treatment of myasthenia gravis & to reverse curare-like overdose",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 33, 39; transcript 10/1"},

{id:"L08-033", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"recall",
 concept:"alzheimers-ache-inhibitors", tags:["druglist"], source:"both",
 stem:"Which statement about donepezil, rivastigmine and galantamine is CORRECT?",
 options:[
  {t:"They are irreversible organophosphates", correct:false, why:"They are reversible with a longer duration of action."},
  {t:"They reverse the course of Alzheimer's disease", correct:false, why:"They do not reverse the course of the disease."},
  {t:"They are lipophilic and cross the BBB", correct:true, why:"They are lipophilic, cross the blood–brain barrier (BBB), have high affinity for AChE and treat early symptoms of Alzheimer's disease."},
  {t:"They are quaternary amines", correct:false, why:"Quaternary amines (neostigmine, pyridostigmine) do not cross the BBB."},
  {t:"They block nicotinic receptors in the brain", correct:false, why:"They block the enzyme and raise acetylcholine."}],
 teach:"Donepezil (Aricept), rivastigmine (Exelon) and galantamine (Razadyne) are reversible acetylcholinesterase (AChE) inhibitors with longer duration of action and high affinity for AChE. They are lipophilic and cross the BBB. They treat early symptoms of Alzheimer's disease and slow the progression of cognitive, functional and behavioral deficits, but do not reverse the course of the disease.",
 quote:"Alzheimer's Disease (AD) & Dementia: Lipophilic (Cross the BBB) … Treat early symptoms of AD; Does not reverse the course of the disease; Slow the progression",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 40; transcript 10/1"},

{id:"L08-034", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"recall",
 concept:"ache-inhibitor-adrs", tags:[], source:"both",
 stem:"Which adverse drug reactions (ADRs) are expected from reversible cholinesterase inhibitors?",
 options:[
  {t:"Anti-DUMBBELSS: dry mouth, urinary retention", correct:false, why:"Anti-DUMBBELSS comes from blocking muscarinic receptors (atropine), not from raising acetylcholine."},
  {t:"DUMBBELSS, insomnia, dizziness and falling", correct:true, why:"Excess acetylcholine at synapses gives DUMBBELSS; GI and CNS effects (insomnia and agitation, dizziness, falling) are each over 10%."},
  {t:"Hyperkalemia and myalgia", correct:false, why:"Hyperkalemia and myalgia are succinylcholine ADRs."},
  {t:"Histamine release and hypotension", correct:false, why:"These are curare-like (atracurium) ADRs."}],
 teach:"Cholinesterase inhibitor ADRs are symptoms of excess acetylcholine at synapses: DUMBBELSS (diarrhea, urination, miosis, bradycardia, bronchial constriction, emesis, lacrimation, salivation, stimulation). GI effects and CNS effects (insomnia and agitation, dizziness leading to falling) each occur in more than 10% of patients. GI = gastrointestinal; CNS = central nervous system.",
 quote:"Symptoms due to excess of Ach at synapses: DUMBBELSS; GI (>10%); CNS (>10%): Insomnia & agitation, Dizziness, Falling",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 41; transcript 10/1"},

{id:"L08-035", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"op", skill:"tell",
 concept:"organophosphate-irreversible", tags:[], source:"slide",
 stem:"What separates organophosphates from neostigmine as acetylcholinesterase inhibitors?",
 options:[
  {t:"Organophosphates bind covalently (irreversible)", correct:true, why:"Organophosphates bind the enzyme covalently; the bond is very stable and slow, so the inhibition is irreversible."},
  {t:"Organophosphates bind the nicotinic receptor directly", correct:false, why:"Organophosphates act on the enzyme, not the receptor."},
  {t:"Organophosphates are poorly absorbed through skin", correct:false, why:"They are well absorbed from skin, lung, gut and conjunctiva."},
  {t:"Organophosphates have a short duration of action", correct:false, why:"A short, readily reversible action describes edrophonium."},
  {t:"Neostigmine is the irreversible one", correct:false, why:"Neostigmine is a reversible inhibitor."}],
 teach:"Organophosphates form a covalent bond with acetylcholinesterase that is very stable and slow, so they are irreversible; they irreversibly phosphorylate cholinesterases. They are used as insecticides (malathion, metabolized in vertebrates; parathion) and as nerve gases (soman, sarin, tabun), and are well absorbed from skin, lung, gut and conjunctiva. Neostigmine, physostigmine, pyridostigmine and edrophonium are reversible.",
 quote:"Forms a covalent bond with the enzyme that is very stable and slow (Irreversible); Used as insecticides; Well absorbed from skin, lung, gut & conjunctiva",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 42–43"},

{id:"L08-036", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"op", skill:"apply", multi:true,
 concept:"organophosphate-toxicity", tags:[], source:"slide",
 stem:"A farm worker is exposed to parathion. Which toxic effects are expected? Select all that apply.",
 options:[
  {t:"Tachycardia and hypertension", correct:true, why:"Stimulation of SNS ganglia gives tachycardia and hypertension."},
  {t:"Muscle cramps, weakness, respiratory paralysis", correct:true, why:"Stimulation of the neuromuscular junction (NMJ) gives cramps, weakness and respiratory paralysis."},
  {t:"Confusion and seizures", correct:true, why:"Stimulation of the CNS gives depression, agitation, confusion and seizures."},
  {t:"Histamine release with bronchial spasm", correct:false, why:"Histamine release is a curare-like (atracurium) ADR."},
  {t:"Blocked acetylcholine release", correct:false, why:"Blocking release is botulinum toxin; organophosphates raise acetylcholine."}],
 teach:"Organophosphates irreversibly phosphorylate cholinesterases, so acetylcholine accumulates everywhere it is released. Toxicity: stimulation of SNS ganglia (tachycardia, hypertension), stimulation of the NMJ (muscle cramps and weakness, respiratory paralysis) and stimulation of the CNS (depression, agitation, confusion, seizures). SNS = sympathetic nervous system; CNS = central nervous system.",
 quote:"Stimulation of SNS ganglia: Tachycardia, hypertension, etc… Stimulation of NMJ: Muscle cramps & weakness, respiratory paralysis, etc… Stimulation of CNS: Depression, agitation, confusion & seizures",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Cholinergic Poisoning (p. 9–10 of 14)", t:"Both the nicotinic and the muscarinic effects of cholinesterase inhibitors can be life-threatening. There is no effective way to directly reverse the nicotinic effects, because nicotinic agonists and antagonists both block transmission."}],
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 43"},

{id:"L08-037", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"op", skill:"apply",
 concept:"organophosphate-antidote", tags:[], source:"slide",
 stem:"Which pair of drugs treats poisoning with an organophosphate acetylcholinesterase inhibitor such as sarin?",
 options:[
  {t:"Atropine and pralidoxime", correct:true, why:"Atropine (M1, M2, M3 antagonist) reduces acetylcholine effects at muscarinic sites; pralidoxime reactivates the phosphorylated enzyme."},
  {t:"Neostigmine and physostigmine", correct:false, why:"These are cholinesterase inhibitors; they would add to the acetylcholine excess."},
  {t:"Succinylcholine and dantrolene", correct:false, why:"Succinylcholine is a depolarizing blocker; dantrolene treats malignant hyperthermia."},
  {t:"Varenicline and donepezil", correct:false, why:"Neither reverses organophosphate poisoning."},
  {t:"Botulinum toxin and rocuronium", correct:false, why:"These cause muscle relaxation; they are not the antidotes listed."}],
 teach:"Treatment of organophosphate poisoning has two parts. The anti-muscarinic atropine (M1, M2 and M3 antagonist; anti-DUMBBELSS) reduces the effects of acetylcholine at muscarinic sites. The cholinesterase reactivator pralidoxime (2-PAM) dephosphorylates the enzyme, splitting off the oxime-phosphonate and leaving the regenerated enzyme.",
 quote:"ANTI-MUSCARINIC - atropine - reduces the effects of ACH at muscarinic sites; CHOLINESTERASE REACTIVATOR - pralidoxime (2-PAM)",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Cholinergic Poisoning — Antimuscarinic therapy; Cholinesterase regenerator compounds (p. 10 of 14)", t:"A tertiary amine, preferably atropine, is used to treat both central and peripheral muscarinic effects of organophosphates, and large repeated doses may be needed. Oximes such as pralidoxime have high affinity for the phosphorus atom and regenerate active enzyme if the complex has not aged; pralidoxime works best at skeletal neuromuscular junctions and does not enter the CNS because it is a quaternary compound."}],
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 44"},

{id:"L08-038", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"op", skill:"recall",
 concept:"echothiophate-glaucoma", tags:["druglist"], source:"slide",
 stem:"Echothiophate lowers intraocular pressure (IOP) in glaucoma. What is its mechanism?",
 options:[
  {t:"AChE inhibitor; ↑ ACh at ciliary M3", correct:true, why:"Echothiophate inhibits acetylcholinesterase (AChE), raising acetylcholine (ACh) and M3 activation in the ciliary muscle, which increases aqueous humor outflow."},
  {t:"M3 antagonist in the ciliary muscle", correct:false, why:"Echothiophate increases M3 activation; it does not block it."},
  {t:"Reversible Nm agonist in the eye", correct:false, why:"Echothiophate acts on the enzyme, and the eye effect is through M3."},
  {t:"Blocks acetylcholine release in the eye", correct:false, why:"Blocking release is botulinum toxin."},
  {t:"α4/β2 partial agonist", correct:false, why:"That is varenicline."}],
 teach:"Echothiophate (Phospholine) is an organophosphate inhibitor of acetylcholinesterase that raises acetylcholine. More M3 activation in the ciliary muscle lowers IOP by increasing aqueous humor outflow. It is quaternary and positively charged, so it is poorly absorbed. ADRs: miosis and blurred vision, lacrimation, stinging and redness of the eyes.",
 quote:"MOA: Organophosphate inhibitor of the acetylcholinesterase enzyme & ↑ Ach levels; ↑ M3 receptor activation in ciliary muscle; Lower intraocular pressure (IOP) by increasing aqueous humor outflow",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 45"},

{id:"L08-039", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"botox", skill:"recall",
 concept:"botulinum-moa", tags:["druglist"], source:"slide",
 stem:"How does botulinum toxin cause muscle relaxation?",
 options:[
  {t:"It cleaves SNARE proteins", correct:true, why:"Its active fragments are endopeptidases that cleave SNARE proteins, so acetylcholine (ACh) cannot be released."},
  {t:"It competitively blocks the Nm receptor", correct:false, why:"Competitive Nm block is the curare-like mechanism."},
  {t:"It keeps the motor end plate depolarized", correct:false, why:"Prolonged depolarization is succinylcholine phase I."},
  {t:"It inhibits acetylcholinesterase", correct:false, why:"Enzyme inhibition raises ACh; botulinum toxin lowers ACh release."},
  {t:"It blocks the ryanodine receptor", correct:false, why:"That is dantrolene."}],
 teach:"Botulinum toxin prevents acetylcholine release from the presynaptic terminal by interfering with the machinery of transmitter release. Its active fragments are endopeptidases whose substrates are SNARE (SNAP receptor) proteins; cleaving specific sites on SNARE proteins stops docking, priming and exocytosis. Less acetylcholine release gives muscle relaxation; uses are cosmetic (crow's feet) and control of excessive drooling.",
 quote:"The active fragments of botulinum toxins are endopeptidases; the SNARE proteins are their substrates. The botulinum toxin cleaves specific sites on SNARE proteins. By ↓ Ach release => Muscle relaxation",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 46–50"},

{id:"L08-040", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"botox", skill:"tell",
 concept:"presynaptic-vs-postsynaptic-relaxants", tags:[], source:"slide",
 stem:"Which agent relaxes skeletal muscle by acting on the presynaptic terminal rather than on the postsynaptic receptor?",
 options:[
  {t:"Vecuronium", correct:false, why:"Vecuronium is a competitive antagonist at the postsynaptic muscle nicotinic receptor."},
  {t:"Succinylcholine", correct:false, why:"Succinylcholine is an agonist at the postsynaptic muscle nicotinic receptor."},
  {t:"Botulinum toxin", correct:true, why:"Botulinum toxin acts in the presynaptic terminal, cleaving SNARE proteins so acetylcholine cannot be released."},
  {t:"Tubocurarine", correct:false, why:"Tubocurarine (curare) is the prototype postsynaptic competitive antagonist."}],
 teach:"Three ways to relax or paralyze skeletal muscle appear here. Botulinum toxin acts presynaptically and prevents acetylcholine release. Succinylcholine acts postsynaptically as a depolarizing agonist. Curare-like drugs (tubocurarine, vecuronium, rocuronium and others) act postsynaptically as competitive antagonists.",
 quote:"Prevent Ach release from presynaptic terminal",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 19, 46"}
);
