TOPICS.push({id:"L09", name:"Day 9: muscarinic receptors, agonists and antagonists", prof:"Gottlieb", lecture:"L09",
  cite:"Day 9 (10/6) — PCOL-Cholinergic-26s.pdf",
  subs:[
    {id:"overview", name:"Cholinergic system overview", cite:"slides 1–4"},
    {id:"loc", name:"M1, M2, M3: where they are", cite:"slides 5, 10"},
    {id:"transd", name:"Gq vs Gi signal transduction", cite:"slides 6–9"},
    {id:"agon", name:"Muscarinic agonists and their uses", cite:"slides 11–12, 14"},
    {id:"dumb", name:"DUMBBELSS and agonist ADRs", cite:"slides 13–15"},
    {id:"atrop", name:"Atropine, scopolamine and organophosphate poisoning", cite:"slides 17–24"},
    {id:"uses", name:"Antimuscarinic uses: Parkinson, eye, lungs", cite:"slides 25–28"},
    {id:"bladder", name:"Overactive bladder antimuscarinics and anti-DUMBBELSS", cite:"slides 29–32"}
  ]});
QUESTIONS.push(
{id:"L09-001", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"overview", skill:"recall",
 concept:"lungs-pns-only-m3", tags:[], source:"slide",
 stem:"Which autonomic division and receptor control bronchial smooth muscle?",
 options:[
  {t:"Parasympathetic only, M3", correct:true, why:"The lungs are marked PNS only, and the receptor drawn on the lungs and on bronchial smooth muscle is M3."},
  {t:"Sympathetic only, α1", correct:false, why:"α1 appears on the eye in the same diagram, not on the lungs; the lungs are marked PNS only."},
  {t:"Both divisions, M2", correct:false, why:"M2 is the heart receptor, and the lungs receive direct input from the PNS only."},
  {t:"Parasympathetic only, Nn", correct:false, why:"Nicotinic receptors sit at the ganglia; the receptor on bronchial smooth muscle is muscarinic M3."},
  {t:"Sympathetic only, M1", correct:false, why:"M1 is drawn on the brain, and the lungs are PNS only."}],
 teach:"The lungs receive direct autonomic input from the parasympathetic nervous system (PNS) only, and the receptor on bronchial smooth muscle is M3. This is the rationale for muscarinic antagonists in asthma and chronic obstructive pulmonary disease (COPD): blocking M3 removes the PNS bronchoconstrictor signal.",
 quote:"Lungs: PNS Only",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Organ System Effects — 4. Respiratory system", t:"Both smooth muscle and secretory glands of the airway receive vagal innervation and contain muscarinic receptors. Even in normal individuals, atropine can cause some bronchodilation and reduce secretion, and the effect is more significant in patients with airway disease."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 3; slide 27"},

{id:"L09-002", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"overview", skill:"tell",
 concept:"muscarinic-vs-nicotinic-sites", tags:[], source:"slide",
 stem:"Which site carries nicotinic, not muscarinic, cholinergic receptors?",
 options:[
  {t:"Autonomic ganglion cells", correct:true, why:"Nicotinic receptors are listed at the neuromuscular junction and on autonomic ganglion cells."},
  {t:"Heart", correct:false, why:"The heart is listed under muscarinic receptors (heart and smooth muscle)."},
  {t:"Smooth muscle of the GI tract", correct:false, why:"Smooth muscle is listed under muscarinic receptors."},
  {t:"Glands", correct:false, why:"Glands are grouped with endothelium under muscarinic receptors."},
  {t:"Endothelium", correct:false, why:"Endothelium is grouped with glands under muscarinic receptors."}],
 teach:"Cholinergic receptors split into two families. Muscarinic receptors are on nerve, heart and smooth muscle, and glands and endothelium. Nicotinic receptors are at the neuromuscular junction and on autonomic ganglion cells.",
 quote:"Muscarinic: Nerve / Heart and Smooth Muscle / Glands and Endothelium. Nicotinic: Neuromuscular Junction / Autonomic Ganglion cells",
 cite:"PCOL-Cholinergic-26s.pdf slide 4"},

{id:"L09-003", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"overview", skill:"recall",
 concept:"direct-vs-indirect-acting", tags:[], source:"slide",
 stem:"How do indirect-acting cholinergic receptor stimulants activate muscarinic and nicotinic receptors?",
 options:[
  {t:"By raising acetylcholine levels", correct:true, why:"Indirect-acting drugs work through an increase in acetylcholine (ACh), which then activates both receptor families."},
  {t:"By binding the receptor directly", correct:false, why:"Binding the receptor is what direct-acting drugs (alkaloids and choline esters) do."},
  {t:"By blocking the M2 receptor", correct:false, why:"Blocking a receptor is antagonism, not stimulation."},
  {t:"By acting as choline esters", correct:false, why:"Choline esters are a group of direct-acting drugs, not indirect-acting ones."}],
 teach:"Receptor stimulants are direct-acting or indirect-acting. Direct-acting drugs are alkaloids or choline esters and act on the receptors themselves. Indirect-acting drugs, reversible or irreversible, raise acetylcholine (ACh), and the extra ACh activates both muscarinic and nicotinic receptors.",
 quote:"Direct-acting drugs: Alkaloids / Choline esters. Indirect-acting drugs: Reversible / Irreversible → ↑ Ach",
 cite:"PCOL-Cholinergic-26s.pdf slide 4"},

{id:"L09-004", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"loc", skill:"tell",
 concept:"m-subtype-locations", tags:[], source:"slide",
 stem:"Which pairing of muscarinic receptor subtype and location is CORRECT?",
 options:[
  {t:"M2: atrioventricular and sinoatrial nodes", correct:true, why:"M2 is the heart receptor, at the atrioventricular (AV) and sinoatrial (SA) nodes."},
  {t:"M1: bladder smooth muscle", correct:false, why:"Bladder smooth muscle is listed under M3 (everywhere else)."},
  {t:"M3: atrioventricular node", correct:false, why:"The AV node is an M2 site, not M3."},
  {t:"M2: salivary glands", correct:false, why:"Glands carry M3, not M2."},
  {t:"M3: brain neurons (Alzheimer disease target)", correct:false, why:"The brain receptor with a role in Alzheimer disease treatment is M1."}],
 teach:"M1 is drawn on the brain and has an important role in the treatment of Alzheimer disease. M2 is on the heart, at the atrioventricular (AV) and sinoatrial (SA) nodes. M3 is everywhere else: smooth muscle of the gut and bladder, airway, eyes, and glands.",
 quote:"M1: Important role in the treatment of Alzheimer disease / M2: AV & SA node / M3: Everywhere Else - Smooth muscle - GI, bladder, - Airway & eyes",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Table 8–1 Muscarinic receptor subgroups", t:"M1 receptors are on nerves (central neurons, autonomic postganglionic cell bodies and presynaptic sites). M2 receptors are in the heart, nerves and smooth muscle. M3 receptors are most common on glands, smooth muscle and endothelium."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 10; slide 5"},

{id:"L09-005", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"loc", skill:"recall",
 concept:"m3-endothelium-non-innervated", tags:[], source:"slide",
 stem:"Which muscarinic receptor subtype is on the endothelium, and is that site innervated?",
 options:[
  {t:"M3; not innervated", correct:true, why:"M3 is listed on smooth muscle (gut), glands, eyes and endothelia, with the endothelia marked non-innervated."},
  {t:"M2; innervated", correct:false, why:"M2 is listed for heart and smooth muscle (GI sphincter), not endothelium."},
  {t:"M1; innervated", correct:false, why:"M1 is listed for the enteric nervous system and neuron ganglia."},
  {t:"M3; innervated by PNS", correct:false, why:"The receptor is right, but the endothelial M3 site is marked non-innervated."}],
 teach:"M3 receptors are on gut smooth muscle, glands, eyes and the endothelium. The endothelial M3 receptors are non-innervated: no parasympathetic nerve ends on them. When a muscarinic agonist reaches them, M3 mediates the release of nitric oxide and vasodilation.",
 quote:"Muscarinic Receptor Type 3 (M3) Smooth Muscle (gut), Glands, eyes and Endothelia (non-innervated)",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Organ System Effects — 3. Cardiovascular system", t:"Most blood vessels receive no direct parasympathetic innervation, but almost all vessels contain endothelial muscarinic receptors that mediate vasodilation. These receptors are readily blocked by antimuscarinic drugs."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 5"},

{id:"L09-006", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"loc", skill:"recall",
 concept:"m1-location", tags:[], source:"slide",
 stem:"Which of the following is CORRECT about the M1 muscarinic receptor?",
 options:[
  {t:"It has a role in Alzheimer disease treatment", correct:true, why:"M1, drawn on the brain, is stated to have an important role in the treatment of Alzheimer disease."},
  {t:"It is the receptor at the SA node", correct:false, why:"The sinoatrial (SA) node carries M2."},
  {t:"It couples to the Gi protein", correct:false, why:"M1 couples to Gq; Gi belongs to M2 (and M4)."},
  {t:"It mediates bronchial smooth muscle constriction", correct:false, why:"Bronchial constriction is an M3 effect."}],
 teach:"M1 is listed for the enteric nervous system and neuron ganglia and is drawn on the brain, where it has an important role in Alzheimer disease treatment. It couples to Gq, like M3. In the central nervous system (CNS), M1 activation by pilocarpine gives emesis, and M1 blockade contributes to CNS adverse effects of antimuscarinics.",
 quote:"Muscarinic Receptor Type 1 (M1) Enteric Nervous System and Neuron Ganglia ... M1: Important role in the treatment of Alzheimer disease",
 cite:"PCOL-Cholinergic-26s.pdf slide 5; slide 10"},

{id:"L09-007", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"recall",
 concept:"gq-subtypes", tags:[], multi:true, source:"slide",
 stem:"Which muscarinic receptor subtypes couple to the Gq protein? Select all that apply.",
 options:[
  {t:"M1", correct:true, why:"M1 is Gq: activation of phospholipase C and a rise in IP3."},
  {t:"M2", correct:false, why:"M2 is Gi: inhibition of adenylyl cyclase."},
  {t:"M3", correct:true, why:"M3 is Gq, the same as M1."},
  {t:"M4", correct:false, why:"M4 (CNS) is listed with M2 on the Gi row."},
  {t:"M5", correct:true, why:"M5 (CNS) is listed with M1 on the Gq row."}],
 teach:"M1 and M5 (CNS) and M3 couple to Gq, which activates phospholipase C (PLC) and raises inositol trisphosphate (IP3) and Ca2+. M2 and M4 (CNS) couple to Gi, which inhibits adenylyl cyclase (AC) and lowers cyclic AMP (cAMP).",
 quote:"M1, M5 (CNS): Gq, Activation of PLC, IP3 ↑. M2, M4 (CNS): Gi, Inhibition of AC, Decrease in cAMP. M3: Gq, Activation of PLC, IP3 ↑",
 cite:"PCOL-Cholinergic-26s.pdf slide 9"},

{id:"L09-008", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"recall",
 concept:"m3-gq-cascade", tags:[], source:"slide",
 stem:"Which sequence describes M3 receptor signaling?",
 options:[
  {t:"Gq → PLC → IP3 → Ca2+", correct:true, why:"M3 activates Gq, which activates phospholipase C (PLC); PLC makes IP3, which releases Ca2+."},
  {t:"Gi → AC → ↓cAMP", correct:false, why:"That is the M2 (Gi) pathway: inhibition of adenylyl cyclase (AC) and less cAMP."},
  {t:"Gs → AC → ↑cAMP", correct:false, why:"Gs raising cAMP is drawn for the β receptor activated by norepinephrine, not for M3."},
  {t:"Gq → AC → IP3 → K+ efflux", correct:false, why:"Gq acts through PLC, not AC, and the K+ channel belongs to the M2 pathway."}],
 teach:"M3 (and M1) couple to Gαq. Acetylcholine binding makes the α subunit release GDP and bind GTP; αq activates phospholipase C (PLC), which turns PIP2 into inositol trisphosphate (IP3). IP3 acts on the IP3 receptor of the endoplasmic reticulum (ER) to release Ca2+, and the rise in Ca2+ drives the response, for example smooth muscle contraction.",
 quote:"M3 => Gq => PLC => IP3 => Ca2+",
 cite:"PCOL-Cholinergic-26s.pdf slide 6; slide 15"},

{id:"L09-009", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"apply",
 concept:"m2-gi-heart", tags:[], multi:true, source:"slide",
 stem:"Acetylcholine binds M2 receptors on the heart. Which effects follow? Select all that apply.",
 options:[
  {t:"Inhibition of adenylyl cyclase", correct:true, why:"αi inhibits adenylyl cyclase (AC), labeled #1 in the M2 figure."},
  {t:"Decrease in cAMP", correct:true, why:"With AC inhibited, less ATP is converted to cyclic AMP (cAMP)."},
  {t:"Membrane hyperpolarization via K+", correct:true, why:"The βγ subunits open a K+ channel (#2), and K+ leaving hyperpolarizes the membrane."},
  {t:"Rise in IP3 and Ca2+", correct:false, why:"IP3 and Ca2+ belong to the Gq pathway of M1 and M3."},
  {t:"Increase in heart rate", correct:false, why:"M2 lowers heart rate and contractility; NE on the β receptor (Gαs) raises them."}],
 teach:"M2 couples to Gαi. Action #1: αi inhibits adenylyl cyclase (AC), so cyclic AMP (cAMP) falls. Action #2: the βγ subunits open a K+ channel, and K+ leaving hyperpolarizes the membrane. Both lower heart rate and contractility, opposing norepinephrine (NE) acting through a Gαs-coupled β receptor that raises cAMP.",
 quote:"M2 Gαi Proteins ... #1 AC ... ATP cAMP ... #2 K+ ... Hyperpolarization of the membrane potential ... ↓ HR & Contractility",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Table 8–1 Muscarinic receptor subgroups", t:"The dominant effector system of M2 (and M4) receptors is a decrease in cAMP and an increase in K+ channel current. M1, M3 and M5 receptors act through increases in IP3 and diacylglycerol (DAG)."}],
 cite:"PCOL-Cholinergic-26s.pdf slides 7–8"},

{id:"L09-010", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"tell",
 concept:"m2-vs-beta-heart", tags:[], source:"slide",
 stem:"In a cardiac cell, acetylcholine acts on M2 and norepinephrine acts on a β receptor. Which statement is CORRECT?",
 options:[
  {t:"M2 uses Gαi; β uses Gαs", correct:true, why:"M2 couples to Gαi and lowers cAMP; the β receptor couples to Gαs and raises it, so the two oppose each other."},
  {t:"Both use Gαq", correct:false, why:"Gαq belongs to M1 and M3, not to M2 or the β receptor."},
  {t:"M2 uses Gαs; β uses Gαi", correct:false, why:"This reverses the two: M2 is Gαi, the β receptor is Gαs."},
  {t:"Both raise heart rate", correct:false, why:"M2 lowers heart rate and contractility; the β receptor raises them."}],
 teach:"Adenylyl cyclase (AC) in the heart is pushed in two directions. Norepinephrine (NE) on a β receptor activates Gαs, raising cyclic AMP (cAMP) and heart rate and contractility. Acetylcholine (ACh) on M2 activates Gαi, inhibiting AC and lowering cAMP, heart rate and contractility.",
 quote:"M2 ... Gαi Proteins ... NE β2 Gαs ... HR & Contractility",
 note:"The M2 figure labels the norepinephrine receptor on the heart cell 'β2' (Gαs); the Exam 1 drug list treats metoprolol, a β1 antagonist, as the cardiac β drug. The question avoids the subtype.",
 cite:"PCOL-Cholinergic-26s.pdf slides 7–8"},

{id:"L09-011", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"transd", skill:"recall",
 concept:"m4-gi", tags:[], source:"slide",
 stem:"The M4 muscarinic receptor (CNS) shares its G protein and second messenger change with which subtype?",
 options:[
  {t:"M2: Gi, decrease in cAMP", correct:true, why:"M4 (CNS) is listed on the M2 row: Gi, inhibition of AC, decrease in cAMP."},
  {t:"M1: Gq, increase in IP3", correct:false, why:"M5, not M4, shares the M1 row."},
  {t:"M3: Gq, increase in IP3", correct:false, why:"M3 is Gq; M4 is Gi."},
  {t:"M2: Gs, increase in cAMP", correct:false, why:"M2 is Gi and lowers cAMP; Gs is the β receptor pathway."}],
 teach:"The receptor table pairs M1 with M5 (CNS) and M2 with M4 (CNS). M1, M5 and M3 are Gq (activation of phospholipase C, IP3 up, Ca2+ up, a stimulatory effect). M2 and M4 are Gi (inhibition of adenylyl cyclase, cAMP down, a lowered signal).",
 quote:"M2 M4 (CNS) Gi Inhibition of AC Decrease in cAMP ↓Signal",
 cite:"PCOL-Cholinergic-26s.pdf slide 9"},

{id:"L09-012", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"recall",
 concept:"muscarinic-agonist-moa", tags:[], source:"slide",
 stem:"Which of the following describes the mechanism of action of acetylcholine, methacholine, carbachol, bethanechol and pilocarpine?",
 options:[
  {t:"Non-selective, reversible M1–M3 agonists", correct:true, why:"The muscarinic agonists are non-selective (M1, M2 and M3) and reversible, with similar effects, adverse reactions and interactions."},
  {t:"Selective, reversible M3 agonists", correct:false, why:"They are non-selective across M1, M2 and M3."},
  {t:"Non-selective, irreversible agonists", correct:false, why:"They are reversible."},
  {t:"Agonists at both nicotinic and muscarinic receptors", correct:false, why:"Pilocarpine is stated to have no effect on nicotinic receptors."}],
 teach:"The muscarinic agonists (acetylcholine, methacholine, carbachol, bethanechol, pilocarpine and cevimeline) are non-selective for M1, M2 and M3 and bind reversibly. Because they hit every subtype, they share similar effects, adverse drug reactions (ADRs) and drug–drug interactions (DDIs); they differ mainly in their uses.",
 quote:"Non-selective (M1, M2, & M3s) Reversible) Similar effect ADR & DDIs",
 cite:"PCOL-Cholinergic-26s.pdf slide 11; slide 12"},

{id:"L09-013", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"tell",
 concept:"agonist-uses", tags:[], source:"slide",
 stem:"Which pairing of muscarinic agonist and use is CORRECT?",
 options:[
  {t:"Methacholine: bronchial hyperactivity diagnosis", correct:true, why:"Methacholine (Provocholine) is used to diagnose bronchial airway hyperactivity."},
  {t:"Bethanechol: glaucoma", correct:false, why:"Bethanechol (Urecholine) is for urinary retention and emptying; carbachol is the glaucoma drug."},
  {t:"Carbachol: urinary retention", correct:false, why:"Carbachol (Miostat) is for glaucoma; bethanechol is for urinary retention."},
  {t:"Acetylcholine: xerostomia and Sjögren's syndrome", correct:false, why:"Acetylcholine (Miochol-E) is used topically during eye surgery; pilocarpine and cevimeline treat dry mouth."},
  {t:"Cevimeline: eye surgery", correct:false, why:"Cevimeline is grouped with pilocarpine for glaucoma, xerostomia and Sjögren's syndrome."}],
 teach:"Acetylcholine (Miochol-E): topical use during ophthalmologic surgery. Methacholine (Provocholine): diagnosis of bronchial airway hyperactivity. Carbachol (Miostat): glaucoma. Bethanechol (Urecholine): urinary retention and emptying. Pilocarpine and cevimeline: glaucoma, xerostomia and Sjögren's syndrome.",
 quote:"Methacholine (Provocholine) Diagnosis of bronchial airway hyperactivity ... Bethanechol (Urecholine) Urinary retention and emptying",
 cite:"PCOL-Cholinergic-26s.pdf slide 11"},

{id:"L09-014", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"apply",
 concept:"bethanechol-urinary-retention", tags:[], source:"slide",
 stem:"A patient cannot empty the bladder after surgery. Which muscarinic agonist is used for urinary retention and emptying?",
 options:[
  {t:"Bethanechol", correct:true, why:"Bethanechol (Urecholine) is the agonist listed for urinary retention and emptying."},
  {t:"Methacholine", correct:false, why:"Methacholine is used to diagnose bronchial airway hyperactivity."},
  {t:"Carbachol", correct:false, why:"Carbachol is listed for glaucoma."},
  {t:"Oxybutynin", correct:false, why:"Oxybutynin is a muscarinic antagonist for overactive bladder; it would worsen retention."},
  {t:"Tropicamide", correct:false, why:"Tropicamide is a muscarinic antagonist used to dilate the pupil."}],
 teach:"Bladder emptying (micturition) is a parasympathetic (PNS), M3 effect, so a muscarinic agonist promotes it. Bethanechol (Urecholine) is the agonist used for urinary retention and emptying. The antagonists for overactive bladder (oxybutynin and others) do the opposite.",
 quote:"Bethanechol (Urecholine) Urinary retention and emptying",
 cite:"PCOL-Cholinergic-26s.pdf slide 11; slide 13"},

{id:"L09-015", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"recall",
 concept:"pilocarpine-cevimeline-uses", tags:[], multi:true, source:"slide",
 stem:"Pilocarpine and cevimeline are used for which of the following? Select all that apply.",
 options:[
  {t:"Glaucoma", correct:true, why:"Glaucoma is listed for pilocarpine (Isopto Carpine) and cevimeline."},
  {t:"Xerostomia", correct:true, why:"Xerostomia (dry mouth) is listed; salivation is an M3 effect of these agonists."},
  {t:"Sjögren's syndrome", correct:true, why:"Sjögren's syndrome is listed with glaucoma and xerostomia."},
  {t:"Motion sickness", correct:false, why:"Motion sickness is treated with scopolamine, a muscarinic antagonist."},
  {t:"Overactive bladder", correct:false, why:"Overactive bladder is treated with antagonists such as oxybutynin; an agonist would increase bladder contraction."}],
 teach:"Pilocarpine (Isopto Carpine and Salagen) and cevimeline (Evoxac) are listed for glaucoma, xerostomia and Sjögren's syndrome. Pilocarpine is used topically for glaucoma and to treat dry mouth, because M3 activation on the salivary gland (through Gq) causes salivation.",
 quote:"Pilocarpine (Isopto Carpine & Salagen) & Cevimeline (Evoxac) Glaucoma, Xerostomia & Sjögren's syndrome",
 cite:"PCOL-Cholinergic-26s.pdf slide 11; slide 14"},

{id:"L09-016", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"figure",
 concept:"ache-hydrolysis-agonists", tags:[], multi:true, source:"slide",
 stem:"A table rates hydrolysis by acetylcholinesterase (AChE) for four muscarinic agonists: acetylcholine +++, methacholine +, carbachol −, pilocarpine −. Which agonists are NOT hydrolyzed by AChE? Select all that apply.",
 options:[
  {t:"Carbachol", correct:true, why:"Carbachol is rated − for hydrolysis by AChE."},
  {t:"Pilocarpine", correct:true, why:"Pilocarpine is rated −; it is a non-ester and is not hydrolyzed."},
  {t:"Methacholine", correct:false, why:"Methacholine is rated +, so it is hydrolyzed, though less than acetylcholine."},
  {t:"Acetylcholine", correct:false, why:"Acetylcholine is rated +++, the most hydrolyzed of the four."}],
 teach:"Hydrolysis by acetylcholinesterase (AChE): acetylcholine +++, methacholine +, carbachol −, pilocarpine −. Pilocarpine is an alkaloid, a non-ester, and is not hydrolyzed. The agonists that resist AChE (carbachol, pilocarpine) carry the strongest ratings for gastrointestinal (GI), bladder and eye effects in the same table.",
 quote:"Hydrolysis by AchE: Ach +++, Methacholine +, Carbachol -, Pilocarpine -",
 cite:"PCOL-Cholinergic-26s.pdf slide 12; slide 14"},

{id:"L09-017", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"figure",
 concept:"agonist-table-cv", tags:[], source:"slide",
 stem:"A table rates the cardiovascular effect (decrease in heart rate) of four muscarinic agonists: acetylcholine ++, methacholine +++, carbachol +, pilocarpine +++. Which agonist has the weakest effect on heart rate?",
 options:[
  {t:"Carbachol", correct:true, why:"Carbachol is rated + for heart rate, the lowest of the four."},
  {t:"Methacholine", correct:false, why:"Methacholine is rated +++ for heart rate."},
  {t:"Pilocarpine", correct:false, why:"Pilocarpine is rated +++ for heart rate."},
  {t:"Acetylcholine", correct:false, why:"Acetylcholine is rated ++ for heart rate."}],
 teach:"The agonist table rates each drug for cardiovascular effect (↓ heart rate), GI effect (↑ tone and motility), bladder (↑ constriction) and eye (miosis). Carbachol is weak on the heart (+) but strong on the GI tract and bladder (+++). Methacholine and pilocarpine are the strongest on the heart (+++).",
 quote:"CV (↓ HR): Ach ++, Methacholine +++, Carbachol +, Pilocarpine +++",
 cite:"PCOL-Cholinergic-26s.pdf slide 12"},

{id:"L09-018", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"agon", skill:"recall",
 concept:"pilocarpine-alkaloid", tags:[], source:"slide",
 stem:"Which of the following is CORRECT about pilocarpine?",
 options:[
  {t:"It is an alkaloid not hydrolyzed by AChE", correct:true, why:"Pilocarpine is an alkaloid, a non-ester that is not hydrolyzed."},
  {t:"It is a choline ester", correct:false, why:"Pilocarpine is a non-ester alkaloid."},
  {t:"It also activates Nn and Nm nicotinic receptors", correct:false, why:"Pilocarpine has no effect on nicotinic receptors."},
  {t:"It is a selective M3 agonist", correct:false, why:"Pilocarpine is a non-selective muscarinic agonist."},
  {t:"It binds irreversibly", correct:false, why:"Pilocarpine is reversible."}],
 teach:"Pilocarpine is an alkaloid: a non-ester that is not hydrolyzed by acetylcholinesterase (AChE). It has no effect on nicotinic receptors. Its pharmacology is a non-selective, reversible muscarinic agonist, used topically to treat glaucoma and to treat dry mouth.",
 quote:"Pilocarpine (Alkaloids) Non-Ester and not hydrolyzed No effect on Nicotinic receptors Used topically to treat glaucoma and to treat dry mouth",
 cite:"PCOL-Cholinergic-26s.pdf slide 14"},

{id:"L09-019", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"agonist-organ-effects", tags:[], source:"slide",
 stem:"A muscarinic agonist is given systemically. Which effect is most likely?",
 options:[
  {t:"Increased peristalsis", correct:true, why:"In the GI tract the PNS is the predominant tone, and a muscarinic agonist increases peristalsis and secretion."},
  {t:"Mydriasis", correct:false, why:"An agonist causes miosis; mydriasis is an antagonist (anti-DUMBBELSS) effect."},
  {t:"Dry mouth", correct:false, why:"An agonist causes salivation; dry mouth comes from blocking M3."},
  {t:"Bronchial smooth muscle dilation", correct:false, why:"An agonist causes bronchial constriction through M3."},
  {t:"Tachycardia", correct:false, why:"An agonist causes bradycardia through M2."}],
 teach:"Muscarinic agonists reproduce parasympathetic nervous system (PNS) effects, summarized as DUMBBELSS: GI tract, increased peristalsis and secretion; urinary bladder, micturition; eye, miosis; heart, bradycardia; lungs, bronchial constriction; CNS, vomiting; glands, salivation and lacrimation. Vasodilation also occurs through nitric oxide.",
 quote:"GI tract PNS Increase peristalsis & Secretion ... Eye (Iris) PNS Miosis ... Heart PNS Bradycardia ... Lungs PNS Bronchial constriction",
 cite:"PCOL-Cholinergic-26s.pdf slide 13"},

{id:"L09-020", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"dumbbelss-select", tags:[], multi:true, source:"slide",
 stem:"Which effects are expected after a muscarinic agonist such as bethanechol? Select all that apply.",
 options:[
  {t:"Micturition", correct:true, why:"Urinary bladder: PNS tone; the agonist effect is micturition."},
  {t:"Miosis", correct:true, why:"Eye (iris): PNS tone; the agonist effect is miosis."},
  {t:"Bradycardia", correct:true, why:"Heart: PNS tone; the agonist effect is bradycardia."},
  {t:"Lacrimation", correct:true, why:"Glands: secretion, salivation and lacrimation."},
  {t:"Constipation", correct:false, why:"Constipation is an antagonist effect; the agonist increases peristalsis."},
  {t:"Bronchial dilation", correct:false, why:"The agonist constricts the bronchi through M3."}],
 teach:"Every muscarinic agonist is non-selective, so each can produce the full DUMBBELSS picture: increased GI peristalsis and secretion, micturition, miosis, bradycardia, bronchial constriction, vomiting, and salivation and lacrimation. Bethanechol is one of the agonists listed with similar effects and adverse reactions.",
 quote:"Urinary Bladder PNS Micturation / Eye (Iris) PNS Miosis / Heart PNS Bradycardia / Glands PNS Secretion (Salivation & lacrimation)",
 cite:"PCOL-Cholinergic-26s.pdf slide 13; slide 11"},

{id:"L09-021", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"pilocarpine-receptor-map", tags:[], source:"slide",
 stem:"A patient taking pilocarpine vomits. Which receptor and G protein most likely mediate this effect?",
 options:[
  {t:"M1 in the CNS, Gq", correct:true, why:"CNS = M1 = Gq = emesis."},
  {t:"M2 in the heart, Gi", correct:false, why:"M2 on the heart through Gi lowers heart rate; it does not cause emesis."},
  {t:"M3 on salivary gland, Gq", correct:false, why:"M3 on the salivary gland through Gq causes salivation."},
  {t:"M2 in the CNS, Gs", correct:false, why:"No muscarinic receptor is listed as Gs; emesis is M1 through Gq."}],
 teach:"Pilocarpine is a non-selective, reversible muscarinic agonist, so its effects follow receptor location: heart = M2 = Gi = ↓ heart rate; salivary gland = M3 = Gq = salivation; bronchial smooth muscle = M3 = Gq = bronchial constriction; central nervous system (CNS) = M1 = Gq = emesis.",
 quote:"Heart = M2 = Gi = ↓ HR / Salivary Gland = M3 = Gq = Salivation / Bronchial Smooth Muscle = M3 = Gq = Bronchial Constriction / CNS = M1 = Gq = Emesis",
 cite:"PCOL-Cholinergic-26s.pdf slide 14"},

{id:"L09-022", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"pilocarpine-heart-m2", tags:[], source:"slide",
 stem:"Pilocarpine is given for dry mouth. What does it most likely do to the heart, and through which receptor?",
 options:[
  {t:"Decreases heart rate through M2 (Gi)", correct:true, why:"Heart = M2 = Gi = ↓ heart rate; pilocarpine is non-selective, so it reaches M2 as well as M3."},
  {t:"Increases heart rate through M2 (Gi)", correct:false, why:"Activating M2 lowers heart rate; raising it is the antagonist (atropine) effect."},
  {t:"Decreases heart rate through M3 (Gq)", correct:false, why:"The heart receptor is M2 (Gi), not M3."},
  {t:"No effect; it is M3-selective", correct:false, why:"Pilocarpine is non-selective, and its heart effect is rated +++."}],
 teach:"Pilocarpine is used for its M3 effect on the salivary gland, but it is a non-selective muscarinic agonist, so it also activates M2 on the heart. M2 couples to Gi and lowers heart rate. In the agonist table, pilocarpine's cardiovascular (↓ heart rate) rating is +++.",
 quote:"Heart = M2 = Gi = ↓ HR",
 cite:"PCOL-Cholinergic-26s.pdf slide 14; slide 12"},

{id:"L09-023", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"apply",
 concept:"agonist-hypotension-no", tags:[], source:"slide",
 stem:"A muscarinic agonist lowers blood pressure. Which mechanism is responsible?",
 options:[
  {t:"M3-mediated release of nitric oxide", correct:true, why:"Hypotension is listed as an adverse reaction from M3-mediated release of nitric oxide (NO)."},
  {t:"M2 activation in vascular smooth muscle", correct:false, why:"The vascular effect is assigned to M3 and NO, not to M2."},
  {t:"Parasympathetic nerves on arteries", correct:false, why:"The endothelial M3 receptors are non-innervated."},
  {t:"Blockade of α1 receptors", correct:false, why:"A muscarinic agonist does not act on α1 receptors."}],
 teach:"Endothelial M3 receptors are non-innervated, but a circulating muscarinic agonist reaches them. M3 activation releases nitric oxide (NO), which produces vasodilation and hypotension. Hypotension is listed with miosis-related difficulty in visual accommodation and bronchial constriction as agonist adverse drug reactions (ADRs).",
 quote:"Hypotension M3 mediated release of Nitric Oxide ... Vasodilation (via Nitric Oxide)",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Organ System Effects — 3. Cardiovascular system", t:"Almost all vessels contain endothelial muscarinic receptors that mediate vasodilation, and these receptors are readily blocked by antimuscarinic drugs. The cardiovascular effects of administered direct-acting muscarinic agonists are easily prevented by atropine."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 15; slide 13; slide 5"},

{id:"L09-024", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"dumb", skill:"recall",
 concept:"agonist-adr-accommodation", tags:[], source:"slide",
 stem:"A patient using a muscarinic agonist reports difficulty in visual accommodation. Which effect underlies this?",
 options:[
  {t:"Miosis through M3", correct:true, why:"Difficulty in visual accommodation is listed with miosis, an M3 effect on the eye."},
  {t:"Mydriasis through M3", correct:false, why:"Mydriasis follows M3 blockade; the agonist constricts the pupil."},
  {t:"Miosis through M2", correct:false, why:"The eye receptor is M3; M2 is the heart."},
  {t:"Hypotension through M2", correct:false, why:"Hypotension is a separate ADR, mediated by M3 release of nitric oxide."}],
 teach:"The listed adverse drug reactions (ADRs) of muscarinic agonists are DUMBBELSS, difficulty in visual accommodation (miosis, M3 on the eye), hypotension (M3-mediated release of nitric oxide) and bronchial constriction (M3 → Gq → phospholipase C (PLC) → inositol trisphosphate (IP3) → Ca2+).",
 quote:"Difficulty in visual accommodation Miosis",
 cite:"PCOL-Cholinergic-26s.pdf slide 15"},

{id:"L09-025", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"recall",
 concept:"atropine-scopolamine-class", tags:[], source:"slide",
 stem:"Which of the following is CORRECT about atropine and scopolamine?",
 options:[
  {t:"Naturally occurring, reversible alkaloids", correct:true, why:"Both are naturally occurring alkaloids, non-selective and reversible muscarinic antagonists."},
  {t:"Synthetic antagonists selective for the M3 receptor", correct:false, why:"They are natural alkaloids and non-selective."},
  {t:"Irreversible muscarinic antagonists", correct:false, why:"They are reversible."},
  {t:"Synthetic agonists at M1, M2 and M3", correct:false, why:"They are antagonists; atropine blocks M1, M2 and M3."}],
 teach:"Atropine and scopolamine are naturally occurring alkaloids. Both are non-selective, reversible muscarinic antagonists: atropine blocks M1, M2 and M3. Scopolamine is also an antagonist at histamine and serotonin receptors.",
 quote:"Naturally occurring Alkaloids / Non-selective and reversible / Atropine (M1, M2, and M3) / Scopolamine Antagonist to the Muscarinic, Histamine and serotonin receptors",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Pharmacodynamics — A. Mechanism of Action", t:"Atropine causes reversible (surmountable) blockade of cholinomimetic actions at muscarinic receptors: a small dose of atropine can be overcome by a larger concentration of acetylcholine. Atropine does not distinguish among the M1–M5 subgroups."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 17"},

{id:"L09-026", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"tell",
 concept:"scopolamine-extra-receptors", tags:[], source:"slide",
 stem:"Besides muscarinic receptors, scopolamine is an antagonist at which receptors?",
 options:[
  {t:"Histamine and serotonin", correct:true, why:"Scopolamine is an antagonist to the muscarinic, histamine and serotonin receptors."},
  {t:"Nicotinic Nn and Nm", correct:false, why:"No nicotinic action is listed for scopolamine."},
  {t:"α1 and β1", correct:false, why:"No adrenergic action is listed for scopolamine."},
  {t:"Dopamine and GABA receptors", correct:false, why:"Dopamine and GABA appear on the Parkinson (benztropine) slide, not as scopolamine targets."}],
 teach:"Atropine is listed as blocking M1, M2 and M3. Scopolamine is listed as an antagonist at muscarinic, histamine and serotonin receptors. Scopolamine penetrates the central nervous system (CNS) more rapidly and is used for motion sickness.",
 quote:"Scopolamine Antagonist to the Muscarinic, Histamine and serotonin receptors",
 cite:"PCOL-Cholinergic-26s.pdf slide 17"},

{id:"L09-027", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"apply",
 concept:"atropine-toxicity", tags:[], multi:true, source:"slide",
 stem:"A child eats berries of Atropa belladonna. Which findings are expected? Select all that apply.",
 options:[
  {t:"Dry mouth and skin", correct:true, why:"Dry as a bone: secretion is blocked."},
  {t:"Hot, red skin", correct:true, why:"Hot as a pistol and red as a beet."},
  {t:"Blurred vision with mydriasis", correct:true, why:"Blind as a bat; the pupil (M3) dilates."},
  {t:"Confusion", correct:true, why:"Mad as a hatter: atropine acts centrally as well as peripherally."},
  {t:"Bradycardia", correct:false, why:"Blocking M2 on the heart raises heart rate; bradycardia is an agonist effect."},
  {t:"Diarrhea", correct:false, why:"Blocking M3 in the GI tract causes constipation."}],
 teach:"Atropine comes from Atropa belladonna and Angel's Trumpet Flower and acts centrally and peripherally in a dose-dependent way. Toxicity: dry as a bone, hot as a pistol, red as a beet, blind as a bat, mad as a hatter. An overdose of a muscarinic antagonist is anti-DUMBBELSS: ↑ heart rate (M2), mydriasis (M3) and constipation (M3).",
 quote:"Toxicity Dry as a Bone Hot as a Pistol Red as a Beet Blind as a Bat Mad as a Hatter",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Adverse Effects", t:"Atropine-poisoned individuals show dry mouth, mydriasis, tachycardia, hot and flushed skin, agitation and delirium, often with elevated body temperature. Infants and children are especially sensitive to the hyperthermic effects of atropine."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 18; slide 19"},

{id:"L09-028", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"apply",
 concept:"atropine-heart-m2", tags:[], source:"slide",
 stem:"Why does atropine increase heart rate?",
 options:[
  {t:"It blocks M2, and PNS tone predominates", correct:true, why:"Heart = M2 = Gi = ↑ heart rate with atropine, because the PNS is the predominant tone at the heart."},
  {t:"It activates β receptors on the SA node", correct:false, why:"Atropine is a muscarinic antagonist with no stated β action."},
  {t:"It blocks M3 on the SA node", correct:false, why:"The SA node receptor is M2."},
  {t:"It activates M2 through the Gs protein", correct:false, why:"Atropine blocks M2; M2 is Gi, not Gs."}],
 teach:"At rest the heart is under predominant parasympathetic (PNS) tone through M2 (Gi), which slows it. Atropine blocks M2, removing that brake, so heart rate rises. The same logic gives mydriasis (M3 on the pupil, Gq) and constipation (M3 in the GI tract, Gq).",
 quote:"Heart = M2 = Gi = ↑ HR PNS is the predominant tone",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Organ System Effects — 3. Cardiovascular system", t:"The sinoatrial node is very sensitive to muscarinic blockade, and moderate to high doses of atropine cause tachycardia by blocking vagal slowing. Lower doses often cause an initial bradycardia, attributed to block of prejunctional M1 autoreceptors."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 19"},

{id:"L09-029", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"recall",
 concept:"atropine-uses", tags:[], source:"slide",
 stem:"Which of the following is a use of atropine?",
 options:[
  {t:"Muscarinic agonist overdose", correct:true, why:"Atropine treats muscarinic agonist overdose (bradycardia or atrioventricular nodal block) and organophosphate poisoning."},
  {t:"Glaucoma", correct:false, why:"Glaucoma is treated with the agonists carbachol and pilocarpine."},
  {t:"Urinary retention after surgery", correct:false, why:"Urinary retention is treated with the agonist bethanechol; atropine would worsen it."},
  {t:"Xerostomia", correct:false, why:"Xerostomia is treated with pilocarpine or cevimeline; atropine causes dry mouth."}],
 teach:"Atropine uses: treatment of muscarinic agonist overdose (bradycardia or atrioventricular nodal block), and organophosphate poisoning if the organophosphate is short acting, 2–5 mg every 10–15 min.",
 quote:"Treatment of Muscarinic Agonist overdose Bradycardia or atrioventricular nodal block Organophosphates Poisoning If the organophosphate is short acting 2-5 mg every 10-15 min",
 note:"Dose: the slide gives 2–5 mg every 10–15 min; Katzung Ch. 8 gives 1–2 mg atropine sulfate IV every 5–15 minutes for organophosphate poisoning. An exam from the lecture keys the slide.",
 cite:"PCOL-Cholinergic-26s.pdf slide 20"},

{id:"L09-030", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"figure",
 concept:"organophosphate-curve-shift", tags:[], source:"slide",
 stem:"A dose–response curve for acetylcholine (ACh) is shown. With an organophosphate present, the curve moves left; adding atropine moves it back right. Which of the following explains the two shifts?",
 options:[
  {t:"Organophosphate inhibits AChE; atropine blocks muscarinic receptors", correct:true, why:"Organophosphates are irreversible antagonists of acetylcholinesterase (AChE), so ACh builds up (left shift); atropine competes with ACh at the receptor (right shift)."},
  {t:"Organophosphate is a direct muscarinic agonist; atropine inhibits AChE", correct:false, why:"The organophosphate acts on AChE, and atropine is the receptor antagonist."},
  {t:"Both irreversibly block the muscarinic receptor", correct:false, why:"The organophosphate is irreversible at AChE, not the receptor, and atropine is reversible."},
  {t:"Organophosphate blocks the receptor; atropine releases ACh", correct:false, why:"This reverses the roles; atropine does not release ACh."}],
 teach:"Organophosphates are irreversible antagonists of acetylcholinesterase (AChE). With AChE inhibited, acetylcholine (ACh) accumulates and the ACh curve moves left, producing DUMBBELSS. Atropine is a reversible muscarinic antagonist that competes with ACh at the receptor and moves the curve back to the right.",
 quote:"Organophosphates Poisoning Irreversible antagonists to the AChE ... Ach + AchE antag. DUMBBELSS",
 cite:"PCOL-Cholinergic-26s.pdf slides 21–23"},

{id:"L09-031", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"atrop", skill:"tell",
 concept:"scopolamine-cns-motion", tags:[], source:"slide",
 stem:"Which muscarinic antagonist penetrates the CNS more rapidly and is used for motion sickness?",
 options:[
  {t:"Scopolamine", correct:true, why:"Scopolamine penetrates the central nervous system (CNS) more rapidly and is used for motion sickness."},
  {t:"Ipratropium", correct:false, why:"Ipratropium is inhaled for the lungs, with less systemic effect."},
  {t:"Tropicamide", correct:false, why:"Tropicamide is used in the eye for pupil dilation."},
  {t:"Trospium", correct:false, why:"Trospium is an overactive bladder drug in the group with the fewest CNS effects."},
  {t:"Benztropine", correct:false, why:"Benztropine is the drug used in Parkinson's patients treated with L-Dopa for tremor and rigidity."}],
 teach:"Scopolamine penetrates the central nervous system (CNS) more rapidly than atropine. It is used for motion sickness, and its CNS effects include drowsiness, euphoria and amnesia, on top of the peripheral anti-DUMBBELSS effects.",
 quote:"Scopolamine Penetrates the CNS more rapidly Motion sickness Drowsiness, euphoria, amnesia Anti-DUMBBELSS",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Chemistry & Pharmacokinetics — C. Distribution; Therapeutic Applications — Motion sickness", t:"Scopolamine is rapidly and fully distributed into the CNS, where it has greater effects than most other antimuscarinic drugs. It is one of the oldest remedies for seasickness and can be given by injection, by mouth or as a transdermal patch."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 24"},

{id:"L09-032", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"apply",
 concept:"benztropine-parkinson", tags:[], source:"slide",
 stem:"A patient with Parkinson's disease on L-Dopa still has tremor and rigidity. Benztropine is added. What is the basis for this?",
 options:[
  {t:"Dopaminergic loss leaves striatal ACh unopposed", correct:true, why:"With 70–80% loss of the dopaminergic neuron from the substantia nigra, cholinergic (ACh) activity in the striatum is unopposed, and benztropine blocks it."},
  {t:"Benztropine is a dopamine agonist", correct:false, why:"Benztropine is listed with atropine among the muscarinic antagonists."},
  {t:"Benztropine activates M1 in the striatum", correct:false, why:"Benztropine is an antagonist; it blocks muscarinic receptors."},
  {t:"Benztropine restores the lost striatal GABA neuron output", correct:false, why:"GABA neurons appear in the striatal diagram, but benztropine acts on the cholinergic side."}],
 teach:"In Parkinson's disease the dopaminergic neuron from the substantia nigra to the striatum is 70–80% lost, while the striatal acetylcholine (ACh) neuron remains. Benztropine (Cogentin), an atropine-like muscarinic antagonist, is used in Parkinson's patients treated with L-Dopa for tremor and rigidity.",
 quote:"Benztropine (Cogentin) Parkinson's Pts treated with L-Dopa Tremor & rigidity ... Dopaminergic Neuron 70-80% loss",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Organ System Effects — 1. Central nervous system", t:"Parkinsonian tremor and rigidity seem to result from a relative excess of cholinergic activity because of a deficiency of dopaminergic activity in the basal ganglia–striatum system. Combining an antimuscarinic agent with levodopa can sometimes give more effective therapy than either drug alone."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 25"},

{id:"L09-033", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"apply",
 concept:"tropicamide-mydriasis", tags:[], source:"slide",
 stem:"Tropicamide drops are placed in the eye before an exam. Why does the pupil dilate?",
 options:[
  {t:"M3 is blocked, leaving SNS dilation unopposed", correct:true, why:"Blocking M3 removes PNS pupil constriction, so SNS dilation is unopposed and mydriasis results."},
  {t:"It activates α1 receptors on the pupil dilator muscle", correct:false, why:"Tropicamide is a muscarinic antagonist; it does not act on α1."},
  {t:"It blocks M2 on the iris", correct:false, why:"The pupil constrictor pathway is M3 (Gq)."},
  {t:"It activates M3 through Gq", correct:false, why:"Activating M3 causes miosis; tropicamide blocks M3."}],
 teach:"The sympathetic nervous system (SNS) dilates the pupil and the parasympathetic nervous system (PNS) constricts it through M3 → Gq → PLC → IP3 and Ca2+ (miosis). Tropicamide blocks M3, so SNS dilation is unopposed and the pupil dilates (mydriasis); its use is optical, for pupil dilation.",
 quote:"Tropicamide Use Optical (Pupil Dilation) Rational? -SNS dilate the pupils -PNS constrict the pupils ... SNS is unopposed => Mydriasis",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Organ System Effects — 2. Eye; Table 8–2", t:"The pupillary constrictor muscle depends on M3 activation; topical antimuscarinics block it and leave sympathetic dilator activity unopposed, giving mydriasis. Tropicamide has the shortest duration of the ophthalmic antimuscarinics, 15–60 minutes."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 26"},

{id:"L09-034", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"tell",
 concept:"ipratropium-vs-tiotropium", tags:[], source:"slide",
 stem:"Which of the following is CORRECT about ipratropium and tiotropium?",
 options:[
  {t:"Ipratropium is a SAMA; tiotropium a LAMA", correct:true, why:"Ipratropium (Atrovent) is a short-acting muscarinic antagonist (SAMA), 3–4 times a day; tiotropium (Spiriva) is a long-acting muscarinic antagonist (LAMA), once a day."},
  {t:"Ipratropium is a LAMA; tiotropium a SAMA", correct:false, why:"This reverses them."},
  {t:"Tiotropium blocks M1, M2 and M3", correct:false, why:"Tiotropium is listed for M1 and M3; ipratropium is the one listed for M1, M2 and M3."},
  {t:"Both are taken orally", correct:false, why:"Both are inhaled, which gives less systemic effect."}],
 teach:"Inhaled muscarinic antagonists have less systemic effect. Ipratropium (Atrovent) blocks M1, M2 and M3 and is a short-acting muscarinic antagonist (SAMA), dosed 3–4 times a day. Tiotropium (Spiriva) blocks M1 and M3 and is a long-acting muscarinic antagonist (LAMA), dosed once a day.",
 quote:"Ipratropium (Atrovent) M1, M2, and M3; SAMA: Short acting (3-4x/Day) Tiotropium (Spiriva) M1 and M3; LAMA: Long acting (1x/Day)",
 note:"Katzung Table 8–1 lists tiotropium among M3 antagonists and says tiotropium and umeclidinium dissociate slowly from M3; the slide lists tiotropium as M1 and M3. An exam from the lecture keys the slide.",
 cite:"PCOL-Cholinergic-26s.pdf slide 28"},

{id:"L09-035", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"recall",
 concept:"aclidinium-umeclidinium", tags:[], source:"slide",
 stem:"Aclidinium and umeclidinium are best described by which of the following?",
 options:[
  {t:"High M3 affinity, slow dissociation", correct:true, why:"They have high affinity for M3 and are reversible but dissociate slowly."},
  {t:"Irreversible M3 antagonists", correct:false, why:"They are reversible, though slow to dissociate."},
  {t:"Oral antimuscarinics for overactive bladder", correct:false, why:"They are in the inhaled lung group with ipratropium and tiotropium."},
  {t:"Inhaled M3 agonists", correct:false, why:"They are muscarinic antagonists; an M3 agonist would constrict the bronchi."}],
 teach:"Aclidinium and umeclidinium are inhaled muscarinic antagonists with high affinity for M3. They are reversible but dissociate slowly from the receptor. Blocking M3 on bronchial smooth muscle removes PNS bronchial constriction in asthma and chronic obstructive pulmonary disease (COPD).",
 quote:"Aclidinium and Umeclidinium High affinity for the M3 (reversible, but slow dissociation)",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Therapeutic Applications — C. Respiratory Disorders", t:"Ipratropium, tiotropium, aclidinium and umeclidinium are synthetic atropine analogs used by inhalation in COPD, alone or with a long-acting β agonist. Tiotropium and umeclidinium can be given once daily because they dissociate slowly from M3 receptors; aclidinium is given twice daily."}],
 cite:"PCOL-Cholinergic-26s.pdf slide 28"},

{id:"L09-036", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"uses", skill:"apply",
 concept:"copd-rationale", tags:[], source:"slide",
 stem:"Why does an inhaled muscarinic antagonist relieve airflow obstruction in chronic obstructive pulmonary disease (COPD)?",
 options:[
  {t:"It blocks M3-driven bronchial constriction", correct:true, why:"The lungs are PNS only, and M3 → Gq → PLC → IP3 and Ca2+ constricts bronchial smooth muscle; blocking M3 stops it."},
  {t:"It blocks M2 on bronchial smooth muscle", correct:false, why:"The bronchial smooth muscle receptor is M3."},
  {t:"It activates sympathetic nerve fibers in the lung", correct:false, why:"The lungs are marked PNS only."},
  {t:"It raises IP3 in the airway", correct:false, why:"IP3 and Ca2+ drive constriction; the antagonist prevents the rise."}],
 teach:"COPD involves chronic inflammation with reduced airflow and mucus production (obstruction). The lungs receive parasympathetic nervous system (PNS) input only, and on bronchial smooth muscle M3 → Gq → phospholipase C (PLC) → inositol trisphosphate (IP3) and Ca2+ produces bronchial constriction. Blocking M3 removes that signal; inhalation gives less systemic effect.",
 quote:"Rational? - Lungs Only PNS Bronchial SM - M3 => Gq => PLC => IP3 & Ca++ = Bronchial Constriction",
 cite:"PCOL-Cholinergic-26s.pdf slide 27; slide 28"},

{id:"L09-037", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"bladder", skill:"recall",
 concept:"oab-moa", tags:[], multi:true, source:"slide",
 stem:"Which statements are CORRECT about the overactive bladder antimuscarinics (oxybutynin, tolterodine, fesoterodine, solifenacin, darifenacin, trospium)? Select all that apply.",
 options:[
  {t:"More selective toward bladder M3", correct:true, why:"They are more selective toward the M3 receptors in the bladder."},
  {t:"Hepatic metabolism by 3A4 or 2D6", correct:true, why:"The mechanism line lists hepatic metabolism (3A4 or 2D6)."},
  {t:"4–10× the antispasmodic effect of atropine", correct:true, why:"They have 4–10× the antispasmodic effect, with 1/5 the anticholinergic effect of atropine."},
  {t:"Irreversible receptor binding", correct:false, why:"They are reversible."},
  {t:"Goal: increase bladder emptying", correct:false, why:"The goal is to decrease urgency, frequency and leakage; emptying is the bethanechol use."}],
 teach:"Oxybutynin (Ditropan) is the oldest; the group also includes trospium, tolterodine (Detrol), fesoterodine (Toviaz), solifenacin (Vesicare) and darifenacin. They are non-selective, reversible and hepatically metabolized (3A4 or 2D6), but more selective toward bladder M3: 1/5 the anticholinergic effect of atropine and 4–10× the antispasmodic effect. Goal: decrease urgency, frequency and leakage.",
 quote:"MOA: Non-selective, reversible, and hepatic metabolism (3A4 or 2D6) More selective towards the M3 receptors in the bladder 1/5 of the anticholinergic effect of atropine 4-10x the antispasmodic effect Goal Decrease urgency, frequency and leakage",
 cite:"PCOL-Cholinergic-26s.pdf slide 29"},

{id:"L09-038", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"bladder", skill:"apply",
 concept:"oab-cns-order", tags:[], source:"slide",
 stem:"An older patient on oxybutynin for overactive bladder becomes confused and drowsy. Which drug is in the group least likely to cause these central nervous system (CNS) effects?",
 options:[
  {t:"Solifenacin", correct:true, why:"Solifenacin is in the M3 group (with darifenacin and trospium), at the bottom of the CNS-effect order."},
  {t:"Tolterodine", correct:false, why:"Tolterodine is in the middle group (M1 and M3)."},
  {t:"Fesoterodine", correct:false, why:"Fesoterodine is in the middle group with tolterodine (M1 and M3)."},
  {t:"Scopolamine", correct:false, why:"Scopolamine penetrates the CNS more rapidly and causes drowsiness and amnesia."}],
 teach:"CNS effects (drowsiness, dizziness and confusion) of the bladder antimuscarinics follow M1 blockade. Oxybutynin (M1 and M3) has the most; tolterodine and fesoterodine (M1 and M3) are intermediate; solifenacin, darifenacin and trospium (M3) have the least. Xerostomia and constipation (M3) occur with all of them.",
 quote:"Order of drugs with CNS effects (Drowsiness, dizziness, & confusion) M1 & M3 Oxybutynin / M1 & M3 Tolterodine Fesoterodine / M3 Solifenacin Darifenacin Trospium",
 note:"Katzung Ch. 8 calls trospium nonselective and comparable to oxybutynin in efficacy and adverse effects, and calls tolterodine M2- and M3-selective; the slide places trospium in the M3 group with the fewest CNS effects and tolterodine under M1 and M3. An exam from the lecture keys the slide.",
 cite:"PCOL-Cholinergic-26s.pdf slide 30"},

{id:"L09-039", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"bladder", skill:"recall",
 concept:"oab-xerostomia-m3", tags:[], source:"slide",
 stem:"Which adverse effects occur with all the overactive bladder antimuscarinics, and through which receptor?",
 options:[
  {t:"Dry mouth and constipation; M3", correct:true, why:"Xerostomia (dry mouth) and constipation are M3 effects and occur with all muscarinic antagonists."},
  {t:"Confusion and drowsiness; M3 receptor", correct:false, why:"CNS effects vary across the group and are linked to M1; they are greatest with oxybutynin."},
  {t:"Bradycardia and miosis; M2", correct:false, why:"Bradycardia and miosis are agonist effects."},
  {t:"Diarrhea and salivation; M3", correct:false, why:"These are DUMBBELSS (agonist) effects; antagonists cause the opposite."}],
 teach:"All the bladder antimuscarinics can cause anti-DUMBBELSS. Xerostomia (dry mouth) and constipation come from M3 blockade and occur with all muscarinic antagonists. Central nervous system (CNS) effects differ by drug and track M1 blockade.",
 quote:"All have the potential to cause anti-DUMBBELSS Xerostomia (dry mouth) and constipation M3 All Musc. Antag",
 note:"The student drug list says solifenacin, darifenacin and trospium are least likely to cause anti-DUMBBELSS; the slide ranks them least for CNS effects and says all have the potential for anti-DUMBBELSS. The slide wins.",
 cite:"PCOL-Cholinergic-26s.pdf slide 30"},

{id:"L09-040", lecture:"L09", prof:"Gottlieb", tier:"new", topic:"L09", sub:"bladder", skill:"apply",
 concept:"anti-dumbbelss-effects", tags:[], multi:true, source:"slide",
 stem:"Which pharmacological effects are expected from a muscarinic antagonist? Select all that apply.",
 options:[
  {t:"Tachycardia", correct:true, why:"Cardiovascular: tachycardia, from M2 blockade."},
  {t:"Bronchial dilation", correct:true, why:"Respiratory: bronchial dilation."},
  {t:"Pupil dilation", correct:true, why:"Eye: pupil dilation."},
  {t:"Hallucinations and restlessness", correct:true, why:"CNS: hallucinations, restlessness and coma, from M1 blockade, dose-dependent."},
  {t:"Miosis", correct:false, why:"Miosis is an agonist effect."},
  {t:"Increased salivation", correct:false, why:"Antagonists cause dry mouth."}],
 teach:"Muscarinic antagonists are reversible and mostly non-selective, and all have affinity for M3. Their effects are anti-DUMBBELSS: dry mouth and constipation, tachycardia (M2), bronchial dilation, pupil dilation, and central nervous system (CNS) hallucinations, restlessness and coma (M1). These depend on dose and selectivity.",
 quote:"Pharmacological effects Dry mouth & constipation M2 CV Tachycardia Respiratory Bronchial dilation Eye Pupil dilation M1 CNS Hallucinations, restlessness, & coma ⇒ Dose-dependent ⇒ Selectivity",
 cite:"PCOL-Cholinergic-26s.pdf slide 32"}
);
