TOPICS.push({id:"L08", name:"Nicotinic receptors and NMJ pharmacology", prof:"Gottlieb", lecture:"L08",
  cite:"Day 8 (10/5) — PCOL-NMJ_PCOL_2026s_pptx.pdf (slides 1–18 were started 10/1)",
  subs:[
    {id:"nnm", name:"Nn vs Nm receptors: location, subunits, SOA", cite:"slides 3–6, 11"},
    {id:"nnag", name:"Nn agonists: ACh, nicotine, varenicline", cite:"slides 7–10"},
    {id:"nmj", name:"NMJ agents and NMJ signaling", cite:"slides 11–19"},
    {id:"sch", name:"Succinylcholine: phase I/II, ADRs, DDI", cite:"slides 19–26"},
    {id:"curare", name:"Curare-like (non-depolarizing) drugs", cite:"slides 27–32"},
    {id:"ache", name:"Reversible cholinesterase inhibitors", cite:"slides 33–41"},
    {id:"op", name:"Organophosphates, antidote, echothiophate", cite:"slides 42–45"},
    {id:"botox", name:"Botulinum toxin", cite:"slides 46–50"}
  ]});
QUESTIONS.push(
{id:"L08-001", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"recall",
 concept:"nn-location", tags:[], source:"both",
 stem:"Where are neuronal nicotinic (Nn) receptors located?",
 options:[
  {t:"Brain and autonomic ganglia", correct:true, why:"Nn receptors are in the brain and in the autonomic ganglia, where they activate postganglionic neurons; the adrenal medulla also has Nn receptors."},
  {t:"Skeletal neuromuscular junction", correct:false, why:"The skeletal neuromuscular junction carries the muscle-type nicotinic (Nm) receptor, not Nn."},
  {t:"Heart and smooth muscle", correct:false, why:"Heart and smooth muscle respond to acetylcholine through muscarinic receptors (for example M2 in the heart), not Nn."},
  {t:"Salivary glands", correct:false, why:"Salivary glands are reached by postganglionic fibers acting on M3 muscarinic receptors."},
  {t:"Skeletal muscle and brain", correct:false, why:"Skeletal muscle has Nm receptors; only the brain half of this pairing is Nn."}],
 teach:"N stands for nicotinic; the subscript N is neuronal and the subscript M is muscular. Nn receptors sit in the brain and in the autonomic ganglia of both the sympathetic and parasympathetic systems, and also at the adrenal medulla. Nm receptors sit at the skeletal neuromuscular junction of the somatic system.",
 quote:"Where are the two locations for the NN receptors? The brain and. On the ganglia of the autonomic nerve system, right?",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 4; transcript 10/1; transcript 10/5"},

{id:"L08-002", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"tell",
 concept:"nn-vs-nm-subunits", tags:[], source:"slide",
 stem:"Which statement correctly contrasts the subunits of neuronal nicotinic (Nn) and muscle nicotinic (Nm) receptors?",
 options:[
  {t:"Nn: only α and β; Nm: α, β, γ, δ and ε", correct:true, why:"Nn receptors are built only from α (α2–α9) and β (β2–β4) subunits; Nm receptors have 5 protein subunits, α, β, γ, δ and ε."},
  {t:"Nn: α, β, γ, δ and ε; Nm: only α and β", correct:false, why:"This reverses the two receptors; the five-subunit set belongs to the muscle receptor."},
  {t:"Both: only α4 and β2", correct:false, why:"α4/β2 is the brain Nn combination; ganglionic Nn is α3/β4 and α3/β2, and Nm has five kinds of subunits."},
  {t:"Nn: α3 and β4 only; Nm: α4 and β2 only", correct:false, why:"α3/β4 is a ganglionic Nn combination and α4/β2 is the brain Nn combination; neither describes Nm."},
  {t:"Nn: γ and ε; Nm: α and δ", correct:false, why:"γ and ε are found in Nm, and Nn is made only of α and β subunits."}],
 teach:"Nn receptors are composed only of α subunits (α2 to α9) and β subunits (β2 to β4); the brain combination is α4/β2 and the ganglionic combinations are α3/β4 and α3/β2. The Nm receptor at the skeletal neuromuscular junction is made of 5 protein subunits: α, β, γ, δ and ε. Both are ion channels that let Na+ in.",
 quote:"Composed of only α and β Subunits; α (α2- α9); β (β2- β4) … Skeletal Neuromuscular Junction in the Somatic System: 5 protein subunits (α, β, γ, δ, and ε)",
 note:"In the 10/1 audio he said NN is \"only beta and gammas\"; the slide reads α and β, and the slide is used here. He said the one Nn combination to know is α4/β2 (10/1); the other combinations appear here only as wrong options.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 6, 11"},

{id:"L08-003", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"recall",
 concept:"nn-alpha4beta2-brain", tags:[], source:"both",
 stem:"Which neuronal nicotinic (Nn) subunit combination is found in the brain?",
 options:[
  {t:"α3/β4", correct:false, why:"α3/β4 is a ganglionic Nn combination; the brain combination, where varenicline acts, is α4/β2."},
  {t:"α4/β2", correct:true, why:"The brain Nn receptor is the α4/β2 combination, the site of action of varenicline."},
  {t:"α3/β2", correct:false, why:"α3/β2 is the other ganglionic Nn combination, on postganglionic neurons of both divisions, not the brain."},
  {t:"α, β, γ, δ, ε", correct:false, why:"The five-subunit set (α, β, γ, δ, ε) is the muscle nicotinic (Nm) receptor at skeletal muscle; Nn receptors have only α and β subunits."}],
 teach:"Nn receptors differ by subunit combination and location: α4/β2 in the brain, α3/β4 and α3/β2 in the autonomic ganglia. The α4/β2 combination is the one to know because it is where varenicline acts. A drug selective for α4/β2 leaves ganglionic Nn and skeletal Nm receptors alone.",
 quote:"SOA: Brain α4/β2. Ganglia: Activate post-ganglionic neurons of both SNS and PNS α3/β4 and α3/β2",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 6; transcript 10/1"},

{id:"L08-004", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"recall", multi:true,
 concept:"nm-features", tags:[], source:"both",
 stem:"Which statements describe the muscle nicotinic (Nm) receptor? Select all that apply.",
 options:[
  {t:"It is at the skeletal neuromuscular junction", correct:true, why:"Nm is the receptor at the skeletal neuromuscular junction of the somatic system."},
  {t:"It has five subunits: α, β, γ, δ, ε", correct:true, why:"Nm is made of 5 protein subunits: α, β, γ, δ and ε."},
  {t:"Opening it lets Na+ in and depolarizes the cell", correct:true, why:"Acetylcholine opens the Nm channel; more Na+ enters than K+ leaves, so the membrane becomes more positive."},
  {t:"It is made only of α and β subunits", correct:false, why:"Only α and β is the neuronal Nn receptor."},
  {t:"It activates postganglionic SNS and PNS neurons", correct:false, why:"Activating postganglionic neurons of both systems is the job of ganglionic Nn receptors (α3/β4, α3/β2)."},
  {t:"Its main subtype is α4/β2 in the brain", correct:false, why:"α4/β2 is the brain Nn receptor."}],
 teach:"The Nm receptor is the nicotinic receptor of skeletal muscle in the somatic system, built from α, β, γ, δ and ε subunits. Acetylcholine binding opens it, Na+ enters and K+ leaves, the end plate depolarizes, voltage-gated Ca2+ channels open and the muscle contracts. Nn receptors (only α and β) are the ones in the brain and in the ganglia of the sympathetic (SNS) and parasympathetic (PNS) nervous systems.",
 quote:"Skeletal Neuromuscular Junction in the Somatic System; 5 protein subunits (α, β, γ, δ, and ε); Skeletal Muscle Contraction",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 11, 13–15; transcript 10/1"},

{id:"L08-005", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"apply",
 concept:"ganglionic-nn-second-effects", tags:[], source:"both",
 stem:"A nicotinic agonist activates neuronal nicotinic (Nn) receptors in the autonomic ganglia. Heart rate and salivation change even though the drug does not bind cardiac or glandular receptors. What explains these organ effects?",
 options:[
  {t:"Postganglionic neurons act on organ receptors", correct:true, why:"Ganglionic Nn activates postganglionic neurons of both the SNS and PNS, which then act on organ receptors such as M2, β, α1 and M3; these are secondary effects."},
  {t:"The drug binds M2 receptors in the heart directly, bypassing the ganglia", correct:false, why:"A nicotinic agonist acts on nicotinic receptors; M2 activation here is downstream of the ganglion."},
  {t:"The drug blocks acetylcholinesterase in the organs", correct:false, why:"Blocking acetylcholinesterase is the mechanism of an indirect-acting drug; a direct Nn agonist binds the ganglionic receptor itself."},
  {t:"Muscle nicotinic (Nm) receptors are on the heart", correct:false, why:"Nm receptors are at the skeletal neuromuscular junction only; the heart responds to the postganglionic transmitters (acetylcholine on M2, norepinephrine on β1)."},
  {t:"Only the PNS ganglia carry Nn receptors", correct:false, why:"Nn receptors activate postganglionic neurons of both the SNS and the PNS."}],
 teach:"Nicotinic drugs act directly where Nn or Nm receptors are: brain, autonomic ganglia, adrenal medulla and skeletal muscle. Because ganglionic Nn receptors drive the postganglionic neurons of both the sympathetic nervous system (SNS) and parasympathetic nervous system (PNS), a ganglionic drug produces 2nd effects in organs through M2 (heart), β, α1 (vessels) and M3 (salivary gland) receptors. Predict the organ effect from where the receptor is.",
 quote:"Some places like the lungs, which only has parasympathetic, it's gonna bronchoconstrict. OK, the blood pressure is gonna rise because it's only sympathetic",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Basic & Clinical Pharmacology of the Ganglion-Blocking Drugs — Mechanism of Action (p. 11 of 14)", t:"Ganglion-blocking drugs act at neuronal nicotinic receptors of both parasympathetic and sympathetic ganglia, so they can block all autonomic outflow. Nicotine itself, and acetylcholine amplified with a cholinesterase inhibitor, can produce depolarizing ganglion block. Organ effects of ganglionic drugs follow from which autonomic division dominates each tissue."}],
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 5–6; transcript 10/5"},

{id:"L08-006", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"apply",
 concept:"adrenal-medulla-nn", tags:[], source:"both",
 stem:"Nicotine reaches the adrenal medulla. Which receptor does acetylcholine or nicotine act on at this site?",
 options:[
  {t:"Muscle nicotinic (Nm) receptor", correct:false, why:"Nm is the receptor at the skeletal neuromuscular junction; the adrenal medulla is reached by a sympathetic preganglionic fiber, like a ganglion, so its receptor is Nn."},
  {t:"Neuronal nicotinic (Nn)", correct:true, why:"At the adrenal medulla a sympathetic fiber releases acetylcholine onto an Nn receptor; this is the exception to the adrenergic rule."},
  {t:"M3 muscarinic receptor", correct:false, why:"M3 is the salivary gland and smooth muscle receptor reached by postganglionic fibers."},
  {t:"α1 adrenergic", correct:false, why:"α1 receptors are on vascular smooth muscle and respond to norepinephrine, not acetylcholine."}],
 teach:"The adrenal medulla is the exception in the sympathetic system: the fiber that reaches it releases acetylcholine onto a neuronal nicotinic (Nn) receptor rather than releasing norepinephrine onto an adrenergic receptor. Anything that activates or blocks Nn receptors therefore also acts at the adrenal medulla. Nm receptors are only at skeletal muscle.",
 quote:"Ach NN Adrenal Medulla",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 4–5; transcript 10/1"},

{id:"L08-007", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnm", skill:"tell",
 concept:"direct-vs-indirect-acting", tags:["cholinesterase"], source:"both",
 stem:"Which pairing of cholinergic receptor stimulant type and its action is correct? (ACh = acetylcholine)",
 options:[
  {t:"Direct-acting: block the enzyme that breaks down ACh", correct:false, why:"Blocking the enzyme is the indirect route; direct-acting drugs bind the receptor."},
  {t:"Indirect-acting: increase synaptic ACh", correct:true, why:"Indirect-acting drugs, reversible or irreversible, raise ACh at the synapse by blocking its breakdown."},
  {t:"Indirect-acting: alkaloids and choline esters", correct:false, why:"Alkaloids and choline esters are the two groups of direct-acting drugs."},
  {t:"Direct-acting: only act at muscarinic receptors", correct:false, why:"Direct-acting drugs act at muscarinic and nicotinic receptors; the alkaloids and choline esters include both kinds."},
  {t:"Indirect-acting: bind the nicotinic receptor", correct:false, why:"Binding the receptor is the direct route; indirect-acting drugs bind the enzyme and act on the receptor only through the extra acetylcholine."}],
 teach:"Receptor stimulants are divided into direct-acting drugs (alkaloids and choline esters), which bind muscarinic or nicotinic receptors themselves, and indirect-acting drugs (reversible or irreversible), which increase acetylcholine (ACh) by blocking its breakdown. Nicotinic receptors are either Nn in autonomic ganglion cells or Nm at the neuromuscular junction. An indirect drug affects the receptor by binding somewhere other than the receptor.",
 quote:"This is what kind of antagonist that is in direct antagonist, because it's affecting somewhere else other than the receptor, right?",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 3; transcript 10/1; transcript 10/5"},

{id:"L08-008", dupOf:"PE2-087", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnag", skill:"recall",
 concept:"varenicline-moa", tags:["druglist"], source:"both",
 stem:"Varenicline is best described as:",
 options:[
  {t:"A competitive antagonist at muscle nicotinic (Nm) receptors", correct:false, why:"Competitive Nm antagonism is the curare-like (non-depolarizing) mechanism."},
  {t:"A full agonist at ganglionic α3/β4 receptors", correct:false, why:"Varenicline is selective for α4/β2 and is a partial agonist; it leaves ganglionic receptors alone."},
  {t:"A partial agonist at α4/β2 Nn receptors", correct:true, why:"Varenicline is a high-affinity, selective partial agonist at the central α4/β2 neuronal nicotinic (Nn) receptor."},
  {t:"An acetylcholinesterase inhibitor", correct:false, why:"Enzyme inhibitors are indirect drugs such as the -stigmines; varenicline binds the receptor directly."},
  {t:"A depolarizing agent at the NMJ", correct:false, why:"The depolarizing agent at the neuromuscular junction (NMJ) is succinylcholine."}],
 teach:"Varenicline has high affinity and partial agonist activity at the α4/β2 central nicotinic (Nn) receptor; its site of action (SOA) is the central nervous system. With low nicotine (withdrawal) it activates the receptor and decreases craving and withdrawal; in a smoker it competes with nicotine and blunts the nicotine effect. He called the α4/β2 partial agonist mechanism the must-know fact.",
 quote:"So it's a partial agonist to what? The alpha 4, beta 2, nicotinic, what type of nicotinic receptor? And for what neuronal.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 7–8; transcript 10/1; transcript 10/5"},

{id:"L08-009", lecture:"L08", prof:"Gottlieb", tier:"new", level:1, topic:"L08", sub:"nnag", skill:"apply", multi:true,
 concept:"varenicline-effects", tags:["druglist"], source:"both",
 stem:"A patient trying to stop smoking starts varenicline. Which effects follow from its mechanism? Select all that apply.",
 options:[
  {t:"Decreased craving and withdrawal", correct:true, why:"Partial activation of α4/β2 receptors relieves craving and withdrawal when nicotine is low."},
  {t:"A blunted effect of smoked nicotine", correct:true, why:"Its high affinity lets it compete with nicotine, and its lower efficacy blunts the nicotine effect."},
  {t:"Action in the central nervous system", correct:true, why:"Its site of action is the CNS (central α4/β2 receptors)."},
  {t:"Skeletal muscle paralysis", correct:false, why:"Varenicline leaves Nm receptors at skeletal muscle alone; paralysis is the effect of succinylcholine or curare-like drugs."},
  {t:"Block of all autonomic ganglia", correct:false, why:"Varenicline is selective for α4/β2 and leaves ganglionic Nn receptors alone."}],
 teach:"Varenicline is a selective, high-affinity partial agonist at central α4/β2 neuronal nicotinic receptors. A partial agonist behaves as an agonist when the baseline is low (withdrawal) and as an antagonist when a full agonist is present (it competes with nicotine). Its selectivity means ganglionic Nn and skeletal Nm receptors are not targeted. CNS = central nervous system.",
 quote:"If it's neuronal, that should be a key that the site of action that drugs where in the brain.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 8; transcript 10/1; transcript 10/5"},

{id:"L08-010", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nnag", skill:"recall",
 concept:"varenicline-adr", tags:["druglist"], source:"both",
 stem:"Which of the following is a common adverse drug reaction (ADR) of varenicline?",
 options:[
  {t:"Hyperkalemia", correct:false, why:"Hyperkalemia comes from opening Nm channels in skeletal muscle so K+ leaves the cells (succinylcholine); varenicline acts at brain α4/β2 receptors, not Nm."},
  {t:"Histamine release with bronchial spasm", correct:false, why:"Histamine release with bronchial spasm is an ADR of some curare-like drugs (mainly atracurium), not of a nicotinic partial agonist."},
  {t:"Nausea", correct:true, why:"Nicotinic receptors in the gut and on the vomiting center are activated, so nausea and vomiting are the most common gastrointestinal (GI) complaints; headache, insomnia and depression are the central nervous system (CNS) effects."},
  {t:"Miosis and blurred vision", correct:false, why:"Miosis and blurred vision come from more acetylcholine on M3 in the eye (echothiophate); varenicline acts at nicotinic receptors."},
  {t:"Respiratory paralysis", correct:false, why:"Respiratory paralysis comes from blocking Nm at the diaphragm (curare-like drugs); varenicline leaves Nm alone."}],
 teach:"The most common side effects of varenicline are GI (nausea and vomiting, because nicotinic receptors in the gut and the vomiting center are activated) and CNS (headache, insomnia, depression), since its site of action is the brain. Patients also complain of flatulence, another GI effect. He said not to memorize the nausea percentage (16–40%); it only shows how frequent nausea is.",
 quote:"Most common: GI: Nausea (16-40%) & Vomiting; CNS: Headache, Insomnia, Depression",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 9; transcript 10/1; transcript 10/5"},

{id:"L08-011", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nmj", skill:"recall",
 concept:"nmj-agent-goal", tags:[], source:"both",
 stem:"What is the primary goal of neuromuscular junction (NMJ) agents?",
 options:[
  {t:"Act at Nm receptors with little or no effect at ganglionic Nn", correct:true, why:"NMJ agents aim to affect transmission at muscle nicotinic (Nm) receptors with no or little effect at neuronal nicotinic (Nn) receptors in the autonomic ganglia."},
  {t:"Act at ganglionic Nn receptors with no effect on skeletal muscle", correct:false, why:"This reverses the target; NMJ agents are aimed at skeletal muscle Nm receptors."},
  {t:"Block muscarinic receptors in the heart", correct:false, why:"Muscarinic receptors in the heart are a side-effect site, not the target; NMJ agents act on the nicotinic Nm receptor of skeletal muscle."},
  {t:"Activate α4/β2 receptors in the brain", correct:false, why:"Activating α4/β2 in the brain is varenicline's action; NMJ agents are aimed at the skeletal muscle Nm receptor."},
  {t:"Prevent ACh synthesis in the nerve", correct:false, why:"NMJ agents act at the receptor or at the enzyme that breaks down acetylcholine (ACh)."}],
 teach:"NMJ agents should affect synaptic transmission at the muscle nicotinic (Nm) receptor while sparing neuronal nicotinic (Nn) receptors at the autonomic ganglia. They come in two types: direct (bind Nm; depolarizing agonists or non-depolarizing antagonists) and indirect (bind acetylcholinesterase and raise acetylcholine). Loss of this selectivity explains ganglionic side effects such as pancuronium tachycardia or succinylcholine cardiovascular effects.",
 quote:"Remember, these drugs, their target is what? The NM. That's what you wanna do. Those are in the skeletal muscle. The NN is on the ganglia.",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Chapter introduction (p. 3 of 14)", t:"Antinicotinic drugs are divided into ganglion blockers and neuromuscular junction blockers. Ganglion blockers have little clinical use, while neuromuscular blockers are heavily used."}],
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 12; transcript 10/5"},

{id:"L08-012", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nmj", skill:"tell",
 concept:"nmj-three-classes", tags:[], source:"both",
 stem:"Which pairing of a neuromuscular junction (NMJ) drug class with its mechanism is correct?",
 options:[
  {t:"Depolarizing agents: direct antagonists", correct:false, why:"Depolarizing agents are direct agonists (acetylcholine, succinylcholine); they open the channel."},
  {t:"Non-depolarizing: direct antagonists", correct:true, why:"Non-depolarizing agents (curare-like drugs) bind the muscle nicotinic receptor with affinity but no efficacy."},
  {t:"Cholinesterase inhibitors: direct Nm agonists", correct:false, why:"Cholinesterase inhibitors are indirect; they bind the enzyme, not the receptor."},
  {t:"Non-depolarizing agents: enzyme inhibitors", correct:false, why:"Enzyme inhibition is the indirect class (cholinesterase inhibitors); non-depolarizing agents bind the Nm receptor itself and block it."},
  {t:"Depolarizing agents: lower synaptic ACh", correct:false, why:"Depolarizing agents open the channel; they do not lower acetylcholine (ACh)."}],
 teach:"Three classes act on the NMJ. Depolarizing agents are nicotinic receptor agonists (acetylcholine, succinylcholine): opening the channel lets Na+ in and makes the membrane more positive. Non-depolarizing agents are nicotinic receptor antagonists (curare-like drugs) that bind and sit with no efficacy. Cholinesterase inhibitors are indirect antagonists that bind the enzyme and raise synaptic acetylcholine.",
 quote:"depolarizing, which is the same thing as an agonist, it is activating the receptors, and non-depolarizing, which is gonna be the antagonist.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 11–12; transcript 10/1; transcript 10/5"},

{id:"L08-013", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"nmj", skill:"recall",
 concept:"nm-activation-sequence", tags:[], source:"both",
 stem:"Acetylcholine opens the muscle nicotinic (Nm) channel at the skeletal muscle cell. What happens next that leads to contraction?",
 options:[
  {t:"Depolarization opens voltage-gated Ca2+ channels", correct:true, why:"More Na+ enters than K+ leaves, the membrane becomes more positive, and voltage-gated Ca2+ channels open; Ca2+ allows actin and myosin to contract."},
  {t:"The membrane hyperpolarizes and K+ channels close", correct:false, why:"Opening the Nm channel makes the membrane more positive, not more negative."},
  {t:"Gαq activates phospholipase C", correct:false, why:"The Nm receptor is a ligand-gated ion channel, not a G protein–coupled receptor."},
  {t:"The Na+/K+ ATPase pumps Na+ into the cell", correct:false, why:"The pump moves Na+ out and K+ in; it restores the resting state during recovery."},
  {t:"Acetylcholinesterase releases more acetylcholine", correct:false, why:"Acetylcholinesterase breaks acetylcholine down into choline and acetate."}],
 teach:"At rest, acetylcholine sits in vesicles. After release it binds the α subunits of the Nm ion channel; Na+ comes in and K+ goes out, the membrane depolarizes, voltage-gated Ca2+ channels open, and Ca2+ drives actin–myosin contraction. Recovery: acetylcholinesterase splits acetylcholine into choline and acetate, the channel closes, and the Na+/K+ ATPase restores the ion gradients.",
 quote:"Very quickly open those channels, allow sodium to come in, which is going to make this more what positive, and that's going to open the calcium channels.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 13–17; transcript 10/1; transcript 10/5"},

{id:"L08-014", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"tell",
 concept:"depolarizing-vs-nondepolarizing", tags:["succinylcholine"], source:"both",
 stem:"Succinylcholine and rocuronium both cause paralysis. Which statement correctly separates them?",
 options:[
  {t:"Succinylcholine opens the channel; rocuronium keeps it shut", correct:true, why:"Succinylcholine is a depolarizing agonist; rocuronium is a non-depolarizing competitive antagonist."},
  {t:"Succinylcholine stops channels from opening; rocuronium opens them", correct:false, why:"Reversed: succinylcholine is the agonist that opens Nm channels; rocuronium is the competitive antagonist that keeps them from opening."},
  {t:"Both are competitive antagonists at muscle nicotinic (Nm) receptors", correct:false, why:"Only rocuronium is a competitive antagonist; succinylcholine is an agonist."},
  {t:"Both inhibit acetylcholinesterase", correct:false, why:"Neither acts on the enzyme; both bind the muscle nicotinic (Nm) receptor."},
  {t:"Succinylcholine blocks ACh release; rocuronium is an agonist", correct:false, why:"Blocking acetylcholine (ACh) release is botulinum toxin; rocuronium is an antagonist."}],
 teach:"Both NMJ agents cause paralysis, by different mechanisms. Depolarizing: succinylcholine (given IV) is an agonist that opens nicotinic ion channels and keeps the end plate depolarized. Non-depolarizing: curare (prototype), mivacurium, vecuronium, rocuronium and pancuronium are competitive antagonists that stop the nicotinic ion channels from opening. Drugs with -cur- in the name are curare-like.",
 quote:"The key thing over here is, even though one is an antagonist and the other one is an agonist, both of these drugs are gonna cause paralysis through different mechanisms of actions, OK?",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 19; transcript 10/5"},

{id:"L08-015", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"recall",
 concept:"sch-structure-use", tags:["druglist", "succinylcholine"], source:"both",
 stem:"Which statement about succinylcholine (SCh) is CORRECT?",
 options:[
  {t:"It resembles two ACh molecules joined end to end", correct:true, why:"Because it looks like acetylcholine (ACh), succinylcholine (SCh) binds and opens the muscle nicotinic (Nm) channel as an agonist; unlike ACh it is not broken down quickly at the synapse."},
  {t:"It has a slow onset and long duration", correct:false, why:"SCh has a rapid onset and a short duration of action."},
  {t:"It is a competitive antagonist at Nm", correct:false, why:"SCh depolarizes the neuromuscular junction: it opens the Nm channel as an agonist, while competitive Nm antagonism is the curare-like mechanism."},
  {t:"It is broken down at the synapse as quickly as ACh", correct:false, why:"SCh is not metabolized effectively at the synapse; that is why it stays on the receptor and keeps the end plate depolarized."},
  {t:"It only acts in the central nervous system", correct:false, why:"SCh acts at the neuromuscular junction and, at higher doses, at autonomic ganglia; its target is the Nm receptor of skeletal muscle."}],
 teach:"Succinylcholine looks like two acetylcholine molecules joined at the alkyl ends, so it is a depolarizing agonist at the neuromuscular junction (NMJ). It has a rapid onset and short duration and is used IV for rapid intubation and as an adjunct to general anesthesia. At increased doses it also stimulates ganglia and therefore the PNS and SNS. He said the uses are for knowledge only and will not be tested; the mechanism and sites of action are what to know.",
 quote:"There are like two molecules of acetylcholine combined together, OK?",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 20; transcript 10/1; transcript 10/5"},

{id:"L08-016", lecture:"L08", prof:"Gottlieb", tier:"new", level:1, ladder:"succinylcholine", ladderName:"Succinylcholine, halothane and dantrolene", topic:"L08", sub:"sch", skill:"apply",
 concept:"sch-ganglia-high-dose", tags:["succinylcholine"], source:"both",
 stem:"A patient receives a high dose of succinylcholine (SCh). Besides the neuromuscular junction, which site can SCh stimulate, producing cardiovascular effects?",
 options:[
  {t:"Autonomic ganglia (PNS and SNS)", correct:true, why:"At increased doses SCh stimulates ganglia, and thus the parasympathetic (PNS) and sympathetic (SNS) systems; downstream M2, β1 and α1 receptors change heart and vessels."},
  {t:"α4/β2 receptors in the brain", correct:false, why:"α4/β2 in the brain is varenicline's site; succinylcholine's extra site at high doses is the ganglionic Nn receptor."},
  {t:"Acetylcholinesterase in cardiac tissue", correct:false, why:"Succinylcholine binds nicotinic receptors as an agonist; it does not inhibit acetylcholinesterase."},
  {t:"Presynaptic SNARE proteins", correct:false, why:"SNARE proteins are cleaved by botulinum toxin to stop acetylcholine release; succinylcholine acts on postsynaptic nicotinic receptors."}],
 teach:"Succinylcholine is selective for the muscle nicotinic (Nm) receptor at clinical doses, but at increased doses it stimulates neuronal nicotinic (Nn) receptors in autonomic ganglia, activating both the parasympathetic and sympathetic outflow. The downstream receptors (M2 and β1 in the heart, α1 on vessels) account for hypertension and arrhythmias listed among its ADRs. A prolonged infusion does the same thing as a higher dose; a non-selective beta blocker is sometimes given to block the cardiac effects.",
 quote:"So if you infuse for a longer period of time, you're gonna start to open those nicotinic receptors in the ganglia, which is gonna increase your parasympathetic and sympathetic at the same time.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 20, 25; transcript 10/5"},

{id:"L08-017", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"tell",
 concept:"sch-phase1-vs-phase2", tags:["succinylcholine"], source:"both",
 stem:"Which statement correctly contrasts phase I and phase II succinylcholine block?",
 options:[
  {t:"Phase I: end plate cannot reprime; phase II: channel block", correct:true, why:"In phase I the agonist keeps the end plate depolarized so it cannot repolarize; in phase II channel blockade prevents Na+/K+ movement and prolongs paralysis."},
  {t:"Phase I: channel blockade; phase II: prolonged depolarization", correct:false, why:"Reversed: phase I is the prolonged depolarization (the end plate cannot re-prime); phase II is succinylcholine lodged inside the channel pore."},
  {t:"Phase I: competitive antagonism; phase II: acetylcholinesterase inhibition", correct:false, why:"Succinylcholine is an agonist in phase I and a channel blocker in phase II; neither phase is competitive antagonism or enzyme inhibition."},
  {t:"Phase I: rapid breakdown by acetylcholinesterase; phase II: release", correct:false, why:"Succinylcholine is not metabolized effectively at the synapse; that is why phase I occurs."},
  {t:"Both phases are a non-depolarizing block", correct:false, why:"Phase I is a depolarizing block (the agonist opens the channels) and phase II is a channel block; neither is the curare-like competitive block."}],
 teach:"Normal transmission needs repetitive firing, rapid breakdown of acetylcholine, and repolarization of the motor end plate (re-priming). Phase I (depolarizing) block: succinylcholine opens the channel but is not metabolized effectively, so the end plate stays depolarized, cannot reprime, and the muscle is paralyzed. Phase II block: succinylcholine blocks the channel, preventing Na+/K+ movement and prolonging the paralysis.",
 quote:"And the first one is that opening of all the receptors. That's called phase one. And then if it stays around longer, now it actually can get lodged inside of that channel. And that will be a phase 2.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 21–24; transcript 10/1; transcript 10/5"},

{id:"L08-018", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"recall", multi:true,
 concept:"sch-phase1-features", tags:["succinylcholine"], source:"both",
 stem:"Which features describe the state of depolarizing blockade (phase I) produced by succinylcholine? Select all that apply.",
 options:[
  {t:"Longer synaptic half-life than acetylcholine", correct:true, why:"Succinylcholine is not broken down quickly at the synapse, so its synaptic half-life is longer."},
  {t:"Prolonged depolarization of the motor end plate", correct:true, why:"The end plate stays depolarized and cannot be re-primed."},
  {t:"Blocks downstream channels and shields the rest of the muscle", correct:true, why:"The sustained depolarization blocks downstream channels and shields the rest of the muscle."},
  {t:"Competes with acetylcholine without opening the channel", correct:false, why:"Binding without opening the channel describes curare-like (non-depolarizing) drugs."},
  {t:"Rapid metabolism of the drug at the synapse", correct:false, why:"Rapid metabolism is a feature of acetylcholine; succinylcholine is not metabolized effectively at the synapse."}],
 teach:"Acetylcholine produces muscle tension through repetitive firing, is quickly metabolized, and lets the motor end plate repolarize (re-prime). Succinylcholine has a longer synaptic half-life, so it causes a prolonged depolarization of the motor end plate that blocks downstream channels and shields the rest of the muscle: this is the state of depolarizing blockade.",
 quote:"it's gonna prolong that depolarization of the motor end plate and you can't reset things you're gonna be stuck in this process.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 21–22; transcript 10/5"},

{id:"L08-019", lecture:"L08", prof:"Gottlieb", tier:"new", level:1, topic:"L08", sub:"sch", skill:"recall", multi:true,
 concept:"sch-adrs", tags:["druglist", "succinylcholine"], source:"both",
 stem:"Which are adverse drug reactions (ADRs) of succinylcholine? Select all that apply.",
 options:[
  {t:"Hyperkalemia", correct:true, why:"Opening Nm channels lets Na+ in and K+ out, so muscle cells lose K+ (and gain Ca++ and Na+) and plasma K+ rises."},
  {t:"Hypertension and arrhythmias", correct:true, why:"At high doses or with prolonged infusion it opens ganglionic Nn receptors, driving both the sympathetic (SNS) and parasympathetic (PNS) outflow: hypertension and arrhythmias."},
  {t:"Post-operative muscle pain", correct:true, why:"Myalgia follows the unsynchronized contractions of the muscle fibers while the end plate is held depolarized."},
  {t:"Histamine release with marked hypotension", correct:false, why:"Histamine release with marked hypotension is an ADR of curare-like drugs, most of all atracurium, not of a depolarizing agonist."},
  {t:"Nausea and depression", correct:false, why:"Nausea and depression follow from varenicline at brain α4/β2 receptors; succinylcholine acts at Nm and, at high doses, ganglionic Nn."}],
 teach:"Succinylcholine ADRs: hyperkalemia (muscle cells lose K+ and gain Ca++ and Na+), cardiovascular effects (hypertension and arrhythmias, from stimulation of ganglia), and post-operative muscle pain (myalgia from unsynchronized contractions). Because of the hyperkalemia risk, it is avoided in renal-deficient and dehydrated patients.",
 quote:"as you open those nicotinic channels, sodium comes in what gets out potassium, so they may get hyperkalemia",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 25; transcript 10/5"},

{id:"L08-020", lecture:"L08", prof:"Gottlieb", tier:"new", level:3, ladder:"succinylcholine", ladderName:"Succinylcholine, halothane and dantrolene", topic:"L08", sub:"sch", skill:"apply",
 concept:"sch-halothane-mh-dantrolene", tags:["succinylcholine"], source:"both",
 stem:"During surgery a patient receives halothane and succinylcholine and develops a rising body temperature from skeletal muscle heat production. Which drug is given, and how does it act?",
 options:[
  {t:"Dantrolene: ryanodine receptor antagonist", correct:true, why:"The drug–drug interaction (DDI) causes malignant hyperthermia from abnormal Ca++ release; dantrolene blocks the ryanodine receptor and decreases intracellular Ca++."},
  {t:"Neostigmine: acetylcholinesterase inhibitor", correct:false, why:"Neostigmine raises acetylcholine to reverse curare-like drugs; more acetylcholine does not stop the Ca++ release behind malignant hyperthermia."},
  {t:"Atropine: M1, M2 and M3 antagonist", correct:false, why:"Atropine treats muscarinic excess (organophosphates), not Ca++ release in muscle."},
  {t:"Pralidoxime: cholinesterase reactivator", correct:false, why:"Pralidoxime reactivates acetylcholinesterase after organophosphate poisoning; it has no effect on Ca++ release from muscle stores."},
  {t:"Rocuronium: competitive Nm antagonist", correct:false, why:"A non-depolarizing blocker does not stop the abnormal Ca++ release from muscle stores."}],
 teach:"Succinylcholine with inhaled anesthetics such as halothane is a drug–drug interaction that can cause malignant hyperthermia. It is caused by abnormal release of Ca++ from stores in skeletal muscle and skeletal muscle heat production. Dantrolene is an antagonist at the ryanodine receptor and decreases intracellular Ca++.",
 quote:"So by blocking that, uh, we can prevent that increase in intracellular calcium.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 26; transcript 10/5"},

{id:"L08-021", lecture:"L08", prof:"Gottlieb", tier:"new", level:2, ladder:"curare", ladderName:"Curare-like paralysis and its reversal", topic:"L08", sub:"curare", skill:"apply",
 concept:"curare-no-anesthesia", tags:[], source:"both",
 stem:"A patient is given rocuronium during surgery, but the general anesthetic is omitted. What is the patient most likely to experience?",
 options:[
  {t:"Paralysis while still awake", correct:true, why:"Curare-like drugs relax skeletal muscle and have no CNS effect; without the anesthetic the patient is paralyzed but can feel and hear."},
  {t:"Sleep without muscle relaxation", correct:false, why:"Rocuronium does not cross the blood–brain barrier, so it cannot cause sleep; it blocks Nm at skeletal muscle and paralyzes."},
  {t:"Muscle cramps and hyperkalemia", correct:false, why:"Hyperkalemia and unsynchronized contractions are succinylcholine effects."},
  {t:"Sleep and paralysis", correct:false, why:"Rocuronium has no CNS effect, so it gives paralysis only; sleep comes from the general anesthetic, which was omitted."}],
 teach:"Non-depolarizing agents (curare-like drugs) are used as an adjuvant in surgical anesthesia to relax skeletal muscle, not as anesthetics, and have no central nervous system (CNS) effect. Given alone they leave a patient paralyzed, unable to move, talk or blink, while still able to feel and hear. He described lawsuits in which the anesthetic was forgotten.",
 quote:"It does not put people to sleep. It just paralyze them, so they can hear.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 27, 32; transcript 10/1; transcript 10/5"},

{id:"L08-022", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"curare", skill:"recall", multi:true,
 concept:"curare-like-members", tags:["druglist"], source:"both",
 stem:"Which drugs are non-depolarizing (curare-like) competitive antagonists at the muscle nicotinic (Nm) receptor? Select all that apply.",
 options:[
  {t:"Mivacurium", correct:true, why:"Mivacurium is listed with the non-depolarizing agents; it carries -cur-."},
  {t:"Vecuronium", correct:true, why:"Vecuronium carries -cur-: a competitive, reversible Nm antagonist like curare."},
  {t:"Pancuronium", correct:true, why:"Pancuronium carries -cur-: a competitive, reversible Nm antagonist like curare (it also blocks autonomic ganglia)."},
  {t:"Succinylcholine", correct:false, why:"Succinylcholine is the depolarizing Nm agonist; it opens the channel rather than competing with acetylcholine."},
  {t:"Neostigmine", correct:false, why:"Neostigmine inhibits acetylcholinesterase and raises acetylcholine; it is what reverses curare-like drugs, not one of them."},
  {t:"Edrophonium", correct:false, why:"Edrophonium is a short-acting cholinesterase inhibitor (it raises acetylcholine); it is not a receptor antagonist."}],
 teach:"Curare (tubocurarine) is the prototype. Mivacurium, vecuronium, rocuronium, pancuronium (and atracurium, cisatracurium in the comparison table) are curare-like: any drug with -cur- in the middle has the same mechanism and site of action. They are competitive antagonists that stop nicotinic ion channels from opening, causing paralysis.",
 quote:"However, if you know that it is a C U R in the middle, it doesn't matter if it's vecuronio, Rocuronio, Pencuronio. They're all the same.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 19, 27; transcript 10/1; transcript 10/5"},

{id:"L08-023", lecture:"L08", prof:"Gottlieb", tier:"new", level:2, ladder:"curare", ladderName:"Curare-like paralysis and its reversal", topic:"L08", sub:"curare", skill:"recall",
 concept:"curare-competitive-reversible", tags:[], source:"both",
 stem:"Curare occupies the same binding site on the muscle nicotinic (Nm) receptor that acetylcholine (ACh) binds to. Which statement about this block is CORRECT?",
 options:[
  {t:"A higher ACh level can outcompete curare", correct:true, why:"Curare is a competitive, reversible antagonist, so enough ACh can outcompete it; this is why an acetylcholinesterase inhibitor reverses it."},
  {t:"The block is covalent and cannot be overcome", correct:false, why:"A covalent, irreversible bond describes organophosphates at acetylcholinesterase; curare binds and then comes off."},
  {t:"Curare opens the channel before blocking it", correct:false, why:"Opening the channel first is succinylcholine; curare has affinity but no efficacy."},
  {t:"Curare lowers ACh release from the nerve", correct:false, why:"Lowering ACh release is botulinum toxin; curare acts at the postsynaptic receptor."},
  {t:"Curare speeds the breakdown of ACh", correct:false, why:"Curare does not act on acetylcholinesterase; it occupies the receptor's binding site."}],
 teach:"Curare binds the α subunits of the Nm receptor at the acetylcholine site and has affinity but no efficacy, so acetylcholine cannot bind and open the channel. The block is competitive and reversible: a higher acetylcholine level still reaches the same maximum effect. The body cannot release enough acetylcholine to outcompete curare, so an acetylcholinesterase inhibitor is given to raise synaptic acetylcholine and reverse the block.",
 quote:"So it's not gonna affect the ability of acetylcholine to get to the the max, but it's gonna require a higher dose.",
 note:"Slide 29 shows this block as a rightward shift of the acetylcholine dose–response curve with the same maximum. On 10/5 he said Exam 2 will not have any dose–response curves, so the question asks about the competitive block in words.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 28–29; transcript 10/5"},

{id:"L08-024", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"curare", skill:"recall",
 concept:"curare-like-shared-moa", tags:["druglist"], source:"both",
 stem:"Pancuronium, rocuronium, vecuronium and atracurium all have -cur- in their names. What do they share? (Nm = muscle nicotinic receptor)",
 options:[
  {t:"Competitive, reversible Nm antagonism causing paralysis", correct:true, why:"Any drug with -cur- in the middle is curare-like: a competitive, reversible Nm antagonist, and blocking Nm causes paralysis."},
  {t:"Depolarizing Nm agonism causing fasciculations", correct:false, why:"Depolarizing agonism with fasciculations before relaxation is succinylcholine; the -cur- drugs bind Nm without opening it."},
  {t:"Irreversible acetylcholinesterase inhibition at all synapses", correct:false, why:"Irreversible (covalent) enzyme inhibition is the organophosphates; the -cur- drugs bind the Nm receptor reversibly."},
  {t:"Partial agonism at α4/β2 receptors in the brain", correct:false, why:"Partial agonism at brain α4/β2 receptors is varenicline; the -cur- drugs are antagonists at skeletal muscle Nm."},
  {t:"Sedation and loss of memory during surgery", correct:false, why:"Curare-like drugs do not cross the blood–brain barrier; they do not put the patient to sleep, so an anesthetic is still needed."}],
 teach:"Any drug with -cur- in the middle is curare-like, with an identical mechanism of action and site of action, so knowing one means knowing them all. They are competitive, reversible antagonists at the Nm receptor of skeletal muscle, and blocking Nm causes paralysis. They differ in side effects (pancuronium blocks autonomic ganglia and is linked to tachycardia; atracurium has the most histamine release), but the shared mechanism is the part he set for Exam 2.",
 quote:"But for our purpose on exam two, all I need you to know is that any karate-like drug is what? A competitive, reversible NM antagonist, and by blocking the NM, what are you gonna get? Paralysis, right?",
 note:"Before the 10/5 lecture this question asked which curare-like drug blocks autonomic ganglia (pancuronium, slides 30 and 32). On 10/5 he said that for Exam 2 all he needs is that any curare-like drug is a competitive, reversible Nm antagonist that causes paralysis.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 19, 27, 30, 32; transcript 10/5"},

{id:"L08-025", lecture:"L08", prof:"Gottlieb", tier:"new", level:1, ladder:"curare", ladderName:"Curare-like paralysis and its reversal", topic:"L08", sub:"curare", skill:"recall",
 concept:"curare-adr-respiratory", tags:[], source:"both",
 stem:"What is the most common adverse drug reaction (ADR) of curare-like drugs?",
 options:[
  {t:"Respiratory paralysis", correct:true, why:"Paralysis progresses to the diaphragm, and the patient cannot breathe."},
  {t:"Hyperkalemia", correct:false, why:"Hyperkalemia is a succinylcholine ADR: open nicotinic channels let K+ out."},
  {t:"Sedation and amnesia", correct:false, why:"Curare-like drugs do not cross the blood–brain barrier and have no CNS effect."},
  {t:"Malignant hyperthermia", correct:false, why:"Malignant hyperthermia is the succinylcholine plus halothane drug–drug interaction."},
  {t:"Diarrhea and salivation", correct:false, why:"Diarrhea and salivation are DUMBBELSS effects of cholinesterase inhibitors."}],
 teach:"Curare-like drugs paralyze skeletal muscle progressively, and paralysis of the diaphragm stops breathing: respiratory paralysis is the most common ADR. Other ADRs depend on the drug: tachycardia with pancuronium (ganglionic block) and histamine release with atracurium (bronchial spasms, marked hypotension). They do not cross the blood–brain barrier and have no central nervous system (CNS) effect.",
 quote:"The most common side effects would be paralysis of the diaphragm, so they can't breathe, and that's gonna be bad.",
 note:"Before the 10/5 lecture this question asked which curare-like drug has the most histamine release (atracurium, slide 30). On 10/5 he said Exam 2 needs only the shared curare-like mechanism, so the drug-by-drug side effects are kept in the explanation only.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 27, 32; transcript 10/5"},

{id:"L08-026", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"recall", multi:true,
 concept:"ache-inhibitor-moa-uses", tags:[], source:"both",
 stem:"Cholinesterase inhibitors bind the active site of acetylcholinesterase and antagonize the enzyme. Which effects are they used for? Select all that apply.",
 options:[
  {t:"Increasing transmission", correct:true, why:"Blocking breakdown potentiates acetylcholine and increases transmission."},
  {t:"Increasing PNS tone", correct:true, why:"More acetylcholine at muscarinic synapses increases parasympathetic (PNS) tone."},
  {t:"Reversing curare effects", correct:true, why:"Raising acetylcholine outcompetes curare-like drugs at the Nm receptor."},
  {t:"Decreasing central cholinergic activity", correct:false, why:"They raise acetylcholine in the brain too (the Alzheimer's use), so central cholinergic activity increases, not decreases."},
  {t:"Blocking acetylcholine release", correct:false, why:"Blocking acetylcholine release is botulinum toxin's action (it cleaves SNARE proteins); cholinesterase inhibitors raise acetylcholine in the synapse."}],
 teach:"Cholinesterase inhibitors bind to the active site of acetylcholinesterase and antagonize the enzyme. They differ in their pharmacokinetics (volume of distribution, duration of action). They potentiate acetylcholine: increasing transmission, increasing PNS tone, increasing central cholinergic activity, and reversing curare effects.",
 quote:"So a better choice is let's give a drug that blocks that blocks the breakdown of acetylcholine and thus increase its synaptic synaptic level, and that's what we do for overdose, OK?",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 33–34; transcript 10/5"},

{id:"L08-027", lecture:"L08", prof:"Gottlieb", tier:"new", level:2, ladder:"organophosphate", ladderName:"Organophosphate poisoning and its antidotes", topic:"L08", sub:"ache", skill:"apply",
 concept:"ache-inhibitor-potency-up", tags:["poll"], source:"both",
 stem:"What happens to the potency of acetylcholine when an acetylcholinesterase (AChE) inhibitor is given?",
 options:[
  {t:"More potent; it is not broken down", correct:true, why:"Acetylcholine is not broken down, so more of it stays at the receptor for longer and a smaller dose gives the same response."},
  {t:"Less potent; the receptor is blocked", correct:false, why:"Blocking the receptor is what curare does; an AChE inhibitor acts on the enzyme, not the receptor."},
  {t:"Unchanged; the drug acts on the enzyme", correct:false, why:"Acting on the enzyme is exactly why acetylcholine potency changes; it is an indirect effect."},
  {t:"Less efficacious; its maximum falls", correct:false, why:"A lower maximum is irreversible antagonism at the receptor; the enzyme inhibitor helps acetylcholine."}],
 teach:"With AChE inhibited, acetylcholine is not split into choline and acetate, so it stays at the synapse longer and more of it binds the receptor: acetylcholine becomes more potent. This is the reason AChE inhibitors are given in myasthenia gravis, where patients are losing nicotinic receptors. AChE inhibitors are called indirect antagonists because they act somewhere other than the receptor.",
 quote:"Now acetylcholine is gonna stay around that synapse for a much longer period of time and it's gonna make it more potent",
 note:"Slide 36 shows this as a leftward shift of the acetylcholine dose–response curve. On 10/5 he said Exam 2 will not have any dose–response curves, so the question asks about potency in words, the way he asked it on 10/1.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 35–36; transcript 10/1; transcript 10/5"},

{id:"L08-028", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"apply",
 concept:"ache-site-anywhere", tags:[], source:"both",
 stem:"Where do acetylcholinesterase inhibitors act?",
 options:[
  {t:"Only at the neuromuscular junction", correct:false, why:"They also act in the CNS (few synapses) and anywhere else acetylcholine is released."},
  {t:"Only in the brain", correct:false, why:"They also act in the periphery, including the neuromuscular junction."},
  {t:"Anywhere acetylcholine is released", correct:true, why:"Ganglia, muscarinic organs, the neuromuscular junction and some CNS synapses all have acetylcholine and the enzyme."},
  {t:"Only at adrenergic synapses", correct:false, why:"Adrenergic synapses release norepinephrine, not acetylcholine."}],
 teach:"Acetylcholinesterase inhibitors act at synapses in the central nervous system (CNS) (few), in the periphery at the neuromuscular junction, and anywhere acetylcholine is released, including autonomic ganglia and muscarinic organs. That is why their ADRs are those of excess acetylcholine (DUMBBELSS) plus GI and CNS effects.",
 quote:"What would be the sites of action of this drug? Everywhere acetylcholine is released, right?",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 37; transcript 10/5"},

{id:"L08-029", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"apply",
 concept:"neostigmine-mg-choice", tags:["druglist"], source:"both",
 stem:"A family member has just been diagnosed with myasthenia gravis. Which drug is the best choice for treatment?",
 options:[
  {t:"Neostigmine", correct:true, why:"Neostigmine is a reversible cholinesterase inhibitor that does not cross the blood–brain barrier, so it acts at skeletal muscle, where the myasthenia gravis problem is."},
  {t:"Physostigmine", correct:false, why:"Physostigmine would work, but it crosses the blood–brain barrier and adds central effects such as nausea and vomiting with no added benefit for the muscle."},
  {t:"Edrophonium", correct:false, why:"Edrophonium is very quick on and very quick off; it answers the diagnostic question and is not used to treat."},
  {t:"Succinylcholine", correct:false, why:"Succinylcholine is a depolarizing Nm agonist that causes paralysis; it would worsen the muscle weakness."},
  {t:"Donepezil", correct:false, why:"Donepezil is lipid soluble and is chosen for Alzheimer's disease, where the target is the brain; the myasthenia gravis problem is at skeletal muscle."}],
 teach:"Myasthenia gravis is an autoimmune disease against the muscle nicotinic (Nm) receptors; patients are fine in the morning and get weaker as the day goes on. Edrophonium, an IV drug with a very small volume of distribution, is used only to answer whether the patient has myasthenia gravis. For treatment, a quaternary cholinesterase inhibitor that stays in the periphery (neostigmine or pyridostigmine) is preferred over physostigmine, which crosses the blood–brain barrier.",
 quote:"But for myasthenia gravis patients, let's keep the one that stays in the periphery",
 note:"Before the 10/5 lecture this question asked what edrophonium is used for (slide 38). On 10/5 he said that for the exam he is not too worried about edrophonium, only about the drugs that will be dispensed to patients, and he asked this question (physostigmine or neostigmine) instead.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 38–39; transcript 10/5"},

{id:"L08-030", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"tell",
 concept:"physo-vs-neo-bbb", tags:["druglist"], source:"both",
 stem:"Which statement correctly separates physostigmine from neostigmine and pyridostigmine?",
 options:[
  {t:"Only physostigmine, a tertiary amine, crosses the blood–brain barrier", correct:true, why:"Physostigmine readily penetrates the central nervous system (CNS); neostigmine and pyridostigmine are quaternary amines that do not cross the blood–brain barrier (BBB)."},
  {t:"Physostigmine is quaternary; the others are tertiary and enter the CNS", correct:false, why:"Reversed: physostigmine is the tertiary amine that enters the CNS; neostigmine and pyridostigmine are quaternary and stay out."},
  {t:"Physostigmine is irreversible; the others are reversible", correct:false, why:"All three are reversible cholinesterase inhibitors with a longer duration of action; the irreversible ones are the organophosphates."},
  {t:"All three cross the BBB equally", correct:false, why:"Only physostigmine (tertiary) readily crosses; the quaternary neostigmine and pyridostigmine do not cross the BBB."},
  {t:"Physostigmine is a direct Nm agonist; the others inhibit the enzyme instead", correct:false, why:"All three inhibit acetylcholinesterase; none of them binds the Nm receptor directly."}],
 teach:"Physostigmine is a tertiary amine that readily penetrates the CNS; it is the drug of choice for poisoning by anti-muscarinic agents such as atropine. Pyridostigmine and neostigmine are quaternary amines that do not cross the BBB; they treat myasthenia gravis and reverse curare-like overdose. All three are reversible with a longer duration of action than edrophonium.",
 quote:"Physostigmine (Antilirium): Tertiary amine and readily Penetrate the CNS … PyriDOstigmine (Mestinon) & Neostigmine (Prostigmin): Quaternary amine and DO NOT cross the BBB",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Cholinesterase regenerator compounds; Ganglion-Blocking Drugs — Central nervous system (p. 10–11 of 14)", t:"Drugs with positively charged quaternary ammonium groups, such as pralidoxime, do not enter the central nervous system. Tertiary or secondary amines such as atropine and mecamylamine cross the blood–brain barrier and act centrally."}],
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 39; transcript 10/5"},

{id:"L08-031", lecture:"L08", prof:"Gottlieb", tier:"new", level:3, ladder:"atropine-poisoning", ladderName:"Atropine poisoning and physostigmine", topic:"L08", sub:"ache", skill:"apply",
 concept:"physostigmine-antimuscarinic-poisoning", tags:["druglist"], source:"both",
 stem:"A patient has poisoning from an anti-muscarinic agent (atropine), with central and peripheral signs. Which drug is the drug of choice?",
 options:[
  {t:"Neostigmine", correct:false, why:"Neostigmine is quaternary and does not cross the blood–brain barrier, so it misses the central signs."},
  {t:"Physostigmine", correct:true, why:"Physostigmine is a tertiary amine that readily penetrates the CNS; it is the drug of choice for anti-muscarinic poisoning."},
  {t:"Pralidoxime", correct:false, why:"Pralidoxime reactivates acetylcholinesterase after organophosphate poisoning; in atropine poisoning the enzyme works, and the problem is blocked muscarinic receptors."},
  {t:"Edrophonium", correct:false, why:"Edrophonium is very short acting (quick on, quick off) and used only for diagnosis; it cannot sustain the rise in acetylcholine needed."},
  {t:"Pyridostigmine", correct:false, why:"Pyridostigmine is quaternary and does not cross the blood–brain barrier, so it misses the central signs."}],
 teach:"Raising acetylcholine with a cholinesterase inhibitor overcomes muscarinic blockade by atropine. Physostigmine is chosen because, as a tertiary amine, it penetrates the central nervous system (CNS) and reaches the central effects as well. Neostigmine and pyridostigmine are quaternary and stay outside the brain.",
 quote:"overdose on, say, atropine, which you're gonna learn is a muscarinic antagonist, and it's called severe anti-dumbbells. So we can give that, that goes everywhere.",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Adverse Effects (p. 10 of 14)", t:"Atropine overdose causes dry mouth, mydriasis, tachycardia, hot flushed skin, agitation and delirium. Katzung states that poison control experts discourage physostigmine for atropine overdose and prefer symptomatic management; when physostigmine is used, small doses are given slowly IV."}],
 note:"Katzung Ch. 8 says poison control experts discourage physostigmine for atropine overdose; the slide and the 10/5 lecture both name physostigmine as the antidote for atropine overdose, so the key follows them.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 39; transcript 10/5"},

{id:"L08-032", lecture:"L08", prof:"Gottlieb", tier:"new", level:3, ladder:"curare", ladderName:"Curare-like paralysis and its reversal", topic:"L08", sub:"ache", skill:"apply",
 concept:"neostigmine-reverse-curare-mg", tags:["druglist"], source:"both",
 stem:"After surgery, a patient still has muscle weakness from a curare-like overdose. Which drug reverses it?",
 options:[
  {t:"Succinylcholine", correct:false, why:"Succinylcholine is a depolarizing Nm agonist; it adds its own paralysis instead of restoring transmission."},
  {t:"Dantrolene", correct:false, why:"Dantrolene treats malignant hyperthermia by blocking the ryanodine receptor."},
  {t:"Neostigmine", correct:true, why:"Neostigmine inhibits acetylcholinesterase at the periphery, so acetylcholine builds up at the Nm receptor and outcompetes the reversible curare-like drug."},
  {t:"Botulinum toxin", correct:false, why:"Botulinum toxin blocks acetylcholine release and causes muscle relaxation."},
  {t:"Atropine", correct:false, why:"Atropine blocks muscarinic receptors; the curare-like block is at the nicotinic Nm receptor, so atropine does not restore muscle strength."}],
 teach:"Curare-like drugs are competitive and reversible, so raising acetylcholine at the muscle nicotinic receptor overcomes the block. Neostigmine and pyridostigmine are quaternary cholinesterase inhibitors that act peripherally (no BBB crossing), used to reverse curare-like overdose and to treat myasthenia gravis.",
 quote:"So neo stigamine, which does not cross the blood brain barrier but can increase the levels of acetylcholine in the synapse of your skeletal muscle",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 33, 39; transcript 10/1; transcript 10/5"},

{id:"L08-033", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"recall",
 concept:"alzheimers-ache-inhibitors", tags:["druglist"], source:"both",
 stem:"Which statement about donepezil and rivastigmine is CORRECT?",
 options:[
  {t:"They are irreversible organophosphates", correct:false, why:"Donepezil and rivastigmine are reversible inhibitors with a longer duration of action; the covalent, irreversible inhibitors are the organophosphates."},
  {t:"They reverse the course of Alzheimer's disease", correct:false, why:"They treat early symptoms and slow the decline, but the disease keeps progressing; they do not reverse it."},
  {t:"They are lipophilic and cross the BBB", correct:true, why:"They are lipophilic, cross the blood–brain barrier (BBB), have high affinity for AChE and treat early symptoms of Alzheimer's disease."},
  {t:"They are quaternary amines", correct:false, why:"Quaternary amines (neostigmine, pyridostigmine) are charged and do not cross the BBB; donepezil and rivastigmine are lipophilic and do."},
  {t:"They block nicotinic receptors in the brain", correct:false, why:"They inhibit acetylcholinesterase, so acetylcholine rises in the brain; they do not block nicotinic receptors."}],
 teach:"Donepezil and rivastigmine are reversible acetylcholinesterase (AChE) inhibitors with a longer duration of action and high affinity for AChE. They are extremely lipid soluble and cross the BBB to raise acetylcholine in the brain. They treat early symptoms of Alzheimer's disease and slow the progression of cognitive, functional and behavioral deficits, but do not reverse the course of the disease. Any drug ending in -stigmine, and donepezil, inhibits the cholinesterase enzyme.",
 quote:"And those drugs are extremely lipid soluble. They will get to the brain",
 note:"Slide 40 also lists galantamine (Razadyne). On 10/5 he said that for the exam he only needs rivastigmine and donepezil, the most prescribed of the three, so galantamine was removed from this question.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 40; transcript 10/1; transcript 10/5"},

{id:"L08-034", lecture:"L08", prof:"Gottlieb", tier:"new", level:1, ladder:"cholinesterase-inhibitor", ladderName:"Cholinesterase inhibitors: DUMBBELSS, add-ons and atropine", topic:"L08", sub:"ache", skill:"recall",
 concept:"ache-inhibitor-adrs", tags:[], source:"both",
 stem:"A patient takes a reversible cholinesterase inhibitor such as donepezil. Which adverse drug reactions (ADRs) are most likely?",
 options:[
  {t:"Anti-DUMBBELSS: dry mouth, urinary retention", correct:false, why:"Anti-DUMBBELSS (dry mouth, urinary retention) comes from blocking muscarinic receptors (atropine); a cholinesterase inhibitor raises acetylcholine, the opposite."},
  {t:"DUMBBELSS, insomnia, dizziness and falling", correct:true, why:"Excess acetylcholine at synapses gives DUMBBELSS; GI and CNS effects (insomnia and agitation, dizziness, falling) are each over 10%."},
  {t:"Hyperkalemia and myalgia", correct:false, why:"Hyperkalemia and myalgia come from succinylcholine opening Nm channels; a cholinesterase inhibitor raises acetylcholine everywhere, giving DUMBBELSS."},
  {t:"Histamine release and hypotension", correct:false, why:"Histamine release with hypotension is a curare-like (atracurium) ADR, not an effect of excess acetylcholine."}],
 teach:"Cholinesterase inhibitor ADRs are symptoms of excess acetylcholine at synapses: DUMBBELSS (diarrhea, urination, miosis, bradycardia, bronchial constriction, emesis, lacrimation, salivation, stimulation). GI effects and CNS effects (insomnia and agitation, dizziness leading to falling) each occur in more than 10% of patients. GI = gastrointestinal; CNS = central nervous system.",
 quote:"patients may have insomnia, agitation, uh, and they also have a high risk of falling",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 41; transcript 10/1; transcript 10/5"},

{id:"L08-035", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"op", skill:"tell",
 concept:"organophosphate-irreversible", tags:[], source:"both",
 stem:"What separates organophosphates from neostigmine as acetylcholinesterase inhibitors?",
 options:[
  {t:"Organophosphates bind covalently (irreversible)", correct:true, why:"Organophosphates bind the enzyme covalently; the bond is very stable and slow, so the inhibition is irreversible."},
  {t:"Organophosphates bind the nicotinic receptor directly", correct:false, why:"Organophosphates bind acetylcholinesterase, not the receptor; they raise acetylcholine by blocking its breakdown."},
  {t:"Organophosphates are poorly absorbed through skin", correct:false, why:"They are well absorbed from skin, lung, gut and conjunctiva."},
  {t:"Organophosphates have a short duration of action", correct:false, why:"Organophosphates bind covalently, so their action lasts; a short, quickly reversible action describes edrophonium."},
  {t:"Neostigmine is the irreversible one", correct:false, why:"Neostigmine binds the enzyme reversibly; the covalent, irreversible bond belongs to the organophosphates."}],
 teach:"Organophosphates form a covalent bond with acetylcholinesterase that is very stable and slow, so they are irreversible; they irreversibly phosphorylate cholinesterases. They are used as insecticides (malathion, metabolized in vertebrates; parathion) and as nerve gases (soman, sarin, tabun), and are well absorbed from skin, lung, gut and conjunctiva. Neostigmine, physostigmine, pyridostigmine and edrophonium are reversible.",
 quote:"So these drugs, they're going to form covalent bonds and as we discussed before, if you form covalent bonds that tells you they are irreversible, right?",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 42–43; transcript 10/5"},

{id:"L08-036", lecture:"L08", prof:"Gottlieb", tier:"new", level:1, ladder:"organophosphate", ladderName:"Organophosphate poisoning and its antidotes", topic:"L08", sub:"op", skill:"apply", multi:true,
 concept:"organophosphate-toxicity", tags:[], source:"both",
 stem:"A farm worker is exposed to parathion. Which toxic effects are expected? Select all that apply.",
 options:[
  {t:"Tachycardia and hypertension", correct:true, why:"Stimulation of SNS ganglia gives tachycardia and hypertension."},
  {t:"Muscle cramps, weakness, respiratory paralysis", correct:true, why:"Stimulation of the neuromuscular junction (NMJ) gives cramps, weakness and respiratory paralysis."},
  {t:"Confusion and seizures", correct:true, why:"Stimulation of the CNS gives depression, agitation, confusion and seizures."},
  {t:"Histamine release with bronchial spasm", correct:false, why:"Histamine release with bronchial spasm is an atracurium (curare-like) ADR; organophosphates act by raising acetylcholine."},
  {t:"Blocked acetylcholine release", correct:false, why:"Blocking acetylcholine release is botulinum toxin; organophosphates block acetylcholine breakdown, so it accumulates."}],
 teach:"Organophosphates irreversibly phosphorylate cholinesterases, so acetylcholine accumulates everywhere it is released. Toxicity: stimulation of SNS ganglia (tachycardia, hypertension), stimulation of the NMJ (muscle cramps and weakness, respiratory paralysis) and stimulation of the CNS (depression, agitation, confusion, seizures). SNS = sympathetic nervous system; CNS = central nervous system.",
 quote:"You have the stimulation of the sympathetic nervous system in the ganglia, the parasympathetic system in the ganglia, the CNS in the brain, the skeletal muscle into paralysis.",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Cholinergic Poisoning (p. 9–10 of 14)", t:"Both the nicotinic and the muscarinic effects of cholinesterase inhibitors can be life-threatening. There is no effective way to directly reverse the nicotinic effects, because nicotinic agonists and antagonists both block transmission."}],
 note:"In lecture he also listed bradycardia among the DUMBBELSS effects of organophosphate poisoning, since both sympathetic and parasympathetic ganglia are stimulated; the slide lists tachycardia under SNS ganglia, and this question keys the slide's list.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 43; transcript 10/5"},

{id:"L08-037", lecture:"L08", prof:"Gottlieb", tier:"new", level:3, ladder:"organophosphate", ladderName:"Organophosphate poisoning and its antidotes", topic:"L08", sub:"op", skill:"apply",
 concept:"organophosphate-antidote", tags:[], source:"both",
 stem:"Which pair of drugs treats poisoning with an organophosphate acetylcholinesterase inhibitor such as sarin?",
 options:[
  {t:"Atropine and pralidoxime", correct:true, why:"Atropine (M1, M2, M3 antagonist) reduces acetylcholine effects at muscarinic sites; pralidoxime reactivates the phosphorylated enzyme."},
  {t:"Neostigmine and physostigmine", correct:false, why:"These are cholinesterase inhibitors; they would add to the acetylcholine excess."},
  {t:"Succinylcholine and dantrolene", correct:false, why:"Succinylcholine is a depolarizing blocker; dantrolene treats malignant hyperthermia."},
  {t:"Varenicline and donepezil", correct:false, why:"Donepezil is another cholinesterase inhibitor and would add to the acetylcholine excess; varenicline acts at brain α4/β2 receptors and treats nothing here."},
  {t:"Botulinum toxin and rocuronium", correct:false, why:"Both reduce Nm signaling (less release, receptor block), but neither removes the excess acetylcholine at muscarinic sites or reactivates the enzyme."}],
 teach:"Treatment of organophosphate poisoning has two parts. The anti-muscarinic atropine (M1, M2 and M3 antagonist; anti-DUMBBELSS) reduces the effects of acetylcholine at muscarinic sites. The cholinesterase reactivator pralidoxime (2-PAM) dephosphorylates the enzyme, splitting off the oxime-phosphonate and leaving the regenerated enzyme. Pralidoxime has to be given early (he said within an hour of exposure) before the bond becomes too tight to break; atropine then manages the DUMBBELSS until new enzyme is made.",
 quote:"So we're gonna give the Tupam to try to break some of those covalent bonds, and then we're gonna give atropine to manage the patient after that.",
 reading:[{src:"Katzung 16e, Ch. 8", sec:"Cholinergic Poisoning — Antimuscarinic therapy; Cholinesterase regenerator compounds (p. 10 of 14)", t:"A tertiary amine, preferably atropine, is used to treat both central and peripheral muscarinic effects of organophosphates, and large repeated doses may be needed. Oximes such as pralidoxime have high affinity for the phosphorus atom and regenerate active enzyme if the complex has not aged; pralidoxime works best at skeletal neuromuscular junctions and does not enter the CNS because it is a quaternary compound."}],
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 44; transcript 10/5"},

{id:"L08-038", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"op", skill:"recall",
 concept:"echothiophate-glaucoma", tags:["druglist"], source:"both",
 stem:"Echothiophate lowers intraocular pressure (IOP) in glaucoma. What is its mechanism?",
 options:[
  {t:"AChE inhibitor; ↑ ACh at ciliary M3", correct:true, why:"Echothiophate inhibits acetylcholinesterase (AChE), raising acetylcholine (ACh) and M3 activation in the ciliary muscle, which increases aqueous humor outflow."},
  {t:"M3 antagonist in the ciliary muscle", correct:false, why:"Echothiophate increases M3 activation in the ciliary muscle; an M3 antagonist would block the outflow it is meant to increase."},
  {t:"Reversible Nm agonist in the eye", correct:false, why:"Echothiophate acts on the enzyme, not on a receptor, and the eye effect it produces is through M3, not a nicotinic receptor."},
  {t:"Blocks acetylcholine release in the eye", correct:false, why:"Blocking acetylcholine release is botulinum toxin; echothiophate raises acetylcholine by blocking its breakdown."},
  {t:"α4/β2 partial agonist", correct:false, why:"α4/β2 partial agonism is varenicline at brain Nn receptors; it has no action at the ciliary muscle."}],
 teach:"Echothiophate is an organophosphate inhibitor of acetylcholinesterase that raises acetylcholine. More M3 activation in the ciliary muscle lowers IOP by increasing aqueous humor outflow. It is quaternary and positively charged, so it is poorly absorbed. ADRs: miosis and blurred vision, lacrimation, stinging and redness of the eyes.",
 quote:"So by giving an acetylcholinesterase enzyme antagonist. We're gonna block the breakdown of acetylcholine on those M3s on that canal of slam or in the trabecular mesh, and that's gonna open up those tubes and allow more aqueous humor to come out",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 45; transcript 10/5"},

{id:"L08-039", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"botox", skill:"recall",
 concept:"botulinum-moa", tags:["druglist"], source:"both",
 stem:"How does botulinum toxin cause muscle relaxation?",
 options:[
  {t:"It cleaves SNARE proteins", correct:true, why:"Its active fragments are endopeptidases that cleave SNARE proteins, so acetylcholine (ACh) cannot be released."},
  {t:"It competitively blocks the Nm receptor", correct:false, why:"Competitive Nm block is the curare-like mechanism at the postsynaptic receptor; botulinum toxin acts before the synapse."},
  {t:"It keeps the motor end plate depolarized", correct:false, why:"Prolonged depolarization of the end plate is succinylcholine phase I; botulinum toxin stops the acetylcholine that would depolarize it."},
  {t:"It inhibits acetylcholinesterase", correct:false, why:"Enzyme inhibition raises ACh; botulinum toxin lowers ACh release."},
  {t:"It blocks the ryanodine receptor", correct:false, why:"Blocking the ryanodine receptor (lowering Ca++ release in muscle) is dantrolene; botulinum toxin acts on the nerve terminal."}],
 teach:"Botulinum toxin prevents acetylcholine release from the presynaptic terminal by interfering with the machinery of transmitter release. Its active fragments are endopeptidases whose substrates are SNARE (SNAP receptor) proteins; cleaving specific sites on SNARE proteins stops docking, priming and exocytosis. Less acetylcholine release gives muscle relaxation; uses are cosmetic (crow's feet) and control of excessive drooling. Local injection also controls excessive sweating, and migraine prevention is an off-label use.",
 quote:"So Botox is an enzyme that breaks down the snare protein, and if you don't have the snare protein, your vesicles can't bind properly and thus you can't release the cetylcholine.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 46–50; transcript 10/5"},

{id:"L08-040", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"botox", skill:"tell",
 concept:"presynaptic-vs-postsynaptic-relaxants", tags:["botulinum"], source:"both",
 stem:"Which agent relaxes skeletal muscle by acting on the presynaptic terminal rather than on the postsynaptic receptor?",
 options:[
  {t:"Vecuronium", correct:false, why:"Vecuronium is a competitive antagonist at the postsynaptic muscle nicotinic receptor."},
  {t:"Succinylcholine", correct:false, why:"Succinylcholine is an agonist at the postsynaptic muscle nicotinic receptor."},
  {t:"Botulinum toxin", correct:true, why:"Botulinum toxin acts in the presynaptic terminal, cleaving SNARE proteins so acetylcholine cannot be released."},
  {t:"Tubocurarine", correct:false, why:"Tubocurarine (curare) is the prototype postsynaptic competitive antagonist."}],
 teach:"Three ways to relax or paralyze skeletal muscle appear here. Botulinum toxin acts presynaptically and prevents acetylcholine release. Succinylcholine acts postsynaptically as a depolarizing agonist. Curare-like drugs (tubocurarine, vecuronium, rocuronium and others) act postsynaptically as competitive antagonists.",
 quote:"So the only one that decreases the release of acetylcholine would be the Botox toxin.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 19, 46; transcript 10/5"},

{id:"L08-046", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"sch", skill:"recall", multi:true,
 concept:"sch-must-know-moa-soa", tags:["druglist", "succinylcholine"], source:"both",
 stem:"Which statements about succinylcholine and the muscle nicotinic (Nm) receptor are CORRECT? Select all that apply.",
 options:[
  {t:"It is an agonist that opens Nm ion channels", correct:true, why:"Succinylcholine is an agonist that depolarizes, opening the ion channels: that is its mechanism of action."},
  {t:"Its intended site of action is skeletal muscle", correct:true, why:"The goal is to open Nm in skeletal muscle and cause paralysis."},
  {t:"Prolonged infusion reaches autonomic ganglia", correct:true, why:"If it stays too long it acts at ganglionic Nn receptors and causes autonomic side effects (hypertension, arrhythmias)."},
  {t:"It is a competitive, reversible Nm antagonist", correct:false, why:"Competitive, reversible Nm antagonism is the curare-like mechanism."},
  {t:"It acts at α4/β2 receptors in the brain", correct:false, why:"α4/β2 in the brain is the varenicline site of action."},
  {t:"It blocks acetylcholine release from the nerve", correct:false, why:"Blocking acetylcholine release is botulinum toxin."}],
 teach:"For succinylcholine, the must-know points are the mechanism and the sites of action. It is an agonist that depolarizes (opens) the Nm ion channels of skeletal muscle and so causes paralysis. If the infusion goes on too long it reaches the neuronal nicotinic (Nn) receptors of the autonomic ganglia, and the mixed sympathetic and parasympathetic signals produce hypertension and arrhythmias.",
 quote:"You must know that a sucycholine is an agonist that depolarize or open those ion channels. That's the mechanism of action.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 19–20, 25; transcript 10/5"},

{id:"L08-047", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"curare", skill:"recall",
 concept:"curare-paralysis-order", tags:[], source:"both",
 stem:"A curare-like drug is given. In what order are the muscles paralyzed?",
 options:[
  {t:"Eyes, jaw, larynx → limbs and trunk → diaphragm", correct:true, why:"Paralysis starts at the eyes, jaw and larynx, moves to the extremities, and reaches the diaphragm last."},
  {t:"Diaphragm → limbs and trunk → eyes, jaw, larynx", correct:false, why:"The diaphragm is last; when it stops, breathing stops."},
  {t:"Diaphragm → eyes, jaw, larynx → limbs and trunk", correct:false, why:"The diaphragm is reached last, not first; when it stops, breathing stops."},
  {t:"All skeletal muscles at the same time", correct:false, why:"The paralysis is progressive: not all muscles are affected equally."}],
 teach:"Not all muscles are created equal: with curare-like drugs the paralysis is progressive, starting with the eyes, jaw and larynx, then the extremities (limbs and trunk), and finally the diaphragm. Paralysis of the diaphragm stops breathing, which is why respiratory paralysis is the dangerous ADR. ADR = adverse drug reaction.",
 quote:"You're gonna start with, you know, the, in this case, the eyes, the jaws, and the, the larynx, and then you go to the extremities, and eventually you can stop the diaphragm from being able to contract",
 note:"Slide 27 lists eyes, jaw and larynx; extremities; diaphragm without saying it is an order; on 10/5 he described it as the order of paralysis for curare-like drugs. For succinylcholine he gave a different order on 10/5 (large limbs first, then the face, then the diaphragm), which is not on a slide.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slide 27; transcript 10/5"},

{id:"L08-048", lecture:"L08", prof:"Gottlieb", tier:"new", topic:"L08", sub:"ache", skill:"apply",
 concept:"rivastigmine-mg-plus-ad", tags:["druglist"], source:"both",
 stem:"A patient has both myasthenia gravis and Alzheimer's disease. Which drug would you recommend?",
 options:[
  {t:"Neostigmine", correct:false, why:"Neostigmine does not cross the blood–brain barrier, so it treats the muscle weakness but not the Alzheimer's disease."},
  {t:"Rivastigmine", correct:true, why:"Rivastigmine crosses the blood–brain barrier well and also works all over the body, so one drug targets both the brain and skeletal muscle."},
  {t:"Edrophonium", correct:false, why:"Edrophonium is very quick on and very quick off and is used only for diagnosis."},
  {t:"Rocuronium", correct:false, why:"Rocuronium is a curare-like Nm antagonist that causes paralysis; it would worsen the myasthenia gravis."},
  {t:"Succinylcholine", correct:false, why:"Succinylcholine is a depolarizing Nm agonist that causes paralysis; it would worsen the myasthenia gravis."}],
 teach:"Cholinesterase inhibitors act anywhere acetylcholine is released; what separates them is whether they reach the brain. Neostigmine stays in the periphery and is preferred for myasthenia gravis alone. Rivastigmine is lipid soluble, crosses the blood–brain barrier and acts throughout the body, so with both diseases it covers the brain and the muscle.",
 quote:"Rivastigamine crosses the blood barrier quite well, but it works all over the body.",
 note:"He asked this aloud on 10/5 (\"which one would you prescribe or recommend, new or Riva?\") and answered rivastigmine because it targets two things.",
 cite:"PCOL-NMJ_PCOL_2026s_pptx.pdf slides 37, 39–40; transcript 10/5"}
);
