TOPICS.push({id:'L01', name:'Pharmacodynamics intro: drugs, receptors, potency', prof:'Gottlieb', lecture:'L01',
  cite:'Day 1 (9/22) — Pharmacodynamics-Day-1-2026s.pdf',
  subs:[
    {id:'intro', name:'Must know vs should know; relevance', cite:'slides ~7–~12'},
    {id:'nds', name:'Drug discovery and natural dietary supplements', cite:'slides ~13–~20'},
    {id:'potency', name:'Affinity, efficacy and potency', cite:'slides ~21–~27, ~37–~38'},
    {id:'theory', name:'Receptor theories and the two-state model', cite:'slides ~28–~29'},
    {id:'drugs', name:'Drugs, selectivity and drug classes', cite:'slides ~29–~33'},
    {id:'receptors', name:'Receptor classes', cite:'slides ~34–~36'},
    {id:'ion', name:'Ion channels', cite:'slides ~39–~48'},
    {id:'gpcr', name:'G protein–coupled receptors', cite:'slides ~49–~55'}
  ]});
QUESTIONS.push(
{id:'L01-001', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'tell',
 concept:'must-know-moa-should-know-soa', tags:['moa','soa'], source:'both',
 stem:'For drugs in this course, which pairing matches the item that must be known with the item that should be known?',
 options:[
  {t:'Must: mechanism of action (MOA); should: site of action (SOA)', correct:true, why:'The MOA (what the drug does to which receptor) is the must-know; the SOA (where the receptor is) is the should-know that lets you predict the rest.'},
  {t:'Must: site of action (SOA); should: mechanism of action (MOA)', correct:false, why:'Reverses the two tiers; the MOA is the starting point that must be known.'},
  {t:'Must: brand name; should: dose', correct:false, why:'Brand names and dose are listed as things Exam 1 will not test.'},
  {t:'Must: adverse drug reactions; should: route', correct:false, why:'Adverse reactions are predicted from MOA plus SOA; route is listed as not tested.'}],
 teach:'The must-know for every drug is its mechanism of action: which receptor it binds and whether it activates, inhibits or just binds. The should-know is the site of action, where that receptor is located. Knowing both lets you predict the effect, side effects, drug–drug interactions, contraindications and use without memorizing them.',
 quote:'there are going to be things that are going to tell you that you must know, and for this particular class in therapeutics it’s going to be the mechanism of action of the drugs... The things that you should know are going to be the sites of actions.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~7; transcript 9/22'},

{id:'L01-002', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'apply',
 concept:'metoprolol-predict-effect', tags:['metoprolol','beta1'], source:'both',
 stem:'Metoprolol is a reversible β1 receptor antagonist, and β1 receptors are located in the heart. What effect on the heart is predicted when a patient takes it?',
 options:[
  {t:'Slower heart rate', correct:true, why:'Blocking the heart’s β1 receptors slows the heart rate; this is the prediction he asked the class to make.'},
  {t:'Faster heart rate', correct:false, why:'Treats an antagonist as if it were an agonist at β1.'},
  {t:'No change in heart rate', correct:false, why:'Ignores that the blocked receptor is located in the heart.'},
  {t:'Increased urination', correct:false, why:'Confuses the β1 blocker with the thiazide diuretic example.'}],
 teach:'If you know the mechanism of action (β1-selective antagonist) and the site of action (β1 receptors in the heart), the effect follows: the heart rate slows. The same reasoning predicts side effects such as bradycardia.',
 quote:'If I give you metoprolol, which is a beta 1 selective antagonist, and beta ones are in the heart, what kind of effect is it going to produce? ... Slow down the heart rate.',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2 Major autonomic receptor types; Table 6–5', t:'β1 adrenoceptors are located especially in the heart, where sympathetic activity accelerates the sinoatrial node through them. A β-blocker binds β receptors and prevents their activation, removing that acceleration.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~9; transcript 9/22'},

{id:'L01-003', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'apply', multi:true,
 concept:'metoprolol-predict-adr', tags:['metoprolol','adr'], source:'both',
 stem:'Metoprolol is a β1 receptor antagonist; its sites of action include the heart, kidneys and brain. Which adverse drug reactions (ADRs) fit this mechanism and site? Select all that apply.',
 options:[
  {t:'Bradycardia', correct:true, why:'Blocking β1 in the heart can slow it too much; bradycardia is listed as an ADR.'},
  {t:'Fatigue', correct:true, why:'Fatigue is listed as an ADR and he ties it to β1 receptors in the brain.'},
  {t:'Tachycardia', correct:false, why:'A β1 antagonist slows the heart; tachycardia reverses the effect.'},
  {t:'Hyponatremia', correct:false, why:'Hyponatremia was the thiazide diuretic example, from losing sodium.'}],
 teach:'Metoprolol blocks β1 receptors. In the heart that slows the rate, and too much slowing is bradycardia. β1 receptors are also in the brain, which he links to fatigue and patients forgetting things.',
 quote:'severe bradycardia that can be a side effect if you get to the brain or the beta ones are as well, it may cause fatigue. Patients may forget things.',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2 Major autonomic receptor types', t:'β1 adrenoceptors are on postsynaptic effector cells, especially heart, lipocytes and brain. Because the sinoatrial node is accelerated through β1 receptors, blocking them slows the heart, and slowing it too far is bradycardia.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~9; transcript 9/22'},

{id:'L01-004', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'recall',
 concept:'drugs-alter-ongoing-system', tags:['definition','poll'], source:'both',
 stem:'Which statement is CORRECT about what drugs do to a biological system?',
 options:[
  {t:'Drugs alter an ongoing physiological or pathological function', correct:true, why:'Drugs change an ongoing physiological or pathological function; they initiate, inhibit or modulate.'},
  {t:'Drugs create a new physiological pathway in the body', correct:false, why:'He states drugs do not create anything new.'},
  {t:'Drugs can only block receptors', correct:false, why:'Drugs can also initiate or modulate a signal.'},
  {t:'Drugs can only mimic hormones and neurotransmitters the body already makes', correct:false, why:'Some drugs mimic body products; others are unique. Either way they alter an existing system.'},
  {t:'All of the above', correct:false, why:'Only the first statement is correct; drugs do not create new pathways, and they can initiate or modulate as well as block.'}],
 teach:'Drugs are chemical substances that alter an ongoing physiological or pathological function by interacting with components of the biological system. They can initiate, inhibit or modulate a signal, but they do not create a new pathway.',
 quote:'drugs don’t create anything new, they just change whatever is happening in the body.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'The Nature of Drugs; Pharmacology (opening definition)', t:'A drug is any substance that brings about a change in biologic function through its chemical actions. In most cases the drug molecule acts as an agonist or antagonist on a target molecule that already plays a regulatory role in the biologic system.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~11, ~31; transcript 9/22'},

{id:'L01-005', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'recall',
 concept:'receptor-message-physiological-response', tags:['receptor'], source:'both',
 stem:'Norepinephrine binds β1 receptors and cardiac output increases. In receptor terms, what is the increase in cardiac output?',
 options:[
  {t:'The physiological response', correct:true, why:'The message a drug–receptor interaction creates is seen as the physiological response.'},
  {t:'The affinity of norepinephrine for β1', correct:false, why:'Affinity is how well the drug binds, not the response produced.'},
  {t:'The site of action', correct:false, why:'The site of action is where the receptor is (the heart), not the response.'},
  {t:'The apparent potency', correct:false, why:'Apparent potency concerns how much drug reaches the site; it is not the response itself.'}],
 teach:'Receptors sense signals such as hormones, neurotransmitters and drugs. The message the receptor creates after binding is what we observe as the physiological response, for example increased cardiac output when norepinephrine binds β1.',
 quote:'The message that the receptor creates is the physiological response.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Pharmacodynamic Principles', t:'Drug binding is only the first step: the drug–receptor complex acts through coupling and effector molecules, and the final change in function is accomplished by that effector mechanism. The rise in cardiac output is that altered function, the effect, not the binding itself.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~11; transcript 9/22'},

{id:'L01-006', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'apply',
 concept:'curare-not-absorbed', tags:['curare','absorption'], source:'both',
 stem:'Curare (Strychnos toxifera) is a very large, positively charged molecule used as a paralytic agent. Why does eating the plant produce no effect?',
 options:[
  {t:'It cannot be absorbed', correct:true, why:'A large, charged molecule is not absorbed, so eating it does nothing.'},
  {t:'It has no affinity', correct:false, why:'Curare paralyzes fish through the gills, so it does act once it reaches its target.'},
  {t:'It is a partial agonist', correct:false, why:'Its lack of oral effect is about absorption, not intrinsic activity.'},
  {t:'Stomach acid adds a charge', correct:false, why:'The charge is a property of the molecule itself.'}],
 teach:'Curare is a large molecule with a positive charge, so it is not absorbed when eaten. It was discovered when fish, whose gills are outside the body, became paralyzed and floated up. It was later used as a paralyzing agent for surgery.',
 quote:'What does that tell you to be large and have a charge to it, positive or negative? You can’t absorb, right?',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Drug Size; Ionization of Weak Acids and Weak Bases', t:'Molecules much larger than about 1000 molecular weight do not diffuse readily between body compartments. The charge of an ionized molecule makes it water-soluble and lipid-insoluble, so a permanently charged molecule permeates membranes poorly.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~14; transcript 9/22'},

{id:'L01-007', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'recall', multi:true,
 concept:'nds-regulation', tags:['nds'], source:'both',
 stem:'Which statements about natural dietary supplements (NDS) are correct? Select all that apply.',
 options:[
  {t:'They are regulated as food', correct:true, why:'NDS are regulated as food, not as drugs.'},
  {t:'They have less FDA oversight', correct:true, why:'Because they are not drugs, the FDA oversees them less; they stay on the market until they cause harm.'},
  {t:'Labels cannot claim they cure', correct:true, why:'Labels cannot state that the product treats, cures, diagnoses or prevents a disease.'},
  {t:'They are tested like Rx drugs', correct:false, why:'The label states the claims have not been evaluated by the FDA.'},
  {t:'Being natural makes them safe', correct:false, why:'He answered this with cyanide and lead: natural does not mean safe.'}],
 teach:'NDS are regulated as food, so they receive less FDA oversight and remain on the market until they cause harm. Their labels cannot claim to treat, cure, diagnose or prevent disease. Natural does not mean safe.',
 quote:'when we look at natural dietary supplements, they are treated as food, which means they have less oversight by the FDA. Which means that until they cause harm, they’re still in the market',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Table 1–6 Some major legislation pertaining to drugs in the USA; The History of Pharmacology', t:'Under the Dietary Supplement Health and Education Act, supplements are part of the food supply and are not fully reviewed by the FDA as drugs. All substances can be toxic, and botanical chemicals are no different from manufactured drug chemicals except for more impurities.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~15–~16; transcript 9/22'},

{id:'L01-008', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'recall',
 concept:'nds-incorrect-poll', tags:['nds','poll'], source:'both',
 stem:'Which statement is INCORRECT about natural dietary supplements (NDS)?',
 options:[
  {t:'Most NDS labels state they cure diseases', correct:false, why:'This is incorrect, but so are the other statements; select the option that covers all of them.'},
  {t:'NDS are tested by the FDA like Rx drugs', correct:false, why:'This is incorrect, but it is not the only incorrect statement.'},
  {t:'NDS have been used for centuries, so they are safe', correct:false, why:'This is incorrect, but it is not the only incorrect statement.'},
  {t:'NDS are natural, so interaction risk is low', correct:false, why:'This is incorrect, but it is not the only incorrect statement.'},
  {t:'All of the above', correct:true, why:'Every statement is incorrect: labels cannot claim cures, NDS are not FDA-tested like drugs, and natural or old does not mean safe or interaction-free.'}],
 teach:'All four statements are wrong. NDS labels cannot claim to cure, they are not tested by the FDA like prescription drugs, long use does not prove safety, and herbals can interact with prescription and OTC drugs. His test tip: if two answers other than a select-all are definitely correct, choose all of the above.',
 quote:'if there are two answers other than a select all that you know absolutely are correct, just go for the all the above.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'The History of Pharmacology (general principles); Table 1–6', t:'All substances can be toxic, and the chemicals in herbs are no different from those in manufactured drugs except for more impurities. Full FDA review of supplements as drugs is prohibited, so they do not meet the same efficacy and safety standards.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~18; transcript 9/22'},

{id:'L01-009', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'recall',
 concept:'fish-oil-evidence', tags:['nds','fish-oil','poll'], source:'both',
 stem:'Which statement is CORRECT about omega-3 fish oil?',
 options:[
  {t:'Omega-3s lower triglycerides and reduce the risk of cardiac death', correct:true, why:'Omega-3s lower triglycerides and reduce the risk of cardiac death, though not the risk of a cardiovascular event.'},
  {t:'Omega-3s reduce the risk of having a cardiovascular event', correct:false, why:'The slide states omega-3s do not reduce the risk of a cardiovascular event.'},
  {t:'Omega-3s have no role in fetal development', correct:false, why:'Omega-3s are important for fetal development.'},
  {t:'Omega-3s have no effect on triglycerides and act only on blood pressure', correct:false, why:'Omega-3s can lower triglycerides; blood pressure is not part of the fish-oil evidence he listed.'},
  {t:'All of the above', correct:false, why:'Only one statement is correct; the others reverse what the NIH evidence says.'}],
 teach:'Omega-3s are important for fetal development and can lower triglycerides. They do not reduce the risk of a cardiovascular event, but appear to reduce the risk of cardiac death if an event occurs.',
 quote:'Although omega-3s can lower triglycerides, they don’t reduce the risk of cardiovascular event but reduce the risk of Cardiac death.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~19; transcript 9/22'},

{id:'L01-010', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'apply',
 concept:'nds-report-interactions', tags:['nds','ddi'], source:'both',
 stem:'A patient on several prescription drugs says she takes an herbal supplement but did not mention it because it is natural. What is the concern?',
 options:[
  {t:'The herbal can interact with her drugs', correct:true, why:'Herbals have active ingredients that can interact with prescription and OTC drugs.'},
  {t:'Herbals lack active ingredients', correct:false, why:'He cites aspirin, digoxin and warfarin as drugs from natural sources; herbals do have active ingredients.'},
  {t:'Only prescription drugs can cause interactions', correct:false, why:'Herbals can interact with both prescription and OTC drugs.'},
  {t:'Herbals are fully FDA-tested', correct:false, why:'Supplements have not been fully tested.'}],
 teach:'Most patients do not consider supplements pertinent and do not report them. Herbals have active ingredients, can interact with prescription or OTC drugs, and can produce side effects because they have not been fully tested.',
 quote:'Herbal medications and supplements do have active ingredients... some of those active ingredients can have drug-drug interactions with their over the counter medications.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'The History of Pharmacology (general principles); Confounding Factors in Clinical Trials', t:'Botanical chemicals are no different from those in manufactured drugs apart from more impurities, so an herbal product carries active chemicals like any drug. Other drugs alter the pharmacokinetics of many drugs, so a pharmacologic history must include over-the-counter drugs and supplements.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~20; transcript 9/22'},

{id:'L01-011', fg:'potency', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'apply',
 concept:'dose-selectivity', tags:['selectivity','metoprolol'], source:'transcript',
 stem:'Metoprolol is β1-selective at lower doses. What happens as the dose rises above about 200 mg?',
 options:[
  {t:'It starts to affect β2 receptors', correct:true, why:'The larger the dose, the less selective the drug; above about 200 mg metoprolol affects β2.'},
  {t:'It becomes more β1-selective', correct:false, why:'Reverses the rule; selectivity falls as dose rises.'},
  {t:'It stops binding the β1 receptors entirely', correct:false, why:'It still binds β1; it adds binding at β2.'},
  {t:'It becomes a β1 agonist', correct:false, why:'Dose changes selectivity, not whether the drug activates or blocks.'}],
 teach:'One rule he gave: the larger the dose, the less selective the drug. Starting with the smallest dose that gives the desired effect keeps the drug at one receptor. Metoprolol is β1-selective up to about 200 mg and begins to affect β2 above that.',
 quote:'Metoprolol is a beta 1 selective up to about 200 mg. Once you go above 200, you start to affect the beta 2s, so you start to lose selectivity',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~21; transcript 9/22'},

{id:'L01-012', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'recall', multi:true,
 concept:'potency-determinants', tags:['potency','affinity','efficacy'], source:'both',
 stem:'The potency of a drug depends on which factors? Select all that apply.',
 options:[
  {t:'Affinity', correct:true, why:'Affinity is one of the two factors intrinsic to the drug.'},
  {t:'Efficacy', correct:true, why:'Efficacy is the other factor intrinsic to the drug.'},
  {t:'The individual or tissue', correct:true, why:'Tissues differ in receptor expression, which changes potency.'},
  {t:'The brand name', correct:false, why:'Brand names have no role in potency and are not tested on Exam 1.'},
  {t:'The drug’s chemical class name', correct:false, why:'A class name is a label; potency depends on the individual or tissue, affinity and efficacy.'}],
 teach:'Potency depends on three things: the individual (tissue, organ or cell line, which differ in receptor expression), and two properties intrinsic to the drug, affinity and efficacy.',
 quote:'the potency of a drug is going to be dependent on three major things. One is... the individual, the tissue... But the two things that are intrinsic to the drug is going to be the affinity and the efficacy of that drug.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~21; transcript 9/22'},

{id:'L01-013', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'recall',
 concept:'affinity-chemical-bonds', tags:['affinity','poll'], source:'both',
 stem:'Affinity of a drug for the receptor is dependent on the type of chemical bonds it makes.',
 options:[
  {t:'True', correct:true, why:'Covalent, hydrogen, ionic and van der Waals bonds give stronger or weaker binding, and that sets how well the drug attaches and stays bound: affinity.'},
  {t:'False', correct:false, why:'The bonds a drug forms are exactly what determine how strongly it binds; affinity is not set by route, first-pass metabolism or receptor activation.'},
  {t:'True only for drugs that form covalent bonds', correct:false, why:'Every bond type counts: hydrogen, ionic and van der Waals bonds also make binding stronger or weaker, not only covalent bonds.'}],
 teach:'Affinity is how well a drug attaches to the receptor and stays bound. The kind of bonds formed (covalent, hydrogen, ionic, van der Waals) makes binding stronger or weaker.',
 quote:'depending on what kind of bonds they form, covalent bonds, hydrogen bonds, ion bonds, van der Waal bonds, they may have stronger or weaker binding',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Drug Reactivity & Drug-Receptor Bonds', t:'Drugs interact with receptors through covalent, electrostatic and hydrophobic bonds. Covalent bonds are very strong and often irreversible, electrostatic bonds range from relatively strong ionic linkages to weaker hydrogen bonds and very weak van der Waals forces, and hydrophobic bonds are usually weak.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~37; transcript 9/22'},

{id:'L01-014', fg:'efficacy', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'tell',
 concept:'efficacy-definition', tags:['efficacy','poll'], source:'both',
 stem:'Efficacy:',
 options:[
  {t:'Is the ability of a drug to bind and stay bound to a receptor', correct:false, why:'This defines affinity, not efficacy.'},
  {t:'Is the ability of a cell to increase its number of receptors', correct:false, why:'Receptor number is a tissue factor, not the drug’s efficacy.'},
  {t:'Is the ability of a drug to change receptor activity/state', correct:true, why:'Efficacy is the drug’s effect on the receptor: positive (activating) or negative (shutting down).'},
  {t:'Is the ability of a drug to be absorbed at the level of the GI', correct:false, why:'Absorption is pharmacokinetics.'}],
 teach:'Affinity is binding and staying bound; efficacy is what the bound drug does to the receptor. Drugs that activate receptors have positive efficacy; drugs that shut receptors down have negative efficacy.',
 quote:'Some drugs are going to be activating receptors so they have positive efficacy. Others are going to be shutting down the receptors so they have negative efficacy.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Agonists, Partial Agonists, and Inverse Agonists', t:'Full agonists shift the receptor pool to the active form, partial agonists do so less fully (low intrinsic efficacy), and inverse agonists stabilize the inactive form. Intrinsic efficacy is independent of affinity, separating the ability to change receptor state from the ability to bind.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~38; transcript 9/22'},

{id:'L01-015', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'tell',
 concept:'pharmacological-vs-apparent-potency', tags:['potency','pk'], source:'both',
 stem:'Two patients get the same drug. One takes it orally and has first-pass metabolism; the other gets it IV. Which type of potency accounts for the difference in effect?',
 options:[
  {t:'Apparent potency', correct:true, why:'Apparent potency includes pharmacokinetics: route, absorption, metabolism, elimination, age and DDIs.'},
  {t:'Intrinsic activity', correct:false, why:'Intrinsic activity is a drug property from Ariens’ theory, unchanged by route.'},
  {t:'Affinity', correct:false, why:'Affinity is fixed by the drug’s bonds with the receptor, not by the route.'},
  {t:'Efficacy', correct:false, why:'Efficacy is the drug’s effect on receptor state, not how much reaches it.'}],
 teach:'Pharmacological potency comes from the drug–receptor side: tissue sensitivity, receptor number and activity, affinity and efficacy. Apparent potency adds pharmacokinetics: age, absorption, distribution, elimination and DDIs, which set how much drug reaches the site of action. IV has 100% bioavailability and bypasses first-pass metabolism.',
 quote:'pharmokinetics is going to be affecting how much of the drug gets to the site of action. Because that’s how it’s going to produce its effects.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Drug-Body Interactions; Pharmacokinetic Principles', t:'Pharmacodynamics is what the drug does to the body; pharmacokinetics is what the body does to the drug: absorption, distribution and elimination. A drug must be absorbed and distributed to its site of action, so the oral–intravenous difference is pharmacokinetic.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~23, ~27; transcript 9/22',
 note:'Slide and transcript disagree. The slide puts absorption, distribution, elimination, age and drug interactions under apparent potency. In class he said these affect pharmacological potency. Use the slide grouping on the exam.'},

{id:'L01-016', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'recall',
 concept:'potency-correct-poll', tags:['potency','poll'], source:'both',
 stem:'Which statement is CORRECT?',
 options:[
  {t:'Route of administration can affect a drug’s potency', correct:false, why:'True, but not the only true statement.'},
  {t:'Drugs can bind one receptor with higher affinity than others', correct:false, why:'True, but not the only true statement.'},
  {t:'Ability to reach the site of action can affect potency', correct:false, why:'True, but not the only true statement.'},
  {t:'Ion channels are typically expressed on cell membranes', correct:false, why:'True, but not the only true statement.'},
  {t:'All the above', correct:true, why:'Every statement is correct; the class answered 100% all the above.'}],
 teach:'Route and the ability to reach the site of action change apparent potency; drugs bind some receptors with higher affinity than others; ion channels are transmembrane proteins on the cell membrane.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~24; transcript 9/22'},

{id:'L01-017', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'apply',
 concept:'safety-vs-efficacy', tags:['efficacy','poll'], source:'both',
 stem:'If your patient has fungal pneumonia, which would you choose?',
 options:[
  {t:'A very efficacious drug that is less safe', correct:true, why:'A very safe drug that does nothing leaves the patient to die of fungal pneumonia.'},
  {t:'A very safe drug that is not very efficacious', correct:false, why:'A safe topical antifungal would not treat fungal pneumonia.'},
  {t:'Neither drug', correct:false, why:'Leaving fungal pneumonia untreated does not protect the patient.'},
  {t:'Either one; they are equal', correct:false, why:'He ranks efficacy first when the safe drug does not work.'}],
 teach:'His answer: choose the efficacious drug if nothing safer works, because a safe drug that does not work wastes the patient’s health and money. If two drugs have equal efficacy, pick the safer one. Cancer drugs are the same case: toxic but needed.',
 quote:'Perhaps if I’m your patient, please choose the most efficacious drug. If there’s nothing else that is safer than that',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Preclinical Safety & Toxicity Testing; The Food & Drug Administration', t:'No drug is completely safe; risk is judged in the context of therapeutic need. Highly toxic drugs valuable in lethal diseases may be approved, since a drug with no efficacy offers no benefit to weigh against its safety.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~25–~26; transcript 9/22'},

{id:'L01-018', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'tell', multi:true,
 concept:'pharmacological-potency-factors', tags:['potency'], source:'slide',
 stem:'In relating dose to effect, which factors belong to pharmacological potency rather than apparent potency? Select all that apply.',
 options:[
  {t:'Tissue sensitivity', correct:true, why:'Listed under pharmacological potency: how sensitive the tissue is belongs to the drug–receptor (pharmacodynamic) side.'},
  {t:'Receptor number', correct:true, why:'Listed under pharmacological potency, together with receptor activity; how many receptors the tissue expresses sets how much response the drug can produce.'},
  {t:'Affinity', correct:true, why:'Listed under pharmacological potency, together with efficacy; affinity and efficacy are the two factors intrinsic to the drug.'},
  {t:'Absorption', correct:false, why:'Absorption is a pharmacokinetic factor under apparent potency.'},
  {t:'Age', correct:false, why:'Age is listed under apparent potency.'},
  {t:'Elimination by the kidney or liver', correct:false, why:'Elimination is a pharmacokinetic factor under apparent potency.'}],
 teach:'Pharmacological potency (pharmacodynamics): tissue sensitivity, receptor number, receptor activity, affinity, efficacy. Apparent potency (pharmacokinetics): age, absorption, distribution, elimination, DDIs.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Drug-Body Interactions; Confounding Factors in Clinical Trials', t:'Pharmacokinetic processes (the actions of the body on the drug) govern absorption, distribution and elimination, and age influences them. Absorption, elimination and age are therefore pharmacokinetic, while tissue sensitivity, receptor number and affinity concern the drug–receptor interaction.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~27',
 note:'Slide and transcript disagree. In class he said absorption, metabolism and age affect pharmacological potency; the slide puts them under apparent potency. Use the slide grouping on the exam.'},

{id:'L01-019', fg:'partial', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'figure',
 concept:'clark-occupancy', tags:['theory','affinity'], source:'both',
 stem:'Curve A is a full agonist and curve B is a partial agonist at the same receptor. Under the occupancy theory, why does curve B stop at 70% of the maximal response?',
 graph:{curves:[{label:'A', ec:0, emax:100}, {label:'B', ec:0, emax:70}], x:'log dose', y:'% of maximal response', caption:'Full agonist (A) and partial agonist (B) at the same receptor'},
 options:[
  {t:'It occupies only part of the receptors', correct:true, why:'In the occupancy theory response depends on how many receptors are occupied; a partial agonist occupies a percentage.'},
  {t:'It shifts receptors to inactive', correct:false, why:'Shifting to the inactive state is negative efficacy from the later two-state model.'},
  {t:'It has zero intrinsic activity', correct:false, why:'Zero intrinsic activity is Ariens’ antagonist.'},
  {t:'It binds an allosteric site on the receptor', correct:false, why:'Allosteric binding is not part of the occupancy theory.'}],
 teach:'The first theory was based only on affinity: the more receptors a drug occupies, the greater the response. A full agonist occupies all receptors for 100% of the response; a partial agonist occupies, for example, 70% and gives 70%. It introduced affinity and full versus partial agonists but could not explain how all drugs work.',
 quote:'a full agonist will produce 100% of the response as a partial may produce a 70% of the response because it can only occupy 70% of the receptors, right? So it’s based on occupancy.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Agonists, Partial Agonists, and Inverse Agonists', t:'Partial agonists bind the same receptors as full agonists but do not evoke as great a response, no matter how high the concentration. Occupancy theory attributes this to the fraction of receptors occupied; the later two-state model attributes it to bound receptors held inactive.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22'},

{id:'L01-020', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'recall',
 concept:'intrinsic-activity-antagonist', tags:['theory','antagonist'], source:'both',
 stem:'Changing one functional group changed a drug from a full agonist to one that binds but produces no effect. What is its intrinsic activity?',
 options:[
  {t:'Zero', correct:true, why:'An antagonist has affinity but zero intrinsic activity; it binds and does nothing to the receptor.'},
  {t:'One', correct:false, why:'An intrinsic activity of one (100%) is a full agonist.'},
  {t:'Between zero and one', correct:false, why:'That range is a partial agonist.'},
  {t:'Negative', correct:false, why:'Negative efficacy came later with the two-state model, not from intrinsic activity.'}],
 teach:'Changing R1 or R2 functional groups could turn a full agonist into a partial agonist or into something with no effect. This led to intrinsic activity: full agonist 100%, partial agonist 1–99%, antagonist zero. Antagonists have affinity but do nothing to the receptor.',
 quote:'my antagonist, there are zero intrinsic activity. They have affinity, they can bind the receptor, but they don’t do anything to the receptor.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Agonists, Partial Agonists, and Inverse Agonists', t:'Conventional antagonists have equal affinity for the inactive and active receptor forms, so the drug-bound fractions stay in the same proportions as without drug and no change in activity is observed. Their presence at the receptor still blocks access of agonists.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22'},

{id:'L01-021', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'recall',
 concept:'two-state-model-l', tags:['theory','two-state'], source:'both',
 stem:'In the two-state model (D + R ⇄ DR resting; D + R* ⇄ DR* active), what does the constant L determine?',
 options:[
  {t:'How likely a receptor is active vs inactive', correct:true, why:'L sets how likely a receptor is found in the inactive versus the active state without drug.'},
  {t:'How tightly the drug binds', correct:false, why:'Binding strength is affinity, not L.'},
  {t:'How many receptors the drug is able to occupy', correct:false, why:'Occupancy is Clark’s idea.'},
  {t:'How much drug reaches the site', correct:false, why:'That is pharmacokinetics.'}],
 teach:'In the two-state model receptors exist as active or inactive. L determines how likely a receptor is in the inactive versus the active state, and cells can move receptors back and forth and change receptor number. Drugs bound to the receptor shift this balance.',
 quote:'this L constant over here. Determines how likely a receptor should be found on the inactive versus the active state.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Agonists, Partial Agonists, and Inverse Agonists (Figure 1–3)', t:'The receptor can assume an inactive form (Ri), which produces no effect even with drug bound, and an active form (Ra). Without drug the two are in equilibrium with Ri favored, and drugs act by shifting that balance: agonists prefer Ra, inverse agonists Ri.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22'},

{id:'L01-022', fg:'inverse', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'apply',
 concept:'negative-efficacy-inverse-agonist', tags:['two-state','inverse-agonist'], source:'both',
 stem:'A drug binds active receptors and shifts them toward the inactive state. Which kind of drug does the two-state model use this to explain?',
 options:[
  {t:'Inverse agonist', correct:true, why:'Shifting receptors to the inactive state is negative efficacy, which explains inverse agonists.'},
  {t:'Full agonist', correct:false, why:'A full agonist has positive efficacy, shifting receptors to active.'},
  {t:'Partial agonist', correct:false, why:'A partial agonist has positive efficacy.'},
  {t:'Antagonist', correct:false, why:'An antagonist binds but does not change receptor state.'}],
 teach:'Drugs that shift receptors toward the active state have positive efficacy; drugs that shift them toward the inactive state have negative efficacy. The two-state model lets us explain inverse agonists.',
 quote:'Are the drugs bound to receptors who are active and shift them to the negative or inactive state, does have a negative efficacy... And that allows us to explain inverse agonists',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Agonists, Partial Agonists, and Inverse Agonists', t:'A drug with much stronger affinity for the inactive (Ri) than the active (Ra) receptor state stabilizes a large fraction in the inactive drug-bound pool, reduces any constitutive activity, and produces effects opposite to those of agonists; such drugs are inverse agonists.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22'},

{id:'L01-023', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'tell',
 concept:'loratadine-vs-diphenhydramine', tags:['selectivity','histamine'], source:'both',
 stem:'Loratadine and diphenhydramine both act at the histamine H1 receptor. What separates them?',
 options:[
  {t:'Loratadine is selective; diphenhydramine is not', correct:true, why:'Loratadine is a selective H1 inverse agonist; diphenhydramine also binds H2 and muscarinic receptors.'},
  {t:'Diphenhydramine is selective; loratadine is not', correct:false, why:'Reverses the pair.'},
  {t:'Both are selective for H1', correct:false, why:'Diphenhydramine binds H1, H2 and muscarinic receptors.'},
  {t:'Neither binds the H1 receptor', correct:false, why:'Both bind H1.'}],
 teach:'Drugs can be selective or non-selective. Loratadine is a selective H1 inverse agonist. Diphenhydramine binds H1, H2 and muscarinic receptors and is very non-selective; it is the ingredient in nighttime products and puts 9 of 10 people to sleep.',
 quote:'Benadryl not only binds to the H1, it binds to the H2... It’s very non-selective.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Drug Size', t:'To fit only one type of receptor, a drug molecule must be sufficiently unique in shape, charge and other properties to prevent its binding to other receptors. A drug whose structure fits several receptor types is by this definition non-selective.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~29; transcript 9/22'},

{id:'L01-024', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'recall',
 concept:'allosteric-drugs', tags:['allosteric','classes'], source:'both',
 stem:'Which drug class does not always act by itself but can make other drugs much better or much worse by changing their potency?',
 options:[
  {t:'Allosteric drugs', correct:true, why:'Allosterics are "where the magic in pharmacology is": they affect the potency of other drugs.'},
  {t:'Full agonists', correct:false, why:'Full agonists act by themselves with positive efficacy.'},
  {t:'Irreversible antagonists', correct:false, why:'Antagonists block receptors; they are not described as changing other drugs’ potency.'},
  {t:'Inverse agonists', correct:false, why:'Inverse agonists act by themselves with negative efficacy.'}],
 teach:'Drug classes by mechanism: agonists (full, partial, inverse), antagonists (direct or indirect; reversible or irreversible), and allosterics (agonist or antagonist). Allosterics do not always act alone but can make other drugs much better or much worse.',
 quote:'we have over here where the magic in pharmacology is, allosterics. These drugs, they don’t do things by themselves all the time, but they can make other drugs much, much better or much, much worse.',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'Types of Drug-Receptor Interactions (Figure 1–2)', t:'Drugs that bind the same receptor as the agonist without preventing agonist binding act allosterically and may enhance or inhibit the agonist’s action. Allosteric activators can increase the agonist’s efficacy or binding affinity; allosteric inhibitors lower the response.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~29; transcript 9/22'},

{id:'L01-025', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'recall',
 concept:'drug-vs-poison-dose', tags:['dose'], source:'both',
 stem:'Carrots are good for eyesight because of vitamin A, but polar bear liver has so much vitamin A that eating it kills. Which statement does this illustrate?',
 options:[
  {t:'Drug and poison differ only in quantity', correct:true, why:'Walter Straub: there is only a quantitative difference between a drug and a poison.'},
  {t:'Natural sources are always safe', correct:false, why:'The example shows a natural source that is lethal.'},
  {t:'Vitamin A has no toxicity', correct:false, why:'Polar bear liver vitamin A is described as a poison.'},
  {t:'Selectivity rises as the dose is increased', correct:false, why:'Reverses the rule; selectivity falls as dose rises.'}],
 teach:'Everything is dose dependent. Walter Straub stated there is only a quantitative difference between a drug and a poison: vitamin A helps eyesight but is lethal at polar bear liver amounts.',
 quote:'Walter Straub: there is only a quantitative difference between a drug and a poison',
 reading:[{src:'Katzung 16e, Ch. 1', sec:'The Nature of Drugs', t:'Poisons are drugs that have almost exclusively harmful effects, and the dose makes the poison: any substance can be harmful if taken in the wrong dosage.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~29; transcript 9/22'},

{id:'L01-026', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'apply',
 concept:'thiazide-moa-predict', tags:['thiazide','moa','classification'], source:'both',
 stem:'A thiazide diuretic blocks the Na+/Cl− symporter in the distal convoluted tubule. Which side effect does this mechanism predict?',
 options:[
  {t:'Hyponatremia', correct:true, why:'Blocking sodium reabsorption loses sodium; losing too much makes the patient hyponatremic.'},
  {t:'Decreased urination', correct:false, why:'Water follows sodium, so urination increases.'},
  {t:'Increased blood volume', correct:false, why:'Losing water lowers blood volume and blood pressure.'},
  {t:'Bradycardia', correct:false, why:'Bradycardia was the metoprolol example.'}],
 teach:'Classifying by chemical structure (benzothiadiazine ring) does not predict much. Classifying by MOA does: blocking the Na+/Cl− symporter at the distal tubule means sodium is lost, water follows, urination increases, blood volume and pressure fall (antihypertensive use), and losing too much sodium causes hyponatremia.',
 quote:'It makes you lose water because it makes you lose sodium. And if you lose too much sodium, you become hyponatremic. That’s a side effect.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~32–~33; transcript 9/22'},

{id:'L01-027', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'receptors', skill:'tell',
 concept:'receptor-class-examples', tags:['receptor-classes'], source:'slide',
 stem:'Which receptor class includes α and β adrenergic, 5HT and histamine receptors?',
 options:[
  {t:'7-transmembrane (GPCR)', correct:true, why:'The G protein–coupled receptor (GPCR) row lists α and β adrenergic, 5HT and histamine.'},
  {t:'1-transmembrane', correct:false, why:'This row lists tyrosine kinases.'},
  {t:'Ion channels', correct:false, why:'This row lists L-type Ca++ channels and GABA.'},
  {t:'Intracellular receptors', correct:false, why:'This row lists steroid hormones.'}],
 teach:'Four receptor classes: ion channels (L-type Ca++ channels, GABA), 7-transmembrane G protein–coupled receptors (α and β adrenergic, 5HT, histamine), 1-transmembrane proteins (tyrosine kinases) and intracellular receptors / transcriptional regulators (steroid hormones).',
 quote:'We also have what is called 7 transmembrane receptors. Those cross the membrane 7 times, and they are unique because they have this protein inside of the cell which is heterotrimeric.',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2 Major autonomic receptor types; Presynaptic Regulation', t:'Adrenoceptors signal through G proteins: α1 receptors form IP3 and DAG, α2 receptors inhibit adenylyl cyclase, and β receptors stimulate adenylyl cyclase and raise cAMP. Nicotinic receptors are the contrast: pentameric proteins whose ligand binding directly opens sodium and potassium channels, the ion-channel class.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~36'},

{id:'L01-028', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'ion', skill:'recall', multi:true,
 concept:'ion-channel-properties', tags:['ion-channels'], source:'slide',
 stem:'Which statements about ion channels are correct? Select all that apply.',
 options:[
  {t:'They are expressed in all cells', correct:true, why:'The ion channel slide lists them as transmembrane proteins expressed in all cells, with about 232 distinct types.'},
  {t:'They alter membrane potential', correct:true, why:'They convey their signal by altering membrane potential or ionic composition.'},
  {t:'The lipid bilayer lets ions through', correct:false, why:'The lipid bilayer is impermeable to anions and cations.'},
  {t:'There are about 7 distinct ones', correct:false, why:'There are about 232 distinct ion channels.'}],
 teach:'Ion channels are transmembrane proteins with various subunit combinations, expressed in all cells, about 232 distinct types. They are classified by the ions they conduct, their architecture and the mechanism that opens them (ligand, voltage or stretch). They signal by altering membrane potential or ionic composition (Na+, K+, Ca2+, Cl−), because the lipid bilayer is impermeable to ions.',
 quote:'Convey their signal by altering cell membrane potential or ionic composition (Na+, K+, Ca2+, and Cl–)',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Postsynaptic Regulation (Figure 6–8)', t:'Ion-channel signaling is expressed as changes in membrane potential: opening sodium and potassium channels depolarizes a cell, and opening potassium channels hyperpolarizes it.'},
         {src:'Katzung 16e, Ch. 1', sec:'Ionization of Weak Acids and Weak Bases; Lipid diffusion', t:'The charge of an ionized molecule makes it water-soluble and lipid-insoluble, so charged species do not readily cross lipid membranes; the bilayer itself is not what lets ions through.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~39'},

{id:'L01-029', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'ion', skill:'tell',
 concept:'ion-channel-types', tags:['ion-channels'], source:'slide',
 stem:'Which type of ion channel is usually closed and has its binding pocket located in the channel, as in the nicotinic acetylcholine receptor?',
 options:[
  {t:'Ligand-gated channel', correct:true, why:'Ligand-gated channels are usually closed and bind acetylcholine, GABA-A or 5HT3 in the channel.'},
  {t:'Passive channel', correct:false, why:'Passive channels are always open and set resting membrane potential.'},
  {t:'Voltage-gated channel', correct:false, why:'These open at certain membrane potentials, e.g., calcium channels.'},
  {t:'Pump', correct:false, why:'Pumps move ions against the concentration gradient.'}],
 teach:'Passive channels are always open (resting membrane potential). Voltage-gated channels are highly selective and open only at certain membrane potentials (calcium channels). Stretch channels are pressure sensitive. Ligand-gated channels are usually closed with the binding pocket in the channel (acetylcholine at nicotinic, GABA-A, 5HT3). Pumps move ions against the concentration gradient (Na+/K+ ATPase).',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2 Major autonomic receptor types; Table 6–5 Steps in autonomic transmission', t:'At nicotinic receptors, ligand binding opens the ion channel in the postsynaptic membrane (Na+ and K+ flow, depolarization); that is the ligand-gated pattern. Voltage-gated channels instead open when an action potential arrives.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~40–~47'},

{id:'L01-030', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'ion', skill:'recall',
 concept:'baroreceptor-stretch', tags:['ion-channels','baroreceptor'], source:'slide',
 stem:'Baroreceptors in the carotid sinus and aortic arch use stretch channels. What happens to nerve firing when stretch increases?',
 options:[
  {t:'Nerve firing increases', correct:true, why:'The slide states increase stretch = increase nerve firing.'},
  {t:'Nerve firing decreases', correct:false, why:'Reverses the relationship.'},
  {t:'Nerve firing does not change', correct:false, why:'Stretch channels are pressure sensitive, so firing changes.'},
  {t:'The channel closes permanently', correct:false, why:'No such behavior is described.'}],
 teach:'Stretch channels are pressure sensitive and embedded in blood vessel walls (baroreceptors). The carotid sinus (glossopharyngeal nerve) monitors blood going to the brain and the aortic arch (vagus nerve) is close to the heart. Increased stretch increases nerve firing.',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Integration of Cardiovascular Function', t:'When mean arterial pressure rises, the compensatory response is mediated by increased firing of the baroreceptor nerves of the carotid sinus and aortic arch. Higher pressure stretching the vessel wall means more baroreceptor firing.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~43'},

{id:'L01-031', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'ion', skill:'apply',
 concept:'nicotinic-sequence', tags:['nicotinic','ion-channels'], source:'slide',
 stem:'Acetylcholine binds the 2 α subunits of the nicotinic receptor, the channel opens and Na+ flows in while K+ flows out. What is the next step?',
 options:[
  {t:'The membrane depolarizes', correct:true, why:'Step 3: depolarization of membrane potential (less negative).'},
  {t:'The Na+/K+ ATPase restores potential', correct:false, why:'That is the last step, after contraction.'},
  {t:'Intracellular Ca++ falls', correct:false, why:'Intracellular Ca++ increases once voltage-sensitive Ca++ channels open.'},
  {t:'The membrane becomes more negative', correct:false, why:'Na+ influx makes the membrane less negative.'}],
 teach:'Sequence: (1) acetylcholine binds 2 α subunits; (2) the channel opens, increasing Na+ influx and K+ outflow; (3) the membrane depolarizes (less negative); (4) voltage-sensitive Ca++ channels open; (5) intracellular Ca++ rises, increasing contraction; (6) the Na+/K+ ATPase restores membrane potential.',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2; Postsynaptic Regulation (Figure 6–8)', t:'Ligand binding at nicotinic receptors opens Na+ and K+ channels and depolarizes the membrane; depolarization is the immediate consequence of the channel opening, before any calcium-dependent step.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~48'},

{id:'L01-032', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'gpcr', skill:'recall',
 concept:'gpcr-largest-class', tags:['gpcr','poll'], source:'both',
 stem:'Which statement is CORRECT about G protein–coupled receptors (GPCRs)?',
 options:[
  {t:'GPCRs interact with 60% plus of active therapeutic drugs', correct:true, why:'The slide states GPCRs interact with 60% plus of active therapeutic drugs.'},
  {t:'GPCRs cross the cell membrane a single time', correct:false, why:'GPCRs are 7-transmembrane proteins.'},
  {t:'The G protein coupled to a GPCR has a single subunit', correct:false, why:'The G protein is heterotrimeric: α, β and γ.'},
  {t:'GPCRs are the smallest class of pharmacological receptors', correct:false, why:'They are the largest single class of pharmacological receptors.'},
  {t:'All of the above', correct:false, why:'Only the 60% statement is correct; GPCRs cross the membrane seven times, use a three-subunit G protein and are the largest receptor class.'}],
 teach:'GPCRs are 7-transmembrane proteins coupled to a heterotrimeric guanine nucleotide binding protein (α, β, γ). They are the largest single class of pharmacological receptors and interact with 60% plus of active therapeutic drugs. The G protein acts as the translator that dictates the signal.',
 quote:'about 60 or more% of all drugs in the market target one of kind of these receptors. So if you know how they work, you’ve got 60% of the drugs in your pocket.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~49; transcript 9/22'},

{id:'L01-033', fg:'gpcr', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'gpcr', skill:'apply',
 concept:'gs-cascade-heart', tags:['gpcr','gs','beta1'], source:'slide',
 stem:'Norepinephrine binds β1 receptors in the heart. After GDP release and GTP binding, what does the αs subunit activate?',
 options:[
  {t:'Adenylate cyclase', correct:true, why:'αs activates adenylate cyclase (AC), which converts ATP to cAMP.'},
  {t:'Phospholipase C', correct:false, why:'Phospholipase C (PLC) is activated by αq at α1 receptors.'},
  {t:'Phosphodiesterase', correct:false, why:'Phosphodiesterase (PDE) breaks down cAMP; it ends the signal.'},
  {t:'The Na+/K+ ATPase', correct:false, why:'That pump restores membrane potential in the nicotinic sequence.'}],
 teach:'At β1 in the heart: norepinephrine binds, GDP is released, GTP binds, and αs activates adenylate cyclase (AC). AC converts ATP to cAMP (amplification), the second messenger, leading to the physiological response of increased heart rate.',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2', t:'For β1 adrenoceptors, the result of ligand binding is stimulation of adenylyl cyclase and increased cAMP. Formation of IP3 belongs to α1 and M1/M3 receptors, and inhibition of adenylyl cyclase to α2 and M2.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~51–~53'},

{id:'L01-034', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'gpcr', skill:'recall', multi:true,
 concept:'gs-termination', tags:['gpcr','rgs','pde'], source:'slide',
 stem:'Which processes end the β1–Gs signal? Select all that apply.',
 options:[
  {t:'Intrinsic GTPase hydrolysis of GTP', correct:true, why:'GTPase-mediated dissociation is the intrinsic process that cleaves GTP to GDP.'},
  {t:'RGS proteins speeding GTP hydrolysis', correct:true, why:'Regulators of G protein signaling (RGS) greatly accelerate GTP hydrolysis.'},
  {t:'Phosphodiesterase breaking down cAMP', correct:true, why:'cAMP phosphodiesterase (PDE) removes the second messenger.'},
  {t:'GDP release from the αs subunit after binding', correct:false, why:'GDP release is an activating step; GTP then binds.'},
  {t:'Adenylate cyclase making cAMP', correct:false, why:'This produces the signal; it does not end it.'}],
 teach:'Activation: binding, GDP release, GTP binding, α-mediated activation of adenylate cyclase, ATP to cAMP. Deactivation: intrinsic GTPase cleavage of GTP, RGS-enhanced dissociation (RGS proteins greatly accelerate GTP hydrolysis), and cAMP phosphodiesterase (PDE).',
 quote:'Regulators of G protein signaling (RGSs) - RGS proteins greatly accelerate the hydrolysis of GTP',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~54'},

{id:'L01-035', fg:'gpcr', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'gpcr', skill:'tell',
 concept:'gq-alpha1-plc', tags:['gpcr','gq','alpha1'], source:'slide',
 stem:'Norepinephrine binds α1 receptors on smooth muscle. Which pathway follows?',
 options:[
  {t:'αq, phospholipase C, PIP2 to IP3', correct:true, why:'α1 couples to αq, which activates phospholipase C (PLC); PIP2 gives IP3, releasing Ca2+ from the ER.'},
  {t:'αs, adenylate cyclase, ATP to cAMP', correct:false, why:'That is the β1 pathway in the heart.'},
  {t:'Na+ influx through the receptor channel', correct:false, why:'That is the nicotinic ligand-gated channel.'},
  {t:'Enzymatic activity of the receptor', correct:false, why:'That describes 1-transmembrane receptors.'}],
 teach:'At α1 receptors on smooth muscle, norepinephrine or epinephrine activates αq, which activates phospholipase C (PLC). PLC converts PIP2 to IP3, and IP3 releases stored Ca2+ from the endoplasmic reticulum (ER).',
 reading:[{src:'Katzung 16e, Ch. 6', sec:'Table 6–2', t:'For α1 adrenoceptors, located especially on smooth muscle, the result of ligand binding is formation of IP3 and DAG and increased intracellular calcium. β receptors act instead through adenylyl cyclase and cAMP.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~55'},

{id:'L01-036', fg:'inverse', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'figure',
 concept:'five-curve-inverse-loratadine-d1', tags:['poll','loratadine','two-state'], source:'both',
 stem:'I have 4 dose–response curves, A–D, of 4 different drugs, drawn in a tissue whose receptors have some activity with nothing bound (the basal line). Which drug is most likely drug D?',
 graph:{curves:[{label:'A', ec:0, emax:100}, {label:'B', ec:0, emax:70}, {label:'C', ec:0, emax:30}, {label:'D', ec:0, emax:5}], base:30, x:'log dose', y:'% of maximal response', caption:'Basal activity 30%; each curve is one drug given alone'},
 options:[
  {t:'Loratadine', correct:true, why:'Curve D shuts the receptors down below their basal activity, which is negative efficacy; loratadine is the H1 inverse agonist he named.'},
  {t:'Metoprolol', correct:false, why:'Metoprolol is a reversible antagonist: it binds with zero intrinsic activity and does nothing to the receptor, so its curve stays on the basal line (curve C).'},
  {t:'Norepinephrine', correct:false, why:'Norepinephrine activates β1 receptors and increases heart rate, positive efficacy; its curve rises above the basal line.'},
  {t:'Acetylcholine', correct:false, why:'Acetylcholine binds the nicotinic receptor and opens the channel, positive efficacy; its curve rises above the basal line.'}],
 teach:'First classify the curve, then match the drug. Drugs with positive efficacy activate receptors, so their curves rise (A full, B partial). An antagonist binds but does nothing, so its curve stays on the basal line (C). A drug that shuts receptors down has negative efficacy, so its curve falls below baseline (D): an inverse agonist, and loratadine is the inverse agonist he named.',
 quote:'Some drugs are going to be activating receptors so they have positive efficacy. Others are going to be shutting down the receptors so they have negative efficacy.',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor Antagonists (inverse agonist activity)', t:'Although antagonists are traditionally thought to have no functional effect without an agonist, some show inverse agonist activity because they reduce receptor activity below basal levels.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~28–~29, ~38; transcript 9/22'},

{id:'L01-037', fg:'classes', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'figure',
 concept:'antagonist-flat-curve-metoprolol', tags:['poll','metoprolol','theory'], source:'both',
 stem:'The four curves, A–D, are four different drugs given alone in a tissue with 30% basal receptor activity. Which curve best represents metoprolol?',
 graph:{curves:[{label:'A', ec:0, emax:5}, {label:'B', ec:0, emax:100}, {label:'C', ec:0, emax:30}, {label:'D', ec:0, emax:70}], base:30, x:'log dose', y:'% of maximal response', caption:'Basal activity 30%; each curve is one drug given alone'},
 options:[
  {t:'A', correct:false, why:'Curve A falls below the basal line, negative efficacy, which is an inverse agonist such as loratadine.'},
  {t:'B', correct:false, why:'Curve B rises to 100%, a full agonist with positive efficacy.'},
  {t:'C', correct:true, why:'Metoprolol is a reversible β1 antagonist: it has affinity but zero intrinsic activity, so it binds and does nothing, and the response stays on the basal line at every dose.'},
  {t:'D', correct:false, why:'Curve D rises to 70%, a partial agonist that occupies part of the receptors.'},
  {t:'None of the above', correct:false, why:'One curve does fit: an antagonist alone produces no change from basal activity, which is curve C.'}],
 teach:'An antagonist has affinity, so it binds the receptor, but zero intrinsic activity, so it does not change the receptor state. Given alone it produces no response above or below the basal line, which drawn as a dose–response curve is a flat line at baseline. Metoprolol is the reversible β1 antagonist on the drug list.',
 quote:'my antagonist, there are zero intrinsic activity. They have affinity, they can bind the receptor, but they don’t do anything to the receptor. They just kinda sit there and just kinda linger.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~9, ~28; transcript 9/22'},

{id:'L01-038', fg:'partial', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'figure',
 concept:'clark-occupancy', tags:['poll','theory'], source:'both',
 stem:'The curves are three different drugs given alone at the same receptor. Which of these drugs is a partial agonist?',
 graph:{curves:[{label:'A', ec:0, emax:100}, {label:'B', ec:-1, emax:100}, {label:'C', ec:0, emax:70}], x:'log dose', y:'% of maximal response'},
 options:[
  {t:'A', correct:false, why:'Curve A reaches 100% of the maximal response, which is a full agonist.'},
  {t:'B', correct:false, why:'Curve B also reaches 100%; reaching the full response makes it a full agonist, whatever its position.'},
  {t:'C', correct:true, why:'Curve C plateaus at 70%: it produces only a percentage of the maximal response, which by the occupancy theory is a partial agonist that occupies only part of the receptors.'},
  {t:'None of the above', correct:false, why:'Curve C plateaus below the maximal response, so one curve is a partial agonist.'}],
 teach:'A full agonist produces 100% of the response; a partial agonist produces a percentage of it, for example 70%, because under the occupancy theory it occupies only that fraction of the receptors. Read the plateau, not the position: any curve that reaches 100% is a full agonist, and the one that stops short is the partial.',
 quote:'a full agonist will produce 100% of the response as a partial may produce a 70% of the response because it can only occupy 70% of the receptors, right? So it’s based on occupancy.',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists', t:'Partial agonists produce a lower response at full receptor occupancy than full agonists do. Their failure to produce a maximal response is not due to decreased affinity for the receptor.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22'},

{id:'L01-039', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'recall',
 concept:'efficacy-definition', tags:['efficacy','poll'], source:'both',
 stem:'Efficacy is the ability of a drug to bind and stay bound to a receptor.',
 options:[
  {t:'True', correct:false, why:'Binding and staying bound is affinity; efficacy is what the bound drug does to the receptor.'},
  {t:'False', correct:true, why:'Efficacy is the ability of a drug to change receptor activity or state, positive (activating) or negative (shutting down); binding and staying bound is affinity.'},
  {t:'True only for antagonists', correct:false, why:'An antagonist binds and stays bound with zero intrinsic activity, which shows that binding is affinity and is separate from efficacy.'}],
 teach:'Affinity is how well a drug attaches to the receptor and stays bound, set by the bonds it forms. Efficacy is the effect the bound drug produces on the receptor: activating it (positive efficacy) or shutting it down (negative efficacy). An antagonist has affinity with zero intrinsic activity, so the two properties are separate.',
 quote:'What about efficacy? ... it’s going to be the effect that a drug is going to produce. Some drugs are going to be activating receptors so they have positive efficacy. Others are going to be shutting down the receptors so they have negative efficacy.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~21, ~38; transcript 9/22'},

{id:'L01-040', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'recall',
 concept:'dose-selectivity', tags:['selectivity','metoprolol','poll'], source:'both',
 stem:'The larger the dose of a drug, the less selective the drug becomes.',
 options:[
  {t:'True', correct:true, why:'One of his rules: as the dose rises the drug starts to interact with other receptors; metoprolol is β1-selective up to about 200 mg and affects β2 above that.'},
  {t:'False', correct:false, why:'Selectivity falls as dose rises; that is why he starts with the smallest dose that gives the desired effect.'},
  {t:'True only for drugs that are already non-selective', correct:false, why:'The rule applies to selective drugs too: metoprolol is β1-selective at low doses and loses that selectivity above about 200 mg.'}],
 teach:'Everything is dose dependent. As the dose rises, a drug starts to go around and interact with other receptors, so the larger the dose, the less selective the drug and the more side effects. Starting with the smallest dose that produces the desired effect keeps the drug at one receptor.',
 quote:'the larger the dose gets, the less selective a drug becomes. You start to go around and interact with other things.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~21, ~29; transcript 9/22'},

{id:'L01-041', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'recall',
 concept:'metoprolol-predict-effect', tags:['metoprolol','beta1','poll'], source:'both',
 stem:'Which statement is CORRECT about metoprolol?',
 options:[
  {t:'Metoprolol is a reversible β1 receptor antagonist', correct:false, why:'True, but not the only true statement.'},
  {t:'Its sites of action include the heart', correct:false, why:'True, but not the only true statement.'},
  {t:'Bradycardia is a predictable adverse reaction', correct:false, why:'True, but not the only true statement.'},
  {t:'Above about 200 mg it begins to affect β2 receptors', correct:false, why:'True, but not the only true statement.'},
  {t:'All of the above', correct:true, why:'Every statement is correct: reversible β1 antagonist, site of action the heart (also kidneys and brain), bradycardia as an ADR, and loss of β1 selectivity above about 200 mg.'}],
 teach:'Metoprolol is the Day 1 example drug: MOA reversible β1 receptor antagonist; SOA heart, kidneys and brain; ADR bradycardia and fatigue; DDI with other drugs that lower heart rate. It stays β1-selective up to about 200 mg. His test tip: when two statements other than a select-all are definitely correct, choose all of the above.',
 quote:'if there are two answers other than a select all that you know absolutely are correct, just go for the all the above.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~9, ~21; transcript 9/22'},

{id:'L01-042', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'recall',
 concept:'intrinsic-activity-antagonist', tags:['theory','poll'], source:'both',
 stem:'Which statement is INCORRECT?',
 options:[
  {t:'Potency depends on affinity and efficacy', correct:false, why:'Correct: affinity and efficacy are the two factors intrinsic to the drug that set its potency, so this is not the incorrect statement.'},
  {t:'Affinity depends on the bonds a drug forms', correct:false, why:'Correct: covalent, hydrogen, ionic and van der Waals bonds make binding stronger or weaker.'},
  {t:'A partial agonist has an intrinsic activity of zero', correct:true, why:'Incorrect: zero intrinsic activity is the antagonist. A partial agonist has an intrinsic activity between 1% and 99%.'},
  {t:'An antagonist has affinity but does nothing to the receptor', correct:false, why:'Correct: antagonists bind the receptor with zero intrinsic activity.'},
  {t:'All of the above', correct:false, why:'Only one statement is incorrect; the other three are his own definitions.'}],
 teach:'Intrinsic activity: full agonist 100%, partial agonist 1–99%, antagonist zero. An antagonist has affinity, so it binds, but does nothing to the receptor. Affinity comes from the bonds the drug forms, and potency depends on affinity, efficacy and the tissue.',
 quote:'100% is your full agonist, between 1% and 99% is your partial, and my antagonist, there are zero intrinsic activity. They have affinity, they can bind the receptor, but they don’t do anything to the receptor.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~21, ~28; transcript 9/22'},

{id:'L01-043', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'intro', skill:'apply',
 concept:'metoprolol-ddi', tags:['metoprolol','ddi'], source:'both',
 stem:'A patient taking metoprolol, a β1 receptor antagonist with its site of action in the heart, starts a second drug that also lowers heart rate. What drug–drug interaction is predicted?',
 options:[
  {t:'Heart rate would fall too far', correct:true, why:'Anything that also lowers heart rate adds to the β1 block in the heart; the predicted interaction is excessive slowing, the bradycardia he lists as the ADR.'},
  {t:'Heart rate would rise', correct:false, why:'Both drugs lower heart rate; neither one speeds the heart.'},
  {t:'No interaction, the drugs act at different receptors', correct:false, why:'The interaction is predicted from the shared effect on the heart, not from sharing a receptor.'},
  {t:'The patient would become hyponatremic', correct:false, why:'Hyponatremia is the thiazide diuretic prediction from losing sodium.'}],
 teach:'Knowing MOA (β1 antagonist) and SOA (heart) lets you predict the DDI without memorizing it: any drug that also lowers heart rate adds to metoprolol and slows the heart too far. His listed examples are verapamil, diltiazem and clonidine.',
 quote:'And what kind of drug drug interaction? Anything that would affect the heart and lower the heart rate.',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Pharmacodynamic variation: Changes in Components of Response Distal to the Receptor', t:'Because the response to a drug depends on the physiologic system it acts on, drugs that converge on the same downstream effect, here heart rate, add together in the patient even when they act through different mechanisms.'}],
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~9; transcript 9/22'},

{id:'L01-044', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'potency', skill:'apply',
 concept:'pharmacological-vs-apparent-potency', tags:['potency','pk'], source:'both',
 stem:'A drug with a large first-pass effect is switched from the oral route to IV, which has 100% bioavailability. What effect would that have on the apparent potency of the drug?',
 options:[
  {t:'Would increase the apparent potency', correct:true, why:'IV bypasses first-pass metabolism, so more of the dose reaches the site of action; the same dose now appears more potent.'},
  {t:'Would lower the apparent potency', correct:false, why:'Lower potency would follow from less drug reaching the site, the opposite of removing first-pass metabolism.'},
  {t:'Would have no effect on the apparent potency', correct:false, why:'Apparent potency depends on how much drug gets to the site of action, and the route changes exactly that.'}],
 teach:'First-pass metabolism in the liver decreases bioavailability, so less of an oral dose reaches the site of action; IV has 100% bioavailability. Pharmacokinetics sets how much drug gets to the site, and that is the apparent potency: the same dose appears more potent when more of it arrives.',
 quote:'pharmokinetics is going to be affecting how much of the drug gets to the site of action. Because that’s how it’s going to produce its effects.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~23–~24, ~27; transcript 9/22',
 note:'Slide and transcript disagree on the label. The slide puts absorption, distribution and elimination under apparent potency; in class he said ADME affects pharmacological potency. Use the slide grouping on the exam.'},

{id:'L01-045', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'drug',
 concept:'negative-efficacy-inverse-agonist', tags:['poll','loratadine','drug-list'], source:'both',
 stem:'Which of the following drugs is an inverse agonist?',
 options:[
  {t:'Loratadine', correct:true, why:'Loratadine is a selective H1 inverse agonist: it shuts the receptor down, negative efficacy.'},
  {t:'Metoprolol', correct:false, why:'Metoprolol is a reversible β1 antagonist: affinity with zero intrinsic activity.'},
  {t:'Norepinephrine', correct:false, why:'Norepinephrine activates β1 and α1 receptors; positive efficacy, an agonist.'},
  {t:'Acetylcholine', correct:false, why:'Acetylcholine binds the nicotinic receptor and opens its channel; positive efficacy, an agonist.'},
  {t:'Hydrochlorothiazide', correct:false, why:'Hydrochlorothiazide blocks the Na+/Cl− symporter in the distal tubule; it is the diuretic example, not an inverse agonist.'}],
 teach:'Drug classes by mechanism: agonists have efficacy, positive (full and partial) or negative (inverse); antagonists bind with zero intrinsic activity; allosterics change other drugs’ potency. Loratadine is the inverse agonist he named on Day 1; metoprolol is the antagonist; norepinephrine and acetylcholine activate their receptors.',
 quote:'What is loratadine? It’s Claritin, which is a selective H1 inverse agonist, right?',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~9, ~29, ~33, ~48, ~51; transcript 9/22'},

{id:'L01-046', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'drug',
 concept:'intrinsic-activity-antagonist', tags:['poll','metoprolol','drug-list'], source:'both',
 stem:'Which of the following drugs is a reversible antagonist?',
 options:[
  {t:'Norepinephrine', correct:false, why:'Norepinephrine binds β1 in the heart and increases heart rate; it activates the receptor.'},
  {t:'Epinephrine', correct:false, why:'Epinephrine, like norepinephrine, activates α1 receptors on smooth muscle; it is an agonist.'},
  {t:'Metoprolol', correct:true, why:'Metoprolol is the reversible β1 receptor antagonist (blocker): affinity with zero intrinsic activity.'},
  {t:'Loratadine', correct:false, why:'Loratadine is an inverse agonist; it has negative efficacy rather than zero intrinsic activity.'},
  {t:'Acetylcholine', correct:false, why:'Acetylcholine binds the nicotinic receptor and opens the channel; it is an agonist.'}],
 teach:'Antagonists have affinity but zero intrinsic activity: they bind and do nothing to the receptor. Metoprolol is a reversible β1 receptor antagonist. Norepinephrine, epinephrine and acetylcholine activate their receptors, and loratadine shuts H1 down (inverse agonist).',
 quote:'Metoprolol (Tropol XL) MOA: Reversible β1 receptor antagonist (blocker)',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~9, ~28–~29, ~48, ~55; transcript 9/22'},

{id:'L01-047', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'recall', multi:true,
 concept:'negative-efficacy-inverse-agonist', tags:['classes'], source:'both',
 stem:'Which of these drug classes have efficacy, positive or negative? Select all that apply.',
 options:[
  {t:'Full agonist', correct:true, why:'A full agonist activates the receptor: positive efficacy, intrinsic activity of 100%.'},
  {t:'Partial agonist', correct:true, why:'A partial agonist activates the receptor to a percentage of the maximal response: positive efficacy.'},
  {t:'Inverse agonist', correct:true, why:'An inverse agonist shuts the receptor down: negative efficacy.'},
  {t:'Antagonist', correct:false, why:'An antagonist has affinity but zero intrinsic activity; it binds and does nothing to the receptor.'}],
 teach:'Agonists are the drugs that have efficacy: full and partial agonists have positive efficacy, inverse agonists have negative efficacy. Antagonists, direct or indirect, reversible or irreversible, bind with zero intrinsic activity. Allosterics act on other drugs’ potency.',
 quote:'They can be divided into agonists. Those are drugs that have efficacy, positive and negative. So we have a full agonist, a partial agonist, and an inverse agonist.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~28–~29; transcript 9/22'},

{id:'L01-048', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'theory', skill:'recall',
 concept:'two-state-model-l', tags:['theory','two-state','poll'], source:'both',
 stem:'Which statement is CORRECT about the two-state model?',
 options:[
  {t:'Receptors exist in an active or an inactive state', correct:false, why:'True, but not the only true statement.'},
  {t:'The constant L sets how likely a receptor is inactive versus active', correct:false, why:'True, but not the only true statement.'},
  {t:'A drug with positive efficacy shifts receptors toward the active state', correct:false, why:'True, but not the only true statement.'},
  {t:'Cells can change receptor activity and number on their own', correct:false, why:'True, but not the only true statement.'},
  {t:'All of the above', correct:true, why:'Every statement is part of the two-state model: two receptor states, L setting their balance, drugs shifting that balance by their efficacy, and the cell having a say in receptor activity and number.'}],
 teach:'The two-state model is home base: receptors come as active or inactive; L determines how likely a receptor is found inactive versus active; cells move receptors back and forth and change their number; a bound drug with positive efficacy shifts the balance to active, one with negative efficacy shifts it to inactive.',
 quote:'this L constant over here. Determines how likely a receptor should be found on the inactive versus the active state. So ourselves can move them back and forth how they wanted.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~28; transcript 9/22'},

{id:'L01-049', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'drugs', skill:'tell',
 concept:'loratadine-vs-diphenhydramine', tags:['selectivity','histamine','poll'], source:'both',
 stem:'Loratadine is a non-selective antihistamine that binds H1, H2 and muscarinic receptors.',
 options:[
  {t:'True', correct:false, why:'That description is diphenhydramine, which binds H1, H2 and muscarinic receptors and is very non-selective.'},
  {t:'False', correct:true, why:'Loratadine is a selective H1 inverse agonist; diphenhydramine is the non-selective one that binds H1, H2 and muscarinic receptors.'},
  {t:'True only at doses above the usual dose', correct:false, why:'The statement swaps the two drugs; loratadine is the selective antihistamine at its usual dose, and the non-selective profile described belongs to diphenhydramine.'}],
 teach:'Two antihistamines at the same H1 receptor: loratadine is a selective H1 inverse agonist; diphenhydramine binds H1, H2 and muscarinic receptors, is very non-selective, and is the ingredient in nighttime products that puts most people to sleep.',
 quote:'What about diphenhydramine? That’s Benadryl. Benadryl not only binds to the H1, it binds to the H2. It binds to muscarinic receptors. It’s very non-selective.',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slide ~29; transcript 9/22'},

{id:'L01-050', lecture:'L01', prof:'Gottlieb', tier:'new', topic:'L01', sub:'nds', skill:'recall',
 concept:'nds-regulation', tags:['nds','poll'], source:'both',
 stem:'Which statement is CORRECT about natural dietary supplements (NDS)?',
 options:[
  {t:'NDS are regulated as food, with less FDA oversight than drugs', correct:false, why:'True, but not the only true statement.'},
  {t:'NDS stay on the market until they cause harm', correct:false, why:'True, but not the only true statement.'},
  {t:'Herbal products can interact with prescription and OTC drugs', correct:false, why:'True, but not the only true statement.'},
  {t:'Most patients do not report the supplements they take', correct:false, why:'True, but not the only true statement.'},
  {t:'All of the above', correct:true, why:'Every statement is correct: NDS are food, not drugs, so they get less oversight and stay on the market until harm is shown; herbals have active ingredients that interact; patients do not think supplements are pertinent.'}],
 teach:'NDS are regulated as food, not drugs, so the FDA oversees them less and they stay on the market until they cause harm. Herbals have active ingredients that can interact with prescription and OTC drugs and can cause side effects. Most patients do not think supplements are pertinent and do not report them. He expects about two common-sense supplement questions.',
 quote:'when we look at natural dietary supplements, they are treated as food, which means they have less oversight by the FDA. Which means that until they cause harm, they’re still in the market',
 cite:'Pharmacodynamics-Day-1-2026s.pdf slides ~16, ~20; transcript 9/22'}
);
