TOPICS.push({id:'L03', name:'Dose–response curves, potency and agonist interactions', prof:'Gottlieb', lecture:'L03',
  cite:'Day 3 (9/24) — Pharmacodynamics-Day_3_2026s.pdf',
  subs:[
    {id:'kd', name:'Affinity, Kd and mass action', cite:'slides ~3–~7; transcript 9/24'},
    {id:'drc', name:'Building and reading the dose–response curve', cite:'slides ~8–~18'},
    {id:'terms', name:'EC50/ED50, potency, intrinsic activity and efficacy', cite:'slides ~19–~29'},
    {id:'theory', name:'Receptor theory, two-state model and full agonists', cite:'slides ~30–~41'},
    {id:'fafa', name:'Full agonist plus full agonist', cite:'slides ~42–~49'},
    {id:'pa', name:'Partial agonists and full agonist plus partial agonist', cite:'slides ~50–~65'}
  ]});
QUESTIONS.push(
{id:'L03-001', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'recall',
 concept:'transporter-blocker-indirect-antagonist', tags:['poll'], source:'transcript',
 stem:'A drug inhibits a major transporter involved in removing norepinephrine from the neuronal synapse. How is this drug classified?',
 options:[
  {t:'Indirect antagonist', correct:true, why:'It acts upstream of the receptor (on the transporter), not at the norepinephrine binding site, so it is classified as indirect.'},
  {t:'Competitive antagonist', correct:false, why:'A competitive antagonist acts at the receptor binding pocket; this drug acts on the transporter.'},
  {t:'Inverse agonist', correct:false, why:'An inverse agonist binds the receptor and favors the inactive state; this drug does not bind the norepinephrine receptor.'},
  {t:'Partial agonist', correct:false, why:'A partial agonist binds and activates the receptor with lower efficacy; this drug acts on a transporter.'},
  {t:'Full agonist', correct:false, why:'A full agonist binds and fully activates the receptor; this drug acts on a transporter.'}],
 teach:'A drug that blocks the transporter removing norepinephrine from the synapse does not affect norepinephrine binding to its receptor. Indirect antagonists can work downstream from the receptor and also upstream from the receptor.',
 quote:'So you said it was an indirect, correct, because it’s not affecting the binding of norepinephrine to its receptor, right? This is affecting the transporter that removes norepinephrine from that system.',
 cite:'transcript 9/24 (in-class poll; no matching slide text in Pharmacodynamics-Day_3_2026s.pdf)'},

{id:'L03-002', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'apply',
 concept:'transporter-blocker-increases-apparent-potency', tags:['poll'], source:'transcript',
 stem:'A drug inhibits the transporter that removes norepinephrine from the neuronal synapse. What effect would this drug have on the potency of norepinephrine?',
 options:[
  {t:'Increase', correct:true, why:'More norepinephrine remains in the synapse for longer, so less of it is needed to produce its effect; it appears more potent.'},
  {t:'Decrease', correct:false, why:'Blocking removal leaves more norepinephrine available, not less.'},
  {t:'No change', correct:false, why:'Although the drug does not bind the norepinephrine receptor, it changes how much norepinephrine is available, which changes apparent potency.'},
  {t:'Abolish it', correct:false, why:'The drug does not prevent norepinephrine from binding its receptor.'}],
 teach:'Blocking the transporter leaves more norepinephrine in the synapse for a longer period of time. Because less norepinephrine is required to bind the receptors and produce its effects, it appears more potent. The professor linked this to how serotonin–norepinephrine reuptake inhibitors (SNRIs) work.',
 quote:'So it’s going to make norepinephrine appear to be more potent because it’s going to require less of it to bind the receptors to produce its effects, right?',
 cite:'transcript 9/24 (in-class poll; no matching slide text in Pharmacodynamics-Day_3_2026s.pdf)'},

{id:'L03-003', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'recall',
 concept:'law-of-mass-action', tags:[], source:'transcript',
 stem:'What does the law of mass action predict about drug–receptor binding?',
 options:[
  {t:'More drug or more receptors increases the chance of binding', correct:true, why:'The law of mass action states that increasing either drug or receptors increases binding capacity.'},
  {t:'Binding depends only on the number of receptors', correct:false, why:'The amount of drug also matters; more drug molecules increase the probability of binding.'},
  {t:'Binding depends only on drug efficacy', correct:false, why:'Mass action concerns amounts of drug and receptor, not efficacy.'},
  {t:'Adding more drug molecules never changes receptor occupancy at all', correct:false, why:'More drug molecules statistically increase the probability of binding a receptor.'}],
 teach:'The law of mass action says that the more receptors or the more drug present, the greater the capacity to bind. This lets us define the concentration that binds 50% of the receptors, which depends on affinity.',
 quote:'the loss of mass action is all it is saying is the more I have either of the receptors or the more I have either the drug, the greater the capacity of binding to something is going to be, right?',
 cite:'transcript 9/24 (no matching slide text in Pharmacodynamics-Day_3_2026s.pdf)',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Relation Between Drug Concentration & Response — Concentration-Effect Curves & Receptor Binding of Agonists', t:'Receptor-bound drug rises with the concentration of free drug, and when receptor number is increased a much lower agonist concentration is enough to occupy the same number of receptors.'}]},

{id:'L03-004', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'recall',
 concept:'kd-inverse-affinity', tags:[], source:'both',
 stem:'How is the dissociation constant (Kd) related to a drug’s affinity for its receptor?',
 options:[
  {t:'Smaller Kd, greater affinity', correct:true, why:'Kd is inversely proportional to affinity: more drug–receptor complex makes the denominator larger and Kd smaller.'},
  {t:'Larger Kd, greater affinity', correct:false, why:'This reverses the inverse relationship.'},
  {t:'Kd reflects efficacy, not affinity', correct:false, why:'Kd is a binding measure used to determine affinity; efficacy is read on the y-axis of a response curve.'},
  {t:'Kd is unrelated to affinity', correct:false, why:'The Kd is how affinity is determined.'}],
 teach:'Kd = [R][A]/[AR]. The more drug–receptor complex present, the larger the denominator and the smaller the Kd. The smaller the Kd, the more likely the drug is to bind and stay bound, and the lower the dose needed.',
 quote:'So the take-home message is that the smaller the coefficient of dissociation is, the more drugs receptors are going to find together, and thus the greater the affinity is going to be.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~31; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Concentration-Effect Curves & Receptor Binding of Agonists', t:'Kd is the concentration of free drug at which receptor binding is half-maximal, a binding measure distinct from the EC50 read from the effect curve. It characterizes affinity reciprocally: a low Kd means high binding affinity, and vice versa.'}]},

{id:'L03-005', fg:'binding-kd', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'calc',
 concept:'kd-calculation', tags:[], source:'transcript',
 stem:'A dish contains 10 receptors and 10 molecules of drug A. At one moment, 9 drug molecules are free, 9 receptors are free, and 1 drug–receptor complex is formed. Using Kd = [D][R]/[DR], what is the dissociation constant (Kd)?',
 options:[
  {t:'81', correct:true, why:'(9 × 9)/1 = 81.'},
  {t:'0.11', correct:false, why:'This is the value when 9 complexes form and only 1 drug and 1 receptor are free (1 × 1/9).'},
  {t:'9', correct:false, why:'This uses only one free term and ignores the other.'},
  {t:'1', correct:false, why:'This is the number of complexes, not the ratio.'}],
 teach:'Kd is the free drug times free receptor divided by the drug–receptor complex. For drug A: 9 × 9 / 1 = 81. For a drug with 1 free drug, 1 free receptor and 9 complexes, Kd = 1/9 = 0.11, a much smaller value and therefore a much greater affinity.',
 quote:'I have 9 receptors all alone, and I only have 1 drug bound to 1 receptor. So when I put in my little values, I come up with 81. That’s my value for my KD.',
 cite:'transcript 9/24 (no matching slide text in Pharmacodynamics-Day_3_2026s.pdf)',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Concentration-Effect Curves & Receptor Binding of Agonists', t:'Kd is the free drug concentration at which receptor binding is half-maximal. A drug that occupies a larger fraction of receptors at the same free concentration has the smaller Kd and the higher affinity.'}]},

{id:'L03-006', fg:'binding-kd', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'figure',
 concept:'binding-curve-affinity-x-axis', tags:[], source:'both',
 stem:'Binding curves (percent of receptors bound vs. log dose) are drawn for drugs A, B and C. Drug C reaches 50% binding at the lowest dose, drug A in the middle, and drug B at a dose 1000-fold higher than C. Which drug has the highest affinity?',
 options:[
  {t:'Drug C', correct:true, why:'C needs the smallest dose to bind 50% of receptors, so it has the smallest Kd and highest affinity.'},
  {t:'Drug B', correct:false, why:'B is furthest right; it has the largest Kd and the lowest affinity of the three.'},
  {t:'Drug A', correct:false, why:'A lies between C and B, so its affinity is intermediate.'},
  {t:'All three are equal', correct:false, why:'They bind 50% of receptors at different doses, so their Kd values differ.'}],
 teach:'Kd is the dose that binds 50% of the receptors on a binding curve. The further to the left a curve is, the smaller the dose required and the greater the affinity. Affinity is read on the x-axis.',
 quote:'Drug C because it requires less dose to bind 50% of the receptors, right?',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~3; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Concentration-Effect Curves & Receptor Binding of Agonists (Figure 2–1B)', t:'On a plot of receptor-bound drug against free drug concentration, Kd is the concentration at which occupancy is half-maximal. The drug whose curve reaches half-maximal binding at the lowest concentration has the lowest Kd and therefore the highest affinity.'}]},

{id:'L03-007', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'apply',
 concept:'kd-units', tags:['poll','exam-cue'], source:'transcript',
 stem:'Drugs A and B both bind beta-1, beta-2 and M3 receptors. At the beta-2 receptor in the lung, the dissociation constant (Kd) of drug A is 1 mM and that of drug B is 20 µM. Which drug has the highest affinity for the beta-2 receptors in the lung?',
 options:[
  {t:'Drug B', correct:true, why:'20 µM (micro = 10^-6) is much smaller than 1 mM (milli = 10^-3); the smaller Kd means higher affinity.'},
  {t:'Drug A', correct:false, why:'This compares only the numbers (1 vs 20) and ignores the units.'},
  {t:'Equal affinity', correct:false, why:'The Kd values differ once units are converted.'},
  {t:'Kd cannot rank affinity', correct:false, why:'Kd is how affinity is determined; the smaller Kd has the greater affinity.'}],
 teach:'Convert units before comparing Kd values: milli = 10^-3, micro = 10^-6, nano = 10^-9. 20 µM is much smaller than 1 mM, so drug B has the smaller Kd and greater affinity.',
 quote:'Because 20 micromolars is much smaller than 1 millimolar. So if you only focus on the number, you’re going to miss the question in the exam. You’ve got to look at the units as well.',
 cite:'transcript 9/24 (in-class poll; table not in deck text)',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Clinical Selectivity: Beneficial Versus Toxic Effects of Drugs', t:'Affinity is expressed through Kd in a reciprocal way: a low Kd means high affinity, so of two drugs at the same receptor, the one with the smaller Kd has the higher affinity.'}]},

{id:'L03-008', fg:'binding-kd', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'calc',
 concept:'kd-units', tags:['poll'], source:'transcript',
 stem:'Five drugs bind the beta-1 receptor. Drug C has a dissociation constant (Kd) of 100 nM. Expressed in molar, what is this Kd?',
 options:[
  {t:'1 × 10^-7 M', correct:true, why:'100 nM = 100 × 10^-9 M = 1 × 10^-7 M.'},
  {t:'1 × 10^-9 M', correct:false, why:'This is 1 nM; the factor of 100 was dropped.'},
  {t:'1 × 10^-6 M', correct:false, why:'This is 1 µM, ten times larger than 100 nM.'},
  {t:'1 × 10^-3 M', correct:false, why:'This is 1 mM; nano was confused with milli.'}],
 teach:'Nano is 10^-9. Taking two zeros out of 100 × 10^-9 gives 1 × 10^-7 M. In the poll this was the smallest Kd of the five drugs, so drug C had the greatest affinity.',
 quote:'Yes, because C has 100 moles, which is 1 to -9. So what you’re gonna do is you take two 0s out of that 100, you have 1 times 10 to -7.',
 cite:'transcript 9/24 (in-class poll; table not in deck text)',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Concentration-Effect Curves & Receptor Binding of Agonists', t:'Kd is a concentration, the free drug concentration at which half-maximal receptor binding is observed, so it is reported in concentration units.'}]},

{id:'L03-009', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'recall', multi:true,
 concept:'covalent-bond-irreversible-affinity', tags:['poll'], source:'transcript',
 stem:'A drug forms a covalent bond with its receptor at body temperature. Which statements apply to this drug? Select all that apply.',
 options:[
  {t:'Binding is irreversible', correct:true, why:'A covalent bond at body temperature cannot be broken.'},
  {t:'Highest affinity', correct:true, why:'It binds and does not come off, giving the highest affinity.'},
  {t:'Smallest Kd', correct:true, why:'Highest affinity corresponds to the smallest dissociation constant.'},
  {t:'Largest Kd', correct:false, why:'A large Kd means low affinity; this reverses the relationship.'},
  {t:'Lowest affinity of all bond types', correct:false, why:'Covalent bonds are the strongest and produce irreversible binding.'}],
 teach:'Covalent bonds are the strongest bonds a drug can form and produce irreversible binding. Because the bond cannot be broken, the drug has the highest affinity and the smallest Kd; these are related.',
 quote:'a drug that forms covalent bond at body temperature is gonna be irreversible, right? As such, you won’t be able to break that bond and it’s gonna have the highest affinity and thus the smallest kg. All those are related.',
 cite:'transcript 9/24 (in-class poll; no matching slide text)',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists', t:'Drugs that form a covalent bond with the receptor bind in an irreversible or nearly irreversible fashion.'}]},

{id:'L03-010', fg:'spare', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'apply',
 concept:'receptor-number-potency', tags:['poll'], source:'both',
 stem:'Two isolated hearts are kept in identical baths (same pH, temperature, flow). One heart has 10 receptors and the other has 100 receptors. The same dose of norepinephrine is given to both and heart rate is measured. What effect does the larger receptor number have on the potency of norepinephrine?',
 options:[
  {t:'Increases potency', correct:true, why:'More receptors raise the probability of binding, so less norepinephrine is needed; the curve shifts left.'},
  {t:'Decreases potency', correct:false, why:'More receptors make binding more likely, not less; this inverts the mass-action reasoning.'},
  {t:'No effect on potency', correct:false, why:'Affinity and efficacy are unchanged, but potency also depends on the tissue, including receptor number.'},
  {t:'Lowers its Kd', correct:false, why:'The drug is the same, so its Kd (affinity) is unchanged; only the tissue changed.'}],
 teach:'By the law of mass action, more receptors increase the probability of binding. Less norepinephrine is needed to bind the same number of receptors, so it appears more potent. Potency depends on affinity, efficacy and the tissue.',
 quote:'Then it’s going to appear to have a greater potency than it does with less receptors. So the take home message over here is that potency is not only going to be defined by the efficacy of the affinity, but also the tissue that is going to be bound to.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~7; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'The sensitivity of a tissue to a given agonist concentration depends not only on the receptor’s affinity (Kd) but also on the total number of receptors present. With ten times more receptors, a much lower agonist concentration produces the same half-maximal response.'}]},

{id:'L03-011', fg:'potency', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'tell', multi:true,
 concept:'receptor-number-potency', tags:[], source:'transcript',
 stem:'A tissue gains more receptors while the same drug, norepinephrine, is applied. Which statements are correct? Select all that apply.',
 options:[
  {t:'The drug’s Kd is unchanged', correct:true, why:'It is the same drug with the same Kd.'},
  {t:'Affinity is unchanged', correct:true, why:'The drug did not change, so affinity did not change.'},
  {t:'The tissue changed', correct:true, why:'Only the receptor population, a tissue factor, changed.'},
  {t:'The drug’s Kd became smaller', correct:false, why:'Kd is a property of the drug–receptor pair; the drug did not change.'},
  {t:'The curve shifts to the right', correct:false, why:'More receptors make the drug appear more potent, which shifts the curve to the left.'}],
 teach:'Adding receptors does not change the drug: its Kd, affinity and efficacy stay the same. What changes is the tissue it acts on, which alters potency. The body can up-regulate or down-regulate receptors, for example building tolerance to nicotine.',
 quote:'We didn’t change the drug. It’s the same drug, same KD. Now it just have more receptors available, so the affinity and efficacy has not changed. What changes the tissue that is working on it.',
 cite:'transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'Kd determines what fraction of receptors is occupied at a given free agonist concentration regardless of receptor number, so adding receptors does not alter Kd or affinity. It changes the tissue: a lower agonist concentration then gives a half-maximal response.'}]},

{id:'L03-012', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'kd', skill:'recall',
 concept:'potency-triad', tags:[], source:'both',
 stem:'Potency of a drug is determined by which combination of factors?',
 options:[
  {t:'Affinity, efficacy and tissue', correct:true, why:'The deck lists affinity, efficacy and cell/tissue/organ/organism (e.g., number of receptors).'},
  {t:'Affinity and efficacy only, without tissue factors', correct:false, why:'This omits the tissue, including receptor number.'},
  {t:'Efficacy and Emax only', correct:false, why:'Emax is the efficacy measure; affinity and tissue are missing.'},
  {t:'Kd alone', correct:false, why:'Kd measures binding only and does not account for the effect produced.'}],
 teach:'Potency is a combination of affinity, efficacy and the cell, tissue, organ or organism (for example, number of receptors). The combination of the three makes a drug more or less potent.',
 quote:'Affinity - Efficacy - Cell/Tissue/Organ/Organism - e.g., # of receptors',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~7; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Potency; Receptor-Effector Coupling & Spare Receptors', t:'Potency depends partly on the affinity (Kd) of receptors for the drug and partly on how efficiently the drug-receptor interaction is coupled to response. Tissue sensitivity also depends on the total number of receptors present, so the responding tissue contributes as well.'}]},

{id:'L03-013', fg:'drc-basic', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'drc', skill:'tell',
 concept:'ec50-vs-ed50', tags:[], source:'both',
 stem:'What distinguishes an EC50 (effective concentration producing 50% of the maximal response) from an ED50 (effective dose producing 50% of the response)?',
 options:[
  {t:'EC50 is a concentration in vitro; ED50 is a dose in vivo', correct:true, why:'Philosophically the same; EC50 uses concentration (isolated cell or organ), ED50 uses dose (living organism).'},
  {t:'EC50 measures efficacy; ED50 measures affinity', correct:false, why:'Both are measures of potency, not of efficacy or affinity alone.'},
  {t:'EC50 comes from binding studies; ED50 comes from response curves', correct:false, why:'Binding studies give Kd; both EC50 and ED50 come from response curves.'},
  {t:'EC50 is in vivo; ED50 is in vitro', correct:false, why:'This reverses the settings.'}],
 teach:'EC50 is the concentration producing 50% of the maximal response, typically in vitro (a petri dish or isolated organ). ED50 is the dose producing 50% of the response, typically in vivo. In vivo, absorption, distribution, metabolism and excretion (ADME) affect how much drug reaches the site of action, giving an apparent potency.',
 quote:'The difference is, is that one is quantified on a dose, and typically we use that for in vivo studies, something that is living, breathing, and the other is a concentration.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~8, ~21; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Relation Between Drug Concentration & Response; Dose & Response in Patients — Potency', t:'Potency refers to the concentration (EC50) or dose (ED50) required to produce 50% of a drug’s maximal effect. In vitro, the concentration-effect relation is simple; in patients, absorption, distribution and clearance alter the concentration reaching the receptors, so dose and response are more complex.'}]},

{id:'L03-014', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'drc', skill:'recall', multi:true,
 concept:'emax-reasons', tags:[], source:'transcript',
 stem:'A dose–response curve plateaus at its maximal effect (Emax). Which explanations can account for the plateau? Select all that apply.',
 options:[
  {t:'All receptors are occupied', correct:true, why:'Once every receptor is occupied, more drug cannot increase the response.'},
  {t:'The organ is at its physiological maximum', correct:true, why:'If a heart can only beat at 150 beats per minute, more norepinephrine cannot exceed that.'},
  {t:'The drug has become irreversible', correct:false, why:'Irreversibility is not one of the two reasons for the plateau; agonists are reversible.'},
  {t:'The dissociation constant (Kd) of the drug has increased', correct:false, why:'Kd is a binding measure and is not one of the two reasons for the plateau.'}],
 teach:'The ceiling (Emax) is reached either because all receptors are occupied or because the physiological system has reached its maximum capacity. Giving more drug beyond the ceiling produces no further benefit.',
 quote:'What are the two reasons why we have reached the Emacs and we can’t keep going up? All the receptors are occupied or I max out the physiological system, right?',
 cite:'transcript 9/24 (slide ~14 "Ceiling of effect")',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'The total number of receptors may limit the maximal effect a drug can produce. For some receptors the response reaches a maximum before full occupancy because downstream effectors, not the receptors, are the limiting component.'}]},

{id:'L03-015', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'drc', skill:'recall',
 concept:'reversibility-of-effect', tags:[], source:'both',
 stem:'On a dose–response curve, what does reversibility of effect mean for most agonists?',
 options:[
  {t:'The effect returns to zero when the drug is stopped', correct:true, why:'The drug is excreted or metabolized and unbinds, so the effect goes back to zero.'},
  {t:'The effect persists long after the drug is removed from the body', correct:false, why:'This describes irreversible binding, which the professor said he knows of for no agonist.'},
  {t:'The curve reverses direction at high doses', correct:false, why:'The curve plateaus at the ceiling; it does not reverse.'},
  {t:'The agonist becomes an antagonist', correct:false, why:'Reversibility refers to the effect ending, not a change in drug class.'}],
 teach:'In most drugs the effect is reversible: once the drug is stopped, it is excreted or metabolized and the effect goes back to zero. The professor stated he does not know of any agonist that is irreversible.',
 quote:'What it means once I stop giving the drug. The effect goes back to zero',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~15; transcript 9/24',
 note:'The handwritten annotation on slide ~15 extracts as "all agonist are irreversible", while the transcript says "I do not know of any agonist that is irreversible. They’re all reversible." Keyed to the transcript.'},

{id:'L03-016', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'drc', skill:'recall',
 concept:'threshold-definition', tags:[], source:'both',
 stem:'On a dose–response curve, what is the threshold?',
 options:[
  {t:'The concentration below which no response occurs', correct:true, why:'The deck defines threshold as the concentration of drug below which it produces no response.'},
  {t:'The concentration that produces 50% of the maximal response', correct:false, why:'That is the EC50.'},
  {t:'The dose at which the curve plateaus', correct:false, why:'That is the ceiling (Emax).'},
  {t:'The linear mid-section of the curve', correct:false, why:'That is the slope.'}],
 teach:'The threshold is the dose right before something happens: below it, no effect; above it, a response. Threshold, maximal response (Emax/ceiling), slope (linear mid-section) and EC50 are the key parts of the curve.',
 quote:'Concentration of the drug below which produces no response',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~21; transcript 9/24'},

{id:'L03-017', fg:'drc-basic', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'drc', skill:'tell',
 concept:'x-axis-affinity-y-axis-efficacy', tags:[], source:'both',
 stem:'On a dose–response curve with log dose on the x-axis, which pairing of axis and property is correct?',
 options:[
  {t:'X-axis: affinity; y-axis: efficacy', correct:true, why:'Left–right position reflects affinity; up–down (height) reflects efficacy.'},
  {t:'X-axis: efficacy; y-axis: affinity', correct:false, why:'This reverses the two axes.'},
  {t:'X-axis: dependent variable', correct:false, why:'The x-axis (dose) is the independent variable; the y-axis is dependent.'},
  {t:'Y-axis: potency only', correct:false, why:'Potency combines x and y information; the y-axis is where efficacy is measured.'}],
 teach:'The x-axis is the independent variable (dose), plotted in log units to give a sigmoid curve; affinity is read left–right. The y-axis is the dependent variable measured experimentally; efficacy is read up–down. Potency combines the two.',
 quote:'OK, so when you’re looking at the efficacy of a drug, we’re looking at the y axis, up or down. When you look at affinity x axis, left or right.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~16–~18; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Potency; Maximal efficacy', t:'Potency is read from the relative positions of curves along the dose axis, and maximal efficacy is the limit of the dose-response relation on the response axis. Potency depends partly on affinity (Kd), so left-right position reflects affinity, while curve height reflects efficacy.'}]},

{id:'L03-018', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'drc', skill:'apply',
 concept:'normalized-y-axis', tags:[], source:'both',
 stem:'Why is the y-axis of a dose–response curve expressed as normalized data (for example, % of maximum response) rather than raw beats per minute?',
 options:[
  {t:'To eliminate biological variability', correct:true, why:'People start from different baselines (resting heart rates of 60, 70 or 40), so percent change allows comparison.'},
  {t:'To convert dose into log units', correct:false, why:'Log units apply to the x-axis (dose), not the y-axis.'},
  {t:'To make the curve reach 100% for all drugs', correct:false, why:'Partial agonists never get to 100%; normalizing addresses different starting points between individuals.'},
  {t:'To measure the Kd directly', correct:false, why:'Kd comes from binding studies, not the response axis.'}],
 teach:'Individuals have different starting points (for example, resting heart rate). Expressing response as a percent change or % of maximum removes this biological variability so drugs can be compared directly.',
 quote:'Normalized data ... Eliminate biological variability',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~18; transcript 9/24'},

{id:'L03-019', fg:'potency', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'drc', skill:'figure',
 concept:'same-emax-leftmost-most-potent', tags:[], source:'both',
 stem:'Drugs A, B and C all reach the same maximal response. Curve A lies furthest left, B in the middle, and C furthest right. Which statement is correct?',
 options:[
  {t:'A is most potent; C has the lowest affinity', correct:true, why:'Equal efficacy, so the leftmost curve (A) has the greatest affinity and potency; C is furthest right.'},
  {t:'A is most efficacious; C is least', correct:false, why:'All three reach the same maximum, so efficacy is equal.'},
  {t:'C is most potent; A has the lowest affinity', correct:false, why:'This reverses the left–right reading.'},
  {t:'All three have equal potency', correct:false, why:'Different positions on the x-axis mean different EC50s and potencies.'}],
 teach:'When curves reach the same Emax, efficacy is equal and the difference is affinity. The curve requiring the lowest dose for an equivalent effect (furthest left) has the highest affinity and is the most potent.',
 quote:'First of all, do they all have the same efficacy? Yes. So what makes A more potent than B and C? Because they have a greater affinity, right?',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~17; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Potency', t:'Among drugs with equal maximal efficacy, the one whose curve lies further left along the dose axis is more potent, since a lower dose produces 50% of its maximal effect. Potency depends partly on the affinity (Kd) of receptors for the drug.'}]},

{id:'L03-020', fg:'efficacy', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'drc', skill:'figure',
 concept:'potency-vs-efficacy-mixed', tags:[], source:'both',
 stem:'Drug A reaches the highest maximal response. Drugs B and C reach the same, lower maximal response, and curve C lies to the left of curve B. Which statement is correct?',
 options:[
  {t:'C is more potent than B', correct:true, why:'B and C have equal efficacy, and C needs a smaller dose for an equivalent response.'},
  {t:'B is more potent than C', correct:false, why:'B is to the right of C, so it has lower affinity and lower potency.'},
  {t:'C is more efficacious than B', correct:false, why:'B and C reach the same maximum, so efficacy is equal.'},
  {t:'B has greater affinity than C does', correct:false, why:'The curve further right has the lower affinity.'}],
 teach:'Efficacy is read from the height of each curve; affinity from left–right position. B and C share the same Emax, so the one further left (C) has higher affinity and is more potent. B has lower affinity than C and lower efficacy than A.',
 quote:'He has lowest affinity than C, but equal efficacy to C. Which is more potent. C, because it requires the smallest dose to produce an equivalent receptor that all three drugs can produce.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~18; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Potency', t:'Potency is a position along the dose axis and maximal efficacy is a limit on the response axis. Two curves of the same height are compared for potency only by which lies further left, the one with the smaller EC50.'}]},

{id:'L03-021', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'terms', skill:'recall',
 concept:'slope-linear-midsection', tags:[], source:'both',
 stem:'Which part of a dose–response curve gives the greatest change in effect for the smallest change in dose?',
 options:[
  {t:'The slope (linear mid-section)', correct:true, why:'In the linear mid-section, a small change in dose gives the greatest change in effect.'},
  {t:'The threshold region', correct:false, why:'Near threshold, large dose changes produce very small changes in effect.'},
  {t:'The ceiling (Emax) region', correct:false, why:'At the ceiling, more dose produces little or no added effect.'},
  {t:'Every region of the curve equally, from threshold to the ceiling', correct:false, why:'Below and above the mid-section, dose changes produce much smaller effect changes.'}],
 teach:'The slope is the linear mid-section of the sigmoid curve. There a small change in dose produces the greatest change in effect. Below or above this region, large changes in dose give very small changes in effect.',
 quote:'This is I’m going to get the greatest change in the response with the smallest change in the dose.',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~20–~21; transcript 9/24'},

{id:'L03-022', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'terms', skill:'apply',
 concept:'steep-slope-risk', tags:['poll'], source:'transcript',
 stem:'Drug red has a very steep dose–response curve; drug black reaches the same maximum over a much wider dose range. What is the risk of the drug with the very steep curve?',
 options:[
  {t:'Small dose change: no effect to maximal effect', correct:true, why:'The steep curve moves from no effect to the maximum over a narrow dose range.'},
  {t:'It works more slowly after it is administered to a patient', correct:false, why:'A dose–response curve measures dose, not speed; the professor stressed it is not about time.'},
  {t:'It can never reach its maximal effect', correct:false, why:'Both drugs reach the maximum; they differ in dose range.'},
  {t:'Its effect cannot be reversed', correct:false, why:'Slope does not determine reversibility.'}],
 teach:'With a steep curve, a narrow dose range takes the response from none to maximal. A shallower curve offers a greater range of doses before a toxic effect, allowing the dose to be increased over time. Which is preferred depends on the scenario.',
 quote:'You’re going from having no effect at all to max it out all the way on the top, right?',
 cite:'transcript 9/24 (in-class poll; slide ~21 "Slope")',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Shape of Dose-Response Curves', t:'Extremely steep dose-response curves may have important clinical consequences if the upper portion of the curve represents an undesirable extent of response. The concern is how large a response a small increase in dose can produce.'}]},

{id:'L03-023', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'terms', skill:'recall',
 concept:'ec50-inverse-potency', tags:[], source:'both',
 stem:'How is the EC50 (effective concentration producing 50% of the maximal response), or the ED50, related to potency?',
 options:[
  {t:'Smaller EC50, greater potency', correct:true, why:'ED50/EC50 and potency are inversely proportional.'},
  {t:'Larger EC50, greater potency of the drug', correct:false, why:'This reverses the inverse relationship.'},
  {t:'EC50 measures efficacy', correct:false, why:'EC50 is the indicator of potency; efficacy is read on the y-axis.'},
  {t:'EC50 is unrelated to potency', correct:false, why:'EC50/ED50 is the measure of potency.'}],
 teach:'EC50/ED50 is the concentration or dose producing 50% of the maximal response to that drug. The smaller the EC50 or ED50, the further left the curve and the greater the potency; they are inversely proportional.',
 quote:'ED50/EC50↓ = ↑ Potency ... inversely proportional',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~22, ~29; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Potency', t:'Potency refers to the concentration (EC50) or dose (ED50) required to produce 50% of a drug’s maximal effect, so a larger EC50 means lower potency and a smaller EC50 greater potency. Potency is distinct from maximal efficacy, the limit on the response axis.'}]},

{id:'L03-024', fg:'potency', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'terms', skill:'calc',
 concept:'relative-potency', tags:[], source:'both',
 stem:'Drugs A and B are full agonists. The ED50 (dose producing 50% of the response) of A is 0.01 and the ED50 of B is 10 (same units). What is the relative potency of A compared with B (ED50 of B / ED50 of A)?',
 options:[
  {t:'1000 times', correct:true, why:'10 / 0.01 = 1000; A needs 1000 times less drug for an equivalent response.'},
  {t:'100 times', correct:false, why:'This misplaces one factor of 10.'},
  {t:'0.001 times', correct:false, why:'This divides ED50A by ED50B, inverting the ratio.'},
  {t:'10 times', correct:false, why:'This misplaces two factors of 10.'}],
 teach:'Relative potency = ED50B / ED50A. Drug A is 1000 times more potent than drug B because it requires 1000 times less drug to produce equivalent responses. The professor said exam math will be minimal and easy.',
 quote:'Relative Potency = ED50B/ED50A =1000X',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~23; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Potency; Quantal Dose-Effect Curves', t:'Relative potency is the ratio of equi-effective doses. If the ED50 values of two drugs are 5 mg and 500 mg, the first is 100 times more potent than the second: the larger ED50 divided by the smaller.'}]},

{id:'L03-025', fg:'partial', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'terms', skill:'figure', multi:true,
 concept:'four-drug-potency-efficacy', tags:['exam-cue'], source:'transcript',
 stem:'Four drugs are tested in the same tissue. Curves A and C plateau below 100%; curves B and D both plateau at 100%. Curve A requires the smallest dose to produce an equivalent effect. Which statements are correct? Select all that apply.',
 options:[
  {t:'A is the most potent', correct:true, why:'A requires the smallest dose to produce the equivalent effect.'},
  {t:'B and D are the most efficacious', correct:true, why:'Both reach the same maximal effect, just at different doses.'},
  {t:'A is the most efficacious', correct:false, why:'A is a partial agonist and never reaches 100%.'},
  {t:'C reaches 100% at high doses', correct:false, why:'A and C are partial agonists and never get to 100%.'},
  {t:'The most potent drug is always preferred', correct:false, why:'Which drug is preferred depends on the effect needed.'}],
 teach:'Potency is compared at equivalent effects, so the curve needing the smallest dose (A) is the most potent even if it is a partial agonist. Efficacy is the maximal effect, shared by B and D. Choosing a drug depends on the goal, for example a small blood pressure drop vs. killing all bacteria.',
 quote:'Now which of these is the most efficacious? Now we can say B and D, right? Because they both produce the same effect, they just require different doses to do that.',
 cite:'transcript 9/24 (figure not in deck text)',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Potency; Maximal efficacy', t:'A partial agonist can be the most potent drug if its EC50 is the smallest, while drugs reaching the highest maximum share the greatest maximal efficacy. Maximal efficacy is crucial when a large response is needed, so the most potent drug is not automatically preferred.'}]},

{id:'L03-026', fg:'potency', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'terms', skill:'figure', multi:true,
 concept:'five-drug-classification', tags:['poll','exam-cue'], source:'transcript',
 stem:'Five drugs, A–E, are plotted as dose–response curves on one graph. Curve A lies furthest left. Drug B plateaus at 100% of the maximal response; drugs A, C, D and E plateau lower, with D lowest. Which statements are correct? Select all that apply.',
 options:[
  {t:'A has the highest affinity', correct:true, why:'A is furthest left, so it has the smallest Kd and the highest affinity.'},
  {t:'B has the highest efficacy', correct:true, why:'B reaches the highest maximum (100%).'},
  {t:'D has the lowest efficacy', correct:true, why:'D has the lowest maximum.'},
  {t:'E is a partial agonist', correct:true, why:'E does not reach 100%, so it is not a full agonist.'},
  {t:'D has the highest affinity', correct:false, why:'Affinity is read on the x-axis; A is furthest left, not D.'},
  {t:'A is a full agonist like drug B', correct:false, why:'A does not reach 100%; being furthest left reflects affinity, not efficacy.'}],
 teach:'Affinity is read left–right: the curve furthest left (A) has the smallest Kd and the highest affinity. Efficacy is read up–down: B has the highest and D the lowest. A full agonist reaches 100% of the maximal response, so B is the full agonist and A, C, D and E are partial agonists.',
 quote:'is A the right answer? Because it has the lowest affinity, the smallest KD is gonna be further to the left. … B as in boy for the highest, D for the lowest, right? … Which of these drugs is the full agonist? B, which you are partial. A, C, D, and E. If you can’t get your 100%, you’re not a full agonist, right?',
 note:'In the transcript the professor says A has "the lowest affinity" in the same sentence as "the smallest KD is gonna be further to the left"; the poll asked for the highest affinity and A was keyed, so "lowest" is treated as a slip.',
 cite:'transcript 9/24 (in-class poll; figure not in deck text)',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists; Dose & Response in Patients', t:'Partial agonists produce a lower response at full receptor occupancy than full agonists, and this is not due to decreased affinity for the receptor. A curve can lie furthest left, indicating the highest affinity, while plateauing below the full agonist, indicating a partial agonist.'}]},

{id:'L03-027', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'terms', skill:'apply',
 concept:'most-efficacious-for-bacteria', tags:['poll'], source:'transcript',
 stem:'Drug A reaches a partial maximal effect at low doses. Drug B requires a higher dose but reaches 100% of the maximal effect. Which drug is most likely to kill 100% of a bacterial colony?',
 options:[
  {t:'Drug B', correct:true, why:'B is the most efficacious; it reaches 100%.'},
  {t:'Drug A', correct:false, why:'A is more potent but cannot reach 100%, leaving bacteria behind.'},
  {t:'Either; they are equal', correct:false, why:'They differ in maximal effect (efficacy).'},
  {t:'Neither drug', correct:false, why:'Drug B reaches the full effect.'}],
 teach:'When the goal is a complete effect, such as killing all bacteria, the most efficacious drug is chosen; bacteria left behind can grow again and become resistant. When a partial effect is enough, such as bringing systolic pressure from 136 to below 130, the most efficacious drug may not be needed.',
 quote:'hopefully you pick B because B will kill 100% of the bacteria colon is the most efficacious in doing that job.',
 cite:'transcript 9/24 (in-class poll; figure not in deck text)',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Maximal efficacy', t:'Maximal efficacy is the limit of the dose-response relation on the response axis and is crucial when a large response is needed. A more potent drug with lower maximal efficacy cannot match that response at any dose.'}]},

{id:'L03-028', fg:'efficacy', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'terms', skill:'figure',
 concept:'equal-ec50-efficacy-tiebreak', tags:['exam-cue'], source:'both',
 stem:'Drugs A and B act in the same tissue with equal affinity and equal EC50 (concentration producing 50% of the maximal response). Drug A reaches a higher maximal response than B. Why is A more potent than B?',
 options:[
  {t:'It has greater efficacy', correct:true, why:'With tissue and affinity held constant, efficacy is the only difference.'},
  {t:'It has greater affinity', correct:false, why:'Affinity is stated to be equal.'},
  {t:'It has a smaller EC50', correct:false, why:'The EC50 values are equal.'},
  {t:'Its tissue has more receptors', correct:false, why:'Both act in the same tissue, so tissue is held constant.'}],
 teach:'When tissue and affinity are equal and EC50 is the same, efficacy breaks the tie: the drug with the higher maximal response is the more potent. The deck summarizes this as equal ED50/EC50 with higher efficacy giving higher potency, while potency is not the same as efficacy.',
 quote:'So test question right here. Why would A be more potent than B? Because it has greater efficacy, right?',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~27; transcript 9/24',
 note:'Katzung 16e, Ch. 2 defines potency strictly as the EC50 or ED50 (position on the dose axis) and maximal efficacy as a separate parameter (the limit on the response axis); by that definition two drugs with equal EC50 are equally potent regardless of Emax. The deck (slide ~27, "equal ED50/EC50, ↑Efficacy = ↑Potency") and the transcript key "greater efficacy" as the reason A is more potent. The exam is written from the lecture, so this item keys efficacy.',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Potency; Receptor-Effector Coupling & Spare Receptors', t:'Potency depends partly on affinity (Kd) and partly on how efficiently the drug-receptor interaction is coupled to response, which separates a full agonist from a partial agonist of equal affinity. By this definition, drugs with identical EC50 values are equally potent whatever their maximal efficacy.'}]},

{id:'L03-029', fg:'partial', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'terms', skill:'tell',
 concept:'intrinsic-activity-vs-efficacy', tags:[], source:'both',
 stem:'Which statement correctly distinguishes intrinsic activity from efficacy?',
 options:[
  {t:'Efficacy also accounts for the tissue', correct:true, why:'Intrinsic activity did not account for the tissue; efficacy is the more comprehensive term.'},
  {t:'Intrinsic activity accounts for the tissue and receptor number', correct:false, why:'Ariëns’ intrinsic activity did not account for how many receptors are present.'},
  {t:'Efficacy is calculated exactly', correct:false, why:'Efficacy cannot be calculated directly; it is a relative measurement.'},
  {t:'Intrinsic activity of an antagonist is 1', correct:false, why:'Full agonist = 1; antagonist = 0.'}],
 teach:'Intrinsic activity (Ariëns) assigns full agonist = 1, partial agonist between 0 and 1, antagonist = 0, and depends on chemical structure. It did not account for the tissue, so it is incomplete. Efficacy is more comprehensive, includes the tissue, cannot be calculated directly, and is a relative measurement of ligands.',
 quote:'What he did not count was for the tissue, how many receptors are present in that system. So this is an incomplete theory that we can’t really use much',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~25–~26; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Dose & Response in Patients — Maximal efficacy (and its footnote)', t:'Efficacy denotes the relative maximal efficacy of agonists and partial agonists acting via the same receptor. Maximal efficacy may be determined by the drug’s mode of interaction with receptors or by characteristics of the receptor-effector system, so the responding tissue is part of the measure.'}]},

{id:'L03-030', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'theory', skill:'recall', multi:true,
 concept:'basic-drug-receptor-theory', tags:[], source:'both',
 stem:'Which statements belong to basic drug–receptor theory? Select all that apply.',
 options:[
  {t:'Multiple chemicals may bind the same receptor', correct:true, why:'Listed on the slide; for example, several beta blockers.'},
  {t:'A chemical may bind multiple receptors', correct:true, why:'Listed on the slide; acetylcholine binds nicotinic and muscarinic receptors.'},
  {t:'Receptors can be in an active or inactive state', correct:true, why:'Listed on the slide.'},
  {t:'Receptor recognition is independent of the chemical’s shape and size', correct:false, why:'Recognition occurs based on the chemical’s shape, size, etc.'},
  {t:'Receptors recognize only exogenous chemicals', correct:false, why:'Ligands can be endogenous as well as exogenous.'}],
 teach:'Cells have receptors that recognize specific chemicals based on shape, size and other properties. Multiple chemicals may bind the same receptor, and one chemical may bind multiple receptors; ligands can be endogenous or exogenous. The less selective a drug is, the more effects (side effects) it produces.',
 quote:'Multiple chemicals may bind the same receptor ... A chemical may bind multiple receptors ... Endogenous as well as exogenous ... Receptors can be on the active or inactive state',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~30; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Introduction (the receptor concept); Receptor Classes & Drug Development', t:'The molecular size, shape and electrical charge of a drug determine whether, and with what affinity, it binds to a particular receptor. Agonists include both drugs and natural ligands such as hormones and neurotransmitters, and one chemical can act on more than one receptor class.'}]},

{id:'L03-031', fg:'partial', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'theory', skill:'tell',
 concept:'full-vs-partial-agonist-summary', tags:[], source:'slide',
 stem:'Which feature separates a partial agonist from a full agonist?',
 options:[
  {t:'It cannot reach 100% of the system’s max', correct:true, why:'A partial agonist has lower efficacy and Emax less than 100%.'},
  {t:'It has negative efficacy at the receptor', correct:false, why:'Both full and partial agonists have positive efficacy.'},
  {t:'It prefers receptors in the inactive state', correct:false, why:'Both have the highest affinity for receptors in the active state.'},
  {t:'It binds irreversibly', correct:false, why:'The deck lists both as reversible drug–receptor interactions.'}],
 teach:'Full agonist: can reach 100% of the system’s max response, highest affinity for active-state receptors, positive efficacy. Partial agonist: same affinity preference and positive efficacy, but lower efficacy, Emax less than 100%, and cannot bring the response all the way to 100% or 0%.',
 quote:'Partial Agonist Summary ... Can NOT reach 100% of the system’s max response',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~41, ~63',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists; Receptor-Effector Coupling & Spare Receptors', t:'Partial agonists produce a lower response at full receptor occupancy than full agonists do, and this failure is not due to decreased affinity for the receptor. Full agonists shift the conformational equilibrium of receptors more strongly than partial agonists.'}]},

{id:'L03-032', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'fafa', skill:'figure', multi:true,
 concept:'fa-plus-fa', tags:[], source:'slide',
 stem:'Drug B, a full agonist, is given as a pretreatment, and a concentration–response curve (CRC) for drug A, a full agonist at the same receptor, is then built. Which changes to A’s curve occur? Select all that apply.',
 options:[
  {t:'Shift to the left', correct:true, why:'The apparent affinity of A increases.'},
  {t:'Increased baseline', correct:true, why:'Receptor activity is raised before A is added.'},
  {t:'No change to Emax', correct:true, why:'A is still able to reach Emax.'},
  {t:'Shift to the right', correct:false, why:'The deck shows the curve of A shifted left in the presence of B.'},
  {t:'Reduced Emax', correct:false, why:'Two full agonists do not reduce the ability to reach Emax.'}],
 teach:'Take-home message for a full agonist in the presence of another full agonist: increased apparent affinity of the agonist for the receptor (shift to the left), still able to reach Emax (no change to Emax), and an increase in the baseline receptor activity. The two agonists show mutual exclusion at the same receptor.',
 quote:'THM: Full agonist (FA) in the presence of another FA ... Increase Apparent Affinity of Agonist for the Receptor (shift to the left) ... Still able to reach Emax (no change to Emax) ... Increase in the baseline (receptor activity)',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~49'},

{id:'L03-033', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'pa', skill:'recall',
 concept:'partial-agonist-table', tags:[], source:'both',
 stem:'Which partial agonist is correctly matched with its receptor and use?',
 options:[
  {t:'Albuterol – β2 – bronchodilator', correct:true, why:'Listed in the partial agonist table.'},
  {t:'Varenicline – μ-opioid – analgesic', correct:false, why:'Varenicline is a nicotinic (Nn) partial agonist for smoking cessation; buprenorphine is the μ-opioid analgesic.'},
  {t:'Pilocarpine – α1 – decongestant', correct:false, why:'Pilocarpine is muscarinic (glaucoma); oxymetazoline is the α1 nasal decongestant.'},
  {t:'Aripiprazole – Nn – glaucoma', correct:false, why:'Aripiprazole is a D2 partial agonist for schizophrenia and bipolar disorder.'}],
 teach:'Partial agonist table: albuterol (β2, bronchodilator), buprenorphine (μ-opioid, analgesic), oxymetazoline (α1, nasal decongestant), pilocarpine (muscarinic, glaucoma), varenicline (nicotinic Nn, smoking cessation), aripiprazole (D2, schizophrenia and bipolar). The professor noted that albuterol does not need to open airways 100% to help a patient with asthma breathe.',
 quote:'Albuterol β2 Bronchodilator',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slide ~53; transcript 9/24',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists', t:'Buprenorphine is a partial agonist of mu-opioid receptors and is used as an analgesic.'}]},

{id:'L03-034', fg:'partial', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'pa', skill:'tell', multi:true,
 concept:'fa-plus-pa-aripiprazole', tags:[], source:'slide',
 stem:'Dopamine (maximal effect, Emax, 100%) and aripiprazole (Emax 60%) compete for the same dopamine D2 receptor. Which statements are correct? Select all that apply.',
 options:[
  {t:'They differ in affinity and efficacy', correct:true, why:'The full agonist and partial agonist pair is labeled "Different Affinity & Efficacy".'},
  {t:'Aripiprazole is the partial agonist', correct:true, why:'Its Emax is 60%, so it cannot reach 100% of the system’s max response.'},
  {t:'They have equal affinity and efficacy', correct:false, why:'Equal affinity and efficacy describes the two full agonists (norepinephrine and Levophed), not this pair.'},
  {t:'Dopamine is the partial agonist', correct:false, why:'Dopamine reaches 100% (Emax 100%), so it is the full agonist.'},
  {t:'Aripiprazole reaches 100% alone', correct:false, why:'Aripiprazole alone has an Emax of 60%.'}],
 teach:'Dopamine (Emax 100%) is a full agonist and aripiprazole (Emax 60%) is a D2 partial agonist used for schizophrenia and bipolar disorder; the pair is shown as a full agonist competing with a partial agonist, with different affinity and efficacy. A partial agonist cannot reach 100% of the system’s max response and can behave like an agonist or an antagonist depending on the physiological state.',
 quote:'Full Agonists Competing with a Partial agonist / Different Affinity & Efficacy / Dopamine (Emax =100%) / Aripiprazole (Emax = 60%)',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~53–~54, ~57, ~63',
 note:'Not covered in the 9/24 transcript (deferred to the next lecture). The manic-patient slides do not state in text what level the combined response reaches, so this item tests only what the slide text states.',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists (Figure 2–4)', t:'Because a partial agonist cannot cause a maximal response even when it saturates all receptors, it competitively inhibits the responses produced by a full agonist at the same receptor. The two differ in efficacy: the partial agonist produces a lower maximal response at full occupancy.'}]},

{id:'L03-035', lecture:'L03', prof:'Gottlieb', tier:'new', topic:'L03', sub:'pa', skill:'recall',
 concept:'partial-agonist-dual-nature', tags:[], source:'slide',
 stem:'Varenicline (Chantix), a partial agonist indicated for smoking cessation, may act as an agonist or as an antagonist. What determines which?',
 options:[
  {t:'The physiological state of the subject', correct:true, why:'The deck states it depends on the physiological state of the subject (dual nature).'},
  {t:'Whether it binds covalently', correct:false, why:'Partial agonists are listed as reversible interactions.'},
  {t:'The route of administration', correct:false, why:'The deck ties the dual nature to physiological state, not route.'},
  {t:'Its intrinsic activity value of exactly 1', correct:false, why:'A partial agonist has intrinsic activity between 0 and 1.'}],
 teach:'A partial agonist can behave like an agonist or an antagonist depending on the physiological state (dual nature). The deck illustrates this with varenicline during smoking (nicotine present) and withdrawal.',
 quote:'It may act as an agonist or antagonist ... Depend on the Physiological State of the subject',
 cite:'Pharmacodynamics-Day_3_2026s.pdf slides ~63–~65',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Variation in Drug Responsiveness — Variation in Concentration of an Endogenous Receptor Ligand; Partial Agonists', t:'A partial agonist may exhibit dramatically different responses depending on the amount of endogenous agonist present. Whether it acts as an agonist or as an antagonist depends on the physiological state of the subject, specifically the level of full agonist it competes with.'}]}
);
