TOPICS.push({id:"L02", name:"Receptor signaling, drug–receptor binding & affinity", prof:"Gottlieb", lecture:"L02",
  cite:"Day 2 (9/23) — Pharmacodynamics-Day_2_2026s copy.pdf",
  subs:[
    {id:"review", name:"Day 1 review taught 9/23 (ion channels)", cite:"transcript 9/23"},
    {id:"gprot", name:"G proteins & tyrosine kinase receptors", cite:"slides ~3–~11"},
    {id:"nuc", name:"Nuclear hormone receptors", cite:"slides ~12–~14"},
    {id:"bond", name:"Drug–receptor binding forces", cite:"slides ~15–~17"},
    {id:"site", name:"Orthosteric vs allosteric binding", cite:"slides ~18–~24"},
    {id:"signal", name:"Signal transduction & crosstalk", cite:"slides ~25–~30"},
    {id:"class", name:"Affinity, efficacy & drug classes", cite:"slides ~31–~44"},
    {id:"kd", name:"Dissociation constant (Kd) & affinity", cite:"slides ~45–~51"},
    {id:"drc", name:"Potency & dose–response curves", cite:"slides ~52–~59"}
  ]});
QUESTIONS.push(
{id:"L02-001", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"review", skill:"tell",
 concept:"voltage-gated-opens-positive", tags:["poll"], source:"transcript",
 stem:"Which of the following opens when a membrane potential becomes more positive?",
 options:[
  {t:"Passive (always-open) ion channels", correct:false, why:"Passive channels are always open; nothing has to change for them to stay open."},
  {t:"Ligand-gated ion channels", correct:false, why:"Ligand-gated channels open when a hormone, neurotransmitter or ingested substance binds them, not in response to membrane potential."},
  {t:"Ion pumps", correct:false, why:"Pumps use energy (ATP) to move ions back to homeostasis; they reset the system rather than open with depolarization."},
  {t:"Voltage-gated calcium channels", correct:true, why:"Voltage-gated calcium channels depend on membrane potential and open only when the membrane becomes more positive."}],
 teach:"Ion channels are classed by what opens them. Passive channels (for example the funny (If) channel in the sinoatrial node) are always open; ligand-gated channels open when a ligand binds; voltage-gated channels open when the membrane potential becomes more positive; pumps use ATP to restore ion balance.",
 quote:"And then we have calcium channels, which are voltage-gated calcium channels that only opens when the membrane becomes more positive, right?",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Signaling Mechanisms & Drug Action — Ion Channels (p. 9–10 of 18)', t:'Ligand-gated ion channels open when a ligand binds them. Voltage-gated ion channels do not bind neurotransmitters directly but are controlled by membrane potential, through a charged domain that serves as the voltage sensor for channel opening.'}],
 cite:"Day 1 material reviewed in class (no Day 2 slide); transcript 9/23"},

{id:"L02-002", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"gprot", skill:"tell",
 concept:"g-alpha-effector-messenger", tags:[], source:"both",
 stem:"Which pairing of G protein α subunit → effector → second messenger is correct? (AC = adenylate cyclase; PLC = phospholipase C; cAMP = cyclic AMP; IP3 = inositol phosphate 3)",
 options:[
  {t:"Gαs → PLC → ↑ IP3, Ca++", correct:false, why:"Gαs acts on AC and increases cAMP; PLC and IP3 belong to Gαq."},
  {t:"Gαi → AC → ↑ cAMP", correct:false, why:"Gαi is inhibitory; it acts on AC but suppresses cAMP."},
  {t:"Gαq → PLC → ↑ IP3, Ca++", correct:true, why:"Gαq activates PLC, which makes IP3; IP3 releases Ca++ from the endoplasmic reticulum."},
  {t:"Gαq → AC → ↑ cAMP", correct:false, why:"AC and cAMP go with Gαs (increase) and Gαi (decrease), not Gαq."},
  {t:"Gαi → PLC → ↓ IP3 and Ca++", correct:false, why:"Gαi acts on AC, not PLC."}],
 teach:"The three α subunits are Gαs (stimulation), Gαi (inhibition) and Gαq (positive, through calcium). Gαs increases cAMP through AC, Gαi suppresses cAMP through AC, and Gαq increases IP3 and Ca++ through PLC. Adenylate cyclase pairs with cyclic AMP; phospholipase C pairs with IP3.",
 quote:"The alphai, which is the opposite, also is going to be associated with the AC, but in this case it's going to suppress the camp. And then the alpha Q is going to increase IP3 and calcium.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'G Proteins & Second Messengers; Table 2–1 (p. 10–11 of 18)', t:'Gs stimulates adenylyl cyclase, which converts ATP to cAMP, while Gi proteins decrease adenylyl cyclase and lower cAMP. Gq stimulates phospholipase C, which raises IP3, diacylglycerol and cytoplasmic calcium.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~3; transcript 9/23"},

{id:"L02-003", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"gprot", skill:"apply",
 concept:"alpha2-gi-decreases-camp", tags:[], source:"both",
 stem:"Norepinephrine binds an α2 adrenergic receptor in the central nervous system (CNS). The receptor is coupled to Gαi. What happens to cyclic AMP (cAMP) in that cell?",
 options:[
  {t:"cAMP decreases", correct:true, why:"Gαi inhibits adenylate cyclase, so less cAMP is made, giving less signaling and less excitation."},
  {t:"cAMP increases", correct:false, why:"An increase in cAMP is the Gαs (stimulatory) result, as with β1 receptors."},
  {t:"cAMP is unchanged", correct:false, why:"An agonist at a Gαi-coupled receptor activates the inhibitory pathway; it does not leave cAMP unchanged."},
  {t:"IP3 (inositol phosphate 3) and Ca++ rise", correct:false, why:"IP3 and Ca++ are the Gαq second messengers (for example α1 receptors), not Gαi."}],
 teach:"An agonist activates whatever pathway the receptor is coupled to. The α2 adrenergic receptor is coupled to Gαi, which inhibits adenylate cyclase; less cAMP means less signaling, and drugs that activate α2 suppress sympathetic outflow. The pathway is reversed when the GTP is hydrolyzed back to GDP and norepinephrine unbinds.",
 quote:"What does the I stand for? Inhibitory, which means that it's going to cause an inhibition of the AC, and I'm going to have less camp being produced.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Table 2–1 G proteins and their receptors and effectors; Variation in Drug Responsiveness (p. 11, 17 of 18)', t:'α2-Adrenergic receptors couple to the Gi family of G proteins. Gi decreases adenylyl cyclase activity and therefore decreases cAMP.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~3; transcript 9/23"},

{id:"L02-004", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"gprot", skill:"recall",
 concept:"gtp-exchange-dissociation", tags:["poll"], source:"transcript",
 stem:"During activation of a G protein–coupled receptor (GPCR), which step triggers the α subunit to separate from the β and γ subunits?",
 options:[
  {t:"GDP is replaced by GTP", correct:true, why:"Removal of the diphosphate (GDP) and replacement with the triphosphate (GTP) triggers the subunits to separate."},
  {t:"GTP is hydrolyzed to GDP", correct:false, why:"Hydrolysis of GTP to GDP is the reversal signal that lets α, β and γ reassociate."},
  {t:"RGS protein binds the α subunit", correct:false, why:"The RGS protein speeds removal of the extra phosphate, which ends signaling."},
  {t:"cAMP binds the receptor", correct:false, why:"cAMP is a downstream second messenger made by adenylate cyclase; it does not bind the receptor."},
  {t:"The agonist unbinds the receptor", correct:false, why:"Agonist unbinding is part of reversing the pathway, not activating it."}],
 teach:"Sequence: the agonist binds, the receptor is activated and changes shape, the G protein (transducer) senses the change, GDP comes off and GTP comes in, and the α subunit separates from βγ to act on an effector (adenylate cyclase or phospholipase C). Reversal: GTP is hydrolyzed to GDP naturally or faster with the RGS protein, the subunits reassociate, and the drug unbinds.",
 quote:"The GDP, as in diphosphate, has to come off, and the GTP, as in triphosphate, has to come in, right?",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'G Proteins & Second Messengers; Figure 2–10 and Figure 2–11 (p. 10–11 of 18)', t:'Agonist binding reduces the nucleotide affinity of the G protein, so GDP dissociates and GTP replaces it. This exchange switches the G protein from its inactive GDP-bound form to its active GTP-bound form.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~3; transcript 9/23"},

{id:"L02-005", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"gprot", skill:"recall", multi:true,
 concept:"gprotein-reversal", tags:[], source:"both",
 stem:"Which events end or reduce signaling after a Gαs-coupled receptor has been activated? Select all that apply.",
 options:[
  {t:"GTP is hydrolyzed to GDP", correct:true, why:"Going from GTP to GDP is the signal for α, β and γ to reassociate."},
  {t:"RGS protein removes the extra phosphate", correct:true, why:"The RGS protein speeds up removal of the extra phosphate from GTP."},
  {t:"PDE enzyme breaks down cAMP", correct:true, why:"The PDE enzyme breaks down cyclic AMP (cAMP), reducing second-messenger signaling and amplification."},
  {t:"The agonist unbinds the receptor", correct:true, why:"Unbinding of the receptor is a trigger for things to reassociate back to where they were."},
  {t:"GDP is replaced by GTP", correct:false, why:"GDP-for-GTP exchange is the activating step, not a reversal step."},
  {t:"The α subunit activates adenylate cyclase (AC)", correct:false, why:"Activating AC makes more cAMP; it propagates the signal rather than ending it."}],
 teach:"Every pathway has a way forward and a way backward. G protein signaling stops when GTP is hydrolyzed to GDP (naturally, or faster with the RGS protein), the subunits reassociate and the agonist unbinds. The PDE enzyme lowers cAMP, which decreases amplification and the physiological response.",
 quote:"I have enzymes over here, for example, that the phosphorusase enzyme, the PDE, is gonna come and chew up that camp, and if I don't have camp, I can't activate the next one and the next one and the next one, and that's going to decrease the second messenger signing.",
 note:'Lecture and textbook differ. The lecture lists the agonist coming off the receptor as one of the steps that ends the signal. The textbook says the G protein stays active for seconds after the agonist has left, so what ends the signal is the G protein splitting its GTP. Use the lecture list on the exam.',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'G Proteins & Second Messengers; Well-Established Second Messengers — cAMP (p. 10, 13 of 18)', t:'G proteins hydrolyze GTP to GDP, and this hydrolysis inactivates the G protein. cAMP itself is degraded to 5′-AMP by cyclic nucleotide phosphodiesterases (PDEs).'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~3, ~29; transcript 9/23"},

{id:"L02-006", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"gprot", skill:"recall",
 concept:"rtk-dimerization", tags:[], source:"both",
 stem:"An inactive receptor tyrosine kinase (RTK) is a monomer. What happens next when a ligand binds its extracellular domain?",
 options:[
  {t:"Dimerization", correct:true, why:"Ligand binding induces two receptors to join (dimerize), the active form."},
  {t:"Tyrosine phosphatase activation", correct:false, why:"Tyrosine phosphatase removes the phosphate at the end of signaling; it is the reversal step."},
  {t:"GDP is exchanged for GTP", correct:false, why:"GDP/GTP exchange belongs to G protein–coupled receptors, not RTKs."},
  {t:"Cross-phosphorylation", correct:false, why:"Cross-phosphorylation of the kinase domain follows dimerization; it is step 3, not step 2."},
  {t:"Transfer to the nucleus", correct:false, why:"RTKs cross the membrane once and signal through their intracellular kinase domain."}],
 teach:"RTK activation steps: (1) the inactive receptor is monomeric, (2) ligand binding induces dimerization, (3) the kinase domains cross-phosphorylate, (4) phosphorylation forms docking sites and signaling complexes, (5) a tyrosine phosphatase removes the phosphate and resets the process.",
 quote:"1. Inactive receptor is monomeric state 2. Ligand binding induces Dimerization (active) 3. Cross-phosphorylation of the kinase domain 4. Phosphorylation forms docking sites & signaling complexes 5. Tyrosine Phosphatase (TP)",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Ligand-Regulated Transmembrane Enzymes Including Receptor Tyrosine Kinases; Figure 2–7 (p. 8 of 18)', t:'Ligand binding to the extracellular domain causes two receptor molecules to bind to one another, converting the receptor from its inactive monomeric state to an active dimeric state. Dimerization then activates the tyrosine kinase activity of the cytoplasmic domains.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~7–~9; transcript 9/23"},

{id:"L02-007", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"gprot", skill:"apply",
 concept:"ras-block-downstream", tags:[], source:"both",
 stem:"In the tyrosine kinase pathway Grb2 → GEF → RAS → RAF → MEK → ERK, a drug X binds RAS and stops it from functioning. What is the expected result?",
 options:[
  {t:"Reduced gene transcription and cell proliferation", correct:true, why:"With RAS blocked, RAF, MEK and ERK are not activated, so cells do not grow or divide."},
  {t:"Increased RAF, MEK and ERK signaling", correct:false, why:"RAF, MEK and ERK are downstream of RAS; blocking RAS removes their activation."},
  {t:"Increased gene transcription and cell proliferation", correct:false, why:"That is the effect of the active pathway, the opposite of blocking RAS."},
  {t:"Increased cyclic AMP production", correct:false, why:"Cyclic AMP is a G protein (Gαs) second messenger, not part of this RAS pathway."}],
 teach:"Receptor tyrosine kinases for insulin and growth factors signal through Grb2, GEF, RAS, RAF, MEK and ERK to gene transcription and cell proliferation. About 20–25% of cancers contain a RAS mutation, so these kinases are a good drug target in cancer. A drug that blocks RAS suppresses the cascade and behaves as an indirect antagonist.",
 quote:"Now, I don't have the RAF, I don't have the Mac, I don't have the ERC, my cells don't grow, my cells don't divide anymore, right?",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor Classes & Drug Development; Phosphorylation: A Common Theme (p. 14 of 18)', t:'Inhibitors can target the GTP-binding transducer proteins (Ras) that function downstream of tyrosine kinase growth factor receptors. Activated Ras stimulates growth factor signaling pathways, so a Ras inhibitor blocks that signaling.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~10–~11, ~41; transcript 9/23"},

{id:"L02-008", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"nuc", skill:"recall", multi:true,
 concept:"nuclear-receptor-ligands", tags:[], source:"both",
 stem:"Which ligands act through nuclear hormone receptors? Select all that apply.",
 options:[
  {t:"Androgens", correct:true, why:"Androgens are listed among the steroid hormones acting on nuclear hormone receptors."},
  {t:"Estrogens", correct:true, why:"Estrogens are listed among the steroid hormones acting on nuclear hormone receptors."},
  {t:"Glucocorticoids", correct:true, why:"Glucocorticoids are listed; they affect DNA and messenger RNA production."},
  {t:"Thyroid hormone", correct:true, why:"Thyroid hormone is listed with the nuclear hormone receptor ligands."},
  {t:"Insulin", correct:false, why:"Insulin acts on a receptor tyrosine kinase, a one-transmembrane receptor."},
  {t:"Epidermal growth factor", correct:false, why:"Epidermal growth factor acts on a receptor tyrosine kinase."},
  {t:"Norepinephrine", correct:false, why:"Norepinephrine acts on G protein–coupled adrenergic receptors."}],
 teach:"Nuclear hormone receptors are a superfamily of 48 receptors whose proteins are transcription factor regulators. Ligands include androgens, estrogens, glucocorticoids, thyroid hormone and vitamin D; they regulate gene expression (protein synthesis or mRNA turnover) in reproduction, inflammation, development and metabolism. Co-repressor binding keeps the receptor inactive; co-activator binding makes it active.",
 quote:"Steroid hormones ... Androgens, estrogens, glucocorticoids, thyroid hormone, and Vit D ... Regulates gene expression",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Intracellular Receptors for Lipid-Soluble Agents (p. 7–8 of 18)', t:'Lipid-soluble ligands that cross the plasma membrane and act on intracellular receptors include the steroids (corticosteroids, mineralocorticoids, sex steroids and vitamin D) and thyroid hormone. Insulin and epidermal growth factor act instead on receptor tyrosine kinases, and norepinephrine acts on G protein–coupled adrenoceptors.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~5, ~12; transcript 9/23"},

{id:"L02-009", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"nuc", skill:"apply",
 concept:"aldosterone-mr-mechanism", tags:[], source:"both",
 stem:"Aldosterone binds the mineralocorticoid receptor (MR) in a collecting-duct principal cell. What is the result?",
 options:[
  {t:"More pumps and channels; Na+ reabsorbed, K+ excreted", correct:true, why:"MR activation codes for mRNA for more Na+/K+ ATPase pumps and channels; sodium is reabsorbed and potassium is excreted."},
  {t:"Fewer pumps and channels; Na+ excreted, K+ retained", correct:false, why:"That is the effect of blocking the MR (spironolactone), not of aldosterone."},
  {t:"More pumps and channels; K+ reabsorbed and Na+ excreted", correct:false, why:"Aldosterone is sodium saving and potassium wasting, not the reverse."},
  {t:"Immediate opening of existing Na+ channels only", correct:false, why:"The MR is a nuclear receptor; it works through messenger RNA to make new pumps and channels."}],
 teach:"The MR is a nuclear receptor: aldosterone binding leads to messenger RNA coding for more pumps and channels in the principal cell. Sodium is reabsorbed (water follows) and potassium is excreted, so aldosterone is a sodium-saving, potassium-wasting hormone. Spironolactone is an MR antagonist that spares potassium and wastes sodium, a weak diuretic.",
 quote:"Aldosterone is going to come and bind to its receptor, the MR receptor, the immunocord cord receptor, and by binding to that MR receptor, it's gonna code for messenger RNA for more pumps and more channels.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Intracellular Receptors for Lipid-Soluble Agents (p. 7–8 of 18)', t:'Mineralocorticoids act on intracellular receptors that regulate gene transcription by binding to response elements on DNA. Their effects appear only after a lag period, the time required for synthesis of new proteins, so they cannot alter a physiologic state within minutes.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~13–~14; transcript 9/23"},

{id:"L02-010", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"bond", skill:"recall",
 concept:"affinity-depends-on-bonds", tags:["poll"], source:"both",
 stem:"Affinity of a drug for the receptor is dependent on which of the following?",
 options:[
  {t:"The type of chemical bonds it forms", correct:true, why:"Covalent, ionic, hydrogen and van der Waals bonds dictate how likely a drug is to bind and stay bound."},
  {t:"The number of receptors the cell makes", correct:false, why:"Receptor number is the cell's business, not a property of the drug's binding."},
  {t:"Its ability to change the receptor state", correct:false, why:"Changing the receptor state is efficacy, not affinity."},
  {t:"How well the drug is absorbed", correct:false, why:"Absorption is pharmacokinetics, not drug–receptor binding."}],
 teach:"Affinity is how likely a drug is to bind and stay bound to a receptor. It depends on the molecular forces (bonds) between drug and receptor: covalent bonds are very strong, while van der Waals bonds are weak.",
 quote:"Remember, affinity is how likely a drug is to bind and stay bound to a receptor, and the binding of a drug to the receptor is going to be depending on what type of bonds they form covalent bonds, hydrogen bonds, ion bonds.",
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~15, ~31; transcript 9/23"},

{id:"L02-011", fg:"irreversible", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"bond", skill:"tell", multi:true,
 concept:"covalent-irreversible-terms", tags:[], source:"both",
 stem:"Drug binding through a covalent bond is described by which terms? Select all that apply.",
 options:[
  {t:"Irreversible", correct:true, why:"Covalent bonds are irreversible at body temperature."},
  {t:"Insurmountable", correct:true, why:"Irreversible, insurmountable and non-competitive all mean the same property."},
  {t:"Non-competitive", correct:true, why:"Irreversible, insurmountable and non-competitive all mean the same property."},
  {t:"Reversible", correct:false, why:"Reversible describes ionic, hydrogen and van der Waals binding."},
  {t:"Surmountable", correct:false, why:"Surmountable describes weaker, reversible bonds that can be outcompeted."},
  {t:"Competitive", correct:false, why:"Competitive describes reversible binding."},
  {t:"Short duration of action", correct:false, why:"Covalent binding gives a long duration of action."}],
 teach:"A covalent bond forms when two atoms share a pair of electrons; it is irreversible at body temperature and gives a long duration of action. Irreversible, insurmountable and non-competitive are three names for the same property. Ionic, hydrogen and van der Waals bonds are reversible, surmountable and competitive.",
 quote:"They can be classified as irreversible, insurmountable, and non-competitive, which means is They all mean the same thing.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists (p. 6 of 18)', t:'A noncompetitive antagonist, which often binds irreversibly by forming a covalent bond, cannot be surmounted by agonists irrespective of their concentration. Its duration of action depends on receptor turnover rather than on its own elimination.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~15; transcript 9/23"},

{id:"L02-012", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"bond", skill:"recall",
 concept:"phenoxybenzamine-covalent", tags:[], source:"both",
 stem:"Which drug binds its receptor irreversibly through a covalent bond?",
 options:[
  {t:"Phenoxybenzamine", correct:true, why:"Phenoxybenzamine is an irreversible, non-competitive, insurmountable antagonist that forms covalent bonds."},
  {t:"Prazosin", correct:false, why:"Prazosin is a reversible, competitive, surmountable antagonist that forms weaker bonds."},
  {t:"Norepinephrine", correct:false, why:"Norepinephrine is a reversible agonist; it binds and eventually pops off."},
  {t:"Diazepam (Valium)", correct:false, why:"Diazepam is an allosteric agonist, and allosteric agonists and antagonists are reversible."}],
 teach:"Drugs listed as forming covalent (irreversible) bonds include aspirin, omeprazole and phenoxybenzamine. Once phenoxybenzamine is bound, the receptor has to be internalized and recycled and the body must make new ones.",
 quote:"And phenoxbenzamine is an irreversible covalent bond forming drug.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists (p. 6 of 18)', t:'Phenoxybenzamine is an irreversible α-adrenoceptor antagonist; its blockade is maintained even against very large amounts of catecholamine and cannot be reversed. Benzodiazepines such as diazepam act as allosteric modulators, and drugs acting at an allosteric site are often reversible.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~15, ~18; transcript 9/23"},

{id:"L02-013", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"bond", skill:"recall",
 concept:"weak-bonds-need-fit", tags:["in-class"], source:"both",
 stem:"Why must a drug that relies on hydrogen and van der Waals bonds fit the receptor pocket closely?",
 options:[
  {t:"Closer atoms allow more bonds to form", correct:true, why:"The better the fit, the closer the atoms get and the more bonds can form, so the drug stays bound long enough to act."},
  {t:"Weak bonds become covalent when close", correct:false, why:"Hydrogen and van der Waals bonds stay reversible; they do not turn into covalent bonds."},
  {t:"Close fit makes the binding irreversible", correct:false, why:"Drugs forming these bonds are reversible and eventually come off."},
  {t:"Fit determines how well it is absorbed", correct:false, why:"Absorption is pharmacokinetics; fit in the pocket concerns receptor binding."}],
 teach:"Hydrogen bonds (electrostatic attraction between H and atoms such as N, O and S) and van der Waals bonds (weak interactions when two atoms are brought close) are each weak, so the drug needs the right distance, size and charge in the pocket for enough bonds to form and keep it bound; a covalent binder only needs to bond enough to one component.",
 quote:"The better the fit of the drug into the receptor pocket, the closer atoms get and more bonds can form",
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~16; transcript 9/23"},

{id:"L02-014", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"bond", skill:"apply",
 concept:"stereoisomerism-potency", tags:[], source:"both",
 stem:"Levalbuterol is more potent than racemic albuterol. Which drug property accounts for the difference?",
 options:[
  {t:"Stereoisomer (chirality) composition", correct:true, why:"Levalbuterol is the more potent isomer of the racemic mixture, which contains both isomers."},
  {t:"Molecular size", correct:false, why:"Isomers have the same exact components; they differ in orientation, not size."},
  {t:"Covalent vs ionic bond type", correct:false, why:"The example concerns isomer orientation, not a change in bond type."},
  {t:"Number of receptors the cell expresses", correct:false, why:"Receptor number is a property of the cell, not of the drug."}],
 teach:"Drug size, drug shape and stereoisomerism (chirality) affect receptor binding. Isomers are mirror images with the same components; how they are oriented can make a drug more or less potent. Levalbuterol is the more potent isomer of racemic albuterol.",
 quote:"So, levo albuterol is the more potent isomer of the racemic mixture of albuterol, which has both confirmations of RNS, you know, isomers in it.",
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~17; transcript 9/23"},

{id:"L02-015", fg:"sites", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"site", skill:"tell",
 concept:"orthosteric-allosteric-poll", tags:["poll"], source:"both",
 stem:"Which of the following is correct?",
 options:[
  {t:"Allosteric agonists compete for the same binding pocket on the receptor", correct:false, why:"Allosteric agonists bind someplace else on the receptor; they do not compete for the orthosteric pocket."},
  {t:"Allosteric agonists have the highest affinity for the orthosteric binding pocket", correct:false, why:"Allosteric agonists do not bind at the orthosteric pocket at all."},
  {t:"Phenoxybenzamine has higher affinity than prazosin", correct:true, why:"Phenoxybenzamine forms covalent bonds and does not come off; prazosin forms weaker bonds and comes off."},
  {t:"In orthosteric interactions, two drugs can be bound at the same time", correct:false, why:"Orthosteric binding is one or the other; only one drug occupies the pocket at a time."}],
 teach:"Orthosteric drugs compete for the same binding pocket, so only one can be bound at a time. Allosteric drugs bind a different site and change the orthosteric pocket. The irreversible (covalent) antagonist phenoxybenzamine has the highest affinity; reversible prazosin binds and comes off.",
 quote:"So which drug has the greatest affinity? The one that forms covalent bond all day long, which are, are irreversible drugs, right?",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists (p. 6 of 18)', t:'Allosteric modulators bind a site separate from the orthosteric site, so they do not compete for the orthosteric pocket. Phenoxybenzamine is an irreversible antagonist whose block agonists cannot surmount, whereas a competitive antagonist can be displaced by high agonist concentrations.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~18–~20, ~37–~38; transcript 9/23"},

{id:"L02-016", fg:"sites", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"site", skill:"apply",
 concept:"orthosteric-competition", tags:[], source:"both",
 stem:"Prazosin is bound in the orthosteric pocket of an α1 receptor when norepinephrine arrives at that same receptor. What happens?",
 options:[
  {t:"Norepinephrine cannot activate that receptor", correct:true, why:"Both bind the same pocket, so while prazosin occupies it norepinephrine cannot bind and activate."},
  {t:"Both drugs bind and the effect is additive", correct:false, why:"Orthosteric binding is one or the other, never both at once."},
  {t:"Norepinephrine binds an allosteric site instead", correct:false, why:"Norepinephrine is an orthosteric agonist; it competes for the same pocket."},
  {t:"Prazosin permanently inactivates the receptor", correct:false, why:"Prazosin is reversible, competitive and surmountable; permanent binding describes phenoxybenzamine."}],
 teach:"Norepinephrine (agonist) and prazosin (reversible α1-selective antagonist) bind the same orthosteric pocket and compete. Only one can occupy the pocket at a time. Because prazosin is reversible, it eventually comes off and can be outcompeted.",
 quote:"It's going to bind to the same binding pocket as norepinephrine is binding to, and there is going to be a competition. Between the two.",
 note:"The transcript line reads 'if the prazosin is bound to that receptor, norepinephrine can activate the receptor'; from the competition context and 'it can be either one or the other, it can't be both', this is a transcription error for 'can't'.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists (p. 5–6 of 18)', t:'A competitive antagonist and the agonist compete for binding to the receptors, so the response depends on both concentrations. Increasing concentrations of a competitive antagonist progressively inhibit the agonist response, and sufficiently high agonist concentrations can surmount a given concentration of antagonist.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~18; transcript 9/23"},

{id:"L02-017", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"site", skill:"recall", multi:true,
 concept:"allosteric-effects", tags:[], source:"both",
 stem:"A drug binds a receptor at a site different from the orthosteric pocket. What can it do to an orthosteric drug at that receptor? Select all that apply.",
 options:[
  {t:"Increase its affinity", correct:true, why:"An allosteric drug can change the pocket so the orthosteric drug binds better."},
  {t:"Decrease its efficacy", correct:true, why:"An allosteric antagonist can decrease the affinity and/or efficacy of another drug."},
  {t:"Have no effect on it", correct:true, why:"Depending on how the pocket changes, some allosteric drugs affect neither affinity nor efficacy."},
  {t:"Displace it by competing for its pocket", correct:false, why:"Competing for the pocket is orthosteric behavior; allosteric drugs bind elsewhere."},
  {t:"Covalently lock the receptor inactive", correct:false, why:"All allosteric agonists and antagonists are described as reversible; they bind and come off."}],
 teach:"An allosteric (allotopic) drug binds at a different site and changes the orthosteric pocket. It can increase or decrease the affinity and/or efficacy of another drug, or have no effect, depending on what it does to the pocket. Allosteric agonists increase and allosteric antagonists decrease; both are reversible.",
 quote:"So some drugs may affect affinity, another drug may affect only the efficacy, another may affect the affinity in the efficacy, and others, they don't even know that it's there.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists (p. 6 of 18)', t:'A drug can act noncompetitively by binding to a site separate from the agonist binding site and modifying receptor activity without blocking agonist binding; such actions are often reversible. Negative allosteric modulators reduce receptor activity, and others increase it.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~20, ~39, ~42–~44; transcript 9/23"},

{id:"L02-018", fg:"sites", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"site", skill:"apply",
 concept:"diazepam-gaba-pam", tags:["exam-cue"], source:"both",
 stem:"Diazepam binds the GABA-A receptor, a chloride (Cl−) ion channel, at a site separate from where GABA (γ-aminobutyric acid) binds. What is the result?",
 options:[
  {t:"GABA binds better; more Cl− enters", correct:true, why:"Diazepam is a positive allosteric modulator: it increases the affinity and/or efficacy of GABA, so more chloride enters."},
  {t:"GABA is displaced; less Cl− enters", correct:false, why:"Diazepam does not compete for the GABA site; it binds someplace else."},
  {t:"Cl− leaves the neuron", correct:false, why:"Opening the GABA channel lets chloride move from outside to inside the cell."},
  {t:"Na+ enters; the neuron is more excitable", correct:false, why:"GABA is the major inhibitory pathway; the channel conducts chloride and shuts things down."}],
 teach:"GABA binds its orthosteric sites and opens the GABA-A channel; chloride enters, the membrane becomes more negative, and the person becomes less anxious and more sleepy. Diazepam, an allosteric agonist (positive allosteric modulator, PAM), binds elsewhere and increases GABA's affinity and/or efficacy, so more chloride enters faster or longer. Combining a benzodiazepine with alcohol puts two allosteric agonists on the same receptor and is dangerous.",
 quote:"Benzos increase the affinity And/or efficacy of GABA For its receptor",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists (p. 6 of 18)', t:'Benzodiazepines bind to an allosteric site on ion channels that are physiologically activated by GABA. They are positive allosteric modulators because they potentiate, rather than inhibit, the ability of the orthosteric agonist GABA to increase channel conductance.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~21–~24; transcript 9/23"},

{id:"L02-019", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"signal", skill:"recall", multi:true,
 concept:"second-messenger-examples", tags:["exam-cue"], source:"both",
 stem:"Which of the following are second messengers? (cAMP = cyclic AMP; PKA = protein kinase A; IP3 = inositol phosphate 3; AC = adenylate cyclase; PLC = phospholipase C) Select all that apply.",
 options:[
  {t:"cAMP", correct:true, why:"Cyclic AMP is the classic second messenger made by AC."},
  {t:"PKA", correct:true, why:"Protein kinase A is listed as a second messenger; anything below cAMP in the cascade counts."},
  {t:"IP3", correct:true, why:"IP3 is the second messenger made by PLC in the Gαq pathway."},
  {t:"Ca++", correct:true, why:"Calcium is listed as a second messenger (released by IP3 in the Gαq pathway)."},
  {t:"AC", correct:false, why:"Adenylate cyclase is the effector (signal amplifier) that makes cAMP."},
  {t:"β1 receptor", correct:false, why:"The β1 receptor is the receptor, not a second messenger."},
  {t:"PLC", correct:false, why:"Phospholipase C is the effector that makes IP3."}],
 teach:"Second messengers are small molecules created, degraded or moved by an enzyme, ion channel or transport protein (the effector). They diffuse near their site of synthesis and convey information to many targets. Examples: cAMP, PKA, protein kinase C (PKC), IP3 and Ca++; the receptor, adenylate cyclase and a calcium channel are not second messengers.",
 quote:"If there is camp at PKA, then select all, right? But you shouldn't be picking the receptor or the AC or the calcium channel.",
 note:'Lecture and textbook differ. The slide lists PKA and PKC as second messengers. The textbook counts only the small non-protein molecules (cAMP, calcium, IP3, DAG) as second messengers and calls PKA the enzyme that cAMP switches on. Use the slide list on the exam.',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Signaling Mechanisms & Drug Action; G Proteins & Second Messengers (p. 7, 10 of 18)', t:'Second messengers are nonprotein chemical mediators inside the cell; named examples are cAMP, calcium ion and the phosphoinositides. Adenylyl cyclase (AC) is the effector enzyme that converts ATP to cAMP, and phospholipase C (PLC) is the effector that produces IP3.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~29; transcript 9/23"},

{id:"L02-020", fg:"gpcr", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"signal", skill:"tell",
 concept:"transducer-identify", tags:["exam-cue"], source:"both",
 stem:"In the pathway epinephrine → β1 receptor → Gαs → adenylate cyclase (AC) → cyclic AMP (cAMP), which component is the transducer?",
 options:[
  {t:"Epinephrine", correct:false, why:"Epinephrine is the signal: anything that binds and activates the receptor."},
  {t:"β1 receptor", correct:false, why:"The β1 receptor is the receptor that the signal binds."},
  {t:"Gαs", correct:true, why:"The G protein senses and translates the change in receptor conformation; that is the transducer."},
  {t:"AC", correct:false, why:"AC is the effector (signal amplifier)."},
  {t:"cAMP", correct:false, why:"cAMP is the second messenger."}],
 teach:"Signal transduction runs signal (hormone, growth factor, agonist drug, neurotransmitter) → receptor → transducer (for example G proteins) → effector, the signal amplifier (adenylate cyclase, phospholipase C) → second messenger → physiological response. The transducer translates, integrates and coordinates the signal.",
 quote:"Our G protein, for example, can understand that change in the receptor. And by understanding and translating that change, it's going to be called the transducer.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Signaling Mechanisms & Drug Action; G Proteins & Second Messengers (p. 7, 10 of 18)', t:'The G protein is a GTP-binding signal transducer protein that the receptor stimulates and that in turn modulates production of a second messenger. The receptor detects the ligand, and the effector, adenylyl cyclase for cAMP, is the enzyme whose activity the G protein changes.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~26–~28; transcript 9/23"},

{id:"L02-021", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"signal", skill:"apply",
 concept:"crosstalk-net-response", tags:[], source:"both",
 stem:"Acetylcholine (ACh) activates muscarinic type 2 (M2) receptors coupled to Gαi, while norepinephrine (NE) activates β1 receptors coupled to Gαs, in the same heart cells at the same time. What determines the heart rate response?",
 options:[
  {t:"The net of opposing effects on cyclic AMP", correct:true, why:"Crosstalk between pathways in the same cell yields a net response: Gαs raises cAMP and heart rate, Gαi suppresses them."},
  {t:"Only the receptor that was activated first", correct:false, why:"The cell integrates all incoming information at once rather than following one receptor."},
  {t:"Only the β1 (Gαs) signal", correct:false, why:"The M2 (Gαi) signal also acts on adenylate cyclase and opposes it."},
  {t:"Only the M2 (Gαi) signal", correct:false, why:"The β1 (Gαs) signal also acts on adenylate cyclase and opposes it."},
  {t:"The sum of two increases in cyclic AMP", correct:false, why:"M2 is Gαi, which suppresses cAMP; the two pathways oppose each other."}],
 teach:"Crosstalk is interaction between signal transduction pathways within the same cell that yields a net response. In the heart, β1 (sympathetic, Gαs) increases cAMP and heart rate, while M2 (parasympathetic, Gαi) suppresses cAMP and decreases heart rate; both converge on adenylate cyclase.",
 quote:"Interaction between signal transduction pathways within the same cell yields a net response.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Table 2–1; Interplay Among Signaling Mechanisms (p. 11, 14 of 18)', t:'β-Adrenergic amines act through Gs to raise cAMP and heart rate, while muscarinic receptors couple to Gi, which lowers cAMP and slows the heart. Pathways active in the same cell at the same time may oppose one another, and the response reflects their interplay.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~30; transcript 9/23"},

{id:"L02-022", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"class", skill:"recall", multi:true,
 concept:"pd-general-rules", tags:[], source:"both",
 stem:"Which are general rules of pharmacodynamics? Select all that apply.",
 options:[
  {t:"Drug must reach the site of action", correct:true, why:"General rule 1: drugs have to get to the site of action to produce effects."},
  {t:"Drug must bind to and interact with a receptor", correct:true, why:"General rule 2, true for about 99% of drugs (osmotic diuretics are the stated exception)."},
  {t:"Drugs change an ongoing physiological system", correct:true, why:"General rule 3: drugs do not create anything; they modify an ongoing system."},
  {t:"Drugs create new physiological functions", correct:false, why:"Rule 3 states drugs do not create anything."},
  {t:"Drug must form a covalent bond with its receptor", correct:false, why:"Most receptor interactions are reversible (ionic, hydrogen, van der Waals); covalent binding is not a rule."}],
 teach:"Pharmacodynamics is the study of biochemical and physiological effects of drugs and their mechanisms of action. General rules: (1) the drug must reach the site of action, (2) the drug must bind to and interact with a receptor, (3) drugs do not create anything but change the ongoing physiological system. Rule 2 holds about 99% of the time; osmotic diuretics do not bind to anything.",
 quote:"1) Drug must reach the site of action 2) Drug must bind to and interact with a receptor 3) Drug do not create anything, but change the ongoing phys. system",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Introduction; Variation in Drug Responsiveness (p. 3–4, 16 of 18)', t:'Most drugs act by associating with a receptor, the cell component that interacts with the drug and initiates the events leading to the observed effect. Receptors normally mediate the actions of endogenous signals, so drugs acting on them modify regulation already in place.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~31; transcript 9/23"},

{id:"L02-023", fg:"efficacy", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"class", skill:"tell",
 concept:"efficacy-definition", tags:["poll"], source:"both",
 stem:"Which best describes efficacy?",
 options:[
  {t:"Ability of a drug to bind and stay bound to a receptor", correct:false, why:"Binding and staying bound is affinity."},
  {t:"Ability of a cell to increase its number of receptors", correct:false, why:"Receptor number is the cell's business, not a drug property."},
  {t:"Ability of a drug to change the receptor behavior", correct:true, why:"Efficacy is the drug changing the receptor state from inactive to active or active to inactive."},
  {t:"Ability of a drug to be absorbed into the body", correct:false, why:"Absorption is pharmacokinetics, not pharmacodynamics."}],
 teach:"Affinity describes the association between drug and receptor (molecular forces, bonds). Efficacy (intrinsic efficacy) describes the mechanism by which the drug changes the receptor. A drug with efficacy changes the receptor state; one with zero efficacy (a neutral antagonist) does not.",
 quote:"Efficacy is the ability of that drug to change the receptor behavior. It's activity, its state from active to inactive or inactive to active, right?",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Introduction; Receptor-Effector Coupling & Spare Receptors (p. 4–5 of 18)', t:'Agonists activate the receptor by binding it, whereas antagonists bind but do not activate; the conformational change an agonist produces in the receptor protein is the basis of activation. Affinity is a separate property that determines the concentration required to form drug–receptor complexes.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~31; transcript 9/23"},

{id:"L02-024", fg:"partial", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"class", skill:"tell",
 concept:"full-vs-partial-agonist", tags:[], source:"both",
 stem:"A full agonist and a partial agonist both have greater affinity for active receptors. What separates them?",
 options:[
  {t:"Partial agonist has lower positive efficacy", correct:true, why:"The full agonist activates receptors at 100%; the partial agonist has lower positive efficacy (1–99%)."},
  {t:"Partial agonist cannot bind inactive receptors", correct:false, why:"Both can bind to inactive receptors and activate them."},
  {t:"Partial agonist has negative efficacy", correct:false, why:"Negative efficacy defines an inverse agonist."},
  {t:"Partial agonist has zero efficacy", correct:false, why:"Zero efficacy defines a neutral antagonist."},
  {t:"Partial agonist binds an allosteric site", correct:false, why:"Full versus partial is about efficacy, not binding site."}],
 teach:"Full and partial agonists both have greater affinity for active receptors and both can bind inactive receptors and activate them. The full agonist activates receptors at 100% (positive efficacy); the partial agonist has lower positive efficacy than the full agonist (1–99%). A partial agonist only activates to its own efficacy.",
 quote:"Has greater affinity for active receptors, but lower (+) Efficacy than the FA (1-99%).",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Partial Agonists (p. 6 of 18)', t:'Partial agonists produce a lower response at full receptor occupancy than full agonists do. This failure is not due to decreased affinity: even at concentrations that saturate all receptors, a partial agonist cannot cause a maximal response.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~32–~34; transcript 9/23"},

{id:"L02-025", fg:"inverse", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"class", skill:"apply",
 concept:"inverse-agonist-vs-antagonist", tags:[], source:"transcript",
 stem:"A cell line has 50% of its receptors naturally active, producing cyclic AMP (cAMP). What happens to cAMP production after an inverse agonist compared with a competitive (neutral) antagonist?",
 options:[
  {t:"Inverse agonist: to zero; antagonist: stays at 50%", correct:true, why:"The inverse agonist shuts off active receptors; the neutral antagonist does not change receptor state."},
  {t:"Both drop cAMP to zero", correct:false, why:"A neutral antagonist has zero efficacy and leaves active receptors active."},
  {t:"Inverse agonist: stays at 50%; antagonist: to zero", correct:false, why:"This reverses the two; negative efficacy belongs to the inverse agonist."},
  {t:"Both leave cAMP at 50%", correct:false, why:"An inverse agonist has negative efficacy and shuts off active receptors."},
  {t:"Inverse agonist: rises to 100%; antagonist: to zero", correct:false, why:"Raising the signal is positive efficacy (agonist), not inverse agonism."}],
 teach:"An inverse agonist has highest affinity for inactive receptors and negative efficacy, so it shuts off receptors that are already active. A neutral antagonist has equal affinity for active and inactive states and zero efficacy; it only prevents agonists from binding and keeps receptors wherever they are.",
 quote:"So if I give an inverse agonist, I'm going to bring the production of camp to zero. But if I give you a competitive antagonist, say it's at 50%, because it's not changing the activity of the receptors, it's just binding and staying bound, so they have affinity but zero efficacy.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists (p. 5 of 18)', t:'A neutral antagonist binds receptors without activating them and leaves the basal level of receptor activity unchanged. An inverse agonist also reduces receptor activity below the basal level observed in the absence of any agonist.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~35–~38; transcript 9/23"},

{id:"L02-026", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"class", skill:"recall",
 concept:"neutral-antagonist-properties", tags:[], source:"both",
 stem:"Which describes a neutral (reversible) antagonist?",
 options:[
  {t:"Equal affinity for active and inactive states; zero efficacy", correct:true, why:"Neutral antagonists do not care about receptor state; it is all about affinity (ε = zero)."},
  {t:"Highest affinity for inactive states; negative efficacy", correct:false, why:"That describes an inverse agonist."},
  {t:"Greater affinity for active states; positive efficacy", correct:false, why:"That describes a full or partial agonist."},
  {t:"Greater affinity for active states; efficacy of 1–99% of the maximum", correct:false, why:"That describes a partial agonist."}],
 teach:"Neutral antagonists have no efficacy (ε = zero) and equal affinity for receptors in the active and inactive state. They work by occupying receptors and preventing agonists from binding, keeping each receptor in whatever state it is in. Irreversible antagonists have the highest affinity.",
 quote:"Neutral ... No Efficacy (ε = zero); equal affinity for receptors in the active and inactive state ... All about Affinity",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists (p. 5 of 18)', t:'Antagonists bind to receptors but do not activate them; they act by reducing the effects of agonists. An antagonist has no functional effect in the absence of an agonist, which distinguishes it from an inverse agonist that reduces receptor activity below basal level.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~37–~38; transcript 9/23"},

{id:"L02-027", fg:"inverse", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"class", skill:"apply",
 concept:"inverse-agonist-loratadine", tags:[], source:"both",
 stem:"Loratadine is taken during pollen season after histamine has already activated H1 receptors, and it shuts those receptors off. Which property allows this?",
 options:[
  {t:"Negative efficacy", correct:true, why:"An inverse agonist with negative efficacy inhibits a receptor that is already active."},
  {t:"Zero efficacy", correct:false, why:"Zero efficacy (neutral antagonist) keeps receptors in their current state; it would not shut off active ones."},
  {t:"Partial positive efficacy", correct:false, why:"Positive efficacy increases the signal."},
  {t:"Irreversible covalent binding", correct:false, why:"Loratadine is an inverse agonist; covalent binding is not the property named."},
  {t:"Allosteric binding", correct:false, why:"Inverse agonism is defined by negative efficacy, not by an allosteric site."}],
 teach:"Inverse agonists have the highest affinity for inactive receptors and negative efficacy: if they bind an active receptor, they inhibit it. H1-selective antihistamines such as loratadine were the first class classified as inverse agonists; they were long classified as antagonists until cell lines with naturally active receptors showed they bring the signal down.",
 quote:"Thus, if it binds to an active receptor, an inverse agonist can inhibit the receptor ... E.g., Anti-Histamine (Loratadine)",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Competitive & Irreversible Antagonists (p. 5 of 18)', t:'An inverse agonist not only interferes with agonist activation but also reduces receptor activity below the basal level observed in the absence of any agonist. A traditional antagonist, by contrast, has no functional effect of its own when no agonist is present.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~35–~36; transcript 9/23"},

{id:"L02-028", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"class", skill:"apply",
 concept:"indirect-antagonist-caffeine", tags:[], source:"both",
 stem:"In central nervous system neurons, norepinephrine drives Gαs signaling and the PDE enzyme breaks down cyclic AMP (cAMP). Caffeine blocks the PDE enzyme. How is caffeine classified, and what happens to cAMP?",
 options:[
  {t:"Indirect antagonist; cAMP rises", correct:true, why:"Caffeine acts on a signaling component, not the receptor; blocking PDE removes the brakes and cAMP goes up."},
  {t:"Indirect antagonist; cAMP falls", correct:false, why:"Blocking the enzyme that breaks down cAMP raises cAMP."},
  {t:"Receptor antagonist; cAMP falls", correct:false, why:"Caffeine does not bind the receptor; it acts downstream on PDE."},
  {t:"Allosteric antagonist; cAMP falls", correct:false, why:"Allosteric drugs bind the receptor at another site; caffeine binds PDE."},
  {t:"Inverse agonist; cAMP falls", correct:false, why:"Inverse agonists bind the receptor with negative efficacy; caffeine binds PDE."}],
 teach:"Indirect antagonists bind to components upstream or downstream from the receptor and can be reversible or irreversible. Caffeine blocks PDE, raising cAMP and enhancing the physiological response even though it is an antagonist of PDE. A drug that blocks RAS in the tyrosine kinase pathway is also an indirect antagonist but suppresses the signal.",
 quote:"So, this is an indirect antagonist. Why is indirect? Because it's not affecting the function of the receptor, it's affecting the, affecting the component of the signaling cascade pathway.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Well-Established Second Messengers — cAMP; Receptor Classes & Drug Development (p. 13–14 of 18)', t:'cAMP is degraded by phosphodiesterases (PDEs), and inhibition of cAMP degradation is how caffeine produces its effects. Drugs acting on phosphodiesterase target an element of the signaling pathway distal to the receptor rather than the receptor itself.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~40–~41; transcript 9/23"},

{id:"L02-029", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"kd", skill:"recall",
 concept:"kd-definition", tags:[], source:"slide",
 stem:"What does the dissociation constant (Kd) define?",
 options:[
  {t:"Concentration binding 50% of available binding sites", correct:true, why:"Kd is the drug concentration that binds 50% of the available binding sites."},
  {t:"Concentration that produces 50% of the maximum response", correct:false, why:"That is the effective concentration 50 (EC50), a potency measure."},
  {t:"Rate at which the drug associates with the receptor", correct:false, why:"The rate of association is K1; Kd is K2/K1."},
  {t:"Maximum number of receptors a drug can bind", correct:false, why:"100% of the receptors bound is Bmax."},
  {t:"Concentration that binds 100% of receptors", correct:false, why:"100% binding corresponds to Bmax, not Kd."}],
 teach:"Kd (also written Ki, Ka; coefficient of dissociation) is the drug concentration that binds 50% of available binding sites. From the law of mass action, Kd = [D][R]/[DR] = K2/K1, where K2 is the rate of dissociation and K1 the rate of association. A smaller Kd means greater affinity.",
 quote:"Define the drug concentration that binds 50% of available binding sites",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Concentration-Effect Curves & Receptor Binding of Agonists; Figure 2–1 (p. 4 of 18)', t:'Kd is the concentration of free drug at which half-maximal binding is observed, and Bmax is the total concentration of receptor sites. EC50 is a different quantity, the concentration that produces 50% of the maximal effect.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~45–~47, ~50"},

{id:"L02-030", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"kd", skill:"calc",
 concept:"kd-calculation", tags:[], source:"slide",
 stem:"10 mol of drug (D) are added to 10 receptors (R). At equilibrium 1 drug–receptor complex (DR) has formed, leaving [D] = 9 and [R] = 9. Using Kd = [D][R]/[DR], what is Kd, and how does this drug compare with one that leaves [D] = 1, [R] = 1 and [DR] = 9?",
 options:[
  {t:"81; lower affinity than the second drug", correct:true, why:"(9 × 9)/1 = 81; the second drug gives (1 × 1)/9 = 0.11, and the smaller Kd has the greater affinity."},
  {t:"81; higher affinity than the second drug", correct:false, why:"Kd and affinity are inversely related; the larger Kd (81) means lower affinity."},
  {t:"0.11; higher affinity than the second drug", correct:false, why:"0.11 is the second drug's Kd, from (1 × 1)/9."},
  {t:"9; lower affinity than the second drug", correct:false, why:"Kd multiplies free [D] and free [R] (9 × 9) and divides by [DR] (1)."},
  {t:"0.11; lower affinity than the second drug", correct:false, why:"0.11 is the second drug's Kd, and a smaller Kd means greater affinity."}],
 teach:"Kd = [D][R]/[DR]. With 10 drug and 10 receptors: if only 1 complex forms, Kd = (9)(9)/(1) = 81; if 9 complexes form, Kd = (1)(1)/(9) = 0.11. A lower Kd means higher affinity (inverse proportional).",
 quote:"[9][9] / [1] = 81 ... [1][1] / [9] = 0.11 ... ↓ Kd = ↑ Affinity",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Concentration-Effect Curves & Receptor Binding of Agonists; Receptor-Effector Coupling & Spare Receptors (p. 4–5 of 18)', t:'The relation between free drug and receptor-bound drug follows the law of mass action, and Kd characterizes affinity reciprocally: a low Kd means high binding affinity and a high Kd means low affinity.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~48–~49"},

{id:"L02-031", fg:"binding-kd", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"kd", skill:"figure",
 concept:"kd-binding-curve", tags:[], source:"slide",
 stem:"A binding curve plots % receptors bound (0% to Bmax, 100%) against log[concentration]. Drug A reaches 50% bound at a lower concentration than Drug B. Which is correct?",
 options:[
  {t:"Drug A has the smaller Kd and greater affinity", correct:true, why:"Kd is read on the x-axis at 50% bound; the lower concentration is the smaller Kd, which means greater affinity."},
  {t:"Drug B has the smaller Kd and the greater affinity", correct:false, why:"Drug B needs more drug to bind 50%, so its Kd is larger."},
  {t:"Drug A has the larger Kd and greater affinity", correct:false, why:"A lower concentration at 50% bound is a smaller Kd, not larger."},
  {t:"Drug B has greater efficacy than Drug A does", correct:false, why:"A binding curve measures receptor occupancy (affinity), not efficacy."},
  {t:"The two drugs have equal Kd values", correct:false, why:"Different concentrations at 50% bound mean different Kd values."}],
 teach:"On a binding curve, Bmax is 100% of the receptors bound and Kd is the concentration at 50% bound, read on the x-axis. The smaller the Kd, the greater the affinity of the drug for the receptor: it requires the least drug to bind the receptors.",
 quote:"The smaller the Kd is, the greater the affinity of a drug for the receptor will be. Kd will be reflected in the x-axis.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Concentration-Effect Curves & Receptor Binding of Agonists; Figure 2–1 (p. 4 of 18)', t:'On a binding curve, Bmax is the total concentration of receptor sites and Kd is the concentration at which binding is half-maximal. Kd characterizes affinity reciprocally, so the drug that reaches half-maximal binding at the lower concentration has the lower Kd and higher affinity.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~50"},

{id:"L02-032", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"kd", skill:"apply",
 concept:"kd-compare-receptors", tags:[], source:"slide",
 stem:"A new blood-pressure-lowering compound, Drug A, has these dissociation constants (Kd): β1 (heart) 250 nM; β2 (vasculature) 30 μM; M1 (gut) 1 mM. For which receptor does Drug A have the greatest affinity?",
 options:[
  {t:"β1 (heart)", correct:true, why:"250 nM is the smallest Kd of the three, and the smallest Kd means the greatest affinity."},
  {t:"β2 (vasculature)", correct:false, why:"30 μM is larger than 250 nM, so affinity at β2 is lower."},
  {t:"M1 (gut)", correct:false, why:"1 mM is the largest Kd, so M1 is where affinity is lowest."},
  {t:"Equal at all three", correct:false, why:"The three Kd values differ, so affinity differs."}],
 teach:"Compare affinity by comparing Kd values after putting them in the same units: nM is smaller than μM, which is smaller than mM. The smallest Kd is the highest affinity.",
 note:"Drug B's column (100 nM, then 250 and 20 with units that are not legible in the extracted text) is not used.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Clinical Selectivity: Beneficial Versus Toxic Effects of Drugs; Case Study Answer (p. 17–18 of 18)', t:'Selectivity is measured by comparing the binding affinities of a drug for different receptors. The receptor with the lowest Kd is the one the drug binds with the greatest affinity.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~51"},

{id:"L02-033", fg:"potency", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"drc", skill:"tell",
 concept:"potency-determinants", tags:["poll"], source:"both",
 stem:"Which statement is correct?",
 options:[
  {t:"G proteins are defined and regulated by the β subunit", correct:false, why:"G proteins are defined by the α subunit."},
  {t:"Phospholipase C is an example of a second messenger", correct:false, why:"Phospholipase C is the effector system that amplifies the signal."},
  {t:"Efficacy is the ability of a drug to bind and stay bound", correct:false, why:"Binding and staying bound is affinity."},
  {t:"The higher the Kd, the greater the affinity of the drug", correct:false, why:"The smaller the dissociation constant (Kd), the greater the affinity."},
  {t:"Potency depends on affinity, efficacy and the tissue", correct:true, why:"Potency depends on the drug's affinity, its efficacy and the tissue (site of action)."}],
 teach:"Potency is determined by affinity (Kd), efficacy (stimulus) and the tissue or site of action. Norepinephrine at β1 in the heart produces tachycardia; the tissue's receptors and signaling determine the response.",
 note:"Three versions of this list. The slide: affinity, efficacy, tissue (site of action). In class: affinity, efficacy, the receptor. The textbook: affinity and how well the receptor is coupled to its response, with efficacy kept as a separate property. Use the slide wording on the exam.",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Relation Between Drug Dose & Clinical Response — Potency; Maximal efficacy (p. 15 of 18)', t:'Potency is the concentration (EC50) or dose (ED50) that produces 50% of maximal effect. It depends partly on receptor affinity for the drug (Kd) and partly on how efficiently the drug–receptor interaction is coupled to response in the responding tissue.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~52–~54; transcript 9/23"},

{id:"L02-034", fg:"potency", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"drc", skill:"figure",
 concept:"ec50-potency-shift", tags:[], source:"slide",
 stem:"On log[concentration]–response curves, Drug B's curve is shifted to the right of Drug A's, with the same maximum response. EC50 is the effective concentration that produces 50% of the maximum response. Which drug is more potent?",
 options:[
  {t:"Drug A", correct:true, why:"Drug A reaches 50% of the maximum at a lower concentration, a lower EC50; lower EC50 means higher potency."},
  {t:"Drug B", correct:false, why:"A right-shifted curve needs more drug for 50% of the maximum, a higher EC50 and lower potency."},
  {t:"Equal potency", correct:false, why:"Equal maximum does not mean equal EC50; the shift changes EC50."},
  {t:"Cannot be compared", correct:false, why:"EC50 values on the same axis compare potency directly."}],
 teach:"EC50 is the effective concentration that produces 50% of the maximum response (Emax). Potency = EC50 (or ED50), and higher potency means a lower EC50 or ED50. Curves are built on log[concentration] with doses such as 1, 3, 10, 30, 100, 300, 1000.",
 quote:"Effective Concentration = EC50 : Effective concentration that produces 50% of the max response. ↑ Potency = ↓ EC50 or ED50",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Relation Between Drug Dose & Clinical Response — Potency; Figure 2–15 (p. 15 of 18)', t:'Potency is judged from the relative positions of dose–response curves along the dose axis. Because potency is the concentration (EC50) that produces 50% of maximal effect, the drug whose curve lies farther left has the lower EC50 and the greater potency.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slides ~57–~58"},

{id:"L02-035", lecture:"L02", prof:"Gottlieb", tier:"new", topic:"L02", sub:"drc", skill:"recall", multi:true,
 concept:"drc-purpose", tags:[], source:"slide",
 stem:"A concentration/dose–response curve is used to do which of the following? Select all that apply.",
 options:[
  {t:"Define concentration and dose responses of a drug", correct:true, why:"Listed: the curve defines concentration and dose responses of a drug."},
  {t:"Predict and compare drugs", correct:true, why:"Listed: it is a model of prediction or comparison."},
  {t:"Determine the potency", correct:true, why:"Listed: it determines potency (ED50)."},
  {t:"Measure how well a drug is absorbed", correct:false, why:"Absorption is pharmacokinetics; the curve measures response to concentration."},
  {t:"Determine how many receptors a cell synthesizes daily", correct:false, why:"Receptor synthesis is a property of the cell, not something the curve defines."}],
 teach:"Pharmacodynamics defines concentration and dose responses of a drug, predicts and compares drugs, and determines potency (Potency = ED50). Dose–response curves serve as models of prediction or comparison.",
 quote:"Defines: Concentration and dose responses of a drug; Predict and compare drugs; Determine the Potency; Potency = ED50",
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Relation Between Drug Dose & Clinical Response; Quantal Dose-Effect Curves (p. 14–16 of 18)', t:'Graded dose–response curves give the relative potency and maximal efficacy of drugs, which the prescriber needs to choose among drugs and determine doses. Comparing the ED50 values of two drugs states how many times more potent one is than the other.'}],
 cite:"Pharmacodynamics-Day_2_2026s copy.pdf slide ~56"}
);
