TOPICS.push({id:'L05', name:'Drug–receptor interactions II: spare receptors, indirect antagonists, receptor regulation, quantal responses, therapeutic index', prof:'Gottlieb', lecture:'L05',
  cite:'Day 5 (9/29) — Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf (pages 1–44)',
  subs:[
    {id:'spare', name:'Spare receptors: response vs occupancy, tissues with many or few receptors', cite:'Part 2 pages 1–3'},
    {id:'ind', name:'Indirect antagonists: PDE inhibitors, RAS blockers, SSRIs/SNRIs, acetylcholinesterase inhibitors', cite:'Part 2 pages 4–15'},
    {id:'reg', name:'Receptor regulation: up-/down-regulation, rapid desensitization, long-term down-regulation, tolerance', cite:'Part 2 pages 16–29'},
    {id:'enh', name:'Enhancement of drug effects: addition, synergism, potentiation', cite:'Part 2 pages 30–31'},
    {id:'quant', name:'Individual vs population: graded vs quantal responses', cite:'Part 2 pages 32–38'},
    {id:'ti', name:'Therapeutic index, safety index, therapeutic window, effect vs side effect', cite:'Part 2 pages 35, 39–44'}
  ]});
QUESTIONS.push(
/* ---------------- Spare receptors (pages 1–3) ---------------- */
{id:'L05-001', fg:'spare', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'spare', skill:'recall',
 concept:'spare-receptors-definition', tags:[], source:'both',
 stem:'Catecholamines such as norepinephrine and epinephrine produce the maximal heart-rate effect. About what fraction of the β-adrenoreceptors in the heart do they need to bind to do it?',
 options:[
  {t:'About 10%', correct:true, why:'Catecholamines bind about 10% of the cardiac β-adrenoreceptors to evoke the maximal effect; the other 90% are spare receptors.'},
  {t:'About 50%', correct:false, why:'Half occupancy is the Kd on a binding curve, not the occupancy needed for the maximal heart-rate response.'},
  {t:'About 90%', correct:false, why:'90% is the fraction left spare, not the fraction that must be bound.'},
  {t:'100%', correct:false, why:'Full occupancy was Clark’s occupancy theory; in many cases 100% effect comes from less than 100% receptor binding.'}],
 teach:'Spare receptors: in many cases 100% of the effect comes from less than 100% receptor binding. Catecholamines have such high affinity and efficacy at the β1 receptors of the heart that occupying about 10% of them evokes the maximal heart rate. The remaining receptors are a cushion that can be occupied if needed.',
 quote:'some drugs can only occupy, only needs to occupy 10% of the receptors to produce the max response.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 1; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'Receptors are spare when a maximal response can be elicited at an agonist concentration that does not occupy all available receptors. Heart muscle gives the same maximal response to catecholamines even when 90% of its β adrenoceptors are blocked.'}]},

{id:'L05-002', fg:'spare', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'spare', skill:'tell', multi:true,
 concept:'spare-receptors-many-effects', tags:[], source:'both',
 stem:'A tissue has a lot of receptors (many spare receptors). Which statements describe how it responds to drugs? Select all that apply.',
 options:[
  {t:'It is more sensitive to an agonist', correct:true, why:'More receptors give a greater statistical probability of binding, so the agonist appears more potent.'},
  {t:'It is less sensitive to an antagonist', correct:true, why:'The antagonist has to block more receptors before the agonist loses its full effect.'},
  {t:'It responds to an irreversible antagonist as if it were competitive at first', correct:true, why:'Early doses only shift the agonist’s curve right; the Emax drops only once fewer receptors than the agonist needs remain.'},
  {t:'Its Emax drops faster in response to a non-competitive antagonist', correct:false, why:'That is the tissue with fewer receptors; with many receptors the Emax drop takes longer.'},
  {t:'It is more sensitive to an antagonist', correct:false, why:'Reversed; more receptors make the antagonist weaker, not stronger.'}],
 teach:'Tissue with a lot of receptors: more sensitive to an agonist (greater probability of binding, so more potent), less sensitive to an antagonist (it must block more receptors), and it responds to a non-competitive or irreversible antagonist as if it were competitive initially, with several right shifts before the Emax drops. More receptors are better for the agonist; fewer receptors are better for the antagonist.',
 quote:'So if I have more spare receptors, I’m going to get a lot more shifts before I see that drop on the efficacy for an irreversible antagonist because they just have more availability of receptors',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 2; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'The sensitivity of a tissue to an agonist depends on the affinity of the receptor (Kd) and on the degree of spareness, the total receptors present compared with the number needed for a maximal response.'}]},

{id:'L05-003', fg:'irreversible', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'spare', skill:'apply',
 concept:'spare-receptors-few-effects', tags:['poll'], source:'both',
 stem:'A tissue has down-regulated its receptors and now has few receptors. An irreversible antagonist is given at increasing doses. Compared with a tissue that has many spare receptors, what happens to the agonist’s Emax?',
 options:[
  {t:'It drops faster', correct:true, why:'With fewer receptors the number the agonist needs is reached sooner, so the Emax falls after fewer antagonist doses.'},
  {t:'It drops more slowly', correct:false, why:'A slow drop is the tissue with many spare receptors, which gives several shifts before the efficacy drops.'},
  {t:'It never drops', correct:false, why:'An irreversible antagonist removes receptors; a reversible competitive antagonist is the one that leaves the Emax untouched.'},
  {t:'It rises', correct:false, why:'No antagonist raises the maximal response.'}],
 teach:'Tissue with fewer receptors: less sensitive to an agonist (more agonist is needed to bind the same number of receptors, so the agonist is less potent), more sensitive to an antagonist (it is more potent), and the Emax drops faster in response to a non-competitive or irreversible antagonist. Fewer receptors are better for the antagonist.',
 quote:'my irreversible antagonist is gonna drop much, much faster, the ability of my agonist to produce that max efficacy because I just have less receptors available for my agonist to bind.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 3; transcript 9/29'},

{id:'L05-004', fg:'spare', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'spare', skill:'figure',
 concept:'spare-receptors-irreversible', tags:['poll'], source:'both',
 stem:'The dotted line is the dose–response curve of agonist A alone. The solid lines are agonist A in the presence of increasing doses of drug B, an irreversible antagonist. The first two doses of B shift the curve to the right with the same maximum; only the higher doses lower the maximum. Why does the maximum hold at first?',
 graph:{curves:[{label:'A', ec:-1.5, emax:100, dashed:true}, {label:'+B', ec:-0.5, emax:100}, {label:'+2B', ec:0.5, emax:100}, {label:'+3B', ec:1.3, emax:60}, {label:'+4B', ec:1.8, emax:30}], base:0, x:'log dose of agonist A', y:'fractional response (%)', caption:'Right shifts with the same maximum first; the maximum falls only at the higher doses of B.'},
 options:[
  {t:'The tissue has spare receptors', correct:true, why:'With more receptors than the agonist needs, the tissue responds to an irreversible antagonist as if it were competitive at first; the Emax drops only once fewer receptors than the agonist needs remain.'},
  {t:'Drug B binds reversibly at low doses', correct:false, why:'The binding is irreversible at every dose; the tissue only responds as if the antagonist were competitive initially.'},
  {t:'Agonist A is a partial agonist', correct:false, why:'A partial agonist would not reach the full response on its own; the dotted curve reaches the maximum.'},
  {t:'Drug B has efficacy at low doses', correct:false, why:'An antagonist has no efficacy; the baseline never moves, and B only removes receptors.'}],
 teach:'With many spare receptors an irreversible antagonist first only shifts the agonist’s curve to the right (the agonist still has more than the receptors it needs), so the tissue responds as if the antagonist were competitive initially. Only when the antagonist has taken the available receptors below the minimum the agonist needs does the Emax drop, and it keeps dropping with more antagonist.',
 quote:'it’s going to take longer or a higher concentration of my irreversible before I go below the minimum number of receptors required to produce the max effect.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 2–3; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'Spare receptors are demonstrated by blocking a proportion of receptors with an irreversible antagonist and showing that high agonist concentrations still produce an undiminished maximal response.'}]},

{id:'L05-005', fg:'potency', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'spare', skill:'figure',
 concept:'four-drug-potency-efficacy', tags:['poll'], source:'both',
 stem:'The dose–response curves below represent four different drugs acting on the same receptor. Which drug has the highest potency?',
 graph:{curves:[{label:'A', ec:-1.4, emax:100}, {label:'B', ec:0.2, emax:90}, {label:'C', ec:1.0, emax:100}, {label:'D', ec:-0.3, emax:60}], base:0, x:'log [A] M', y:'response (%)'},
 options:[
  {t:'A', correct:true, why:'A requires the smallest amount of drug to produce equivalent responses; its ED50 is the smallest.'},
  {t:'B', correct:false, why:'B is more efficacious than D but its ED50 is larger than A’s, so it is less potent.'},
  {t:'C', correct:false, why:'C reaches 100% but sits farthest right: the largest ED50, the least potent.'},
  {t:'D', correct:false, why:'D’s ED50 is left of B’s and C’s but right of A’s, and its efficacy is the lowest.'},
  {t:'They all have equal efficacy as they all can produce 50% of the effect', correct:false, why:'Producing 50% of the effect is not efficacy; efficacy is the maximal response each drug can reach, and B and D plateau below A and C.'}],
 teach:'Potency is all about the ED50: find the ED50 of each drug and the one with the smallest ED50, farthest to the left, is the most potent. Drug A requires the smallest amount of drug to produce equivalent responses. Efficacy is a separate question: the most and least efficacious drugs are read from the top of each curve.',
 quote:'Potency is all about the ED50. You find the ED50 of that drug, and whoever has the smallest or farthest to the left, depending of the efficacy, because remember, potency is a combination of the affinity and the efficacy, so the A will be more potent.',
 cite:'transcript 9/29 (PollEV, 9/29); Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf'},

{id:'L05-006', fg:'potency', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'spare', skill:'figure',
 concept:'same-emax-leftmost-most-potent', tags:['poll'], source:'both',
 stem:'Five drugs, A–E, are tested in the same tissue. Which of the following is CORRECT?',
 graph:{curves:[{label:'A', ec:-1.6, emax:90}, {label:'B', ec:-1.1, emax:100}, {label:'C', ec:0, emax:90}, {label:'D', ec:0.5, emax:60}, {label:'E', ec:1.4, emax:90}], base:0, x:'log dose', y:'effect (%)', marks:[{x:-1.6, label:'ED50 A'}, {x:0, label:'ED50 C'}]},
 options:[
  {t:'Drug E is more potent than Drug C due to its efficacy', correct:false, why:'E is the least potent of the five, and its efficacy equals C’s, so efficacy cannot be the reason.'},
  {t:'Drug B is more potent than Drug A due to its affinity', correct:false, why:'B is more efficacious than A, but its ED50 is larger, which makes it less potent.'},
  {t:'Drug A is more potent than Drug C due to its affinity', correct:true, why:'With equal efficacy in the same tissue, the only difference between A and C is affinity, and that is what makes A more potent.'},
  {t:'Drug C is more potent than Drug E due to its efficacy', correct:false, why:'C is more potent than E, but not due to efficacy: the efficacies are equal, so the difference is affinity.'},
  {t:'Drug D is more potent than B due to its affinity and efficacy', correct:false, why:'D is to the right of B, so D is less potent, and its efficacy is the lowest of the five, not higher.'}],
 teach:'When drugs are tested in the same individual, tissue or organ and have equal efficacy, the only difference between them is affinity, and affinity is what makes one more potent than another. Potency is read from the ED50; a drug can be more efficacious than another and still be less potent if its ED50 is larger.',
 quote:'Assuming that we are testing the drug in the same individual. Or tissue or organ. They have equal efficacy, so the only difference between them is what affinity, right? That’s what makes it more potent.',
 cite:'transcript 9/29 (PollEV, 9/29); Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf'},

/* ---------------- Indirect antagonists (pages 4–15) ---------------- */
{id:'L05-007', fg:'classes', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ind', skill:'recall',
 concept:'indirect-antagonist-definition', tags:['poll'], source:'both',
 stem:'Which statement is CORRECT about indirect antagonists?',
 options:[
  {t:'They act downstream or upstream of the receptor, not on the receptor itself', correct:false, why:'Correct statement (they inhibit the generation of the response at some point downstream, or change the signal upstream), but not the only correct one.'},
  {t:'They can be reversible or irreversible', correct:false, why:'Correct statement, but not the only correct one.'},
  {t:'They can increase or decrease the physiological response', correct:false, why:'Correct statement (a PDE inhibitor raises the response, a RAS blocker lowers it), but not the only correct one.'},
  {t:'All of the above', correct:true, why:'All three statements are correct.'}],
 teach:'An indirect antagonist inhibits the generation of a biological response by acting at some point downstream of the receptor, or upstream of it; it does not bind or affect the receptor directly. It can be reversible or irreversible. Depending on which component of the signaling cascade it modulates, the physiological response can go up (phosphodiesterase inhibitors such as milrinone or caffeine) or down (cancer drugs that block RAS).',
 quote:'They’re not directly binding and affecting the receptor, they are affecting the signal or something upstream from that process, and it can be reversible or irreversible in this process.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 4; transcript 9/29'},

{id:'L05-008', fg:'gpcr', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ind', skill:'apply',
 concept:'indirect-antagonist-caffeine', tags:['poll'], source:'both',
 stem:'A partial agonist activates a Gαs-coupled receptor and raises cyclic adenosine monophosphate (cAMP). Milrinone, a reversible phosphodiesterase (PDE) inhibitor, is added. What happens to the dose–response curve of the agonist?',
 options:[
  {t:'Shifts left; the maximal response may rise', correct:true, why:'PDE breaks down cAMP; blocking it raises intracellular cAMP, the signal gets bigger, the agonist appears more potent and a partial agonist can behave like a full one.'},
  {t:'Shifts right with the same maximum', correct:false, why:'A right shift is what a drug that makes the agonist’s life harder does; the PDE inhibitor helps the signal.'},
  {t:'No change; the receptor itself is untouched by milrinone', correct:false, why:'The receptor is untouched, but the response downstream of it is larger, and the curve reflects the response.'},
  {t:'Shifts right and the maximum falls', correct:false, why:'That is a RAS blocker or an irreversible antagonist, drugs that lower the signal.'}],
 teach:'The two gatekeepers of cAMP are adenylate cyclase (AC), which makes it, and phosphodiesterase (PDE), which breaks it down. A PDE inhibitor (milrinone, caffeine) takes away the brakes: more cAMP, more protein kinase A (PKA), more contraction. The agonist’s curve shifts left (increasing its potency), and a partial agonist can now behave like a full agonist. The indirect antagonist here increases the response.',
 quote:'So if I take a drug like murone or perhaps drink my coffee, who is a reversible antagonist to the PDE. Now I’m taking away the brakes of the system.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 5–6; transcript 9/29'},

{id:'L05-009', fg:'classes', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ind', skill:'apply',
 concept:'ras-block-downstream', tags:['poll'], source:'both',
 stem:'A growth factor acting as a full agonist signals through a one-transmembrane receptor: GEF, RAS, RAF, MEK, ERK. A cancer drug X blocks RAS. What would that do to the potency of the growth factor?',
 options:[
  {t:'Would lower it', correct:true, why:'With RAS blocked the signal is decreased; the full agonist now behaves like a partial, less efficacious agonist.'},
  {t:'Would increase it', correct:false, why:'Increasing the signal is what a PDE inhibitor does; blocking RAS cuts the cascade.'},
  {t:'No effect', correct:false, why:'Drug X does not bind the receptor, but the response downstream is lost, so the dose–response curve changes.'}],
 teach:'Drug X binds RAS, downstream of the receptor, so it is an indirect antagonist that decreases the signal. With less signal the cells do not grow and divide as quickly. On the dose–response curve the growth factor is made less potent and less efficacious: it used to be a full agonist and now behaves like a partial one. PDE inhibitor increases the response; RAS blocker decreases it.',
 quote:'So in this case over here, I’m making my drug less potent, my full agonist. I used to be a full agonist, and I’m a partial, less efficacious, right? I’m decreasing that signal process.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 7–8; transcript 9/29'},

{id:'L05-010', fg:'classes', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ind', skill:'tell', multi:true,
 concept:'indirect-antagonist-examples', tags:[], source:'both',
 stem:'Which of the following drugs are indirect antagonists? Select all that apply.',
 options:[
  {t:'Fluoxetine (Prozac), a selective serotonin reuptake inhibitor', correct:true, why:'It blocks the serotonin reuptake transporter (SERT), upstream of the receptor, and changes the serotonin concentration.'},
  {t:'Physostigmine, an acetylcholinesterase inhibitor', correct:true, why:'It blocks the enzyme that breaks down acetylcholine, so more acetylcholine reaches the receptors.'},
  {t:'Milrinone, a phosphodiesterase inhibitor', correct:true, why:'It blocks PDE downstream of the receptor and raises cAMP.'},
  {t:'Carbidopa, which blocks the enzyme that breaks down L-DOPA in the gut', correct:true, why:'It blocks the enzyme in the gut that breaks down dopa, so more gets to the brain; it acts away from the receptor.'},
  {t:'Metoprolol', correct:false, why:'Metoprolol binds the β1 receptor itself as a competitive, reversible antagonist.'},
  {t:'Diazepam', correct:false, why:'Diazepam binds the receptor at an allosteric site; an indirect antagonist never touches the receptor.'}],
 teach:'Indirect antagonists change the signal without touching the receptor: a transporter blocker (fluoxetine at SERT, duloxetine at the norepinephrine transporter, cocaine), an enzyme blocker (physostigmine at acetylcholinesterase, carbidopa in the gut), a PDE inhibitor (milrinone, caffeine) or a RAS blocker. A drug that binds the receptor, at the orthosteric site (metoprolol) or an allosteric site (diazepam), is not indirect.',
 quote:'it’s still indirect because it’s not directly affecting the receptor itself, it’s just changing the concentration of the neurotransmitter.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 4–13, 31; transcript 9/29'},

{id:'L05-011', fg:'potency', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ind', skill:'figure',
 concept:'ssri-serotonin-potency', tags:['poll'], source:'both',
 stem:'The dashed line is the dose–response curve of serotonin (5HT) alone. Fluoxetine (Prozac) binds the serotonin reuptake transporter (SERT). Which solid curve is serotonin in the presence of fluoxetine?',
 graph:{curves:[{label:'5HT', ec:0.5, emax:100, dashed:true}, {label:'A', ec:-1, emax:100}, {label:'B', ec:1.5, emax:100}, {label:'C', ec:-1, emax:60}, {label:'D', ec:1.5, emax:60}], base:0, x:'log [5HT]', y:'response (%)'},
 options:[
  {t:'A: shifted left, same maximum', correct:true, why:'Less serotonin is cleared, so more is floating in the synapse; it appears more potent, and the efficacy is unchanged, it is still serotonin.'},
  {t:'B: shifted right, same maximum', correct:false, why:'A right shift means serotonin was made less potent; blocking reuptake does the opposite.'},
  {t:'C: shifted left, lower maximum', correct:false, why:'The maximum does not fall: nothing changed the drug or the receptor, only the concentration.'},
  {t:'D: shifted right, lower maximum', correct:false, why:'This is the picture of an irreversible antagonist, not of a reuptake blocker.'}],
 teach:'Fluoxetine blocks SERT, the serotonin reuptake transporter, so more serotonin stays in the synapse. Serotonin appears more potent and its curve shifts to the left. Efficacy does not change: it is still serotonin, there is simply more of it.',
 quote:'by doing so I’m going to have a lot more serotonin, which means it’s going to make it more potent by shifting the dose response curve to the left. Why is it not affecting the efficacy? Still serotonin.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 9–11; transcript 9/29'},

{id:'L05-012', fg:'potency', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ind', skill:'figure',
 concept:'transporter-blocker-increases-apparent-potency', tags:['poll'], source:'both',
 stem:'Dose–response curve B represents norepinephrine (NE) alone. Which curve best represents NE in the presence of duloxetine, a serotonin–norepinephrine reuptake inhibitor (SNRI) that blocks the norepinephrine transporter (NET)?',
 graph:{curves:[{label:'A', ec:-1, emax:100}, {label:'B', ec:0, emax:100, dashed:true}, {label:'C', ec:0.7, emax:60}, {label:'D', ec:1.0, emax:100}, {label:'E', ec:1.5, emax:75}], base:0, x:'log [agonist], M', y:'response, percent of control'},
 options:[
  {t:'A', correct:true, why:'Reuptake is blocked, norepinephrine floats around longer in the synapse, and it appears more potent: shift to the left.'},
  {t:'C', correct:false, why:'A right shift with a lower maximum is an irreversible antagonist or an allosteric antagonist affecting affinity and efficacy.'},
  {t:'D', correct:false, why:'A right shift with the same maximum is a competitive antagonist such as metoprolol, or an allosteric antagonist affecting only affinity.'},
  {t:'E', correct:false, why:'A right shift with a lower maximum: the drug makes the agonist’s life more difficult, the opposite of a reuptake blocker.'},
  {t:'None of the above', correct:false, why:'One of the curves fits: the reuptake blocker helps the agonist, so the curve moves left.'}],
 teach:'First question on any drug–drug figure: does the second drug help the agonist or make its life more difficult? Duloxetine blocks the norepinephrine transporter, so norepinephrine stays in the synapse longer and appears more potent: shift left, curve A. Same figure: competitive antagonist gives D; irreversible antagonist C or E (depending on spare receptors); allosteric antagonist affecting only affinity D, affecting both C or E.',
 quote:'we’re blocking the reuptake of norepinephrine, which means we’re gonna have norepinephrine floating around for a longer period of time in that synapse and thus make it norepinephrine more potent, shifting to the left.',
 cite:'transcript 9/29 (PollEV, 9/29); Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 9–11'},

{id:'L05-013', fg:'classes', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ind', skill:'figure', multi:true,
 concept:'helps-or-hinders-direction', tags:['poll'], source:'transcript',
 stem:'Dose–response curve B is norepinephrine (NE) alone. Which second drugs would move NE to curve A? Select all that apply.',
 graph:{curves:[{label:'A', ec:-1, emax:100}, {label:'B', ec:0, emax:100, dashed:true}, {label:'C', ec:0.7, emax:60}, {label:'D', ec:1.0, emax:100}, {label:'E', ec:1.5, emax:75}], base:0, x:'log [agonist], M', y:'response, percent of control'},
 options:[
  {t:'Duloxetine (norepinephrine transporter blocker)', correct:true, why:'Reuptake blocked, more NE in the synapse, NE more potent: left shift.'},
  {t:'An allosteric agonist that affects only affinity', correct:true, why:'It helps binding without changing efficacy: left shift, same maximum.'},
  {t:'Epinephrine (another full agonist)', correct:true, why:'Two full agonists help each other: left shift, same maximum.'},
  {t:'Metoprolol', correct:false, why:'A competitive antagonist shifts NE right with the same maximum: curve D.'},
  {t:'Phenoxybenzamine', correct:false, why:'An irreversible antagonist shifts right and lowers the maximum: curve C or E.'}],
 teach:'On the same figure the permutations are: another full agonist, an allosteric agonist affecting only affinity, or a reuptake blocker moves NE to A; a competitive antagonist or an allosteric antagonist affecting only affinity moves it to D; an irreversible antagonist or an allosteric antagonist affecting affinity and efficacy moves it to C or E. Ask whether the drug helps or hinders the agonist.',
 quote:'If it was an irreversible, it could be either C or E, right, depending on how much spare receptors they would have. Uh, if it is an allosteric antagonist that affects only affinity, it would be D or a allo. Asteric that affects affinity and efficacy, now CNE or a allosteric agonist that affects only affinity, then A again, right? Or another full agonist.',
 cite:'transcript 9/29; Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 9–11'},

{id:'L05-014', fg:'irreversible', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ind', skill:'figure',
 concept:'irreversible-antagonist-curve', tags:['poll'], source:'transcript',
 stem:'Dose–response curve B is norepinephrine (NE) alone. In one tissue, phenoxybenzamine moves NE to curve C; in another tissue, the same dose of phenoxybenzamine moves NE to curve E. What differs between the two tissues?',
 graph:{curves:[{label:'A', ec:-1, emax:100}, {label:'B', ec:0, emax:100, dashed:true}, {label:'C', ec:0.7, emax:60}, {label:'D', ec:1.0, emax:100}, {label:'E', ec:1.5, emax:75}], base:0, x:'log [agonist], M', y:'response, percent of control'},
 options:[
  {t:'How many spare receptors each has', correct:true, why:'An irreversible antagonist gives C or E depending on how many spare receptors the tissue has; the maximum falls less where more receptors remain.'},
  {t:'Whether phenoxybenzamine is reversible in that tissue', correct:false, why:'Phenoxybenzamine is irreversible everywhere; a reversible antagonist would give curve D with the maximum intact.'},
  {t:'Whether NE is a full or a partial agonist there', correct:false, why:'NE is the same full agonist in both tissues; curve B alone reaches the full response.'},
  {t:'How much NE was given', correct:false, why:'Each curve already spans the NE doses; the difference is in the receptors left for NE to bind.'}],
 teach:'Phenoxybenzamine is the only irreversible antagonist on the drug list. An irreversible antagonist shifts the agonist to the right and lowers the Emax, so on this figure it could be either C or E, depending on how many spare receptors the tissue has: with more spare receptors the maximum falls less. Curve D (same maximum) belongs to a reversible competitive antagonist.',
 quote:'If it was an irreversible, it could be either C or E, right, depending on how much spare receptors they would have.',
 cite:'transcript 9/29; Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 2–3'},

{id:'L05-015', fg:'potency', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ind', skill:'apply',
 concept:'ache-inhibitor-ach-potency', tags:['poll'], source:'both',
 stem:'Acetylcholinesterase, an enzyme on cell membranes of the parasympathetic system, breaks down acetylcholine. Physostigmine blocks the enzyme. What effect would physostigmine have on the potency of acetylcholine?',
 options:[
  {t:'Would increase the potency of acetylcholine', correct:true, why:'Acetylcholine is not broken down as quickly, so more of it reaches the receptors and less needs to be released; the curve shifts left.'},
  {t:'Would lower the potency of acetylcholine', correct:false, why:'Lowering the potency would require removing acetylcholine or blocking its receptors; blocking the enzyme does the opposite.'},
  {t:'Would have no effect on the potency of acetylcholine', correct:false, why:'Physostigmine never touches the receptor, but it raises the acetylcholine concentration, which changes the curve.'}],
 teach:'Same principle as the reuptake blocker, different target: instead of the transporter, the enzyme that breaks down the neurotransmitter is blocked. More acetylcholine means more receptors bound, so acetylcholine appears more potent and its curve shifts to the left. It is still an indirect antagonist: it changes the concentration of the neurotransmitter, not the receptor.',
 quote:'by blocking the enzyme, I can increase the levels of acetylcholine, the more acetylcholine I have, the more receptors I can bind, and thus make acetylcholine more potent, thus shifting to the left. Same principle. But different target.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 12–13; transcript 9/29'},

{id:'L05-016', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ind', skill:'recall',
 concept:'myasthenia-gravis-downregulation', tags:[], source:'both',
 stem:'A patient with myasthenia gravis wakes up with normal strength and becomes progressively weaker through the day. What is the cause of the muscle weakness?',
 options:[
  {t:'Antibodies against the nicotinic receptors', correct:true, why:'In about 90% of patients it is an autoimmune disease: antibodies target and destroy the nicotinic receptors of skeletal muscle, a form of receptor down-regulation.'},
  {t:'Too much acetylcholinesterase enzyme activity in the synapse', correct:false, why:'The enzyme is normal; the receptors are the problem. Blocking the enzyme (physostigmine) is the treatment, not the cause.'},
  {t:'Up-regulation of nicotinic receptors', correct:false, why:'Up-regulation makes a tissue supersensitive; myasthenia gravis is a loss of receptors.'},
  {t:'A lack of acetylcholine release', correct:false, why:'Acetylcholine is released normally; the receptors it binds are being destroyed.'}],
 teach:'Myasthenia gravis: in about 90% of patients an autoimmune disease in which antibodies target the nicotinic receptors at the neuromuscular junction of skeletal muscle, so the receptors do not function and are destroyed. It is one of the clinical manifestations of receptor down-regulation. Treatment: physostigmine or any drug ending in -stigmine blocks acetylcholinesterase, raises acetylcholine and makes it more potent at the receptors that remain.',
 quote:'They are targeting their nicotinic receptors in their skeletal muscle, so they have this progressive loss of strength, muscle strength.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 12, 29; transcript 9/29'},

/* ---------------- Receptor regulation (pages 16–29) ---------------- */
{id:'L05-017', fg:'gpcr', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'recall', multi:true,
 concept:'receptor-regulation-mechanisms', tags:[], source:'both',
 stem:'Receptors are subject to many regulatory and homeostatic controls. Which of the following are ways receptor function is regulated? Select all that apply.',
 options:[
  {t:'Synthesis and degradation', correct:true, why:'The cell can make more receptors or break them down quicker.'},
  {t:'Covalent modification', correct:true, why:'The cell’s own proteins form bonds to the receptor, affecting its function.'},
  {t:'Association with other regulatory proteins', correct:true, why:'Regulatory proteins (such as β-arrestin) can make a receptor non-functional or resistant to an agonist.'},
  {t:'Re-localization within the cell', correct:true, why:'The receptor is brought inside the cell by endocytosis and then recycled or broken down.'},
  {t:'A change in the chemical bonds the drug forms', correct:false, why:'The bonds a drug forms set its affinity; they are a property of the drug, not a control the cell applies to the receptor.'}],
 teach:'Four ways the cell regulates its receptors: synthesis and degradation (make more, or break down quicker), covalent modification (the cell’s own proteins bond to the receptor), association with other regulatory proteins (which can make the receptor non-functional or resistant to an agonist), and re-localization within the cell (endocytosis, then recycling or breakdown).',
 quote:'we can bring that receptor inside of the cell through a process called endocytosis, and then we can either recycle the receptor back or break it down and make something else with it',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 16, 21; transcript 9/29'},

{id:'L05-018', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'recall',
 concept:'regulation-correct-poll', tags:['poll'], source:'both',
 stem:'Which statement is CORRECT?',
 options:[
  {t:'If one gets exposed to too much activation by an agonist, the body is most likely to up-regulate the receptors', correct:false, why:'Too much agonist makes the body do the opposite: down-regulate.'},
  {t:'Short term regulation of receptors involves relocation of receptors into the cells', correct:false, why:'Relocation into the cell (endocytosis) is long-term, chronic regulation; short-term is the regulatory proteins.'},
  {t:'Indirect antagonists are allosteric drugs that bind at another site in the receptor', correct:false, why:'Indirect antagonists bind upstream or downstream from the receptor and never touch it; allosteric drugs bind the receptor.'},
  {t:'Decreasing the number of receptors may lead to decrease in the potency of an agonist', correct:true, why:'With fewer receptors more agonist is needed to bind the same number, so the curve shifts right and potency falls.'}],
 teach:'Too much agonist stimulation makes the body down-regulate, not up-regulate. Relocation of receptors into the cell is a long-term process, not short-term. Indirect antagonists are not allosteric; they act upstream or downstream of the receptor. Decreasing the number of receptors lowers the potency of an agonist, which is why this is the correct statement.',
 quote:'If you want to get exposed to too much activation by an agonist, the body is going up regulate, uh uh, down regulate, right? Do the opposite.',
 cite:'transcript 9/29 (PollEV, 9/29); Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 17, 21, 28'},

{id:'L05-019', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'recall',
 concept:'regulation-all-correct-poll', tags:['poll'], source:'both',
 stem:'Which statement is CORRECT?',
 options:[
  {t:'Increasing the number of receptors may increase the potency of a drug', correct:false, why:'Correct statement (up-regulation shifts the agonist to the left), but not the only correct one.'},
  {t:'Beta arrestin is involved in rapid receptor desensitization', correct:false, why:'Correct statement (GRK phosphorylates, β-arrestin binds and stops the receptor), but not the only correct one.'},
  {t:'Endocytosis of receptors is part of the long term receptor down-regulation', correct:false, why:'Correct statement (endocytosis, coated pits, recycling or degradation), but not the only correct one.'},
  {t:'Tolerance to a drug effect is a product of receptor down-regulation', correct:false, why:'Correct statement (tolerance is the clinical manifestation of down-regulation), but not the only correct one.'},
  {t:'All of the above', correct:true, why:'Every statement is correct.'}],
 teach:'All four statements are correct: more receptors make an agonist more potent; β-arrestin is the rapid desensitization protein; endocytosis is the long-term down-regulation process; and tolerance is the clinical manifestation of down-regulation.',
 quote:'99 says E, that’s the correct answer, right? They’re all correct.',
 cite:'transcript 9/29 (PollEV, 9/29); Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 18, 22–23, 27, 29'},

{id:'L05-020', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'tell',
 concept:'up-vs-down-regulation-trigger', tags:['poll'], source:'both',
 stem:'Which statement is CORRECT about the regulation of receptor expression?',
 options:[
  {t:'Up-regulation follows chronic reduction of receptor stimulation, as with an antagonist', correct:false, why:'Correct statement (it is a compensatory mechanism that adds spare receptors), but not the only correct one.'},
  {t:'Down-regulation follows chronic exposure of the receptor to a stimulus, as with an agonist', correct:false, why:'Correct statement (too much stimulation and the body lowers the receptor number), but not the only correct one.'},
  {t:'Up-regulation increases the number of spare receptors', correct:false, why:'Correct statement, but not the only correct one.'},
  {t:'All of the above', correct:true, why:'All three are correct: the body opposes what the drug does to maintain homeostasis.'}],
 teach:'Up-regulation: more receptors, following chronic reduction of receptor stimulation (an antagonist or inverse agonist); a compensatory mechanism that increases the spare receptors. Down-regulation: fewer receptors, following chronic exposure of the receptor to a stimulus (an agonist). Typically an antagonist up-regulates and an agonist down-regulates, because the body does the opposite of the drug to maintain homeostasis.',
 quote:'So typically an antagonist will up regulate, an agonist is going to down regulate because our body is going to do the opposite to maintain that homeostasis.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 17; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Alterations in Number or Function of Receptors', t:'An antagonist can increase receptor number by preventing the downregulation that an endogenous agonist would cause; an agonist itself can decrease receptor number (downregulation) or coupling efficiency (desensitization).'}]},

{id:'L05-021', fg:'competitive', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'apply',
 concept:'beta-blocker-upregulation-taper', tags:[], source:'both',
 stem:'A patient has taken a β-blocker for months to years and wants to stop it. What should the pharmacist advise, and why?',
 options:[
  {t:'Taper stepwise; the receptors are up-regulated', correct:true, why:'Prolonged antagonist use increases the number of functional cardiac β-adrenoreceptors; stopping cold turkey leaves them all unblocked and the patient is likely to go into a hypertensive crisis.'},
  {t:'Stop at once; the receptors are down-regulated', correct:false, why:'Down-regulation follows an agonist, not an antagonist; a chronic blocker up-regulates.'},
  {t:'Stop at once; the receptor number has not changed', correct:false, why:'Chronic reduction of stimulation by the antagonist is a compensatory signal to add receptors.'},
  {t:'Double the dose first; tolerance to the blocker has developed', correct:false, why:'Tolerance is a manifestation of down-regulation after continued agonist exposure, not of antagonist use.'}],
 teach:'Prolonged use of an antagonist up-regulates: β-blockers cause an increase in the number of functional cardiac β-adrenoreceptors. Going cold turkey leaves many receptors and no antagonist to block them, and the patient is likely to go into a hypertensive crisis. That is why β-blockers are stopped by stepwise tapering, decreasing the dose gradually.',
 quote:'Do not go cold turkey. Because if you go cold turkey, you have lots of receptors that are being up regulated and no antagonists to block it, and that patient is going to be very likely to go into what is called a hypertensive crisis',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 19; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Alterations in Number or Function of Receptors', t:'When an antagonist that raised receptor number is withdrawn, the elevated number of receptors can produce an exaggerated response to physiologic concentrations of agonist.'}]},

{id:'L05-022', fg:'partial', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'figure',
 concept:'upregulation-partial-agonist', tags:['poll'], source:'both',
 stem:'The dashed line is a partial agonist alone. The tissue then up-regulates its receptors. Which solid curve shows the partial agonist in the up-regulated tissue?',
 graph:{curves:[{label:'PA', ec:0.5, emax:50, dashed:true}, {label:'A', ec:-1, emax:100}, {label:'B', ec:1.5, emax:50}, {label:'C', ec:-1, emax:25}, {label:'D', ec:1.5, emax:25}], base:0, x:'log [PA]', y:'response (%)'},
 options:[
  {t:'A: shifted left and up to 100%', correct:true, why:'More receptors: less drug is needed (more potent) and there are enough receptors to bind to produce the full response.'},
  {t:'B: shifted right, same maximum', correct:false, why:'A right shift is loss of potency, what down-regulation does.'},
  {t:'C: shifted left, lower maximum', correct:false, why:'Up-regulation adds receptors; the maximal response can rise, not fall.'},
  {t:'D: shifted right, lower maximum', correct:false, why:'This is the picture of down-regulation or an irreversible antagonist.'}],
 teach:'Up-regulation (more spare receptors) increases the potency of a full agonist (shift left) and increases the potency and/or the maximal response of a partial agonist. With enough receptors to bind, a drug that behaved like a partial agonist can produce the full response and behave like a full agonist. The more spare receptors, the more potent the agonist.',
 quote:'I can even make a drug who behaves like a partial agonist to become a full agonist because now I have enough receptors to bind and produce the full response',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 18; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor-Effector Coupling & Spare Receptors', t:'With more receptors than effectors, a lower agonist concentration occupies enough receptors for a half-maximal response, so the sensitivity of a tissue can be changed by changing receptor number.'}]},

{id:'L05-023', fg:'potency', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'apply',
 concept:'downregulation-decreases-potency', tags:['poll'], source:'both',
 stem:'A patient addicted to cocaine, an indirect antagonist that blocks the reuptake of norepinephrine, has so much norepinephrine around that the body down-regulates its receptors. What effect does that have on the potency of norepinephrine?',
 options:[
  {t:'Would lower it', correct:true, why:'With fewer receptors the neurons must produce more norepinephrine to get the same response; the curve shifts right.'},
  {t:'Would increase it', correct:false, why:'More potency comes from more receptors (up-regulation), not fewer.'},
  {t:'No effect', correct:false, why:'Changing the receptor number changes how much drug is needed, so the potency changes.'}],
 teach:'Long-term down-regulation lowers the number of receptors. To produce the same effect as before the concentration has to increase: the neurons work harder, or the user goes from one sniff to two. The dose–response curve of norepinephrine shifts to the right, requiring more of it to produce equivalent responses. Down-regulation is analogous to an irreversible antagonist: the receptor population available is lowered.',
 quote:'that’s gonna shift the dose response curve of norepinephrine to the right because it’s gonna require more of it to produce equivalent responses.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 20, 25–26; transcript 9/29',
 note:'The handwritten note on page 26 says “shift left b/c going to require more of it to get a response”; the arrow on the same slide and what he said in class both give a shift to the RIGHT (needing more drug is a right shift). Use right.'},

{id:'L05-024', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'apply',
 concept:'agonist-downregulation-withdrawal', tags:[], source:'both',
 stem:'An intensive-care patient has been on a continuous Levophed (norepinephrine) drip to hold up blood pressure. The drip is shut off abruptly. What happens and why?',
 options:[
  {t:'Blood pressure falls: the agonist down-regulated the receptors', correct:true, why:'Continuous agonist exposure lowered the receptor number; without the drip there are not enough receptors for the body’s own norepinephrine to do the job.'},
  {t:'Hypertensive crisis: the receptors were up-regulated', correct:false, why:'Up-regulation follows an antagonist; an agonist drip does the opposite.'},
  {t:'No change: the body’s own norepinephrine takes over the receptors', correct:false, why:'The body’s norepinephrine faces fewer receptors than before.'},
  {t:'Blood pressure rises: the drug stops occupying receptors', correct:false, why:'Norepinephrine was raising the pressure; removing an agonist from a down-regulated system lowers it.'}],
 teach:'Too much agonist stimulation makes the body lower the number of receptors. Shut off the Levophed drip and the pressure tanks: there are not enough receptors to do the job. It is the opposite effect of stopping an antagonist, which brings things up. The same happens with Afrin, an α agonist nasal decongestant: used for more than 2 to 3 days it down-regulates the receptors.',
 quote:'they’re getting levofed to bring up their blood pressure. If you shut down that IV drip, bonk, they’re gonna tank it out because there’s just not enough receptors to do the job',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 17, 20; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Alterations in Number or Function of Receptors', t:'When an agonist is discontinued, the receptor number, decreased by drug-induced downregulation, is too low for the endogenous agonist to produce effective stimulation.'}]},

{id:'L05-025', fg:'gpcr', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'tell', multi:true,
 concept:'rapid-vs-longterm-regulation', tags:[], source:'both',
 stem:'Receptor regulation can be rapid or long-term. Which processes are long-term? Select all that apply.',
 options:[
  {t:'Synthesis of more receptors', correct:true, why:'Making receptors takes time.'},
  {t:'Degradation of receptors', correct:true, why:'Breaking receptors down takes time.'},
  {t:'Internalization (endocytosis) of receptors', correct:true, why:'Bringing the receptor inside the cell and recycling or degrading it is the long process.'},
  {t:'Binding of β-arrestin to the phosphorylated receptor', correct:false, why:'Proteins bind and unbind very quickly; association with regulatory proteins is the rapid process, within milliseconds.'}],
 teach:'Rapid regulation is association with regulatory proteins (GRK phosphorylates the receptor, β-arrestin binds), a temporary stop that can be taken off right away. Long-term regulation takes time: synthesis, degradation and internalization (relocation inside the cell). The poll trap: short-term regulation does not involve relocation of receptors into the cell; that is long-term.',
 quote:'So long term is going to be synthesis, degradation, internalization. Those are long term. That takes time. Proteins can bind and unbind very quickly, so that’s rapid.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 21; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor Regulation', t:'Desensitization can be rapidly reversible within minutes, while repeated or prolonged agonist exposure sends internalized receptors to lysosomes and down-regulates them.'}]},

{id:'L05-026', fg:'gpcr', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'recall',
 concept:'grk-beta-arrestin', tags:['poll'], source:'both',
 stem:'Which statement is CORRECT about rapid desensitization of a G protein–coupled receptor (GPCR)?',
 options:[
  {t:'The agonist-bound receptor serves as a substrate for GPCR kinases (GRK), which phosphorylate it', correct:false, why:'Correct statement (GRK phosphorylates the tail of the seven-transmembrane receptor), but not the only correct one.'},
  {t:'Phosphorylation allows β-arrestin to bind and stop the receptor from signaling', correct:false, why:'Correct statement (β-arrestin is the stop plug: no more cAMP until the drug comes off), but not the only correct one.'},
  {t:'It happens within milliseconds', correct:false, why:'Correct statement, but not the only correct one.'},
  {t:'All of the above', correct:true, why:'All three statements are correct.'}],
 teach:'Rapid desensitization of a GPCR: the agonist-induced change in receptor conformation lets the receptor bind, activate and serve as a substrate for GPCR kinases (GRK). GRK phosphorylates the tail of the receptor, which allows β-arrestin to bind. β-arrestin stops the receptor from functioning: the α subunit cannot reassociate and reset the system, the cAMP response flattens, and nothing more happens until the drug comes off. This occurs within milliseconds.',
 quote:'the GRK is phosphoryating and which allows the beta restsin to come and bind it, right? So the beta restsin is what it’s kind of like, that’s the stop plug, you know, until that drug comes off, I’m not coming out.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 22–24; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor Regulation', t:'GRKs phosphorylate the cytoplasmic tail of the agonist-activated receptor, which reduces its ability to activate Gs and raises its affinity for β-arrestin; β-arrestin binding further attenuates the response.'}]},

{id:'L05-027', fg:'gpcr', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'recall',
 concept:'longterm-downregulation-steps', tags:[], source:'both',
 stem:'A receptor stays over-stimulated after β-arrestin has bound it. What happens to the receptor in long-term down-regulation?',
 options:[
  {t:'It enters coated pits and is endocytosed, then recycled or degraded', correct:true, why:'β-arrestin facilitates uptake into coated pits; inside the cell the receptor is either recycled to the surface or broken down.'},
  {t:'It is covalently modified by the cell and stays at the surface signaling', correct:false, why:'Long-term down-regulation removes the receptor from the cell surface.'},
  {t:'More copies of it are synthesized', correct:false, why:'Synthesis of more receptors is up-regulation.'},
  {t:'GRK removes the phosphates and it resets', correct:false, why:'Resetting after the drug leaves is the rapid, reversible process; continued stimulation goes on to internalization.'}],
 teach:'Long-term down-regulation: with too much stimulation, blocking through β-arrestin is not enough, so β-arrestin facilitates uptake of the receptor into coated pits and the receptor is engulfed by endocytosis. Inside the cell it is either recycled back to the surface or put in a lysosome and broken down. If the stimulation continues the cell keeps the receptors low; a receptor that is not in the cell wall cannot bind anything.',
 quote:'those beta resting is going to facilitate the uptake of those receptors to petticoat coated pits ... we’re going to engulf that receptor. We’re going to bring it inside of the cell and then we’re going to ask the question, should I be able to recycle this back or should I just put it into a lysosome',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 27; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Receptor Regulation', t:'The receptor–arrestin complex binds to coated pits and is internalized; recycling to the surface resensitizes the cell, while delivery to lysosomes down-regulates the receptors.'}]},

{id:'L05-028', fg:'potency', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'figure',
 concept:'receptor-density-potency', tags:['poll'], source:'both',
 stem:'The same agonist is tested in three cell lines, A, B and C, that differ only in receptor density. Which cell line has the lowest receptor density?',
 graph:{curves:[{label:'A', ec:-2, emax:100}, {label:'B', ec:0, emax:70}, {label:'C', ec:1.6, emax:35}], base:0, x:'log [agonist]', y:'fractional response (%)', marks:[{x:-2, label:'ED50 A'}]},
 options:[
  {t:'C', correct:true, why:'Fewer receptors available: the ED50 has moved to higher doses and the maximum is lost as well; potency and efficacy both fall.'},
  {t:'A', correct:false, why:'A has the smallest ED50 and reaches 100%: the drug behaves like a full agonist with all the receptors it needs, the high-density line.'},
  {t:'B', correct:false, why:'B is in between: the ED50 is higher than A’s and the maximum is lower, but C has lost more.'},
  {t:'They are equal; the drug changed', correct:false, why:'The drug is the same; only the number of receptors differs between the cell lines.'}],
 teach:'In a cell line with high receptor density the agonist binds easily, produces its full effect and behaves like a full agonist. In cell lines with fewer receptors the same drug loses potency (the ED50 climbs from about 10 to the minus 7 toward 10 to the minus 4.5 and 10 to the minus 3.5) and loses the maximal effect, as with an irreversible antagonist.',
 quote:'as I start to move from less and less receptors, what is happening to the ED5 of my drug? It’s increasing ... I’m not only decreasing my affinity of my drug, but also I’m decreasing what? The ability to produce the max effect.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 28; transcript 9/29'},

{id:'L05-029', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'reg', skill:'recall',
 concept:'tolerance-definition', tags:[], source:'both',
 stem:'A patient using an α-adrenoreceptor agonist nasal decongestant every day for weeks finds it no longer works at the same dose. What is this called and what causes it?',
 options:[
  {t:'Tolerance, from receptor down-regulation', correct:true, why:'The effects that follow continued exposure to the same concentration of drug are diminished; too much agonist stimulation lowered the receptor number.'},
  {t:'Tolerance, from receptor up-regulation', correct:false, why:'Up-regulation would make the agonist more potent, not less.'},
  {t:'Synergism with the body’s own norepinephrine', correct:false, why:'Synergism is two drugs producing more than the sum of their effects; here one drug is losing its effect.'},
  {t:'Rapid desensitization only', correct:false, why:'β-arrestin binding is milliseconds; weeks of use is the long-term process.'}],
 teach:'Tolerance: the effects that follow continued exposure to the same concentration of drug are diminished. It is the clinical manifestation of down-regulation: opioid analgesics, α-adrenoreceptor agonists used as nasal decongestants (the box says 2 to 3 days only), cocaine. The body suppresses the receptor number to counteract the stimulation, so more drug is needed for the same effect.',
 quote:'Tolerance: The effects that follow continue exposure to the same concentration of drug is diminished',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 17, 29; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Variation in Drug Responsiveness', t:'Responsiveness that decreases with continued drug administration is relative tolerance; agonist-induced downregulation or desensitization of receptors contributes to it.'}]},

/* ---------------- Enhancement of drug effects (pages 30–31) ---------------- */
{id:'L05-030', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'enh', skill:'tell',
 concept:'synergism', tags:[], source:'both',
 stem:'Penicillin alone kills 30% of a bacterial colony and gentamicin alone kills 50%. Given together they kill 100%. What is this drug–drug interaction called?',
 options:[
  {t:'Synergism', correct:true, why:'Both drugs have an effect, and together the effect is greater in magnitude than the sum of each drug alone.'},
  {t:'Addition', correct:false, why:'Addition gives exactly the sum of the individual effects (30 + 50 = 80, not 100).'},
  {t:'Potentiation', correct:false, why:'In potentiation one drug lacks an effect on its own; here both kill bacteria.'},
  {t:'Indirect antagonism', correct:false, why:'Neither drug is inhibiting the other’s signal; they enhance each other.'}],
 teach:'Addition: two different drugs with the same effect are given together and the result equals the sum of the individual effects (trimethoprim and sulfamethoxazole; two antibiotics each killing 50% kill 100% together). Synergism: two drugs with the same effect give a result greater in magnitude than the sum of each drug alone (penicillin and gentamicin, antipseudomonal activity). One plus one equals five.',
 quote:'So they both have an effect and when we put them together, they’re greater than the independently they do together. So this is you have 1 plus 1 and you get 5.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 30; transcript 9/29'},

{id:'L05-031', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'enh', skill:'tell',
 concept:'potentiation-carbidopa', tags:[], source:'both',
 stem:'Carbidopa has no benefit on its own for a Parkinson’s patient, but given with L-DOPA it makes L-DOPA much more effective. What is this called?',
 options:[
  {t:'Potentiation', correct:true, why:'One drug lacks an effect on its own but increases the effect of another: carbidopa is an inactive analog that blocks the breakdown of dopa.'},
  {t:'Synergism', correct:false, why:'In synergism both drugs have an effect by themselves; carbidopa does not.'},
  {t:'Addition', correct:false, why:'Addition is the sum of two effects; carbidopa contributes no effect of its own.'},
  {t:'Physiological antagonism', correct:false, why:'Carbidopa helps L-DOPA; it does not oppose it.'}],
 teach:'Potentiation: one drug lacks an effect on its own but increases the effect of another. Carbidopa is an inactive analog that blocks the enzyme in the gut that breaks down dopa, so more dopamine gets to the brain; it is classified as an indirect antagonist. In synergism both drugs have efficacy and make each other better; in potentiation one is neutral by itself.',
 quote:'In synergism, both drugs have an efficacy. They have an effect, and together they make each other better. Here, one is neutral, has no effect by itself, but it can make the other a lot more potent.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 31; transcript 9/29'},

/* ---------------- Individual vs population, quantal responses (pages 32–38) ---------------- */
{id:'L05-032', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'quant', skill:'tell',
 concept:'graded-vs-quantal', tags:[], source:'both',
 stem:'Which statement is CORRECT about graded and quantal responses?',
 options:[
  {t:'A graded response is measured on one sample, on a scale from no effect to maximum', correct:false, why:'Correct statement (degree of muscle contraction with nicotine, degree of paralysis by curare), but not the only correct one.'},
  {t:'A quantal response is a binary measurement: any effect or none', correct:false, why:'Correct statement (alive or dead, a 5% increase in blood pressure or not), but not the only correct one.'},
  {t:'Populations are usually studied with quantal responses', correct:false, why:'Correct statement, but not the only correct one.'},
  {t:'All of the above', correct:true, why:'All three statements are correct.'}],
 teach:'Until now every example was one sample: degree of muscle contraction with nicotine, degree of paralysis by curare, measured from no effect to maximum, a graded response. A population is usually studied with a quantal response: a binary measurement, any effect or none, alive or dead, a defined response such as a 5% increase in blood pressure. Does this drug take care of your back pain, yes or no.',
 quote:'So it’s going to be a binary measurement. It’s either yes or no, OK? Either you have an effect or you don’t. Either you’re either you’re dead or alive. You can’t be in between',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 32–33; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Quantal Dose-Effect Curves', t:'A graded dose–response curve shows the maximal efficacy of a drug; a quantal dose–effect curve shows the variability of responsiveness among individuals.'}]},

{id:'L05-033', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'quant', skill:'figure',
 concept:'quantal-cumulative-sigmoid', tags:[], source:'both',
 stem:'Which statement is CORRECT? Dogs of different breeds are given rising doses of epinephrine (7.7 to 108 ng/kg/min) and the number of dogs whose blood pressure rises at each dose is plotted as bars.',
 options:[
  {t:'Joining the peaks of the bars gives a normal distribution curve', correct:false, why:'Correct statement (most dogs respond in the middle, a few are very sensitive or very resistant), but not the only correct one.'},
  {t:'Graphing the same data in cumulative form gives a sigmoidal curve', correct:false, why:'Correct statement (a dog sensitive to 7.7 is also sensitive to 10, 13 and 17, so the responders accumulate), but not the only correct one.'},
  {t:'The cumulative curve allows the effects of different ligands to be compared in a population', correct:false, why:'Correct statement, but not the only correct one.'},
  {t:'All of the above', correct:true, why:'All three statements are correct.'}],
 teach:'The bar graph of number responding vs dose is non-cumulative: it shows who is sensitive and who is resistant; joining the peaks makes a normal distribution curve. Graphing the data cumulatively (a dog sensitive to 7.7 is also sensitive to every higher dose) creates the sigmoidal curve, which gives the threshold and the dose treating 50% (about 29 ng/kg/min here) and lets ligands be compared in a population.',
 quote:'So now, instead of having this bell-shaped curve, I have an old sigmoid curve that we did before. I can determine now this cumulative effect.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 33–34; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Quantal Dose-Effect Curves', t:'The doses needed to produce a specified quantal effect are lognormally distributed; summing the frequency distribution gives the cumulative quantal dose–effect curve of the percentage of individuals responding at each log dose.'}]},

{id:'L05-034', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'quant', skill:'figure',
 concept:'ed50-population', tags:[], source:'both',
 stem:'In an acetaminophen study, students with a headache receive increasing doses (100 mg steps, evaluated every 15 minutes) and answer yes or no to “do you still have a headache?”. The cumulative curve crosses 50% of responders at about 325 mg. What is 325 mg called?',
 options:[
  {t:'The ED50', correct:true, why:'On a quantal curve the effective dose 50 is the dose at which half the population shows the defined response.'},
  {t:'The LD50', correct:false, why:'The LD50 is the dose that kills 50% of the population, read from a mortality curve, not a headache-relief curve.'},
  {t:'The Emax', correct:false, why:'Emax belongs to the graded curve of one sample; the top of a quantal curve is 100% of the population responding.'},
  {t:'The Kd', correct:false, why:'Kd is the concentration binding half the receptors on a binding curve, not a population dose.'}],
 teach:'From the cumulative quantal data come the minimum dose that does something, the maximum dose, and the dose that takes care of half of the population, the effective dose 50 (ED50). For the headache study that is about 325 mg, the dose that takes care of 50% of you.',
 quote:'I can just go straight to the 325, which is gonna be the dose that takes care of 50% of you.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 36–38; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Quantal Dose-Effect Curves', t:'On a quantal curve the median effective dose (ED50) is the dose at which 50% of individuals exhibit the specified effect, a different meaning from the ED50 of a graded curve.'}]},

/* ---------------- Therapeutic index, safety index, therapeutic window (pages 35, 39–44) ---------------- */
{id:'L05-035', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'recall',
 concept:'therapeutic-index-definition', tags:['poll'], source:'both',
 stem:'The larger the therapeutic index (TI), the safer the drug. True or False?',
 options:[
  {t:'True', correct:true, why:'TI = LD50/ED50; the larger the ratio, the wider the window of doses between the good and the bad of the drug.'},
  {t:'False', correct:false, why:'A small TI means the effective and lethal doses are close together, very little room for mistakes.'}],
 teach:'The therapeutic index estimates the drug’s margin of safety: the ratio of the toxic (lethal or sub-lethal) effect to the therapeutic effect, mathematically LD50 divided by ED50, the window of doses between the good and the bad of the drug. The larger the ratio the safer the drug; the narrower it is, the less room before going from good to bad. Phenobarbital TI = 10, alprazolam TI = 2500.',
 quote:'So, the larger the therapeutic index is, the safer it’s gonna be because my window is gonna be huge. The narrower it is, oh man, I have very little room to mistakes over here before going from good to bad',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 35, 39; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Quantal Dose-Effect Curves', t:'The therapeutic index relates the dose required for a desired effect to the dose that produces an undesired effect, defined in animal studies as TD50 divided by ED50.'}]},

{id:'L05-036', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'calc',
 concept:'ti-phenobarbital-alprazolam', tags:[], source:'both',
 stem:'Phenobarbital has an LD50 of 40 mg/kg and an ED50 of 4 mg/kg. Alprazolam has a therapeutic index (TI) of 2500. Which statement is CORRECT?',
 options:[
  {t:'Phenobarbital’s TI is 10, so alprazolam is the safer drug', correct:true, why:'TI = LD50/ED50 = 40/4 = 10; 2500 is far larger, a much wider dose range before it can kill anybody.'},
  {t:'Phenobarbital’s TI is 0.1, so phenobarbital is the safer drug', correct:false, why:'0.1 is ED50/LD50, the ratio upside down; and a smaller TI is less safe, not more.'},
  {t:'Phenobarbital’s TI is 160', correct:false, why:'160 is 40 times 4; the TI is a quotient, 40 divided by 4.'},
  {t:'The two drugs are equally safe', correct:false, why:'10 and 2500 are very different; the barbiturate has a very small range of doses before it kills.'}],
 teach:'TI = LD50/ED50. Phenobarbital: 40 (mg/kg) divided by 4 (mg/kg) = 10. Alprazolam: 2500. The larger the number, the safer the drug: the benzodiazepine has a much wider dose range before it can kill anybody, the barbiturate a very small range. The math on the exam is simple division with whole numbers; the trap is inverting the ratio.',
 quote:'if you know the lethal dose that’s going to kill 50% of the population and you know the effective dose that is. To treat 50% of the population and you divide one by the other, you can come up with a therapeutic index',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 39; transcript 9/29'},

{id:'L05-037', dupOf:'L05-038', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'calc',
 concept:'ti-from-curves', tags:['poll'], source:'both',
 stem:'Two cumulative quantal curves are drawn for one drug: the percent of individuals showing the desired effect reaches 50% at 10 mg, and the percent dead at each dose reaches 50% at 160 mg. What is the therapeutic index (TI)?',
 options:[
  {t:'16', correct:true, why:'TI = LD50/ED50 = 160/10 = 16.'},
  {t:'0.0625', correct:false, why:'10/160 is the ratio inverted; the lethal dose goes on top.'},
  {t:'150', correct:false, why:'160 minus 10 is a difference, not the ratio.'},
  {t:'1600', correct:false, why:'160 times 10 is a product; the TI divides LD50 by ED50.'}],
 teach:'Find the effective dose that treats 50% of the population on the left curve (ED50 = 10 mg) and the lethal dose that kills 50% on the right curve (LD50 = 160 mg); the lethal curve is to the right because people are treated before they are killed. TI = LD50/ED50 = 160/10 = 16. With equal efficacy, the drug with the larger TI is the one to give.',
 quote:'if I divide the LD50 by the ED50, I’m gonna get the therapeutic index, which is in this case is 16.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 40; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Quantal Dose-Effect Curves', t:'The median lethal dose (LD50) is the dose that kills 50% of animals; the median toxic dose (TD50) is the dose producing a specified toxic effect in 50%.'}]},

{id:'L05-038', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'calc',
 concept:'ti-from-curves', tags:['poll'], source:'both',
 stem:'A drug produces hypnosis and, at higher doses, death. The cumulative curve for hypnosis crosses 50% at 100 μg/kg (ED50); the cumulative curve for death crosses 50% at 400 μg/kg (LD50). What is the TI of this drug?',
 options:[
  {t:'0.25', correct:false, why:'100/400 is the ratio inverted.'},
  {t:'1', correct:false, why:'The two doses are not equal; 400 divided by 100 is not 1.'},
  {t:'4', correct:true, why:'TI = LD50/ED50 = 400/100 = 4.'},
  {t:'100', correct:false, why:'100 is the ED50 itself, not the ratio.'},
  {t:'400', correct:false, why:'400 is the LD50 itself, not the ratio.'}],
 teach:'The exam figure will not label ED50 and LD50: find the dose at which the therapeutic curve crosses 50% and the dose at which the lethal curve crosses 50%, then divide the lethal dose by the effective dose. 400 divided by 100 = 4. The distractors are the numbers you would get by inverting the ratio or by reading one dose alone.',
 quote:'The lethal dose that kills 50% divided by the effective dose that treats 50% of the population',
 cite:'transcript 9/29 (PollEV, 9/29); Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 41'},

{id:'L05-039', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'apply',
 concept:'ti-is-drug-safe', tags:['poll'], source:'both',
 stem:'For the hypnosis/death drug (ED50 100 μg/kg, LD50 400 μg/kg, TI = 4), the dose that treats 99% of patients (ED99) and the dose that kills 1% (LD1) both fall at about 200 μg/kg. Is this drug safe?',
 options:[
  {t:'Yes, its lethal curve lies to the right of its effective curve', correct:false, why:'Every drug’s lethal curve lies to the right; the question is how far, and here the two overlap.'},
  {t:'Yes, its TI of 4 is greater than 1', correct:false, why:'The TI compares only the two 50% points; the tails overlap here, so people die before everyone is treated.'},
  {t:'No, it kills some before treating all', correct:true, why:'The dose that kills 1% is about the same as the dose that treats 99%: patients start dying before everyone is treated.'},
  {t:'No, its ED50 is above its LD50', correct:false, why:'The ED50 (100) is below the LD50 (400); that is not the problem.'}],
 teach:'The drug is not safe: it is already killing people before it treats everybody. For a drug to be safe the ED99 should be less than the LD1, so the two curves should be far apart. A very toxic drug like this is used only when there are no other options. On the exam: find the points, do the math, then judge whether the curves are far enough apart.',
 quote:'No, why not? Because you’re already healing people before we treat even all the population, right? This is a very toxic drug that is not going to do much good for us unless you have no other options.',
 cite:'transcript 9/29 (PollEV, 9/29); Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 41–42'},

{id:'L05-040', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'calc',
 concept:'safety-index', tags:['poll'], source:'both',
 stem:'A sleeping drug: ED50 = 0.1, LD50 = 100, ED99 = 10, LD1 = 1 (dose units on a log scale). What are its therapeutic index (TI) and safety index (SI)?',
 options:[
  {t:'TI = 1000; SI = 0.1', correct:true, why:'TI = LD50/ED50 = 100/0.1 = 1000; SI = LD1/ED99 = 1/10 = 0.1.'},
  {t:'TI = 1000; SI = 10', correct:false, why:'10/1 is the effective dose on top, which is how he read it aloud; the slide formula is SI = LD1/ED99 = 1/10 = 0.1, and either way the conclusion is the same: not a safe drug.'},
  {t:'TI = 0.001; SI = 0.1', correct:false, why:'0.1/100 is the TI inverted.'},
  {t:'TI = 100; SI = 1', correct:false, why:'Neither ratio is right: 100/0.1 is 1000, and 1/10 is 0.1.'}],
 teach:'TI = LD50/ED50 = 100/0.1 = 1000. The safety index asks what dose treats 99% of patients and what dose kills 1%: SI = LD1/ED99 = 1/10 = 0.1. The dose that kills 1% (1) is one tenth of the dose effective in 99% (10): of 100 patients, 99 sleep and one dies. The larger the SI the safer; for a safe drug the ED99 is less than the LD1.',
 quote:'For a drug to be safe the ED99 should be less than the LD1',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 42; transcript 9/29',
 note:'The slide gives SI = LD01/ED99 = 1/10 = 0.1. In class he read the numbers as “the effective dose, which is 10 ... divided by the lethal dose” and the transcript says “1.1”; the slide formula and its result (0.1) are what to use on the exam, and the conclusion is the same: not a safe drug.'},

{id:'L05-041', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'apply',
 concept:'safety-index-interpretation', tags:['poll'], source:'both',
 stem:'A drug has a therapeutic index of 1000 and a safety index of 0.1. Which statement is CORRECT?',
 options:[
  {t:'It is safe: a TI of 1000 means the lethal dose is a thousand times the effective dose', correct:false, why:'The TI alone is not enough; a large TI can hide an SI below 1.'},
  {t:'It is not safe: the dose that kills 1% is a tenth of the dose that treats 99%', correct:true, why:'SI = LD1/ED99 = 0.1 means patients die before all are treated; for a safe drug the ED99 must be less than the LD1.'},
  {t:'It is safe: the SI is below 1', correct:false, why:'Reversed; the bigger the SI, the safer the drug.'},
  {t:'The two numbers contradict each other', correct:false, why:'They measure different things: the TI compares the 50% points, the SI compares the 99% effective and 1% lethal points.'}],
 teach:'A TI of 1000 says nothing about the tails of the curves. The SI compares the dose that treats 99% with the dose that kills 1%. An SI of 0.1 means the killing dose is a tenth of the dose that treats everybody: not a safe drug. For a safe drug both TI and SI must be large, and the ED99 less than the LD1.',
 quote:'So, for a drug to be safe, not only its TI has to be large, but also it’s SI, OK?',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 42; transcript 9/29'},

{id:'L05-042', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'apply',
 concept:'ti-compare-drugs', tags:['poll'], source:'both',
 stem:'Five drugs with equal efficacy have therapeutic indices of 4, 10, 16, 40 and 2500. Which is the safest, and which the most toxic?',
 options:[
  {t:'Safest 2500; most toxic 4', correct:true, why:'The larger the ratio the safer the drug; the smallest ratio has the narrowest window between the effective and lethal doses.'},
  {t:'Safest 4; most toxic 2500', correct:false, why:'Reversed: a small TI means the ED50 and LD50 are close together.'},
  {t:'Safest 16; most toxic 40', correct:false, why:'Neither is an extreme; the TI ranks the drugs from 4 (worst) to 2500 (best).'},
  {t:'They are equally safe; only efficacy differs', correct:false, why:'Efficacy is equal here; the TI is what separates them, and it differs widely.'}],
 teach:'One way he asks: here are five drugs and their therapeutic index values; which is the safest, which the most toxic? The bigger the TI the safer the drug. If two drugs have equal efficacy, go for the one with the larger TI (and SI). If a drug is very toxic but there is no other option, it is used anyway.',
 quote:'One is I can give you a number of drugs. I said there’s 5 drugs. Here are their therapeutic index values. Which of these drugs is the safest? Which one is the more toxic? But if you understand that the bigger it is, the safer it is, then you’re in good terms.',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 39–41; transcript 9/29'},

{id:'L05-043', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'apply',
 concept:'ti-depends-on-effect-measured', tags:[], source:'both',
 stem:'Codeine is used for cough and for pain. Its therapeutic index for cough is very large and for pain very small. Why does one drug have two therapeutic indices?',
 options:[
  {t:'The TI depends on which effect is measured; no drug produces a single effect', correct:true, why:'The TI is a statement of how selective a drug is in producing a desired effect, so it is calculated per effect: cough suppression takes very little codeine, pain relief takes much more.'},
  {t:'The LD50 changes with the indication', correct:false, why:'The lethal dose is the same drug and the same population; it is the ED50 that differs between cough and pain.'},
  {t:'Codeine acts at two different receptors with different Kd values for cough and pain', correct:false, why:'Not part of the explanation given; the point is the parameter measured, not the receptor.'},
  {t:'The larger index is a rounding error', correct:false, why:'The difference is real: it takes very little codeine to stop a cough and much more to treat pain.'}],
 teach:'The therapeutic index is a statement of how selective a drug is in producing its desired effects, and no drug produces a single effect. So the TI is calculated for the parameter being measured: codeine for cough has a huge window (a drop of codeine in an over-the-counter antitussive), codeine for pain a very narrow one. Compare drugs on the same effect, apples with apples.',
 quote:'depending what parameter or function you’re measuring, even the same drug can have different therapeutic index, right?',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 41; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Quantal Dose-Effect Curves', t:'Comparing a drug’s ED50 values for two different quantal effects in a population gives an index of the selectivity of its action.'}]},

{id:'L05-044', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'recall',
 concept:'therapeutic-window', tags:[], source:'both',
 stem:'What is the therapeutic window of a drug?',
 options:[
  {t:'The range of steady-state concentrations that gives therapeutic efficacy with minimal toxicity', correct:true, why:'The window lies between the concentration that produces the therapeutic response and the concentration at which adverse effects begin.'},
  {t:'The ratio of the lethal dose that kills 50% of the population to the effective dose that treats 50%', correct:false, why:'That ratio is the therapeutic index, a single number, not a range of concentrations.'},
  {t:'The time between doses', correct:false, why:'A dosing interval is not the window; the window is a range of plasma concentrations.'},
  {t:'The dose that treats 50% of the population', correct:false, why:'That is the ED50, one point on the quantal curve.'}],
 teach:'The therapeutic window is the range of steady-state concentrations of drug that provides therapeutic efficacy with minimal toxicity. The clinically acceptable risk of toxicity depends critically on the severity of the disease being treated: treating a headache is not treating Hodgkin’s lymphoma. Knowing the TI and the SI tells you the window in which it is safe to give the drug.',
 quote:'So that by knowing the TI and the SI, we know that therapeutic window that it’s safe to give a drug to our patients, right?',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf page 43; transcript 9/29',
 reading:[{src:'Katzung 16e, Ch. 2', sec:'Quantal Dose-Effect Curves', t:'The range between the minimum therapeutic dose and the minimum toxic dose is the therapeutic window; the acceptable risk of toxicity depends on the severity of the disease treated.'}]},

{id:'L05-045', lecture:'L05', prof:'Gottlieb', tier:'new', topic:'L05', sub:'ti', skill:'recall',
 concept:'side-effects-predictable', tags:['poll'], source:'both',
 stem:'Which statement is CORRECT about side effects?',
 options:[
  {t:'They are predictable if the pharmacology of the ligand is known', correct:false, why:'Correct statement (ligand affects receptor, receptor affects cell function, cell function gives the observable response), but not the only correct one.'},
  {t:'Undesired actions of drugs are commonly called side effects or adverse drug reactions (ADR)', correct:false, why:'Correct statement, but not the only correct one.'},
  {t:'A toxic effect is an example of an undesired effect and can be lethal or sub-lethal', correct:false, why:'Correct statement, but not the only correct one.'},
  {t:'All of the above', correct:true, why:'All three statements are correct.'}],
 teach:'Side effects are predictable if the pharmacology of a ligand is known: the ligand affects receptor function, receptors change cell function, and that gives the observable clinical response. Undesired actions are called side effects or ADRs; a toxic effect can be lethal or sub-lethal. Sildenafil (studied for blood pressure, marketed for the erectile side effect) and minoxidil (blood pressure, then hair loss) show the desired effect depends on the aim.',
 quote:'the desired effect, right, it can be one or the other. It depends what you’re trying to do because multiple drugs can target multiple receptors, especially depending on the dose',
 cite:'Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf pages 35, 44; transcript 9/29'}
);
