TOPICS.push({id:"L11", name:"Day 11: β receptors, epinephrine and norepinephrine, β blockers, nitric oxide", prof:"Gottlieb", lecture:"L11",
  cite:"Day 11 (10/7) — PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf (slides 33–85 taught)",
  subs:[
    {id:"mirt", name:"Mirtazapine's adverse reactions", cite:"slide 33"},
    {id:"pbz", name:"Phenoxybenzamine", cite:"slides 34–38"},
    {id:"beta", name:"β receptors: dobutamine, β2 agonists, mirabegron, isoproterenol", cite:"slides 39–45"},
    {id:"epi", name:"Epinephrine and epinephrine reversal", cite:"slides 46–52"},
    {id:"ne", name:"Norepinephrine", cite:"slide 53"},
    {id:"bb", name:"β blockers", cite:"slides 54–59"},
    {id:"xtalk", name:"Review and cross-talk", cite:"slides 60–61"},
    {id:"no", name:"Nitric oxide, cGMP and PDE inhibitors", cite:"slides 62–74"},
    {id:"lab", name:"Lab tracings: acetylcholine, atropine, norepinephrine", cite:"slides 75–85"}
  ]});
QUESTIONS.push(
/* ---------------- Mirtazapine's adverse reactions (slide 33) ---------------- */
{id:"L11-001", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"mirt", skill:"recall", multi:true,
 concept:"mirtazapine-adrs", tags:[], source:"both",
 stem:"Which adverse reactions are expected with mirtazapine? Select all that apply.",
 options:[
  {t:"Drowsiness", correct:true, why:"Blockade of muscarinic and histamine (H1) receptors in the brain causes sedation."},
  {t:"Weight gain", correct:true, why:"Listed under endocrine effects (with increased cholesterol); he tied it to the serotonin effect."},
  {t:"Dry mouth and constipation", correct:true, why:"Muscarinic blockade gives these anti-DUMBBELSS effects."},
  {t:"Peripheral edema", correct:true, why:"Blockade of α1 relaxes the vessels in the periphery."},
  {t:"Diarrhea", correct:false, why:"Diarrhea is a muscarinic agonist effect; mirtazapine blocks muscarinic receptors (constipation)."},
  {t:"Miosis", correct:false, why:"Miosis is a muscarinic agonist effect; no pupil effect was given for mirtazapine."}],
 teach:"Mirtazapine blocks presynaptic α2, histamine H1, muscarinic and α1 receptors. Its adverse reactions follow: drowsiness (H1 and muscarinic block), weight gain and increased serum cholesterol (serotonin), dry mouth (xerostomia) and constipation (muscarinic block), peripheral edema (α1 block) and hypertension (more norepinephrine release). Agranulocytosis is a rare effect he called FYI.",
 quote:"So, we're gonna get your drowsiness because we're blocking the muscarinic antihistamine receptors, uh, weight gain, as you're gonna learn in the CNS, any drug that affects serotonin can have an effect on the weight, uh, of our patients. Uh, by blocking those muscarinics, you're gonna get. The anti-dumbbells, so you can't salivate, you're gonna get dry, dry mouth",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 33; transcript 10/7"},

{id:"L11-002", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"mirt", skill:"apply",
 concept:"mirtazapine-edema-alpha1", tags:[], source:"both",
 stem:"A patient on mirtazapine develops peripheral edema. Which receptor blockade explains it?",
 options:[
  {t:"α1", correct:true, why:"Blocking α1 relaxes the arteries and veins of the periphery; fluid collects there."},
  {t:"Histamine H1", correct:false, why:"H1 block (with muscarinic block) is tied to drowsiness."},
  {t:"Muscarinic", correct:false, why:"Muscarinic block is tied to dry mouth and constipation (and sedation)."},
  {t:"β1", correct:false, why:"Mirtazapine does not block β1."}],
 teach:"Slide 33 lists peripheral edema under cardiovascular effects with “Blockade of alpha 1”. Without α1 tone the peripheral vessels relax. The same patient may instead become hypertensive, because α2 block raises norepinephrine release, so the net effect varies from patient to patient.",
 quote:"and uh you can get peripheral edema by blocking the alpha-1s, but that can be overcome by increase of the sympathetic and norepinephrine which causes increase in blood pressure. So it varies from patient to patient.",
 note:"The drug list (page 6) blames peripheral edema on α2 block in small blood vessels; slide 33 and the 10/7 audio give α1 block. Keyed to the slide and his words.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 33; transcript 10/7"},

{id:"L11-003", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"mirt", skill:"tell",
 concept:"mirtazapine-adr-causes", tags:[], source:"both",
 stem:"Which pairing of a mirtazapine adverse reaction and its cause is CORRECT?",
 options:[
  {t:"Xerostomia: muscarinic block", correct:true, why:"Dry mouth (xerostomia) and constipation come from blocking muscarinic receptors."},
  {t:"Drowsiness: α1 block", correct:false, why:"Drowsiness comes from blocking muscarinic and histamine H1 receptors."},
  {t:"Peripheral edema: H1 block", correct:false, why:"Peripheral edema comes from α1 block."},
  {t:"Hypertension: muscarinic block", correct:false, why:"Hypertension comes from increased norepinephrine release (α2 block)."},
  {t:"Weight gain: α2 block", correct:false, why:"Weight gain is tied to serotonin."}],
 teach:"Each mirtazapine adverse reaction maps to one of its actions: drowsiness — muscarinic and H1 block; weight gain and higher cholesterol — serotonin; xerostomia and constipation — muscarinic block; peripheral edema — α1 block; hypertension — more norepinephrine release from α2 block.",
 quote:"Uh, the GI, you know, you're gonna have, uh, uh, dry mouth and constipation associated with that because of the muscarinic blockade that you're gonna have, as well as some maybe hypertension, uh, and peripheral edema on the periphery.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 33; transcript 10/7"},

{id:"L11-004", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"mirt", skill:"apply",
 concept:"mirtazapine-htn-ne", tags:[], source:"both",
 stem:"Some patients on mirtazapine develop hypertension. Which action explains it?",
 options:[
  {t:"More norepinephrine release", correct:true, why:"Blocking the presynaptic α2 autoreceptor removes the brake on release; more norepinephrine raises blood pressure."},
  {t:"Blockade of α1 in arteries", correct:false, why:"α1 block relaxes vessels (peripheral edema); it does not raise pressure."},
  {t:"Blockade of histamine H1", correct:false, why:"H1 block is tied to drowsiness."},
  {t:"Activation of muscarinic receptors", correct:false, why:"Mirtazapine blocks muscarinic receptors; it does not activate them."}],
 teach:"Slide 33 lists hypertension with “Increase NE release”. Mirtazapine inhibits the inhibitor (presynaptic α2), so more norepinephrine is released. Its α1 block pushes the other way, so some patients become hypertensive and others do not.",
 quote:"but that can be overcome by increase of the sympathetic and norepinephrine which causes increase in blood pressure. So it varies from patient to patient. Some patients get hypertension",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 33; transcript 10/7"},

/* ---------------- Phenoxybenzamine (slides 34–38) ---------------- */
{id:"L11-005", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"pbz", skill:"recall",
 concept:"phenoxybenzamine-covalent", tags:[], source:"both",
 stem:"Which describes how phenoxybenzamine binds α receptors?",
 options:[
  {t:"Covalently and irreversibly", correct:true, why:"It forms covalent bonds with α1 and α2; norepinephrine cannot outcompete it."},
  {t:"Reversibly and competitively", correct:false, why:"That is prazosin, a reversible α1 antagonist."},
  {t:"As a partial agonist", correct:false, why:"Phenoxybenzamine is an antagonist; pindolol is the partial agonist in this deck."},
  {t:"At an allosteric site that raises potency", correct:false, why:"It blocks the receptors; it does not enhance them."}],
 teach:"Phenoxybenzamine is an irreversible, non-selective α1 and α2 antagonist. It forms covalent bonds with the receptors, so however much epinephrine or norepinephrine the body makes, it cannot outcompete the drug; activity returns only as new receptors are made.",
 quote:"This is an irreversible non-selective alpha 1, alpha 2 adrenergic receptor antagonist, which means it's going to form covalent bonds.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 34–35; transcript 10/7"},

{id:"L11-006", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"pbz", skill:"apply",
 concept:"phenoxybenzamine-pheochromocytoma", tags:[], source:"both", lowYield:true,
 stem:"A patient with a pheochromocytoma (an adrenal tumor making large amounts of epinephrine and norepinephrine) needs blood pressure control until surgery. Why is phenoxybenzamine chosen over prazosin?",
 options:[
  {t:"Its block cannot be outcompeted", correct:true, why:"Its covalent block holds no matter how much epinephrine and norepinephrine the tumor releases."},
  {t:"It is selective for α1", correct:false, why:"Phenoxybenzamine is non-selective (α1 and α2); prazosin is the selective one."},
  {t:"It also blocks β1 in the heart", correct:false, why:"Phenoxybenzamine blocks α1 and α2, not β receptors."},
  {t:"It lowers how much catecholamine the tumor makes", correct:false, why:"It blocks the receptors; it does not change how much the tumor makes."}],
 teach:"He gave two uses: short-term control in pheochromocytoma until surgery, and, in the past, the hypertensive crisis of patients on non-selective monoamine oxidase (MAO) inhibitors such as phenelzine (the cheese effect). In both, the reason is the covalent, irreversible block that high catecholamine levels cannot overcome.",
 quote:"So by permanently blocking with covalent bonds, that means that I can produce all the epi and norepinephrine that I want, I can't outcompete those because I'm covalently bound to it. So we're gonna use that for a very short period of time.",
 note:"A use; his 10/5 rule is that uses are not tested, so this is marked low yield. The mechanism behind it (irreversible, cannot be outcompeted) is the testable point.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 34–35; transcript 10/7"},

{id:"L11-007", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"pbz", skill:"apply",
 concept:"phenoxybenzamine-gi-stimulation", tags:["in-class"], source:"both",
 stem:"Phenoxybenzamine causes cramping and diarrhea. Which mechanism explains this?",
 options:[
  {t:"α2 on parasympathetic nerves is blocked", correct:true, why:"α2 (Gi) normally brakes acetylcholine release in the gut; blocking it lets more acetylcholine reach M3."},
  {t:"α1 on gut smooth muscle is activated", correct:false, why:"Phenoxybenzamine is an antagonist; it activates nothing."},
  {t:"Acetylcholinesterase in the gut is blocked", correct:false, why:"That is the -stigmine drugs; phenoxybenzamine does not touch the enzyme."},
  {t:"M3 in the gut is blocked", correct:false, why:"Blocking gut M3 gives constipation, the opposite."}],
 teach:"The sympathetic system normally inhibits the parasympathetic in the gut: norepinephrine acts on α2 (Gαi, inhibitory) on the parasympathetic nerve and lowers acetylcholine release. Phenoxybenzamine blocks α2 irreversibly, so the brake is gone; more acetylcholine activates M3 (Gq, more calcium), raising gut motility and tone — cramping and diarrhea.",
 quote:"Now as we block the alpha juice, now we're going to get gastrointestinal tract stimulation. Why is that? What is the function of the alpha chews on the gut to suppress the parasympathetic. So if I take away the brakes, now my parasympathetic has no inhibition, gonna release a lot of acetylcholine, it's gonna activate a lot of those M3s",
 note:"He asked the class “What is the function of the alpha 2s on the gut?” and answered it himself. The transcript renders “alpha 2s” as “alpha juice/chews”.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 36–38; transcript 10/7"},

{id:"L11-008", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"pbz", skill:"apply", multi:true,
 concept:"phenoxybenzamine-adrs", tags:[], source:"both",
 stem:"Which adverse reactions are expected with phenoxybenzamine? Select all that apply.",
 options:[
  {t:"Orthostatic hypotension", correct:true, why:"α1 block in arteries and veins; not enough blood reaches the heart and brain on standing."},
  {t:"Reflex tachycardia", correct:true, why:"The baroreceptors sense the drop in pressure, suppress the parasympathetic and increase the sympathetic."},
  {t:"GI stimulation", correct:true, why:"α2 block on the parasympathetic nerve lets more acetylcholine reach gut M3."},
  {t:"Miosis", correct:true, why:"α1 block in the eye leaves the parasympathetic as the predominant tone."},
  {t:"Constipation", correct:false, why:"The gut is stimulated, not slowed."},
  {t:"Mydriasis", correct:false, why:"α1 block makes the pupil smaller (miosis)."},
  {t:"Bradycardia", correct:false, why:"Heart rate rises by reflex (tachycardia, arrhythmias, ischemia)."}],
 teach:"Slides 36–38: reflex cardiac stimulation (tachycardia, arrhythmias and ischemia), enhanced norepinephrine secretion, orthostatic hypotension, GI stimulation and miosis. The α1 effects are the same as prazosin's; the GI stimulation comes from α2 block.",
 quote:"The side effect profile is going to be kind of similar to the prazosin. ... we can get the reflex tachycardia because as you drop your blood pressure, the barrels are going to sense they're going to suppress the parasympathetic and increase the sympathetic so that it can try to bring that back up.",
 note:"In the audio he says “You're going to get the hypertension, which may cause the orthostatic hypertension”; slides 36–38 say orthostatic hypotension, and he describes people passing out. Keyed to the slide.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 36–38; transcript 10/7"},

{id:"L11-009", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"pbz", skill:"apply",
 concept:"phenoxybenzamine-miosis", tags:[], source:"both",
 stem:"A patient on phenoxybenzamine complains of poor vision at night. Which explains it?",
 options:[
  {t:"Small pupils from α1 block", correct:true, why:"α1 opens the pupil; with α1 blocked the parasympathetic tone predominates and the pupils stay small (miosis)."},
  {t:"Large pupils from α2 block", correct:false, why:"The pupil gets smaller, not larger."},
  {t:"Large pupils from M3 block", correct:false, why:"Phenoxybenzamine does not block muscarinic receptors."},
  {t:"Small pupils from β2 activation", correct:false, why:"Phenoxybenzamine blocks α receptors; it does not activate β2."}],
 teach:"In the eye, α1 receptors pull the pupil open (radial muscle). Blocking them leaves the parasympathetic (M3) as the predominant tone, so the pupil constricts — miosis. Patients complain of blurred vision and of not seeing at night.",
 quote:"Um also may get meiosis because they're gonna block the alpha ones which are trying to open up our pupils, and that's parasympathic now is the predominant tone. It's gonna close your pupils. So your patients may complain of blurred vision, they can't see at night because their pupils are too small, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 36–38; transcript 10/7"},

{id:"L11-010", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"pbz", skill:"tell",
 concept:"prazosin-vs-phenoxybenzamine", tags:[], source:"both",
 stem:"Which statement correctly tells prazosin and phenoxybenzamine apart?",
 options:[
  {t:"Only phenoxybenzamine is irreversible", correct:true, why:"Phenoxybenzamine binds covalently; prazosin is reversible."},
  {t:"Only prazosin blocks α2", correct:false, why:"Prazosin is selective for α1; phenoxybenzamine blocks α1 and α2."},
  {t:"Only prazosin causes reflex tachycardia", correct:false, why:"Both lower blood pressure through α1 block and both cause reflex tachycardia."},
  {t:"Only phenoxybenzamine dilates arteries", correct:false, why:"Both block α1 in arteries and veins and cause vasodilation."}],
 teach:"Prazosin: reversible, selective α1 antagonist. Phenoxybenzamine: irreversible, non-selective α1 and α2 antagonist. Both cause α1-block effects (vasodilation, orthostatic hypotension, reflex tachycardia, miosis); phenoxybenzamine adds the α2-block effect in the gut.",
 quote:"So similar to prazosin, the difference is irreversible and also blocks the alpha-2s, OK?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 27, 34–38; transcript 10/7"},

{id:"L11-011", lecture:"L11", prof:"Gottlieb", tier:"new", level:3, ladder:"prazosin", ladderName:"Prazosin, norepinephrine and phenoxybenzamine", topic:"L11", sub:"pbz", skill:"apply",
 concept:"prazosin-reversible-competition", tags:["exam-cue"], source:"both",
 stem:"As prazosin lowers blood pressure, the body releases more norepinephrine. Why does this weaken prazosin's effect but not phenoxybenzamine's?",
 options:[
  {t:"Prazosin is reversible", correct:true, why:"Norepinephrine competes with prazosin for α1; it cannot compete with phenoxybenzamine's covalent bond."},
  {t:"Prazosin also blocks α2", correct:false, why:"Prazosin is α1 selective; it is phenoxybenzamine that blocks α2."},
  {t:"Prazosin activates β2", correct:false, why:"Prazosin is an α1 antagonist; it has no β2 action."},
  {t:"Phenoxybenzamine stops norepinephrine release", correct:false, why:"Blocking presynaptic α2 increases, not stops, norepinephrine release."}],
 teach:"With a reversible antagonist such as prazosin, extra norepinephrine (released by the baroreceptor reflex) binds, comes off and competes for α1, so the drop in pressure is partly undone. Phenoxybenzamine is covalently bound, so more norepinephrine makes no difference; it gives the greater drop in blood pressure (see his poll, PE2-039).",
 quote:"Because even though you are increasing the levels of norepinephrine being released, it doesn't matter. It's covalently bound. It's irreversible. You can't outcompete, right? ... Noreprazosin is reversible, so you can actually produce more norepinephrine as you sense that blood pressure going down, and that may decrease its effects because now you have competition",
 note:"Variant of his 10/7 poll “Which drug produces the greatest drop in blood pressure?” (PE2-039). On 10/7 he said he will use one of that day's questions on the exam “in a different shape or form, but very similar” (see notes/L11.md, Exam cues).",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 27, 34–35; transcript 10/7"},

/* ---------------- β receptors (slides 39–45) ---------------- */
{id:"L11-012", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"beta", skill:"recall", multi:true,
 concept:"beta-sites-effects", tags:[], source:"both",
 stem:"Which pairings of β receptor site and effect are CORRECT? Select all that apply.",
 options:[
  {t:"β2 in the lungs: bronchodilation", correct:true, why:"β2 activation relaxes bronchial smooth muscle and opens the airways."},
  {t:"β3 in the bladder: relaxation", correct:true, why:"β3 relaxes the bladder smooth muscle so it holds more urine."},
  {t:"β1 in the kidney: renin production", correct:true, why:"Renal β1 increases renin, the rate-limiting enzyme for angiotensin II."},
  {t:"β1 in the heart: lower cardiac output", correct:false, why:"β1 activation increases cardiac output (rate and force)."},
  {t:"β2 in blood vessels: constriction", correct:false, why:"β2 on vascular smooth muscle causes dilation."}],
 teach:"β receptor sites: brain (excitation; tremor), heart β1 (cardiac output), kidney β1 (renin), lungs β2 (bronchodilation), vascular smooth muscle β2 (vasodilation), eye β2 (more aqueous humor), bladder β3 (relaxation). All are linked to Gs; what differs is location and function.",
 quote:"So the easiest part for you is that it doesn't matter if it's a beta 1, a beta 2, or beta 3, they are all linked to GS, which means they're going to stimulate. The difference over here is the location and the function they're going to have, OK.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 39–44; transcript 10/7"},

{id:"L11-013", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"beta", skill:"recall",
 concept:"beta1-gs-heart-kidney", tags:[], source:"both",
 stem:"β1 receptors are located mainly in the heart and kidney. What does their activation do?",
 options:[
  {t:"Raises cardiac output and renin", correct:true, why:"Gs → adenylyl cyclase → more cAMP and cytosolic calcium: higher cardiac output, more renin."},
  {t:"Lowers cardiac output and renin", correct:false, why:"That is what a β blocker does."},
  {t:"Raises cardiac output, lowers renin", correct:false, why:"Renal β1 increases renin."},
  {t:"Relaxes the heart muscle", correct:false, why:"In cardiac myocytes β1 increases contraction; relaxation is the β2 effect on smooth muscle."}],
 teach:"β1 is linked to Gs: activation of adenylate cyclase, more cyclic AMP (cAMP) and more cytosolic calcium. In the heart that raises cardiac output; in the kidney it raises renin and so angiotensin II. The design is to bring blood pressure up. Selective agonist: dobutamine; selective antagonist: metoprolol.",
 quote:"So the GS over here for the beta 1s in the heart and the kidney is going to increase camp, which is going to increase the cardiac output and increase the production of renin. This is designed to bring up your blood pressure.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 40; transcript 10/7"},

{id:"L11-014", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"beta", skill:"recall",
 concept:"dobutamine-moa", tags:[], source:"both",
 stem:"Which describes dobutamine?",
 options:[
  {t:"Selective β1 agonist", correct:true, why:"Dobutamine activates β1 in the heart: stronger contraction (+ inotropic) and higher heart rate."},
  {t:"Selective β1 antagonist", correct:false, why:"That is metoprolol."},
  {t:"Non-selective β1 and β2 agonist", correct:false, why:"That is isoproterenol."},
  {t:"Selective β3 agonist", correct:false, why:"That is mirabegron."}],
 teach:"Dobutamine is the selective β1 agonist: positive inotropic action and increased heart rate. It is an intravenous drug for short-term treatment of cardiac decompensation (intensive care or emergency room), when the patient's cardiovascular system is collapsing.",
 quote:"So these two drugs are, one is a selective beta 1 agonist in green, the top one, the buttamine, metoprolol is a selective beta 1 antagonist. So, if I give dobutamine to my patient, that drug is going to get to the beta ones in the heart and it's going to increase the contraction of the cardiac myocyte.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 40–41; transcript 10/7"},

{id:"L11-015", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"beta", skill:"apply",
 concept:"dobutamine-tolerance", tags:["in-class"], source:"both",
 stem:"Patients kept on dobutamine need higher and higher doses. Which mechanism explains the tolerance?",
 options:[
  {t:"β1 receptors are down-regulated", correct:true, why:"The body answers constant activation by an agonist by making fewer receptors."},
  {t:"β1 receptors are up-regulated", correct:false, why:"Up-regulation follows chronic block by an antagonist (β blockers, clonidine)."},
  {t:"Dobutamine becomes an antagonist", correct:false, why:"The drug does not change; the receptor number does."},
  {t:"The parasympathetic system shuts off", correct:false, why:"Tolerance is a receptor change, not loss of the parasympathetic system."}],
 teach:"Tolerance limits dobutamine's long-term use. Over-activation by an agonist leads to down-regulation of the receptors, so the dose has to keep rising; higher doses push heart rate higher, toward arrhythmias. Patients kept on it long term were more likely to die, so it is a short-term drug.",
 quote:"How do you think they start to build tolerance for the long term? What is one of the ways the body deals with overactivation by an agonist? Is going down regulate the receptors, right? So you have to keep giving higher and higher doses to maintain that.",
 note:"He asked the class how tolerance develops and answered it himself.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 41; transcript 10/7"},

{id:"L11-016", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"beta", skill:"apply",
 concept:"dobutamine-arrhythmia", tags:[], source:"both",
 stem:"What is the major adverse reaction of dobutamine as the dose is pushed higher?",
 options:[
  {t:"Tachycardia and arrhythmias", correct:true, why:"The faster the heart beats, the more likely it goes out of rhythm."},
  {t:"Bradycardia and heart block", correct:false, why:"A β1 agonist speeds the heart; it does not slow it."},
  {t:"Bronchoconstriction", correct:false, why:"Dobutamine acts on β1 in the heart; bronchoconstriction comes from β2 block or M3."},
  {t:"Orthostatic hypotension", correct:false, why:"That is the α1 antagonists."}],
 teach:"Slide 41: major adverse reactions are tachycardia and arrhythmias. The heart's rhythm is set by the sinoatrial (SA) node, the atria, the atrioventricular (AV) node and then the ventricles; when it is driven too fast it goes out of sync.",
 quote:"The faster your heart is beating, the more likely it's going to go to out of the rails. They're going to arrhythmias, out of sync because the heart has a rhythm, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 41; transcript 10/7"},

{id:"L11-017", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"beta", skill:"recall", multi:true,
 concept:"beta2-effects", tags:[], source:"both",
 stem:"Which effects follow β2 receptor activation? Select all that apply.",
 options:[
  {t:"Bronchodilation", correct:true, why:"β2 relaxes bronchial smooth muscle."},
  {t:"Vasodilation", correct:true, why:"β2 relaxes vascular smooth muscle."},
  {t:"Stimulation in the brain", correct:true, why:"In the central nervous system β2 activation is excitatory."},
  {t:"More aqueous humor in the eye", correct:true, why:"In the eye β2 makes more aqueous humor."},
  {t:"Bronchoconstriction", correct:false, why:"Bronchoconstriction is M3 (Gq); β2 does the opposite."},
  {t:"Vasoconstriction", correct:false, why:"Vasoconstriction is α1 (Gq)."}],
 teach:"β2 is linked to Gs and raises cyclic AMP. On smooth muscle (bronchi, blood vessels, bladder) the result is relaxation, an exception to the usual Gs “stimulate” rule; in the brain it stimulates; in the eye it increases aqueous humor production. Albuterol is the prototype β2 agonist.",
 quote:"All right, so in the vascular and bronchius moo muscle, beta 2s are gonna cause dilation. In the CNS it's gonna stimulate. In the eye, it's gonna make more aqueous humor, so more liquid production inside of the eye.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 42–43; transcript 10/7"},

{id:"L11-018", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"beta", skill:"recall",
 concept:"terol-beta2-agonist", tags:["exam-cue"], source:"both",
 stem:"A drug's name ends in -terol, such as formoterol. What is its mechanism of action?",
 options:[
  {t:"β2 agonist", correct:true, why:"Any -terol is a β2 agonist, short or long acting."},
  {t:"β2 antagonist", correct:false, why:"β blockers end in -olol."},
  {t:"Muscarinic antagonist", correct:false, why:"The inhaled muscarinic antagonists are -tropium or -clidinium drugs."},
  {t:"β1 agonist", correct:false, why:"The selective β1 agonist is dobutamine."}],
 teach:"Albuterol and levalbuterol are short acting (SABA, 2–6 hours); salmeterol and formoterol are long acting (LABA, 12 hours or more). For this exam he only needs the class: a -terol is a β2 agonist; short versus long acting is for the pulmonary module.",
 quote:"If you know that a terol is a beta2 agonist, that's good for me. It doesn't matter if it's short acting or long acting. That's not the point over here. The point over here is for you to identify. Which of these is a beta2 agonist? OK.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 43; transcript 10/7"},

{id:"L11-019", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"beta", skill:"apply", multi:true,
 concept:"albuterol-systemic-effects", tags:["in-class"], source:"both",
 stem:"A child swallows much of an albuterol dose instead of inhaling it. Which effects are likely? Select all that apply.",
 options:[
  {t:"Higher heart rate", correct:true, why:"Outside the lungs the drug increases sympathetic effects on the heart."},
  {t:"Higher blood pressure", correct:true, why:"He listed increased blood pressure among the effects outside the lungs."},
  {t:"Agitation", correct:true, why:"β2 in the brain is excitatory."},
  {t:"Bronchoconstriction", correct:false, why:"A β2 agonist dilates the bronchi."},
  {t:"Sedation", correct:false, why:"β2 activation in the brain excites rather than sedates."}],
 teach:"Inhaled properly, albuterol stays in the lungs and causes bronchodilation. Swallowed, or given by nebulizer, it reaches the rest of the body: higher heart rate and blood pressure and agitation, a concern in the elderly and the young. This is why inhaler technique (and a spacer) matters.",
 quote:"So what kind of side effects would I expect with a beta blocker? Oh, with a beta2 agonist? Sorry. It may increase heart rate, it may increase blood pressure, it may increase agitation, right, especially the elderly and the, the young, those are the ones that we're always worried about.",
 note:"From his review of albuterol on the summary (“money”) slide, chosen by the class.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 42, 60; transcript 10/7"},

{id:"L11-020", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"beta", skill:"recall",
 concept:"mirabegron-beta3", tags:[], source:"both",
 stem:"Which describes mirabegron?",
 options:[
  {t:"β3 agonist that relaxes the bladder", correct:true, why:"β3 activation relaxes the detrusor muscle and increases bladder capacity."},
  {t:"Selective M3 antagonist that relaxes the bladder", correct:false, why:"That is trospium, solifenacin and oxybutynin."},
  {t:"β3 antagonist that contracts the bladder", correct:false, why:"Mirabegron activates β3; it does not block it."},
  {t:"β2 agonist that opens the airways", correct:false, why:"That is albuterol and the other -terols."}],
 teach:"Mirabegron is the one β3 drug: a selective β3 agonist. Like β2, β3 raises cyclic AMP and relaxes smooth muscle; in the bladder this relaxes the detrusor and increases capacity, preventing voiding — relief for overactive bladder and urinary incontinence.",
 quote:"The beta 3s, there's only one drug over here, uh, mitaegron, and this is a beta 3 selective agonist.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 44; transcript 10/7"},

{id:"L11-021", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"beta", skill:"tell",
 concept:"mirabegron-vs-antimuscarinic", tags:[], source:"both",
 stem:"Mirabegron and trospium both relax the bladder. Which statement about mirabegron is CORRECT?",
 options:[
  {t:"It lacks the anti-DUMBBELSS effects", correct:true, why:"It stays with the bladder β3: no constipation, blurred vision, or heart and lung effects."},
  {t:"It blocks bladder M3 like trospium", correct:false, why:"Mirabegron activates β3; trospium blocks M3."},
  {t:"It causes more dry mouth than trospium", correct:false, why:"Dry mouth is an antimuscarinic effect; mirabegron does not have it."},
  {t:"It is cheaper than trospium", correct:false, why:"It is newer, still on patent, and costs more."}],
 teach:"Two classes relax the bladder and decrease urination: muscarinic M3 antagonists (trospium, solifenacin, oxybutynin) and the β3 agonist mirabegron. Mirabegron is more selective to the bladder and avoids the anti-DUMBBELSS effects, which is why it is becoming first line; it is more expensive.",
 quote:"And even better is not going to produce the anti-dumbbell effects that the anti-muscarinics produce. So you don't have to worry about the constipation. You don't have to worry about the blurring in the eye, in the vision, the effects in the heart, in the lungs, and all the other stuff.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 44; transcript 10/7"},

{id:"L11-023", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"beta", skill:"apply", multi:true,
 concept:"bladder-relaxer-select-all", tags:["in-class","variant","exam-cue"], source:"both",
 stem:"Which of the following drugs relax the bladder smooth muscle, thus decreasing urination? Select all that apply.",
 options:[
  {t:"Mirabegron", correct:true, why:"β3 agonist: relaxes the bladder."},
  {t:"Trospium", correct:true, why:"Muscarinic M3 antagonist: blocks bladder M3 and prevents urination."},
  {t:"Carbachol", correct:false, why:"Muscarinic agonist: contracts the bladder."},
  {t:"Neostigmine", correct:false, why:"Cholinesterase inhibitor: more acetylcholine, more urination."},
  {t:"Isoproterenol", correct:false, why:"β1 and β2 agonist acting on the heart and lungs; it has no β3 action."}],
 teach:"The select-all version he described: with trospium added, both the β3 agonist and the M3 antagonist are correct. Either activating β3 or blocking M3 relaxes the detrusor and decreases urination.",
 quote:"What if I had to put trosium in there too? Would that be true? Now we have a selectol, right? ... So, one of the best of one or a select all.",
 note:"The select-all form he described aloud right after his 10/7 bladder poll (PE2-041, which has one key, mirabegron): “What if I had to put trosium in there too? Would that be true? Now we have a selectol, right?” Kept as a variant because it asks something different: with trospium among the options, both the β3 agonist and the M3 antagonist are correct. One of the 10/7 questions will be reused “in a different shape or form”.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 44; transcript 10/7"},

{id:"L11-024", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"beta", skill:"apply",
 concept:"isoproterenol-replaced", tags:["in-class"], source:"both",
 stem:"Isoproterenol produces good bronchodilation but is no longer used for asthma. Why?",
 options:[
  {t:"It also activates β1 in the heart", correct:true, why:"Equal β1 and β2 affinity: palpitations, tachycardia and arrhythmias."},
  {t:"It blocks the β2 receptors of bronchial muscle", correct:false, why:"Isoproterenol is an agonist at β2; that is why it dilates the bronchi."},
  {t:"It activates α1 in the airways", correct:false, why:"Isoproterenol acts at β1 and β2, not α1."},
  {t:"It is an irreversible antagonist", correct:false, why:"It is a non-selective β agonist."}],
 teach:"Isoproterenol is a non-selective β agonist with equal affinity for β1 and β2 (“iso” = equal). β2 gives bronchodilation and lower vascular resistance; β1 raises heart rate and contractility, with palpitations, tachycardia and cardiac ischemia. Albuterol replaced it for asthma.",
 quote:"Why do we stop using for asthma? Yeah, it produced a beautiful bronchodilation, but also the palpitation and tachycardia and arrhythmias, and that's gonna be bad for our patients, right? So, albuterol came after isoproterenol and has replaced it completely, OK?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 45; transcript 10/7"},

{id:"L11-025", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"beta", skill:"tell",
 concept:"beta-agonist-selectivity", tags:[], source:"both",
 stem:"Which pairing of β agonist and receptor is CORRECT?",
 options:[
  {t:"Isoproterenol: β1 and β2", correct:true, why:"Non-selective: equal affinity for β1 and β2."},
  {t:"Dobutamine: β2", correct:false, why:"Dobutamine is the selective β1 agonist."},
  {t:"Albuterol: β1", correct:false, why:"Albuterol is the prototype β2 agonist."},
  {t:"Mirabegron: β2 and β3 equally", correct:false, why:"Mirabegron is the selective β3 agonist."},
  {t:"Salmeterol: β3", correct:false, why:"Salmeterol is a long-acting β2 agonist."}],
 teach:"Selective β agonists: dobutamine (β1), albuterol and the other -terols (β2), mirabegron (β3). Non-selective: isoproterenol (β1 and β2). Epinephrine and norepinephrine act at α and β receptors.",
 quote:"So this is a non-selective beta 1, beta2 agonist. So iso equal, right, equal affinity and efficacy for the beta 1s and the beta 2s.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 9, 40–45; transcript 10/7"},

/* ---------------- Epinephrine (slides 46–52) ---------------- */
{id:"L11-026", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"epi", skill:"recall",
 concept:"epinephrine-affinity-rank", tags:[], source:"both",
 stem:"In which order does epinephrine bind adrenergic receptors as its dose rises?",
 options:[
  {t:"β1 and β2, then α1, then α2", correct:true, why:"Highest affinity for β1 and β2 at low doses; α1 and finally α2 join as the dose rises."},
  {t:"α1, then α2, then β1 and β2", correct:false, why:"The α receptors are reached only at higher doses."},
  {t:"α2, then β2, then α1", correct:false, why:"α2 is the last to be activated."},
  {t:"All receptors equally at every dose", correct:false, why:"Epinephrine's response depends on dose because its affinities differ."}],
 teach:"Epinephrine has different affinities for the adrenergic receptors. At low doses it binds β1 and β2 best; as the dose rises it also activates α1 and eventually α2. The rank is β1, β2, α1, then α2. This difference explains epinephrine reversal.",
 quote:"At low doses, uh, epinephrine has the highest affinity for the beta 1 and the beta 2 receptor. ... So, the, the, the rank of affinity is gonna be beta one beta choose, alpha one, and then alpha 2. OK?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 47; transcript 10/7"},

{id:"L11-027", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, ladder:"epinephrine", ladderName:"Epinephrine: α1 and β2, its blockers, and the EpiPen overdose", topic:"L11", sub:"epi", skill:"apply",
 concept:"epinephrine-dose-vessels", tags:[], source:"both",
 stem:"What does epinephrine do to arterial tone at a low dose and at a high dose?",
 options:[
  {t:"Low: dilation; high: constriction", correct:true, why:"Low dose: β2 (dilation). High dose: α1 joins and overrides β2 (constriction)."},
  {t:"Low: constriction; high: dilation", correct:false, why:"Reversed: α1 is reached only at high doses."},
  {t:"Constriction at both doses", correct:false, why:"At low dose only β2 is activated in the vessel, which dilates."},
  {t:"Dilation at both doses", correct:false, why:"At high dose α1 overrides β2 and the vessel constricts."}],
 teach:"The two major receptors on arterial and venous smooth muscle are α1 (constriction) and β2 (dilation). At low doses epinephrine activates β2 and the vessels dilate; at high doses it activates everyone, α1 overrides β2 and the vessels constrict, so blood pressure rises. The response is the net of α1 minus β2.",
 quote:"which is called epinephrine reversal, which means that at low doses, epinephrine is causing vasodilation, but a higher dose is going to cause vasoconstriction. So it has this reversal of the effect, and that's due to the affinity of the drug for the different types of adrenergic receptors.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 47–48; transcript 10/7"},

{id:"L11-028", lecture:"L11", prof:"Gottlieb", tier:"new", level:2, ladder:"epinephrine", ladderName:"Epinephrine: α1 and β2, its blockers, and the EpiPen overdose", topic:"L11", sub:"epi", skill:"figure",
 concept:"epinephrine-reversal-prazosin", tags:["in-class"], source:"both",
 stem:"A blood pressure tracing: a high dose of epinephrine raises blood pressure. After prazosin is given, the same epinephrine dose lowers blood pressure. Which explains the change?",
 options:[
  {t:"α1 is blocked, so β2 acts alone", correct:true, why:"With α1 occupied by prazosin, epinephrine's β2 dilation is unopposed: epinephrine reversal."},
  {t:"β2 is blocked, so α1 acts alone", correct:false, why:"Blocking β2 would make the rise in pressure larger, not reverse it."},
  {t:"Prazosin activates β2 directly", correct:false, why:"Prazosin is an α1 antagonist; it does not act on β2."},
  {t:"Prazosin blocks epinephrine release", correct:false, why:"Epinephrine is injected; prazosin acts at the α1 receptor."}],
 teach:"High-dose epinephrine gives a net pressor effect: α1 constriction minus β2 dilation, with α1 winning. Pretreatment with an α1 antagonist (prazosin) removes the α1 part; the β2 part is left unopposed and the same dose now dilates and lowers pressure. An antagonist used this way teases out which receptor carries each part of the response.",
 quote:"So if I give prazosin, now prazosin is gonna block the alpha ones who is unopposed. The beta 2. So what am I getting now? A vasodilation, right? So by utilizing an antagonist, I can tease out the different receptors involved in the different processes of the blood blood pressure control.",
 note:"He asked the class “what would you predict to happen if I put an alpha one antagonist first and then gave epinephrine?” and walked through it on the epinephrine reversal tracings (slides 48–51), whose pictures could not be seen; the tracing is described from his words.",
 reading:[{"src":"Katzung 16e, Ch. 10","sec":"Pharmacologic Effects — Cardiovascular Effects","t":"Activation of both α and β receptors in the vasculature can produce opposite responses. Blocking α adrenoceptors unmasks the effect of epinephrine on β receptors, so a pressor response to epinephrine becomes a fall in blood pressure; this is called epinephrine reversal."}],
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 48–51; transcript 10/7"},

{id:"L11-029", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"epi", skill:"figure",
 concept:"phenylephrine-vs-epinephrine-pressor", tags:["in-class"], source:"both",
 stem:"Blood pressure tracings compare a high dose of epinephrine with phenylephrine. Phenylephrine gives the larger rise. Why?",
 options:[
  {t:"No β2 dilation opposes it", correct:true, why:"Phenylephrine activates only α1; epinephrine's rise is reduced by its own β2 dilation."},
  {t:"It also activates β1", correct:false, why:"Phenylephrine is selective for α1."},
  {t:"It blocks the β2 receptors", correct:false, why:"Phenylephrine is an agonist at α1; it does not block β2."},
  {t:"It has a higher affinity for α2", correct:false, why:"Phenylephrine is the selective α1 agonist."}],
 teach:"Epinephrine's pressor response is α1 minus β2. Phenylephrine is a selective α1 agonist and leaves β2 alone, so the whole response is α1-mediated and the constriction is greater than with epinephrine.",
 quote:"So I can predict that the vasoconstriction produced by epinephrine or by phenophrine is gonna be greater than. Because it's only bind me to the alpha ones. I have no beta 2. So here in the bottom when I give feennuafrin, all of this is going to be alpha 1 mediated.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 49–51; transcript 10/7"},

{id:"L11-030", lecture:"L11", prof:"Gottlieb", tier:"new", level:2, topic:"L11", sub:"epi", skill:"figure",
 concept:"phenylephrine-after-prazosin", tags:[], source:"both",
 stem:"Phenylephrine is given after prazosin, and the blood pressure response is abolished with no fall in pressure. What does this show?",
 options:[
  {t:"Phenylephrine has no β2 action", correct:true, why:"With α1 blocked nothing is left; no reversal means no β2 involvement."},
  {t:"Prazosin also blocks β2", correct:false, why:"Prazosin is selective for α1; epinephrine still dilates after prazosin."},
  {t:"Phenylephrine is an α1 antagonist", correct:false, why:"Phenylephrine is an α1 agonist."},
  {t:"Prazosin is irreversible", correct:false, why:"Prazosin is reversible; a high enough phenylephrine dose could outcompete it."}],
 teach:"After prazosin, epinephrine reverses (β2 dilation appears) but phenylephrine simply loses its effect. At these doses prazosin wins the competition at α1, and because phenylephrine has no β2 action there is no reversal. A larger dose of phenylephrine could outcompete the reversible antagonist.",
 quote:"And then if I repeat the same experiment and give feuaphrine in the presence of prazosin, which is the antagonist, look what happens. All is blocked. ... The reversal is gone, and that further proves that there's no beta 2 involvement with phenyphrine. It's only activating the alpha ones.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 50–51; transcript 10/7"},

{id:"L11-031", lecture:"L11", prof:"Gottlieb", tier:"new", level:3, topic:"L11", sub:"epi", skill:"apply",
 concept:"epinephrine-wean", tags:[], source:"both",
 stem:"Why must a hospitalized patient on an epinephrine infusion be weaned off rather than stopped abruptly?",
 options:[
  {t:"Its receptors are down-regulated", correct:true, why:"With fewer receptors and no epinephrine, the cardiovascular system collapses."},
  {t:"Its receptors are up-regulated", correct:false, why:"Up-regulation follows an antagonist (β blockers, clonidine), giving a hypertensive crisis."},
  {t:"It is irreversibly bound to the receptor", correct:false, why:"Epinephrine is an agonist, not a covalent antagonist."},
  {t:"It causes a cheese effect", correct:false, why:"The cheese effect is the MAO inhibitor reaction to dietary tyramine."}],
 teach:"An agonist given continuously leads to down-regulation of its receptors. If epinephrine is then shut off, the patient has no epinephrine and fewer receptors, and the cardiovascular system collapses. Slide 52: “Pts treated with Epi have to be weaned off.”",
 quote:"You got to wean them off because you're giving an agonist and now your patient is down regulating the receptors. If you shut off that epinephrine, now you have no epi, no receptors, the cardiovascular is going to collapse, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 52; transcript 10/7"},

{id:"L11-032", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, ladder:"epinephrine", ladderName:"Epinephrine: α1 and β2, its blockers, and the EpiPen overdose", topic:"L11", sub:"epi", skill:"recall",
 concept:"epinephrine-overdose-receptors", tags:[], source:"both",
 stem:"In an epinephrine overdose, which receptors predominate in the response?",
 options:[
  {t:"α1 and β1", correct:true, why:"Heart rate and blood pressure both go as high as possible."},
  {t:"β2 and α2", correct:false, why:"These are not the ones that predominate in the overdose."},
  {t:"β2 only", correct:false, why:"β2 alone is the low-dose vasodilation."},
  {t:"α2 and β3", correct:false, why:"Neither drives the overdose picture."}],
 teach:"Slide 52: “OD of Epi α1 & β1 predominates.” α1 constricts the resistance arteries (afterload and blood pressure rise) and β1 drives the heart rate up. The question then is which to block first.",
 quote:"Now, in the case of an overdose of a epinephrine, your alpha ones and your beta ones are gonna be predominant on that process. They're gonna have the highest effects, OK?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 52; transcript 10/7"},

/* ---------------- Norepinephrine (slide 53) ---------------- */
{id:"L11-034", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"ne", skill:"recall",
 concept:"norepinephrine-affinity", tags:[], source:"both",
 stem:"For which receptors does norepinephrine have its highest affinity?",
 options:[
  {t:"α1 and β1", correct:true, why:"α1: vasoconstriction (higher total peripheral resistance); β1: higher heart rate and contractility."},
  {t:"β1 and β2", correct:false, why:"That is epinephrine at low doses."},
  {t:"β2 and α2", correct:false, why:"Norepinephrine can bind these, but with lower affinity."},
  {t:"β3 only", correct:false, why:"The β3 agonist is mirabegron."}],
 teach:"Norepinephrine (Levophed as a drug) has a higher affinity for β1 and α1 than for β2 or α2, although it can bind and activate those too. α1 constriction raises total peripheral resistance; β1 raises heart rate and myocardial contractility.",
 quote:"All right, so norepinephrine is different than Api because norepinephrine appears to have a higher affinity for the beta ones and the alpha ones, OK, than it does for the beta 2s or the alpha 2s. Although it can bind and activate those receptors.",
 note:"Slide 53 lists α1 and β1; slide 84 (lab section) lists NE at α1, α2 and β1, as does the autonomic slide 13 (as the neurotransmitter). The drug list gives α1 and β1. He framed it as highest affinity for α1 and β1, with β2 and α2 possible.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 53; transcript 10/7"},

{id:"L11-035", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"ne", skill:"apply", multi:true,
 concept:"norepinephrine-problems", tags:[], source:"both",
 stem:"Why is a norepinephrine infusion used only short term in a failing cardiovascular system? Select all that apply.",
 options:[
  {t:"It raises the heart's oxygen demand", correct:true, why:"It works the heart harder (more cardiac output and afterload)."},
  {t:"It is directly toxic to the heart", correct:true, why:"Kept on long term it becomes toxic and the heart starts to fail."},
  {t:"It decreases blood flow to other organs", correct:true, why:"α1 constriction diverts flow (slide 53, problems)."},
  {t:"It causes bronchoconstriction", correct:false, why:"Bronchoconstriction is not among its listed problems."},
  {t:"It causes severe bradycardia", correct:false, why:"β1 activation raises heart rate."}],
 teach:"Slide 53 problems: decreased blood flow to other organs, increased oxygen demand of the heart, direct toxicity to tissue, pulmonary edema, stroke and arrhythmias. Like dobutamine, norepinephrine (Levophed) is kept for life-threatening situations; the harder the heart is worked, the less it lasts, which is why β blockers save lives.",
 quote:"But the problem with norepinephrine, levofed, same thing with butamine, is that you can't keep your patients on long term because it becomes toxic. To the heart and the heart starts to fail.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 53; transcript 10/7"},

{id:"L11-036", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"ne", skill:"tell",
 concept:"epinephrine-vs-norepinephrine", tags:[], source:"both",
 stem:"Which statement correctly tells epinephrine and norepinephrine apart?",
 options:[
  {t:"Low-dose epinephrine favors β2", correct:true, why:"Epinephrine binds β1 and β2 best at low doses; norepinephrine favors α1 and β1."},
  {t:"Norepinephrine favors β2", correct:false, why:"Norepinephrine has its highest affinity for α1 and β1."},
  {t:"Epinephrine cannot activate α1", correct:false, why:"At high doses epinephrine activates α1 (vasoconstriction)."},
  {t:"Norepinephrine cannot activate β1", correct:false, why:"β1 is one of norepinephrine's two main receptors."}],
 teach:"Epinephrine: β1 and β2 at low doses (vasodilation in vessels), α1 and then α2 at high doses (vasoconstriction). Norepinephrine: highest affinity for α1 and β1 (more total peripheral resistance, heart rate and contractility). That is why low-dose epinephrine can dilate vessels while norepinephrine constricts them.",
 quote:"Now, the key thing over here is going to be their affinities, and the epinephrine, for example, has different affinities for the different receptors.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 47, 53; transcript 10/7"},

/* ---------------- β blockers (slides 54–59) ---------------- */
{id:"L11-037", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"bb", skill:"tell",
 concept:"beta-blocker-selectivity", tags:["exam-cue"], source:"both",
 stem:"Which pairing of β blocker and receptors blocked is CORRECT?",
 options:[
  {t:"Atenolol: β1 only", correct:true, why:"Atenolol is one of the β1-selective blockers (metoprolol, atenolol, nebivolol: “MAN”)."},
  {t:"Propranolol: β1 only", correct:false, why:"Propranolol blocks β1 and β2."},
  {t:"Carvedilol: β1 only", correct:false, why:"Carvedilol blocks β1, β2 and α1."},
  {t:"Metoprolol: β1, β2 and α1", correct:false, why:"Metoprolol is β1 selective."},
  {t:"Labetalol: β1 and β2 only", correct:false, why:"Labetalol also blocks α1."}],
 teach:"The β blockers he wants known: β1 selective — metoprolol, atenolol, nebivolol (“MAN”); β1 and β2 — propranolol (the prototype) and pindolol (partial agonist); β1, β2 and α1 — carvedilol and labetalol. Generations and brand names are not tested.",
 quote:"So, those are gonna be the beta blockers that you need to know from me on the exam, and which one is selective versus which one is not selective.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 54; transcript 10/7"},

{id:"L11-038", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"bb", skill:"recall", multi:true,
 concept:"beta1-selective-man", tags:["exam-cue"], source:"both",
 stem:"Which β blockers are β1 selective? Select all that apply.",
 options:[
  {t:"Metoprolol", correct:true, why:"The M of “MAN”."},
  {t:"Atenolol", correct:true, why:"The A of “MAN”."},
  {t:"Nebivolol", correct:true, why:"The N of “MAN”, the newest β blocker."},
  {t:"Propranolol", correct:false, why:"Blocks β1 and β2 (the prototype)."},
  {t:"Carvedilol", correct:false, why:"Blocks β1, β2 and α1."},
  {t:"Pindolol", correct:false, why:"Blocks β1 and β2 as a partial agonist."}],
 teach:"Every β blocker ends in -olol and every β blocker blocks β1. The β1-selective ones are metoprolol, atenolol and nebivolol (“MAN”); the rest on his list are non-selective (propranolol, pindolol: β1 and β2; carvedilol, labetalol: β1, β2 and α1).",
 quote:"How about if we spell man. Man, right? So, we have metoprolol, atenolol, and nabivolol. Those are gonna be your beta one selectives, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 54; transcript 10/7"},

{id:"L11-039", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"bb", skill:"recall",
 concept:"propranolol-prototype", tags:[], source:"both",
 stem:"Which drug is the prototype β blocker against which newer β blockers are measured?",
 options:[
  {t:"Propranolol", correct:true, why:"One of the first β blockers; non-selective (β1 and β2)."},
  {t:"Metoprolol", correct:false, why:"Metoprolol is a β1-selective blocker from a later group."},
  {t:"Nebivolol", correct:false, why:"Nebivolol is the newest β blocker on his list."},
  {t:"Labetalol", correct:false, why:"Labetalol is a mixed β1, β2 and α1 blocker."},
  {t:"Isoproterenol", correct:false, why:"Isoproterenol is a non-selective β agonist, not a blocker."}],
 teach:"Propranolol was one of the first β blockers on the market and is the standard: any new β blocker has to be equal to or better than it. It blocks β1 and β2 and is very lipophilic, so it reaches the brain.",
 quote:"but I would like for you to know propranolol because that's the prototypical drug that was one of the first beta blockers that we had in the market, and that drug is now the standard to which any other beta blocker that is discovered has to be measured against.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 54; transcript 10/7"},

{id:"L11-040", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, ladder:"beta-blocker", ladderName:"β blockers: the heart, insulin, and stopping abruptly", topic:"L11", sub:"bb", skill:"apply", multi:true,
 concept:"beta-blocker-heart-effects", tags:[], source:"both",
 stem:"Which cardiac effects do all β blockers share? Select all that apply.",
 options:[
  {t:"Lower contractile force", correct:true, why:"Negative inotropic effect from β1 block."},
  {t:"Lower heart rate", correct:true, why:"Negative chronotropic effect; the parasympathetic takes over (bradycardia)."},
  {t:"Slower relaxation", correct:true, why:"The rate of relaxation falls too."},
  {t:"Higher cardiac output", correct:false, why:"The primary effect is to decrease cardiac output."},
  {t:"Tachycardia", correct:false, why:"Blocking β1 lets the parasympathetic predominate: bradycardia."}],
 teach:"All β blockers block β1, so all of them act on the heart: less force (inotropic), lower rate (chronotropic), slower relaxation, and so lower cardiac output. With the sympathetic input to β1 blocked, the resting parasympathetic tone takes over and heart rate falls (bradycardia).",
 quote:"So if I block the ability of my norepinephrine to bind and activate the beta ones, because all beta blockers blocks beta ones, who's gonna take over? Parasympathetic. So you're gonna get what? Bradycardia, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 56–58; transcript 10/7"},

{id:"L11-041", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"bb", skill:"recall",
 concept:"beta-blocker-primary-effect", tags:[], source:"both",
 stem:"What is the primary effect of β blockers on the circulation?",
 options:[
  {t:"Decreased cardiac output", correct:true, why:"The designed effect; renin and central effects are the bonus."},
  {t:"Decreased renin secretion", correct:false, why:"A real effect, but he calls it a bonus, not the primary one."},
  {t:"Arterial vasodilation through α1", correct:false, why:"Only the mixed blockers (carvedilol, labetalol) block α1."},
  {t:"Increased parasympathetic release", correct:false, why:"The parasympathetic takes over because β1 is blocked; release is not increased."}],
 teach:"Slides 56–57: β blockers reduce myocardial contractility, heart rate and cardiac output; block β1 in the juxtaglomerular complex (less renin and angiotensin II); and reduce central sympathetic output. He ranks them: the decrease in cardiac output is primary; the rest is “the cherry on top”, building up over weeks to years.",
 quote:"So the way we're going to do this over here is the primary effect of our beta blockers, it's going to be to decrease the cardiac output. So this is number one. This is our primary effect. All these other guys over here are the cherry on top.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 56–57; transcript 10/7"},

{id:"L11-042", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"bb", skill:"apply",
 concept:"beta-blocker-renin", tags:[], source:"both",
 stem:"Besides slowing the heart, how do β blockers lower angiotensin II?",
 options:[
  {t:"β1 block in juxtaglomerular cells", correct:true, why:"Less renin secretion means less angiotensin II."},
  {t:"β2 block in the arterioles", correct:false, why:"β2 block in vessels does not lower renin."},
  {t:"α1 block in the kidney", correct:false, why:"Only the mixed blockers block α1, and renin is controlled by β1."},
  {t:"Inhibition of angiotensin-converting enzyme", correct:false, why:"That is the ACE inhibitors (the -pril drugs); β blockers act on renin release."}],
 teach:"Renin is made by the juxtaglomerular cells of the kidney under β1 control. Blocking these β1 receptors reduces renin secretion and the production of angiotensin II, a vasoconstrictor. Every β blocker does this because every β blocker blocks β1.",
 quote:"Also, it's going to block the beta 1s in the kidney, in the gestic glomera cells which are involved in the production of renin and production of angiotensin 2.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 56–57; transcript 10/7"},

{id:"L11-043", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"bb", skill:"apply",
 concept:"propranolol-anxiety-cns", tags:[], source:"both",
 stem:"Propranolol taken before a public speech lowers anxiety. Which mechanism explains this?",
 options:[
  {t:"Less central norepinephrine release", correct:true, why:"Central β2 (Gs) is positive feedback on norepinephrine release; blocking it lowers sympathetic output."},
  {t:"Activation of central α2", correct:false, why:"Propranolol does not activate α2; that is clonidine."},
  {t:"Block of muscarinic M1 receptors in the brain", correct:false, why:"Propranolol does not act at muscarinic receptors."},
  {t:"Block of α1 in the brain", correct:false, why:"Propranolol does not block α1."}],
 teach:"Presynaptically, α2 (Gαi) is negative feedback that suppresses norepinephrine release, while β2 (Gs) is positive feedback that increases it. Propranolol is lipophilic and reaches the brain; blocking β2 there shifts the balance toward the negative feedback, lowering sympathetic output and anxiety.",
 quote:"And the beta 2s in the brain are involving the positive feedback. So remember that alpha 2s are G alphai, so they are inhibitory. This is the negative feedback, as beta 2s are G alphaS, so they're going to be positive. ... So by blocking those beta 2 receptors in the CNS, we're going to have less sympathetic output. And thus decrease your anxiety",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 56–57; transcript 10/7"},

{id:"L11-044", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, ladder:"beta-blocker-asthma", ladderName:"β blocker in asthma, with albuterol", topic:"L11", sub:"bb", skill:"apply",
 concept:"asthma-metoprolol", tags:["in-class"], source:"both",
 stem:"A patient with asthma needs a β blocker to slow the heart. Which choice is better, and why?",
 options:[
  {t:"Metoprolol: it spares lung β2", correct:true, why:"β1 selective: acts on the heart and leaves the bronchial β2 alone."},
  {t:"Propranolol: it spares lung β2", correct:false, why:"Propranolol blocks β2 too."},
  {t:"Propranolol: it dilates the bronchi", correct:false, why:"Blocking β2 can only narrow the airways or oppose the inhaler."},
  {t:"Carvedilol: it blocks α1 in the lungs", correct:false, why:"Carvedilol also blocks β2 and is not the choice in asthma."}],
 teach:"Slide 59: be careful in reactive airway disease (asthma) with non-selective β blockers. Blocking lung β2 means more puffs of the β2 agonist are needed to outcompete the blocker, costing money and quality of life. A β1-selective blocker such as metoprolol leaves the lungs alone.",
 quote:"What if your patient has uh a past medical history of asthma? Would that swaye you between propranolol and metoprolol now? So which one? Metoprolol, right? Because why would you mess with their beta 2s in the lungs if you don't have to?",
 reading:[{"src":"Katzung 16e, Ch. 10","sec":"Pharmacologic Effects — Effects on the Respiratory Tract","t":"Blocking β2 receptors in bronchial smooth muscle may increase airway resistance, particularly in patients with asthma. β1-selective antagonists such as metoprolol and atenolol have an advantage over non-selective β antagonists when β2 blockade is undesirable, but none is specific enough to avoid β2 completely, so Katzung advises that they generally be avoided in asthma."}],
 note:"Katzung goes further than the lecture: even β1-selective blockers should generally be avoided in asthma. He framed it as a choice between the two drugs; keyed to him.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 54, 59; transcript 10/7"},

{id:"L11-045", lecture:"L11", prof:"Gottlieb", tier:"new", level:2, ladder:"beta-blocker", ladderName:"β blockers: the heart, insulin, and stopping abruptly", topic:"L11", sub:"bb", skill:"apply",
 concept:"beta-blocker-hypoglycemia", tags:[], source:"both",
 stem:"An insulin-dependent diabetic on propranolol becomes hypoglycemic. Which warning sign is still present?",
 options:[
  {t:"Sweating", correct:true, why:"With β1 and β2 blocked, only the sweaty palms are left."},
  {t:"Tachycardia", correct:false, why:"Every β blocker blocks β1, so the fast heart rate is masked."},
  {t:"Tremor", correct:false, why:"A non-selective blocker also masks the tremor."},
  {t:"Nervousness", correct:false, why:"A non-selective blocker also masks the nervousness."}],
 teach:"The warning signs of hypoglycemia are a racing heart, agitation, tremor and sweaty palms. Every β blocker masks the tachycardia; a non-selective one (propranolol) also masks the nervousness and tremor, leaving only sweating. If one must be used in an insulin-dependent diabetic, a β1-selective blocker leaves the tremor and nervousness.",
 quote:"It's even worse if you have a non-selective beta blocker because now you're blocking the nervousness, you block the tremor, all we have is the sweat palms.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 59; transcript 10/7"},

{id:"L11-046", lecture:"L11", prof:"Gottlieb", tier:"new", level:2, topic:"L11", sub:"bb", skill:"apply",
 concept:"diabetic-beta1-selective", tags:["in-class"], source:"both",
 stem:"If a β blocker must be given to an insulin-dependent diabetic, which type is preferred?",
 options:[
  {t:"β1 selective", correct:true, why:"It leaves tremor and nervousness as warning signs of hypoglycemia."},
  {t:"β1 and β2 blocker", correct:false, why:"Non-selective blockers mask tremor and nervousness too: a “no go”."},
  {t:"β1, β2 and α1 blocker", correct:false, why:"Also blocks β2, so the warning signs are masked."},
  {t:"Any β blocker equally", correct:false, why:"The non-selective ones mask more of the warning signs."}],
 teach:"All β blockers mask the tachycardia of hypoglycemia. Non-selective ones also mask tremor and nervousness, so they are a no-go for insulin-dependent diabetics. A β1-selective blocker (metoprolol, atenolol, nebivolol) keeps those signs. Glucose monitors have made the problem smaller than it used to be.",
 quote:"But even at that, if I had to choose, if I must choose a beta-blocker to an insulin-dependent diabetic, which one would I pick? I said beta one selective, right? Cause at least I leave the tremor and the nervousness out of that mix.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 59; transcript 10/7"},

{id:"L11-047", lecture:"L11", prof:"Gottlieb", tier:"new", level:3, ladder:"beta-blocker", ladderName:"β blockers: the heart, insulin, and stopping abruptly", topic:"L11", sub:"bb", skill:"apply",
 concept:"beta-blocker-withdrawal", tags:[], source:"both",
 stem:"A patient stops metoprolol abruptly while traveling. What is the risk, and why?",
 options:[
  {t:"Rebound hypertension from up-regulation", correct:true, why:"Chronic block led the body to make more β receptors; without the drug they are all available."},
  {t:"Excessive bradycardia from receptor down-regulation", correct:false, why:"An antagonist causes up-regulation, and stopping it speeds the heart."},
  {t:"Hypotension from down-regulation", correct:false, why:"The risk is a rise in pressure, not a fall."},
  {t:"No risk: the drug is reversible", correct:false, why:"Reversibility does not remove the extra receptors the body made."}],
 teach:"Slide 59: sudden discontinuation leads to rebound hypertension (up-regulation). The antagonist lowered the system's function, so the body made more receptors; stopping cold turkey leaves all those receptors and no blocker — a hypertensive crisis. Patients must wean off or get a supply from a pharmacist.",
 quote:"You cannot go cold turkey. Because if you go cold turkey, you get what hypertensive crisis, right? You've been up regulating your receptors because that antagonist is lowering the function of the system.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 59; transcript 10/7"},

{id:"L11-048", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"bb", skill:"apply",
 concept:"pindolol-low-heart-rate", tags:[], source:"both",
 stem:"A patient with sinoatrial (SA) or atrioventricular (AV) node dysfunction already has a very low heart rate but needs a β blocker. Which choice has a rationale?",
 options:[
  {t:"Pindolol", correct:true, why:"A partial agonist: it keeps some heart rate at night yet outcompetes norepinephrine when awake."},
  {t:"Propranolol", correct:false, why:"A full antagonist; at night, with the parasympathetic in charge, heart rate may fall too far."},
  {t:"Metoprolol", correct:false, why:"A full β1 antagonist; the same risk of excessive bradycardia."},
  {t:"Dobutamine", correct:false, why:"A β1 agonist, not a β blocker."}],
 teach:"Slide 59: be careful in sinoatrial (SA) or atrioventricular (AV) nodal dysfunction (excessive bradycardia). During sleep the parasympathetic takes over and the heart rate drops further. Pindolol, a partial agonist, behaves like an agonist when norepinephrine is low (keeping some heart rate) and like an antagonist when norepinephrine is high.",
 quote:"So in this case over here, Pindolol as the partial agonist would be a rationale to why choosing it because your patient has a very low heart rate to start with. ... It's going to behave like an agonist and behave like an antagonist.",
 note:"He said partial agonists were covered for Exam 1 and will not be discussed much for this exam (“We're not gonna be talking about much about the partial agonists for this purpose because we already addressed that in the exam one”); this is the one use of pindolol he gave on 10/7.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 54–55, 59; transcript 10/7"},

{id:"L11-050", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"bb", skill:"tell",
 concept:"metoprolol-vs-propranolol-brain", tags:[], source:"both",
 stem:"Why is metoprolol (Toprol XL) less likely than propranolol to cause fatigue and brain fog?",
 options:[
  {t:"Poor bioavailability to the brain", correct:true, why:"Propranolol is very lipophilic and gets everywhere, including the brain."},
  {t:"It blocks β2 in the brain", correct:false, why:"Metoprolol is β1 selective."},
  {t:"It is a partial agonist like pindolol", correct:false, why:"Metoprolol is a full β1 antagonist; the partial agonist is pindolol."},
  {t:"It also blocks α1", correct:false, why:"α1 block belongs to carvedilol and labetalol."}],
 teach:"Slide 55: β blockers differ in lipid solubility, receptor selectivity and partial agonist activity. Propranolol is very lipophilic and reaches the brain (fatigue, brain fog, depression); metoprolol has poor bioavailability to the brain. For the exam he focuses on receptor selectivity.",
 quote:"Also, the Toprol XL has poor bioavailability to the brain. So it may be more or less likely to cause fatigue, uh, brain fog, you know, anxiety, right? Depression, things like that, as propranolol is very lipophilic, it's gonna get everywhere.",
 note:"A brand name appears only because he used it; the exam asks generic names.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 55; transcript 10/7"},

/* ---------------- Cross-talk (slides 60–61) ---------------- */
{id:"L11-051", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"xtalk", skill:"recall",
 concept:"cross-talk-heart", tags:[], source:"both",
 stem:"In the heart, acetylcholine on M2 and norepinephrine on β1 act in opposite directions. Which statement about this cross-talk is CORRECT?",
 options:[
  {t:"The predominant tone wins", correct:true, why:"Whichever system has the predominant tone sets the response."},
  {t:"M2 always wins", correct:false, why:"In fight or flight the sympathetic β1 drive wins."},
  {t:"β1 always wins", correct:false, why:"At rest the parasympathetic tone predominates in the heart."},
  {t:"They act on the same G protein", correct:false, why:"M2 is Gi (less cAMP); β1 is Gs (more cAMP and PKA)."}],
 teach:"Cross-talk follows from dual innervation: something does a job and something opposes it. In the heart acetylcholine on M2 lowers rate and contractility, and norepinephrine on β1 (Gs, cAMP, PKA) raises contractility. Whoever has the predominant tone wins.",
 quote:"So if you look at the heart, where we have that dual innervation in which acetylcholine activates the M2s and that leads to bradycardia, decreasing contractility, as the beta ones are activated by norepinephrine and GS and that leads to an increasing contractility, that crosstalk is going to be happening to ourselves. And whoever has the predominant tone wins that crosstalk",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 61; transcript 10/7"},

/* ---------------- Nitric oxide (slides 62–74) ---------------- */
{id:"L11-052", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"no", skill:"recall",
 concept:"nos-arginine", tags:[], source:"both",
 stem:"How is nitric oxide (NO) made in the body?",
 options:[
  {t:"NOS converts L-arginine to L-citrulline", correct:true, why:"Nitric oxide synthase (NOS) oxidizes L-arginine to L-citrulline, with NO as a by-product."},
  {t:"sGC converts GTP to NO", correct:false, why:"Soluble guanylyl cyclase (sGC) makes cGMP from GTP; it is NO's target."},
  {t:"PDE converts cGMP to NO", correct:false, why:"Phosphodiesterase (PDE) breaks down cGMP; it makes no NO."},
  {t:"Monoamine oxidase converts tyrosine to NO", correct:false, why:"Monoamine oxidase breaks down catecholamines."}],
 teach:"Endogenous nitric oxide (NO) is made by nitric oxide synthase (NOS), which oxidizes the amino acid L-arginine to L-citrulline (with NADPH, O2 and calcium–calmodulin); NO is the by-product. There are several NOS subtypes (such as a brain NOS) that work the same way. In blood vessels NOS sits in the thin endothelial layer.",
 quote:"So what this nitric oxide synthase does, the NOS enzyme, is they can convert an amino acid, the L arginine, into the L-citrullin. And as a byproduct of that, you get nitric oxide.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 63; transcript 10/7"},

{id:"L11-053", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"no", skill:"recall",
 concept:"no-sgc-cgmp", tags:[], source:"both",
 stem:"Nitric oxide (NO) diffuses into vascular smooth muscle. What does it do there?",
 options:[
  {t:"Activates sGC to make cGMP", correct:true, why:"NO activates soluble guanylyl cyclase (sGC), which makes cyclic GMP (cGMP): vasodilation."},
  {t:"Activates adenylyl cyclase to make cAMP", correct:false, why:"That is β2 (Gs); NO uses the guanylyl cyclase pathway."},
  {t:"Activates PLC to make IP3", correct:false, why:"PLC and IP3 are the Gq pathway (α1, M3)."},
  {t:"Blocks PDE to keep cGMP", correct:false, why:"Phosphodiesterase (PDE) blockers are drugs such as sildenafil; NO activates sGC."}],
 teach:"Nitric oxide (NO) is a gas, very lipophilic, and crosses membranes easily. In the smooth muscle it activates soluble guanylyl cyclase (sGC) — like adenylyl cyclase but floating in the cytoplasm instead of on the membrane — which makes cyclic guanosine monophosphate (cGMP), a potent vasodilator. The more cGMP, the greater the vasodilation.",
 quote:"So instead of having the AC, we have the JC, but it's not on the membrane, it's floating on the cytoplasma, and that's what makes cyclic GMP. Which is a vasodilatory process.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 67, 70; transcript 10/7"},

{id:"L11-054", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"no", skill:"apply",
 concept:"endothelial-m3-vasodilation", tags:[], source:"both",
 stem:"M3 receptors are Gq-coupled, yet activating them on blood vessels causes vasodilation. Why?",
 options:[
  {t:"They are on the endothelium and make NO", correct:true, why:"Calcium in the endothelium activates NOS; nitric oxide (NO) relaxes the smooth muscle underneath."},
  {t:"They are Gi-coupled in vessels", correct:false, why:"M3 is Gq everywhere; the location makes the difference."},
  {t:"They lower calcium in smooth muscle", correct:false, why:"Gq raises calcium, in the endothelial cell."},
  {t:"They are innervated by the parasympathetic", correct:false, why:"Vascular M3 receptors are not innervated."}],
 teach:"Vascular M3 receptors are on the endothelium and are not innervated. M3 (Gq) → PLC → IP3 → calcium release from the endoplasmic reticulum → calcium–calmodulin → nitric oxide synthase (NOS) → nitric oxide (NO), which diffuses into the smooth muscle, activates soluble guanylyl cyclase and raises cGMP: vasodilation. This is the M3 exception he flagged in the G-protein table.",
 quote:"And this was one of our exceptions on the quick stable on the M3s on the endothelium. It does not cause constriction. It's going to cause dilation, and that's because calcium is one of the activators of the NS enzyme.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 68–74; transcript 10/7"},

{id:"L11-055", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"no", skill:"recall",
 concept:"nitrates-no-donors", tags:[], source:"both",
 stem:"How do nitroglycerin and nitroprusside cause vasodilation?",
 options:[
  {t:"They donate NO that activates sGC directly", correct:true, why:"As they are metabolized they give off nitric oxide (NO), bypassing M3 and NOS."},
  {t:"They activate the M3 receptors on the endothelium", correct:false, why:"That is a muscarinic agonist; the nitrates bypass M3."},
  {t:"They block phosphodiesterase", correct:false, why:"That is sildenafil and the other PDE inhibitors."},
  {t:"They activate β2 receptors", correct:false, why:"β2 agonists raise cAMP; the nitrates raise cGMP."}],
 teach:"Drugs with “nitro” in the name (nitroglycerin, nitroprusside, isosorbide dinitrate and mononitrate) are nitric oxide (NO) donors. As they are metabolized they release NO, which skips the M3–calcium–NOS steps and goes straight to soluble guanylyl cyclase (sGC), raising cGMP and causing vasodilation. They replace the NO a damaged or aging endothelium can no longer make.",
 quote:"As you take nitroglycerin, nitroglycerin over here is going to give away its nitric oxide which is going to bypass all of this and go straight into the subglonola cyclase and produce cyclic GMP, which leads to vasodilation.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 62, 67; transcript 10/7"},

{id:"L11-056", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"no", skill:"figure",
 concept:"furchgott-endothelium", tags:[], source:"both",
 stem:"Two labs test isolated rat femoral arteries. In both, epinephrine constricts the artery. Acetylcholine then relaxes the artery in lab 1 but not in lab 2, whose technician damaged the endothelium. Which explains the difference?",
 options:[
  {t:"No endothelium, no NO", correct:true, why:"Nitric oxide (NO) is made in the endothelium; strip it and acetylcholine has nothing to act through."},
  {t:"Lab 2 used a low epinephrine dose", correct:false, why:"Both labs got the same constriction from epinephrine."},
  {t:"Smooth muscle M3 was blocked in lab 2", correct:false, why:"The vascular M3 receptors are on the endothelium, which lab 2 removed."},
  {t:"Acetylcholine constricts smooth muscle directly", correct:false, why:"Neither lab saw acetylcholine constrict the artery."}],
 teach:"The 1998 Nobel Prize work (Furchgott, Ignarro, Murad): with intact endothelium, acetylcholine activates endothelial M3, calcium rises, NOS makes nitric oxide (NO), and the artery relaxes. With damaged endothelium there is no NO and acetylcholine cannot relax the epinephrine-constricted artery. The scientists' names are for information only.",
 quote:"In the second one, because you're ripping off the endothelium, there was no nitric oxide being produced, so you can get the dilation effect that they had, right? Does that kinda make sense? So, being careful in the lab can make a whole difference, right?",
 note:"“you can get the dilation effect” in the transcript reads as “you can't get”; the next sentence, “the other one just stays constricted”, confirms it. The slide 64 picture (intact vs damaged endothelium) could not be seen; the experiment is described from his words.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 64; transcript 10/7"},

{id:"L11-057", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, topic:"L11", sub:"no", skill:"figure",
 concept:"furchgott-epi-dose", tags:["in-class"], source:"both",
 stem:"In the isolated-artery experiment, epinephrine constricted the artery. Was the epinephrine dose high or low?",
 options:[
  {t:"High: α1 caused the constriction", correct:true, why:"Constriction means α1 was activated, which epinephrine reaches only at a high dose."},
  {t:"Low: β2 caused the constriction", correct:false, why:"β2 dilates vessels; a low dose would relax the artery."},
  {t:"Low: α2 caused the constriction", correct:false, why:"α2 is the last receptor epinephrine reaches, and it is inhibitory."},
  {t:"High: β1 caused the constriction", correct:false, why:"β1 is in the heart, not the arterial smooth muscle."}],
 teach:"Epinephrine binds β1 and β2 at low doses and α1 at high doses. In an artery, a low dose would dilate (β2); a constriction tells you α1 was activated, so the dose was high.",
 quote:"Is this a high or low dose of epi? What is the affinity profile of epinephrine? It has to be high, right, because if it's low, it's activating the beta 2. But because we're getting a vasoconstriction, that means that we are activating the alpha 1 at a very high dose of epinephrine.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 47, 64; transcript 10/7"},

{id:"L11-059", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"no", skill:"tell",
 concept:"camp-cgmp-pde-crosstalk", tags:[], source:"both",
 stem:"β2 activation and nitric oxide both relax vascular smooth muscle. Which statement about them is CORRECT?",
 options:[
  {t:"PDE breaks down both messengers", correct:true, why:"Phosphodiesterase (PDE) breaks down cAMP (β2) and cGMP (nitric oxide)."},
  {t:"Both act through cAMP", correct:false, why:"β2 raises cAMP; nitric oxide raises cGMP."},
  {t:"Both act through cGMP", correct:false, why:"Only nitric oxide raises cGMP."},
  {t:"Their effects oppose each other in the vessel", correct:false, why:"Both dilate; their effects add."}],
 teach:"Blood vessels can be dilated two ways: β2 activation (Gs, more cyclic AMP, cAMP) or nitric oxide (soluble guanylyl cyclase, more cyclic GMP, cGMP). Both second messengers are broken down by phosphodiesterase (PDE), so the two pathways add — a cross-talk with an additive vasodilation.",
 quote:"So the phosphodiesterase enzyme can break both cyclic EMP and cyclic GMP, our second messengers. So we have this cross stalk that has this additive vasodilation process.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 68–74; transcript 10/7"},

{id:"L11-060", lecture:"L11", prof:"Gottlieb", tier:"new", level:2, ladder:"nitroglycerin", ladderName:"Nitroglycerin and sildenafil", topic:"L11", sub:"no", skill:"apply",
 concept:"pde-inhibitor-potency", tags:["in-class"], source:"both",
 stem:"A drug blocks phosphodiesterase (PDE). What happens to the potency of nitric oxide?",
 options:[
  {t:"It increases", correct:true, why:"cGMP is no longer broken down, so the same nitric oxide gives more vasodilation."},
  {t:"It decreases", correct:false, why:"PDE ends the signal; blocking it prolongs and strengthens it."},
  {t:"It does not change", correct:false, why:"PDE activity is one of the two rate-limiting parts of the pathway."},
  {t:"It reverses to vasoconstriction", correct:false, why:"More cGMP means more vasodilation."}],
 teach:"Two components limit the nitric oxide response: how much nitric oxide there is (it has a very short half-life) and how much phosphodiesterase (PDE) activity there is to break down cGMP. Slide 74: “PDE inhibitors increase the potency of NO.”",
 quote:"So what do you think is going to happen if I give a drug that blocks the PDE? What is going to happen to the potency of nitric oxide? It's gonna increase.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 74; transcript 10/7"},

{id:"L11-061", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, ladder:"nitroglycerin", ladderName:"Nitroglycerin and sildenafil", topic:"L11", sub:"no", skill:"apply",
 concept:"aging-endothelium-nitrates", tags:[], source:"both",
 stem:"With age, damage to the blood vessels reduces nitric oxide production. What is the expected result, and how can a drug replace it?",
 options:[
  {t:"Blood pressure rises; a nitrate donates NO", correct:true, why:"Without endogenous nitric oxide (NO) the vessels cannot dilate; a NO donor supplies it."},
  {t:"Blood pressure falls; sildenafil restores it", correct:false, why:"Less NO means less dilation and higher pressure, not lower."},
  {t:"Heart rate falls; atropine restores NO", correct:false, why:"Atropine blocks M3 and would block, not restore, endothelial NO."},
  {t:"Blood pressure rises; propranolol donates NO", correct:false, why:"Propranolol is a β blocker, not a nitric oxide donor."}],
 teach:"As we age the endothelium is damaged and makes less nitric oxide (NO), so blood vessels cannot dilate and blood pressure can rise. Nitroglycerin, nitroprusside or isosorbide dinitrate/mononitrate replace the missing NO and restore the dilation.",
 quote:"So if you get old and as we get old there is damage to that blood vessel, we lose the ability to produce nitric oxide, our blood pressure can rise because I can't dilate anymore. So we can replace that by giving a nitroglycerin or a nitro pruide or isobyditrate or mononitrate",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 62, 74; transcript 10/7"},

{id:"L11-062", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"no", skill:"recall", multi:true,
 concept:"no-take-home", tags:[], source:"both",
 stem:"Which statements about the nitric oxide system are CORRECT? Select all that apply.",
 options:[
  {t:"Vascular M3 receptors are not innervated", correct:true, why:"Slide 74: “M3 are located on the endothelium & Not-innervated”."},
  {t:"Nitric oxide is a potent vasodilator", correct:true, why:"It diffuses into the smooth muscle and raises cGMP."},
  {t:"PDE inhibitors increase its potency", correct:true, why:"They stop the breakdown of cGMP."},
  {t:"Nitric oxide is made in the smooth muscle", correct:false, why:"It is made in the endothelium and diffuses into the smooth muscle."},
  {t:"Nitric oxide has a long half-life", correct:false, why:"It is broken down very quickly."}],
 teach:"Take-home message (slide 74): M3 receptors sit on the endothelium and are not innervated; their activation raises calcium and nitric oxide production in the endothelium; nitric oxide diffuses into the smooth muscle and produces potent vasodilation; phosphodiesterase (PDE) inhibitors increase its potency. He will not ask every step of the cascade.",
 quote:"first thing you got to remember that the M3s RGQ, they're going to increase calcium, but because they're located in the endothelium, they're not going to constrict, the smooth muscle. They're going to relax it because they're producing the nitric oxide, OK.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 74; transcript 10/7"},

/* ---------------- Lab tracings (slides 75–85, 10/7) ---------------- */
{id:"L11-063", lecture:"L11", prof:"Gottlieb", tier:"new", level:1, ladder:"ach-rat", ladderName:"Acetylcholine, atropine and blood pressure in the rat", topic:"L11", sub:"lab", skill:"figure",
 concept:"ach-bolus-reflex-tachycardia", tags:["in-class"], source:"both",
 stem:"In an anesthetized rat, an intravenous bolus of acetylcholine makes blood pressure fall and heart rate rise. Why does heart rate rise when acetylcholine on M2 should slow it?",
 options:[
  {t:"A baroreceptor reflex through β1", correct:true, why:"The fall in pressure (endothelial M3 → nitric oxide) triggers sympathetic drive to β1, overriding M2."},
  {t:"Acetylcholine activates β1 directly", correct:false, why:"Acetylcholine does not bind β1; norepinephrine from the reflex does."},
  {t:"Acetylcholine blocks M2 in the heart", correct:false, why:"Acetylcholine is the agonist at M2."},
  {t:"M2 is Gs-coupled in the rat", correct:false, why:"M2 is Gi everywhere."}],
 teach:"Acetylcholine activates endothelial M3, nitric oxide relaxes the vessels and blood pressure tanks. The baroreceptors sense it, shut off the parasympathetic and kick up the sympathetic; norepinephrine on β1 overrides the M2 slowing. The rise in heart rate is a β1 reflex tachycardia. Rule: blood pressure down, heart rate up.",
 quote:"So what you're seeing up there is not the effect of acetylcholineno M2, it's the effect of your sympathetic overriding the M2. Right? Your sympathetics are releasing norepinephrine full blast, activating the beta ones in order to compensate for this drop in blood pressure over here. So this is a beta one reflex. Tachycardia.",
 note:"He asked the class why heart rate rose; a student began with M2 being Gi, and he finished the answer. The tracing pictures (slides 77, 80) could not be seen; the tracing is described from his words.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 75–77; transcript 10/7"},

{id:"L11-064", lecture:"L11", prof:"Gottlieb", tier:"new", level:2, ladder:"ach-rat", ladderName:"Acetylcholine, atropine and blood pressure in the rat", topic:"L11", sub:"lab", skill:"figure",
 concept:"atropine-pretreatment-ach", tags:["in-class"], source:"both",
 stem:"The rat is pretreated with atropine, and the same acetylcholine dose is given. Blood pressure no longer falls. Why?",
 options:[
  {t:"Atropine blocks endothelial M3", correct:true, why:"No M3 activation, no nitric oxide, no drop in blood pressure (and no baroreceptor reflex)."},
  {t:"Atropine blocks α1 in the vessels", correct:false, why:"Atropine is a muscarinic antagonist; it does not act on α1."},
  {t:"Atropine breaks down acetylcholine", correct:false, why:"Acetylcholinesterase breaks down acetylcholine; atropine blocks the receptor."},
  {t:"Atropine activates β2 in the vessels", correct:false, why:"Atropine does not act on β2."}],
 teach:"Atropine is a non-selective muscarinic antagonist (M1, M2, M3). Blocking vascular (endothelial) M3 removes the nitric oxide drop in pressure, so the baroreceptors are left alone. Blocking cardiac M2 removes the parasympathetic tone, so β1 is unopposed and heart rate is higher.",
 quote:"So when I repeat this experiment, look over there now. I'm blocking the M3s in the blood vessels. There's no drop in blood pressure, but I'm also blocking who the M2s in the heart. So who is unopposed? The sympathetics.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 78–80; transcript 10/7"},

{id:"L11-065", lecture:"L11", prof:"Gottlieb", tier:"new", level:3, ladder:"ach-rat", ladderName:"Acetylcholine, atropine and blood pressure in the rat", topic:"L11", sub:"lab", skill:"figure",
 concept:"atropine-surmountable", tags:["in-class"], source:"both",
 stem:"After atropine, how can acetylcholine's fall in blood pressure and reflex tachycardia be restored?",
 options:[
  {t:"Give a much higher acetylcholine dose", correct:true, why:"Atropine is competitive; 100-fold more acetylcholine (5 to 500) outcompetes it."},
  {t:"Give neostigmine with the same dose", correct:false, why:"Not the step he described; he raised the agonist dose to outcompete atropine."},
  {t:"Nothing: atropine is irreversible", correct:false, why:"Atropine is a reversible, competitive antagonist."},
  {t:"Give prazosin first to free the M3 receptors", correct:false, why:"Prazosin blocks α1 and does not remove atropine from M3."}],
 teach:"Atropine is a reversible competitive antagonist, so a high enough agonist dose overcomes it. Raising acetylcholine 100-fold (from 5 to 500) brings back the drop in blood pressure and the reflex tachycardia.",
 quote:"How do I, how am I able to restore the effects of acetylcholine? What do I have to do in order to outcompete atropine? 4 o'clock. I have to increase the dose.",
 note:"Slide 77 labels the first dose “Acetylcholine, 5 mcg/kg”; he said “I went from 5 to 500”.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 77, 83; transcript 10/7"},

/* ---------------- β blocker and epinephrine summaries (10/7) ---------------- */
{id:"L11-072", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"bb", skill:"tell", multi:true,
 concept:"beta-blockers-block-beta2", tags:["exam-cue"], source:"both",
 stem:"Which β blockers also block β2 receptors? Select all that apply.",
 options:[
  {t:"Propranolol", correct:true, why:"Non-selective: β1 and β2."},
  {t:"Pindolol", correct:true, why:"Non-selective (β1 and β2), as a partial agonist."},
  {t:"Carvedilol", correct:true, why:"Mixed: β1, β2 and α1."},
  {t:"Labetalol", correct:true, why:"Mixed: β1, β2 and α1."},
  {t:"Metoprolol", correct:false, why:"β1 selective (“MAN”)."},
  {t:"Atenolol", correct:false, why:"β1 selective (“MAN”)."},
  {t:"Nebivolol", correct:false, why:"β1 selective (“MAN”)."}],
 teach:"Every β blocker blocks β1. Those that also block β2 are propranolol and pindolol (β1 and β2) and carvedilol and labetalol (β1, β2 and α1); these are the ones to be careful with in asthma. Metoprolol, atenolol and nebivolol (“MAN”) are β1 selective.",
 quote:"You should know which ones are beta 1 selectives, which ones are beta 1, beta 2 non-selectives, and which ones are beta 1, beta 2, and alpha 1 non-selectives. That's gonna be a key process.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 54, 59; transcript 10/7"},

{id:"L11-073", lecture:"L11", prof:"Gottlieb", tier:"new", topic:"L11", sub:"epi", skill:"recall", multi:true,
 concept:"epinephrine-statements", tags:[], source:"both",
 stem:"Which statements about epinephrine are CORRECT? Select all that apply.",
 options:[
  {t:"Low doses act mainly at β1 and β2", correct:true, why:"Its highest affinities are for β1 and β2."},
  {t:"At high doses α1 overrides β2 in vessels", correct:true, why:"The net response becomes vasoconstriction."},
  {t:"Patients on it must be weaned off", correct:true, why:"Its receptors are down-regulated during treatment."},
  {t:"It is a selective α1 agonist", correct:false, why:"That is phenylephrine; epinephrine acts at α1, α2, β1 and β2."},
  {t:"It cannot activate α2", correct:false, why:"α2 is the last receptor it reaches as the dose rises."}],
 teach:"Epinephrine is an endogenous catecholamine with different affinities: β1 and β2 at low doses, then α1 and α2 as the dose rises. In blood vessels the high-dose α1 effect overrides β2 (constriction); with α1 blocked, the β2 dilation shows (epinephrine reversal). Treatment down-regulates its receptors, so patients are weaned off.",
 quote:"But the key thing over here for you to remember is that epinephrine has different affinities. At low doses, they're the ones better choose. At higher doses, everybody, but alpha ones wins.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 47–52; transcript 10/7"},

/* ---------------- Ladder rungs (Tier 3): reversing a drug's effect ---------------- */
{id:"L11-075", lecture:"L11", prof:"Gottlieb", tier:"new", level:3, ladder:"mao-inhibitor", ladderName:"MAO inhibitor, tyramine and the hypertensive crisis", topic:"L11", sub:"pbz", skill:"apply",
 concept:"phenoxybenzamine-mao-crisis", tags:["reversal"], source:"both",
 stem:"A patient taking phenelzine eats aged cheese and drinks wine, then arrives with a hypertensive crisis. Which drug could lower the pressure, and why?",
 options:[
  {t:"Phenoxybenzamine: irreversible α1 and α2 block", correct:true, why:"Its covalent α1 block cannot be outcompeted by the flood of norepinephrine, so the vessels dilate and the pressure falls."},
  {t:"Selegiline: it blocks MAO-B in the brain", correct:false, why:"Another monoamine oxidase (MAO) inhibitor adds to the problem; it does not block the receptors that norepinephrine is acting on."},
  {t:"Phenylephrine: it activates α1 in the vessels", correct:false, why:"An α1 agonist constricts the vessels and raises the pressure further."},
  {t:"Dextroamphetamine: it releases norepinephrine", correct:false, why:"Releasing more norepinephrine adds to the crisis."},
  {t:"Cocaine: it blocks the norepinephrine transporter", correct:false, why:"Blocking reuptake leaves more norepinephrine at the receptors and raises the pressure further."}],
 teach:"Phenelzine irreversibly blocks MAO-A and MAO-B, so more norepinephrine is stored and released. With MAO-A blocked in the gut, dietary tyramine from fermented foods (cheese, bread, wine) cannot be broken down, and the result is the cheese effect: a hypertensive crisis. Phenoxybenzamine is an irreversible (covalent) α1 and α2 antagonist; because the excess norepinephrine cannot outcompete it, it can lower the pressure, and slide 34 lists hypertensive crisis from MAO inhibitors as one of its uses.",
 quote:"Uh, in the old days we also used to treat those patients who are getting that non-selective MAO inhibitors. Remember we have the cheese effect that we talked about it. They get that hypertensive crisis. So if you had a patient. who have a hypertensive crisis, we could use fenoxybenzammine to kind of lower their blood pressure and manage them a little bit better due to that uh cheese effect that you get.",
 note:"He said this use is less common now (\"We don't use it as often because people are not on an MAO and, you know, as often as they used to\"). The item asks the reversal through the mechanism, which he tests, rather than the use itself.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 14–15, 34; transcript 10/6; transcript 10/7"},

{id:"L11-076", lecture:"L11", prof:"Gottlieb", tier:"new", level:3, ladder:"beta-blocker-asthma", ladderName:"β blocker in asthma, with albuterol", topic:"L11", sub:"bb", skill:"apply",
 concept:"albuterol-outcompete-beta-blocker", tags:["reversal"], source:"both",
 stem:"A patient with asthma uses albuterol. Propranolol is started for his heart, and his wheezing returns. What will it take for albuterol to open his airways again, and why?",
 options:[
  {t:"More puffs, to outcompete propranolol at β2", correct:true, why:"Propranolol blocks lung β2 reversibly, so a higher amount of the β2 agonist can outcompete it, at more cost and more time to bronchodilate."},
  {t:"Nothing works; propranolol binds β2 covalently", correct:false, why:"Propranolol is a competitive β blocker; it can be outcompeted."},
  {t:"Fewer puffs; propranolol raises β2 activity", correct:false, why:"Propranolol is an antagonist; it lowers β2 activity in the lungs."},
  {t:"Add metoprolol to free the β2 receptors", correct:false, why:"Metoprolol is a selective β1 antagonist; it does not free β2 receptors from propranolol."},
  {t:"The same puffs; propranolol blocks only β1", correct:false, why:"Propranolol is non-selective: it blocks β1 and β2, including β2 in the lungs."}],
 teach:"Albuterol is a β2 agonist (Gs, more cyclic AMP) that relaxes bronchial smooth muscle. Propranolol is a non-selective β1 and β2 blocker, so in the lungs it blocks the β2 that albuterol needs and makes asthma worse. The block is competitive, so it takes more puffs of the short-acting or long-acting β2 agonist (SABA or LABA) to outcompete it, which costs the patient money and quality of life. The better choice for such a patient is a β1-selective blocker such as metoprolol.",
 quote:"If you have a beta blocker that is non-selective and we're blocking the beta 2, it's going to require more puffs of your saba or your laba to outcompete the beta blocker, which means it's going to cost your patient more money. And it's going to cost them also quality of life because it's going to take longer for them to get to a level where they can bronchodilate.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 42–43, 54, 59; transcript 10/7"}
);
