TOPICS.push({id:"L10", name:"Day 10: adrenergic receptors, indirect-acting drugs, α1 and α2", prof:"Gottlieb", lecture:"L10",
  cite:"Day 10 (10/6) — PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf (slides 1–32 taught)",
  subs:[
    {id:"rec", name:"Adrenergic receptors and their G proteins", cite:"slides 2–3"},
    {id:"map", name:"Heart, circulation and the MAP equation", cite:"slides 4–7"},
    {id:"ne", name:"Norepinephrine synthesis, release and removal", cite:"slide 8"},
    {id:"class", name:"Direct, mixed and indirect agonists", cite:"slide 9"},
    {id:"indirect", name:"Cocaine, amphetamines and methylphenidate", cite:"slides 10–12"},
    {id:"mao", name:"MAO inhibitors and the cheese effect", cite:"slides 13–15"},
    {id:"a1", name:"α1 receptors: phenylephrine, oxymetazoline", cite:"slides 16–19"},
    {id:"a2", name:"α2 receptors: clonidine", cite:"slides 20–24, 26"},
    {id:"a1ant", name:"α antagonists: prazosin and the -osins", cite:"slides 27–30"},
    {id:"mirt", name:"Mirtazapine (α2 antagonist)", cite:"slides 31–32"}
  ]});
QUESTIONS.push(
/* ---------------- Receptors and G proteins (slide 3) ---------------- */
{id:"L10-001", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"rec", skill:"recall",
 concept:"adrenergic-g-proteins", tags:[], source:"both",
 stem:"Which pairing of adrenergic receptor and G protein is CORRECT?",
 options:[
  {t:"α2: Gi", correct:true, why:"α2 is coupled to Gi: inhibition of adenylyl cyclase (AC) and less cyclic AMP (cAMP)."},
  {t:"α1: Gs", correct:false, why:"α1 is coupled to Gq (phospholipase C, IP3, Ca++), not Gs."},
  {t:"β1: Gi", correct:false, why:"All β receptors are Gs; β1 activates AC and raises cAMP."},
  {t:"β2: Gq", correct:false, why:"β2 is Gs (activation of AC, more cAMP)."},
  {t:"β3: Gi", correct:false, why:"β3 is also Gs: it increases AC and cAMP."}],
 teach:"The adrenergic table: α1 → Gq → phospholipase C (PLC) → IP3; α2 → Gi → inhibition of adenylyl cyclase (AC) → less cyclic AMP (cAMP); β1, β2 and β3 → Gs → activation of AC → more cAMP. All the β receptors are Gs, so they act in the same direction on the second messenger.",
 quote:"We have alpha 1s, alpha 2s, beta 1s, beta 2s, and beta 3s. The good news is all betas are GS, so you kind of know what they're going to do ... alpha 2s are GI, and alpha 1s are GQ.",
 note:"In the same sentence he also said “alpha 2s are GQ” before correcting himself to “alpha 2s are GI”; the slide table gives α2 = Gi. Keyed to the slide.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 3; transcript 10/6"},

{id:"L10-002", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"rec", skill:"tell",
 concept:"alpha-like-muscarinic", tags:[], source:"both",
 stem:"Which adrenergic receptor uses the same G protein and second-messenger change as the muscarinic M2 receptor?",
 options:[
  {t:"α2", correct:true, why:"M2 and α2 are both Gi: inhibition of adenylyl cyclase and less cAMP."},
  {t:"α1", correct:false, why:"α1 is Gq, like M3 (PLC, IP3, ↑Ca++)."},
  {t:"β1", correct:false, why:"β1 is Gs, which raises cAMP, the opposite of M2."},
  {t:"β2", correct:false, why:"β2 is Gs and raises cAMP."},
  {t:"β3", correct:false, why:"β3 is Gs and raises cAMP."}],
 teach:"The adrenergic receptors reuse the muscarinic second-messenger patterns. α2, like M2, is Gi (inhibition of adenylyl cyclase, less cyclic AMP). α1, like M3, is Gq (phospholipase C, IP3, more Ca++). They differ in where in the body they are located.",
 quote:"So if you know what M2 does, you know what alpha-2 is gonna do. If you know what M3 does, alpha-1 is gonna do a similar process. They're just located in different parts of our body",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 3; transcript 10/6"},

{id:"L10-003", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"rec", skill:"recall",
 concept:"beta3-bladder", tags:[], source:"both",
 stem:"Where do β3 receptors have their greatest effect?",
 options:[
  {t:"Bladder", correct:true, why:"His one point to remember about β3: its primary location, where it has the greatest effect, is the bladder."},
  {t:"Heart", correct:false, why:"The heart is run by β1."},
  {t:"Resistance arteries", correct:false, why:"Arteries and veins are run by α1 (with β2 causing vasodilation)."},
  {t:"Brain", correct:false, why:"In the brain the adrenergic receptor he stresses is α2, which suppresses the sympathetic system."},
  {t:"Salivary glands", correct:false, why:"No β3 site was given for the glands."}],
 teach:"β3 is coupled to Gs like β1 and β2: it increases adenylyl cyclase (AC) and cyclic AMP (cAMP). Its primary site, where it has the greatest effect, is the bladder, which lets drugs act there with fewer side effects.",
 quote:"The one thing that you need to remember about beta 3 is their primary location where they have the greatest effect is gonna be in the bladder, OK?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 3; transcript 10/6"},

{id:"L10-004", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"rec", skill:"recall", multi:true,
 concept:"camp-raising-receptors", tags:[], source:"both",
 stem:"Activation of which adrenergic receptors increases cyclic AMP (cAMP)? Select all that apply.",
 options:[
  {t:"β1", correct:true, why:"β1 → Gs → activation of adenylyl cyclase (AC) → more cAMP."},
  {t:"β2", correct:true, why:"β2 → Gs → activation of AC → more cAMP."},
  {t:"β3", correct:true, why:"β3 → Gs → ↑AC → ↑cAMP."},
  {t:"α1", correct:false, why:"α1 → Gq → phospholipase C → IP3 and Ca++; not cAMP."},
  {t:"α2", correct:false, why:"α2 → Gi → inhibition of AC → cAMP goes down."}],
 teach:"Only the β receptors raise cAMP: all three are Gs and activate adenylyl cyclase (AC). α2 does the opposite (Gi, less cAMP), and α1 works through Gq, phospholipase C, IP3 and calcium.",
 quote:"They're gonna increase the GS activity, they're gonna increase AC which is gonna increase camp.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 3; transcript 10/6"},

/* ---------------- Heart, circulation, MAP (slides 4–7) ---------------- */
{id:"L10-005", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"map", skill:"tell",
 concept:"preload-vs-afterload", tags:["in-class"], source:"both",
 stem:"Which statement about preload and afterload is CORRECT?",
 options:[
  {t:"Preload is the blood in the ventricle at end diastole", correct:true, why:"Preload = end-diastolic volume (diastolic pressure): how much blood is in the relaxed ventricle, ready to be pumped."},
  {t:"Afterload is the blood returning to the heart", correct:false, why:"Blood returning to the heart is preload (venous return)."},
  {t:"Preload is the pressure needed to open the aortic valve", correct:false, why:"The pressure the heart must overcome to open the valve is afterload (systolic pressure)."},
  {t:"Afterload is set mainly by the veins", correct:false, why:"Afterload is set by the resistance arteries; the veins set preload."},
  {t:"Preload and afterload both mean heart rate", correct:false, why:"Heart rate and contractility are the factors within the heart; preload and afterload are outside it."}],
 teach:"Preload (diastolic pressure, end-diastolic volume) is the blood in the ventricle at the end of diastole, set by venous return. Afterload (systolic pressure) is the force the ventricle must overcome to open the valve and push blood out, set by the resistance arteries. Heart rate and contractility are the factors within the heart.",
 quote:"So preload is how much blood is in the ventricle at the top of diastole when your ventricle is the most relaxed, right? Another word for that is called end diastolic volume or diastolic pressure. ... So afterload is the same thing as systolic pressure, right? What is the pressure in your resistant arteries?",
 note:"He asked the class “So what is preload?” and “What about afterload?”; a student answered “The resistance of the vessels” for afterload.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 4, 6; transcript 10/6"},

{id:"L10-006", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"map", skill:"apply",
 concept:"afterload-cardiac-output", tags:[], source:"both",
 stem:"With nothing else changed, an increase in afterload is most likely to do which of the following?",
 options:[
  {t:"Decrease stroke volume", correct:true, why:"More of the heart's work goes into opening the valve, leaving less to push blood out: stroke volume and cardiac output fall."},
  {t:"Increase stroke volume", correct:false, why:"That is what lowering afterload (a vasodilator) does."},
  {t:"Decrease preload directly", correct:false, why:"The slide says a fall in stroke volume must be compensated by an increase in preload, not a decrease."},
  {t:"Leave cardiac output unchanged", correct:false, why:"Afterload affects how much the heart can eject, so cardiac output changes."}],
 teach:"Afterload is the pressure the ventricle must overcome to open the valve. The higher it is, the more work the heart does just to open the valve and the less blood it squeezes out, so stroke volume and cardiac output fall; this must be compensated by an increase in preload. A vasodilator lowers afterload and frees the heart to eject more.",
 quote:"The higher the afterload is, the work, the more work my heart has to do to open that valve and squeeze it out. So that's going to decrease my cardiac output. ... At the same token, if we give vasodilators ... now I have to work less to open the valve and I have more energy to squeeze the blood out, thus increasing the cardiac output.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 6; transcript 10/6"},

{id:"L10-007", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"map", skill:"tell",
 concept:"cv-receptor-roles", tags:[], source:"both",
 stem:"Which pairing of adrenergic receptor and cardiovascular role is CORRECT?",
 options:[
  {t:"β1: heart rate and contractility", correct:true, why:"Within the heart, the β1s run the show: how fast it beats and how strongly it contracts."},
  {t:"α1 in veins: afterload", correct:false, why:"α1 in the veins sets preload (venous return); afterload is α1 in the resistance arteries."},
  {t:"α1 in arteries: preload", correct:false, why:"α1 in the resistance arteries sets afterload."},
  {t:"α2 in brain: more sympathetic outflow", correct:false, why:"α2 is Gi and inhibitory; in the brain it suppresses the sympathetic system."},
  {t:"β2: vasoconstriction", correct:false, why:"β2 causes vasodilation, a check on α1 vasoconstriction."}],
 teach:"The cardiovascular map: α1 in the veins (preload) and in the resistance arteries (afterload), both directly innervated by the sympathetic system; β1 in the heart (heart rate, contractility, rate of relaxation) and kidney (renin); β2 causes vasodilation to counter constriction; α2 in the brain and on nerves suppresses sympathetic outflow.",
 quote:"So in the heart, within the heart, the beta ones run the show. Those are the receptors that are going to affect how fast your heart is beating and how strongly it is contracting in the arteries. It's going to be our alpha 1 adrenergic receptors.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 4–5; transcript 10/6"},

{id:"L10-008", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"map", skill:"apply",
 concept:"venous-alpha1-preload", tags:[], source:"both",
 stem:"Sympathetic activity to the α1 receptors in the veins increases. Which change is most likely?",
 options:[
  {t:"Preload rises", correct:true, why:"Squeezing the veins (Gq, ↑Ca++) sends more blood back to the heart: more venous return, more preload."},
  {t:"Preload falls", correct:false, why:"Relaxed veins pool blood in the feet and lower preload; α1 activation does the opposite."},
  {t:"Heart rate falls through β1", correct:false, why:"Venous α1 does not act on β1; the question is about venous tone."},
  {t:"Veins dilate through Gi", correct:false, why:"α1 is Gq: more calcium and constriction, not Gi."}],
 teach:"Venous return depends on venous tone. Norepinephrine released by sympathetic nerves activates α1 (Gq → ↑Ca++ → constriction) in the veins, squeezing blood back to the heart and raising preload. Relaxed veins act like a water-filled balloon: blood stays in the feet.",
 quote:"So, as I squeeze the veins, depending on how much tone of my sympathetics are activating those alpha-1 in the veins, that's gonna determine how much blood returns to the heart and how much blood comes out of the heart.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 5; transcript 10/6"},

{id:"L10-009", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"map", skill:"recall",
 concept:"beta1-kidney-renin", tags:[], source:"both",
 stem:"Activation of β1 receptors in the kidney mainly increases the production of which substance?",
 options:[
  {t:"Renin", correct:true, why:"Renal β1 increases renin, which leads to more angiotensin II, a vasoconstrictor."},
  {t:"Nitric oxide", correct:false, why:"Nitric oxide comes from endothelial M3 activation, not renal β1."},
  {t:"Acetylcholine", correct:false, why:"Acetylcholine is released by cholinergic nerves, not made by renal β1."},
  {t:"Norepinephrine", correct:false, why:"Norepinephrine is released by sympathetic nerves; β1 is the receptor it acts on."}],
 teach:"The kidney is the long-term regulator of blood pressure. β1 receptors there increase renin production, which makes more angiotensin II, a vasoconstrictor (the renin–angiotensin system is a later lecture).",
 quote:"And finally, we have a long-term component over here that is involved in the long-term regulation of blood pressure, and that's gonna be the kidneys. OK, and in the kidneys, the beta ones also can affect its function. Primarily by increasing the production of what? Ren, which it makes more gen testing 2, which is a vasoconstrictor, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 5; transcript 10/6"},

{id:"L10-010", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"map", skill:"recall",
 concept:"map-equation", tags:["exam-cue"], source:"both",
 stem:"Which equation gives mean arterial pressure (MAP)?",
 options:[
  {t:"MAP = CO × TPR", correct:true, why:"MAP = cardiac output (CO, which is HR × SV) × total peripheral resistance (TPR)."},
  {t:"MAP = CO + TPR", correct:false, why:"The two terms multiply, not add."},
  {t:"MAP = CO ÷ TPR", correct:false, why:"Raising resistance raises pressure; it does not divide it."},
  {t:"MAP = HR × TPR", correct:false, why:"Heart rate alone is incomplete: cardiac output is HR × stroke volume."},
  {t:"MAP = SV × HR", correct:false, why:"HR × SV is cardiac output, only one of the two terms."}],
 teach:"MAP = CO (HR × SV) × TPR: mean arterial pressure equals cardiac output (heart rate × stroke volume) times total peripheral resistance. Drugs lower MAP by lowering cardiac output (less contractility and heart rate, less ventricular filling) or TPR (vasodilation of resistance vessels, less sympathetic tone).",
 quote:"Some drugs are going to be more selective to one component versus the other, but the goal over here is for us to be able to predict what component of the aminote pressure formula is being affected by our drugs.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 7; transcript 10/6"},

{id:"L10-011", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"map", skill:"apply",
 concept:"carvedilol-map", tags:[], source:"both",
 stem:"Carvedilol blocks β1, β2 and α1 receptors. Which describes its effect on the mean arterial pressure (MAP) equation?",
 options:[
  {t:"It lowers both CO and TPR", correct:true, why:"β1 block decreases the heart's effects (cardiac output, CO); α1 block in arteries and veins decreases total peripheral resistance (TPR)."},
  {t:"It lowers CO only", correct:false, why:"Its α1 block also relaxes arteries and veins, lowering TPR."},
  {t:"It lowers TPR only", correct:false, why:"Its β1 block also lowers the heart's rate and force, lowering CO."},
  {t:"It raises CO and lowers TPR", correct:false, why:"Blocking β1 lowers, not raises, cardiac output."}],
 teach:"MAP = cardiac output (CO) × total peripheral resistance (TPR). Carvedilol blocks β1 (heart: less rate and contractility, lower CO) and α1 (arteries and veins: vasodilation, lower TPR), so it acts on both terms. The skill is to place each drug on the part of the equation it changes.",
 quote:"As such, if I block the beta ones, I can decrease the effects in the heart, and if I block the alpha ones, I can decrease the effects in the arteries and the veins, thus decreasing my total peripheral resistance. So carvedilol can do it all.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 7; transcript 10/6"},

{id:"L10-012", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"map", skill:"apply",
 concept:"blood-pressure-rules", tags:[], source:"both",
 stem:"A drug lowers a patient's blood pressure. Which reflex change is most likely?",
 options:[
  {t:"Heart rate goes up", correct:true, why:"His rule, “blood pressure rules”: if blood pressure goes down, heart rate goes up."},
  {t:"Heart rate goes down", correct:false, why:"Heart rate falls when blood pressure rises, not when it falls."},
  {t:"Heart rate does not change", correct:false, why:"The body defends mean arterial pressure, so heart rate responds."},
  {t:"The veins dilate further", correct:false, why:"The compensation is more sympathetic drive, which constricts rather than dilates."}],
 teach:"Mean arterial pressure is defended: when blood pressure falls, sympathetic drive and heart rate rise; when it rises, heart rate falls. This is why vasodilators such as prazosin cause reflex tachycardia.",
 quote:"And there's a rule that we need to follow, and the rule is blood blood pressure rules. What do I mean by that? If my blood pressure goes down, heart rate goes up. If my blood pressure goes up, heart rate goes down.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 5; transcript 10/6"},

{id:"L10-013", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"map", skill:"recall",
 concept:"beta1-rate-of-relaxation", tags:[], source:"both",
 stem:"Besides heart rate and contractility, which cardiac function does β1 activation increase?",
 options:[
  {t:"Rate of relaxation", correct:true, why:"β1 (Gs) increases heart rate, contractility and the rate of relaxation, so the ventricle can refill between fast beats."},
  {t:"Afterload", correct:false, why:"Afterload is set by α1 in the resistance arteries."},
  {t:"Venous capacitance", correct:false, why:"Venous tone is α1 in the veins."},
  {t:"Acetylcholine release", correct:false, why:"β1 does not control acetylcholine release."}],
 teach:"β1 receptors in the heart are Gs: they increase heart rate, contractility and the rate of relaxation. Relaxation takes energy too; if the heart beats fast but does not relax fast enough, the ventricles cannot fill.",
 quote:"We're going to increase the heart rate. We're going to increase the contractility, and also we're going to increase the rate of relaxation. ... It's just how fast your heart has to relax to fill the blood so that it can pump again.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 5; transcript 10/6"},

/* ---------------- NE synthesis, release, removal (slide 8) ---------------- */
{id:"L10-014", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"ne", skill:"recall",
 concept:"ne-synthesis", tags:[], source:"both",
 stem:"Which sequence shows the synthesis of norepinephrine?",
 options:[
  {t:"Tyrosine → L-Dopa → dopamine → norepinephrine", correct:true, why:"The precursor chain drawn in the nerve terminal."},
  {t:"L-Dopa → tyrosine → dopamine → norepinephrine", correct:false, why:"Tyrosine comes first; L-Dopa is made from it."},
  {t:"Tyrosine → dopamine → L-Dopa → norepinephrine", correct:false, why:"L-Dopa comes before dopamine."},
  {t:"Dopamine → tyrosine → L-Dopa → norepinephrine", correct:false, why:"Dopamine is made from L-Dopa, which is made from tyrosine."}],
 teach:"In the sympathetic nerve terminal, tyrosine → L-Dopa → dopamine → norepinephrine (NE). NE is stored in vesicles and released on an action potential, like acetylcholine in the cholinergic nerve.",
 quote:"So very similar to the muscarinic, uh, to the acetylcholines, norepinephrine is gonna be made by a precursor, and it's gonna be stored in a vesicle, and upon an extra potential, we're gonna have the release of norepinephrine to the synapse.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 8; transcript 10/6"},

{id:"L10-015", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"ne", skill:"recall",
 concept:"presynaptic-alpha2-feedback", tags:[], source:"both",
 stem:"What does activation of the presynaptic α2 receptor do?",
 options:[
  {t:"Suppresses norepinephrine release", correct:true, why:"Presynaptic α2 is negative feedback, the gatekeeper that suppresses release of norepinephrine."},
  {t:"Increases norepinephrine release", correct:false, why:"That is what blocking α2 does (mirtazapine)."},
  {t:"Breaks down norepinephrine", correct:false, why:"Breakdown is done by the enzymes COMT and MAO."},
  {t:"Recycles norepinephrine into vesicles", correct:false, why:"Recycling is the norepinephrine transporter (NET)."},
  {t:"Contracts the effector cell", correct:false, why:"The effector cell carries postsynaptic α1 and β receptors, not the presynaptic α2."}],
 teach:"Postsynaptically, norepinephrine acts on α1 or β receptors. Presynaptically sits α2, coupled to Gi: it is negative feedback that suppresses further norepinephrine release (the gatekeeper).",
 quote:"Typically, on the post-synaptic side, we're gonna have either alpha one or beta ones, OK? On the pre-synaptic side, we're typically gonna have alpha-2s. Which are negative feedback. This is what's going to suppress the release of norepinephrine. This is our gatekeeper.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 8; transcript 10/6"},

{id:"L10-016", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"ne", skill:"recall", multi:true,
 concept:"ne-removal", tags:[], source:"both",
 stem:"Which remove released norepinephrine from the synapse? Select all that apply.",
 options:[
  {t:"Catechol-O-methyltransferase (COMT)", correct:true, why:"One of the two enzymes that break norepinephrine down to inactive metabolites."},
  {t:"Monoamine oxidase (MAO)", correct:true, why:"The other enzyme that breaks norepinephrine down."},
  {t:"Norepinephrine transporter (NET)", correct:true, why:"The NET takes norepinephrine back so it can be recycled into the vesicle."},
  {t:"Acetylcholinesterase", correct:false, why:"Acetylcholinesterase breaks down acetylcholine, not norepinephrine."},
  {t:"Presynaptic α2 receptor", correct:false, why:"α2 lowers release; it does not remove norepinephrine already released."}],
 teach:"After release, norepinephrine is removed by two enzymes, catechol-O-methyltransferase (COMT) and monoamine oxidase (MAO), and, more economically, by the norepinephrine transporter (NET), which recycles it back into the vesicle. Each is a drug target: NET blockers and MAO inhibitors raise norepinephrine.",
 quote:"We have two enzymes, the COAMT or the MAO, right? And they're gonna cut it down, break down the norepinephrine. More economically, can we move them to the net transporter, the norepinephrine transporter, and recycle it back into the vesicle so that we don't have to make new ones.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 8; transcript 10/6"},

{id:"L10-017", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"ne", skill:"tell",
 concept:"net-recycles", tags:[], source:"both",
 stem:"Which of the following returns norepinephrine to the nerve so it can be stored in the vesicle again?",
 options:[
  {t:"Norepinephrine transporter (NET)", correct:true, why:"The NET moves norepinephrine back into the nerve to be recycled into the vesicle."},
  {t:"Monoamine oxidase (MAO)", correct:false, why:"MAO breaks norepinephrine down; it does not recycle it."},
  {t:"Catechol-O-methyltransferase (COMT)", correct:false, why:"COMT breaks norepinephrine down to inactive metabolites."},
  {t:"Presynaptic α2 receptor", correct:false, why:"α2 suppresses release; it does not take norepinephrine up."}],
 teach:"Removal routes for norepinephrine: two enzymes that destroy it (COMT, MAO) and one transporter that recycles it (NET). Cocaine blocks the NET; phenelzine and selegiline block MAO.",
 quote:"If we have too much of it, the enzymes come and break it. If we don't have enough, we might shunt more through the transporter pathways, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 8; transcript 10/6"},

/* ---------------- Classification of agonists (slide 9) ---------------- */
{id:"L10-018", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"class", skill:"tell",
 concept:"oxymetazoline-nonselective", tags:[], source:"both",
 stem:"Which drug is a non-selective, direct-acting α1 and α2 agonist?",
 options:[
  {t:"Oxymetazoline", correct:true, why:"Oxymetazoline binds and activates both α1 and α2, so it is non-selective."},
  {t:"Phenylephrine", correct:false, why:"Phenylephrine is a selective α1 agonist."},
  {t:"Clonidine", correct:false, why:"Clonidine is a selective α2 agonist."},
  {t:"Cocaine", correct:false, why:"Cocaine is indirect acting (reuptake inhibitor)."},
  {t:"Selegiline", correct:false, why:"Selegiline is indirect acting (MAO inhibitor)."}],
 teach:"A selective drug binds one receptor; a drug that binds two or more is non-selective. Selective direct agonists: phenylephrine (α1), clonidine (α2). Non-selective direct agonists: oxymetazoline (α1 and α2), and epinephrine and norepinephrine (α1, α2, β1, β2).",
 quote:"And some of those drugs are gonna be selective, they only bind to one receptor or non-selective. They bind to one or more receptors. If you bind to two or more, you're not selective, OK?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 9, 19; transcript 10/6"},

{id:"L10-019", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"class", skill:"recall",
 concept:"ephedrine-mixed", tags:[], source:"both",
 stem:"Ephedrine is classified as mixed acting. Which describes it?",
 options:[
  {t:"Activates α and β receptors and releases norepinephrine", correct:true, why:"Ephedrine is an α1, α2, β1, β2 agonist and a releasing agent: direct and indirect at once."},
  {t:"Blocks the norepinephrine transporter only", correct:false, why:"That is cocaine, an indirect reuptake inhibitor."},
  {t:"Irreversibly blocks MAO-A and MAO-B (monoamine oxidase)", correct:false, why:"That is phenelzine."},
  {t:"Selectively activates α1 receptors", correct:false, why:"That is phenylephrine, a direct selective agonist."}],
 teach:"Mixed-acting means both mechanisms: ephedrine binds and activates α1, α2, β1 and β2 and also increases norepinephrine release. The result is massive sympathetic activation (constricted vessels, a working heart, continuous norepinephrine), which caused strokes and heart attacks and ended its use in US dietary supplements.",
 quote:"You can see that this drug not only can bind and activate all the receptors but also increase the release of norepinephrine. So we have this massive activation of your sympathetic nervous system, which causes people to have a heart attack",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 9; transcript 10/6"},

{id:"L10-020", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"class", skill:"tell", multi:true,
 concept:"indirect-acting-group", tags:[], source:"both",
 stem:"Which drugs are indirect-acting adrenergic agonists? Select all that apply.",
 options:[
  {t:"Amphetamine", correct:true, why:"A releasing agent."},
  {t:"Cocaine", correct:true, why:"A reuptake inhibitor (blocks the NET)."},
  {t:"Phenelzine", correct:true, why:"An MAO inhibitor."},
  {t:"Selegiline", correct:true, why:"An MAO inhibitor (selective MAO-B)."},
  {t:"Phenylephrine", correct:false, why:"A direct, selective α1 agonist."},
  {t:"Clonidine", correct:false, why:"A direct, selective α2 agonist."},
  {t:"Oxymetazoline", correct:false, why:"A direct, non-selective α1 and α2 agonist."}],
 teach:"Indirect-acting drugs do not bind the adrenergic receptor; they raise norepinephrine. Three groups: releasing agents (amphetamine), reuptake inhibitors (cocaine) and monoamine oxidase (MAO) inhibitors (phenelzine, selegiline). Direct agonists (phenylephrine, clonidine, oxymetazoline) bind the receptor themselves.",
 quote:"The other ones over here that are indirectly we have the amphetamine-like drugs. ... We have drugs like cocaine that are used recreationally ... And then we have some of the MAO inhibitors that by blocking the enzyme that breaks down catecholamines, we can increase the levels in the brain",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 9; transcript 10/6"},

/* ---------------- Cocaine, amphetamines (slides 10–12) ---------------- */
{id:"L10-021", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"indirect", skill:"apply",
 concept:"cocaine-nasal-vasoconstriction", tags:["in-class"], source:"both",
 stem:"A person who snorts cocaine has repeated nosebleeds and damage to the nasal septum. Which mechanism explains it?",
 options:[
  {t:"Excess α1 vasoconstriction", correct:true, why:"Blocking the NET raises synaptic norepinephrine, which constricts nasal vessels through α1 so much that the mucosa dies."},
  {t:"More acetylcholine on M3 → vasodilation", correct:false, why:"Cocaine acts on norepinephrine reuptake, not acetylcholine."},
  {t:"β2 activation → vasodilation", correct:false, why:"The damage comes from too much constriction, not dilation."},
  {t:"α2 activation → less norepinephrine", correct:false, why:"Cocaine raises synaptic norepinephrine; it does not lower it."},
  {t:"MAO block → tyramine crisis", correct:false, why:"MAO block is phenelzine and selegiline; cocaine blocks the NET."}],
 teach:"Cocaine is a reuptake inhibitor: it blocks the norepinephrine transporter (NET), raising synaptic norepinephrine and activating the postsynaptic receptors. In nasal blood vessels the α1 vasoconstriction is severe enough to kill the mucosa and destroy the septum, so users bleed from the nose. In the central nervous system it causes excitation; in the heart, higher heart rate and risk of a heart attack.",
 quote:"You're releasing norepinephrine, you're vasoconstricting those blood vessels so much that it starts to kill your mucosa of your sinus and destroy your septum and everything else in there. And that's gonna lead to bleeding on their nose. So, in the blood vessels, this drug can cause severe vasoconstriction.",
 note:"He asked the class “do you know why that is happening?” about the nosebleeds and answered himself.",
 reading:[{"src":"Katzung 16e, Ch. 9","sec":"The Norepinephrine Transporter","t":"Blocking the norepinephrine transporter, for example by the non-selective psychostimulant cocaine, impairs the main route by which norepinephrine is removed from the synapse, so synaptic norepinephrine levels rise and adrenergic receptors are stimulated more."}],
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 10; transcript 10/6"},

{id:"L10-022", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"indirect", skill:"apply",
 concept:"cocaine-lidocaine-local", tags:[], source:"transcript", lowYield:true,
 stem:"Cocaine or another strong vasoconstrictor is sometimes added to lidocaine when a cut is sutured. What is the rationale?",
 options:[
  {t:"Keeps lidocaine local", correct:true, why:"Vasoconstriction decreases bleeding and stops lidocaine from going systemic and reaching the heart, where it can cause arrhythmias."},
  {t:"Speeds lidocaine's spread to the heart", correct:false, why:"The goal is the opposite: keep lidocaine out of the heart."},
  {t:"Blocks the pain by dilating vessels", correct:false, why:"The added drug constricts, not dilates, the vessels."},
  {t:"Treats an arrhythmia caused by the cut", correct:false, why:"The vasoconstrictor prevents lidocaine-induced arrhythmias; it does not treat one."}],
 teach:"Lidocaine numbs the area. Adding a powerful vasoconstrictor (cocaine, or epinephrine/norepinephrine) constricts local vessels, which decreases bleeding during suturing and keeps lidocaine from being distributed systemically, where it could reach the heart and cause arrhythmias.",
 quote:"But the reason why we can add that cocaine or powerful vasoconstrictor is that we don't want it to become systemic because the lidocaine can stop your heart. So you want to stay local. So by vasoconstricting those blood vessels, you decrease the bleeding while you're suturing, and also you prevent the systemic distribution of our drug into the heart.",
 note:"A use, which he generally does not test (10/5: “I'm not testing you on the use”), so marked low yield. The drug list instead says cocaine is “used with lidocaine to control arrythmias (Na+ channel blocker)”; he said the vasoconstrictor keeps lidocaine away from the heart to prevent arrhythmias. Keyed to the transcript (see DL2 conflicts).",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 10; transcript 10/6"},

{id:"L10-023", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"indirect", skill:"tell",
 concept:"amphetamine-primary-moa", tags:[], source:"both",
 stem:"What is the primary mechanism of action of dextroamphetamine and methylphenidate?",
 options:[
  {t:"Presynaptic catecholamine release", correct:true, why:"Primary action: release of norepinephrine, dopamine and serotonin."},
  {t:"Fully block the norepinephrine transporter", correct:false, why:"That is cocaine; amphetamines are only weak reuptake inhibitors."},
  {t:"Irreversibly block monoamine oxidase B", correct:false, why:"That is selegiline."},
  {t:"Directly activate α1 receptors", correct:false, why:"That is phenylephrine; amphetamines do not typically bind and activate the receptors."},
  {t:"Directly activate α2 receptors", correct:false, why:"That is clonidine."}],
 teach:"The amphetamine-like stimulants (dextroamphetamine, amphetamine, lisdexamfetamine, methylphenidate, dexmethylphenidate) work mainly by stimulating presynaptic release of norepinephrine (NE), dopamine (DA) and serotonin (5HT). Secondarily they moderately decrease reuptake and block monoamine oxidase (MAO).",
 quote:"So they do not work typically by binding and activating the receptors. They are indirectly enhancing the release, so they stimulate the release of catecholamine, such as norepinephrine, serotonin, and dopamine, OK?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 11; transcript 10/6"},

{id:"L10-024", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"indirect", skill:"recall", multi:true,
 concept:"amphetamine-secondary-moa", tags:[], source:"both",
 stem:"Besides stimulating catecholamine release, which weaker actions do the amphetamine-like stimulants have? Select all that apply.",
 options:[
  {t:"Decrease reuptake of norepinephrine", correct:true, why:"Second, moderate action: decrease reuptake (weak NET inhibition)."},
  {t:"Block monoamine oxidase (MAO)", correct:true, why:"Second, moderate action: blocks MAO, the enzyme that breaks catecholamines down."},
  {t:"Activate presynaptic α2", correct:false, why:"Activating α2 would lower release; that is clonidine."},
  {t:"Block postsynaptic α1", correct:false, why:"Blocking α1 is prazosin."},
  {t:"Activate COMT", correct:false, why:"No drug in this lecture activates COMT."}],
 teach:"Primary mechanism: release of norepinephrine, dopamine and serotonin. Secondary, weak-to-moderate mechanisms: inhibition of reuptake and inhibition of monoamine oxidase (MAO). The drug touches several steps of norepinephrine handling.",
 quote:"You also have a secondary effect of being a very weaker inhibitor of the reuptake and the enzyme that breaks down catecholamine. So it has multiple mechanisms of action. The primary is releasing of norepinephrine with a very weak to moderate inhibition of the reuptake as well as the breakdown of catecholamines.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 11; transcript 10/6"},

{id:"L10-025", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"indirect", skill:"apply", multi:true,
 concept:"stimulant-effects", tags:[], source:"both",
 stem:"A patient takes increasing doses of dextroamphetamine. Which effects are expected? Select all that apply.",
 options:[
  {t:"Decreased appetite", correct:true, why:"Central effect on the slide: decreased sleep and appetite."},
  {t:"Tremor", correct:true, why:"Peripheral effect; he ties it to activation of β2."},
  {t:"Increased heart rate", correct:true, why:"Increased sympathetic outflow raises heart rate and blood pressure."},
  {t:"Sedation", correct:false, why:"Stimulants increase energy and decrease sleep."},
  {t:"Bradycardia", correct:false, why:"More sympathetic tone raises, not lowers, heart rate."}],
 teach:"Stimulants raise sympathetic outflow. Central: mood, more energy, less sleep and appetite, better focus and alertness, faster breathing. Peripheral: tremor, sweating (diaphoresis), cardiovascular effects (higher blood pressure and heart rate) and hyperthermia. Side effects grow with dose.",
 quote:"So these drugs are gonna increase the sympathetic outflow as a side effect. So it may increase your blood pressure, increase your, your heart rate, it cause tremors, right, because you're activating those beta 2s",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 12; transcript 10/6"},

{id:"L10-026", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"indirect", skill:"apply",
 concept:"stimulant-caffeine-ddi", tags:[], source:"transcript",
 stem:"A student taking a prescribed stimulant drinks several caffeinated energy shots while studying overnight. Which drug–drug interaction is most likely?",
 options:[
  {t:"Additive stimulant effects", correct:true, why:"Caffeine is also a stimulant: two stimulants on board add up and push the dose toward side effects such as arrhythmias."},
  {t:"Caffeine cancels the stimulant", correct:false, why:"Both drugs stimulate; their effects add."},
  {t:"No interaction", correct:false, why:"Two stimulants together have an additive effect."},
  {t:"Sedation from both drugs", correct:false, why:"Neither drug sedates."}],
 teach:"Caffeine is a stimulant, so combining it with an amphetamine-like drug is additive: the therapeutic window shrinks toward the side-effect end. His example was a student who ended up in the emergency room with arrhythmias after drinking energy shots all night before an exam.",
 quote:"Caffeine is a stimulant. So if you are taking a stimulant and then you add caffeine and Red Bull in 5 minutes, you know, whatever crap that is, uh, you're just compounding. ... She was in the ER because she was having arrhythmias.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 12; transcript 10/6"},

/* ---------------- MAO inhibitors (slides 13–15) ---------------- */
{id:"L10-027", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"mao", skill:"tell",
 concept:"mao-a-vs-b-location", tags:[], source:"both",
 stem:"Which statement about the two monoamine oxidase (MAO) subtypes is CORRECT?",
 options:[
  {t:"MAO-B is mainly in the brain", correct:true, why:"MAO-B is present in the CNS striatum and breaks down dopamine (“B for brain”)."},
  {t:"MAO-A is only in the brain", correct:false, why:"MAO-A is in the brain, liver and gut; he stresses the gut."},
  {t:"MAO-B is mainly in the gut", correct:false, why:"The gut enzyme is MAO-A."},
  {t:"MAO-B breaks down acetylcholine", correct:false, why:"MAO breaks down catecholamines (norepinephrine, dopamine), not acetylcholine."}],
 teach:"Both monoamine oxidase (MAO) subtypes break down catecholamines. MAO-A is in the brain, liver and gastrointestinal tract and breaks down norepinephrine and dopamine; MAO-B is in the central nervous system (striatum) and breaks down dopamine. His memory aid: B for brain.",
 quote:"So the older drugs. They are less selective, so they can inhibit both enzymes, the MAOA that is in the gut, as well as the MAOB that is for the brain. So if you're not sure, think about B for brain",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 13; transcript 10/6"},

{id:"L10-028", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"mao", skill:"tell",
 concept:"phenelzine-vs-selegiline", tags:[], source:"both",
 stem:"Which pairing of drug and target is CORRECT?",
 options:[
  {t:"Phenelzine: MAO-A and MAO-B", correct:true, why:"Phenelzine is the non-selective MAO inhibitor: it blocks both monoamine oxidase (MAO) subtypes."},
  {t:"Selegiline: MAO-A and MAO-B", correct:false, why:"Selegiline is selective for MAO-B (at low doses)."},
  {t:"Phenelzine: MAO-B only", correct:false, why:"Phenelzine is non-selective."},
  {t:"Selegiline: norepinephrine transporter", correct:false, why:"Blocking the norepinephrine transporter is cocaine."},
  {t:"Phenelzine: COMT", correct:false, why:"No drug in this lecture blocks catechol-O-methyltransferase (COMT)."}],
 teach:"Phenelzine: non-selective inhibitor of monoamine oxidase A and B (MAO-A and MAO-B), irreversible. Selegiline (low doses): selective MAO-B inhibitor, irreversible. Both raise catecholamines by blocking their breakdown.",
 quote:"There are MOA inhibitors. We have the non-selectives, and I picked phenelzine as our prototypical drug. ... And then we have a better MAO inhibitor, uh, selegiline, which is selective to the MAOB.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 14; transcript 10/6"},

{id:"L10-029", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"mao", skill:"recall",
 concept:"maoi-irreversible", tags:[], source:"both",
 stem:"How do phenelzine and selegiline bind monoamine oxidase?",
 options:[
  {t:"Irreversibly", correct:true, why:"Both are irreversible antagonists: once bound, the enzyme is out and the body has to make new ones."},
  {t:"Reversibly and competitively", correct:false, why:"The slide marks both as irreversible antagonists."},
  {t:"As partial agonists", correct:false, why:"They block (antagonize) the enzyme; they do not activate it."},
  {t:"Phenelzine reversibly, selegiline irreversibly", correct:false, why:"Both are irreversible."}],
 teach:"Phenelzine and selegiline are both irreversible antagonists of monoamine oxidase (MAO). Once the drug binds, that enzyme molecule no longer works; activity returns only when the body makes new enzyme.",
 quote:"This drug is an irreversible antagonist, which means is, once you bind that enzyme, your body has to make new ones. That one is, is toasted, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 14; transcript 10/6"},

{id:"L10-030", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"mao", skill:"apply",
 concept:"cheese-effect-crisis", tags:[], source:"both",
 stem:"A patient taking phenelzine eats aged cheese and drinks wine at a party. Which is most likely?",
 options:[
  {t:"Hypertensive crisis", correct:true, why:"Non-selective MAO inhibition leaves dietary tyramine unprocessed: the “cheese effect”, a hypertensive crisis."},
  {t:"Severe hypotension", correct:false, why:"The tyramine reaction raises blood pressure."},
  {t:"Bradycardia from vagal tone", correct:false, why:"The reaction is sympathetic and hypertensive."},
  {t:"No reaction", correct:false, why:"Fermented foods are high in tyramine, which the patient cannot break down."},
  {t:"Sedation", correct:false, why:"The reaction is a hypertensive crisis; his colleague passed out from the very high pressure."}],
 teach:"A non-selective monoamine oxidase (MAO) inhibitor blocks MAO in the gut as well as the brain, so dietary tyramine from fermented foods (cheese, bread, wine) is not broken down. The result is a hypertensive crisis, the “cheese effect”. His example: a professor on the drug ate cheese at a party and left in an ambulance.",
 quote:"You cannot eat anything that is fermented. Like cheese and bread and wine, all of those are off the plate, right? And the reason being is because you have the inability to break down that dietary tyramine that you're consuming, and those fermented foods have high levels of tyramine, and that can cause what is called a hypertensive crisis.",
 reading:[{"src":"Katzung 16e, Ch. 9","sec":"Specific Sympathomimetic Drugs — Tyramine","t":"In patients treated with MAO inhibitors, particularly those inhibiting the MAO-A isoform, the sympathomimetic effect of tyramine can be greatly intensified, with marked increases in blood pressure. This follows from greater bioavailability of tyramine and larger neuronal stores of catecholamines, so these patients should avoid tyramine-containing foods such as aged cheese, cured meats and pickled food."}],
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 15; transcript 10/6"},

{id:"L10-031", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"mao", skill:"tell",
 concept:"no-cheese-effect-mao-b", tags:[], source:"both",
 stem:"Which monoamine oxidase inhibitor carries no “cheese effect” with dietary tyramine?",
 options:[
  {t:"Selegiline", correct:true, why:"Selective MAO-B inhibition acts in the brain only, so gut tyramine is still broken down: no cheese effect."},
  {t:"Phenelzine", correct:false, why:"Phenelzine also blocks gut MAO-A, so tyramine causes a hypertensive crisis."},
  {t:"Both phenelzine and selegiline", correct:false, why:"Only the non-selective drug causes the cheese effect."},
  {t:"Neither drug", correct:false, why:"Selegiline is the one without it."}],
 teach:"No cheese effect for selective MAO-B inhibitors: selegiline blocks monoamine oxidase B in the brain and leaves gut MAO-A free to break down dietary tyramine. That is why, money aside, he would choose the selective MAO-B drug.",
 quote:"So, if we need to choose one and your patient, money is not an issue, I'd rather pick the selective MOAB because that only blocks in the brain and you don't have to worry about the cheese effect associated with your patients, OK?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 15; transcript 10/6"},

{id:"L10-032", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"mao", skill:"apply",
 concept:"maoi-more-ne-stored", tags:[], source:"both",
 stem:"Why does blocking monoamine oxidase (MAO) increase the amount of norepinephrine released?",
 options:[
  {t:"More is stored in vesicles", correct:true, why:"With less breakdown, more norepinephrine is stored, so each release puts more into the synapse."},
  {t:"The α2 receptor is blocked", correct:false, why:"Blocking α2 is mirtazapine, not an MAO inhibitor."},
  {t:"The transporter pumps more out", correct:false, why:"MAO inhibitors act on the breakdown enzyme, not the transporter."},
  {t:"Tyrosine synthesis stops", correct:false, why:"Synthesis continues; it is breakdown that is reduced."}],
 teach:"Monoamine oxidase breaks down norepinephrine, dopamine and epinephrine. Blocking it means more norepinephrine is stored in the vesicles, so more is released into the synapse. Raising brain catecholamines this way is how the MAO inhibitors, the oldest antidepressants, decrease depression.",
 quote:"As such, if I block the enzyme, I can make an assumption that I'm gonna have a lot more norepinephrine being stored in the vesicles, which means that when I release, I have more norepinephrine being released.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 13–14; transcript 10/6"},

/* ---------------- α1: sites, phenylephrine, oxymetazoline (slides 16–19) ---------------- */
{id:"L10-033", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1", skill:"recall", multi:true,
 concept:"alpha1-sites", tags:[], source:"both",
 stem:"Which are major sites of action of α1 receptors? Select all that apply.",
 options:[
  {t:"Eye (pupil)", correct:true, why:"“I see”: α1 dilates the pupil."},
  {t:"Blood vessels of the nose", correct:true, why:"“and smell”: α1 constricts nasal vessels (decongestion)."},
  {t:"Arteries and veins", correct:true, why:"“bloody”: α1 sets afterload and preload."},
  {t:"Urethra (bladder sphincter, prostate vessels)", correct:true, why:"“urine”: α1 on the sphincter and the blood vessels around the prostate."},
  {t:"Sinoatrial node", correct:false, why:"The heart is run by β1."},
  {t:"Bronchial smooth muscle", correct:false, why:"The lungs have M3 (parasympathetic only) and β2; α1 is not listed there."}],
 teach:"His memory aid for α1 sites: “I see and smell bloody urine”: eye (pupil dilation), nose (nasal blood vessels), blood vessels (systemic arteries for afterload, veins for preload) and urethra (bladder sphincter and the blood vessels of the prostate). α1 is Gq: phospholipase C, IP3, more Ca++.",
 quote:"So, the way I remember when I was in school is I see and smell bloody urine, right? ... So think about, uh, those sites as our major sites of action.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 16–17; transcript 10/6"},

{id:"L10-034", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1", skill:"apply",
 concept:"phenylephrine-eye", tags:[], source:"both",
 stem:"Phenylephrine drops are placed in the eye. Which effect is most likely?",
 options:[
  {t:"Mydriasis", correct:true, why:"α1 on the radial (dilator) fibers contracts and pulls the pupil open: pupil dilation."},
  {t:"Miosis", correct:false, why:"Miosis is the M3 effect on the circular muscle."},
  {t:"Lacrimation", correct:false, why:"Lacrimation is a muscarinic (DUMBBELSS) effect."},
  {t:"No effect on the pupil", correct:false, why:"α1 is one of the two receptors controlling pupil size."}],
 teach:"The pupil has dual innervation: M3 on the circular muscle constricts it, α1 on the radial muscle dilates it. Phenylephrine, a selective α1 agonist (Gq, ↑Ca++), contracts the radial fibers and causes mydriasis (pupil dilation). Burning and blurred vision are its eye side effects.",
 quote:"So if activate the alpha 1 is in the eyes, they are in these transverse fibers, so we're going to pull them apart by constricting and you're going to get pupil dilation, also known as madriasis, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 18; transcript 10/6"},

{id:"L10-035", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1", skill:"apply",
 concept:"phenylephrine-preload-afterload", tags:[], source:"both",
 stem:"Phenylephrine reaches the systemic arteries and veins. Which change is most likely?",
 options:[
  {t:"Preload and afterload both rise", correct:true, why:"α1 in arterial smooth muscle raises afterload; α1 in venous smooth muscle raises preload; blood pressure goes up."},
  {t:"Preload and afterload both fall", correct:false, why:"That is what an α1 antagonist (prazosin) does."},
  {t:"Only preload rises", correct:false, why:"The arteries also constrict, so afterload rises too."},
  {t:"Only afterload rises", correct:false, why:"The veins also constrict, so preload rises too."}],
 teach:"Phenylephrine activates α1 (Gq, ↑Ca++) in vascular smooth muscle: arterial constriction raises afterload, venous constriction raises preload, and blood pressure rises. That is why it is used carefully in patients with hypertension; long use can itself keep blood pressure high.",
 quote:"So increase calcium. In the blood vessels, it's going to increase both preload and after load, so it's going to increase your blood pressure. And we're going to be careful with patients with hypertension.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 18; transcript 10/6"},

{id:"L10-036", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1", skill:"recall", multi:true,
 concept:"phenylephrine-adr", tags:[], source:"both",
 stem:"Which adverse effects of phenylephrine should a patient be warned about? Select all that apply.",
 options:[
  {t:"Burning", correct:true, why:"Listed ADR; anything put in the eye or nose can burn."},
  {t:"Rebound congestion", correct:true, why:"Listed ADR; the box says not to use for more than 3 days."},
  {t:"Blurred vision", correct:true, why:"Listed ADR (eye use)."},
  {t:"Higher blood pressure", correct:true, why:"Careful in patients with hypertension: α1 raises preload and afterload."},
  {t:"Dry mouth", correct:false, why:"Dry mouth is the complaint with clonidine."},
  {t:"Orthostatic hypotension", correct:false, why:"That is the α1 antagonists (prazosin); phenylephrine raises pressure."}],
 teach:"Phenylephrine's adverse reactions: burning, blurred vision and rebound congestion (do not use for more than 3 days), and higher blood pressure, so care is needed in patients with hypertension. Each follows from α1 activation at its sites.",
 quote:"And then there are some side effects associated with that, which of course if you put anything in the eye, it's going to cause some burning, blurred vision, uh, you may have rebound congestion. As such, if you read in the back of the box, it tells you you don't use for more than 3 days.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 18; transcript 10/6"},

{id:"L10-037", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1", skill:"tell",
 concept:"oxymetazoline-less-constriction", tags:[], source:"both",
 stem:"Oxymetazoline is used as a nasal decongestant. Why does it constrict nasal vessels less than expected from its α1 action?",
 options:[
  {t:"It also activates α2 (Gi)", correct:true, why:"It is non-selective: α1 (Gq) constricts, α2 (Gi) relaxes, so the two partly offset."},
  {t:"It blocks α1 receptors", correct:false, why:"Oxymetazoline is an agonist, not an antagonist."},
  {t:"It activates β2 receptors", correct:false, why:"Its receptors are α1 and α2."},
  {t:"It acts indirectly through release", correct:false, why:"It is a direct agonist."}],
 teach:"Oxymetazoline is a non-selective α1 and α2 agonist acting on nasal smooth muscle. α1 (Gq) constricts and α2 (Gi) relaxes, so the two receptors “play with each other” and the vessels constrict less than with a pure α1 agonist.",
 quote:"This is a non-selective alpha 1, alpha 2, so they're gonna kind of, you know, play with each other. Remember, alpha 1s are Q constriction. Alpha 2 is I relaxing, right? So you don't have as much constriction of those blood vessels that you would expect.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 19; transcript 10/6"},

{id:"L10-038", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1", skill:"tell",
 concept:"alpha1-vs-alpha2-messenger", tags:["in-class"], source:"both",
 stem:"Which statement about α1 and α2 activation is CORRECT?",
 options:[
  {t:"α1 raises Ca++; α2 lowers cAMP", correct:true, why:"α1 is Gq (calcium goes up, excitation); α2 is Gi (cAMP goes down, inhibition)."},
  {t:"α1 lowers cAMP; α2 raises Ca++", correct:false, why:"The G proteins are swapped."},
  {t:"Both raise cAMP", correct:false, why:"Only β receptors raise cAMP."},
  {t:"Both are Gq", correct:false, why:"α2 is Gi."}],
 teach:"A student asked why α1 and α2 agonists seem to contradict each other. They do: α1 is Gαq and excitatory (Ca++ up, constriction), α2 is Gαi and inhibitory (cyclic AMP, cAMP, down; relaxation and less norepinephrine release).",
 quote:"They do. Because alpha 1 agonist constrict, alpha 2 relax because one is exciting, the other one is inhibiting. Remember, alpha 2 is G alpha I, alpha 1 is G alpha Q. So calcium goes up with alpha 1s, scamp goes down with the alpha 2s.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 17, 21; transcript 10/6"},

/* ---------------- α2 and clonidine (slides 20–24, 26) ---------------- */
{id:"L10-039", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a2", skill:"recall",
 concept:"alpha2-location-cns", tags:[], source:"both",
 stem:"Where are the α2 receptors that clonidine acts on primarily located?",
 options:[
  {t:"Nerve endings in the CNS", correct:true, why:"α2 is primarily in the central nervous system (CNS), presynaptically, modulating norepinephrine release."},
  {t:"Ventricular muscle of the heart", correct:false, why:"The heart is run by β1."},
  {t:"Detrusor muscle of the bladder", correct:false, why:"The bladder's adrenergic receptor stressed is β3."},
  {t:"Bronchial smooth muscle", correct:false, why:"The lungs have M3 and β2."},
  {t:"Radial muscle of the iris", correct:false, why:"The iris dilator is α1."}],
 teach:"α2 receptors are located at nerve endings, primarily in the central nervous system (CNS), and also in the gastrointestinal tract and on pancreatic β cells. Presynaptically they modulate how much norepinephrine is released; they are Gi (less cAMP), so they are inhibitory.",
 quote:"So alpha chews are going to be primary locations going to be the CNS. That's what we're going to be thinking about those guys. They are going to be pre-synaptically, so they're modulating the levels of norepinephrine release.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 20–21; transcript 10/6"},

{id:"L10-040", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a2", skill:"tell",
 concept:"clonidine-agonist-inhibits", tags:[], source:"both",
 stem:"Clonidine is an agonist, yet it lowers sympathetic activity. Which explains this?",
 options:[
  {t:"It activates an inhibitory Gi receptor", correct:true, why:"α2 is Gi: activating it suppresses norepinephrine release, so the sympathetic system is turned down."},
  {t:"It blocks α1 receptors", correct:false, why:"Blocking α1 is prazosin; clonidine activates α2."},
  {t:"It blocks the norepinephrine transporter", correct:false, why:"That is cocaine, which raises sympathetic activity."},
  {t:"It irreversibly blocks MAO", correct:false, why:"That is phenelzine and selegiline, which raise norepinephrine."}],
 teach:"Clonidine is a selective α2 agonist. Because α2 is coupled to Gαi, activating it is inhibitory: less cAMP, less norepinephrine release and less sympathetic outflow. It behaves like an antagonist of the sympathetic system but is an agonist at its receptor.",
 quote:"So clonidine is an agonist that activates the inhibitory pathway. So he's behaving like an antagonist, but he's actually an agonist.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 21, 23–24; transcript 10/6"},

{id:"L10-041", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a2", skill:"apply", multi:true,
 concept:"clonidine-effects", tags:[], source:"both",
 stem:"Which effects does clonidine produce? Select all that apply.",
 options:[
  {t:"Decreased sympathetic tone", correct:true, why:"Central α2 (Gi) activation suppresses norepinephrine release."},
  {t:"Vasodilation", correct:true, why:"Less sympathetic input to α1 in arteries and veins: they relax (less afterload and preload)."},
  {t:"Bradycardia", correct:true, why:"Less sympathetic drive to the heart lowers heart rate and contractile force."},
  {t:"Tachycardia", correct:false, why:"Heart rate falls, not rises."},
  {t:"More norepinephrine release", correct:false, why:"That is mirtazapine (α2 antagonist)."},
  {t:"Higher preload", correct:false, why:"Venous sympathetic tone falls, so preload falls."}],
 teach:"Clonidine's effects are decrease of sympathetic tone, vasodilation and bradycardia. Suppressing sympathetic input to the heart lowers heart rate and force (cardiac output); to the arteries, afterload; to the veins, preload.",
 quote:"So, if I suppress sympathetic to the heart, I'm going to decrease the heart rate and the contractile force. If I suppress the sympathetics to the arteries, I'm going to decrease the afterload. If I suppress the sympathetics to the veins, I'm going to decrease the preload, plus everything else.",
 reading:[{"src":"Katzung 16e, Ch. 9","sec":"Cardiovascular System — Blood Vessels","t":"Selective α2 agonists such as clonidine act in the central nervous system to reduce sympathetic activity and are therefore called central sympatholytics; they are used to treat hypertension."}],
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 23–24; transcript 10/6"},

{id:"L10-042", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a2", skill:"apply",
 concept:"clonidine-dry-mouth", tags:["in-class"], source:"both",
 stem:"Which is one of the major complaints of patients taking clonidine?",
 options:[
  {t:"Dry mouth", correct:true, why:"Sympathetic input to the salivary glands is suppressed; about 40% of patients complain of it."},
  {t:"Diarrhea", correct:false, why:"Clonidine causes constipation (less acetylcholine release in the gut)."},
  {t:"Tachycardia", correct:false, why:"Clonidine causes bradycardia."},
  {t:"Insomnia", correct:false, why:"Clonidine causes sedation."},
  {t:"Rebound nasal congestion", correct:false, why:"That is phenylephrine."}],
 teach:"Clonidine suppresses sympathetic outflow everywhere, including to the salivary glands, so dry mouth (“cotton mouth”) is very common, in about 40% of patients. The effect is predicted from the mechanism of action, not memorized.",
 quote:"Do you know what is one of the major complaints of patients taking clonidine? Dry mouth. Because you suppress the sympathetic to the salivary gland, and they're going to get dry mouth. About 40% of them complain of dry mouth.",
 reading:[{"src":"Katzung 16e, Ch. 9","sec":"Other Organ Systems","t":"The salivary glands contain adrenoceptors that regulate secretion of amylase and water, and α2 agonists such as clonidine produce dry mouth; central nervous system effects are likely responsible for this side effect."}],
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 26; transcript 10/6"},

{id:"L10-043", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a2", skill:"apply",
 concept:"clonidine-withdrawal-crisis", tags:["exam-cue"], source:"both",
 stem:"A patient stops clonidine abruptly after months of use. Which is most likely, and why?",
 options:[
  {t:"Hypertensive crisis from up-regulated receptors", correct:true, why:"Chronic suppression of sympathetic tone makes the body add receptors; without the drug, norepinephrine floods them."},
  {t:"Hypotension from down-regulated α1 receptors", correct:false, why:"Chronic suppression up-regulates receptors, and the result is high, not low, pressure."},
  {t:"Bradycardia from extra parasympathetic tone", correct:false, why:"Stopping the drug removes the brake on the sympathetic system."},
  {t:"Bronchoconstriction from unopposed parasympathetic tone", correct:false, why:"Withdrawal unleashes sympathetic activity; it does not constrict the airways."}],
 teach:"Months of suppressed sympathetic tone cause receptor up-regulation. Stopping clonidine cold turkey leaves many receptors and a surge of norepinephrine: a hypertensive crisis. His major counseling point: patients must be weaned off.",
 quote:"We're gonna make more receptors, right? We're gonna cause up regulation. So what is the one education point that you have to make to your patients? You got to wean yourself off because if you go cold turkey, you got all these receptors, now norepinephrine is flowing like there's no tomorrow, and you go into a hypertensive crisis, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 26; transcript 10/6"},

{id:"L10-044", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a2", skill:"apply",
 concept:"clonidine-constipation", tags:["in-class"], source:"both",
 stem:"Why does clonidine cause constipation?",
 options:[
  {t:"Less acetylcholine reaches gut M3", correct:true, why:"α2 on the cholinergic nerve slows acetylcholine secretion, so M3 is not activated and motility and tone fall."},
  {t:"It blocks gut M3 receptors", correct:false, why:"Clonidine is not a muscarinic antagonist; it reduces acetylcholine release."},
  {t:"It activates gut α1 receptors", correct:false, why:"Clonidine is selective for α2."},
  {t:"It raises norepinephrine release in the gut", correct:false, why:"Clonidine lowers norepinephrine release."}],
 teach:"The gut is one of the dual-innervation exceptions: α2 receptors slow the release of acetylcholine. Activating them with clonidine means less acetylcholine, no M3 activation, less motility and tone, and constipation.",
 quote:"What would you predict that would happen in the gut? Well, it was kind of list their constipation, right? But why? Because you're slowing down. Because you're slowing down the secretion of acetylcholine, this is one of our dual innervation exception, right? That by suppressing acetylcholine release, we don't activate the M3s",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 26; transcript 10/6"},

{id:"L10-045", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a2", skill:"recall", multi:true,
 concept:"clonidine-adr", tags:[], source:"both",
 stem:"Which adverse effects are expected with clonidine? Select all that apply.",
 options:[
  {t:"Sedation", correct:true, why:"Central nervous system inhibition; CNS side effects are the most common."},
  {t:"Hypotension", correct:true, why:"Too much of the wanted effect; with bradycardia, it raises the risk of falls."},
  {t:"Sexual dysfunction", correct:true, why:"Sympathetic suppressed while parasympathetic is left working (“all show and no go”)."},
  {t:"Nightmares and depression", correct:true, why:"Listed CNS side effects."},
  {t:"Tachycardia", correct:false, why:"Clonidine causes bradycardia."},
  {t:"Diarrhea", correct:false, why:"Clonidine causes constipation."}],
 teach:"Clonidine's adverse reactions: CNS effects (sedation, nightmares, depression), dry mouth and constipation, hypotension and bradycardia (risk of falls), sexual dysfunction, and a hypertensive crisis on abrupt withdrawal from receptor up-regulation.",
 quote:"So when it comes to side effects, the most common side effects with this drug can be sedation because you're inhibiting the CNS. Patients may complain of nightmares and maybe depression. Dry mouth is very common. ... so hypertension and bradycardia can be severe if the dose is too high. It may cause sexual dysfunction.",
 note:"The transcript has “hypertension and bradycardia” where the slide says “Hypotension & Bradycardia”; in context (“lower blood pressure, lower heart rate”) it is hypotension. Keyed to the slide.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 26; transcript 10/6"},

{id:"L10-046", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a2", skill:"tell",
 concept:"idine-osin-names", tags:[], source:"both",
 stem:"A drug name ends in “-idine” (for example, brimonidine or tizanidine). Which mechanism should you predict?",
 options:[
  {t:"α2 agonist", correct:true, why:"Most drugs ending in -idine are α2 agonists like clonidine."},
  {t:"Selective α1 antagonist", correct:false, why:"The α1 antagonists end in -osin (prazosin, terazosin)."},
  {t:"Muscarinic antagonist", correct:false, why:"Atropine-like drugs carry “trop”."},
  {t:"Cholinesterase inhibitor", correct:false, why:"Those end in -stigmine."},
  {t:"α1 agonist", correct:false, why:"Phenylephrine “sounds like” epinephrine and norepinephrine."}],
 teach:"Name cues: -idine (clonidine, brimonidine, tizanidine) → α2 agonist; -osin (prazosin, terazosin, doxazosin) → selective α1 antagonist; phenylephrine sounds like epinephrine and norepinephrine → α1 agonist. For the exam he focuses on clonidine as the prototype α2 agonist.",
 quote:"It doesn't matter if it's clonidine or brimonidine or, you know, tizanidine. They all have this edine with it, and it's gonna tell you where they're gonna fall, OK? So for our purpose on exam one, we're gonna focus on clonidine because that's our prototypical drug.",
 note:"“exam one” in the quote is a slip for Exam 2, the exam this lecture belongs to.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 17, 22; transcript 10/6"},

{id:"L10-047", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a2", skill:"apply",
 concept:"clonidine-everywhere", tags:["in-class"], source:"both",
 stem:"How can clonidine lower blood pressure and cause dry mouth at the same time?",
 options:[
  {t:"It lowers sympathetic outflow", correct:true, why:"One central action reduces sympathetic input to every organ: salivary glands, heart, arteries and veins."},
  {t:"It blocks M3 in glands and vessels", correct:false, why:"Clonidine is not a muscarinic antagonist."},
  {t:"It activates α1 in glands and vessels", correct:false, why:"Activating α1 would constrict vessels and raise pressure."},
  {t:"It raises norepinephrine everywhere", correct:false, why:"It lowers norepinephrine release."}],
 teach:"A student asked how clonidine can do both. Answer: the sympathetic system is one-to-many, so suppressing it centrally suppresses salivation, pupil dilation, heart rate and force, and vessel tone at once. The arteries and veins have only sympathetic innervation, so without it they relax and blood pressure falls.",
 quote:"Because it's suppressed sympathetic to all over the body. So remember the sympathetic is one too many, right? So by suppressing the sympathetic outflow, you're gonna suppress the salivation. ... There's only sympathetic to the arteries and the veins, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 23–24, 26; transcript 10/6"},

/* ---------------- α antagonists, prazosin (slides 27–30) ---------------- */
{id:"L10-048", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1ant", skill:"recall",
 concept:"alpha-blocker-irreversible", tags:[], source:"both",
 stem:"Which α-receptor antagonist is irreversible?",
 options:[
  {t:"Phenoxybenzamine", correct:true, why:"Phenoxybenzamine is the non-selective (α1 and α2) irreversible antagonist; all the others are reversible."},
  {t:"Prazosin", correct:false, why:"Prazosin is a reversible, selective α1 antagonist."},
  {t:"Terazosin", correct:false, why:"An -osin: reversible, selective α1."},
  {t:"None; all are reversible", correct:false, why:"Phenoxybenzamine is the irreversible one."},
  {t:"Mirtazapine", correct:false, why:"Mirtazapine is a reversible α2 (and H1, muscarinic, α1) antagonist."}],
 teach:"The α-antagonist table: irreversible, non-selective α1 and α2: phenoxybenzamine. Reversible, α1 selective: prazosin, terazosin, doxazosin, alfuzosin, tamsulosin, silodosin (the -osins). Reversible, α2 non-selective: mirtazapine (α2, H1, muscarinic, α1).",
 quote:"So all the other drugs are gonna be reversible and then we have here alpha-1 selectives all the zosin or Osin, right?",
 note:"He described phenoxybenzamine aloud (“a non-selective alpha 1 and alpha 2 irreversible antagonists”) while answering a student question, then said “we're gonna get a little bit ahead of us, so just wait”; its own slides (34–38) were not taught on 10/6.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 27; transcript 10/6"},

{id:"L10-049", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1ant", skill:"tell",
 concept:"prazosin-moa", tags:["exam-cue"], source:"both",
 stem:"Which of the following describes prazosin?",
 options:[
  {t:"Reversible, selective α1 antagonist", correct:true, why:"Prazosin is about a thousandfold more selective for α1 and reversibly blocks catecholamines from binding it."},
  {t:"Irreversible α1 and α2 antagonist", correct:false, why:"That is phenoxybenzamine."},
  {t:"Selective α2 antagonist", correct:false, why:"The α2 antagonist is mirtazapine, and it is not selective."},
  {t:"Selective α1 agonist", correct:false, why:"That is phenylephrine."},
  {t:"Reversible, non-selective α antagonist", correct:false, why:"Prazosin is selective for α1."}],
 teach:"Prazosin is a reversible, selective α1 antagonist (about 1000-fold): it blocks norepinephrine and epinephrine from binding α1. Every drug ending in -osin (terazosin, doxazosin, tamsulosin, silodosin) is the same for the exam: a selective α1 antagonist acting at the α1 sites (eye, nose, blood vessels, urethra).",
 quote:"For our exam purpose, all I need to know if you see a drug with OC is a selective alpha-1 antagonist. And where the alpha ones are in the nose, in the eye, in the blood vessels, in the urethra, OK? Those are gonna be your sites of actions.",
 reading:[{"src":"Katzung 16e, Ch. 10","sec":"Specific Agents — Prazosin, terazosin, doxazosin","t":"Prazosin, terazosin and doxazosin are highly selective for α1 receptors. They dilate both arterial and venous smooth muscle, and smooth muscle in the prostate, by blocking α1 receptors; they are used as second-line treatment for hypertension and for urinary symptoms of benign prostatic hyperplasia."}],
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 27–28; transcript 10/6"},

{id:"L10-050", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1ant", skill:"apply",
 concept:"alpha1-block-vasodilation", tags:[], source:"both",
 stem:"How does blocking α1 receptors lower blood pressure in a patient with hypertension?",
 options:[
  {t:"Less Gq signaling → less Ca++ → vasodilation", correct:true, why:"Norepinephrine cannot bind α1, so less Gq, PLC and IP3, less calcium, and the vessels relax: lower TPR."},
  {t:"More Gi signaling → less cAMP → vasodilation", correct:false, why:"That describes α2 activation, not α1 blockade."},
  {t:"Less β1 signaling → lower heart rate", correct:false, why:"Prazosin does not block β1; heart rate actually rises by reflex."},
  {t:"More nitric oxide → vasodilation", correct:false, why:"Nitric oxide comes from endothelial M3; α1 block works on smooth-muscle calcium."}],
 teach:"In the arteries and veins, α1 is the main receptor and the sympathetic system the only (and so the primary physiological) tone: they are always constricting through Gq → PLC → IP3 → Ca++. Blocking α1 lowers that calcium, the vessels dilate, and systemic vascular resistance (total peripheral resistance, TPR) falls.",
 quote:"if I block it, norepinephrine can't bind to that receptor. As such, I have less GQ. If I have less GQ, I'm gonna have less calcium, and if I have less calcium, I have more vasodilation.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 29; transcript 10/6"},

{id:"L10-051", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1ant", skill:"apply",
 concept:"alpha1-block-vein-orthostatic", tags:["in-class"], source:"both",
 stem:"What would you think would be a side effect of taking a drug that antagonizes the alpha one receptor in the vein?",
 options:[
  {t:"Orthostatic hypotension and syncope", correct:true, why:"Relaxed veins let blood pool in the feet; it does not reach the heart or brain, and the patient falls on standing."},
  {t:"Rebound nasal congestion", correct:false, why:"That is phenylephrine, an α1 agonist."},
  {t:"Bradycardia from a baroreceptor reflex", correct:false, why:"Falling pressure raises, not lowers, heart rate by reflex."},
  {t:"Bronchial constriction", correct:false, why:"α1 is not the airway receptor."},
  {t:"Higher preload", correct:false, why:"Venous relaxation lowers preload."}],
 teach:"His spoken question. First ask what the vein does: return blood to the heart (preload). An α1 antagonist relaxes venous tone, blood pools in the feet, does not reach the heart or the brain, and the patient falls: orthostatic hypotension and syncope. The side effect is predicted from mechanism and site, not memorized.",
 quote:"So if it's an alpha one antagonist in the veins, what that's gonna do to the vein, the venous tone? Is it gonna be constricted or relaxed? Relax. Relax. So if blood is, if your blood is pooling in my feet, what is not gonna go? It's not gonna go to the heart, it's not gonna go to the brain. So, you're gonna Fall off, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 29–30; transcript 10/6"},

{id:"L10-052", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1ant", skill:"apply",
 concept:"alpha1-block-reflex-tachycardia", tags:["in-class"], source:"both",
 stem:"Prazosin dilates the resistance arteries. Which response follows through the baroreceptors?",
 options:[
  {t:"Reflex tachycardia (palpitations)", correct:true, why:"The baroreceptors sense low pressure and raise sympathetic drive: reflex tachycardia, felt as palpitations."},
  {t:"Reflex bradycardia", correct:false, why:"Bradycardia is the reflex to a rise in pressure."},
  {t:"Miosis", correct:false, why:"Miosis is not a baroreflex response."},
  {t:"Less sympathetic drive to the heart", correct:false, why:"Low pressure increases sympathetic drive."}],
 teach:"Dilating the arteries lowers blood pressure; the baroreceptors sense it and increase sympathetic outflow, giving reflex tachycardia (palpitations). Because of this, prazosin is not a good monotherapy; a β blocker may be added to block the tachycardia.",
 quote:"What about if it's the alpha ones in the arteries? If you vasodilate the arteries, now your barrels are gonna sense my blood pressure is too low. What is it gonna do? I'm gonna increase the sympathetic, I'm gonna get reflex tachycardia, so palpitations, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 30; transcript 10/6"},

{id:"L10-053", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1ant", skill:"recall", multi:true,
 concept:"prazosin-adr", tags:[], source:"both",
 stem:"Which adverse effects are expected when a patient starts prazosin? Select all that apply.",
 options:[
  {t:"First-dose orthostatic hypotension", correct:true, why:"First dose effect: orthostatic hypotension and syncope (30–90 min)."},
  {t:"Reflex tachycardia", correct:true, why:"Baroreceptors respond to the fall in pressure."},
  {t:"Blurred vision", correct:true, why:"α1 in the eye is blocked, so the pupil cannot dilate properly."},
  {t:"Headache", correct:true, why:"A common adverse reaction for vasodilators."},
  {t:"Bradycardia", correct:false, why:"Heart rate rises by reflex."},
  {t:"Hypertensive crisis on withdrawal", correct:false, why:"That is clonidine (receptor up-regulation)."},
  {t:"Rebound congestion", correct:false, why:"That is phenylephrine."}],
 teach:"Prazosin's adverse reactions: the first-dose effect (orthostatic hypotension and syncope, 30–90 minutes), reflex tachycardia (palpitations), dizziness, blurred vision and headache. Headache and flushing are common to vasodilators.",
 quote:"So we have that first dose effect that is gonna cause the reflex tachycardia because your barrels are gonna sense that your blood pressure is too low. ... We have alpha ones in the eyes, so we won't be able to dilate very properly, so you get the blurred vision.",
 note:"The transcript says “first dose orthostatic hypertension” and “orthostatic hypertension, also known as syncope”; the slide says “Orthostatic Hypotension & Syncope”, and he describes patients passing out. Keyed to the slide (hypotension).",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 30; transcript 10/6"},

{id:"L10-054", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1ant", skill:"apply",
 concept:"vasodilator-headache", tags:[], source:"both",
 stem:"Why do vasodilators such as prazosin commonly cause headache?",
 options:[
  {t:"Raised pressure inside the skull", correct:true, why:"The brain is enclosed by the rigid skull; dilating its vessels raises pressure in the head (with flushing)."},
  {t:"They block α2 in the brain", correct:false, why:"Prazosin is selective for α1."},
  {t:"They constrict vessels in the brain", correct:false, why:"They dilate, not constrict."},
  {t:"They lower acetylcholine in the brain", correct:false, why:"Prazosin does not act on acetylcholine."}],
 teach:"A general rule he will use again in cardiovascular: a vasodilator most likely causes headache. Vessels in the face and brain dilate, and the brain sits inside the hard skull with little room, so pressure in the head rises; flushing goes with it.",
 quote:"So when you vasodilate those blood vessels, you increase the pressure in the head and you get the flushing and the headache associated with that. So one of the good general rules is if you are a vasodilator, most likely you're gonna get a headache for your patient, OK?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 30; transcript 10/6"},

{id:"L10-055", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1ant", skill:"apply",
 concept:"alpha1-antagonist-nose", tags:[], source:"both",
 stem:"What would an α1 antagonist do to nasal congestion?",
 options:[
  {t:"Make it worse", correct:true, why:"Blocking α1 relaxes the nasal blood vessels, which adds to the congestion."},
  {t:"Clear it", correct:false, why:"Clearing congestion needs vessel constriction, an α1 agonist (phenylephrine)."},
  {t:"Cause rebound congestion only after 3 days", correct:false, why:"Rebound congestion after days of use is the phenylephrine warning."},
  {t:"Have no effect on the nose", correct:false, why:"The nose is one of the α1 sites (“smell”)."}],
 teach:"The nose is an α1 site. An α1 agonist (phenylephrine) constricts nasal vessels and relieves congestion; an α1 antagonist (prazosin) relaxes them and makes congestion worse, so α1 antagonists have no use as decongestants.",
 quote:"And then, uh, we don't really use alpha one antagonist to decongestant because it's gonna make it worse. It's gonna relax the blood vessels in the nose and it's gonna cause even more congestion for those patients, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 28; transcript 10/6"},

{id:"L10-056", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"a1ant", skill:"recall",
 concept:"arteries-veins-sympathetic-only", tags:[], source:"both",
 stem:"Which statement about the arteries and veins is CORRECT?",
 options:[
  {t:"They have only sympathetic innervation", correct:true, why:"Sympathetic is the only (primary physiological) tone, so α1 always keeps some constriction."},
  {t:"They have only parasympathetic innervation", correct:false, why:"Parasympathetic-only is the lungs, not the vessels."},
  {t:"Their main receptor is β1", correct:false, why:"Their main receptor is α1."},
  {t:"They are relaxed unless a drug is given", correct:false, why:"They are always constricting to some degree to maintain blood pressure."}],
 teach:"The arteries and veins are one of the autonomic exceptions: sympathetic innervation only, with α1 as the predominant receptor. They are always constricting; the question is how much. Removing that sympathetic tone (clonidine centrally, prazosin at the receptor) relaxes them.",
 quote:"There's only sympathetic to the arteries and the veins, right? So, you're always constricting. The question is how much. So, are you constricting a lot or not a lot. You have to constrict somehow in order to maintain your blood pressure. But if you don't have sympathetics, relax",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 29; transcript 10/6"},

/* ---------------- Mirtazapine (slides 31–32) ---------------- */
{id:"L10-057", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"mirt", skill:"apply",
 concept:"mirtazapine-inhibit-inhibitor", tags:["in-class"], source:"both",
 stem:"How does blocking presynaptic α2 receptors with mirtazapine increase norepinephrine release?",
 options:[
  {t:"It removes the inhibitor of release", correct:true, why:"α2 is the inhibitory (Gi) gatekeeper; blocking the inhibitor gives a positive effect: more norepinephrine."},
  {t:"It blocks the norepinephrine transporter", correct:false, why:"That is cocaine."},
  {t:"It activates α1 on the nerve", correct:false, why:"Mirtazapine blocks α1; it activates nothing."},
  {t:"It inhibits monoamine oxidase", correct:false, why:"That is phenelzine and selegiline."}],
 teach:"α2 autoreceptors are inhibitory (Gαi) and suppress norepinephrine release. Mirtazapine antagonizes them: inhibiting the inhibitor gives a positive effect, more norepinephrine (and serotonin) release, which helps decrease depression.",
 quote:"So what do you think is gonna happen to the levels of norepinephrine if I inhibit the alpha 2s? What happens if I inhibit the inhibitor? I get positive effect. So by inhibiting the alpha 2s in the CNS, I'm gonna get less inhibition from the G alphai pathway.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 31–32; transcript 10/6"},

{id:"L10-058", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"mirt", skill:"recall", multi:true,
 concept:"mirtazapine-receptors", tags:[], source:"both",
 stem:"Which receptors does mirtazapine block? Select all that apply.",
 options:[
  {t:"α2", correct:true, why:"Its main action: presynaptic α2 autoreceptor antagonist."},
  {t:"H1", correct:true, why:"Histamine 1 receptors (sedation)."},
  {t:"Muscarinic", correct:true, why:"Muscarinic receptors (sedation)."},
  {t:"α1", correct:true, why:"It can block α1 as well."},
  {t:"β1", correct:false, why:"No β action was given for mirtazapine."},
  {t:"Muscle nicotinic (Nm)", correct:false, why:"Nm is the neuromuscular receptor; mirtazapine does not cause paralysis."}],
 teach:"Mirtazapine is marketed as an α2 antagonist but also blocks histamine H1, muscarinic and α1 receptors. α2 block raises norepinephrine (antidepressant); H1 and muscarinic block cause sedation; α1 block adds its own effects.",
 quote:"Mirtazapine is our alpha-2 antagonist, but also can block H1s, it can block muscarinics, and it can block alpha-1s. So that's gonna be a fun drug to take, right?",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 27, 31–32; transcript 10/6"},

{id:"L10-059", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"mirt", skill:"apply",
 concept:"mirtazapine-sedation", tags:["in-class"], source:"both",
 stem:"Mirtazapine helps depressed patients who also have insomnia fall asleep. Which receptor blockade accounts for this?",
 options:[
  {t:"Histamine H1 and muscarinic", correct:true, why:"Blocking histamine and muscarinic receptors in the brain causes sedation."},
  {t:"Presynaptic α2 only", correct:false, why:"α2 block raises norepinephrine, the antidepressant effect, not sleep."},
  {t:"α1 and β1", correct:false, why:"β1 is not one of its receptors, and sedation is tied to H1 and muscarinic block."},
  {t:"The norepinephrine transporter", correct:false, why:"Mirtazapine does not block the transporter."}],
 teach:"Mirtazapine is adjunct therapy for major depressive disorder with insomnia. α2 block raises norepinephrine (less depression); H1 and muscarinic block in the brain causes sedation (sleep). The pharmacology explains the use.",
 quote:"What is the side effect of having a drug that blocks the muscarinic and the histamine receptors? Sedation, right? You're gonna put them to sleep. So this drug not only helps with the depression by increasing repinephrine, but also helps them to fall asleep",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slides 31–32; transcript 10/6"},

{id:"L10-060", lecture:"L10", prof:"Gottlieb", tier:"new", topic:"L10", sub:"mirt", skill:"tell",
 concept:"clonidine-vs-mirtazapine", tags:[], source:"both",
 stem:"Which pairing of α2 drug and central effect is CORRECT?",
 options:[
  {t:"Clonidine: less norepinephrine release", correct:true, why:"Clonidine activates the inhibitory α2 pathway: less sympathetic (↓CNS on the slide)."},
  {t:"Mirtazapine: less norepinephrine release", correct:false, why:"Mirtazapine blocks α2 and enhances release (↑CNS)."},
  {t:"Clonidine: more norepinephrine release", correct:false, why:"Activating α2 suppresses release."},
  {t:"Mirtazapine: activates α2 receptors", correct:false, why:"Mirtazapine is the α2 antagonist."}],
 teach:"Same receptor, opposite drugs. Clonidine (α2 agonist) activates the Gi pathway: less norepinephrine, less sympathetic (↓CNS). Mirtazapine (α2 antagonist) removes that brake: more norepinephrine, more sympathetic (↑CNS).",
 quote:"So if you think about the CNS, clonidine is going to activate the inhibitory pathway, I get less sympathetic, as mirtazapine is going to enhance the sympathetic.",
 cite:"PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf slide 21; transcript 10/6"}
);
