TOPICS.push({id:'PE2', name:'His Exam 2 polls (verbatim)', prof:'Gottlieb', lecture:'PE2', cite:'PollEV’s Exam 2.pdf',
  subs:[{id:'verbatim', name:'His polls, word for word', cite:'PollEV’s Exam 2.pdf'},{id:'variant', name:'Same idea, different correct option', cite:'PollEV’s Exam 2.pdf'}]});
QUESTIONS.push(
/* ---------------- Poll 1: activation of the SNS ---------------- */
{id:'PE2-001', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'sns-activation-salivation', tags:['poll','pollev'], source:'both',
 stem:'Activation of the SNS is most likely to evoke:',
 options:[
  {t:'Diarrhea', correct:false, why:'Diarrhea is the D of DUMBBELSS, a parasympathetic (M3) effect; the sympathetic system slows the gut through α2 (constipation).'},
  {t:'Bronchial constriction', correct:false, why:'Bronchial constriction is parasympathetic (M3); sympathetic activation releases epinephrine that dilates the airways through β2.'},
  {t:'Salivation', correct:true, why:'His key: both the parasympathetic and the sympathetic systems cause salivation, because a sympathetic fiber releases acetylcholine onto M3 at the salivary glands.'},
  {t:'Miosis', correct:false, why:'Miosis is parasympathetic; sympathetic activation of α1 in the eye gives mydriasis.'},
  {t:'Increase in Na+ excretion', correct:false, why:'Sympathetic input to the kidney activates the renin–angiotensin system and retains Na+ and water, the opposite of excretion.'}],
 teach:'SNS = sympathetic nervous system. The sympathetic response is roughly the anti-DUMBBELSS, with an exception at the salivary glands: a sympathetic fiber releases acetylcholine onto M3, so both divisions cause salivation (parasympathetic: fluid saliva; sympathetic: thick saliva). The kidney retains Na+ and water under sympathetic drive.',
 quote:'Remember, both parasympathetic and sympathetic causes salivation, right? If I increase sympathetic to my kidneys, I\'m gonna retain more sodium because I make the ras system, which is gonna cause the retention of sodium and water.',
 note:'In the 10/1 audio he does not read out a letter; he explains the key by pointing out that both systems cause salivation and that sympathetic activation retains (not excretes) sodium. Every other option is a parasympathetic effect or the opposite of a sympathetic effect.',
 cite:'PollEV’s Exam 2.pdf poll 1; transcript 10/1; Autonomic Nervous System.pdf slides 30, 35'},

{id:'PE2-002', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'apply',
 concept:'sns-activation-mydriasis', tags:['poll','pollev'], source:'both',
 stem:'Activation of the sympathetic nervous system (SNS) is most likely to evoke:',
 options:[
  {t:'Diarrhea', correct:false, why:'Diarrhea is parasympathetic (M3); sympathetic α2 decreases GI activity.'},
  {t:'Bronchial constriction', correct:false, why:'Bronchial constriction is parasympathetic (M3); epinephrine dilates through β2.'},
  {t:'Mydriasis', correct:true, why:'Sympathetic α1 in the eye pulls the pupil open: mydriasis (pupil dilation).'},
  {t:'Increased urination', correct:false, why:'β3 relaxes the bladder so urine is retained; urination is parasympathetic (M3).'},
  {t:'Increase in Na+ excretion', correct:false, why:'Sympathetic activation retains Na+ and water through the renin–angiotensin system.'}],
 teach:'Sympathetic activation: excitation (α1, β) or sedation (α2) in the brain, mydriasis (α1), tachycardia (β1), vasoconstriction (α1), bronchodilation from circulating epinephrine (β2), bladder relaxation (β3), Na+ and water retention (β1), decreased GI activity (α2). His tip: picture yourself running from a dog, and pick the effect that helps you run.',
 quote:'Uh, in the eye, we have the alpha 1, so we\'re gonna pull the eyes open, so we\'re gonna get madriasis or pupil dilation, OK.',
 cite:'PollEV’s Exam 2.pdf poll 1 (variant); transcript 10/1; Autonomic Nervous System.pdf slide 31'},

{id:'PE2-003', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'apply',
 concept:'sns-activation-na-retention', tags:['poll','pollev'], source:'both',
 stem:'Activation of the sympathetic nervous system (SNS) is most likely to evoke:',
 options:[
  {t:'Bradycardia', correct:false, why:'Bradycardia is parasympathetic (M2, Gi); sympathetic β1 causes tachycardia.'},
  {t:'Miosis', correct:false, why:'Miosis is parasympathetic; sympathetic α1 dilates the pupil.'},
  {t:'Decrease in Na+ excretion', correct:true, why:'Sympathetic input to the kidney (β1, renin, angiotensin II, aldosterone) retains Na+ and water, so less Na+ is excreted.'},
  {t:'Increased urination', correct:false, why:'The sympathetic system decreases urine output; β3 relaxes the bladder to retain urine.'},
  {t:'Increased gastrointestinal motility', correct:false, why:'α2 on the parasympathetic nerve cuts acetylcholine release, so GI motility falls.'}],
 teach:'The kidney has only sympathetic innervation. Sympathetic drive leads to renin release; angiotensin II and aldosterone cause Na+ and water reabsorption (water follows sodium), raising blood volume. So sympathetic activation decreases, not increases, Na+ excretion.',
 quote:'And uh in the GI we\'re gonna have, oh sorry, on the kidneys, we\'re gonna have beta 1s, which are gonna increase the retention of sodium. Wherever sodium goes, water is gonna follow.',
 cite:'PollEV’s Exam 2.pdf poll 1 (variant); transcript 10/1; Autonomic Nervous System.pdf slides 31, 43'},

/* ---------------- Poll 2: activation of the cholinergic system ---------------- */
{id:'PE2-004', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'cholinergic-activation-diarrhea', tags:['poll','pollev'], source:'both',
 stem:'Activation of the cholinergic system will most likely produce which of the following?',
 options:[
  {t:'Dry mouth', correct:false, why:'Cholinergic activation causes salivation; dry mouth is the antagonist (anti-DUMBBELSS) effect.'},
  {t:'Decrease urination', correct:false, why:'M3 contracts the bladder, so urination increases.'},
  {t:'Diarrhea', correct:true, why:'His key (96% of the class): diarrhea is the D of DUMBBELSS, from M3 (Gq) increasing gut motility and tone.'},
  {t:'Mydrasis', correct:false, why:'Cholinergic activation causes miosis (pupil constriction); mydriasis is sympathetic (α1) or antimuscarinic.'},
  {t:'Bronchial dilation', correct:false, why:'Acetylcholine on M3 constricts the airways; dilation is a β2 effect.'}],
 teach:'Activating the cholinergic (parasympathetic) system gives DUMBBELSS: diarrhea, urination, miosis, bradycardia, bronchial constriction, emesis, lacrimation, salivation, stimulation. Every other option in this poll is the opposite of a DUMBBELSS effect.',
 quote:'Uh, so 96 says it\'s diarrhea because when you activate the cholinergic, you get the dumbbells, and out of the dumbbells, uh, diarrhea would fit to that D. Uh, you cause increased urination, you cause salivation, you\'re gonna cause meiosis, and you\'re gonna cause bronchial constriction.',
 note:'“Mydrasis” is his spelling in the poll (mydriasis, pupil dilation); kept as written.',
 cite:'PollEV’s Exam 2.pdf poll 2; transcript 10/1; Autonomic Nervous System.pdf slide 27'},

{id:'PE2-005', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'apply',
 concept:'cholinergic-activation-bradycardia', tags:['poll','pollev'], source:'both',
 stem:'Activation of the cholinergic system will most likely produce which of the following?',
 options:[
  {t:'Dry mouth', correct:false, why:'Cholinergic activation causes salivation, not dry mouth.'},
  {t:'Mydriasis', correct:false, why:'Cholinergic activation constricts the pupil (miosis).'},
  {t:'Bronchial dilation', correct:false, why:'M3 constricts the airways.'},
  {t:'Bradycardia', correct:true, why:'Acetylcholine on M2 (Gi) in the heart lowers cAMP and slows heart rate.'},
  {t:'Tachycardia', correct:false, why:'Tachycardia is β1 (sympathetic) or the result of blocking M2.'}],
 teach:'M2 receptors are in the heart and coupled to Gi (inhibitory): less cAMP, slower heart rate, decreased contractile force and cardiac output. Bradycardia is the first B of DUMBBELSS.',
 quote:'M2s are in the heart. That\'s our second stop. M2s are GI, not the gastrointestinal system, right? The G alpha I. Alpha I is for inhibitory, so it\'s going to cause what? Last camp, bradycardia, decreased contactile force.',
 cite:'PollEV’s Exam 2.pdf poll 2 (variant); transcript 9/30; Autonomic Nervous System.pdf slide 24'},

{id:'PE2-006', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'apply',
 concept:'cholinergic-blockade-dry-mouth', tags:['poll','pollev'], source:'both',
 stem:'Blocking the muscarinic receptors of the cholinergic system will most likely produce which of the following?',
 options:[
  {t:'Diarrhea', correct:false, why:'Diarrhea is the agonist effect; an antagonist causes constipation.'},
  {t:'Increased urination', correct:false, why:'An antagonist relaxes the bladder; the patient cannot urinate.'},
  {t:'Miosis', correct:false, why:'An antagonist dilates the pupil (mydriasis).'},
  {t:'Dry mouth', correct:true, why:'Blocking M3 on the glands stops salivation: the anti-DUMBBELSS.'},
  {t:'Bronchial constriction', correct:false, why:'Constriction is the agonist effect; an antagonist blocks it.'}],
 teach:'If the agonist gives DUMBBELSS, the antagonist gives the opposite: cannot poop, cannot pee, cannot see because the pupils dilate, tachycardia, and a dry mouth because the glands stop secreting.',
 quote:'The antagonists cause what? Anti dumbbells. You can\'t poop, can\'t pee, can\'t see because your pupils dilate. You get tachycardia. You get the opposite effect.',
 cite:'PollEV’s Exam 2.pdf poll 2 (variant); transcript 9/30; Autonomic Nervous System.pdf slide 24'},

/* ---------------- Poll 3: statements about innervation ---------------- */
{id:'PE2-007', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'recall',
 concept:'sns-kidneys-major', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is CORRECT?',
 options:[
  {t:'Direct release of NE in the lungs causes bronchial constriction', correct:false, why:'There is no sympathetic innervation of airway smooth muscle, and sympathetic stimulation (epinephrine on β2) dilates, not constricts.'},
  {t:'Direct release of Ach in the resistance arteries causes vasoconstriction', correct:false, why:'Resistance arteries have only sympathetic innervation; and M3 on the endothelium causes vasodilation through nitric oxide.'},
  {t:'SNS is the major autonomic nervous system component in the kidneys', correct:true, why:'His key: the sympathetic system is the major (only) autonomic input to the kidneys and blood vessels.'},
  {t:'PNS activation causes salivation & SNS activation causes dry mouth', correct:false, why:'Both divisions cause salivation; the sympathetic fiber releases acetylcholine onto M3 at the salivary glands.'}],
 teach:'Single innervation: the lungs are parasympathetic (PNS) only; blood vessels and kidneys are sympathetic (SNS) only. Cooperative innervation: both divisions cause salivation. Each wrong statement here breaks one of those exceptions.',
 quote:'So the sympathetic nerve system is the major autonomic nerve system in the kidneys and in the blood vessels, right? As the parasympathetic, it is on the lungs.',
 cite:'PollEV’s Exam 2.pdf poll 3; transcript 10/1; Autonomic Nervous System.pdf slides 43–44'},

{id:'PE2-008', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'salivation-both-divisions', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is CORRECT?',
 options:[
  {t:'The SNS is the major autonomic component in the lungs', correct:false, why:'The lungs are parasympathetic (PNS) only.'},
  {t:'The PNS is the major autonomic component in the kidneys', correct:false, why:'The kidneys are sympathetic (SNS) only.'},
  {t:'Both PNS and SNS activation cause salivation', correct:true, why:'The parasympathetic gives fluid saliva and the sympathetic (acetylcholine on M3) gives thick saliva.'},
  {t:'Direct release of Ach in resistance arteries causes vasoconstriction', correct:false, why:'Resistance arteries have no parasympathetic innervation; M3 on the endothelium dilates through nitric oxide.'}],
 teach:'PNS = parasympathetic nervous system; SNS = sympathetic nervous system. The salivary glands and the male sex organ are where the two work together. The lungs (PNS only) and the blood vessels and kidneys (SNS only) are single-innervation exceptions.',
 quote:'So, typically, the parasympathetic is a more fluid, liquidy, as the sympathetic is a more like thick saliva that he produces, right? ... So but both parasympathetic and sympathetic can cause salivation.',
 cite:'PollEV’s Exam 2.pdf poll 3 (variant); transcript 10/1; Autonomic Nervous System.pdf slide 44'},

{id:'PE2-009', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'innervation-incorrect-statement', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is INCORRECT?',
 options:[
  {t:'The SNS is the major autonomic component in the kidneys', correct:false, why:'Correct statement: the kidneys have only sympathetic innervation.'},
  {t:'Airway smooth muscle is innervated only by the PNS', correct:false, why:'Correct statement: the lungs are parasympathetic only.'},
  {t:'Resistance blood vessels are innervated only by the SNS, not the PNS', correct:false, why:'Correct statement: blood vessels have only sympathetic innervation.'},
  {t:'PNS activation causes salivation & SNS activation causes dry mouth', correct:true, why:'Incorrect statement: the sympathetic system also causes salivation (acetylcholine on M3), so it does not cause dry mouth.'}],
 teach:'PNS = parasympathetic, SNS = sympathetic. Know the exceptions: lungs PNS only; blood vessels and kidneys SNS only; salivary glands and the male sex organ have both working together. He warns that “only” is usually wrong on a test, but these “only” statements are right.',
 quote:'So when it comes to salivation, both parasympathetic and sympathetic increased salivation. The difference is what kind of gland they activate.',
 cite:'PollEV’s Exam 2.pdf poll 3 (variant); transcript 10/1; Autonomic Nervous System.pdf slides 43–44'},

/* ---------------- Poll 4: statements, all of the above ---------------- */
{id:'PE2-010', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'recall',
 concept:'ans-overview-all-above', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is CORRECT?',
 options:[
  {t:'Both PNS and SNS release acetylcholine in the ganglionic synapses', correct:false, why:'Correct statement (acetylcholine on Nn in both divisions’ ganglia), but not the only correct one.'},
  {t:'cAMP is a second messenger involved in a number of physiological functions', correct:false, why:'Correct statement (feeding, water homeostasis, sleep, heart rate and contractility, endocrine and neural processes), but not the only one.'},
  {t:'The autonomic nervous system is involuntary & composed of PNS and SNS', correct:false, why:'Correct statement (somatic is voluntary), but not the only one.'},
  {t:'Beta 2 adrenergic receptors are typically not innervated by the SNS', correct:false, why:'Correct statement (β2 is reached by circulating epinephrine), but not the only one.'},
  {t:'All of the above', correct:true, why:'All four statements are true; the class answered E and he confirmed “All the above.”'}],
 teach:'Ganglia of both the parasympathetic (PNS) and sympathetic (SNS) divisions use acetylcholine on Nn receptors. Cyclic AMP (cAMP) is a second messenger in many functions. The autonomic system is involuntary, with PNS and SNS branches. β2 receptors are typically not innervated. His test-taking tip: when at least two statements are right, go for all of the above.',
 quote:'54321 services. My ja says E, is that the correct answer? It is, right? All the above. Very good.',
 note:'The 9/30 audio does not read this poll’s stem aloud. The one clicker question he keyed on 9/30 after the neurotransmission slides was answered “E … All the above”, and every statement in this poll was taught on 9/30 before that point; polls 1–3, 5 and 6 are all keyed on 10/1. The match of this poll to that 9/30 answer is by elimination, not by a spoken stem.',
 cite:'PollEV’s Exam 2.pdf poll 4; transcript 9/30; Autonomic Nervous System.pdf slides 7, 11–13'},

{id:'PE2-011', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'ganglionic-transmitter-incorrect', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is INCORRECT?',
 options:[
  {t:'Both PNS and SNS release norepinephrine in the ganglionic synapses', correct:true, why:'Incorrect statement: the ganglionic transmitter in both divisions is acetylcholine, acting on Nn receptors.'},
  {t:'cAMP is a second messenger involved in a number of physiological functions', correct:false, why:'Correct statement.'},
  {t:'The autonomic nervous system is involuntary & composed of PNS and SNS', correct:false, why:'Correct statement.'},
  {t:'Beta 2 adrenergic receptors are typically not innervated by the SNS', correct:false, why:'Correct statement: β2 receptors are reached by epinephrine from the adrenal gland.'}],
 teach:'In the ganglia, independent of whether the division is parasympathetic (PNS) or sympathetic (SNS), acetylcholine is released and binds the neuronal nicotinic receptor (Nn). Norepinephrine is the usual sympathetic transmitter at the end organ, not in the ganglion.',
 quote:'and in the distal ganglia, independent if it\'s a parasympathetic or sympathetic, we\'re gonna be releasing acetylcholine as a neurotransmitter, and it\'s gonna be binding to a nicotinic receptor.',
 cite:'PollEV’s Exam 2.pdf poll 4 (variant); transcript 9/30; Autonomic Nervous System.pdf slide 12'},

{id:'PE2-012', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'ganglia-nn-not-nm', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is CORRECT?',
 options:[
  {t:'Both PNS and SNS ganglia use acetylcholine on Nm receptors', correct:false, why:'Ganglia use Nn (neuronal); Nm is the skeletal muscle receptor.'},
  {t:'Beta 1 adrenergic receptors are typically not innervated', correct:false, why:'β1 receptors are innervated; β2 is the one typically not innervated.'},
  {t:'The somatic nervous system is involuntary', correct:false, why:'The somatic system is voluntary (skeletal muscle); the autonomic is involuntary.'},
  {t:'Beta 2 receptors respond to circulating epinephrine', correct:true, why:'β2 receptors have no nerve; adrenal epinephrine in the blood activates them.'},
  {t:'None of the above', correct:false, why:'The β2 statement is correct.'}],
 teach:'PNS = parasympathetic, SNS = sympathetic. Nn (N for neuronal) is in the ganglia and brain; Nm (M for muscle) is at the skeletal muscle. α1, α2 and β1 are innervated; β2 is activated by epinephrine released into the blood by the adrenal gland.',
 quote:'But that epi and norepinephrine that your adrenal produces is gonna flow in your blood and then it\'s gonna get you those beta tubes, it\'s gonna activate them.',
 cite:'PollEV’s Exam 2.pdf poll 4 (variant); transcript 9/30; Autonomic Nervous System.pdf slides 12–13'},

/* ---------------- Poll 5: baroreceptors ---------------- */
{id:'PE2-013', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'recall',
 concept:'baroreceptors-all-above', tags:['poll','pollev'], source:'both',
 stem:'Which of the following is CORRECT regarding baroreceptors?',
 options:[
  {t:'Activation of the baroreceptors causes a decrease in BP', correct:false, why:'Correct (firing raises parasympathetic and lowers sympathetic activity), but not the only correct statement.'},
  {t:'Suppression of the baroreceptors causes an increase in BP', correct:false, why:'Correct (sympathetic activity is unopposed), but not the only one.'},
  {t:'Baroreceptors are pressure ion channels', correct:false, why:'Correct (pressoreceptors embedded in the vessel wall), but not the only one.'},
  {t:'When one stands up, the baroreceptors decrease firing', correct:false, why:'Correct (less venous return and stretch), but not the only one.'},
  {t:'All of the above', correct:true, why:'His key: “What is the best answer? All the above, that’s it.”'}],
 teach:'Baroreceptor firing is inversely related to sympathetic activity. Firing → parasympathetic up, sympathetic down, blood pressure (BP) down. Suppressed firing → sympathetic up, BP up. They are pressure-sensing ion channels. Standing up pools blood in the legs, so they fire less and the sympathetic system keeps the brain perfused.',
 quote:'What is the best answer? All the above, that\'s it. Remember that if your barrels are firing, barrel sympathetic is high, sympathetic is low, blood pressure is going to be low. If you suppress the barrels, sympathetic is high, blood pressure is going to be high. The barrels are pressure ion channels. And when you decrease, when you stand up, your barrels go silent',
 cite:'PollEV’s Exam 2.pdf poll 5; transcript 10/1; Autonomic Nervous System.pdf slides 49–52'},

{id:'PE2-014', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'baroreceptors-incorrect', tags:['poll','pollev'], source:'both',
 stem:'Which of the following is INCORRECT regarding baroreceptors?',
 options:[
  {t:'Activation of the baroreceptors increases SNS activity', correct:true, why:'Incorrect statement: ↑ baroreceptor firing = sympathetic (SNS) activity ↓.'},
  {t:'Baroreceptors are pressure ion channels', correct:false, why:'Correct statement.'},
  {t:'When one stands up, the baroreceptors decrease their firing', correct:false, why:'Correct statement.'},
  {t:'Carotid sinus baroreceptors signal through nerve IX', correct:false, why:'Correct statement: the carotid sinus uses the glossopharyngeal nerve (IX); the aortic arch uses the vagus (X).'}],
 teach:'↑ Baroreceptor firing = sympathetic nervous system (SNS) activity ↓. The carotid sinus (glossopharyngeal nerve, IX) and the aortic arch (vagus nerve, X) hold pressoreceptors embedded in the wall.',
 quote:'So, the more the barrel fires, the more parasympathetic you\'re gonna have. The lower the firing is, the more sympathetic you\'re gonna have.',
 cite:'PollEV’s Exam 2.pdf poll 5 (variant); transcript 10/1; Autonomic Nervous System.pdf slides 49–50'},

{id:'PE2-015', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'figure',
 concept:'baroreceptor-firing-pattern', tags:['poll','pollev'], source:'slide',
 stem:'Baroreceptor nerve firing is recorded while arterial pressure is rising, held constant, or falling around the same value. Under which condition is firing greatest?',
 options:[
  {t:'Pressure falling', correct:false, why:'Least firing occurs at decreasing pressure.'},
  {t:'Pressure held constant', correct:false, why:'Constant pressure gives less firing than rising pressure.'},
  {t:'Pressure rising', correct:true, why:'Most firing occurs at increasing pressure.'},
  {t:'Firing is the same in all three', correct:false, why:'The slide lists three different levels: most, less, least.'}],
 teach:'On the firing–pressure slide: most firing at increasing pressure, less firing at constant pressure, least firing at decreasing pressure. The curve is sigmoidal, with no firing below 50 mmHg, maximum firing near 180 mmHg and maximum sensitivity near 93 mmHg.',
 quote:'-Most Firing at Increasing Pressure -Less Firing at Constant Pressure -Least Firing at Decreasing Pressure',
 cite:'PollEV’s Exam 2.pdf poll 5 (variant); Autonomic Nervous System.pdf slide 50'},

/* ---------------- Poll 6: varenicline ---------------- */
{id:'PE2-016', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'recall',
 concept:'varenicline-all-above', tags:['poll','pollev'], source:'transcript',
 stem:'Which of the following is CORRECT about varenicline?',
 options:[
  {t:'Is a partial agonist to the alpha4/beta2 nicotinic receptor', correct:false, why:'Correct (his must-know fact), but not the only correct statement.'},
  {t:'It may cause depression in some patients', correct:false, why:'Correct (it acts in the brain and removes the nicotine-driven release of feel-good transmitters), but not the only one.'},
  {t:'It compete with nicotine for the Nn receptors in the brain', correct:false, why:'Correct (that is its mechanism of action), but not the only one.'},
  {t:'It decreases withdraw syndrome in pts trying to stop smoking', correct:false, why:'Correct (partial activation relieves withdrawal), but not the only one.'},
  {t:'All of the above', correct:true, why:'He confirmed each statement in turn after the poll: partial agonist, depression, competition with nicotine, less withdrawal.'}],
 teach:'Varenicline (Chantix) is a selective partial agonist at the α4β2 neuronal nicotinic (Nn) receptor in the brain; it leaves ganglionic and skeletal muscle nicotinic receptors alone. As a partial agonist it relieves withdrawal when nicotine is low and competes with nicotine when the patient smokes. Its side effects are mostly in the brain (headache, insomnia, depression) plus nausea.',
 quote:'So we know it\'s a partial agonist to the alpha 4 beta 2 nicotinic NN receptor. That\'s the must know information, right? It may cause some depression in patients because it works in the brain ... Uh, it compete with nicotine for the receptors in the brain. Yeah, that\'s their mechanism of action. ... It decrease the withdrawal syndrome, yes, so that\'s how it\'s gonna do the job.',
 note:'He does not say “all of the above” aloud for this poll; he affirms each of the four statements, which keys E. Wording kept as written (“It compete”, “withdraw syndrome”, “pts”). The drug is on the neuromuscular junction deck (L08), taught on 10/1.',
 cite:'PollEV’s Exam 2.pdf poll 6; transcript 10/1'},

{id:'PE2-017', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'varenicline-incorrect', tags:['poll','pollev'], source:'transcript',
 stem:'Which of the following is INCORRECT about varenicline?',
 options:[
  {t:'It is a full agonist at the α4β2 nicotinic receptor', correct:true, why:'Incorrect statement: varenicline is a partial agonist, which is why it can both relieve withdrawal and blunt nicotine.'},
  {t:'It may cause depression in some patients', correct:false, why:'Correct statement.'},
  {t:'It competes with nicotine for Nn receptors in the brain', correct:false, why:'Correct statement: that is its mechanism of action.'},
  {t:'It decreases withdrawal in patients trying to stop smoking', correct:false, why:'Correct statement.'}],
 teach:'Partial agonists have a two-sided effect: when the baseline is low (withdrawal) varenicline acts like an agonist because it has positive efficacy; when the patient smokes, it outcompetes nicotine and brings the effect down. A full agonist would not do the second part.',
 quote:'You gotta know there\'s a partial agonist to the alpha 4, beta 2 combination of NN receptors. That\'s a must no. There is no wiggle room for this now.',
 cite:'PollEV’s Exam 2.pdf poll 6 (variant); transcript 10/1'},

{id:'PE2-018', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'tell',
 concept:'varenicline-site-of-action', tags:['poll','pollev'], source:'transcript',
 stem:'Varenicline is selective. Which nicotinic receptors does it act on?',
 options:[
  {t:'Nm receptors at skeletal muscle', correct:false, why:'He says it leaves the skeletal muscle nicotinic receptors alone; succinylcholine is the Nm drug.'},
  {t:'Nn receptors in autonomic ganglia', correct:false, why:'He says it leaves the ganglionic nicotinic receptors alone.'},
  {t:'α4β2 Nn receptors in the brain', correct:true, why:'Its site of action is the α4β2 neuronal nicotinic receptor in the brain, involved in nicotine addiction.'},
  {t:'Muscarinic M1 receptors in the brain', correct:false, why:'Varenicline is nicotinic, not muscarinic.'}],
 teach:'Neuronal nicotinic (Nn) receptors are built from α2–α9 and β2–β4 subunits; the combination to know is α4β2. Varenicline is a selective partial agonist there, so it acts on the brain sites of nicotine addiction and leaves the ganglia and the skeletal muscle alone. Because the site of action is the brain, most side effects are in the brain.',
 quote:'This drug is a selective partial agonist to that specific combination of alpha 4, beta 2, nicotinic receptors. What it means is it\'s going to leave the nicotinic receptors in the ganglia alone, the nicotinic receptors in the skeletal muscle alone.',
 cite:'PollEV’s Exam 2.pdf poll 6 (variant); transcript 10/1'}
);
