TOPICS.push({id:'PE2', name:'His Exam 2 polls (verbatim)', prof:'Gottlieb', lecture:'PE2', cite:'PollEV’s Exam 2.pdf',
  subs:[{id:'verbatim', name:'His polls, word for word', cite:'PollEV’s Exam 2.pdf'},{id:'variant', name:'Same idea, different correct option', cite:'PollEV’s Exam 2.pdf'}]});
QUESTIONS.push(
/* ---------------- Poll 1: activation of the SNS ---------------- */
{id:'PE2-001', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'sns-activation-salivation', tags:['poll','pollev'], source:'both',
 stem:'Activation of the SNS is most likely to evoke:',
 options:[
  {t:'Diarrhea', correct:false, why:'Diarrhea is the D of DUMBBELSS, a parasympathetic (M3) effect; the sympathetic system slows the gut through α2 (constipation).'},
  {t:'Bronchial constriction', correct:false, why:'Bronchial constriction is parasympathetic (M3); sympathetic activation releases epinephrine that dilates the airways through β2.'},
  {t:'Salivation', correct:true, why:'His key: both the parasympathetic and the sympathetic systems cause salivation, because a sympathetic fiber releases acetylcholine onto M3 at the salivary glands.'},
  {t:'Miosis', correct:false, why:'Miosis is parasympathetic; sympathetic activation of α1 in the eye gives mydriasis.'},
  {t:'Increase in Na+ excretion', correct:false, why:'Sympathetic input to the kidney activates the renin–angiotensin system and retains Na+ and water, the opposite of excretion.'}],
 teach:'SNS = sympathetic nervous system. The sympathetic response is roughly the anti-DUMBBELSS, with an exception at the salivary glands: a sympathetic fiber releases acetylcholine onto M3, so both divisions cause salivation (parasympathetic: fluid saliva; sympathetic: thick saliva). The kidney retains Na+ and water under sympathetic drive.',
 quote:'Remember, both parasympathetic and sympathetic causes salivation, right? If I increase sympathetic to my kidneys, I\'m gonna retain more sodium because I make the ras system, which is gonna cause the retention of sodium and water.',
 note:'In the 10/1 audio he does not read out a letter; he explains the key by pointing out that both systems cause salivation and that sympathetic activation retains (not excretes) sodium. Every other option is a parasympathetic effect or the opposite of a sympathetic effect.',
 cite:'PollEV’s Exam 2.pdf poll 1; transcript 10/1; Autonomic Nervous System.pdf slides 30, 35'},

{id:'PE2-002', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'apply',
 concept:'sns-activation-mydriasis', tags:['poll','pollev'], source:'both',
 stem:'Activation of the sympathetic nervous system (SNS) is most likely to evoke:',
 options:[
  {t:'Diarrhea', correct:false, why:'Diarrhea is parasympathetic (M3); sympathetic α2 decreases GI activity.'},
  {t:'Bronchial constriction', correct:false, why:'Bronchial constriction is parasympathetic (M3); epinephrine dilates through β2.'},
  {t:'Mydriasis', correct:true, why:'Sympathetic α1 in the eye pulls the pupil open: mydriasis (pupil dilation).'},
  {t:'Increased urination', correct:false, why:'β3 relaxes the bladder so urine is retained; urination is parasympathetic (M3).'},
  {t:'Increase in Na+ excretion', correct:false, why:'Sympathetic activation retains Na+ and water through the renin–angiotensin system.'}],
 teach:'Sympathetic activation: excitation (α1, β) or sedation (α2) in the brain, mydriasis (α1), tachycardia (β1), vasoconstriction (α1), bronchodilation from circulating epinephrine (β2), bladder relaxation (β3), Na+ and water retention (β1), decreased GI activity (α2). His tip: picture yourself running from a dog, and pick the effect that helps you run.',
 quote:'Uh, in the eye, we have the alpha 1, so we\'re gonna pull the eyes open, so we\'re gonna get madriasis or pupil dilation, OK.',
 cite:'PollEV’s Exam 2.pdf poll 1 (variant); transcript 10/1; Autonomic Nervous System.pdf slide 31'},

{id:'PE2-003', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'apply',
 concept:'sns-activation-na-retention', tags:['poll','pollev'], source:'both',
 stem:'Activation of the sympathetic nervous system (SNS) is most likely to evoke:',
 options:[
  {t:'Bradycardia', correct:false, why:'Bradycardia is parasympathetic (M2, Gi); sympathetic β1 causes tachycardia.'},
  {t:'Miosis', correct:false, why:'Miosis is parasympathetic; sympathetic α1 dilates the pupil.'},
  {t:'Decrease in Na+ excretion', correct:true, why:'Sympathetic input to the kidney (β1, renin, angiotensin II, aldosterone) retains Na+ and water, so less Na+ is excreted.'},
  {t:'Increased urination', correct:false, why:'The sympathetic system decreases urine output; β3 relaxes the bladder to retain urine.'},
  {t:'Increased gastrointestinal motility', correct:false, why:'α2 on the parasympathetic nerve cuts acetylcholine release, so GI motility falls.'}],
 teach:'The kidney has only sympathetic innervation. Sympathetic drive leads to renin release; angiotensin II and aldosterone cause Na+ and water reabsorption (water follows sodium), raising blood volume. So sympathetic activation decreases, not increases, Na+ excretion.',
 quote:'And uh in the GI we\'re gonna have, oh sorry, on the kidneys, we\'re gonna have beta 1s, which are gonna increase the retention of sodium. Wherever sodium goes, water is gonna follow.',
 cite:'PollEV’s Exam 2.pdf poll 1 (variant); transcript 10/1; Autonomic Nervous System.pdf slides 31, 43'},

/* ---------------- Poll 2: activation of the cholinergic system ---------------- */
{id:'PE2-004', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'cholinergic-activation-diarrhea', tags:['poll','pollev'], source:'both',
 stem:'Activation of the cholinergic system will most likely produce which of the following?',
 options:[
  {t:'Dry mouth', correct:false, why:'Cholinergic activation causes salivation; dry mouth is the antagonist (anti-DUMBBELSS) effect.'},
  {t:'Decrease urination', correct:false, why:'M3 contracts the bladder, so urination increases.'},
  {t:'Diarrhea', correct:true, why:'His key (96% of the class): diarrhea is the D of DUMBBELSS, from M3 (Gq) increasing gut motility and tone.'},
  {t:'Mydrasis', correct:false, why:'Cholinergic activation causes miosis (pupil constriction); mydriasis is sympathetic (α1) or antimuscarinic.'},
  {t:'Bronchial dilation', correct:false, why:'Acetylcholine on M3 constricts the airways; dilation is a β2 effect.'}],
 teach:'Activating the cholinergic (parasympathetic) system gives DUMBBELSS: diarrhea, urination, miosis, bradycardia, bronchial constriction, emesis, lacrimation, salivation, stimulation. Every other option in this poll is the opposite of a DUMBBELSS effect.',
 quote:'Uh, so 96 says it\'s diarrhea because when you activate the cholinergic, you get the dumbbells, and out of the dumbbells, uh, diarrhea would fit to that D. Uh, you cause increased urination, you cause salivation, you\'re gonna cause meiosis, and you\'re gonna cause bronchial constriction.',
 note:'“Mydrasis” is his spelling in the poll (mydriasis, pupil dilation); kept as written.',
 cite:'PollEV’s Exam 2.pdf poll 2; transcript 10/1; Autonomic Nervous System.pdf slide 27'},

{id:'PE2-005', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'apply',
 concept:'cholinergic-activation-bradycardia', tags:['poll','pollev'], source:'both',
 stem:'Activation of the cholinergic system will most likely produce which of the following?',
 options:[
  {t:'Dry mouth', correct:false, why:'Cholinergic activation causes salivation, not dry mouth.'},
  {t:'Mydriasis', correct:false, why:'Cholinergic activation constricts the pupil (miosis).'},
  {t:'Bronchial dilation', correct:false, why:'M3 constricts the airways.'},
  {t:'Bradycardia', correct:true, why:'Acetylcholine on M2 (Gi) in the heart lowers cAMP and slows heart rate.'},
  {t:'Tachycardia', correct:false, why:'Tachycardia is β1 (sympathetic) or the result of blocking M2.'}],
 teach:'M2 receptors are in the heart and coupled to Gi (inhibitory): less cAMP, slower heart rate, decreased contractile force and cardiac output. Bradycardia is the first B of DUMBBELSS.',
 quote:'M2s are in the heart. That\'s our second stop. M2s are GI, not the gastrointestinal system, right? The G alpha I. Alpha I is for inhibitory, so it\'s going to cause what? Last camp, bradycardia, decreased contactile force.',
 cite:'PollEV’s Exam 2.pdf poll 2 (variant); transcript 9/30; Autonomic Nervous System.pdf slide 24'},

{id:'PE2-006', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'apply',
 concept:'cholinergic-blockade-dry-mouth', tags:['poll','pollev'], source:'both',
 stem:'Blocking the muscarinic receptors of the cholinergic system will most likely produce which of the following?',
 options:[
  {t:'Diarrhea', correct:false, why:'Diarrhea is the agonist effect; an antagonist causes constipation.'},
  {t:'Increased urination', correct:false, why:'An antagonist relaxes the bladder; the patient cannot urinate.'},
  {t:'Miosis', correct:false, why:'An antagonist dilates the pupil (mydriasis).'},
  {t:'Dry mouth', correct:true, why:'Blocking M3 on the glands stops salivation: the anti-DUMBBELSS.'},
  {t:'Bronchial constriction', correct:false, why:'Constriction is the agonist effect; an antagonist blocks it.'}],
 teach:'If the agonist gives DUMBBELSS, the antagonist gives the opposite: cannot poop, cannot pee, cannot see because the pupils dilate, tachycardia, and a dry mouth because the glands stop secreting.',
 quote:'The antagonists cause what? Anti dumbbells. You can\'t poop, can\'t pee, can\'t see because your pupils dilate. You get tachycardia. You get the opposite effect.',
 cite:'PollEV’s Exam 2.pdf poll 2 (variant); transcript 9/30; Autonomic Nervous System.pdf slide 24'},

/* ---------------- Poll 3: statements about innervation ---------------- */
{id:'PE2-007', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'recall',
 concept:'sns-kidneys-major', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is CORRECT?',
 options:[
  {t:'Direct release of NE in the lungs causes bronchial constriction', correct:false, why:'There is no sympathetic innervation of airway smooth muscle, and sympathetic stimulation (epinephrine on β2) dilates, not constricts.'},
  {t:'Direct release of Ach in the resistance arteries causes vasoconstriction', correct:false, why:'Resistance arteries have only sympathetic innervation; and M3 on the endothelium causes vasodilation through nitric oxide.'},
  {t:'SNS is the major autonomic nervous system component in the kidneys', correct:true, why:'His key: the sympathetic system is the major (only) autonomic input to the kidneys and blood vessels.'},
  {t:'PNS activation causes salivation & SNS activation causes dry mouth', correct:false, why:'Both divisions cause salivation; the sympathetic fiber releases acetylcholine onto M3 at the salivary glands.'}],
 teach:'Single innervation: the lungs are parasympathetic (PNS) only; blood vessels and kidneys are sympathetic (SNS) only. Cooperative innervation: both divisions cause salivation. Each wrong statement here breaks one of those exceptions.',
 quote:'So the sympathetic nerve system is the major autonomic nerve system in the kidneys and in the blood vessels, right? As the parasympathetic, it is on the lungs.',
 cite:'PollEV’s Exam 2.pdf poll 3; transcript 10/1; Autonomic Nervous System.pdf slides 43–44'},

{id:'PE2-008', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'salivation-both-divisions', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is CORRECT?',
 options:[
  {t:'The SNS is the major autonomic component in the lungs', correct:false, why:'The lungs are parasympathetic (PNS) only.'},
  {t:'The PNS is the major autonomic component in the kidneys', correct:false, why:'The kidneys are sympathetic (SNS) only.'},
  {t:'Both PNS and SNS activation cause salivation', correct:true, why:'The parasympathetic gives fluid saliva and the sympathetic (acetylcholine on M3) gives thick saliva.'},
  {t:'Direct release of Ach in resistance arteries causes vasoconstriction', correct:false, why:'Resistance arteries have no parasympathetic innervation; M3 on the endothelium dilates through nitric oxide.'}],
 teach:'PNS = parasympathetic nervous system; SNS = sympathetic nervous system. The salivary glands and the male sex organ are where the two work together. The lungs (PNS only) and the blood vessels and kidneys (SNS only) are single-innervation exceptions.',
 quote:'So, typically, the parasympathetic is a more fluid, liquidy, as the sympathetic is a more like thick saliva that he produces, right? ... So but both parasympathetic and sympathetic can cause salivation.',
 cite:'PollEV’s Exam 2.pdf poll 3 (variant); transcript 10/1; Autonomic Nervous System.pdf slide 44'},

{id:'PE2-009', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'innervation-incorrect-statement', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is INCORRECT?',
 options:[
  {t:'The SNS is the major autonomic component in the kidneys', correct:false, why:'Correct statement: the kidneys have only sympathetic innervation.'},
  {t:'Airway smooth muscle is innervated only by the PNS', correct:false, why:'Correct statement: the lungs are parasympathetic only.'},
  {t:'Resistance blood vessels are innervated only by the SNS, not the PNS', correct:false, why:'Correct statement: blood vessels have only sympathetic innervation.'},
  {t:'PNS activation causes salivation & SNS activation causes dry mouth', correct:true, why:'Incorrect statement: the sympathetic system also causes salivation (acetylcholine on M3), so it does not cause dry mouth.'}],
 teach:'PNS = parasympathetic, SNS = sympathetic. Know the exceptions: lungs PNS only; blood vessels and kidneys SNS only; salivary glands and the male sex organ have both working together. He warns that “only” is usually wrong on a test, but these “only” statements are right.',
 quote:'So when it comes to salivation, both parasympathetic and sympathetic increased salivation. The difference is what kind of gland they activate.',
 cite:'PollEV’s Exam 2.pdf poll 3 (variant); transcript 10/1; Autonomic Nervous System.pdf slides 43–44'},

/* ---------------- Poll 4: statements, all of the above ---------------- */
{id:'PE2-010', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'recall',
 concept:'ans-overview-all-above', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is CORRECT?',
 options:[
  {t:'Both PNS and SNS release acetylcholine in the ganglionic synapses', correct:false, why:'Correct statement (acetylcholine on Nn in both divisions’ ganglia), but not the only correct one.'},
  {t:'cAMP is a second messenger involved in a number of physiological functions', correct:false, why:'Correct statement (feeding, water homeostasis, sleep, heart rate and contractility, endocrine and neural processes), but not the only one.'},
  {t:'The autonomic nervous system is involuntary & composed of PNS and SNS', correct:false, why:'Correct statement (somatic is voluntary), but not the only one.'},
  {t:'Beta 2 adrenergic receptors are typically not innervated by the SNS', correct:false, why:'Correct statement (β2 is reached by circulating epinephrine), but not the only one.'},
  {t:'All of the above', correct:true, why:'All four statements are true; the class answered E and he confirmed “All the above.”'}],
 teach:'Ganglia of both the parasympathetic (PNS) and sympathetic (SNS) divisions use acetylcholine on Nn receptors. Cyclic AMP (cAMP) is a second messenger in many functions. The autonomic system is involuntary, with PNS and SNS branches. β2 receptors are typically not innervated. His test-taking tip: when at least two statements are right, go for all of the above.',
 quote:'54321 services. My ja says E, is that the correct answer? It is, right? All the above. Very good.',
 note:'The 9/30 audio does not read this poll’s stem aloud. The one clicker question he keyed on 9/30 after the neurotransmission slides was answered “E … All the above”, and every statement in this poll was taught on 9/30 before that point; polls 1–3, 5 and 6 are all keyed on 10/1. The match of this poll to that 9/30 answer is by elimination, not by a spoken stem; the updated poll sheet (10/6) highlights All of the above as the class key.',
 cite:'PollEV’s Exam 2.pdf poll 4; transcript 9/30; Autonomic Nervous System.pdf slides 7, 11–13'},

{id:'PE2-011', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'ganglionic-transmitter-incorrect', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is INCORRECT?',
 options:[
  {t:'Both PNS and SNS release norepinephrine in the ganglionic synapses', correct:true, why:'Incorrect statement: the ganglionic transmitter in both divisions is acetylcholine, acting on Nn receptors.'},
  {t:'cAMP is a second messenger involved in a number of physiological functions', correct:false, why:'Correct statement.'},
  {t:'The autonomic nervous system is involuntary & composed of PNS and SNS', correct:false, why:'Correct statement.'},
  {t:'Beta 2 adrenergic receptors are typically not innervated by the SNS', correct:false, why:'Correct statement: β2 receptors are reached by epinephrine from the adrenal gland.'}],
 teach:'In the ganglia, independent of whether the division is parasympathetic (PNS) or sympathetic (SNS), acetylcholine is released and binds the neuronal nicotinic receptor (Nn). Norepinephrine is the usual sympathetic transmitter at the end organ, not in the ganglion.',
 quote:'and in the distal ganglia, independent if it\'s a parasympathetic or sympathetic, we\'re gonna be releasing acetylcholine as a neurotransmitter, and it\'s gonna be binding to a nicotinic receptor.',
 cite:'PollEV’s Exam 2.pdf poll 4 (variant); transcript 9/30; Autonomic Nervous System.pdf slide 12'},

{id:'PE2-012', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'ganglia-nn-not-nm', tags:['poll','pollev'], source:'both',
 stem:'Which of the following statements is CORRECT?',
 options:[
  {t:'Both PNS and SNS ganglia use acetylcholine on Nm receptors', correct:false, why:'Ganglia use Nn (neuronal); Nm is the skeletal muscle receptor.'},
  {t:'Beta 1 adrenergic receptors are typically not innervated', correct:false, why:'β1 receptors are innervated; β2 is the one typically not innervated.'},
  {t:'The somatic nervous system is involuntary', correct:false, why:'The somatic system is voluntary (skeletal muscle); the autonomic is involuntary.'},
  {t:'Beta 2 receptors respond to circulating epinephrine', correct:true, why:'β2 receptors have no nerve; adrenal epinephrine in the blood activates them.'},
  {t:'None of the above', correct:false, why:'The β2 statement is correct.'}],
 teach:'PNS = parasympathetic, SNS = sympathetic. Nn (N for neuronal) is in the ganglia and brain; Nm (M for muscle) is at the skeletal muscle. α1, α2 and β1 are innervated; β2 is activated by epinephrine released into the blood by the adrenal gland.',
 quote:'But that epi and norepinephrine that your adrenal produces is gonna flow in your blood and then it\'s gonna get you those beta tubes, it\'s gonna activate them.',
 cite:'PollEV’s Exam 2.pdf poll 4 (variant); transcript 9/30; Autonomic Nervous System.pdf slides 12–13'},

/* ---------------- Poll 5: baroreceptors ---------------- */
{id:'PE2-013', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'recall',
 concept:'baroreceptors-all-above', tags:['poll','pollev'], source:'both',
 stem:'Which of the following is CORRECT regarding baroreceptors?',
 options:[
  {t:'Activation of the baroreceptors causes a decrease in BP', correct:false, why:'Correct (firing raises parasympathetic and lowers sympathetic activity), but not the only correct statement.'},
  {t:'Suppression of the baroreceptors causes an increase in BP', correct:false, why:'Correct (sympathetic activity is unopposed), but not the only one.'},
  {t:'Baroreceptors are pressure ion channels', correct:false, why:'Correct (pressoreceptors embedded in the vessel wall), but not the only one.'},
  {t:'When one stands up, the baroreceptors decrease firing', correct:false, why:'Correct (less venous return and stretch), but not the only one.'},
  {t:'All of the above', correct:true, why:'His key: “What is the best answer? All the above, that’s it.”'}],
 teach:'Baroreceptor firing is inversely related to sympathetic activity. Firing → parasympathetic up, sympathetic down, blood pressure (BP) down. Suppressed firing → sympathetic up, BP up. They are pressure-sensing ion channels. Standing up pools blood in the legs, so they fire less and the sympathetic system keeps the brain perfused.',
 quote:'What is the best answer? All the above, that\'s it. Remember that if your barrels are firing, barrel sympathetic is high, sympathetic is low, blood pressure is going to be low. If you suppress the barrels, sympathetic is high, blood pressure is going to be high. The barrels are pressure ion channels. And when you decrease, when you stand up, your barrels go silent',
 cite:'PollEV’s Exam 2.pdf poll 5; transcript 10/1; Autonomic Nervous System.pdf slides 49–52'},

{id:'PE2-014', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'baroreceptors-incorrect', tags:['poll','pollev'], source:'both',
 stem:'Which of the following is INCORRECT regarding baroreceptors?',
 options:[
  {t:'Activation of the baroreceptors increases SNS activity', correct:true, why:'Incorrect statement: ↑ baroreceptor firing = sympathetic (SNS) activity ↓.'},
  {t:'Baroreceptors are pressure ion channels', correct:false, why:'Correct statement.'},
  {t:'When one stands up, the baroreceptors decrease their firing', correct:false, why:'Correct statement.'},
  {t:'Carotid sinus baroreceptors signal through nerve IX', correct:false, why:'Correct statement: the carotid sinus uses the glossopharyngeal nerve (IX); the aortic arch uses the vagus (X).'}],
 teach:'↑ Baroreceptor firing = sympathetic nervous system (SNS) activity ↓. The carotid sinus (glossopharyngeal nerve, IX) and the aortic arch (vagus nerve, X) hold pressoreceptors embedded in the wall.',
 quote:'So, the more the barrel fires, the more parasympathetic you\'re gonna have. The lower the firing is, the more sympathetic you\'re gonna have.',
 cite:'PollEV’s Exam 2.pdf poll 5 (variant); transcript 10/1; Autonomic Nervous System.pdf slides 49–50'},

{id:'PE2-015', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'figure',
 concept:'baroreceptor-firing-pattern', tags:['poll','pollev'], source:'slide',
 stem:'Baroreceptor nerve firing is recorded while arterial pressure is rising, held constant, or falling around the same value. Under which condition is firing greatest?',
 options:[
  {t:'Pressure falling', correct:false, why:'Least firing occurs at decreasing pressure.'},
  {t:'Pressure held constant', correct:false, why:'Constant pressure gives less firing than rising pressure.'},
  {t:'Pressure rising', correct:true, why:'Most firing occurs at increasing pressure.'},
  {t:'Firing is the same in all three', correct:false, why:'The slide lists three different levels: most, less, least.'}],
 teach:'On the firing–pressure slide: most firing at increasing pressure, less firing at constant pressure, least firing at decreasing pressure. The curve is sigmoidal, with no firing below 50 mmHg, maximum firing near 180 mmHg and maximum sensitivity near 93 mmHg.',
 quote:'-Most Firing at Increasing Pressure -Less Firing at Constant Pressure -Least Firing at Decreasing Pressure',
 cite:'PollEV’s Exam 2.pdf poll 5 (variant); Autonomic Nervous System.pdf slide 50'},

/* ---------------- Poll 6: varenicline ---------------- */
{id:'PE2-016', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'recall',
 concept:'varenicline-all-above', tags:['poll','pollev'], source:'transcript',
 stem:'Which of the following is CORRECT about varenicline?',
 options:[
  {t:'Is a partial agonist to the alpha4/beta2 nicotinic receptor', correct:false, why:'Correct (his must-know fact), but not the only correct statement.'},
  {t:'It may cause depression in some patients', correct:false, why:'Correct (it acts in the brain and removes the nicotine-driven release of feel-good transmitters), but not the only one.'},
  {t:'It compete with nicotine for the Nn receptors in the brain', correct:false, why:'Correct (that is its mechanism of action), but not the only one.'},
  {t:'It decreases withdraw syndrome in pts trying to stop smoking', correct:false, why:'Correct (partial activation relieves withdrawal), but not the only one.'},
  {t:'All of the above', correct:true, why:'He confirmed each statement in turn after the poll: partial agonist, depression, competition with nicotine, less withdrawal.'}],
 teach:'Varenicline (Chantix) is a selective partial agonist at the α4β2 neuronal nicotinic (Nn) receptor in the brain; it leaves ganglionic and skeletal muscle nicotinic receptors alone. As a partial agonist it relieves withdrawal when nicotine is low and competes with nicotine when the patient smokes. Its side effects are mostly in the brain (headache, insomnia, depression) plus nausea.',
 quote:'So we know it\'s a partial agonist to the alpha 4 beta 2 nicotinic NN receptor. That\'s the must know information, right? It may cause some depression in patients because it works in the brain ... Uh, it compete with nicotine for the receptors in the brain. Yeah, that\'s their mechanism of action. ... It decrease the withdrawal syndrome, yes, so that\'s how it\'s gonna do the job.',
 note:'He does not say “all of the above” aloud for this poll; he affirms each of the four statements, which keys E. Wording kept as written (“It compete”, “withdraw syndrome”, “pts”). The drug is on the neuromuscular junction deck (L08), taught on 10/1.',
 cite:'PollEV’s Exam 2.pdf poll 6; transcript 10/1'},

{id:'PE2-017', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'recall',
 concept:'varenicline-incorrect', tags:['poll','pollev'], source:'transcript',
 stem:'Which of the following is INCORRECT about varenicline?',
 options:[
  {t:'It is a full agonist at the α4β2 nicotinic receptor', correct:true, why:'Incorrect statement: varenicline is a partial agonist, which is why it can both relieve withdrawal and blunt nicotine.'},
  {t:'It may cause depression in some patients', correct:false, why:'Correct statement.'},
  {t:'It competes with nicotine for Nn receptors in the brain', correct:false, why:'Correct statement: that is its mechanism of action.'},
  {t:'It decreases withdrawal in patients trying to stop smoking', correct:false, why:'Correct statement.'}],
 teach:'Partial agonists have a two-sided effect: when the baseline is low (withdrawal) varenicline acts like an agonist because it has positive efficacy; when the patient smokes, it outcompetes nicotine and brings the effect down. A full agonist would not do the second part.',
 quote:'You gotta know there\'s a partial agonist to the alpha 4, beta 2 combination of NN receptors. That\'s a must no. There is no wiggle room for this now.',
 cite:'PollEV’s Exam 2.pdf poll 6 (variant); transcript 10/1'},

{id:'PE2-018', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'tell',
 concept:'varenicline-site-of-action', tags:['poll','pollev'], source:'transcript',
 stem:'Varenicline is selective. Which nicotinic receptors does it act on?',
 options:[
  {t:'Nm receptors at skeletal muscle', correct:false, why:'He says it leaves the skeletal muscle nicotinic receptors alone; succinylcholine is the Nm drug.'},
  {t:'Nn receptors in autonomic ganglia', correct:false, why:'He says it leaves the ganglionic nicotinic receptors alone.'},
  {t:'α4β2 Nn receptors in the brain', correct:true, why:'Its site of action is the α4β2 neuronal nicotinic receptor in the brain, involved in nicotine addiction.'},
  {t:'Muscarinic M1 receptors in the brain', correct:false, why:'Varenicline is nicotinic, not muscarinic.'}],
 teach:'Neuronal nicotinic (Nn) receptors are built from α2–α9 and β2–β4 subunits; the combination to know is α4β2. Varenicline is a selective partial agonist there, so it acts on the brain sites of nicotine addiction and leaves the ganglia and the skeletal muscle alone. Because the site of action is the brain, most side effects are in the brain.',
 quote:'This drug is a selective partial agonist to that specific combination of alpha 4, beta 2, nicotinic receptors. What it means is it\'s going to leave the nicotinic receptors in the ganglia alone, the nicotinic receptors in the skeletal muscle alone.',
 cite:'PollEV’s Exam 2.pdf poll 6 (variant); transcript 10/1'},

/* ================ 10/5 polls (verbatim, keys highlighted on his sheet) ================ */
/* ---------------- Poll 7: paralysis by antagonizing ACh at Nm ---------------- */
{id:'PE2-019', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'tell',
 concept:'rocuronium-antagonist-paralysis', tags:['poll','pollev','verbatim'], source:'both',
 stem:'Which of the following drugs causes paralysis by antagonizing the binding of ACh to the Nm receptor?',
 options:[
  {t:'Varenicline', correct:false, why:'Varenicline is a partial agonist at the α4/β2 neuronal nicotinic (Nn) receptor in the brain; it does not cause paralysis.'},
  {t:'Succinycholine', correct:false, why:'Succinylcholine does cause paralysis, but as an agonist: it opens the Nm channel and does not compete with acetylcholine (ACh).'},
  {t:'Rocuronium', correct:true, why:'His key: rocuronium is a curare-like competitive, reversible Nm antagonist; it stops ACh from binding and opening the channel, so the muscle is paralyzed.'},
  {t:'Norepinephrine', correct:false, why:'Norepinephrine is an adrenergic agonist; it does not act at the Nm receptor and does not cause paralysis.'}],
 teach:'Two of the four options cause paralysis at the muscle nicotinic (Nm) receptor, by opposite mechanisms. Succinylcholine is a depolarizing agonist that opens the channel; curare-like drugs (any drug with -cur- in its name, such as rocuronium) are non-depolarizing competitive antagonists with affinity but no efficacy. The stem asks for the antagonist, so the agonist is out.',
 quote:'So out of these questions, just based on the stem, you should be able to eliminate two options, right? Right off the bat because two of them may cause paralysis, the other two do not cause paralysis ... Why is not B as in boy? Because they don\'t compete with a pseudocholine. They\'re both agonists. ... Uh, so, uh, Roqueron will be the best answer.',
 note:'“Succinycholine” is his spelling on the poll (succinylcholine); kept as written. Bonus-point poll on 10/5. Green highlight on the sheet: Rocuronium; in the audio he keys C and rules out B because it is an agonist.',
 cite:'PollEV’s Exam 2.pdf poll 7; transcript 10/5; PCOL-NMJ_PCOL_2026s_pptx.pdf slide 19'},

/* ---------------- Poll 8: rocuronium, most likely effect ---------------- */
{id:'PE2-020', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'rocuronium-effect-paralysis', tags:['poll','pollev','verbatim'], source:'both',
 stem:'If a patient is administered rocuronium, which of the following is most likely to occur?',
 options:[
  {t:'diarrhea', correct:false, why:'The gut is controlled by muscarinic receptors; rocuronium blocks Nm at skeletal muscle.'},
  {t:'increase urination', correct:false, why:'The bladder needs muscarinic or adrenergic receptors; rocuronium does not act there.'},
  {t:'hypertension', correct:false, why:'Blood vessels are controlled only by adrenergic (sympathetic) receptors; rocuronium does not act on them.'},
  {t:'paralysis', correct:true, why:'His key: blocking the muscle nicotinic (Nm) receptor causes paralysis every time; it is what the drug is used for.'},
  {t:'bronchial constriction', correct:false, why:'Bronchial constriction is a muscarinic effect; bronchial spasm from histamine release is a curare-like side effect with a very small chance for rocuronium.'}],
 teach:'Rocuronium is a curare-like competitive Nm antagonist, so paralysis happens 100% of the time. To affect an organ, a drug needs the receptor that controls it: the gut is muscarinic, the bladder muscarinic or adrenergic, and the blood vessels adrenergic. Histamine release may or may not happen with some curare-like drugs, and with rocuronium the chance is very small.',
 quote:'All right, what is the best answer? Paralysis, right? Remember, in order to affect the gut, it has to be what? muscarinic. In order to affect the bladder, it has to be muscarinic or adrenergic, right? Uh, in order to affect the blood vessel has to be adrenergic because that\'s the only, uh, sympathetic that we have. ... So what we have over here is paralysis. That\'s always going to happen.',
 note:'Green highlight: paralysis; he keyed paralysis aloud on 10/5. A student argued for a histamine effect; he answered that paralysis happens every time while histamine release may or may not, “But Rocuronium, very small chance”. In the same answer he said it “may cause bronchodilation because of the release of histamine”; slides 30 and 32 list bronchial spasm from histamine release, so that remark is treated as misspoken.',
 cite:'PollEV’s Exam 2.pdf poll 8; transcript 10/5; PCOL-NMJ_PCOL_2026s_pptx.pdf slides 19, 30, 32'},

/* ---------------- Poll 9: rivastigmine ---------------- */
{id:'PE2-021', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'stigmine-dumbbelss', tags:['poll','pollev','verbatim','druglist'], source:'both',
 stem:'Rivastigmine is most likely to produce:',
 options:[
  {t:'Constipation', correct:false, why:'Constipation is an anti-DUMBBELSS (antagonist) effect; a -stigmine raises acetylcholine and causes diarrhea.'},
  {t:'Tachycardia', correct:false, why:'-stigmines cause bradycardia, part of DUMBBELSS.'},
  {t:'Salivation', correct:true, why:'His key (C): rivastigmine inhibits the cholinesterase enzyme, acetylcholine becomes more potent everywhere, and salivation is the S of DUMBBELSS.'},
  {t:'Decrease urination', correct:false, why:'Anti-DUMBBELSS; more acetylcholine squeezes the bladder and increases urination.'},
  {t:'Pupil dilation', correct:false, why:'Anti-DUMBBELSS; -stigmines cause miosis (pupil constriction).'}],
 teach:'Any drug with -stigmine in its name inhibits the cholinesterase enzyme, so acetylcholine is not broken down and is more potent all over the body. The side effects are DUMBBELSS: diarrhea, urination, miosis, bronchial constriction, bradycardia, emesis, lacrimation, salivation and stimulation of the brain. Every wrong option here is an anti-DUMBBELSS effect.',
 quote:'So as far as side effects go, they\'re going to cause the dumbbells. Why? Because you\'re making acetylcholine more potent all over the body. ... What is the best answer? We have uh C as in cat, is that part of the process? Yes, that\'s the dumbbells, right?',
 note:'Green highlight: Salivation (option C). On 10/5, before showing the results, he said “Are you sure it\'s not D as in David? OK. Just trying to help.”; D (Decrease urination) is anti-DUMBBELSS, and he then keyed C.',
 cite:'PollEV’s Exam 2.pdf poll 9; transcript 10/5; PCOL-NMJ_PCOL_2026s_pptx.pdf slides 40–41'},

/* ---------------- Poll 10: curare arrow (NTK) ---------------- */
{id:'PE2-022', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'curare-reversal-neostigmine', tags:['poll','pollev','verbatim','exam-cue','ntk','druglist'], source:'both',
 stem:'While hunting, your friend had an accident and pocked himself with an arrow tip (contain curare). Which of these would you have to do to reverse the effects?',
 options:[
  {t:'Succinylcholine', correct:false, why:'Succinylcholine also causes paralysis; adding another paralytic agent stops the diaphragm and breathing.'},
  {t:'Rocuronium', correct:false, why:'Rocuronium has -cur- in its name and belongs to the same class as curare; it doubles the paralysis.'},
  {t:'Neostigmine', correct:true, why:'His key: neostigmine does not cross the blood–brain barrier but raises acetylcholine at the skeletal muscle synapse, which outcompetes curare.'},
  {t:'Varenicline', correct:false, why:'Varenicline acts on neuronal nicotinic receptors in the brain; curare has no effect in the brain, so it gives no benefit.'},
  {t:'Tickle your friend', correct:false, why:'A paralyzed friend cannot laugh or move; tickling does nothing to the block at the receptor.'}],
 teach:'Any drug with -cur- in its name is a competitive, reversible antagonist at the muscle nicotinic (Nm) receptor and causes paralysis. Reversal needs the opposite effect: more acetylcholine at the skeletal muscle synapse. A cholinesterase inhibitor such as neostigmine blocks acetylcholine breakdown and lets acetylcholine outcompete curare.',
 quote:'So neo stigamine, which does not cross the blood brain barrier but can increase the levels of acetylcholine in the synapse of your skeletal muscle, would give you a better chance of outcompeting karate and regain some movement for your friend. Yes. I have a question similar to this in the exam every year, and about 30% of the class misses it.',
 note:'“pocked” and “(contain curare)” are as written on the poll; “karate” in the audio is curare. Bonus-point poll on 10/5; green highlight: Neostigmine, and he keyed C aloud (“I have over here, see, is that the correct answer?”). Handwritten on the student’s sheet: “NTK, similar question on exam” (NTK = need to know); in the audio he said a question similar to this is on the exam every year and about 30% of the class misses it.',
 cite:'PollEV’s Exam 2.pdf poll 10; transcript 10/5; PCOL-NMJ_PCOL_2026s_pptx.pdf slides 19, 39'},

/* ---------------- Poll 11: decreases ACh release ---------------- */
{id:'PE2-023', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'tell',
 concept:'ach-release-botulinum', tags:['poll','pollev','verbatim'], source:'both',
 stem:'Which of the following decreases the release of Ach from pre-synaptic neurons?',
 options:[
  {t:'Varenicline', correct:false, why:'Varenicline is a partial agonist at the neuronal nicotinic (Nn) receptor; it acts after release.'},
  {t:'Succinylcholine', correct:false, why:'Succinylcholine is an agonist at the nicotinic receptor; it acts after release.'},
  {t:'Rocuronium', correct:false, why:'Rocuronium is an antagonist at the nicotinic receptor; it acts after release.'},
  {t:'Rivastigmine', correct:false, why:'Rivastigmine is an antagonist of the cholinesterase enzyme; it keeps released acetylcholine around longer.'},
  {t:'Botox', correct:true, why:'His key: botulinum toxin breaks down the SNARE proteins, so vesicles cannot dock and acetylcholine (Ach) is not released.'}],
 teach:'Four of these drugs act after acetylcholine is released: at the receptor (varenicline, succinylcholine, rocuronium) or at the enzyme that breaks it down (rivastigmine). Botulinum toxin acts before release: it is an enzyme that cleaves the SNARE proteins that anchor the vesicle to the membrane, so the vesicles stay full and acetylcholine is not released.',
 quote:'Pennyline is a partial agonist to the NN receptor. Succylcholine is an agonist to the nicotinic receptor. Rocurono is an antagonist to the nicotinic receptor, and rivasciamine is an antagonist to the psytocholesterase enzyme. So the only one that decreases the release of acetylcholine would be the Botox toxin.',
 note:'Green highlight: Botox; on 10/5: “Hopefully, you pick Botox, and that would be the correct answer, right?”',
 cite:'PollEV’s Exam 2.pdf poll 11; transcript 10/5; PCOL-NMJ_PCOL_2026s_pptx.pdf slides 46–50'},

/* ---------------- Poll 12: cholinergic agonist overdose ---------------- */
{id:'PE2-024', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'cholinergic-overdose-poll', tags:['poll','pollev','verbatim'], source:'both',
 stem:'If one overdose on a cholinergic agonist, which of the symptoms is most likely to occur?',
 options:[
  {t:'Diarrhea', correct:false, why:'Occurs (the D of DUMBBELSS), but it is not the only listed symptom that occurs.'},
  {t:'Can\'t urinate', correct:false, why:'Does not occur: the agonist squeezes the bladder and the patient urinates more. He keyed “all the above” with the exception of this option.'},
  {t:'Miosis', correct:false, why:'Occurs (M3 squeezes the circular muscle of the pupil), but it is not the only one.'},
  {t:'Bradycardia', correct:false, why:'Occurs (M2, Gi, in the heart), but it is not the only one.'},
  {t:'All of the above', correct:true, why:'His key: diarrhea, miosis and bradycardia all occur; he said “all the above with the exception of” B, Can\'t urinate.'}],
 teach:'A cholinergic agonist overdose gives DUMBBELSS: diarrhea, urination (more, not less), miosis, bradycardia, bronchial constriction, emesis, lacrimation, salivation and stimulation. Can\'t urinate is the antagonist (anti-DUMBBELSS) effect. As keyed, “All of the above” stands for the three DUMBBELSS options, not the urination option.',
 quote:'I think I changed this answer because B is not uh the correct answer. Remember that if you activate the bladder, you\'re gonna squeeze the bladder, you\'re gonna increase urination. So, out of these questions, uh, B is you urinate more, it\'s not that you can\'t urinate. So, that\'s uh, that answer. But yes, you get diarrhea, you get meiosis, you get bradycardia, and you\'re gonna get, uh, it would be all the above with the exception of uh B as in boy, OK? Maybe last year was which of these would not occur and that was the right answer, but uh I didn\'t catch that.',
 note:'Green highlight: All of the above. Handwritten next to “Can\'t urinate” on the student’s sheet: “not included”. In the 10/5 audio he says B is not correct, keys “all the above with the exception of” B, and says last year’s version may have asked which symptom would NOT occur, with B as the answer (“I didn\'t catch that”). Read literally, “All of the above” would include Can\'t urinate, which does not occur; his key is all of the above except B.',
 cite:'PollEV’s Exam 2.pdf poll 12; transcript 10/5; PCOL-Cholinergic-26s.pdf slide 13'},

/* ---------------- Poll 13: carbachol ---------------- */
{id:'PE2-025', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'carbachol-poll', tags:['poll','pollev','verbatim'], source:'both',
 stem:'Carbachol is most likely to cause:',
 options:[
  {t:'Dry mouth', correct:false, why:'Anti-DUMBBELSS; a muscarinic agonist causes salivation.'},
  {t:'Bradycardia', correct:true, why:'His key: the “chol” marks a cholinergic (muscarinic) agonist; at the heart’s M2 (Gi) it slows the heart.'},
  {t:'Constipation', correct:false, why:'Anti-DUMBBELSS; an agonist increases GI motility and tone (diarrhea).'},
  {t:'Bronchial dilation', correct:false, why:'An agonist constricts the bronchi through M3.'},
  {t:'Decrease in vomiting', correct:false, why:'An agonist causes emesis (the E of DUMBBELSS), not less vomiting.'}],
 teach:'The “chol” in carbachol links it to the mechanism: a non-selective muscarinic agonist. Knowing the site of action predicts the effect: heart M2 (Gi) gives bradycardia, and the M3 sites give the rest of the DUMBBELSS. The effects of a muscarinic agonist mirror activation of the cholinergic system.',
 quote:'when you see carbacol, there is something on that drug name that is gonna allow you to associate with the mechanism of action of a drug, and then if you know the site of action, you can predict what it would do. ... What is the best answer? Uh, B as in bravo, bravo, bradycardia, right?',
 note:'Green highlight: Bradycardia; keyed aloud on 10/5 (“B as in bravo”).',
 cite:'PollEV’s Exam 2.pdf poll 13; transcript 10/5; PCOL-Cholinergic-26s.pdf slides 11–13'},

/* ---------------- Poll 14: atropine ---------------- */
{id:'PE2-026', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'recall',
 concept:'atropine-poll', tags:['poll','pollev','verbatim'], source:'both',
 stem:'Atropine:',
 options:[
  {t:'Activates the M1, M2, and M3 receptors', correct:false, why:'Atropine binds M1, M2 and M3 but blocks them; it is the prototype muscarinic antagonist, not an agonist.'},
  {t:'Block the ability of NE to bind and activate its receptors', correct:false, why:'Norepinephrine (NE) acts on adrenergic receptors; atropine has affinity only for muscarinic receptors.'},
  {t:'Competitively antagonize the activations of muscarinic receptors', correct:true, why:'His key (C): atropine is a non-selective, reversible (competitive) muscarinic antagonist.'},
  {t:'Causes severe diarrhea as an ADR', correct:false, why:'Diarrhea is an agonist (DUMBBELSS) effect; atropine causes constipation as an adverse drug reaction (ADR).'},
  {t:'Causes paralysis by blocking Nm receptors', correct:false, why:'Blocking Nm is what the curare-like drugs (rocuronium) do; atropine has no affinity for nicotinic receptors.'}],
 teach:'Atropine is the prototype muscarinic antagonist: a natural alkaloid, non-selective (M1, M2, M3) and reversible, so it competes with acetylcholine and can be outcompeted. It gives anti-DUMBBELSS effects (tachycardia, mydriasis, constipation, dry mouth). It does not bind nicotinic or adrenergic receptors.',
 quote:'service says the majority says C and that is the correct answer. What if I had a set one of the answer choice where it\'s gonna block the ability of acetylcholine to bind to the nicotinic receptors? Would that be true or false? False, right? Because these drugs only have affinity for what? Muscarinic receptors, OK.',
 note:'Green highlight: option C; keyed aloud on 10/5. “Block”, “antagonize” and “activations” are as written on the poll.',
 cite:'PollEV’s Exam 2.pdf poll 14; transcript 10/5; PCOL-Cholinergic-26s.pdf slides 17, 19'},

/* ---------------- Poll 15: trospium ---------------- */
{id:'PE2-027', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'trospium-decrease-urination', tags:['poll','pollev','verbatim','druglist'], source:'both',
 stem:'Trospium is most likely to:',
 options:[
  {t:'Cause bronchial constriction', correct:false, why:'Bronchial constriction is an agonist (M3) effect; a muscarinic antagonist relaxes the bronchi.'},
  {t:'Evoke salivation', correct:false, why:'Salivation is an agonist effect; the bladder antimuscarinics cause dry mouth (xerostomia).'},
  {t:'Decrease urination', correct:true, why:'Trospium is an atropine-like (“trop”) muscarinic antagonist for overactive bladder: blocking bladder M3 decreases urgency, frequency and leakage.'},
  {t:'Increase GI motility', correct:false, why:'Increased motility is an agonist effect; blocking GI M3 gives constipation.'},
  {t:'Excitation', correct:false, why:'Blocking M1 in the brain gives sedation, not excitation; trospium is at the bottom of the slide’s list of bladder drugs with CNS effects (drowsiness, dizziness, confusion).'}],
 teach:'Any drug with “trop” in its name is an atropine-like muscarinic antagonist. Trospium is one of his three overactive-bladder drugs (with oxybutynin and solifenacin): blocking M3 in the bladder decreases urgency, frequency and leakage, so the patient urinates less. All of them can cause anti-DUMBBELSS effects such as dry mouth and constipation.',
 quote:'And then we have here trospium, which has that trope in it, so it kinda help you figure out that it\'s atropine-like drug. ... So the goal over here is to stop urination. They all can do that.',
 note:'Green highlight: Decrease urination. This poll is not in the 10/5 audio: after the bladder slides he looked for a clicker question (“Oh, where is the clear question? I don\'t have.”) and ended the class. The key is from the highlighted sheet; it matches what he taught.',
 cite:'PollEV’s Exam 2.pdf poll 15; transcript 10/5; PCOL-Cholinergic-26s.pdf slides 29–30'},

/* ---------------- Poll 16: severe bradycardia ---------------- */
{id:'PE2-028', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'atropine-bradycardia', tags:['poll','pollev','verbatim'], source:'both',
 stem:'If your patient is having severe bradycardia, which of the following drugs would be most beneficial?',
 options:[
  {t:'Carbachol', correct:false, why:'A muscarinic agonist; at M2 it slows the heart further.'},
  {t:'Succinylcholine', correct:false, why:'An Nm agonist used to cause paralysis; it is not given to raise heart rate.'},
  {t:'Atropine', correct:true, why:'Blocking M2 (Gi) in the heart raises heart rate; bradycardia and atrioventricular nodal block are uses of atropine.'},
  {t:'Rocuronium', correct:false, why:'An Nm antagonist that causes paralysis; it does not act at the heart’s M2.'},
  {t:'Neostigmine', correct:false, why:'A cholinesterase inhibitor raises acetylcholine, which adds bradycardia (DUMBBELSS).'}],
 teach:'M2 receptors on the sinoatrial (SA) and atrioventricular (AV) nodes are coupled to Gi and slow the heart. An agonist brings a fast heart rate down; an antagonist brings a slow one up. Atropine, a non-selective muscarinic antagonist, is given for severe bradycardia or AV nodal block.',
 quote:'So these drugs are gonna be given in case if your patient has too much of a tachycardia, we\'re gonna give an agonist to bring it down, or if they have severe bradycardia, we can give an antagonist to bring it up, depending on what we\'re trying to do.',
 note:'Green highlight: Atropine. This poll is not in the 10/5 audio; the key is from the highlighted sheet, and it matches what he taught on 10/5 (“patients with severe low heart rate so we can give atropine to bring their heart rate up”).',
 cite:'PollEV’s Exam 2.pdf poll 16; transcript 10/5; PCOL-Cholinergic-26s.pdf slides 19–20'},

/* ---------------- Poll 17: α1 in the arteries (9/30 bonus) ---------------- */
{id:'PE2-029', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'apply',
 concept:'alpha1-gq-plc-ip3', tags:['poll','pollev','verbatim'], source:'both',
 stem:'Activation of alpha 1 receptors in the arteries by an agonist will produce which of the following?',
 options:[
  {t:'Activation of Gi=>inhibition of AC=>vasodilation', correct:false, why:'Gi inhibiting adenylyl cyclase (AC) belongs to α2 and M2, not α1.'},
  {t:'Activation of Gs=>activation of AC=>vasodilation', correct:false, why:'Gs activating AC belongs to the β receptors (β2 relaxes smooth muscle), not α1.'},
  {t:'Activation of Gq=>activation of PLC=>vasoconstriction', correct:true, why:'His key: α1 is coupled to Gq, which activates phospholipase C (PLC); IP3 raises Ca++ and the arterial smooth muscle constricts.'},
  {t:'Opening of Nm receptors=>Increase in Ca++=>Vasoconstriction', correct:false, why:'Nm is the ion-channel receptor of skeletal muscle; α1 is a G protein–coupled receptor.'},
  {t:'Increase pupil dilation', correct:false, why:'α1 in the eye does cause mydriasis, but the stem asks about α1 in the arteries.'}],
 teach:'On his quick table, α1 sits on the Gq row: phospholipase C (PLC), then inositol trisphosphate (IP3), then a rise in Ca++. A rise in calcium is, as a general rule, a signal for something positive, so arterial smooth muscle constricts. Knowing the receptor and its G protein predicts the effect.',
 quote:'So, what is alpha 1 Kappa 2 on your quick stable? I would say GQ. If it\'s GQ, who is activating PLC and increasing IP3 and calcium, right? So right there, if you know your G protein and your receptor, you already can figure out what it\'s going to be.',
 note:'Green highlight: the Gq option. This is the 9/30 clicker question “for exam 2 for the bonus”. He read it aloud in other words (“So which of the following is most likely to occur when an alpha-1 receptor is activated by norepinephrine, which is a what? An agonist.”) and keyed it by naming Gq and PLC.',
 cite:'PollEV’s Exam 2.pdf poll 17; transcript 9/30; Autonomic Nervous System.pdf slides 4, 31'},

/* ---------------- Poll 18: GI smooth muscle tracing (figure) ---------------- */
{id:'PE2-030', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'verbatim', skill:'figure',
 concept:'gi-tracing-drug-x-atropine', tags:['poll','pollev','verbatim','figure-drill'], source:'both',
 img:'pe2-gi-tracing', imgAlt:'Tracing of GI smooth muscle tone over time: flat baseline, a rise and fall after the first pilocarpine dose, an arrow marked X where tone dips slightly, then no rise after the second pilocarpine dose', imgCap:'GI smooth muscle tone: pilocarpine, drug X at the arrow, then pilocarpine again',
 stem:'The figure below shows tracing of GI smooth muscle in response to pilocarpine before and after drug X. Drug X is most likely to be:',
 options:[
  {t:'Carbachol', correct:false, miss:'direction', why:'A muscarinic agonist would help pilocarpine and raise tone; after X, pilocarpine has no effect at all.'},
  {t:'Neostigmine', correct:false, miss:'direction', why:'A cholinesterase inhibitor makes acetylcholine more potent and would raise GI tone, not abolish the pilocarpine response.'},
  {t:'Rocuronium', correct:false, miss:'class', why:'Rocuronium blocks Nm at skeletal muscle; GI smooth muscle tone is controlled by muscarinic M3 receptors.'},
  {t:'Atropine', correct:true, why:'After X, pilocarpine no longer raises tone: X blocks the muscarinic (M3) receptor that pilocarpine activates. Atropine is a non-selective, reversible muscarinic antagonist.'},
  {t:'Varenicline', correct:false, miss:'class', why:'A partial agonist at α4/β2 Nn receptors in the brain; it does not act on GI smooth muscle muscarinic receptors.'}],
 teach:'Read the tracing in order. Pilocarpine alone raises GI smooth muscle tone (a muscarinic agonist on M3, Gq, ↑Ca++, contraction). Drug X is given at the arrow, tone drifts slightly below the starting line, and the second dose of pilocarpine produces no rise; a drug that removes the response to a muscarinic agonist is a muscarinic antagonist, atropine.',
 quote:'If it\'s in the M3, depending where it is, let\'s say it\'s on the GI tract, I\'m gonna increase motility and tone.',
 note:'On the sheet this poll is a PollEV screenshot with no green highlight. The screenshot shows Atropine as the recorded response, with the student’s handwritten “Ant M3” (M3 antagonist) beside it and “muscarinic agonist (M1, M2, M3)” under the first “Pilocarpine”. The poll is not in the 10/5 audio, so the key rests on the sheet; it matches what he taught about pilocarpine and atropine.',
 cite:'PollEV’s Exam 2.pdf poll 18; transcript 10/5; PCOL-Cholinergic-26s.pdf slides 12–14, 17, 19'},

{id:'PE2-031', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'figure',
 concept:'gi-tracing-pilocarpine-m3', tags:['poll','pollev','figure-drill'], source:'both',
 img:'pe2-gi-tracing', imgAlt:'Tracing of GI smooth muscle tone over time: flat baseline, a rise and fall after the first pilocarpine dose, an arrow marked X where tone dips slightly, then no rise after the second pilocarpine dose', imgCap:'GI smooth muscle tone: pilocarpine, drug X at the arrow, then pilocarpine again',
 stem:'In the tracing below, what does the first dose of pilocarpine do to GI smooth muscle tone, and through which receptor?',
 options:[
  {t:'Raises tone through M3 (Gq)', correct:true, why:'The tracing rises after pilocarpine: a muscarinic agonist on M3 (Gq, PLC, IP3, ↑Ca++) contracts GI smooth muscle, increasing motility and tone.'},
  {t:'Lowers tone through M2 (Gi)', correct:false, miss:'read', why:'The tracing goes up, not down, and GI smooth muscle tone is an M3 effect.'},
  {t:'Raises tone through Nm (ion channel)', correct:false, miss:'class', why:'Pilocarpine has no effect on nicotinic receptors; Nm is at skeletal muscle.'},
  {t:'Lowers tone through α2 (Gi)', correct:false, miss:'read', why:'α2 activation is what decreases GI activity, but pilocarpine is a muscarinic agonist and the tracing goes up.'},
  {t:'No change in tone', correct:false, miss:'read', why:'The tracing clearly rises and falls back after the first pilocarpine dose.'}],
 teach:'Pilocarpine is a non-selective, reversible muscarinic agonist with no effect on nicotinic receptors. In the gastrointestinal (GI) tract, M3 (Gq) raises Ca++ and increases motility and tone, which is the first peak on the tracing. Sympathetic α2 does the opposite (decreased GI activity).',
 quote:'If it\'s in the M3, depending where it is, let\'s say it\'s on the GI tract, I\'m gonna increase motility and tone.',
 cite:'PollEV’s Exam 2.pdf poll 18 (variant); transcript 10/5; PCOL-Cholinergic-26s.pdf slides 12–14; Autonomic Nervous System.pdf slide 31'},

{id:'PE2-032', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'figure',
 concept:'gi-tracing-m3-blocked', tags:['poll','pollev','figure-drill'], source:'both',
 img:'pe2-gi-tracing', imgAlt:'Tracing of GI smooth muscle tone over time: flat baseline, a rise and fall after the first pilocarpine dose, an arrow marked X where tone dips slightly, then no rise after the second pilocarpine dose', imgCap:'GI smooth muscle tone: pilocarpine, drug X at the arrow, then pilocarpine again',
 stem:'In the tracing below, why does the second dose of pilocarpine produce no rise in tone?',
 options:[
  {t:'Drug X blocks the M3 receptors', correct:true, why:'Pilocarpine acts directly on muscarinic M3 receptors; once X occupies them, pilocarpine cannot activate them, so tone does not rise.'},
  {t:'Drug X blocks the Nm receptors', correct:false, miss:'class', why:'Nm is at skeletal muscle; pilocarpine acts on muscarinic receptors of smooth muscle.'},
  {t:'Drug X inhibits cholinesterase', correct:false, miss:'direction', why:'A cholinesterase inhibitor makes acetylcholine more potent, which would raise tone.'},
  {t:'Drug X stops acetylcholine release', correct:false, miss:'class', why:'Stopping acetylcholine release (Botox) does not stop pilocarpine, a direct agonist that binds the muscarinic receptor itself.'},
  {t:'Pilocarpine is broken down by cholinesterase', correct:false, miss:'read', why:'Pilocarpine is not an ester and is not hydrolyzed by the enzyme.'}],
 teach:'Pilocarpine is a direct-acting muscarinic agonist that is not an ester and is not hydrolyzed by cholinesterase. The only way to remove its effect is to block the receptor it binds: a muscarinic antagonist such as atropine. A drug acting before the receptor (less acetylcholine release) or on the enzyme would leave the pilocarpine response in place or raise tone.',
 quote:'What I need you to know is that it does not bind or activate the nicotinic receptors. It only has affinity for the muscarinics. That\'s going to be a very key information for you',
 cite:'PollEV’s Exam 2.pdf poll 18 (variant); transcript 10/5; PCOL-Cholinergic-26s.pdf slides 14, 19; PCOL-NMJ_PCOL_2026s_pptx.pdf slides 46–50'},

{id:'PE2-033', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'figure',
 concept:'gi-tracing-pns-tone', tags:['poll','pollev','figure-drill'], source:'both',
 img:'pe2-gi-tracing', imgAlt:'Tracing of GI smooth muscle tone over time: flat baseline, a rise and fall after the first pilocarpine dose, an arrow marked X where tone dips slightly, then no rise after the second pilocarpine dose', imgCap:'GI smooth muscle tone: pilocarpine, drug X at the arrow, then pilocarpine again',
 stem:'In the tracing below, tone falls slightly below the starting line when drug X is given, before the second pilocarpine dose. Which explains the fall?',
 options:[
  {t:'X blocks the resting PNS tone', correct:true, why:'The GI tract has a predominant parasympathetic (PNS) tone through M3; blocking it lowers tone below the starting line (anti-DUMBBELSS constipation).'},
  {t:'X activates GI M3 receptors', correct:false, miss:'direction', why:'Activating M3 would raise tone, and pilocarpine would still work.'},
  {t:'X blocks Nm receptors in the gut', correct:false, miss:'class', why:'Nm receptors are at skeletal muscle; GI smooth muscle tone is muscarinic.'},
  {t:'X inhibits cholinesterase', correct:false, miss:'direction', why:'More acetylcholine would raise tone, not lower it.'}],
 teach:'At rest the gastrointestinal (GI) tract runs on a predominant parasympathetic (PNS) tone through M3. A muscarinic antagonist blocks that tone as well as any added agonist: tone falls a little when X is given, and pilocarpine then cannot raise it. This is the anti-DUMBBELSS constipation of atropine.',
 quote:'And if you know what the agonist is going to do, what do you think the antagonist is going to do? The opposite, the anti-dumbbells, constipation, can\'t pee, can\'t cry, can\'t sweat, can\'t see, right?',
 cite:'PollEV’s Exam 2.pdf poll 18 (variant); transcript 10/5; PCOL-Cholinergic-26s.pdf slides 13, 19'},

{id:'PE2-034', lecture:'PE2', prof:'Gottlieb', tier:'new', topic:'PE2', sub:'variant', skill:'figure',
 concept:'gi-tracing-other-antagonist', tags:['poll','pollev','figure-drill'], source:'both',
 img:'pe2-gi-tracing', imgAlt:'Tracing of GI smooth muscle tone over time: flat baseline, a rise and fall after the first pilocarpine dose, an arrow marked X where tone dips slightly, then no rise after the second pilocarpine dose', imgCap:'GI smooth muscle tone: pilocarpine, drug X at the arrow, then pilocarpine again',
 stem:'Which of the following could also be drug X in the tracing below?',
 options:[
  {t:'Scopolamine', correct:true, why:'Like atropine, scopolamine is a natural, non-selective, reversible muscarinic antagonist; it blocks GI M3 and gives constipation.'},
  {t:'Bethanechol', correct:false, miss:'direction', why:'A “chol” muscarinic agonist; it would raise GI tone like pilocarpine.'},
  {t:'Neostigmine', correct:false, miss:'direction', why:'A cholinesterase inhibitor raises acetylcholine and increases GI tone.'},
  {t:'Succinylcholine', correct:false, miss:'class', why:'An Nm agonist at skeletal muscle; it does not act on GI smooth muscle M3.'},
  {t:'Botox', correct:false, miss:'class', why:'Stopping acetylcholine release does not stop pilocarpine, which binds the M3 receptor directly.'}],
 teach:'Drug X behaves like a muscarinic antagonist. Atropine and scopolamine are the natural, non-selective, reversible muscarinic antagonists, and any “trop” drug is atropine-like as well. Agonists (the “chol” drugs, pilocarpine) and cholinesterase inhibitors (the -stigmines) would raise tone instead.',
 quote:'So scopolamine is a non-selective muscarinic antagonist, uh, most times we use for motion sickness.',
 cite:'PollEV’s Exam 2.pdf poll 18 (variant); transcript 10/5; PCOL-Cholinergic-26s.pdf slides 11, 17, 24'}
);
