TOPICS.push({id:'PE', name:'PollEV questions', prof:'Gottlieb', lecture:'PE', cite:'PollEV_s.pdf (his polls with his keys)',
  subs:[{id:'verbatim', name:'His polls, word for word', cite:'PollEV_s.pdf'},{id:'variant', name:'Same figure, different point of reference', cite:'PollEV_s.pdf'}]});
QUESTIONS.push(
/* ---------------- Part 1: verbatim polls, keyed as the PDF highlights ---------------- */
{id:'PE-001', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'recall',
 concept:'nds-incorrect-poll', dupOf:'L01-008', tags:['poll','pollev','nds'], source:'both',
 stem:'Which statement is INCORRECT about natural dietary supplements (NDS)?',
 options:[
  {t:'Most of NDS packaging labels state that they can cure diseases', correct:false, why:'Incorrect statement (labels cannot claim a cure), but it is not the only incorrect one.'},
  {t:'NDS are tested by the FDA just like prescription drugs', correct:false, why:'Incorrect statement (NDS are regulated as food, with less FDA oversight), but not the only one.'},
  {t:'NDS have been used for centuries, thus are safe & effective', correct:false, why:'Incorrect statement (long use does not prove safety or efficacy), but not the only one.'},
  {t:'NDS are natural, thus they have a low risk for drug interactions', correct:false, why:'Incorrect statement (herbals interact with prescription and OTC drugs), but not the only one.'},
  {t:'All of the above', correct:true, why:'Every statement is incorrect; 90% of the class chose all of the above and he agreed.'}],
 teach:'All four statements about natural dietary supplements are wrong: labels cannot claim to cure disease, NDS are not tested by the FDA like prescription drugs, centuries of use do not prove safety or efficacy, and natural products can still interact with drugs. His test tip: when two answers other than a select-all are definitely correct, go for all of the above.',
 quote:'90% says all the above. What is the correct answer? I would say all the above, right?',
 cite:'PollEV_s.pdf page 1; transcript 9/22'},

{id:'PE-002', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'recall',
 concept:'potency-correct-poll', dupOf:'L01-016', tags:['poll','pollev','potency'], source:'both',
 stem:'Which statement is CORRECT?',
 options:[
  {t:'The route of administration can affect the potency of a drug', correct:false, why:'Correct statement (route changes bioavailability and apparent potency), but not the only correct one.'},
  {t:'Drugs can bind to a receptor with high affinity than to other receptors', correct:false, why:'Correct statement (a drug binds some receptors with higher affinity than others), but not the only correct one.'},
  {t:'The ability of the drug to reach the site of action can affect it potency', correct:false, why:'Correct statement (a drug that cannot reach its site of action appears less potent), but not the only correct one.'},
  {t:'Ion channels are typically expressed on the cell membranes', correct:false, why:'Correct statement (ion channels are transmembrane proteins), but not the only correct one.'},
  {t:'All the above', correct:true, why:'Every statement is correct; the class answered 100% all the above and he confirmed it.'}],
 teach:'Route of administration and the ability to reach the site of action change a drug’s apparent potency; a drug can bind one receptor with higher affinity than another; ion channels sit in the cell membrane. All four statements hold, so the answer is all the above.',
 quote:'We have 100%, says that it is all the above, uh, that’s the correct answer, right?',
 cite:'PollEV_s.pdf page 1; transcript 9/22'},

{id:'PE-003', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'apply',
 concept:'safety-vs-efficacy', tags:['poll','pollev','efficacy'], source:'both',
 stem:'Which is more important?',
 options:[
  {t:'Safety', correct:true, why:'The keyed answer in his poll file. Safety is the baseline: given two drugs of equal efficacy, pick the safer one.'},
  {t:'Efficacy', correct:false, why:'Not the keyed answer. In class he argued that a drug that does not work wastes the patient’s health and money, but the poll key is safety.'},
  {t:'None of the above', correct:false, why:'He does not treat the choice as irrelevant; safety and efficacy are weighed against each other.'}],
 teach:'His poll key is safety. His spoken rule: if two drugs have equal efficacy, by all means pick the safer drug; a drug that does not do the job should not be taken. When the safe drug does nothing for a fatal disease (fungal pneumonia, cancer), efficacy wins, which is the point of the next poll.',
 quote:'if I have two drugs and one is safer than the other, but they have equal efficacy, by all means pick the safer drug, right?',
 note:'The PDF highlights Safety. In class he never named a keyed answer for this poll; he let students argue, then said that for fungal pneumonia he would choose the most efficacious drug if nothing safer works. The lecture bank (L01-017) keys the fungal-pneumonia version to the efficacious drug. For this poll as written, the PDF key (Safety) wins.',
 cite:'PollEV_s.pdf page 1; transcript 9/22'},

{id:'PE-004', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'apply',
 concept:'safety-vs-efficacy', dupOf:'L01-017', tags:['poll','pollev','efficacy'], source:'both',
 stem:'If your patient has fungal pneumonia, which would you choose?',
 options:[
  {t:'A drug that is very safe, but not efficacious', correct:false, why:'A very safe topical antifungal does nothing for fungal pneumonia; the patient dies of the infection.'},
  {t:'A drug that is very efficacious, but not as safe', correct:true, why:'An azole that may harm the liver a little is worth the risk of surviving rather than dying; 99% of the class agreed.'}],
 teach:'When the safe drug cannot treat the disease, efficacy comes first: a topical antifungal is very safe but will not save a patient with fungal pneumonia, so the drug that may toast the liver a little is the right choice. Cancer drugs are the same case: none are safe, and they are still needed.',
 quote:'If you have a fungal pneumonia, using a topical antifungal, which is very, very safe, it’s not going to really do anything for your patient. Actually, they are going to die of fungal pneumonia.',
 cite:'PollEV_s.pdf page 1; transcript 9/22'},

{id:'PE-005', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'recall',
 concept:'affinity-chemical-bonds', dupOf:'L01-013', tags:['poll','pollev','affinity'], source:'both',
 stem:'Affinity of a drug for the receptor is dependent on the type of chemical bonds it makes.',
 options:[
  {t:'True', correct:true, why:'Affinity is how likely a drug is to bind and stay bound, and that depends on the bonds it forms: covalent, ionic, hydrogen or van der Waals.'},
  {t:'False', correct:false, why:'Treats binding strength as independent of bond type; covalent bonds give the strongest, irreversible binding and weak bonds the least.'}],
 teach:'Affinity is how good a drug is at attaching to and staying on the receptor. The type of bond decides it: covalent bonds are strongest (irreversible), then ionic, hydrogen and van der Waals bonds, which are weaker and reversible.',
 quote:'Remember, affinity is how likely a drug is to bind and stay bound to a receptor, and the binding of a drug to the receptor is going to be depending on what type of bonds they form covalent bonds, hydrogen bonds, ion bonds.',
 cite:'PollEV_s.pdf page 1; transcript 9/23'},

{id:'PE-006', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'tell',
 concept:'efficacy-definition', dupOf:'L01-014', tags:['poll','pollev','efficacy'], source:'both',
 stem:'Efficacy:',
 options:[
  {t:'Is the ability of a drug to bind and stay bound to a receptor', correct:false, why:'That is affinity, not efficacy.'},
  {t:'Is the ability of a cell to increase its number of receptors', correct:false, why:'Receptor number is the cell’s business (a tissue factor), not the drug’s efficacy.'},
  {t:'Is the ability of a drug to change receptor activity/state', correct:true, why:'Efficacy is what the bound drug does to the receptor: activate it (positive) or shut it down (negative).'},
  {t:'Is the ability of a drug to be absorbed at the level of the GI', correct:false, why:'Absorption is pharmacokinetics, not pharmacodynamics.'}],
 teach:'Affinity is binding and staying bound; efficacy is the ability of the drug to change the receptor’s behavior or state. Agonists have positive efficacy, inverse agonists negative efficacy. Receptor number belongs to the cell, and absorption belongs to pharmacokinetics.',
 quote:'The ability to bind and stay bound, that’s affinity. Efficacy is the ability of that drug to change the receptor behavior.',
 cite:'PollEV_s.pdf page 1; transcript 9/23'},

{id:'PE-007', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'tell',
 concept:'voltage-gated-opens-positive', dupOf:'L02-001', tags:['poll','pollev','ion-channels'], source:'both',
 stem:'Which of the following opens when the membrane potential becomes more positive?',
 options:[
  {t:'Passive ion channels', correct:false, why:'Passive channels are always open; nothing has to change for them to stay open.'},
  {t:'Ligand gated channels', correct:false, why:'Ligand-gated channels open when a neurotransmitter or hormone binds them, not in response to membrane potential.'},
  {t:'Ion pumps', correct:false, why:'Pumps use ATP to move ions back toward homeostasis; they do not open with depolarization.'},
  {t:'Ca++ channels', correct:true, why:'Voltage-gated calcium channels depend on membrane potential and open only when the membrane becomes more positive.'},
  {t:'None of the above', correct:false, why:'One listed channel (the voltage-gated Ca++ channel) does open when the membrane potential becomes more positive.'}],
 teach:'Ion channels are classed by what opens them: passive channels are always open, ligand-gated channels open when a ligand binds, voltage-gated channels open when the membrane potential becomes more positive, and pumps use ATP to restore the ion balance. The Ca++ channels here are voltage-gated.',
 quote:'And then we have calcium channels, which are voltage-gated calcium channels that only opens when the membrane becomes more positive, right?',
 cite:'PollEV_s.pdf page 1; transcript 9/23'},

{id:'PE-008', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'figure',
 concept:'gtp-exchange-dissociation', dupOf:'L02-049', tags:['poll','pollev','gpcr'], source:'both',
 img:'pollev-gs-cascade', imgAlt:'Norepinephrine, beta-1 receptor, Gs, adenylate cyclase, cAMP, PKA and calcium in a heart cell', imgCap:'Norepinephrine at the β1 receptor of a heart cell',
 stem:'Rank the sequence of events from 1st to last. Which order is correct?',
 options:[
  {t:'Binding of drug and receptor → alpha s subunit dissociation → AC activation → Increase levels of cAMP → RGS-mediated hydrolysis', correct:true, why:'Binding is always first; the activated receptor lets αs swap GDP for GTP and dissociate, αs activates adenylate cyclase (AC), AC makes cAMP, and the RGS protein ends it by removing the extra phosphate from GTP.'},
  {t:'Alpha s subunit dissociation → Binding of drug and receptor → AC activation → Increase levels of cAMP → RGS-mediated hydrolysis', correct:false, why:'The αs subunit cannot dissociate before the drug binds; binding of drug and receptor is the trigger.'},
  {t:'Binding of drug and receptor → AC activation → alpha s subunit dissociation → Increase levels of cAMP → RGS-mediated hydrolysis', correct:false, why:'AC is activated by the dissociated αs subunit, so αs must dissociate before AC activation.'},
  {t:'Binding of drug and receptor → alpha s subunit dissociation → Increase levels of cAMP → AC activation → RGS-mediated hydrolysis', correct:false, why:'cAMP is made by AC, so AC activation must come before the rise in cAMP.'},
  {t:'Binding of drug and receptor → RGS-mediated hydrolysis → alpha s subunit dissociation → AC activation → Increase levels of cAMP', correct:false, why:'RGS-mediated hydrolysis of GTP is the reversal step that brings α, β and γ back together; it comes last, not second.'}],
 teach:'Forward: norepinephrine binds β1, the receptor activates, αs releases GDP, takes GTP and dissociates, αs activates adenylate cyclase (AC), and cAMP rises to activate PKA and let Ca++ in. Reverse: the extra phosphate on GTP falls off naturally or the RGS protein chops it off, GDP re-forms and α, β and γ reassociate.',
 quote:'we can speed that up by utilizing a protein called the RGS. The RGS is going to come in and it’s going to chop off that extra phosphate out of there. As I remove the extra phosphate, I’m going to go from a GTP triphosphate to a GDP diphosphate. That’s my signal for my alpha and beta and gamma to come back together.',
 note:'The PDF poll is a drag-to-rank item with five events; here it is a single-answer question whose options are orderings, with his order as the key.',
 cite:'PollEV_s.pdf page 1; transcript 9/23'},

{id:'PE-009', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'tell',
 concept:'potency-determinants', dupOf:'L02-033', tags:['poll','pollev','potency'], source:'both',
 stem:'Which of the following is CORRECT?',
 options:[
  {t:'G-proteins are defined and regulated by the beta subunit', correct:false, why:'G proteins are defined by the alpha subunit (αs, αi, αq), not the beta.'},
  {t:'Phospholipase C (PLC) is an example of a second messenger', correct:false, why:'PLC is the effector system; its second messengers are IP3 and calcium.'},
  {t:'Efficacy is defined by the ability of a drug to bind and stay bound to a receptor', correct:false, why:'Binding and staying bound is affinity.'},
  {t:'The potency of a drug is dependent on the affinity, efficacy and # of receptors', correct:true, why:'Potency is the triad: affinity, efficacy and the tissue (how many receptors it has); 94% of the class chose this.'},
  {t:'The higher the Kd, the greater the affinity of a drug for the receptor', correct:false, why:'Reversed: the smaller the dissociation constant (Kd), the greater the affinity.'}],
 teach:'Potency depends on affinity, efficacy and the number of receptors in the tissue. The other statements each swap a definition: G proteins are defined by α, not β; PLC is an effector, not a second messenger; binding and staying bound is affinity; and a higher Kd means lower, not greater, affinity.',
 quote:'94% chose pothesis of a drugs depending on the affinity, the efficacy, and the receptor which binds you, right? So that’s gonna be the correct answer for us.',
 cite:'PollEV_s.pdf page 1; transcript 9/23'},

{id:'PE-010', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'tell',
 concept:'orthosteric-allosteric-poll', dupOf:'L02-015', tags:['poll','pollev','allosteric','phenoxybenzamine'], source:'both',
 stem:'Which of the following is CORRECT?',
 options:[
  {t:'Allosteric agonist compete for the same binding pocket in the receptor', correct:false, why:'Allosteric drugs bind someplace else on the receptor; they do not compete for the orthosteric pocket.'},
  {t:'Allosteric agonist have the highest affinity for the orthosteric binding pocket', correct:false, why:'Allosteric agonists do not bind the orthosteric pocket at all.'},
  {t:'Phenoxybenzamine has higher affinity than prazosin', correct:true, why:'Phenoxybenzamine forms covalent bonds and never comes off (irreversible); prazosin forms weaker, reversible bonds.'},
  {t:'In orthosteric interactions, two drugs can be bound at the same time to the receptor', correct:false, why:'Orthosteric binding is one or the other; only one drug occupies the pocket at a time.'},
  {t:'None of the above', correct:false, why:'One statement is correct: the covalent, irreversible phenoxybenzamine has the higher affinity.'}],
 teach:'Orthosteric drugs compete for the same pocket, so only one can be bound at a time; allosteric drugs bind a different site and do not compete. The drug with the greatest affinity is the one that forms covalent bonds all day long: phenoxybenzamine, the only irreversible drug on the list, beats reversible prazosin.',
 quote:'So which of these can have the highest affinity? Pbenzamine, right? So that would be our correct answer.',
 cite:'PollEV_s.pdf page 1; transcript 9/23'},

{id:'PE-011', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'apply',
 concept:'transporter-blocker-increases-apparent-potency', dupOf:'L03-002', tags:['poll','pollev','potency'], source:'both',
 stem:'A drug inhibits the major transporter involved in the removal of NE from the neuron synapse. What effect would have on the potency of that NE?',
 options:[
  {t:'Decrease', correct:false, why:'Blocking removal leaves more norepinephrine (NE) in the synapse, not less.'},
  {t:'Increase', correct:true, why:'More NE stays in the synapse for longer, so less of it is needed to bind the receptors; NE appears more potent.'},
  {t:'No change', correct:false, why:'The drug never touches the NE receptor, but it changes how much NE is available, which changes apparent potency.'}],
 teach:'The transporter blocker is an indirect antagonist working upstream of the receptor. With reuptake blocked, more norepinephrine stays around for longer and less is needed to produce its effect, so NE appears more potent. This is how the serotonin–norepinephrine reuptake inhibitors (SNRIs) work.',
 quote:'So it’s going to make norepinephrine appear to be more potent because it’s going to require less of it to bind the receptors to produce its effects, right?',
 cite:'PollEV_s.pdf page 1; transcript 9/24'},

{id:'PE-012', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'apply',
 concept:'kd-units', dupOf:'L03-007', tags:['poll','pollev','kd','exam-cue'], source:'both',
 img:'pollev-kd-table', imgAlt:'Table of Kd values for Drug A and Drug B at beta-1, beta-2 and M1 receptors', imgCap:'Dissociation constants (Kd) of two drugs at three receptors',
 stem:'Which of the two drugs is more likely to successfully interact with β2 receptors on the lungs?',
 options:[
  {t:'Drug A', correct:false, why:'Compares only the numbers (1 vs 20) and ignores the units: 1 mM is 10^-3 M, far larger than 20 µM.'},
  {t:'Drug B', correct:true, why:'At β2 the Kd of Drug B is 20 µM (micro = 10^-6), much smaller than Drug A’s 1 mM (milli = 10^-3); the smaller Kd is the higher affinity.'}],
 teach:'Read the units before the numbers: milli is 10^-3, micro is 10^-6, nano is 10^-9. At the β2 receptor Drug B’s Kd of 20 µM is much smaller than Drug A’s 1 mM, so Drug B has the greater affinity. He promised a very similar question with more options on the exam.',
 quote:'Because 20 micromolars is much smaller than 1 millimolar. So if you only focus on the number, you’re going to miss the question in the exam. You’ve got to look at the units as well.',
 cite:'PollEV_s.pdf page 1; transcript 9/24'},

{id:'PE-013', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'recall',
 concept:'covalent-bond-irreversible-affinity', dupOf:'L03-009', tags:['poll','pollev','affinity'], source:'both',
 stem:'Which of the following drug will have the greatest affinity for a receptor?',
 options:[
  {t:'A drug that forms hydrogen bonds with the receptor', correct:false, why:'Hydrogen bonds are weak and reversible; the drug binds and comes off.'},
  {t:'A drug that forms Van der Waal’s bonds with the receptor', correct:false, why:'Van der Waals bonds are the weakest; the drug needs a close fit and still comes off.'},
  {t:'A drug that forms covalent bonds with the receptor', correct:true, why:'A covalent bond at body temperature cannot be broken, so the binding is irreversible: the highest affinity and the smallest Kd.'},
  {t:'A drug that forms ionic bonds with the receptor', correct:false, why:'Ionic bonds are stronger than hydrogen bonds but still reversible.'}],
 teach:'Covalent bonds are the strongest bonds a drug can form. Formed at body temperature they cannot be broken, so the drug is irreversible, has the highest affinity and the smallest dissociation constant (Kd). Ionic, hydrogen and van der Waals bonds are progressively weaker and reversible.',
 quote:'a drug that forms covalent bond at body temperature is gonna be irreversible, right? As such, you won’t be able to break that bond and it’s gonna have the highest affinity and thus the smallest [Kd].',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-014', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'apply',
 concept:'receptor-number-potency', dupOf:'L03-010', tags:['poll','pollev','potency'], source:'both',
 img:'pollev-two-hearts', imgAlt:'Two dishes, one with 10 receptors and one with 100 receptors, each receiving 1000 nM of drug', imgCap:'Same dose of norepinephrine, two receptor numbers',
 stem:'What would happen to the potency of a NE if one increase the number of receptors expressed in a Heart?',
 options:[
  {t:'Decrease the potency of a drug', correct:false, why:'More receptors make binding more likely, not less; this inverts the law of mass action.'},
  {t:'Increase the potency of a drug', correct:true, why:'By the law of mass action more receptors raise the probability of binding, so less norepinephrine is needed for the same effect: it appears more potent.'},
  {t:'No change to the potency of a drug', correct:false, why:'The drug’s affinity and efficacy are unchanged, but potency also depends on the tissue, and the tissue gained receptors.'}],
 teach:'The same 1000 nM of norepinephrine meets 10 receptors in one heart and 100 in the other. More receptors mean a greater statistical chance of binding, so fewer molecules are needed to occupy the same number of receptors and the drug appears more potent; on a graph the curve shifts left. Potency is affinity, efficacy and the tissue.',
 quote:'So the more receptors you have based on the laws of mass action, the greater the statistical probability of binding something. ... Then it’s going to appear to have a greater potency than it does with less receptors.',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-015', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'figure',
 concept:'five-drug-classification', dupOf:'L03-026', tags:['poll','pollev','affinity','exam-cue'], source:'both',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E on a log dose axis with a dotted horizontal line Y', imgCap:'Five drugs, one receptor; Y is a dotted horizontal line',
 stem:'The DRCs below represent the DRC of five different drugs acting on the same receptor. Which drug has the highest affinity?',
 options:[
  {t:'A', correct:true, why:'A is furthest to the left: it needs the smallest dose for an equivalent effect, so it has the smallest Kd and the highest affinity.'},
  {t:'B', correct:false, why:'B reaches the highest maximum (efficacy, read on the y-axis) but lies to the right of A.'},
  {t:'C', correct:false, why:'C lies to the right of A and B, so it needs more drug to produce the same effect.'},
  {t:'D', correct:false, why:'D is to the right and has the lowest plateau; a low curve does not mean high affinity.'},
  {t:'They all have equal efficacy since they all can produce 50% of the effect', correct:false, why:'Crossing the Y line says nothing about efficacy, which is read from each curve’s maximum; the maxima differ.'}],
 teach:'Affinity is read left to right on the x-axis: the curve furthest left has the smallest Kd and the highest affinity, whether or not it reaches 100%. Efficacy is read up and down on the y-axis. He said he will reuse this figure with a different point of reference.',
 quote:'is A the right answer? ... the smallest KD is gonna be further to the left.',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-016', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'calc',
 concept:'kd-units', dupOf:'L03-008', tags:['poll','pollev','kd','exam-cue'], source:'both',
 img:'pollev-kd-table', imgAlt:'Table of Kd values for Drug A and Drug B at beta-1, beta-2 and M1 receptors', imgCap:'Dissociation constants (Kd); the options list four drugs that bind the β1 receptor',
 stem:'Which of the two drugs has the greatest affinity for the beta 1 receptors in the heart?',
 options:[
  {t:'Drug A (Kd = 1 mM)', correct:false, why:'1 mM is 1 × 10^-3 M, the largest Kd but one here; a large Kd means low affinity.'},
  {t:'Drug B (Kd = 20 microM)', correct:false, why:'20 µM is 2 × 10^-5 M, larger than 100 nM; lower affinity than Drug C.'},
  {t:'Drug C (Kd = 100 nM)', correct:true, why:'100 nM is 1 × 10^-7 M, the smallest Kd of the four, so the greatest affinity.'},
  {t:'Drug D (Kd= 1000 M)', correct:false, why:'1000 M is enormous; the largest Kd is the lowest affinity.'}],
 teach:'First know the relationship: the smaller the Kd, the greater the affinity. Then know the units: milli 10^-3, micro 10^-6, nano 10^-9. Take two zeros out of 100 nM and it is 1 × 10^-7 M, the smallest Kd listed, so Drug C has the greatest affinity. He told the class to ignore the table and use the options.',
 quote:'Ignore the table. I have here 5 drugs that bind to the beta 1 receptor. Uh, which of these drugs is going to have the greatest affinity? ... C has 100 moles, which is 1 to -9. So what you’re gonna do is you take two 0s out of that 100, you have 1 times 10 to -7.',
 note:'In the PDF this poll shows the Drug A / Drug B table but its options are four drugs with their own Kd values (A 1 mM, B 20 microM, C 100 nM, D 1000 M); the key is Drug C (Kd = 100 nM). In class he said to ignore the table.',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-017', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'apply',
 concept:'most-efficacious-for-bacteria', dupOf:'L03-027', tags:['poll','pollev','efficacy'], source:'both',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E on a log dose axis with a dotted horizontal line Y', imgCap:'Five drugs, one receptor; Y is a dotted horizontal line',
 stem:'Which of these drugs is most likely to kill 100% of a bacterial colony?',
 options:[
  {t:'A', correct:false, why:'A is the most potent (furthest left) but its maximum is below B’s; it leaves bacteria behind.'},
  {t:'B', correct:true, why:'B reaches the highest maximal effect, so it is the most efficacious drug for killing the whole colony.'},
  {t:'C', correct:false, why:'C plateaus below B; some bacteria survive to grow back.'},
  {t:'D', correct:false, why:'D has the lowest maximum of the five; it kills the least.'},
  {t:'E', correct:false, why:'E plateaus below B and lies furthest right.'}],
 teach:'When the goal is a complete effect, such as killing all the bacteria, choose the most efficacious drug, the one whose curve reaches the highest maximum. A more potent drug with a lower plateau leaves bacteria behind to grow again and come back resistant.',
 quote:'hopefully you pick B because B will kill 100% of the bacteria colon is the most efficacious in doing that job. Why would I take any of the other ones and leave some bacteria behind to grow again and cause the same infection?',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-018', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'figure',
 concept:'five-drug-classification', dupOf:'L03-026', tags:['poll','pollev','efficacy'], source:'both',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E on a log dose axis with a dotted horizontal line Y', imgCap:'Five drugs, one receptor; Y is a dotted horizontal line',
 stem:'Which of these drugs is the least effective?',
 options:[
  {t:'A', correct:false, why:'A has the highest affinity (furthest left); its plateau is well above D’s.'},
  {t:'B', correct:false, why:'B is the most effective: it reaches the highest maximum.'},
  {t:'C', correct:false, why:'C plateaus above D.'},
  {t:'D', correct:true, why:'D has the lowest maximum of the five curves; efficacy is read on the y-axis, and D’s plateau is the lowest.'},
  {t:'E', correct:false, why:'E is furthest right (lowest affinity), but its plateau is higher than D’s; least potent is not least effective.'}],
 teach:'Effectiveness (efficacy) is read on the y-axis from the height of the plateau, not from the position on the x-axis. D has the lowest maximum, so it is the least effective; B has the highest and is the only full agonist. E is the least potent, which is a different question.',
 quote:'What if I ask which of these drugs has the highest efficacy? Which has the lowest efficacy, D as in David, B as in boy for the highest, D for the lowest, right?',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-019', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'recall',
 concept:'full-vs-partial-agonist-summary', dupOf:'L04-046', tags:['poll','pollev','full-agonist'], source:'both',
 stem:'Which of the following is CORRECT about full agonists?',
 options:[
  {t:'Its Emax is 100% of the system’s max response', correct:false, why:'Correct statement (a full agonist gets all the way up to the response), but not the only correct one.'},
  {t:'It has high affinity for receptors in the active state', correct:false, why:'Correct statement (full agonists love active receptors), but not the only correct one.'},
  {t:'It can activate inactive receptors', correct:false, why:'Correct statement (that is its positive efficacy), but not the only correct one.'},
  {t:'A full agonist will shift the DRC of another full agonist to the left', correct:false, why:'Correct statement (two full agonists help each other), but not the only correct one.'},
  {t:'All of the above', correct:true, why:'Every statement is correct: Emax 100%, highest affinity for active receptors, positive efficacy on inactive receptors, and a left shift of another full agonist’s curve.'}],
 teach:'Four facts hold for a full agonist: its Emax is 100% of the system’s response, it has the highest affinity for receptors in the active state, it can activate a receptor it finds inactive, and it shifts the dose–response curve (DRC) of another full agonist to the left, since the two help each other.',
 quote:'I have all the above. Is that the correct answer? Yes, right. It’s Emacs is 100%. It gets all the way up to the response. It has the highest affinity for receptors on the active state. However, if you bind into receptors that are inactive, it can activate them, right? And a full agonist will shift the dose response curve on another full agonist to the left because they’re gonna be helping each other.',
 cite:'PollEV_s.pdf page 2; transcript 9/28'},

{id:'PE-020', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'figure',
 concept:'fa-plus-fa', dupOf:'L04-005', tags:['poll','pollev','full-agonist'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC B is the DRC of an agonist alone, which DRC would best represent that agonist in the presence of another agonist with similar efficacy?',
 options:[
  {t:'A', correct:true, why:'Two agonists of similar efficacy help each other, so the curve moves to the left with the same maximum; A is the only curve left of B.'},
  {t:'B', correct:false, why:'B is the point of reference (agonist alone); a second agonist changes the curve.'},
  {t:'C', correct:false, why:'C is to the right with a lower maximum; the agonist was made less potent and less effective, which a helper never does.'},
  {t:'D', correct:false, why:'D is to the right of B, so the agonist appears less potent; a second agonist helps, it does not compete it down.'},
  {t:'None of the above', correct:false, why:'Curve A does show the left shift that a second agonist of similar efficacy produces.'}],
 teach:'First decide whether the second drug adds to the agonist’s effect or opposes it. A second agonist with similar efficacy helps, so only curves to the left are possible; C, D and E all make the agonist less potent and are eliminated at once. B is a full agonist (100%), and the helped curve is A.',
 quote:'The majority says A, the best answer is A, right? So just by knowing that both drugs are going to work together and help each other, you already can eliminate C, D, and E because those drugs are making my agonist less potent.',
 cite:'PollEV_s.pdf page 2; transcript 9/28'},

{id:'PE-021', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'drug',
 concept:'partial-agonist-table', dupOf:'L04-009', tags:['poll','pollev','albuterol','drug-list'], source:'both',
 stem:'Which of the following drugs is a partial agonist?',
 options:[
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist at α and β receptors.'},
  {t:'Histamine', correct:false, why:'Histamine is a full agonist at H1 and H2 receptors.'},
  {t:'Albuterol', correct:true, why:'Albuterol is the β2 partial agonist on the drug list; it opens the airways just enough without a 100% effect.'},
  {t:'Acetylcholine', correct:false, why:'Acetylcholine is a full agonist at muscarinic and nicotinic receptors.'},
  {t:'Metoprolol', correct:false, why:'Metoprolol is a β1 antagonist; it has no positive efficacy.'}],
 teach:'From the drug list, albuterol is the partial agonist: it produces a positive effect that plateaus below 100%, enough to help an asthma patient breathe. Epinephrine, histamine and acetylcholine are full agonists; metoprolol is a competitive antagonist. He said this question is easy if the drug list has been started.',
 quote:'The majority says albuterol, as we just talked about it, right? That’s a partial agonist, as the other ones are agonist or an antagonist such as metoprolol.',
 note:'The PDF spells the last option "Meotprolol"; corrected to Metoprolol.',
 cite:'PollEV_s.pdf page 2; transcript 9/28'},

{id:'PE-022', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'figure',
 concept:'fa-plus-fa', dupOf:'L04-005', tags:['poll','pollev','full-agonist','epinephrine'], source:'both',
 img:'pollev-abcde-ne-epi', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC B is the DRC of NE binding to the beta 1 receptor alone, which DRC best represents the DRC of NE in the presence of epinephrine?',
 options:[
  {t:'A', correct:true, why:'Norepinephrine (NE) and epinephrine are both full agonists at β1; whichever is bound produces the same effect, so NE appears more potent and its curve moves left.'},
  {t:'B', correct:false, why:'B is NE alone, the point of reference; adding a second full agonist changes the curve.'},
  {t:'C', correct:false, why:'C is right-shifted with a lower maximum; that is what an antagonist does to NE, not what a second full agonist does.'},
  {t:'D', correct:false, why:'D is to the right of B, meaning NE was made less potent; a second full agonist makes NE appear more potent, not less.'},
  {t:'None of the above', correct:false, why:'A shows the left shift that a second full agonist produces.'}],
 teach:'Norepinephrine and epinephrine are both full agonists at the same β1 receptor. Depending on which one is bound, the receptor does the same thing, so each makes the other appear more potent and the curve shifts to the left with the maximum unchanged. Curves to the right (C, D, E) mean the agonist was hindered.',
 quote:'hopefully you’ll pick A again because we have two full agonists, norepinephrine and Epi, that binds to the same receptor and depending on who is bound to it, they’re going to do the same effect. And thus shifting to the left.',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-023', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'figure',
 concept:'allosteric-antagonist-effects', dupOf:'L04-024', tags:['poll','pollev','allosteric'], source:'both',
 img:'pollev-abcde-allo-ant', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC "D" is the DRC of an agonist alone, which curve would best represent agonist "D" in the presence of another and allosteric antagonist that affects the affinity and efficacy of D?',
 options:[
  {t:'A', correct:false, why:'A is far to the left: the agonist was helped, which an antagonist never does.'},
  {t:'B', correct:false, why:'B is to the left of D with the same maximum; that would be an allosteric agonist affecting affinity.'},
  {t:'C', correct:false, why:'C moved left (affinity improved) yet lost its maximum (efficacy reduced); no drug in the world does that.'},
  {t:'D', correct:false, why:'D is the point of reference; the allosteric antagonist changes the curve.'},
  {t:'E', correct:true, why:'Lower affinity shifts the curve to the right and lower efficacy brings the maximum down; E is right of D and plateaus lower.'}],
 teach:'An allosteric antagonist does the opposite of an allosteric agonist. Affecting affinity shifts the curve to the right; affecting efficacy brings the maximum down. Both together give a curve to the right and below the reference: E. A curve that moves left while losing its maximum (C) has no matching drug.',
 quote:'it’s affecting the affinity, so it’s gonna shift to the right and it’s affecting the efficacy, so it’s gonna bring it down. So E would be the best answer. Why is not C? Because C is moving to the left, so is a is a positive to the affinity, but negative to the efficacy. There’s no drug in the world that does that',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-024', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'figure',
 concept:'five-curve-e-loratadine', dupOf:'L04-016', tags:['poll','pollev','loratadine','drug-list'], source:'both',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises below 100%, C stays flat at 50%, D falls part way, E falls to 0%', imgCap:'Figure 1: five drugs given alone, each starting from the 50% baseline',
 stem:'The DRCs below represent the individual DRC of 5 different drugs. DRC "E" most likely represents the DRC of:',
 options:[
  {t:'NE', correct:false, why:'Norepinephrine (NE) is a full agonist; alone it rises from the baseline to 100% (curve A).'},
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist; alone it rises to a plateau below 100% (curve B).'},
  {t:'Loratadine', correct:true, why:'Curve E brings the baseline down to 0%, the signature of an inverse agonist, and loratadine is the inverse agonist on the drug list.'},
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist; alone it rises to 100%.'}],
 teach:'Two steps: classify the curve, then match the drug list. A curve that takes a 50% baseline down to 0% has negative efficacy, so E is an inverse agonist. The only inverse agonist on the list is loratadine, an antihistamine. Full agonists go up to 100%, partial agonists to a lower plateau.',
 quote:'100% takes loratadine. So the first thing you need to understand is that E is what an inverse agonist, right? Why is that? Because it’s bringing the baseline to zero.',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-025', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'figure',
 concept:'allosteric-agonist-affinity-only', dupOf:'L04-018', tags:['poll','pollev','allosteric'], source:'both',
 img:'pollev-abcde-allo-ag', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC "B" is the DRC of an agonist alone, which curve would best represent agonist "B" in the presence of another and allosteric agonist that affect only the affinity?',
 options:[
  {t:'A', correct:true, why:'An allosteric agonist helps, so the curve moves to the left; affinity only means the maximum is untouched, and A is left of B at the same 100%.'},
  {t:'B', correct:false, why:'B is the point of reference; the allosteric agonist changes the curve.'},
  {t:'C', correct:false, why:'C has a lower maximum, so efficacy was changed; the stem says affinity only.'},
  {t:'D', correct:false, why:'D is to the right, so the agonist was made less potent; an allosteric agonist helps.'},
  {t:'E', correct:false, why:'E is right-shifted with a lower maximum; both affinity and efficacy were reduced.'}],
 teach:'Help means more potent, so the curve moves left. Affinity only means the ability to produce the effect is untouched, so the maximum stays at 100%. Curves C and E changed the maximum (efficacy) and are out at once; D is less potent. That leaves A.',
 quote:'Help, which means you’re gonna make the drug more potent, right? And it because it only affects affinity, you’re not affecting the ability to produce its effect, is moving to the left. So drugs C and E are affecting the efficacy. So that immediately should be a no no for you because the effect is not changing. Uh, and D is making less potent.',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-026', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'figure',
 concept:'dotted-line-drug-x-competitive', dupOf:'L04-032', tags:['poll','pollev','competitive'], source:'both',
 img:'pollev-dotted-x', imgAlt:'A dotted concentration-response curve and three solid curves shifted progressively to the right, all reaching 100%', imgCap:'Dotted line: agonist alone; solid lines: agonist with increasing doses of drug X',
 stem:'The dotted line represents the DRC of the agonist alone and the solid lines represent the DRC of the agonist in the presence of increasing doses of drug "X." Drug X is most likely:',
 options:[
  {t:'A full agonist', correct:false, why:'A full agonist would help and move the curve to the left.'},
  {t:'A partial agonist', correct:false, why:'A partial agonist has efficacy and would change the baseline; here the baseline never moves.'},
  {t:'A competitive antagonist', correct:true, why:'Shift to the right with no change to the baseline or the Emax is the competitive antagonist; the class clicked C.'},
  {t:'An irreversible antagonist', correct:false, why:'An irreversible antagonist would lower the Emax; here every curve still reaches 100%.'},
  {t:'An allosteric agonist', correct:false, why:'An allosteric agonist helps the agonist and shifts it to the left.'}],
 teach:'Process of elimination. Helpers (full agonist, allosteric agonist) would shift the curve left: out. A partial agonist has efficacy and would move the baseline: out. An irreversible antagonist would lower the Emax, and the Emax is unchanged: out. What remains, a right shift with baseline and Emax intact, is the competitive antagonist.',
 quote:'Who can you eliminate right away? A full agonist because they’ll move you to the left or an allosteric agonist, right? ... Why a partial agonist? It would affect the baseline, right? It has efficacy. What could this be, uh, irreversible? It’s not changing, right? The Emacs is staying the same, so the best answer here is what? Everybody clicked C as in cat, right?',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-027', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'verbatim', skill:'drug',
 concept:'drug-x-metoprolol', dupOf:'L04-033', tags:['poll','pollev','metoprolol','drug-list'], source:'both',
 img:'pollev-dotted-ne', imgAlt:'A dotted concentration-response curve of norepinephrine and three solid curves shifted progressively to the right, all reaching 100%', imgCap:'Dotted line: norepinephrine alone; solid lines: with increasing doses of drug X',
 stem:'The dotted line represents the DRC of norepinephrine alone and the solid lines represent the DRC of the agonist in the presence of increasing doses of drug "X." Drug X is most likely:',
 options:[
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist; it would shift norepinephrine to the left.'},
  {t:'Albuterol', correct:false, why:'Albuterol is the partial agonist on the list; it has efficacy and would change the baseline.'},
  {t:'Phenoxybenzamine', correct:false, why:'Phenoxybenzamine is the only irreversible antagonist on the list; it would lower the Emax, which stays at 100% here.'},
  {t:'Metoprolol', correct:true, why:'The figure shows a competitive, reversible antagonist (right shift, same baseline and Emax), and metoprolol is the competitive β1 antagonist on the drug list.'},
  {t:'Diazepam', correct:false, why:'Diazepam is the allosteric agonist on the list; it would help norepinephrine and shift it left.'}],
 teach:'Same figure as the previous poll, now with drug names. First read the class (competitive antagonist), then match the list: epinephrine is a full agonist, albuterol the partial agonist, phenoxybenzamine the only irreversible antagonist, diazepam the allosteric agonist, and metoprolol the competitive reversible antagonist.',
 quote:'Hopefully you pick D as in David, metoprolol, because epinephrine is a full agonist. Albuterol is your partial, as you answered previously in the question. Fenoxbenzammine is the only irreversible that is on your list, and diazepam is your allosteric agonist.',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

/* ---------------- Part 2: same figure, different point of reference ---------------- */
/* Five-DRC figure (page 2) */
{id:'PE-028', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure', multi:true,
 concept:'five-drug-classification', dupOf:'L03-038', tags:['poll','pollev','partial-agonist'], source:'both',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E on a log dose axis with a dotted horizontal line Y', imgCap:'Five drugs, one receptor; Y is a dotted horizontal line',
 stem:'The DRCs below represent the DRC of five different drugs acting on the same receptor. Which of these drugs are partial agonists? Select all that apply.',
 options:[
  {t:'A', correct:true, why:'A has the highest affinity but plateaus below B’s maximum; a curve that cannot reach 100% is a partial agonist.'},
  {t:'B', correct:false, why:'B reaches the highest maximum of the system; it is the only full agonist.'},
  {t:'C', correct:true, why:'C plateaus below B, so it is a partial agonist.'},
  {t:'D', correct:true, why:'D has the lowest plateau; it is still a partial agonist.'},
  {t:'E', correct:true, why:'E plateaus below B; being furthest right (lowest affinity) does not change that it is partial.'}],
 teach:'A full agonist reaches 100% of the maximal response; any curve that plateaus below it is a partial agonist, no matter how far left it lies. In this figure only B reaches the top, so A, C, D and E are the partial agonists. For a select-all, pick them all.',
 quote:'Which of these drugs is the full agonist? B, which you are partial. A, C, D, and E. If you can’t get your 100%, you’re not a full agonist, right?',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-029', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'five-drug-classification', tags:['poll','pollev','full-agonist'], source:'both',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E on a log dose axis with a dotted horizontal line Y', imgCap:'Five drugs, one receptor; Y is a dotted horizontal line',
 stem:'The DRCs below represent the DRC of five different drugs acting on the same receptor. Which of these drugs is the full agonist?',
 options:[
  {t:'A', correct:false, why:'A is the most potent (furthest left) but does not reach the highest maximum; potency is not efficacy.'},
  {t:'B', correct:true, why:'B is the only curve that reaches 100% of the system’s response, so it is the only full agonist.'},
  {t:'C', correct:false, why:'C plateaus below B; it is a partial agonist.'},
  {t:'D', correct:false, why:'D has the lowest plateau; it is the least efficacious partial agonist.'},
  {t:'E', correct:false, why:'E plateaus below B and lies furthest right; a partial agonist with the lowest affinity.'}],
 teach:'Full versus partial is decided on the y-axis: only the curve that reaches the system’s maximum is a full agonist. B is the only one; A, C, D and E all stop short. Being furthest left (A) is affinity, a separate reading.',
 quote:'Which of these drugs is the full agonist? B, which you are partial. A, C, D, and E.',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-030', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'five-drug-classification', tags:['poll','pollev','affinity'], source:'both',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E on a log dose axis with a dotted horizontal line Y', imgCap:'Five drugs, one receptor; Y is a dotted horizontal line',
 stem:'The DRCs below represent the DRC of five different drugs acting on the same receptor. Which drug has the lowest affinity?',
 options:[
  {t:'A', correct:false, why:'A is furthest left: the smallest Kd and the highest affinity.'},
  {t:'B', correct:false, why:'B lies second from the left; high affinity and the highest efficacy.'},
  {t:'C', correct:false, why:'C is in the middle of the x-axis.'},
  {t:'D', correct:false, why:'D has the lowest efficacy (y-axis), but E lies further right on the x-axis; lowest efficacy is not lowest affinity.'},
  {t:'E', correct:true, why:'E is furthest to the right: it needs the largest dose for an equivalent effect, so it has the largest Kd and the lowest affinity.'}],
 teach:'Affinity is read on the x-axis. The farther left, the more affinity; the farther right, the more drug is required just to bind enough receptors, so the lowest affinity is the curve furthest right, E. D has the lowest efficacy, which is the y-axis reading.',
 quote:'So the farther to the left you are, the more affinity I’m going to have. The farther the right I am, so drug C has the lowest affinity, does require even more drug just to bind enough receptors and stay bound.',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-031', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'five-drug-classification', dupOf:'L03-037', tags:['poll','pollev','efficacy'], source:'both',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E on a log dose axis with a dotted horizontal line Y', imgCap:'Five drugs, one receptor; Y is a dotted horizontal line',
 stem:'The DRCs below represent the DRC of five different drugs acting on the same receptor. Which drug has the highest efficacy?',
 options:[
  {t:'A', correct:false, why:'A is furthest left (highest affinity) but plateaus below B; that is potency, not efficacy.'},
  {t:'B', correct:true, why:'B reaches the highest maximal response; efficacy is read up and down on the y-axis.'},
  {t:'C', correct:false, why:'C plateaus below B.'},
  {t:'D', correct:false, why:'D has the lowest plateau, the lowest efficacy.'},
  {t:'E', correct:false, why:'E plateaus below B and needs the most drug.'}],
 teach:'Efficacy is measured on the y-axis: the highest plateau is the highest efficacy (B) and the lowest plateau the lowest (D). Affinity is on the x-axis (A highest). Potency combines the two. Answering all three readings from one figure is what he said guarantees points on the exam.',
 quote:'Which has the lowest efficacy, D as in David, B as in boy for the highest, D for the lowest, right?',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-032', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'five-drug-classification', dupOf:'L03-039', tags:['poll','pollev'], source:'both',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E on a log dose axis with a dotted horizontal line Y', imgCap:'Five drugs, one receptor; Y is a dotted horizontal line',
 stem:'The DRCs below represent the DRC of five different drugs acting on the same receptor. Which statement is CORRECT?',
 options:[
  {t:'A has the highest affinity', correct:false, why:'Correct (A is furthest left), but it is not the only correct statement.'},
  {t:'B is the only full agonist', correct:false, why:'Correct (only B reaches the maximum), but it is not the only correct statement.'},
  {t:'D has the lowest efficacy', correct:false, why:'Correct (D has the lowest plateau), but it is not the only correct statement.'},
  {t:'All of the above', correct:true, why:'Affinity is read left to right (A), full versus partial from reaching the maximum (only B), and efficacy from the plateau (D lowest).'}],
 teach:'Three readings from one figure: affinity from the x-axis (furthest left, A), efficacy from the y-axis (highest plateau B, lowest D), and full versus partial agonist from whether the curve reaches 100% (only B). When every statement checks out, choose all of the above.',
 quote:'is A the right answer? ... the smallest KD is gonna be further to the left. ... D as in David, B as in boy for the highest, D for the lowest, right? ... Which of these drugs is the full agonist? B',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

/* A–E response figure (pages 2–3): A left of B at 100%; B 100%; C right of B, plateau ~75%; D right of B at 100%; E furthest right, plateau ~75% */
{id:'PE-033', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'competitive-antagonist-shift', dupOf:'L04-036', tags:['poll','pollev','competitive'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC B is the DRC of a full agonist alone, which DRC best represents that agonist in the presence of a competitive antagonist?',
 options:[
  {t:'A', correct:false, why:'A moved left: the agonist was helped. A competitive antagonist opposes it, so the curve moves right.'},
  {t:'B', correct:false, why:'B is the point of reference; a drug competing for the same receptor changes the curve.'},
  {t:'C', correct:false, why:'C lost its maximum. A competitive antagonist is reversible, so enough agonist outcompetes it and the Emax is unchanged.'},
  {t:'D', correct:true, why:'Shift to the right with the same baseline and the same 100% maximum: the agonist appears less potent but still reaches its Emax.'},
  {t:'E', correct:false, why:'E is right-shifted and lower; a lowered Emax needs an irreversible antagonist or an allosteric antagonist affecting efficacy.'}],
 teach:'A competitive (reversible, surmountable) antagonist competes for the same pocket: the agonist needs a higher dose (shift to the right), the baseline does not move (no efficacy), and the Emax is unchanged since enough agonist outcompetes a drug that binds and comes off. D is the only curve right of B that still reaches 100%.',
 quote:'If you see something that it lowers the Emacs, you know that has to be either an irreversible antagonist or an allosteric antagonist that affects efficacy, right? Those are the only two that can affect the Emacs. Everybody else is competitive. Everybody else is reversible, no change to the Emacs.',
 cite:'PollEV_s.pdf pages 2–3; transcript 9/28'},

{id:'PE-034', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure', multi:true,
 concept:'irreversible-antagonist-curve', tags:['poll','pollev','irreversible'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC B is the DRC of a full agonist alone, which DRCs could represent that agonist in the presence of an irreversible antagonist? Select all that apply.',
 options:[
  {t:'A', correct:false, why:'A moved left; the agonist was helped, which an antagonist never does.'},
  {t:'B', correct:false, why:'B is the agonist alone, the point of reference.'},
  {t:'C', correct:true, why:'C is shifted right with a lower maximum: fewer receptors remain, so the agonist is less potent and cannot reach its Emax.'},
  {t:'D', correct:false, why:'D keeps the 100% maximum, which is the competitive (reversible) antagonist; an irreversible antagonist cannot be outcompeted.'},
  {t:'E', correct:true, why:'E is shifted further right with a lower maximum: a larger dose of the irreversible antagonist removes more receptors.'}],
 teach:'An irreversible antagonist forms covalent bonds and removes receptors from the pool. The agonist needs more drug for the receptors left (shift right) and, once too few remain, cannot reach the maximal response (Emax falls). Both C and E show a right shift with a lower maximum; D keeps its Emax and is competitive.',
 quote:'what is about an irreversible antagonist? What property do they have that should be like red light blinking in your head during the exam? They form covalent bonds which cannot be reversed under their normal metabolic function, right?',
 cite:'PollEV_s.pdf pages 2–3; transcript 9/28'},

{id:'PE-035', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'allosteric-antagonist-effects', dupOf:'L04-050', tags:['poll','pollev','allosteric'], source:'both',
 img:'pollev-abcde-allo-ant', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC B is the DRC of an agonist alone, which curve would best represent agonist B in the presence of an allosteric antagonist that affects only the affinity of B?',
 options:[
  {t:'A', correct:false, why:'A moved left, so the agonist was helped; an antagonist makes its life more difficult.'},
  {t:'B', correct:false, why:'B is the point of reference; the allosteric antagonist changes the curve.'},
  {t:'C', correct:false, why:'C moved right and lost its maximum, so efficacy was affected too; the stem says affinity only.'},
  {t:'D', correct:true, why:'Affinity only: the agonist appears less potent (shift to the right) but still reaches the maximal response at higher doses.'},
  {t:'E', correct:false, why:'E moved right and lost its maximum; both affinity and efficacy were reduced.'}],
 teach:'Whatever the allosteric agonist does, the allosteric antagonist does the opposite. Affinity only: shift to the right without affecting the ability to get the maximal response. Efficacy only: no shift, the maximum falls. Both: right and down. Since the stem says affinity only, any curve whose maximum changed is out.',
 quote:'what would happen to the dose response curve of this agonist in the presence of an allosteric antagonist that only affects affinity? What would you predict to do? It’s gonna shift to the right. Without affecting the ability to get the max response.',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-036', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'competitive-antagonist-shift', tags:['poll','pollev','competitive'], source:'both',
 img:'pollev-abcde-allo-ant', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC "D" is the DRC of a full agonist alone, which curve would best represent agonist "D" in the presence of a competitive antagonist?',
 options:[
  {t:'A', correct:false, why:'A is far to the left; a competitive antagonist makes the agonist less potent, not more.'},
  {t:'B', correct:false, why:'B is left of D; the agonist was helped.'},
  {t:'C', correct:false, why:'C is left of D with a lower maximum; no drug helps affinity while lowering efficacy.'},
  {t:'D (curve does not change)', correct:false, why:'D is the agonist alone; a competitive antagonist shifts the agonist’s curve to the right.'},
  {t:'E', correct:false, why:'E is right of D but its maximum is lower; a competitive antagonist is reversible and never lowers the Emax.'},
  {t:'None of the above', correct:true, why:'A competitive antagonist shifts D to the right with the Emax unchanged, and no curve in the figure lies right of D at 100%.'}],
 teach:'The competitive antagonist rule is fixed: shift to the right, no change to the baseline, no change to the Emax. With D as the reference, the only curve to its right is E, and E has lost its maximum, which only an irreversible antagonist or an efficacy-lowering allosteric antagonist does. So no curve fits: none of the above.',
 quote:'Everybody else is competitive. Everybody else is reversible, no change to the Emacs.',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-037', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'irreversible-antagonist-curve', tags:['poll','pollev','irreversible','phenoxybenzamine'], source:'both',
 img:'pollev-abcde-allo-ant', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC "D" is the DRC of norepinephrine alone, which curve would best represent norepinephrine in the presence of phenoxybenzamine?',
 options:[
  {t:'A', correct:false, why:'A is far to the left: norepinephrine was helped. Phenoxybenzamine is an antagonist.'},
  {t:'B', correct:false, why:'B is left of D with the same maximum; that is a helper (a full agonist or an affinity-only allosteric agonist).'},
  {t:'C', correct:false, why:'C moved left and lost its maximum; no drug does that.'},
  {t:'D', correct:false, why:'D is norepinephrine alone, the point of reference.'},
  {t:'E', correct:true, why:'Phenoxybenzamine is the only irreversible antagonist on the drug list: covalent bonds remove receptors, so the curve shifts right and the Emax falls, which is E.'}],
 teach:'Phenoxybenzamine forms covalent bonds that are not reversed under normal metabolic function, so the receptors it occupies are gone. Norepinephrine needs a higher dose for the receptors that remain (shift right) and cannot reach the maximal response (Emax falls). Right and down from D is E.',
 quote:'Fenoxbenzammine is the only irreversible that is on your list',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-038', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure', multi:true,
 concept:'fa-plus-fa', tags:['poll','pollev','full-agonist'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC D is the DRC of a full agonist alone, which DRCs could represent that agonist in the presence of another full agonist? Select all that apply.',
 options:[
  {t:'A', correct:true, why:'A is left of D with the same 100% maximum: the agonist was helped and appears more potent.'},
  {t:'B', correct:true, why:'B is also left of D at 100%: a second full agonist shifts the curve left without changing the Emax.'},
  {t:'C', correct:false, why:'C is left of D but its maximum is lower; a second full agonist never lowers the Emax.'},
  {t:'D', correct:false, why:'D is the point of reference; a second full agonist changes the curve.'},
  {t:'E', correct:false, why:'E is right-shifted and lower; the agonist was hindered, which a helper never does.'}],
 teach:'Two full agonists at the same receptor help each other: whichever is bound produces the same effect, so the agonist appears more potent (shift left) and the Emax stays at 100%. From D, both A and B show a left shift at the same maximum; C lost its maximum and E was hindered.',
 quote:'a full agonist will shift the dose response curve on another full agonist to the left because they’re gonna be helping each other.',
 cite:'PollEV_s.pdf pages 2–3; transcript 9/28'},

{id:'PE-039', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'allosteric-antagonist-effects', tags:['poll','pollev','allosteric','partial-agonist'], source:'both',
 img:'pollev-abcde-allo-ant', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'If DRC "C" is the DRC of a partial agonist alone, which curve would best represent agonist "C" in the presence of an allosteric antagonist that affects only the affinity of C?',
 options:[
  {t:'A', correct:false, why:'A is to the left and reaches 100%; the agonist was helped and its efficacy raised.'},
  {t:'B', correct:false, why:'B is to the left with a higher maximum; that is help, not antagonism.'},
  {t:'C', correct:false, why:'C is the point of reference; the allosteric antagonist changes the curve.'},
  {t:'D', correct:false, why:'D is to the right but reaches 100%; an antagonist cannot raise a partial agonist’s maximum.'},
  {t:'E', correct:true, why:'E is to the right of C with the same plateau: affinity reduced (less potent), efficacy untouched.'}],
 teach:'Affinity only means the curve moves right and the maximum does not change. C is a partial agonist plateauing at about 75%; the only curve to its right with the same plateau is E. Curves that reach 100% (A, B, D) changed efficacy upward, which an antagonist never does.',
 quote:'It’s gonna shift to the right. Without affecting the ability to get the max response.',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-040', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure', multi:true,
 concept:'partial-agonist-range', tags:['poll','pollev','partial-agonist'], source:'both',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M', imgCap:'Response (% of control) vs [Agonist, M]',
 stem:'The DRCs below represent five different drugs, each given on its own at the same receptor. Which of these drugs are partial agonists? Select all that apply.',
 options:[
  {t:'A', correct:false, why:'A reaches 100%; a full agonist.'},
  {t:'B', correct:false, why:'B reaches 100%; a full agonist.'},
  {t:'C', correct:true, why:'C rises but plateaus at about 75%: a positive effect that cannot reach 100%, so a partial agonist.'},
  {t:'D', correct:false, why:'D reaches 100%, only at a higher concentration; the least potent full agonist, not a partial one.'},
  {t:'E', correct:true, why:'E plateaus at about 75%; a partial agonist with the lowest affinity.'}],
 teach:'A partial agonist has positive efficacy somewhere between 1% and 99% of the system’s maximum. Read the plateau, not the position: C and E stop at about 75%, so both are partial agonists; A, B and D all reach 100% and are full agonists, D simply the least potent of them.',
 quote:'All those are partial agonists because they are above 1 and they less than 99, right? So for your exam, if this is a select hall. You pick it all',
 cite:'PollEV_s.pdf pages 2–3; transcript 9/28'},

/* Figure 1 (page 3): 50% baseline */
{id:'PE-041', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'baseline-reflects-receptor-activity', tags:['poll','pollev','full-agonist','drug-list'], source:'both',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises below 100%, C stays flat at 50%, D falls part way, E falls to 0%', imgCap:'Figure 1: five drugs given alone, each starting from the 50% baseline',
 stem:'The DRCs below represent the individual DRC of 5 different drugs. DRC "A" most likely represents the DRC of:',
 options:[
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist; it rises from the baseline but plateaus below 100% (curve B).'},
  {t:'Metoprolol', correct:false, why:'Metoprolol has affinity but no efficacy; alone it leaves the 50% baseline flat (curve C).'},
  {t:'Loratadine', correct:false, why:'Loratadine is the inverse agonist; it takes the baseline down to 0% (curve E).'},
  {t:'NE', correct:true, why:'Curve A starts at the 50% baseline and rises to 100%, the full agonist, and norepinephrine (NE) is a full agonist on the drug list.'}],
 teach:'The baseline is 50% because half the receptors are active on their own. A full agonist starts there and goes all the way to 100%: curve A. Of the drugs listed, norepinephrine is the full agonist; albuterol is partial, metoprolol a neutral antagonist and loratadine the inverse agonist.',
 quote:'Where would I start? I start at 50 because that’s where my baseline is now, right?',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-042', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'partial-agonist-table', dupOf:'L04-040', tags:['poll','pollev','albuterol','drug-list'], source:'both',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises below 100%, C stays flat at 50%, D falls part way, E falls to 0%', imgCap:'Figure 1: five drugs given alone, each starting from the 50% baseline',
 stem:'The DRCs below represent the individual DRC of 5 different drugs. DRC "B" most likely represents the DRC of:',
 options:[
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist; alone it rises to 100% (curve A).'},
  {t:'Albuterol', correct:true, why:'Curve B rises from the baseline but plateaus below 100%: a partial agonist, and albuterol is the partial agonist on the drug list.'},
  {t:'Metoprolol', correct:false, why:'Metoprolol has no efficacy; alone it gives a flat line at the baseline (curve C).'},
  {t:'Loratadine', correct:false, why:'Loratadine has negative efficacy; it brings the baseline down to 0% (curve E).'}],
 teach:'Classify first, then match. Curve B produces a positive effect but stops short of 100%, so it is a partial agonist (any maximum between 1% and 99%). On the drug list the partial agonist is albuterol, which opens the airways just enough for an asthma patient to breathe.',
 quote:'Albuterol is a partial agonist. You don’t have to open up your airways 100% in order to help somebody with asthma to breathe.',
 cite:'PollEV_s.pdf page 3; transcript 9/24, 9/28'},

{id:'PE-043', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'competitive-antagonist-neutral-alone', dupOf:'L04-039', tags:['poll','pollev','metoprolol','drug-list'], source:'both',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises below 100%, C stays flat at 50%, D falls part way, E falls to 0%', imgCap:'Figure 1: five drugs given alone, each starting from the 50% baseline',
 stem:'The DRCs below represent the individual DRC of 5 different drugs. DRC "C" most likely represents the DRC of:',
 options:[
  {t:'NE', correct:false, why:'Norepinephrine (NE) is a full agonist; alone it rises from 50% to 100% (curve A).'},
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist; alone it rises toward its own plateau below 100% (curve B).'},
  {t:'Metoprolol', correct:true, why:'A flat line at the baseline is a drug with affinity but no efficacy: the neutral competitive antagonist, and metoprolol is the competitive antagonist on the list.'},
  {t:'Loratadine', correct:false, why:'Loratadine is the inverse agonist; alone it brings the baseline down to 0% (curve E).'},
  {t:'Epinephrine', correct:false, why:'Epinephrine is a full agonist; alone it rises to 100%.'}],
 teach:'A competitive antagonist has equal affinity for active and inactive receptors and does not change the balance, so given alone it leaves the baseline where it found it: 50 stays 50. Full and partial agonists go up from the baseline, and the inverse agonist goes down. Metoprolol is the competitive antagonist on the list.',
 quote:'Just a straight line because one is neutral, doesn’t change the balance of the receptors. The other one wants to keep everybody inactive.',
 cite:'PollEV_s.pdf page 3; transcript 9/24, 9/28'},

{id:'PE-044', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'five-curve-e-loratadine', tags:['poll','pollev','loratadine','drug-list'], source:'both',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises below 100%, C stays flat at 50%, D falls part way, E falls to 0%', imgCap:'Figure 1: five drugs given alone, each starting from the 50% baseline',
 stem:'The DRCs below represent the individual DRC of 5 different drugs. DRC "E" most likely represents the DRC of:',
 options:[
  {t:'Prazosin', correct:false, why:'Prazosin is a reversible α1 antagonist: affinity but no efficacy, so alone it leaves the baseline flat (curve C).'},
  {t:'Diphenhydramine', correct:false, why:'Diphenhydramine is a non-selective histamine receptor antagonist on the list; an antagonist alone does not move the baseline.'},
  {t:'Loratadine', correct:true, why:'Curve E takes the 50% baseline down to 0%, negative efficacy, and loratadine is the only inverse agonist on the drug list.'},
  {t:'Albuterol', correct:false, why:'Albuterol is a partial agonist; it rises above the baseline (curve B).'}],
 teach:'Same poll, different distractors. The curve that brings the baseline to zero is the inverse agonist; there is only one inverse agonist to know, the antihistamine loratadine. Antagonists such as prazosin and diphenhydramine have no efficacy and leave the baseline flat; albuterol rises to a partial plateau.',
 quote:'there’s only one inverse agonist you need to know. It’s gonna be an antihistamine. If you know what loratadine is, you know that’s the inverse agonist',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-045', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'baseline-reflects-receptor-activity', tags:['poll','pollev'], source:'both',
 img:'pollev-figure1', imgAlt:'Figure 1: five curves A to E starting from a 50% baseline; A rises to 100%, B rises below 100%, C stays flat at 50%, D falls part way, E falls to 0%', imgCap:'Figure 1: five drugs given alone, each starting from the 50% baseline',
 stem:'The DRCs below represent the individual DRC of 5 different drugs. Which statement is CORRECT about Figure 1?',
 options:[
  {t:'Half of the receptors are active before any drug is given', correct:false, why:'Correct (the baseline is 50%), but it is not the only correct statement.'},
  {t:'A is the only full agonist', correct:false, why:'Correct (only A reaches 100%), but it is not the only correct statement.'},
  {t:'C has affinity but no efficacy', correct:false, why:'Correct (a flat line at the baseline is the neutral antagonist), but it is not the only correct statement.'},
  {t:'E has negative efficacy', correct:false, why:'Correct (E takes the baseline to 0%, an inverse agonist), but it is not the only correct statement.'},
  {t:'All of the above', correct:true, why:'The 50% baseline means half the receptors are active; A alone reaches 100%; C is flat (no efficacy); E goes to 0% (negative efficacy).'}],
 teach:'The starting point tells you the receptor population: a 50% baseline means half the receptors are active on their own. From there a full agonist goes to 100% (A), a partial agonist to a lower plateau (B), a neutral antagonist stays flat (C), and an inverse agonist with negative efficacy goes toward 0% (E).',
 quote:'What if I put the same drug into a different cell that now say perhaps my receptor population is 50/50 ... Where would I start? I start at 50 because that’s where my baseline is now, right?',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

/* Dotted-line figure (page 3) */
{id:'PE-046', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure', multi:true,
 concept:'competitive-antagonist-shift', dupOf:'L04-027', tags:['poll','pollev','competitive'], source:'both',
 img:'pollev-dotted-x', imgAlt:'A dotted concentration-response curve and three solid curves shifted progressively to the right, all reaching 100%', imgCap:'Dotted line: agonist alone; solid lines: agonist with increasing doses of drug X',
 stem:'The dotted line represents the DRC of the agonist alone and the solid lines represent the DRC of the agonist in the presence of increasing doses of drug "X." Which features of the figure identify drug X as a competitive antagonist? Select all that apply.',
 options:[
  {t:'Shift to the right', correct:true, why:'Each dose of X makes the agonist appear less potent; more agonist is needed to outcompete it.'},
  {t:'No change to the Emax', correct:true, why:'X is reversible, so enough agonist outcompetes it and the maximal response is still reached.'},
  {t:'No change to the baseline', correct:true, why:'X has no efficacy of its own; the starting point never moves.'},
  {t:'Symmetrical shifts', correct:true, why:'The shifts follow the law of mass action: each tenfold dose of X needs a tenfold dose of agonist, so the curves are evenly spaced.'},
  {t:'Shift to the left', correct:false, why:'A left shift means the agonist was helped (a full agonist or an allosteric agonist).'},
  {t:'A lower Emax with each dose', correct:false, why:'A falling maximum is the irreversible antagonist; here every curve reaches 100%.'}],
 teach:'The competitive antagonist’s signature: shift to the right (higher ED50, appears less potent), no change to the baseline (no efficacy), no change to the Emax (reversible, so the agonist outcompetes it), and symmetrical shifts by the law of mass action, going toward infinity. Only an irreversible antagonist or an efficacy-lowering allosteric antagonist drops the Emax.',
 quote:'So what would happen if I give now 10 times the dose of my antagonist? Well, I have to increase the dose of my agonist by 10 times in order to outcompete that drug.',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-047', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'apply',
 concept:'drug-x-phenoxybenzamine', tags:['poll','pollev','phenoxybenzamine','irreversible'], source:'both',
 img:'pollev-dotted-ne', imgAlt:'A dotted concentration-response curve of norepinephrine and three solid curves shifted progressively to the right, all reaching 100%', imgCap:'Dotted line: norepinephrine alone; solid lines: with increasing doses of drug X',
 stem:'The dotted line represents the DRC of norepinephrine alone and the solid lines represent the DRC of norepinephrine in the presence of increasing doses of drug "X." If drug X were phenoxybenzamine instead, which statement is CORRECT?',
 options:[
  {t:'The Emax would fall with each dose of X', correct:true, why:'Phenoxybenzamine forms covalent bonds and removes receptors from the pool, so with enough of it norepinephrine can no longer reach its maximal response.'},
  {t:'The solid lines would shift to the left instead', correct:false, why:'A left shift means the agonist’s effect was added to; phenoxybenzamine is an antagonist and makes norepinephrine’s life harder.'},
  {t:'The baseline would rise', correct:false, why:'Phenoxybenzamine has no efficacy of its own; the baseline does not move.'},
  {t:'The figure would not change', correct:false, why:'Metoprolol (reversible) and phenoxybenzamine (irreversible) differ exactly in what happens to the Emax.'}],
 teach:'Phenoxybenzamine is the only irreversible antagonist on the drug list. Its covalent bonds cannot be reversed under normal metabolic function, so each dose removes receptors permanently: the curve still shifts right, the baseline stays, but the Emax falls and can be abolished. A reversible antagonist such as metoprolol never lowers the Emax.',
 quote:'If you see something that it lowers the Emacs, you know that has to be either an irreversible antagonist or an allosteric antagonist that affects efficacy, right?',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

{id:'PE-048', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'recall',
 concept:'antagonist-synonyms', tags:['poll','pollev','competitive'], source:'both',
 img:'pollev-dotted-x', imgAlt:'A dotted concentration-response curve and three solid curves shifted progressively to the right, all reaching 100%', imgCap:'Dotted line: agonist alone; solid lines: agonist with increasing doses of drug X',
 stem:'The dotted line represents the DRC of the agonist alone and the solid lines represent the DRC of the agonist in the presence of increasing doses of drug "X." Which statement is CORRECT about drug X?',
 options:[
  {t:'It is reversible', correct:false, why:'Correct (it binds and comes off, which is why the Emax is unchanged), but not the only correct statement.'},
  {t:'It is surmountable', correct:false, why:'Correct (enough agonist overcomes it), but not the only correct statement.'},
  {t:'It competes with the agonist for the same receptor site', correct:false, why:'Correct (orthosteric competition), but not the only correct statement.'},
  {t:'All of the above', correct:true, why:'Competitive, reversible and surmountable are different names for the same drug, one that competes with the agonist for the same site and comes off.'}],
 teach:'The figure shows a competitive antagonist: right shift, baseline and Emax unchanged. Competitive, reversible and surmountable are three names for the same drug. It competes with the agonist for the same receptor site, binds and comes off, so a higher dose of agonist overcomes it. This is the most common antagonist in clinical practice.',
 quote:'One is competitive antagonist, also known as reversible antagonists, also known as surmountable antagonists, different names for the same drug. They bind and they come off.',
 cite:'PollEV_s.pdf page 3; transcript 9/28'},

/* Kd table (pages 1–2) */
{id:'PE-049', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'apply',
 concept:'kd-units', tags:['poll','pollev','kd'], source:'both',
 img:'pollev-kd-table', imgAlt:'Table of Kd values for Drug A and Drug B at beta-1, beta-2 and M1 receptors', imgCap:'Dissociation constants (Kd) of two drugs at three receptors',
 stem:'Which of the two drugs is more likely to successfully interact with β1 receptors in the heart?',
 options:[
  {t:'Drug A', correct:false, why:'30 µM is 3 × 10^-5 M, three hundred times larger than 100 nM; comparing 30 with 100 ignores the units.'},
  {t:'Drug B', correct:true, why:'At β1 the Kd of Drug B is 100 nM (1 × 10^-7 M), far smaller than Drug A’s 30 µM; the smaller Kd is the greater affinity.'},
  {t:'Both equally', correct:false, why:'The two Kd values differ by a factor of 300 once the units are converted.'},
  {t:'Neither drug binds β1', correct:false, why:'Both have a measured Kd at β1; the question is which binds better.'}],
 teach:'Same table, different row. Nano is 10^-9 and micro is 10^-6, so Drug B’s 100 nM at β1 is much smaller than Drug A’s 30 µM. The smaller the Kd, the greater the affinity, so Drug B is the one more likely to interact with the β1 receptors in the heart.',
 quote:'So, the first thing you need to know is the relationship between KD and affinity. If you know that, you’re halfway through the battle. The next step is, can you know your units?',
 cite:'PollEV_s.pdf pages 1–2; transcript 9/24'},

{id:'PE-050', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'apply',
 concept:'kd-inverse-affinity', tags:['poll','pollev','kd'], source:'both',
 img:'pollev-kd-table', imgAlt:'Table of Kd values for Drug A and Drug B at beta-1, beta-2 and M1 receptors', imgCap:'Dissociation constants (Kd) of two drugs at three receptors',
 stem:'Which of the two drugs has the greater affinity for the M1 receptors in the gut?',
 options:[
  {t:'Drug A', correct:false, why:'Drug A’s Kd at M1 is 250 nM, the same as Drug B’s.'},
  {t:'Drug B', correct:false, why:'Drug B’s Kd at M1 is 250 nM, the same as Drug A’s.'},
  {t:'They have equal affinity', correct:true, why:'Both drugs have a Kd of 250 nM at M1; the same Kd is the same affinity.'},
  {t:'Neither drug binds the M1 receptor', correct:false, why:'Both have a measured Kd at M1, so both bind it.'}],
 teach:'Affinity is read from the Kd, and Kd is inversely proportional to affinity. At the M1 receptor both drugs have a Kd of 250 nM, so their affinities are equal. The table separates the drugs at β1 and β2, not at M1.',
 quote:'So the affinity is going to be inverse proportional to the [Kd].',
 cite:'PollEV_s.pdf pages 1–2; transcript 9/24'},

{id:'PE-051', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'apply',
 concept:'kd-compare-receptors', tags:['poll','pollev','kd'], source:'both',
 img:'pollev-kd-table', imgAlt:'Table of Kd values for Drug A and Drug B at beta-1, beta-2 and M1 receptors', imgCap:'Dissociation constants (Kd) of two drugs at three receptors',
 stem:'For which receptor does Drug B have the greatest affinity?',
 options:[
  {t:'β1 (heart)', correct:true, why:'Drug B’s smallest Kd is 100 nM at β1; the smallest Kd is the greatest affinity.'},
  {t:'β2 (vasculature)', correct:false, why:'20 µM is 2 × 10^-5 M, larger than both 100 nM and 250 nM.'},
  {t:'M1 (gut)', correct:false, why:'250 nM is larger than 100 nM, so β1 wins.'},
  {t:'Equal for all three', correct:false, why:'The three Kd values differ once units are converted.'}],
 teach:'Read down Drug B’s column and convert the units: 100 nM (1 × 10^-7 M) at β1, 20 µM (2 × 10^-5 M) at β2 and 250 nM (2.5 × 10^-7 M) at M1. The smallest Kd is at β1, so that is where Drug B has the greatest affinity.',
 quote:'What is micro? What is the value? 10-6, nano is 10-9, milli is 10-3.',
 cite:'PollEV_s.pdf pages 1–2; transcript 9/24'},

{id:'PE-052', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'apply',
 concept:'kd-compare-receptors', dupOf:'L02-032', tags:['poll','pollev','kd'], source:'both',
 img:'pollev-kd-table', imgAlt:'Table of Kd values for Drug A and Drug B at beta-1, beta-2 and M1 receptors', imgCap:'Dissociation constants (Kd) of two drugs at three receptors',
 stem:'For which receptor does Drug A have the greatest affinity?',
 options:[
  {t:'β1 (heart)', correct:false, why:'30 µM is 3 × 10^-5 M, larger than 250 nM.'},
  {t:'β2 (vasculature)', correct:false, why:'1 mM is 1 × 10^-3 M, the largest Kd in the table and the lowest affinity.'},
  {t:'M1 (gut)', correct:true, why:'Drug A’s smallest Kd is 250 nM (2.5 × 10^-7 M) at M1; the smallest Kd is the greatest affinity.'},
  {t:'Equal for all three', correct:false, why:'The three Kd values differ by orders of magnitude.'}],
 teach:'Read down Drug A’s column and convert: 30 µM at β1, 1 mM at β2, 250 nM at M1. Nano is smaller than micro is smaller than milli, so the smallest Kd, and the greatest affinity, is at the M1 receptor in the gut.',
 quote:'So if you only focus on the number, you’re going to miss the question in the exam. You’ve got to look at the units as well.',
 cite:'PollEV_s.pdf pages 1–2; transcript 9/24'},

{id:'PE-053', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'apply',
 concept:'covalent-bond-irreversible-affinity', tags:['poll','pollev','kd','irreversible'], source:'both',
 stem:'Four drugs bind the beta 1 receptor. Which of these drugs is most likely to be an irreversible antagonist?',
 options:[
  {t:'Drug A (Kd = 1 mM)', correct:false, why:'1 mM is the second-largest Kd here: low affinity, a drug that comes off easily.'},
  {t:'Drug B (Kd = 20 microM)', correct:false, why:'20 µM is larger than 100 nM; lower affinity than Drug C.'},
  {t:'Drug C (Kd = 100 nM)', correct:true, why:'The smallest Kd is the highest affinity, and the highest affinity belongs to the drug that binds covalently and does not come off: the irreversible antagonist.'},
  {t:'Drug D (Kd= 1000 M)', correct:false, why:'1000 M is the largest Kd of all: the lowest affinity.'}],
 teach:'His follow-up to the β1 Kd poll: an irreversible antagonist forms covalent bonds, so it has the highest affinity and the smallest Kd. Among the four, Drug C’s 100 nM (1 × 10^-7 M) is the smallest Kd, so Drug C is the one most likely to be irreversible.',
 quote:'What if I ask you which of these drugs is going to be more likely to be an irreversible antagonist? ... C as in cat, Because it has the smallest KD.',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

/* Two hearts (page 2) */
{id:'PE-054', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'tell', multi:true,
 concept:'receptor-number-potency', dupOf:'L03-011', tags:['poll','pollev','potency'], source:'both',
 img:'pollev-two-hearts', imgAlt:'Two dishes, one with 10 receptors and one with 100 receptors, each receiving 1000 nM of drug', imgCap:'Same dose of norepinephrine, two receptor numbers',
 stem:'The same dose of norepinephrine is given to a heart with 10 receptors and to a heart with 100 receptors. Which of the following stay the same between the two hearts? Select all that apply.',
 options:[
  {t:'The Kd of norepinephrine', correct:true, why:'Kd belongs to the drug–receptor pair; the same drug binds the same receptor, so Kd is unchanged.'},
  {t:'The affinity of norepinephrine', correct:true, why:'The drug did not change, so its affinity did not change.'},
  {t:'The efficacy of norepinephrine', correct:true, why:'What the bound drug does to each receptor is the same in both hearts.'},
  {t:'The potency of norepinephrine', correct:false, why:'Potency rises in the 100-receptor heart: less drug is needed for the same effect.'},
  {t:'The tissue', correct:false, why:'The tissue is exactly what changed; it has ten times more receptors.'}],
 teach:'Adding receptors does not change the drug: its Kd, affinity and efficacy stay the same. What changes is the tissue it acts on, and since potency is affinity, efficacy and the tissue together, potency changes. The body does this itself by up- or down-regulating receptors.',
 quote:'Now it just have more receptors available, so the affinity and efficacy has not changed. What changes the tissue that is working on it.',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

{id:'PE-055', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'receptor-number-potency', dupOf:'L03-042', tags:['poll','pollev','potency'], source:'both',
 img:'pollev-two-hearts', imgAlt:'Two dishes, one with 10 receptors and one with 100 receptors, each receiving 1000 nM of drug', imgCap:'Same dose of norepinephrine, two receptor numbers',
 stem:'The dose–response curve of norepinephrine is drawn in the heart with 10 receptors. Compared with that curve, the curve in the heart with 100 receptors would be:',
 options:[
  {t:'Shifted to the left', correct:true, why:'More receptors mean less norepinephrine is needed for the same effect; a more potent drug sits further left.'},
  {t:'Shifted to the right', correct:false, why:'A right shift means less potent; more receptors make the drug appear more potent, not less.'},
  {t:'Unchanged', correct:false, why:'Affinity and efficacy are unchanged, but the tissue changed and potency with it.'},
  {t:'Lowered to a smaller maximum', correct:false, why:'More receptors do not lower the response; removing receptors (an irreversible antagonist) does that.'}],
 teach:'By the law of mass action, more receptors raise the chance of binding, so a smaller dose of norepinephrine occupies enough receptors for the same effect: the drug appears more potent and its dose–response curve shifts to the left. When he asked the class whether the graph would shift left, the answer was correct.',
 quote:'if that was a graph, right, would that shift to the left? Correct.',
 cite:'PollEV_s.pdf page 2; transcript 9/24'},

/* Gs cascade figure (page 1) */
{id:'PE-056', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'gs-termination', tags:['poll','pollev','gpcr'], source:'both',
 img:'pollev-gs-cascade', imgAlt:'Norepinephrine, beta-1 receptor, Gs, adenylate cyclase, cAMP, PKA and calcium in a heart cell', imgCap:'Norepinephrine at the β1 receptor of a heart cell',
 stem:'Which event reverses the signal in the pathway shown?',
 options:[
  {t:'Binding of drug and receptor', correct:false, why:'Binding is the first step forward, the trigger for everything else.'},
  {t:'Alpha s subunit dissociation', correct:false, why:'αs dissociates after taking up GTP; that is the forward signal, not its reversal.'},
  {t:'AC activation', correct:false, why:'Adenylate cyclase (AC) activation makes cAMP; forward.'},
  {t:'Increase levels of cAMP', correct:false, why:'Rising cAMP activates PKA and lets calcium in; forward.'},
  {t:'RGS-mediated hydrolysis', correct:true, why:'The RGS protein chops the extra phosphate off GTP, giving GDP, which is the signal for α, β and γ to reassociate.'}],
 teach:'The heart should not beat at 160 all the time, so the signal has to be reversed. The phosphate on GTP falls off naturally, or the RGS protein speeds that hydrolysis up. GTP becomes GDP, the α subunit rejoins β and γ, and the cycle can start again; PDE separately chews up the cAMP.',
 quote:'we can speed that up by utilizing a protein called the RGS. The RGS is going to come in and it’s going to chop off that extra phosphate out of there.',
 cite:'PollEV_s.pdf page 1; transcript 9/23'},

{id:'PE-057', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'second-messenger-examples', tags:['poll','pollev','gpcr'], source:'both',
 img:'pollev-gs-cascade', imgAlt:'Norepinephrine, beta-1 receptor, Gs, adenylate cyclase, cAMP, PKA and calcium in a heart cell', imgCap:'Norepinephrine at the β1 receptor of a heart cell',
 stem:'In the pathway shown, which component is the second messenger?',
 options:[
  {t:'NE (norepinephrine)', correct:false, why:'Norepinephrine (NE) is the signal, the first messenger.'},
  {t:'β1 receptor', correct:false, why:'The β1 receptor receives the signal.'},
  {t:'Gs protein', correct:false, why:'Gs is the transducer, the G protein that translates the receptor change.'},
  {t:'AC (adenylate cyclase)', correct:false, why:'Adenylate cyclase (AC) is the effector system that makes the second messenger.'},
  {t:'cAMP', correct:true, why:'Cyclic AMP is made by AC and carries the signal on to PKA; that is the second messenger.'}],
 teach:'Name the parts: norepinephrine is the signal, β1 the receptor, Gs the transducer, adenylate cyclase (AC) the effector system, and cAMP the second messenger it produces. He said the exam will ask for exactly these identifications.',
 quote:'I need you to identify what is a second messenger, what is a transducer, what is a receptor, what is a signal, what is a factor system, the components of that process',
 cite:'PollEV_s.pdf page 1; transcript 9/23'},

{id:'PE-058', lecture:'PE', prof:'Gottlieb', tier:'new', topic:'PE', sub:'variant', skill:'figure',
 concept:'transducer-identify', tags:['poll','pollev','gpcr'], source:'both',
 img:'pollev-gs-cascade', imgAlt:'Norepinephrine, beta-1 receptor, Gs, adenylate cyclase, cAMP, PKA and calcium in a heart cell', imgCap:'Norepinephrine at the β1 receptor of a heart cell',
 stem:'In the pathway shown, which component is the transducer?',
 options:[
  {t:'NE (norepinephrine)', correct:false, why:'Norepinephrine is the signal.'},
  {t:'β1 receptor', correct:false, why:'The β1 receptor binds the signal; the G protein senses the change in the receptor.'},
  {t:'Gs protein', correct:true, why:'The G protein translates the change in receptor conformation into a signal; transducer is a fancy name for translation.'},
  {t:'AC (adenylate cyclase)', correct:false, why:'Adenylate cyclase (AC) is the effector system.'},
  {t:'cAMP', correct:false, why:'cAMP is the second messenger.'}],
 teach:'When norepinephrine activates β1, the G protein senses the change in the receptor’s conformation and translates it, which is why it is called the transducer. It then swaps GDP for GTP, αs dissociates and activates the effector adenylate cyclase, which makes the second messenger cAMP.',
 quote:'As I activate the receptor, the G protein is going to sense that change in the receptor conformation. The receptor structure is going to translate that information, and that’s why we call them the transducer. Fancy name for translation.',
 cite:'PollEV_s.pdf page 1; transcript 9/23'}
);
