/* His practice questions 1–25 (posted before Exam 1), with his keys from the
   graded attempt. Stems and options are his, word for word; question 21 is left
   out because its figure (DRC3.jpg) is not in the file. Figures 2 and the
   dotted-line figure are the same images as his PollEV figures; Figure 1,
   Figure 3, the therapeutic-index curves and the two cell lines are redrawn
   from the values on his images. */
TOPICS.push({id:'PQ', name:'His practice set (1–25)', prof:'Gottlieb', lecture:'PQ',
  cite:'Practice questions 1–25, his keys',
  subs:[
    {id:'verbatim', name:'His questions, word for word', cite:'Practice questions 1–25'}
  ]});
QUESTIONS.push(
{id:'PQ-01', fg:'efficacy', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'recall',
 concept:'efficacy-definition', tags:['poll','pollev','practice'], source:'slide',
 stem:'Efficacy:',
 options:[
  {t:'The effective concentration of an agonist producing 50% maximal response to that particular drug', correct:false, why:'That is the EC50, a measure of potency (read on the x-axis), not efficacy.'},
  {t:'Is the property of a molecule that causes the receptor to change its behavior toward the host (cell)', correct:true, why:'Efficacy is what the bound drug does to the receptor: it changes its behavior. It shows as the height of the curve, the Emax.'},
  {t:'Inversely proportional to the equilibrium of dissociation (K2/K1)', correct:false, why:'That describes affinity: the smaller the Kd, the greater the affinity.'},
  {t:'A measure of the forces that cause a molecule to bind and stay bound to the receptor', correct:false, why:'Binding and staying bound is affinity, set by the bonds the drug forms.'}],
 teach:'Three words, three readings of a curve. Affinity: how well the drug binds and stays bound (Kd, the bonds). Efficacy: what the bound drug does to the receptor, changing its behavior (the height, Emax). Potency: the dose needed for the effect (EC50 or ED50, the x-axis). The EC50 option is the potency distractor.',
 cite:'Practice questions 1–25, question 1'},

{id:'PQ-02', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'figure',
 concept:'indirect-downstream-curve', tags:['poll','pollev','practice'], source:'slide',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'D is the agonist alone',
 stem:'The figure below represents the DRC of an agonist DRC "D" alone (point of reference) or in the presence of other drugs. Which DRC would best represent the agonist in the presence of an indirect antagonist that binds and inhibit a second messenger in this receptor signalling cascade?',
 options:[
  {t:'C', correct:false, miss:'direction', why:'C is to the left of D: the agonist was helped. Blocking a second messenger makes life more difficult.'},
  {t:'B', correct:false, miss:'direction', why:'B is to the left of D, the helping direction.'},
  {t:'A', correct:false, miss:'direction', why:'A is the farthest left, the most helped curve.'},
  {t:'E', correct:true, why:'Right of D with a lower top: the receptor still binds the agonist, but the cascade beneath it is cut, so more agonist is needed and the full response can no longer be reached.'}],
 teach:'An indirect antagonist that works downstream, on the cascade after the receptor, cuts the signal the receptor sends. The agonist curve moves right and its top falls, because no amount of agonist restores a second messenger that is being inhibited. Compare the upstream reuptake blocker, which moves the curve left.',
 cite:'Practice questions 1–25, question 2'},

{id:'PQ-03', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'recall',
 concept:'affinity-bond-factors', tags:['poll','pollev','practice'], source:'slide',
 stem:'The affinity of a drug for a receptor depends on________',
 options:[
  {t:'The shape of the drug molecule', correct:false, why:'True, but not the only factor listed.'},
  {t:'The isomer conformation', correct:false, why:'True, but not the only factor listed.'},
  {t:'The size of the drug molecule', correct:false, why:'True, but not the only factor listed.'},
  {t:'all the above', correct:true, why:'Shape, size, isomer and functional groups all decide which bonds the drug can form, and the bonds decide affinity.'},
  {t:'The type of functional groups it possesses', correct:false, why:'True, but not the only factor listed.'}],
 teach:'Affinity depends on the bonds the drug forms with the receptor, and the bonds depend on how the molecule fits: its shape, size, isomer and functional groups.',
 cite:'Practice questions 1–25, question 3'},

{id:'PQ-04', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'recall',
 concept:'allosteric-antagonist-site', tags:['poll','pollev','practice'], source:'slide',
 stem:'Antagonists are ligands that interfere with the interaction between an agonist and a receptor. One class of antagonist is known as Allosteric Antagonists because these drugs produce ____________________',
 options:[
  {t:'a non-competitive antagonism that can increase the affinity and/or efficacy of an agonist', correct:false, why:'An antagonist lowers, not raises, the agonist\'s affinity or efficacy.'},
  {t:'a competitive antagonism affecting affinity or efficacy of an agonist', correct:false, why:'Competitive means the same pocket; an allosteric drug binds elsewhere.'},
  {t:'their actions by binding to the receptor at a site that is different from the agonist binding site', correct:true, why:'Allosteric means a second site on the receptor, away from the agonist pocket.'},
  {t:'their effect by forming covalent bonds at the same binding pocket as the agonist', correct:false, why:'Covalent bonds in the agonist pocket describe the irreversible antagonist.'},
  {t:'an antagonism that shifts the agonist dose response curve to the left', correct:false, why:'An antagonist shifts the curve right; a left shift is helping.'}],
 teach:'Allosteric = a different site on the same receptor. Orthosteric = the agonist\'s own pocket. An allosteric antagonist lowers the agonist\'s affinity, efficacy or both, and because its site fills up, its shifts shrink and stop.',
 cite:'Practice questions 1–25, question 4'},

{id:'PQ-05', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'apply',
 concept:'potency-ed50', tags:['poll','pollev','practice'], source:'slide',
 stem:'Hydromorphone is 8-10 times more potent than morphine. Both drugs bind to the same receptor, "mu" opioid receptor, and can produce maximal analgesia. Which of the following statements concerning morphine and hydromorphone is true?',
 options:[
  {t:'Morphine has a larger ED50 and thus, a less potent analgesic than hydromorphone', correct:true, why:'Less potent means more dose for the same effect: a larger ED50.'},
  {t:'Hydromorphone has less affinity, but greater efficacy than morphine', correct:false, why:'Both reach maximal analgesia, so their efficacy is the same; the difference is potency.'},
  {t:'Morphine is given IV, thus a less potent analgesic than hydromorphone which is given orally', correct:false, why:'The stem says nothing about routes; the statement adds facts.'},
  {t:'Hydromorphone is a more potent analgesic because it has a greater efficacy than morphine', correct:false, why:'Potency and efficacy are separate: equal maximal analgesia means equal efficacy.'},
  {t:'Hydromorphone is a more effective analgesic because it has a lower bioavailability than morphine', correct:false, why:'Lower bioavailability would lower apparent potency, and the efficacies are equal.'}],
 teach:'"More potent" and "smaller ED50" always belong to the same drug. Both opioids reach maximal analgesia, so their efficacy is equal; hydromorphone needs 8–10 times less dose, so morphine has the larger ED50.',
 cite:'Practice questions 1–25, question 5'},

{id:'PQ-06', fg:'competitive', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'drug',
 concept:'drug-x-metoprolol', tags:['poll','pollev','practice','metoprolol'], source:'slide',
 graph:{curves:[{label:'A', ec:-1.4, emax:100}, {label:'B', ec:-0.2, emax:100}, {label:'C', ec:0.8, emax:100}, {label:'D', ec:0.9, emax:65}], x:'Log [Agonist]', y:'response (fraction of max)', caption:'Figure 1 (redrawn): B is epinephrine alone; C is right of B with the same top; D is right of B with a lower top.'},
 stem:'If curve "B" is the representative dose response curve (DRC) of Epinephrine alone, which DRC would best describe Epi in the presence of metoprolol?',
 options:[
  {t:'A', correct:false, why:'A is to the left: epinephrine was helped.'},
  {t:'C', correct:true, why:'Metoprolol is a reversible β1 antagonist: a right shift with the same top.'},
  {t:'D', correct:false, why:'A lower top needs receptors taken out (irreversible) or efficacy cut (allosteric on efficacy).'},
  {t:'B', correct:false, why:'B is epinephrine alone; metoprolol does change the curve.'}],
 teach:'Metoprolol competes in the pocket and comes off, so enough epinephrine wins it back: right shift, same Emax, baseline unchanged.',
 cite:'Practice questions 1–25, question 6'},

{id:'PQ-07', fg:'shift-allo-antagonist', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'figure',
 concept:'allosteric-antagonist-effects', tags:['poll','pollev','practice'], source:'slide',
 graph:{curves:[{label:'A', ec:-1.4, emax:100}, {label:'B', ec:-0.2, emax:100}, {label:'C', ec:0.8, emax:100}, {label:'D', ec:0.9, emax:65}], x:'Log [Agonist]', y:'response (fraction of max)', caption:'Figure 1 (redrawn): B is epinephrine alone.'},
 stem:'If curve "B" is the representative dose response curve (DRC) of Epinephrine alone, which DRC would best describe Epi in the presence of ligand, HBG420 (1 µM), assuming it is an allosteric antagonist that affects efficacy and affinity?',
 options:[
  {t:'D', correct:true, why:'Affinity down moves the curve right; efficacy down lowers the top. D does both.'},
  {t:'B', correct:false, why:'B is epinephrine alone.'},
  {t:'A', correct:false, why:'A is to the left, the helping direction.'},
  {t:'C', correct:false, why:'C moves right with the same top: affinity only, not efficacy.'}],
 teach:'Read the stem for which property the allosteric drug changes. Affinity only: right shift, same top. Efficacy only: lower top, no shift. Both: right and down.',
 cite:'Practice questions 1–25, question 7'},

{id:'PQ-08', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'figure',
 concept:'potency-lowest', tags:['poll','pollev','practice'], source:'slide',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Figure 2',
 stem:'Based on figure 2, which drug (A, B, C, D, or E) has the lowest potency?',
 options:[
  {t:'E', correct:true, why:'E is the farthest right: it needs the most drug, the largest ED50.'},
  {t:'B', correct:false, miss:'potency', why:'B is the tallest, which is efficacy, not potency.'},
  {t:'D', correct:false, miss:'potency', why:'D is right of A, B and C but left of E.'},
  {t:'A', correct:false, miss:'potency', why:'A is the farthest left, the most potent.'},
  {t:'C', correct:false, miss:'potency', why:'C sits in the middle of the dose axis.'}],
 teach:'Potency is read left to right: the farther right, the more drug needed, the less potent.',
 cite:'Practice questions 1–25, question 8'},

{id:'PQ-09', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'figure', multi:true,
 concept:'efficacy-highest', tags:['poll','pollev','practice'], source:'slide',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Figure 2',
 stem:'Based on figure 2, which drug(s) (A, B, C, D, or E) has the greatest efficacy? Select all that apply.',
 options:[
  {t:'C', correct:false, miss:'efficacy', why:'C plateaus near 75%.'},
  {t:'B', correct:true, why:'B reaches the top.'},
  {t:'D', correct:true, why:'D reaches the top, even though it is less potent.'},
  {t:'E', correct:false, miss:'efficacy', why:'E plateaus near 75%.'},
  {t:'A', correct:true, why:'A reaches the top.'}],
 teach:'Efficacy is read up and down: A, B and D share the highest top. Position on the dose axis does not change it.',
 cite:'Practice questions 1–25, question 9'},

{id:'PQ-10', fg:'shift-allo-agonist', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'figure',
 concept:'allosteric-agonist-affinity-only', tags:['poll','pollev','practice'], source:'slide',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'Figure 2: E is drug X alone',
 stem:'Based on figure 2, if "E" is the DRC of an agonist (Drug X) alone, which DRC (A, B, C, D, or E) would represent Drug X in the presence of an allosteric agonist that affects affinity but not efficacy?',
 options:[
  {t:'C', correct:true, why:'Left of E with the same top (about 75%): more affinity, same efficacy.'},
  {t:'D', correct:false, miss:'efficacy', why:'D is left of E but taller: efficacy changed too.'},
  {t:'B', correct:false, miss:'efficacy', why:'B is left and taller: affinity and efficacy.'},
  {t:'A', correct:false, miss:'efficacy', why:'A is far left and taller: efficacy changed.'},
  {t:'E', correct:false, miss:'direction', why:'E is drug X alone.'}],
 teach:'Affinity only = a sideways move with the same top. Drug X is a partial agonist (top about 75%), and an allosteric agonist on affinity moves it left without raising that top.',
 cite:'Practice questions 1–25, question 10'},

{id:'PQ-11', fg:'potency', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'figure',
 concept:'four-drug-potency-efficacy', tags:['poll','pollev','practice'], source:'slide',
 graph:{curves:[{label:'A', ec:-1.1, emax:80}, {label:'B', ec:-0.5, emax:82}, {label:'C', ec:0.6, emax:100}, {label:'D', ec:1.2, emax:30}], x:'Log dose', y:'fractional response', caption:'Figure 3 (redrawn): A and B top near 0.8, C reaches 1.0, D tops near 0.3.'},
 stem:'Assuming that figure 3 shows the actions of a series of agonist (drugs A-D) that act on the same receptor and same tissue, what statement is correct?',
 options:[
  {t:'Drug A has greater potency and lower efficacy than D', correct:false, why:'A is more potent than D, but A\'s top is higher, so A has greater efficacy.'},
  {t:'Drug C has higher efficacy, but lower potency than B', correct:true, why:'C is right of B (less potent) and taller (more efficacy).'},
  {t:'Drug D has more spare receptors than C', correct:false, why:'Same receptor, same tissue: the spare-receptor pool is the same.'},
  {t:'Drug B has higher efficacy than A and D', correct:false, why:'B and A share about the same top.'}],
 teach:'Compare two curves on both axes separately: left-right for potency, up-down for efficacy. A drug can win one and lose the other.',
 cite:'Practice questions 1–25, question 11'},

{id:'PQ-12', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'recall',
 concept:'indirect-antagonist-definition', tags:['poll','pollev','practice'], source:'slide',
 stem:'Which of the following statements is correct?',
 options:[
  {t:'Full agonists must bind to 100% of receptors in order to evoke an Emax', correct:false, why:'Spare receptors: a full agonist can reach Emax while occupying a fraction of the receptors.'},
  {t:'Down regulation typically occurs when a tissue/person is exposed to an antagonist over a long period of time', correct:false, why:'The body does the opposite: an antagonist up-regulates, an agonist down-regulates.'},
  {t:'Indirect antagonist inhibits the generation of a biological response by interacting with components of the signaling cascade', correct:true, why:'Indirect = not at the receptor, at a component of the cascade upstream or downstream.'},
  {t:'Partial agonists can behave like antagonist when the majority of the receptors are present in the inactive state', correct:false, why:'A partial agonist acts as an antagonist when most receptors are active (high baseline); from an inactive system it acts as an agonist.'},
  {t:'Full agonist have higher affinity for receptors present in the inactive state and can move receptors from active to inactive states', correct:false, why:'That describes the inverse agonist.'}],
 teach:'The partial-agonist trap: it pulls the response toward its own Emax. Below that level (mostly inactive receptors) it acts as an agonist; above it (mostly active receptors) it acts as an antagonist.',
 cite:'Practice questions 1–25, question 12'},

{id:'PQ-13', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'apply', multi:true,
 concept:'baseline-reflects-receptor-activity', tags:['poll','pollev','practice'], source:'slide',
 stem:'Assuming that the greater majority of the receptors are in the inactive conformation (R>>>R*), which of the following statements are true? Select all that apply.',
 options:[
  {t:'An irreversible antagonist would increase the baseline', correct:false, why:'An antagonist has no efficacy; it cannot move the baseline.'},
  {t:'A competitive antagonist would not change the baseline', correct:true, why:'No efficacy, so the baseline stays where it was.'},
  {t:'A full agonist would increase the baseline', correct:true, why:'From a baseline near 0, a full agonist activates receptors and raises the response.'},
  {t:'An inverse agonist would decrease the baseline', correct:false, why:'With R>>>R* the baseline is already about 0; there is nothing to bring down, so it stays at 0.'},
  {t:'A partial agonist would increase the baseline', correct:true, why:'From near 0 a partial agonist rises to its own Emax: up.'}],
 teach:'R>>>R* means almost every receptor is inactive, so the baseline is about 0. Agonists of any strength raise it; antagonists leave it; the inverse agonist has nothing to lower ("Stays at zero because it\'s already doing what I want"). Write the baseline first, then ask what each class does to it.',
 cite:'Practice questions 1–25, question 13'},

{id:'PQ-14', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'recall',
 concept:'partial-agonist-efficacy-order', tags:['poll','pollev','practice'], source:'slide',
 stem:'Partial agonists:',
 options:[
  {t:'Partial agonists have affinity, but no efficacy', correct:false, why:'Affinity with no efficacy is a neutral antagonist.'},
  {t:'Partial agonists have efficacy, but no affinity', correct:false, why:'No drug acts without binding: every class has affinity.'},
  {t:'Partial agonists have higher efficacy than inverse agonist', correct:true, why:'Partial agonist efficacy is positive (1–99%); inverse agonist efficacy is negative.'},
  {t:'Partial agonists have lower affinity, but higher efficacy than full agonist', correct:false, why:'A partial agonist has lower efficacy than a full agonist.'},
  {t:'Partial agonists have higher affinity, but lower efficacy than antagonist', correct:false, why:'An antagonist has zero efficacy, so a partial agonist\'s efficacy is higher.'}],
 teach:'Order the classes by efficacy: inverse agonist (negative) < neutral antagonist (0) < partial agonist (1–99%) < full agonist (100%). Affinity is a separate scale.',
 cite:'Practice questions 1–25, question 14'},

{id:'PQ-15', fg:'ind-ache', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'figure',
 concept:'ache-indirect-left', tags:['poll','pollev','practice','acetylcholine'], source:'slide',
 img:'pollev-five-drc', imgAlt:'Five dose-response curves A to E, effect against log dose, with a dotted horizontal line Y; B reaches the top; A, C and E plateau at the same middle height; D plateaus lowest; left to right A, B, C, D, E', imgCap:'C is acetylcholine alone',
 stem:'If curve C represents the increase of motility of isolated stomach smooth muscle after acetylcholine (Ach) was administered alone, which curve represents the effect of acetylcholine in a preparation pretreated with physostigmine (a drug that inhibits the enzyme involved in Ach breakdown)?',
 options:[
  {t:'Curve C', correct:false, miss:'direction', why:'C is acetylcholine alone.'},
  {t:'Curve E', correct:false, miss:'direction', why:'E is to the right: acetylcholine made weaker.'},
  {t:'Curve B', correct:false, miss:'efficacy', why:'B is left but taller; blocking the enzyme leaves acetylcholine\'s efficacy unchanged.'},
  {t:'Curve D', correct:false, miss:'direction', why:'D is right and lower.'},
  {t:'Curve A', correct:true, why:'Left of C with the same top: more acetylcholine survives to bind, so it looks more potent.'}],
 teach:'Physostigmine blocks acetylcholinesterase, upstream of the receptor. More acetylcholine reaches the receptor, so the curve moves left; the receptor and acetylcholine\'s efficacy are unchanged, so the top stays.',
 cite:'Practice questions 1–25, question 15'},

{id:'PQ-16', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'recall',
 concept:'neutral-antagonist-equal-affinity', tags:['poll','pollev','practice'], source:'slide',
 stem:'Which of the following statements is CORRECT?',
 options:[
  {t:'When comparing drugs, the one with the greatest efficacy will have a smaller ED50', correct:false, why:'ED50 is potency; efficacy does not set it.'},
  {t:'7-transmebrane receceptors are ligand gated ion channels', correct:false, why:'7-transmembrane receptors are G protein–coupled receptors.'},
  {t:'Drugs with a steep slope has the lowest probability of over dosing', correct:false, why:'A steep slope goes from no effect to maximum over a narrow dose range, which makes overdose easier.'},
  {t:'Neutral competitive antagonist have equal affinity for receptors independent of the state, active vs inactive states', correct:true, why:'Equal affinity for R and R* is why it leaves the balance, and the baseline, unchanged.'},
  {t:'If drug "Y" has a 30,000 fold greater potency than drug "X," then it is safer to say that "X" has the smallest EC50', correct:false, why:'More potent means smaller EC50, so Y has the smaller EC50; X has the larger one.'}],
 teach:'The 30,000-fold option is a direction check: the more potent drug always has the smaller EC50. The neutral antagonist binds R and R* equally, so it does not shift the equilibrium.',
 cite:'Practice questions 1–25, question 16'},

{id:'PQ-17', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'apply',
 concept:'pindolol-partial-agonist-two-baselines', tags:['poll','pollev','practice'], source:'slide',
 stem:'Pindolol is an orthosteric partial agonist and norepinephrine (NE) is a full agonist. Both drugs have affinity for the beta 1 adrenergic receptors in the heart. The maximal heart rate NE can produce is 140 beats/minute. Pindolol can evoke an increase of heart rate up to 80 beats/minute. Which of the following is CORRECT?',
 options:[
  {t:'If you patient decide to exercise and he is taking pindolol, the max heart rate it will be able to achieve is 140 beats/minute', correct:false, why:'Pindolol occupies β1 receptors and holds NE back, so 140 is not reached.'},
  {t:'Two correct answers', correct:true, why:'The two correct statements are the resting one (heart rate goes up toward 80) and the NE one (140 is not reached).'},
  {t:'Pindolol likes to bind to inactive receptors and stabilize them in the inactive conformation. Thus, it has negative efficacy', correct:false, why:'That is an inverse agonist. A partial agonist prefers active receptors and has positive efficacy, only less than a full agonist.'},
  {t:'Pindolol will increase the heart rate if given to a patient in the resting state (60 beats/min)', correct:false, why:'Correct statement: from 60, below its own 80, it acts as an agonist. It is one of the two.'},
  {t:'Pindolol will prevent endogenous NE from binding to the beta 1 receptors and prevent your patient\'s heart rate from reaching 140 beats/minute', correct:false, why:'Correct statement: it competes with NE for the pocket and acts as an antagonist above 80. It is one of the two.'}],
 teach:'A partial agonist pulls the response toward its own maximum: up from below (rest, 60 → toward 80), down from above (NE driving toward 140). Positive efficacy, active-state preference; negative efficacy belongs to the inverse agonist.',
 cite:'Practice questions 1–25, question 17'},

{id:'PQ-18', fg:'quantal', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'calc',
 concept:'ti-from-curves', tags:['poll','pollev','practice'], source:'slide',
 graph:{curves:[{label:'effect', ec:-1, emax:100}, {label:'lethal', ec:2, emax:100}], x:'dose (log scale)', y:'percent effect', marks:[{x:-1, y:50, label:'0.1'}, {x:0, y:3, label:'1'}, {x:1, y:99, label:'10'}, {x:2, y:50, label:'100'}], caption:'Redrawn from his figure: dashed lines where his arrows point (0.1, 1, 10, 100).'},
 stem:'What is the therapeutic index of this drug?',
 options:[
  {t:'100', correct:false, why:'Check the division: 100 ÷ 0.1 is 1000.'},
  {t:'1', correct:false, why:'TI is LD50 ÷ ED50, not the ratio of two equal doses.'},
  {t:'1000', correct:true, why:'LD50 ÷ ED50 = 100 ÷ 0.1 = 1000.'},
  {t:'10000', correct:false, why:'One zero too many: 100 ÷ 0.1 = 1000.'},
  {t:'10', correct:false, why:'10 is where the effect curve reaches 100%, not a ratio.'}],
 teach:'TI = LD50 ÷ ED50 (or TD50 ÷ ED50). Read each 50% point on the dose axis: 0.1 for the effect, 100 for death. 100 ÷ 0.1 = 1000. A larger TI means a safer drug compared with another one.',
 cite:'Practice questions 1–25, question 18'},

{id:'PQ-19', fg:'quantal', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'apply',
 concept:'safety-index-overlap', tags:['poll','pollev','practice'], source:'slide',
 graph:{curves:[{label:'effect', ec:-1, emax:100}, {label:'lethal', ec:2, emax:100}], x:'dose (log scale)', y:'percent effect', marks:[{x:-1, y:50, label:'0.1'}, {x:0, y:3, label:'1'}, {x:1, y:99, label:'10'}, {x:2, y:50, label:'100'}], caption:'Redrawn from his figure: dashed lines where his arrows point (0.1, 1, 10, 100).'},
 stem:'Is this drug Safe?',
 options:[
  {t:'Yes, the therapeutic index is high', correct:false, why:'The TI compares the 50% points only. Read the ends: the dose that treats everyone (near 10) is above the dose that starts killing (near 1).'},
  {t:'Can\'t determine, need more data', correct:false, why:'The figure gives both ends of both curves; that is enough.'},
  {t:'No, cannot treat everyone without killing some', correct:true, why:'The curves overlap: ED99 (about 10) is greater than LD1 (about 1).'}],
 teach:'"Is it safe" asks about the ends of the curves, not the middles. The safety index is LD1 ÷ ED99: about 1 ÷ 10 = 0.1 here. Below 1 means the dose that treats every patient already kills some. A TI of 1000 does not change that.',
 cite:'Practice questions 1–25, question 19'},

{id:'PQ-20', fg:'two-state', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'recall',
 concept:'negative-efficacy-inverse-agonist', tags:['poll','pollev','practice'], source:'slide',
 stem:'Which of the following statements is CORRECT?',
 options:[
  {t:'Competitive antagonist have higher affinity for receptors in the inactive state', correct:false, why:'A neutral competitive antagonist has equal affinity for both states.'},
  {t:'Inverse agonist have the capacity to make active receptors into inactive', correct:true, why:'Negative efficacy: it binds active receptors and shuts them off.'},
  {t:'Partial agonist have higher efficacy, but lower affinity than full agonists', correct:false, why:'A partial agonist has lower efficacy than a full agonist.'},
  {t:'Irreversible antagonist bind to a site away from the agonist binding pocket', correct:false, why:'Binding away from the pocket is allosteric; the irreversible antagonist binds covalently in the pocket.'},
  {t:'Full agonist have higher affinity for receptors in the inactive state', correct:false, why:'A full agonist prefers the active state: binding it holds the receptor active.'}],
 teach:'Which state each class prefers: full and partial agonists prefer R* (active), the inverse agonist prefers R (inactive) and turns active ones off, the neutral antagonist binds both equally.',
 cite:'Practice questions 1–25, question 20'},

{id:'PQ-22', fg:'competitive', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'drug',
 concept:'tropicamide-competitive', tags:['poll','pollev','practice','tropicamide'], source:'slide',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'B is acetylcholine alone',
 stem:'DRC "B" represents the DRC of acetylcholine (ACh) alone in the bronchial smooth muscle. Which DRC would best represent ACh in the presence of tropicamide?',
 options:[
  {t:'DRC D', correct:true, why:'Tropicamide is a reversible muscarinic antagonist: right of B with the same top.'},
  {t:'DRC B', correct:false, miss:'class', why:'B is acetylcholine alone.'},
  {t:'DRC C', correct:false, miss:'emax', why:'C is right but lower; a reversible antagonist keeps the top.'},
  {t:'DRC E', correct:false, miss:'emax', why:'E is right and lower.'},
  {t:'DRC A', correct:false, miss:'direction', why:'A is to the left, the helping direction.'}],
 teach:'Name the drug\'s class first: tropicamide is a reversible (competitive) muscarinic antagonist. Then the curve: right, same top.',
 cite:'Practice questions 1–25, question 22'},

{id:'PQ-23', fg:'galpha', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'recall',
 concept:'g-protein-alpha-pathways', tags:['poll','pollev','practice','g-protein'], source:'slide',
 stem:'Which of the following is CORRECT?',
 options:[
  {t:'Activation of Gs leads to the suppression of AC and decreases in cAMP', correct:false, why:'Gs stimulates adenylate cyclase: cAMP goes up.'},
  {t:'Ligand gated ion channels require that the membrane potential becomes less negative in order to open', correct:false, why:'That describes a voltage-gated channel; a ligand-gated channel opens when the ligand binds.'},
  {t:'Activation of Gi leads to inhibition of PLC and decreases in IP3', correct:false, why:'Gi inhibits adenylate cyclase and lowers cAMP; PLC belongs to Gq.'},
  {t:'Activation of Gq produces an activation of the PLC and increases in IP3', correct:true, why:'αq stimulates phospholipase C: IP3 up, then calcium.'},
  {t:'1-Transmembrane receptors are g-proteins and require displacement of the GDP to activate', correct:false, why:'G proteins work with 7-transmembrane receptors; 1-transmembrane receptors are kinases.'}],
 teach:'Gs: AC up, cAMP up. Gi: the same AC inhibited, cAMP down. Gq: PLC up, IP3 and calcium up. The GDP-to-GTP swap is the G protein switching on, one step before the effector.',
 cite:'Practice questions 1–25, question 23'},

{id:'PQ-24', fg:'two-state', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'figure',
 concept:'partial-agonist-two-cell-lines', tags:['poll','pollev','practice'], source:'slide',
 graph:[{curves:[{label:'A', ec:-1.2, emax:100}, {label:'B', ec:-0.6, emax:80}, {label:'C', ec:0, emax:50}, {label:'D', ec:0.6, emax:25}, {label:'E', ec:1.2, emax:0}], base:50, x:'Log [ ]', y:'% effect', caption:'Exp 1: R = R* (half the receptors active, baseline 50%).'},
        {curves:[{label:'A', ec:-1.2, emax:100}, {label:'B', ec:-0.6, emax:80}, {label:'C', ec:0, emax:50}, {label:'D', ec:0.6, emax:25}, {label:'E', ec:1.2, emax:0}], base:100, x:'Log [ ]', y:'% effect', caption:'Exp 2: R << R* (almost every receptor active, baseline 100%).'}],
 stem:'The figure below represents the DRC of five drugs given alone to two different cell lines (exp 1 and exp 2). Based on the data you collected, which of the following is CORRECT?',
 options:[
  {t:'Drug D is an inverse agonist', correct:false, why:'D stops near 25% in both cell lines; an inverse agonist goes all the way to 0. D is a partial agonist.'},
  {t:'Drug B is a partial agonist', correct:true, why:'B rises from 50 to about 80 in Exp 1 and falls from 100 to about 80 in Exp 2: it ends at its own Emax both times.'},
  {t:'Drug A is a competitive antagonist', correct:false, why:'A reaches 100% in both: a full agonist.'},
  {t:'Drug C is a competitive antagonist', correct:false, why:'Flat at 50% in Exp 1 could be an antagonist, but in Exp 2 C falls from 100 to 50. An antagonist would have stayed at 100: C is a partial agonist with 50% efficacy.'}],
 teach:'Read the notation first: R = R* means half active (baseline 50%); R << R* means R is much smaller than R*, so almost all receptors are active (baseline 100%). Then each drug alone ends at its own efficacy: A 100 (full), B about 80, C about 50, D about 25 (all partial), E 0 (inverse). A drug flat at the baseline in one cell line is only proven to be an antagonist if it stays flat in the other.',
 note:'This is the "Figure 2" case from his 9/30 review: "Could you say with certainty that C was a partial agonist?" The second cell line answers it.',
 cite:'Practice questions 1–25, question 24'},

{id:'PQ-25', fg:'competitive', lecture:'PQ', prof:'Gottlieb', tier:'new', topic:'PQ', sub:'verbatim', skill:'drug',
 concept:'drug-x-metoprolol', tags:['poll','pollev','practice','metoprolol'], source:'slide',
 img:'pollev-abcde-similar', imgAlt:'Five concentration-response curves A to E, response as percent of control against agonist concentration from 10^-9 to 10^-3 M; A, B and D reach full height, C and E plateau at about 75%; left to right A, B, C, D, E', imgCap:'B is epinephrine alone',
 stem:'If DRC B represents the DRC of epinephrine on the heart rate, which DRC would best represent the effects of epinephrine in presence of metoprolol?',
 options:[
  {t:'DRC C', correct:false, miss:'emax', why:'C is right but lower; a reversible antagonist keeps the top.'},
  {t:'DRC A', correct:false, miss:'direction', why:'A is to the left, the helping direction.'},
  {t:'DRC E', correct:false, miss:'emax', why:'E is right and lower.'},
  {t:'DRC D', correct:true, why:'Metoprolol is a reversible β1 antagonist: right of B, same top.'}],
 teach:'Same answer pattern as tropicamide with acetylcholine: a reversible antagonist from the drug list moves the agonist right with the same top.',
 cite:'Practice questions 1–25, question 25'}
);
