const TELL_HTML = `
<h2>Tell apart</h2>
<p class="sub">Slide numbers marked ~ were counted from the deck text and may be off by one or two. Pairs that share wording: the feature that separates them and the trap a question sets. Nothing here is scored.</p>
<p class="sub">Notation: R = an inactive receptor, R* = an active receptor. R &gt; R*: most inactive, baseline about 0%. R = R*: half active, baseline 50%. R &lt; R*: most active, baseline about 100%. → = leads to; ↑ = rises; ↓ = falls. Baseline = the response before any drug; Emax = the plateau; FA = full agonist, PA = partial agonist, IA = inverse agonist.</p>
<h3 id="tell-shifts">The shifts at a glance</h3>
<p class="sub">Dashed curve = the agonist alone. Solid = with the second drug. Symmetry of the shifts depends on where the second drug binds, not on the scenario: a drug in the agonist’s pocket (orthosteric) gives equal steps for equal doses; a drug at a second site (allosteric) gives shrinking steps that stop once that site is full. Circle = agonist, square = antagonist, lock = irreversible, small side circle = allosteric.</p>
<table class="reftab"><thead><tr><th style="width:22%">Second drug</th><th>At the receptor</th><th>Shift</th><th>Baseline</th><th>Emax</th></tr></thead><tbody>
<tr><td>Full agonist</td><td>Competes for the same pocket; either one activates</td><td>Left</td><td>Up</td><td>Same</td></tr>
<tr><td>Partial agonist</td><td>Competes for the pocket; activates less</td><td>none</td><td>Ends at the partial agonist’s own Emax (up from low, down from full)</td><td>100% only with the full agonist given alone</td></tr>
<tr><td>Inverse agonist</td><td>Competes; holds the receptor inactive</td><td>Right</td><td>Down to 0</td><td>Same (reversible, so more agonist outcompetes it)</td></tr>
<tr><td>Reversible (competitive) antagonist</td><td>Same pocket, no activation, comes off</td><td>Right, symmetrical, no limit</td><td>Same</td><td>Same</td></tr>
<tr><td>Irreversible antagonist</td><td>Same pocket, covalent, never comes off</td><td>Right</td><td>Same</td><td>Down toward 0 once spare receptors (more than the agonist needs) are used up</td></tr>
<tr><td>Allosteric agonist (positive allosteric modulator, PAM)</td><td>Second site; agonist stays bound</td><td>Left (affinity), asymmetrical, saturable</td><td>Same</td><td>Up only if the agonist was partial</td></tr>
<tr><td>Allosteric antagonist (negative allosteric modulator, NAM)</td><td>Second site; agonist stays bound; reversible</td><td>Right (affinity), asymmetrical, saturable</td><td>Same</td><td>Down if efficacy is affected; never to 0, because the second site saturates</td></tr>
</tbody></table>
<p class="sub">Day 3 slides ~42–~49; Day 4 slides ~13–~55; transcript 9/28. Of the drugs that bind the receptor, only the irreversible antagonist and the allosteric antagonist acting on efficacy lower Emax; off the receptor, a RAS blocker also does (next table).</p>
<div class="pair"><!--FIG:shift-fafa--><!--FIG:shift-fafa-anim--></div>
<div class="pair"><!--FIG:shift-fapa--><!--FIG:shift-fapa-anim--></div>
<div class="pair"><!--FIG:shift-fapa-down--><!--FIG:shift-fapa-down-anim--></div>
<div class="pair"><!--FIG:shift-inverse--><!--FIG:shift-inverse-anim--></div>
<div class="pair"><!--FIG:shift-competitive--><!--FIG:shift-competitive-anim--></div>
<div class="pair"><!--FIG:shift-irreversible--><!--FIG:shift-irreversible-anim--></div>
<div class="pair"><!--FIG:shift-allo-agonist--><!--FIG:shift-allo-agonist-anim--></div>
<div class="pair"><!--FIG:shift-allo-antagonist--><!--FIG:shift-allo-antagonist-anim--></div>
<h3 id="tell-indirect">Indirect antagonists: upstream or downstream</h3>
<p class="sub">The receptor itself is never touched. Upstream drugs change how much agonist reaches it (a transporter or an enzyme); downstream drugs change what happens to the signal after it (phosphodiesterase, PDE, which breaks down cAMP; RAS, a step in the growth cascade). Part 2 pages 4–13, 31; 9/29 lecture.</p>
<table class="reftab"><thead><tr><th style="width:24%">Drug</th><th>Target</th><th>Upstream or downstream</th><th>Agonist’s curve</th></tr></thead><tbody>
<tr><td>Duloxetine (serotonin–norepinephrine reuptake inhibitor, SNRI), cocaine</td><td>Norepinephrine reuptake transporter</td><td>Upstream: more norepinephrine stays in the synapse</td><td>Left, same Emax</td></tr>
<tr><td>Fluoxetine (selective serotonin reuptake inhibitor, SSRI)</td><td>Serotonin reuptake transporter (SERT)</td><td>Upstream: more serotonin stays in the cleft</td><td>Left, same Emax</td></tr>
<tr><td>Physostigmine (any -stigmine)</td><td>Acetylcholinesterase (AChE, the enzyme that breaks down acetylcholine)</td><td>Upstream: acetylcholine is not broken down</td><td>Left, same Emax</td></tr>
<tr><td>Carbidopa</td><td>Enzyme in the gut that breaks down dopa</td><td>Upstream: more dopa reaches the brain (potentiation; no effect alone)</td><td>L-dopa left</td></tr>
<tr><td>Milrinone, caffeine</td><td>Phosphodiesterase (breaks down cAMP)</td><td>Downstream: cAMP builds up behind the same signal</td><td>Left; a partial agonist can reach the full response</td></tr>
<tr><td>Cancer drug X</td><td>RAS in the GEF → RAS → RAF → MEK → ERK cascade</td><td>Downstream: the message is cut after the receptor</td><td>Right and Emax down</td></tr>
</tbody></table>
<div class="pair"><!--FIG:ind-snri--><!--FIG:ind-snri-anim--></div>
<div class="pair"><!--FIG:ind-ssri--><!--FIG:ind-ssri-anim--></div>
<div class="pair"><!--FIG:ind-ache--><!--FIG:ind-ache-anim--></div>
<div class="pair"><!--FIG:ind-carbidopa--><!--FIG:ind-carbidopa-anim--></div>
<div class="pair"><!--FIG:ind-pde--><!--FIG:ind-pde-anim--></div>
<div class="pair"><!--FIG:ind-ras--><!--FIG:ind-ras-anim--></div>
<h3 id="tell-enhance">Addition, synergism, potentiation</h3>
<div class="pair"><!--FIG:enhance--><!--FIG:enhance-anim--></div>
<h3 id="tell-gpcr">The GPCR process and receptor regulation</h3>
<p class="sub">The forward steps and what ends them (Day 1 slides ~51–~54; 9/23 lecture), then what the cell does to the receptor after too much or too little stimulation (Part 2 pages 16–29; 9/29 lecture).</p>
<div class="pair"><!--FIG:gpcr-steps--><!--FIG:gpcr-anim--></div>
<div class="pair"><!--FIG:galpha--><!--FIG:galpha-anim--></div>
<div class="pair"><!--FIG:desens-rapid--><!--FIG:desens-rapid-anim--></div>
<div class="pair"><!--FIG:desens-long--><!--FIG:desens-long-anim--></div>
<div class="pair"><!--FIG:upreg--><!--FIG:upreg-anim--></div>
<div class="pair"><!--FIG:downreg--><!--FIG:downreg-anim--></div>
<!--FIG:reg-chain-->
<h3 id="tell-day1">Day 1 (9/22) &mdash; Pharmacodynamics-Day-1-2026s.pdf</h3>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Slides</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Affinity vs efficacy</td><td>Affinity = how well a drug binds and stays bound (bond types); efficacy = ability to change receptor activity/state (positive or negative)</td><td>Picking "bind and stay bound" for efficacy</td><td>~21, ~37–38</td><td data-q="L01-013">L01-013</td></tr>
<tr><td>Pharmacological vs apparent potency</td><td>Pharmacological: tissue sensitivity, receptor number, receptor activity, affinity, efficacy; apparent adds PK (pharmacokinetics, what the body does to the drug): age, absorption, distribution, elimination, DDI (drug–drug interactions)</td><td>Putting absorption/age/elimination under pharmacological potency</td><td>~22–23, ~27</td><td data-q="L01-015">L01-015</td></tr>
<tr><td>Safety vs efficacy</td><td>If the safe drug does not work, choose the efficacious one; if efficacy is equal, choose the safer</td><td>Choosing "very safe but not efficacious" for fungal pneumonia</td><td>~25–26</td><td data-q="L01-017">L01-017</td></tr>
<tr><td>Occupancy theory vs intrinsic activity vs two-state model</td><td>Occupancy (affinity only) cannot explain antagonists or inverse agonists, because it predicts a response from every occupied receptor; the two-state model (active/inactive receptors, efficacy) can; the names are FYI</td><td>Giving an antagonist efficacy</td><td>~28</td><td data-q="L01-019">L01-019</td></tr>
<tr><td>Inverse agonist vs antagonist</td><td>Inverse agonist shifts receptors to the inactive state (negative efficacy); antagonist binds with zero intrinsic activity (no effect of its own) and does nothing to the receptor</td><td>Calling a drug that inactivates receptors an antagonist</td><td>~28–29</td><td data-q="L01-022">L01-022</td></tr>
<tr><td>Loratadine vs diphenhydramine</td><td>Loratadine = selective H1 inverse agonist; diphenhydramine = non-selective (H1, H2, muscarinic)</td><td>Reversing which is selective</td><td>~29</td><td data-q="L01-023">L01-023</td></tr>
<tr><td>Classify by structure vs by MOA</td><td>Structure (benzothiadiazine ring) does not predict effects; MOA (mechanism of action) + SOA (site of action) (Na+/Cl− symporter antagonist at distal convoluted tubule) predicts diuresis (more urine), hyponatremia (low blood sodium), antihypertensive use</td><td>Predicting decreased urination or increased blood volume</td><td>~32–33</td><td data-q="L01-026">L01-026</td></tr>
<tr><td>Four receptor classes</td><td>Ion channels (L-type Ca++, GABA); 7-TM (7-transmembrane) GPCR, G protein–coupled receptor (α/β adrenergic, 5-HT (serotonin), histamine); 1-TM (1-transmembrane: tyrosine kinases); intracellular (steroid hormones)</td><td>Putting adrenergic or histamine receptors under 1-TM or ion channels</td><td>~35–36</td><td data-q="L01-027">L01-027</td></tr>
<tr><td>Passive vs voltage-gated vs ligand-gated vs pump</td><td>Passive: always open; voltage-gated: open at certain membrane potentials; ligand-gated: usually closed, binding pocket in channel; pump: moves ions against gradient</td><td>Calling the nicotinic receptor voltage-gated</td><td>~40–47</td><td data-q="L01-029">L01-029</td></tr>
<tr><td>Gs (β1, heart) vs Gq (α1, smooth muscle)</td><td>Gs: αs → adenylate cyclase → ATP → cAMP → ↑ heart rate; Gq: αq → PLC (phospholipase C) → PIP2 → IP3 (inositol trisphosphate) → Ca2+ from the ER (endoplasmic reticulum)</td><td>Assigning PLC to β1 or adenylate cyclase to α1</td><td>~51–55</td><td data-q="L01-033">L01-033</td></tr>
</tbody></table>
<div class="pair"><!--FIG:superfamilies--><!--FIG:bonds--></div>
<!--FIG:selectivity-->
<h3 id="tell-day2">Day 2 (9/23) &mdash; Pharmacodynamics-Day_2_2026s copy.pdf</h3>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Slides</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Gαs vs Gαi vs Gαq</td><td>Gαs → AC (adenylate cyclase) → ↑cAMP; Gαi → AC → ↓cAMP; Gαq → PLC (phospholipase C) → ↑IP3, Ca++</td><td>Gαi also uses AC, so it is easy to give it PLC or an increase in cAMP</td><td>~3</td><td data-q="L02-002">L02-002</td></tr>
<tr><td>Covalent vs ionic/hydrogen/van der Waals</td><td>Covalent: irreversible, insurmountable, non-competitive, long duration. Others: reversible, surmountable, competitive</td><td>Reading insurmountable or non-competitive as a different drug from irreversible; for the covalent binder all three names mean the same drug (allosteric antagonists are also called non-competitive)</td><td>~15–16</td><td data-q="L02-011">L02-011</td></tr>
<tr><td>Agonist vs antagonist vs reversible vs irreversible vs allosteric</td><td>Three separate questions, one class name answers all: activates or not; lets go or not; own pocket or second site. Phenoxybenzamine: orthosteric, antagonist, irreversible.</td><td>Reading &ldquo;allosteric agonist&rdquo; or &ldquo;irreversible antagonist&rdquo; as one word; reversible says how the drug leaves, allosteric says where it binds, neither says what it does.</td><td>~18, ~37&ndash;~39; drug list, Table 1</td><td>&mdash;</td></tr>
<tr><td>Orthosteric vs allosteric</td><td>Orthosteric drugs compete for the agonist's own pocket (one or the other); allosteric drugs bind a second site and change the pocket (one and the other)</td><td>Choosing "allosteric agonists compete for the pocket" or "have highest affinity for the orthosteric pocket"</td><td>~18–20, ~39–44</td><td data-q="L02-015">L02-015</td></tr>
<tr><td>Affinity vs efficacy</td><td>Affinity: bind and stay bound (bonds). Efficacy: change receptor state</td><td>Poll distractor "bind and stay bound" is affinity</td><td>~31</td><td data-q="L02-010">L02-010</td></tr>
<tr><td>Transducer vs effector vs second messenger</td><td>Transducer (carries the signal on) = G protein; effector (signal amplifier) = AC, PLC; second messenger (made or released inside the cell) = cAMP, PKA (protein kinase A), PKC (protein kinase C), IP3, Ca++</td><td>PLC called a second messenger; a receptor, AC or calcium channel chosen as a second messenger</td><td>~26–29</td><td data-q="L02-019">L02-019</td></tr>
<tr><td>Full agonist vs partial agonist</td><td>Both have greater affinity for active receptors and can activate inactive ones; full = 100% efficacy, partial = 1–99%</td><td>Thinking a partial agonist cannot activate inactive receptors</td><td>~32–34</td><td data-q="L02-024">L02-024</td></tr>
<tr><td>Inverse agonist vs neutral antagonist</td><td>Inverse: highest affinity for inactive receptors, negative efficacy, shuts off active receptors. Neutral: equal affinity for both states, ε (efficacy) = 0, keeps the state as is</td><td>Expecting both to lower cAMP: in a dish with 50% of receptors active, the inverse agonist takes cAMP to zero and the antagonist leaves it at 50%</td><td>~35–38</td><td data-q="L02-025">L02-025</td></tr>
<tr><td>Indirect antagonist vs receptor/allosteric antagonist</td><td>Indirect antagonists bind components upstream (before) or downstream (after) the receptor (PDE, phosphodiesterase; RAS); they can enhance (caffeine) or suppress (RAS drug) the response</td><td>Calling caffeine a receptor or allosteric antagonist; expecting any "antagonist" to lower the signal</td><td>~40–41</td><td data-q="L02-028">L02-028</td></tr>
<tr><td>Kd vs EC50</td><td>Kd (dissociation constant) = concentration binding 50% of sites (affinity); EC50 = concentration producing 50% of max response (potency)</td><td>Swapping the two definitions; thinking a larger Kd means greater affinity</td><td>~45, ~50, ~57–58</td><td data-q="L02-029">L02-029</td></tr>
</tbody></table>
<h3 id="tell-day3">Day 3 (9/24) &mdash; Pharmacodynamics-Day_3_2026s.pdf</h3>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Slides</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Kd vs EC50/ED50</td><td>Kd is the concentration binding 50% of receptors (binding only); EC50/ED50 is the concentration/dose giving 50% of the maximal response (potency)</td><td>Both are read on the x-axis, but Kd does not take the drug's effect into account</td><td>~3, ~22, ~29</td><td data-q="L03-004">L03-004</td></tr>
<tr><td>EC50 vs ED50</td><td>EC50 = concentration, typically in vitro (in a dish); ED50 = dose, typically in vivo (in a body), where ADME (absorption, distribution, metabolism, excretion) affects apparent potency</td><td>Philosophically the same; swapping in vitro/in vivo</td><td>~8, ~21</td><td data-q="L03-013">L03-013</td></tr>
<tr><td>Affinity vs efficacy on a DRC</td><td>Affinity read on x-axis (left/right); efficacy on y-axis (up/down)</td><td>Reading curve height as affinity</td><td>~16–18</td><td data-q="L03-017">L03-017</td></tr>
<tr><td>Potency vs efficacy</td><td>Potency = smallest EC50/ED50; efficacy = highest maximal response; a partial agonist can be the most potent</td><td>Assuming the most potent drug is also the most efficacious or always preferred</td><td>~22, ~27</td><td data-q="L03-020">L03-020</td></tr>
<tr><td>Equal EC50, different Emax</td><td>With tissue and affinity held constant, the drug with greater efficacy is more potent</td><td>Picking "greater affinity" when affinity is stated equal</td><td>~27</td><td data-q="L03-028">L03-028</td></tr>
<tr><td>More receptors vs changed drug</td><td>More receptors increase potency (shift left) while Kd, affinity and efficacy of the drug are unchanged</td><td>Answering "no change" because the dose is the same, or saying Kd changed</td><td>~7</td><td data-q="L03-010">L03-010</td></tr>
<tr><td>Intrinsic activity vs efficacy</td><td>Intrinsic activity (FA 100% (1), PA 1&ndash;99% (0.01&ndash;0.99), antagonist 0) ignores the tissue; efficacy is more comprehensive and only relative between drugs</td><td>Thinking efficacy can be calculated exactly</td><td>~25–26</td><td data-q="L03-029">L03-029</td></tr>
<tr><td>Full agonist vs partial agonist</td><td>Both have positive efficacy and highest affinity for active-state receptors; only the full agonist reaches 100% of the system's max</td><td>Giving the partial agonist negative efficacy or inactive-state preference</td><td>~41, ~63</td><td data-q="L03-026">L03-026</td></tr>
<tr><td>Threshold vs EC50 vs Emax vs slope</td><td>Threshold = below it no response; EC50 = 50% of max; Emax = ceiling; slope = linear mid-section</td><td>Reading the threshold as the ED50; the ED50 is the dose at half the Emax (“we can divide it by 2”)</td><td>~20–21</td><td data-q="L03-016">L03-016</td></tr>
<tr><td>Steep vs shallow slope</td><td>Steep: narrow dose range from no effect to max; shallow: wider dose range from no effect to max, so more room before a toxic effect</td><td>Picking one as better; his answer was “it depends”: steep goes from no effect to max at once, shallow gives a dose range before toxicity</td><td>~21</td><td data-q="L03-022">L03-022</td></tr>
</tbody></table>
<h3 id="tell-day4">Day 4 (9/28) &mdash; Pharmacodynamics-Day_4_-_5_2026s_pptx.pdf</h3>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Slides</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Full agonist vs partial agonist (two-state)</td><td>Both prefer active receptors, both have positive efficacy, both reversible; only the full agonist reaches 100%, the partial plateaus at 1–99%</td><td>Giving the partial agonist negative efficacy or inactive-state preference</td><td>Day 3 ~32–~41, ~50–~52</td><td data-q="L04-001">L04-001</td></tr>
<tr><td>Partial agonist vs inverse agonist as "antagonists"</td><td>A partial agonist brings a high baseline down only to its own efficacy (a 75% partial stops at 75%); an inverse agonist brings it to 0%</td><td>Expecting a partial agonist to bring the response to zero</td><td>Day 3 ~59–~63; Day 4 ~12</td><td data-q="L04-007">L04-007</td></tr>
<tr><td>Full agonist + full agonist vs full agonist + inverse agonist</td><td>FA + FA: shift left, baseline up, Emax same. FA + IA (inverse agonist): shift right, baseline down to 0, Emax same</td><td>Reading the direction of the shift without first asking whether the second drug helps or hinders</td><td>Day 3 ~42–~49; Day 4 ~13–~22</td><td data-q="L04-004">L04-004</td></tr>
<tr><td>Inverse agonist vs competitive antagonist</td><td>Inverse: highest affinity for inactive receptors, negative efficacy, lowers a raised baseline. Competitive: equal affinity for both states, no efficacy, leaves the baseline alone</td><td>At a baseline of 0% both give the same figure, because there is nothing to lower; a raised baseline (R = R*) is needed to tell them apart</td><td>~4–~12, ~15, ~43–~44</td><td data-q="L04-014">L04-014</td></tr>
<tr><td>Allosteric agonist affecting affinity vs efficacy</td><td>Affinity only: shift left, same max. Efficacy only: no shift, curve rises (partial → full). Both: left and up</td><td>Picking a curve whose maximum changed for an affinity-only drug</td><td>~26–~29, ~42</td><td data-q="L04-018">L04-018</td></tr>
<tr><td>Allosteric antagonist affecting affinity vs efficacy</td><td>Affinity only: shift right, same max. Efficacy only: no shift, max falls. Both: right and down</td><td>Choosing a curve that moves left while losing its maximum ("no drug in the world does that")</td><td>~38–~42</td><td data-q="L04-024">L04-024</td></tr>
<tr><td>Allosteric shifts vs competitive shifts</td><td>Allosteric: asymmetrical (unequal steps), saturable (stop after enough doses, once the second site is full), two drugs bound at once. Competitive: symmetrical (equal steps), continue toward infinity, one or the other</td><td>Expecting equal steps from an allosteric drug</td><td>~30–~34, ~45–~50</td><td data-q="L04-020">L04-020</td></tr>
<tr><td>Chemical vs physiological antagonism</td><td>Chemical: direct interaction between antagonist and agonist (dimercaprol, chelators). Physiological: two agonists at different receptors with opposing effects (ACh, acetylcholine, and Epi, epinephrine, in the heart)</td><td>Calling ACh vs Epi in the heart "competitive"; they use different receptors, so they do not compete</td><td>~35</td><td data-q="L04-021">L04-021</td></tr>
<tr><td>Competitive vs irreversible antagonist names</td><td>Competitive = reversible = surmountable (more agonist overcomes it). Irreversible = insurmountable = nonequilibrium-competitive = non-competitive</td><td>Reading "surmountable" as a property of the irreversible drug</td><td>~36</td><td data-q="L04-022">L04-022</td></tr>
<tr><td>Irreversible antagonist vs allosteric antagonist (both non-competitive)</td><td>Irreversible: covalent, binds and never comes off, can abolish the response to 0. Allosteric: binds elsewhere, reversible, saturates before zero</td><td>Assuming "non-competitive" means one mechanism</td><td>~36–~41, ~51–~54</td><td data-q="L04-025">L04-025</td></tr>
<tr><td>Competitive vs irreversible antagonist on the curve</td><td>Both shift right with the baseline unchanged; only the irreversible lowers the Emax (fewer receptors available)</td><td>Too few shifts make an irreversible look competitive, because spare receptors hold the Emax at first; when Emax is unchanged the best single answer is competitive</td><td>~45–~55</td><td data-q="L04-027">L04-027</td></tr>
<tr><td>Classes that change Emax vs classes that do not</td><td>Of the drugs that bind the receptor, only the irreversible antagonist and the allosteric antagonist affecting efficacy lower Emax; every reversible orthosteric drug leaves Emax alone</td><td>Choosing the inverse agonist as an Emax-lowering drug (it lowers the baseline)</td><td>~21–~22, ~39–~41, ~53–~54</td><td data-q="L04-031">L04-031</td></tr>
<tr><td>Drug X = class vs drug X = drug-list name</td><td>Same figure, two questions: first classify (competitive antagonist), then match to the list (metoprolol; not epinephrine, a full agonist; albuterol, a partial agonist; phenoxybenzamine, irreversible; diazepam, an allosteric agonist)</td><td>Knowing the class but not the drug list, or the reverse</td><td>~24, ~55</td><td data-q="L04-016">L04-016</td></tr>
</tbody></table>
<h3 id="tell-day5">Day 5 (9/29) &mdash; Pharmacodynamics-Day_4_-_5_2026s_pptx Part 2.pdf</h3>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Pages</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Tissue with many receptors vs tissue with few receptors</td><td>Many: agonist more sensitive/potent, antagonist less potent, irreversible antagonist looks competitive (Emax held) at first. Few: agonist less potent, antagonist more potent, Emax drops faster</td><td>Assuming more receptors also make the antagonist stronger</td><td>2–3</td><td data-q="L05-002">L05-002</td></tr>
<tr><td>Irreversible antagonist with spare receptors vs competitive antagonist</td><td>Both shift right at first; only the irreversible eventually lowers the Emax once fewer receptors than the agonist needs remain</td><td>Concluding competitive from the early right shifts alone; only later doses show the Emax falling</td><td>2–3</td><td data-q="L05-004">L05-004</td></tr>
<tr><td>Potency vs efficacy on the five-curve figure</td><td>Potency = ED50 (left is more potent); efficacy = height of the plateau; with equal efficacy the difference is affinity</td><td>Saying B is more potent than A because B is more efficacious</td><td>PollEV 9/29</td><td data-q="L05-005">L05-005</td></tr>
<tr><td>PDE inhibitor vs RAS blocker (both indirect antagonists)</td><td>PDE (phosphodiesterase) inhibitor stops cAMP breakdown, so cAMP rises: agonist more potent, partial may look full. RAS blocker cuts the cascade after the receptor: agonist less potent and less efficacious</td><td>Assuming every indirect antagonist lowers the response</td><td>5–8</td><td data-q="L05-008">L05-008</td></tr>
<tr><td>Indirect antagonist vs allosteric drug</td><td>Indirect: never touches the receptor (transporter, enzyme, PDE, RAS). Allosteric: binds the receptor at a second site</td><td>Poll option "indirect antagonists are allosteric drugs"</td><td>4, 9–13</td><td data-q="L05-010">L05-010</td></tr>
<tr><td>Reuptake blocker (SSRI, selective serotonin reuptake inhibitor; SNRI, serotonin–norepinephrine reuptake inhibitor) vs acetylcholinesterase inhibitor</td><td>Same principle, different target: transporter vs enzyme; both raise the neurotransmitter concentration and shift its curve left without changing Emax</td><td>Expecting the Emax to rise; it does not, because the receptor still sees the same neurotransmitter</td><td>9–13</td><td data-q="L05-011">L05-011</td></tr>
<tr><td>Up-regulation vs down-regulation</td><td>Up: after a chronic antagonist; more spare receptors; agonist more potent. Down: after a chronic agonist; fewer receptors; agonist less potent, like an irreversible antagonist. The body does the opposite of the drug</td><td>"Too much agonist makes the body up-regulate"</td><td>17–18, 20, 25–26</td><td data-q="L05-018">L05-018</td></tr>
<tr><td>Stopping a chronic antagonist vs stopping a chronic agonist</td><td>Antagonist stopped (β-blocker): up-regulated receptors unblocked, hypertensive crisis, so taper the dose down. Agonist stopped (Levophed drip, Afrin): down-regulated receptors, so the response falls sharply</td><td>Predicting hypotension after stopping a β-blocker</td><td>19–20</td><td data-q="L05-021">L05-021</td></tr>
<tr><td>Rapid desensitization vs long-term down-regulation</td><td>Rapid: GRK (G protein–coupled receptor kinase) phosphorylates the receptor, β-arrestin binds, milliseconds, reversible when the drug leaves. Long-term: endocytosis (receptor taken into the cell) via coated pits, recycling or lysosomal degradation; takes time</td><td>"Short term regulation involves relocation into the cell"</td><td>21–24, 27</td><td data-q="L05-025">L05-025</td></tr>
<tr><td>Addition vs synergism vs potentiation</td><td>Addition: sum (50 + 50 = 100). Synergism: more than the sum (30 + 50 gives 100). Potentiation: one drug has no effect alone but raises the other's effect (carbidopa)</td><td>Calling carbidopa + L-DOPA synergism; carbidopa does nothing alone, so it is potentiation</td><td>30–31</td><td data-q="L05-030">L05-030</td></tr>
<tr><td>Graded vs quantal response</td><td>Graded: one sample, continuous scale from no effect to maximum. Quantal: population, each member binary (any effect or none), cumulative form gives a sigmoid (S-shaped curve)</td><td>Reading Emax off a quantal curve (its top is 100% of the population); looking for a labelled ED50, which the exam figure will not have</td><td>32–34</td><td data-q="L05-032">L05-032</td></tr>
<tr><td>Therapeutic index vs safety index</td><td>TI (therapeutic index) = LD50/ED50, lethal dose for 50% over effective dose for 50%. SI (safety index) = LD1/ED99, the tails; for a safe drug ED99 &lt; LD1. Both: larger is safer</td><td>Inverting either ratio; trusting a large TI when the SI is 0.1</td><td>39–42</td><td data-q="L05-036">L05-036</td></tr>
<tr><td>Therapeutic index vs therapeutic window</td><td>TI: one number, a ratio of doses. Window: a range of steady-state concentrations giving efficacy with minimal toxicity</td><td>Defining the window as a ratio</td><td>39, 43</td><td data-q="L05-044">L05-044</td></tr>
<tr><td>Same drug, two therapeutic indices (codeine)</td><td>The TI is per effect measured, because the ED50 differs for each effect: cough (huge) vs pain (very small). "No drug produces a single effect."</td><td>Treating the TI as a property of the drug alone</td><td>41</td><td data-q="L05-043">L05-043</td></tr>
</tbody></table>
<!--FIG:graded-quantal-->
<h3 id="tell-druglist">Exam 1 drug list</h3>
<table class="reftab"><thead><tr><th style="width:24%">Looks alike</th><th>What separates them</th><th style="width:28%">The trap</th><th style="width:10%">Question</th></tr></thead><tbody>
<tr><td><b>Prazosin</b> vs <b>phenoxybenzamine</b></td><td>Prazosin blocks α1 only and is reversible. Phenoxybenzamine blocks α1 and α2 and is irreversible.</td><td>Calling both reversible; the list names phenoxybenzamine as its only irreversible drug.</td><td data-q="DL1-016">DL1-016</td></tr>
<tr><td><b>Phenylephrine</b> vs <b>prazosin</b></td><td>Both are α1-selective. Phenylephrine is an agonist; prazosin is an antagonist.</td><td>Matching on the receptor and missing the direction of the effect.</td><td data-q="DL1-019">DL1-019</td></tr>
<tr><td><b>Metoprolol</b> vs <b>pindolol</b></td><td>Metoprolol is a β1 antagonist. Pindolol is a partial agonist at β1 and β2.</td><td>Filing pindolol with the β antagonists.</td><td data-q="DL1-021">DL1-021</td></tr>
<tr><td><b>Albuterol</b> vs <b>pindolol</b></td><td>Both are β partial agonists. Albuterol acts at β2 only; pindolol at β1 and β2.</td><td>Giving albuterol the β1 action.</td><td data-q="DL1-010">DL1-010</td></tr>
<tr><td><b>Loratadine</b> vs <b>diphenhydramine</b></td><td>Loratadine is an H1 inverse agonist. Diphenhydramine is a non-selective histamine receptor antagonist.</td><td>Calling loratadine an antagonist, or diphenhydramine H1-selective.</td><td data-q="DL1-017">DL1-017</td></tr>
<tr><td><b>Acetylcholine</b> vs <b>varenicline</b></td><td>Acetylcholine is an agonist at M1, M2, M3, Nn and Nm. Varenicline is a partial agonist at Nn only.</td><td>Giving varenicline muscarinic activity.</td><td data-q="DL1-018">DL1-018</td></tr>
</tbody></table>
<p class="sub">Exam_1_Drug_List_2026.pdf, Table 1.</p>
<h3 id="tell-day6">Day 6 (9/30) &mdash; Pharmacodynamics reviews.pdf</h3>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Pages</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>One right shift: competitive antagonist vs inverse agonist vs irreversible antagonist with spare receptors</td><td>All three give one right shift, same Emax, baseline 0. Inverse would pull a raised baseline to 0; irreversible drops the Emax with more antagonist, once spare receptors are used up</td><td>Picking irreversible as the one best answer from one shift (competitive is); ruling out inverse on a figure whose baseline is already 0</td><td>6, 9</td><td data-q="L06-023">L06-023</td></tr>
<tr><td>Symmetrical vs non-symmetrical shifts</td><td>Equal steps, no limit: competitive (orthosteric: the agonist's own pocket) antagonist or inverse agonist. Unequal steps that stop: allosteric (second site); then agonist or antagonist, affinity or efficacy or both</td><td>Calling unequal right shifts with the same Emax a competitive antagonist</td><td>6, 10</td><td data-q="L06-024">L06-024</td></tr>
<tr><td>Baseline 50% figure: antagonist vs partial agonist with 50% efficacy</td><td>Both are flat at 50%. In a second cell line with most receptors inactive, the partial agonist rises to 50% and the antagonist stays flat</td><td>Insisting C is a partial agonist from the 50% figure alone; on that figure it is competitive; with the second figure (baseline 0) the partial agonists are B, C and D</td><td>4</td><td data-q="L06-014">L06-014</td></tr>
<tr><td>Allosteric antagonist vs indirect antagonist (J14)</td><td>Allosteric: binds a second site on the receptor, lowers the agonist&rsquo;s affinity or efficacy. Indirect: binds upstream or downstream, never the receptor</td><td>Jeopardy option &ldquo;a drug that binds downstream from the receptor and decreases the response&rdquo; (that is indirect)</td><td>Jeopardy</td><td data-q="JP-014">JP-014</td></tr>
<tr><td>Full agonist vs inverse agonist: affinity for R vs R*</td><td>The full agonist binds active receptors (R*) tightest and keeps them active; the inverse agonist binds inactive receptors (R) tightest and keeps them inactive</td><td>Swapping the two (the class did during Jeopardy)</td><td>Jeopardy</td><td data-q="JP-018">JP-018</td></tr>
<tr><td>Pindolol vs a full &beta;-blocker</td><td>Pindolol, a partial agonist, brings 100% down to 50% and 0 up to about 50%; a full &beta;-blocker can push a low heart rate lower</td><td>Filing pindolol with the neutral antagonists; expecting it to take a low heart rate lower</td><td>11</td><td data-q="L06-026">L06-026</td></tr>
<tr><td>Therapeutic efficacy vs potency on the analgesic figure</td><td>Efficacy is the plateau: morphine and meperidine tie high, ibuprofen low. Potency is the left&ndash;right position: morphine first, meperidine second, ibuprofen last</td><td>Calling meperidine less efficacious than morphine (it is only less potent)</td><td>Part 3 page 2</td><td data-q="L06-005">L06-005</td></tr>
</tbody></table>
`;
