const TELL_HTML = `
<h2>Tell apart</h2>
<p class="sub">Slide numbers marked ~ were counted from the deck text and may be off by one or two. Pairs that share wording. Each row gives the feature that separates them and the trap a question sets. Nothing here is scored.</p>
<h3>Day 1 (9/22) &mdash; Pharmacodynamics-Day-1-2026s.pdf</h3>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Slides</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Must know vs should know</td><td>Must know = mechanism of action (MOA); should know = site of action (SOA); effect/ADR/DDI are "would be nice to know" (predicted)</td><td>Swapping MOA and SOA; thinking brand names/dose are tested</td><td>~7–8</td><td data-q="L01-001">L01-001</td></tr>
<tr><td>Affinity vs efficacy</td><td>Affinity = how well a drug binds and stays bound (bond types); efficacy = ability to change receptor activity/state (positive or negative)</td><td>Picking "bind and stay bound" for efficacy</td><td>~21, ~37–38</td><td data-q="L01-013">L01-013</td></tr>
<tr><td>Pharmacological vs apparent potency</td><td>Pharmacological: tissue sensitivity, receptor #, receptor activity, affinity, efficacy; apparent adds PK: age, absorption, distribution, elimination, DDI</td><td>Putting absorption/age/elimination under pharmacological potency</td><td>~22–23, ~27</td><td data-q="L01-015">L01-015</td></tr>
<tr><td>Safety vs efficacy</td><td>If the safe drug does not work, choose the efficacious one; if efficacy is equal, choose the safer</td><td>Choosing "very safe but not efficacious" for fungal pneumonia</td><td>~25–26</td><td data-q="L01-017">L01-017</td></tr>
<tr><td>Occupancy theory vs intrinsic activity vs two-state model</td><td>Clark: affinity only, response ∝ receptors occupied; Ariens: intrinsic activity (full 100%, partial 1–99%, antagonist 0); Stephenson/Furchgott/Nickerson: efficacy, active/inactive receptors, L constant</td><td>Explaining partial agonism by negative efficacy; giving an antagonist intrinsic activity</td><td>~28</td><td data-q="L01-019">L01-019</td></tr>
<tr><td>Inverse agonist vs antagonist</td><td>Inverse agonist shifts receptors to the inactive state (negative efficacy); antagonist binds with zero intrinsic activity and does nothing to the receptor</td><td>Calling a drug that inactivates receptors an antagonist</td><td>~28–29</td><td data-q="L01-022">L01-022</td></tr>
<tr><td>Loratadine vs diphenhydramine</td><td>Loratadine = selective H1 inverse agonist; diphenhydramine = non-selective (H1, H2, muscarinic)</td><td>Reversing which is selective</td><td>~29</td><td data-q="L01-023">L01-023</td></tr>
<tr><td>Classify by structure vs by MOA</td><td>Structure (benzothiadiazine ring) does not predict effects; MOA + SOA (Na+/Cl− symporter antagonist at distal convoluted tubule) predicts diuresis, hyponatremia, antihypertensive use</td><td>Predicting decreased urination or increased blood volume</td><td>~32–33</td><td data-q="L01-026">L01-026</td></tr>
<tr><td>Four receptor classes</td><td>Ion channels (L-type Ca++, GABA); 7-TM GPCR (α/β adrenergic, 5HT, histamine); 1-TM (tyrosine kinases); intracellular (steroid hormones)</td><td>Putting adrenergic or histamine receptors under 1-TM or ion channels</td><td>~35–36</td><td data-q="L01-027">L01-027</td></tr>
<tr><td>Passive vs voltage-gated vs ligand-gated vs pump</td><td>Passive: always open; voltage-gated: open at certain membrane potentials; ligand-gated: usually closed, binding pocket in channel; pump: moves ions against gradient</td><td>Calling the nicotinic receptor voltage-gated</td><td>~40–47</td><td data-q="L01-029">L01-029</td></tr>
<tr><td>Gs (β1, heart) vs Gq (α1, smooth muscle)</td><td>Gs: αs → adenylate cyclase → ATP → cAMP → ↑ heart rate; Gq: αq → PLC → PIP2 → IP3 → Ca2+ from ER</td><td>Assigning PLC to β1 or adenylate cyclase to α1</td><td>~51–55</td><td data-q="L01-033">L01-033</td></tr>
</tbody></table>
<h3>Day 2 (9/23) &mdash; Pharmacodynamics-Day_2_2026s copy.pdf</h3>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Slides</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Gαs vs Gαi vs Gαq</td><td>Gαs → AC → ↑cAMP; Gαi → AC → ↓cAMP; Gαq → PLC → ↑IP3, Ca++</td><td>Gαi also uses AC, so it is easy to give it PLC or an increase in cAMP</td><td>~3</td><td data-q="L02-002">L02-002</td></tr>
<tr><td>Covalent vs ionic/hydrogen/van der Waals</td><td>Covalent: irreversible, insurmountable, non-competitive, long duration. Others: reversible, surmountable, competitive</td><td>Three different names mean the same property</td><td>~15–16</td><td data-q="L02-011">L02-011</td></tr>
<tr><td>Agonist vs antagonist vs reversible vs irreversible vs allosteric</td><td>Three separate questions, and a class name answers all three at once. Where does it bind: the messenger&rsquo;s own pocket (orthosteric) or a second site (allosteric)? Does it turn the receptor on (agonist) or not (antagonist)? Does it let go (reversible) or stay bound (irreversible)? Phenylephrine: orthosteric, agonist, reversible. Prazosin: orthosteric, antagonist, reversible. Phenoxybenzamine: orthosteric, antagonist, irreversible. Diazepam: allosteric, activates only with GABA present, reversible.</td><td>Reading &ldquo;allosteric agonist&rdquo; or &ldquo;irreversible antagonist&rdquo; as one word. Reversible and irreversible say how the drug leaves, not what it does while bound; allosteric says where it binds, not whether it activates.</td><td>~18, ~37&ndash;~39; drug list, Table 1</td></tr>
<tr><td>Orthosteric vs allosteric</td><td>Orthosteric drugs compete for one pocket (one or the other); allosteric drugs bind elsewhere and change the pocket (one and the other)</td><td>Choosing "allosteric agonists compete for the pocket" or "have highest affinity for the orthosteric pocket"</td><td>~18–20, ~39–44</td><td data-q="L02-015">L02-015</td></tr>
<tr><td>Affinity vs efficacy</td><td>Affinity: bind and stay bound (bonds). Efficacy: change receptor state</td><td>Poll distractor "bind and stay bound" is affinity</td><td>~31</td><td data-q="L02-010">L02-010</td></tr>
<tr><td>Transducer vs effector vs second messenger</td><td>Transducer = G protein; effector (signal amplifier) = AC, PLC; second messenger = cAMP, PKA, PKC, IP3, Ca++</td><td>PLC called a second messenger; a receptor, AC or calcium channel chosen as a second messenger</td><td>~26–29</td><td data-q="L02-019">L02-019</td></tr>
<tr><td>Full agonist vs partial agonist</td><td>Both have greater affinity for active receptors and can activate inactive ones; full = 100% efficacy, partial = 1–99%</td><td>Thinking a partial agonist cannot activate inactive receptors</td><td>~32–34</td><td data-q="L02-024">L02-024</td></tr>
<tr><td>Inverse agonist vs neutral antagonist</td><td>Inverse: highest affinity for inactive, negative efficacy, shuts off active receptors. Neutral: equal affinity for both states, ε = 0, keeps the state as is</td><td>Petri dish: inverse → cAMP to zero; antagonist → stays at 50%</td><td>~35–38</td><td data-q="L02-025">L02-025</td></tr>
<tr><td>Indirect antagonist vs receptor/allosteric antagonist</td><td>Indirect antagonists bind components upstream or downstream of the receptor (PDE, RAS); they can enhance (caffeine) or suppress (RAS drug) the response</td><td>Calling caffeine a receptor or allosteric antagonist; expecting any "antagonist" to lower the signal</td><td>~40–41</td><td data-q="L02-028">L02-028</td></tr>
<tr><td>Kd vs EC50</td><td>Kd = concentration binding 50% of sites (affinity); EC50 = concentration producing 50% of max response (potency)</td><td>Swapping the two definitions; thinking a larger Kd means greater affinity</td><td>~45, ~50, ~57–58</td><td data-q="L02-029">L02-029</td></tr>
</tbody></table>
<h3>Day 3 (9/24) &mdash; Pharmacodynamics-Day_3_2026s.pdf</h3>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Slides</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Kd vs EC50/ED50</td><td>Kd is the dose binding 50% of receptors (binding only); EC50/ED50 is the concentration/dose giving 50% of the response (potency)</td><td>Both are read on the x-axis, but Kd does not take the drug's effect into account</td><td>~3, ~22, ~29</td><td data-q="L03-004">L03-004</td></tr>
<tr><td>EC50 vs ED50</td><td>EC50 = concentration, typically in vitro; ED50 = dose, typically in vivo, where ADME affects apparent potency</td><td>Philosophically the same; swapping in vitro/in vivo</td><td>~8, ~21</td><td data-q="L03-013">L03-013</td></tr>
<tr><td>Affinity vs efficacy on a DRC</td><td>Affinity read on x-axis (left/right); efficacy on y-axis (up/down)</td><td>Reading curve height as affinity</td><td>~16–18</td><td data-q="L03-017">L03-017</td></tr>
<tr><td>Potency vs efficacy</td><td>Potency = smallest EC50/ED50; efficacy = highest maximal response; a partial agonist can be the most potent</td><td>Assuming the most potent drug is also the most efficacious or always preferred</td><td>~22, ~27</td><td data-q="L03-020">L03-020</td></tr>
<tr><td>Equal EC50, different Emax</td><td>With tissue and affinity held constant, the drug with greater efficacy is more potent</td><td>Picking "greater affinity" when affinity is stated equal</td><td>~27</td><td data-q="L03-028">L03-028</td></tr>
<tr><td>More receptors vs changed drug</td><td>More receptors increase potency (shift left) while Kd, affinity and efficacy of the drug are unchanged</td><td>Answering "no change" because the dose is the same, or saying Kd changed</td><td>~7</td><td data-q="L03-010">L03-010</td></tr>
<tr><td>Intrinsic activity vs efficacy</td><td>Intrinsic activity (FA 1, PA 0–1, antagonist 0) ignores the tissue; efficacy is more comprehensive and only relative</td><td>Thinking efficacy can be calculated exactly</td><td>~25–26</td><td data-q="L03-029">L03-029</td></tr>
<tr><td>Full agonist vs partial agonist</td><td>Both have positive efficacy and highest affinity for active-state receptors; only the full agonist reaches 100% of the system's max</td><td>Giving the partial agonist negative efficacy or inactive-state preference</td><td>~41, ~63</td><td data-q="L03-026">L03-026</td></tr>
<tr><td>Threshold vs EC50 vs Emax vs slope</td><td>Threshold = below it no response; EC50 = 50% of max; Emax = ceiling; slope = linear mid-section</td><td>Mixing threshold with EC50</td><td>~20–21</td><td data-q="L03-016">L03-016</td></tr>
<tr><td>Steep vs shallow slope</td><td>Steep: narrow dose range from no effect to max; shallow: wider dose range before toxic effect</td><td>Treating slope as speed of onset</td><td>~21</td><td data-q="L03-022">L03-022</td></tr>
</tbody></table>
<h3>Exam 1 drug list</h3>
<table class="reftab"><thead><tr><th style="width:24%">Looks alike</th><th>What separates them</th><th style="width:28%">The trap</th><th style="width:10%">Question</th></tr></thead><tbody>
<tr><td><b>Prazosin</b> vs <b>phenoxybenzamine</b></td><td>Prazosin blocks α1 only and is reversible. Phenoxybenzamine blocks α1 and α2 and is irreversible.</td><td>Calling both reversible; the list names phenoxybenzamine as its only irreversible drug.</td><td data-q="DL1-016">DL1-016</td></tr>
<tr><td><b>Phenylephrine</b> vs <b>prazosin</b></td><td>Both are α1-selective. Phenylephrine is an agonist; prazosin is an antagonist.</td><td>Matching on the receptor and missing the direction of the effect.</td><td data-q="DL1-019">DL1-019</td></tr>
<tr><td><b>Metoprolol</b> vs <b>pindolol</b></td><td>Metoprolol is a β1 antagonist. Pindolol is a partial agonist at β1 and β2.</td><td>Filing pindolol with the β antagonists.</td><td data-q="DL1-021">DL1-021</td></tr>
<tr><td><b>Albuterol</b> vs <b>pindolol</b></td><td>Both are β partial agonists. Albuterol acts at β2 only; pindolol at β1 and β2.</td><td>Giving albuterol the β1 action.</td><td data-q="DL1-010">DL1-010</td></tr>
<tr><td><b>Loratadine</b> vs <b>diphenhydramine</b></td><td>Loratadine is an H1 inverse agonist. Diphenhydramine is a non-selective histamine receptor antagonist.</td><td>Calling loratadine an antagonist, or diphenhydramine H1-selective.</td><td data-q="DL1-017">DL1-017</td></tr>
<tr><td><b>Acetylcholine</b> vs <b>varenicline</b></td><td>Acetylcholine is an agonist at M1, M2, M3, Nn and Nm. Varenicline is a partial agonist at Nn only.</td><td>Giving varenicline muscarinic activity.</td><td data-q="DL1-018">DL1-018</td></tr>
</tbody></table>
<p class="sub">Exam_1_Drug_List_2026.pdf, Table 1.</p>
`;
