const TELL2_HTML = `
<p class="sub">Pairs that share wording: the feature that separates them and the trap a question sets. Source shorthand: ANS = Autonomic Nervous System.pdf, NMJ = PCOL-NMJ_PCOL_2026s_pptx.pdf, Chol = PCOL-Cholinergic-26s.pdf, Adr = PCOL-Adrenergic_PCOL-26s_PTII_pptx.pdf, RAAS = PCOL-RAAS_26s.pdf, List = Pharmacology_Exam_2_Drug_List.pdf; “s” = slide, “p” = page, T = transcript date. → = leads to; ↑ = rises; ↓ = falls.</p>

<h3 id="tell2-nn-nm">Nn vs Nm</h3>
<p class="sub">N = nicotinic; the subscript is the site: Nn = neuronal (brain, autonomic ganglia, adrenal medulla), Nm = muscle (skeletal muscle at the neuromuscular junction, NMJ).</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Ganglia vs skeletal muscle</td><td>Acetylcholine (ACh) acts on Nn in the ganglia of both the parasympathetic (PNS) and sympathetic (SNS) divisions; on Nm at skeletal muscle</td><td>Reading the “m” as muscarinic or smooth muscle</td><td>ANS s12, 23; T 9/30</td><td data-q="L07-009">L07-009</td></tr>
<tr><td>Nn vs Nm subunits</td><td>Nn: only α and β subunits (brain α4/β2; ganglia α3/β4, α3/β2). Nm: five subunits, α, β, γ, δ, ε</td><td>Giving Nm the α4/β2 combination</td><td>NMJ s6, 11</td><td data-q="L08-002">L08-002</td></tr>
<tr><td>Where Nn is</td><td>Brain and autonomic ganglia (plus the adrenal medulla)</td><td>Putting Nn on skeletal muscle</td><td>NMJ s4, 6; T 10/5</td><td data-q="L08-001">L08-001</td></tr>
<tr><td>Adrenal medulla</td><td>Sympathetic ACh acts on Nn there and releases epinephrine</td><td>Picking an adrenergic or muscarinic receptor</td><td>NMJ s4; ANS s35</td><td data-q="L08-006">L08-006</td></tr>
<tr><td>Varenicline vs the NMJ drugs</td><td>Varenicline: partial agonist at α4/β2 Nn in the brain. Succinylcholine and rocuronium: Nm at skeletal muscle</td><td>Giving varenicline a muscle site</td><td>NMJ s7–8, 19; T 10/1</td><td data-q="PE2-018">PE2-018</td></tr>
<tr><td>A ganglionic Nn drug vs an organ receptor drug</td><td>A drug at ganglionic Nn changes heart rate or salivation through the postganglionic neurons, without binding the organ’s receptors</td><td>Thinking the drug must bind M2 or M3 to change those organs</td><td>NMJ s5; T 10/1</td><td data-q="L08-005">L08-005</td></tr>
<tr><td>Succinylcholine at Nm vs at Nn</td><td>Intended site: Nm. With prolonged infusion it reaches ganglionic Nn: hypertension, arrhythmias</td><td>Picking brain α4/β2 receptors</td><td>NMJ s20, 25; T 10/5</td><td data-q="L08-016">L08-016</td></tr>
</tbody></table>
<p class="sub">“the two things that students get in trouble every year is not just about the mechanism of action of these drugs, it’s remembering where the receptors are located. And if the [N] cannot give you a hint that it is the neuron and the M is the muscle, we’re in trouble” (T 10/1).</p>

<h3 id="tell2-depolarizing">Depolarizing vs non-depolarizing neuromuscular blockers</h3>
<p class="sub">Both paralyze skeletal muscle at the muscle nicotinic (Nm) receptor: succinylcholine (depolarizing) opens the channel as an agonist; the curare-like drugs (-cur-: rocuronium, vecuronium, pancuronium) keep it shut as competitive antagonists.</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Two drugs that paralyze</td><td>Succinylcholine opens the Nm channel (agonist); rocuronium keeps it from opening (competitive antagonist)</td><td>Assuming an agonist must cause contraction</td><td>NMJ s19; T 10/5</td><td data-q="L08-014">L08-014</td></tr>
<tr><td>“Antagonizing the binding of ACh”</td><td>Only the curare-like drug competes with acetylcholine (ACh) for the binding site</td><td>Picking succinylcholine because it paralyzes</td><td>NMJ s19; T 10/5</td><td data-q="PE2-019">PE2-019</td></tr>
<tr><td>Phase I vs phase II (succinylcholine)</td><td>Phase I: the end plate stays depolarized and cannot reprime. Phase II: succinylcholine blocks the channel; no Na+/K+ movement</td><td>Swapping the phases, or calling phase I competitive</td><td>NMJ s22–24; T 10/5</td><td data-q="L08-017">L08-017</td></tr>
<tr><td>Reversing the block</td><td>Curare-like block is reversible: more ACh (an acetylcholinesterase inhibitor such as neostigmine) outcompetes it</td><td>Picking succinylcholine or rocuronium to reverse curare</td><td>NMJ s27–29, 39; T 10/5</td><td data-q="PE2-022">PE2-022</td></tr>
<tr><td>Adverse reactions</td><td>Succinylcholine: hyperkalemia, hypertension and arrhythmias (ganglia), myalgia; malignant hyperthermia with halothane. Curare-like: respiratory paralysis, no central nervous system effect</td><td>Picking histamine release, a curare-like reaction</td><td>NMJ s25–26, 32; T 10/5</td><td data-q="L08-019">L08-019</td></tr>
<tr><td>Most likely effect of rocuronium</td><td>Paralysis; the gut, bladder and vessels need muscarinic or adrenergic receptors</td><td>Picking diarrhea, urination or bronchial constriction</td><td>NMJ s19, 32; T 10/5</td><td data-q="PE2-020">PE2-020</td></tr>
<tr><td>The curare-like drugs vs each other</td><td>Same mechanism and site: competitive, reversible Nm antagonism → paralysis</td><td>Picking depolarizing agonism or sedation</td><td>NMJ s19, 30; T 10/5</td><td data-q="L08-024">L08-024</td></tr>
</tbody></table>
<p class="sub">“You must know that a [succinylcholine] is an agonist that depolarize or open those ion channels.” “any [curare]-like drug is what? A competitive, reversible NM antagonist, and by blocking the NM, what are you gonna get? Paralysis” (T 10/5).</p>

<h3 id="tell2-ache">Reversible vs irreversible cholinesterase inhibitors</h3>
<p class="sub">All raise acetylcholine (ACh) by blocking acetylcholinesterase (AChE); the bond decides: reversible (the -stigmines, donepezil) or covalent and irreversible (organophosphates, including echothiophate). Among the reversible ones, crossing the blood–brain barrier (BBB) decides the site.</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Organophosphates vs neostigmine</td><td>Organophosphates form a covalent, very stable bond with the enzyme: irreversible</td><td>Calling neostigmine the irreversible one</td><td>NMJ s39, 42–43; T 10/5</td><td data-q="L08-035">L08-035</td></tr>
<tr><td>Echothiophate vs the -stigmines</td><td>Echothiophate is an organophosphate: irreversible, although it is a therapeutic eye drop</td><td>Calling it reversible because it is a medicine</td><td>NMJ s45; T 10/5</td><td data-q="DL2-021">DL2-021</td></tr>
<tr><td>Treating the irreversible one</td><td>Pralidoxime dephosphorylates (frees) the enzyme; atropine blocks the excess ACh at muscarinic receptors</td><td>Pairing neostigmine with physostigmine, or succinylcholine with dantrolene</td><td>NMJ s44; Chol s20–23; T 10/5</td><td data-q="L08-037">L08-037</td></tr>
<tr><td>Organophosphate toxicity vs DUMBBELSS alone</td><td>Ganglia: tachycardia, hypertension. Neuromuscular junction: cramps, weakness, respiratory paralysis. Brain: confusion, seizures</td><td>Picking histamine release or blocked ACh release</td><td>NMJ s43; T 10/5</td><td data-q="L08-036">L08-036</td></tr>
<tr><td>Physostigmine vs neostigmine, pyridostigmine</td><td>Physostigmine (tertiary amine) crosses the BBB; neostigmine and pyridostigmine (quaternary) do not</td><td>Thinking every -stigmine reaches the brain</td><td>NMJ s39; T 10/5</td><td data-q="L08-030">L08-030</td></tr>
<tr><td>Which reversible ones reach the brain</td><td>Physostigmine, donepezil, rivastigmine</td><td>Adding neostigmine</td><td>NMJ s39–40; T 10/5</td><td data-q="DL2-016">DL2-016</td></tr>
<tr><td>Neostigmine vs physostigmine for a muscle disease</td><td>Neostigmine stays in the periphery, where the problem is; physostigmine only adds central side effects</td><td>Picking the drug that “goes everywhere”</td><td>NMJ s39; T 10/5</td><td data-q="L08-029">L08-029</td></tr>
<tr><td>Neostigmine vs rivastigmine</td><td>Rivastigmine crosses the BBB and acts in the body too: the pick for myasthenia gravis plus Alzheimer’s disease</td><td>Choosing neostigmine when the brain is also a target</td><td>NMJ s39–40; T 10/5</td><td data-q="L08-048">L08-048</td></tr>
</tbody></table>
<p class="sub">“these drugs, they’re going to form covalent bonds and as we discussed before, if you form covalent bonds that tells you they are irreversible” (T 10/5). DUMBBELSS = diarrhea, urination, miosis, bradycardia, bronchial constriction, emesis, lacrimation, salivation, stimulation of the brain.</p>

<h3 id="tell2-direct-indirect">Muscarinic agonist vs cholinesterase inhibitor (direct vs indirect)</h3>
<p class="sub">A muscarinic agonist (methacholine, carbachol, bethanechol, pilocarpine) binds the muscarinic receptor itself; a cholinesterase inhibitor (the -stigmines, donepezil) binds the enzyme and raises acetylcholine (ACh), which then acts at muscarinic and nicotinic receptors.</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Direct vs indirect acting</td><td>Direct: binds the receptor. Indirect: raises ACh by blocking its breakdown, “somewhere else other than the receptor”</td><td>Calling an enzyme inhibitor a receptor agonist</td><td>NMJ s3, 10–12; Chol s4; T 10/5</td><td data-q="L09-003">L09-003</td></tr>
<tr><td>Which receptors</td><td>Muscarinic agonists: M1, M2, M3 only, never nicotinic. ACh itself binds both</td><td>Thinking carbachol or pilocarpine also activate nicotinic receptors</td><td>Chol s11–12, 14; T 10/5</td><td data-q="L09-016">L09-016</td></tr>
<tr><td>Where the inhibitor acts</td><td>Anywhere ACh is released: ganglia, heart, glands, skeletal muscle</td><td>Limiting it to the neuromuscular junction or the brain</td><td>NMJ s37; T 10/5</td><td data-q="L08-028">L08-028</td></tr>
<tr><td>Both cause DUMBBELSS (agonist)</td><td>Carbachol activates M2 in the heart: bradycardia</td><td>Picking an anti-DUMBBELSS effect (dry mouth, constipation)</td><td>Chol s11–14; T 10/5</td><td data-q="PE2-025">PE2-025</td></tr>
<tr><td>Both cause DUMBBELSS (inhibitor)</td><td>Rivastigmine raises ACh: salivation</td><td>Picking constipation, tachycardia or pupil dilation</td><td>NMJ s40–41; T 10/5</td><td data-q="PE2-021">PE2-021</td></tr>
<tr><td>Reversing curare</td><td>Only the inhibitor raises ACh at Nm (muscle nicotinic) to outcompete curare; a muscarinic agonist cannot reach Nm</td><td>Picking atropine, which blocks only muscarinic receptors</td><td>NMJ s39; T 10/5</td><td data-q="DL2-018">DL2-018</td></tr>
<tr><td>Potency of ACh</td><td>An AChE inhibitor makes ACh more potent: it is not broken down</td><td>Reading the enzyme “antagonist” as an antagonist of ACh</td><td>NMJ s35–36; T 10/1, 10/5</td><td data-q="L08-027">L08-027</td></tr>
<tr><td>Names: “chol” vs “-stigmine”</td><td>“chol” (methacholine, carbachol, bethanechol): muscarinic agonist. “-stigmine”: cholinesterase enzyme</td><td>Reading “chol” as an antagonist</td><td>Chol s11; NMJ s39; T 10/5</td><td data-q="L09-013">L09-013</td></tr>
<tr><td>Atropine against either</td><td>A reversible muscarinic agonist is outcompeted by a muscarinic antagonist</td><td>Thinking the agonist binds irreversibly</td><td>Chol s12, 19; T 10/5</td><td data-q="L09-054">L09-054</td></tr>
</tbody></table>
<p class="sub">Carbachol walk-through (T 10/6): “What would be a possible drug-drug interaction? Well, if add another agonist ... Or if we add one of those [acetylcholinesterase] enzyme antagonists ... What would be a negative drug-drug interaction? If you add an antagonist to outcompete it”.</p>

<h3 id="tell2-antimuscarinic">Atropine vs scopolamine vs the bladder drugs</h3>
<p class="sub">All are reversible muscarinic antagonists with affinity for M3; they differ in what else they block, where they go, and how selective they are for the bladder’s M3.</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Atropine vs scopolamine: receptors</td><td>Atropine: M1, M2, M3 only. Scopolamine: muscarinic plus histamine and serotonin receptors</td><td>Giving atropine the histamine block</td><td>Chol s17; T 10/5</td><td data-q="L09-026">L09-026</td></tr>
<tr><td>Atropine vs scopolamine: brain</td><td>Scopolamine penetrates the central nervous system (CNS) faster: drowsiness, euphoria, amnesia; motion sickness</td><td>Picking another “trop” drug</td><td>Chol s24; T 10/5</td><td data-q="L09-031">L09-031</td></tr>
<tr><td>Atropine: muscarinic only</td><td>“Competitively antagonize the activations of muscarinic receptors”; no muscle nicotinic (Nm) block, so no paralysis</td><td>“Causes paralysis by blocking Nm receptors”</td><td>Chol s17, 19; T 10/5</td><td data-q="PE2-026">PE2-026</td></tr>
<tr><td>Atropine and the heart</td><td>Blocks M2; the parasympathetic tone predominates, so heart rate rises: the drug for severe bradycardia</td><td>Picking carbachol or neostigmine</td><td>Chol s19–20; T 10/6</td><td data-q="PE2-028">PE2-028</td></tr>
<tr><td>Bladder drugs: effect</td><td>Trospium, oxybutynin, solifenacin block bladder M3: decreased urination</td><td>Picking salivation or increased GI motility</td><td>Chol s29; T 10/6</td><td data-q="PE2-027">PE2-027</td></tr>
<tr><td>Oxybutynin vs solifenacin</td><td>Oxybutynin: oldest, least selective (M1 and M3), most anti-DUMBBELSS, sedation from M1. Solifenacin: more selective for M3; enough of it still gives all the anti-DUMBBELSS</td><td>Thinking solifenacin cannot cause anti-DUMBBELSS</td><td>Chol s29–30; T 10/5</td><td data-q="L09-052">L09-052</td></tr>
<tr><td>Shared by all the bladder drugs</td><td>Dry mouth and constipation, through M3</td><td>Attributing them to M1 or M2</td><td>Chol s30; T 10/5</td><td data-q="L09-039">L09-039</td></tr>
<tr><td>“trop” in the name</td><td>Atropine, ipratropium, tiotropium, trospium, benztropine, tropicamide: atropine-like antagonists</td><td>Reading “trop” as an agonist</td><td>Chol s17, 26, 28–29; T 10/5</td><td data-q="L09-049">L09-049</td></tr>
<tr><td>Bladder antimuscarinic vs mirabegron</td><td>Mirabegron relaxes the bladder as a β3 agonist: no anti-DUMBBELSS</td><td>Thinking mirabegron blocks M3</td><td>Adr s44; T 10/7</td><td data-q="L11-021">L11-021</td></tr>
</tbody></table>
<p class="sub">“That one is really non-selective. That not only blocks all the muscarinics, but also histamine and serotonin receptors.” “VESIcare is more selective [to] M3, less anti-dumbbell side effects ... If I give enough of VESIcare, I’m gonna get all the anti-dumbbells.” (T 10/5) The exam’s bladder drugs: oxybutynin, trospium, solifenacin. Anti-DUMBBELSS = the opposite of diarrhea, urination, miosis, bradycardia, bronchial constriction, emesis, lacrimation, salivation, CNS stimulation.</p>

<h3 id="tell2-alpha">α1 vs α2 drugs</h3>
<p class="sub">α1 is Gq (↑Ca++, constriction, excitatory); α2 is Gi (↓cAMP, less norepinephrine (NE) release, inhibitory). Agonist or antagonist, selective or not, reversible or not: phenylephrine, oxymetazoline, clonidine, prazosin, phenoxybenzamine, mirtazapine.</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>α1 vs α2 signalling</td><td>α1: phospholipase C → IP3 → ↑Ca++. α2: inhibits adenylate cyclase → ↓cAMP</td><td>Swapping the G proteins</td><td>Adr s3, 17, 21; T 10/6</td><td data-q="L10-038">L10-038</td></tr>
<tr><td>Phenylephrine vs clonidine (both agonists)</td><td>Phenylephrine activates α1: vasoconstriction, decongestion. Clonidine activates α2: less NE release, lower blood pressure (BP)</td><td>Thinking every adrenergic agonist raises BP</td><td>Adr s17–18, 21–24; T 10/6</td><td data-q="PE2-037">PE2-037</td></tr>
<tr><td>Why phenylephrine decongests</td><td>It activates α1, which increases Ca++ in nasal vascular smooth muscle</td><td>Picking M3, Nm or α4/β2 options</td><td>Adr s17–18; T 10/6</td><td data-q="PE2-036">PE2-036</td></tr>
<tr><td>Phenylephrine vs oxymetazoline</td><td>Phenylephrine: α1 only. Oxymetazoline: α1 and α2, so less constriction</td><td>Calling oxymetazoline selective</td><td>Adr s9, 18–19; T 10/6</td><td data-q="L10-018">L10-018</td></tr>
<tr><td>Clonidine: agonist that lowers activity</td><td>It activates an inhibitory (Gi) receptor on the nerve ending</td><td>Explaining it by α1, NET or MAO block</td><td>Adr s21, 23–24; T 10/6</td><td data-q="L10-040">L10-040</td></tr>
<tr><td>Clonidine vs mirtazapine (both at α2)</td><td>Clonidine (agonist): less NE release. Mirtazapine (antagonist): more NE release, plus H1 and muscarinic block (sedation)</td><td>Giving mirtazapine the clonidine effect</td><td>Adr s21, 31–32; T 10/6</td><td data-q="L10-060">L10-060</td></tr>
<tr><td>Phenylephrine vs prazosin (both at α1)</td><td>Prazosin is the α1 antagonist: vasodilation</td><td>Picking phenylephrine for vasodilation</td><td>Adr s27–29; T 10/7</td><td data-q="PE2-038">PE2-038</td></tr>
<tr><td>Prazosin vs phenoxybenzamine</td><td>Prazosin: reversible, α1 only. Phenoxybenzamine: irreversible (covalent), α1 and α2</td><td>Giving prazosin the α2 block</td><td>Adr s27, 34; T 10/7</td><td data-q="L11-010">L11-010</td></tr>
<tr><td>Which drops BP more</td><td>Phenoxybenzamine: the extra NE released cannot outcompete a covalent bond</td><td>“Equal potency”, or thinking the extra NE weakens phenoxybenzamine</td><td>Adr s34–36; T 10/7</td><td data-q="PE2-039">PE2-039</td></tr>
<tr><td>Phenoxybenzamine’s GI stimulation</td><td>α2 on the parasympathetic nerve in the gut is blocked, so ACh release is no longer inhibited</td><td>Putting α2 on the gut muscle</td><td>Adr s36–38; T 10/7</td><td data-q="L11-007">L11-007</td></tr>
<tr><td>Two “rebound” warnings</td><td>Clonidine stopped abruptly: up-regulated receptors → hypertensive crisis. Phenylephrine over 3 days: rebound congestion</td><td>Mixing up the two</td><td>Adr s18, 26; T 10/6</td><td data-q="L10-043">L10-043</td></tr>
<tr><td>“-idine” vs “-osin”</td><td>-idine (clonidine, brimonidine, tizanidine): α2 agonist. -osin (prazosin, terazosin, doxazosin): selective α1 antagonist</td><td>Reading -osin as an agonist</td><td>Adr s22, 27; T 10/6</td><td data-q="L10-046">L10-046</td></tr>
</tbody></table>
<p class="sub">“alpha 1 agonist constrict, alpha 2 relax ... So calcium goes up with alpha 1s, [cAMP] goes down with the alpha 2s.” “What happens if I inhibit the inhibitor? I get positive effect.” (T 10/6)</p>

<h3 id="tell2-beta-blockers">β1-selective vs non-selective vs mixed β blockers (MAN)</h3>
<p class="sub">MAN (metoprolol, atenolol, nebivolol): β1 only. Propranolol, pindolol: β1 and β2. Carvedilol, labetalol: β1, β2 and α1. Every one of them blocks β1.</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Which are β1-selective</td><td>Metoprolol, atenolol, nebivolol</td><td>Adding propranolol or carvedilol</td><td>Adr s54; T 10/7</td><td data-q="L11-038">L11-038</td></tr>
<tr><td>Which also block β2</td><td>Propranolol, pindolol, carvedilol, labetalol</td><td>Leaving out the α1 blockers</td><td>Adr s54; T 10/7</td><td data-q="L11-072">L11-072</td></tr>
<tr><td>Drug and receptors</td><td>Atenolol: β1 only; carvedilol and labetalol add α1</td><td>Calling carvedilol cardioselective</td><td>Adr s54; T 10/7</td><td data-q="L11-037">L11-037</td></tr>
<tr><td>What all of them share</td><td>β1 block in the heart: ↓contractile force, ↓heart rate, slower relaxation</td><td>Picking tachycardia or higher cardiac output</td><td>Adr s56–58; T 10/7</td><td data-q="L11-040">L11-040</td></tr>
<tr><td>Patient with asthma</td><td>Metoprolol spares lung β2; propranolol blocks it and constricts the airway</td><td>Choosing propranolol</td><td>Adr s54, 59; T 10/7</td><td data-q="L11-044">L11-044</td></tr>
<tr><td>The twins race</td><td>Metoprolol: “at least the metoprolol guy can breathe”; propranolol and carvedilol block β2, carbachol and neostigmine constrict the bronchi</td><td>Picking neostigmine</td><td>Adr s54, 59; T 10/7</td><td data-q="PE2-042">PE2-042</td></tr>
<tr><td>Insulin-dependent diabetes</td><td>β1-selective preferred; all mask the tachycardia of hypoglycemia, non-selective ones also tremor and nervousness</td><td>Choosing a non-selective blocker</td><td>Adr s59; T 10/7</td><td data-q="L11-046">L11-046</td></tr>
<tr><td>Pindolol vs propranolol</td><td>Pindolol is a partial agonist: smaller drop in resting heart rate</td><td>Picking propranolol or metoprolol</td><td>Adr s54–55; T 10/7</td><td data-q="DL2-071">DL2-071</td></tr>
<tr><td>Carvedilol vs metoprolol on MAP</td><td>Carvedilol lowers both cardiac output and total peripheral resistance (α1); metoprolol lowers cardiac output</td><td>Giving carvedilol only a heart effect</td><td>Adr s7, 54; T 10/6</td><td data-q="L10-011">L10-011</td></tr>
<tr><td>Propranolol vs metoprolol in the brain</td><td>Propranolol is lipophilic and blocks central β2: less anxiety. Metoprolol reaches the brain poorly</td><td>Picking a central α2 or M1 effect</td><td>Adr s56–57; T 10/7</td><td data-q="L11-043">L11-043</td></tr>
<tr><td>Stopping any β blocker</td><td>Blockade up-regulated the receptors: rebound hypertension</td><td>Expecting hypotension</td><td>Adr s59; T 10/7</td><td data-q="L11-047">L11-047</td></tr>
</tbody></table>
<p class="sub">“How about if we spell man. Man, right? So, we have metoprolol, atenolol, and [nebivolol]. Those are gonna be your beta one selectives ... it will be silly for you to miss a question exam but not knowing which of the beta blockers is the selective or not.” (T 10/7) Generations are not asked.</p>

<h3 id="tell2-catecholamines">Epinephrine vs norepinephrine vs isoproterenol vs dobutamine</h3>
<p class="sub">The receptor profile separates them: epinephrine β1, β2 first then α1, α2 as the dose rises; norepinephrine α1 and β1; isoproterenol β1 = β2; dobutamine β1 only.</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Epinephrine’s order of affinity</td><td>β1 and β2, then α1, then α2</td><td>Reversing the order</td><td>Adr s47; T 10/7</td><td data-q="L11-026">L11-026</td></tr>
<tr><td>Epinephrine low vs high dose</td><td>Low: β2 dilates the vessels. High: α1 joins and overrides β2: constriction</td><td>Expecting constriction at every dose</td><td>Adr s47–51; T 10/7</td><td data-q="L11-027">L11-027</td></tr>
<tr><td>Receptor A vs receptor B in a vessel</td><td>A (constriction at high concentration): α1. B (dilation at low concentration): β2</td><td>Picking α2 or β1 for A</td><td>Adr s47; T 10/8</td><td data-q="PE2-049">PE2-049</td></tr>
<tr><td>Epinephrine vs norepinephrine</td><td>Low-dose epinephrine favors β2; norepinephrine has its highest affinity for α1 and β1</td><td>Giving norepinephrine the low-dose dilation</td><td>Adr s47, 53; T 10/7</td><td data-q="L11-036">L11-036</td></tr>
<tr><td>Norepinephrine’s receptors</td><td>Highest affinity: α1 and β1 (it can bind α2 and β2)</td><td>Picking β1 and β2</td><td>Adr s53; T 10/7</td><td data-q="L11-034">L11-034</td></tr>
<tr><td>Isoproterenol vs dobutamine</td><td>Isoproterenol: β1 and β2 equally (“iso equal”). Dobutamine: β1 only</td><td>Calling isoproterenol selective, or dobutamine a β2 drug</td><td>Adr s40, 45; T 10/7</td><td data-q="L11-025">L11-025</td></tr>
<tr><td>Why isoproterenol left asthma care</td><td>It also activates β1 in the heart: palpitations, tachycardia</td><td>Thinking it blocks bronchial β2</td><td>Adr s45; T 10/7</td><td data-q="L11-024">L11-024</td></tr>
<tr><td>Dobutamine</td><td>Selective β1 agonist; tolerance from β1 down-regulation</td><td>Calling it a β1 antagonist or a non-selective agonist</td><td>Adr s40–41; T 10/7</td><td data-q="L11-014">L11-014</td></tr>
<tr><td>Epinephrine overdose</td><td>α1 and β1 predominate; give prazosin first to dilate and keep blood flowing, then slow the heart</td><td>Giving metoprolol first</td><td>Adr s52; T 10/7</td><td data-q="PE2-040">PE2-040</td></tr>
<tr><td>Epinephrine vs phenylephrine pressor rise</td><td>Phenylephrine rises more: it has no β2 dilation opposing α1</td><td>Crediting phenylephrine with a β1 action</td><td>Adr s48–51; T 10/7</td><td data-q="L11-029">L11-029</td></tr>
<tr><td>Prazosin vs propranolol before epinephrine</td><td>Prazosin (α1 blocked): epinephrine now dilates (reversal). Propranolol (β2 blocked): greater constriction</td><td>Expecting a β blocker to reverse the pressor effect</td><td>Adr s48–51; T 10/7, 10/8</td><td data-q="PE2-052">PE2-052</td></tr>
</tbody></table>
<p class="sub">“the rank of affinity is gonna be beta one beta [twos], alpha one, and then alpha 2.” “norepinephrine appears to have a higher affinity for the beta ones and the alpha ones ... than it does for the beta 2s or the alpha 2s.” “iso equal, right, equal affinity and efficacy for the beta 1s and the beta 2s.” (T 10/7)</p>

<h3 id="tell2-indirect-adrenergic">Cocaine vs amphetamine vs MAO inhibitors</h3>
<p class="sub">All raise synaptic norepinephrine (NE) without binding an adrenergic receptor; the step decides: cocaine blocks reuptake (the NE transporter, NET), amphetamine releases NE, monoamine oxidase (MAO) inhibitors stop its breakdown.</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Which blocks the NET</td><td>Cocaine: a complete NET blocker</td><td>Picking amphetamine (a weak NET inhibitor)</td><td>Adr s10–11; T 10/6</td><td data-q="PE2-035">PE2-035</td></tr>
<tr><td>Amphetamine’s primary action</td><td>Presynaptic release of NE, dopamine and serotonin</td><td>Calling it a reuptake inhibitor first</td><td>Adr s11; T 10/6</td><td data-q="L10-023">L10-023</td></tr>
<tr><td>Amphetamine’s weaker actions</td><td>Decreased reuptake; MAO block</td><td>Thinking it has none</td><td>Adr s11; T 10/6</td><td data-q="L10-024">L10-024</td></tr>
<tr><td>Why an MAO inhibitor raises NE</td><td>Less NE is broken down, so more is stored in vesicles and released</td><td>Thinking the α2 receptor is blocked</td><td>Adr s8, 13–14; T 10/6</td><td data-q="L10-032">L10-032</td></tr>
<tr><td>Phenelzine vs selegiline</td><td>Phenelzine: MAO-A and MAO-B. Selegiline: MAO-B (low doses). Both irreversible</td><td>Giving selegiline both MAO-A and MAO-B</td><td>Adr s14; T 10/6</td><td data-q="L10-028">L10-028</td></tr>
<tr><td>Cheese effect</td><td>Phenelzine also blocks gut MAO, so dietary tyramine is not broken down: hypertensive crisis. Selegiline: no cheese effect</td><td>Giving selegiline the tyramine crisis</td><td>Adr s15; T 10/6</td><td data-q="L10-031">L10-031</td></tr>
<tr><td>Indirect vs direct</td><td>Indirect: amphetamine, cocaine, phenelzine, selegiline. Direct agonists: phenylephrine, clonidine, oxymetazoline (ephedrine is mixed: direct agonist and releaser)</td><td>Adding a direct agonist such as phenylephrine</td><td>Adr s9; T 10/6</td><td data-q="L10-020">L10-020</td></tr>
<tr><td>Cocaine’s nosebleeds</td><td>Excess NE on α1 in the nasal vessels: severe vasoconstriction</td><td>Blaming MAO block or a β2 effect</td><td>Adr s10; T 10/6</td><td data-q="L10-021">L10-021</td></tr>
</tbody></table>
<p class="sub">“So amphetamine is a weaker inhibitor of the net, but its primary ... mechanism of action is what? Increase the release of norepinephrine, right? So, cocaine is a 100% inhibitor of the net process.” (T 10/6)</p>

<h3 id="tell2-raas">ACE inhibitor vs ARB vs aliskiren vs spironolactone</h3>
<p class="sub">Each blocks a different step of the renin–angiotensin–aldosterone system (RAAS): aliskiren the enzyme renin, an angiotensin-converting enzyme (ACE) inhibitor (-pril) the ACE enzyme, an angiotensin II receptor blocker (ARB, -sartan) the AT1 receptor, spironolactone the aldosterone (mineralocorticoid, MR) receptor. Downstream of the block goes down; upstream goes up.</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Drug and target</td><td>Aliskiren: renin. -pril: ACE. -sartan: AT1. Spironolactone: MR</td><td>Pairing losartan with ACE or captopril with AT1</td><td>RAAS s4, 21; T 10/8</td><td data-q="L12-011">L12-011</td></tr>
<tr><td>Angiotensin I: lisinopril vs aliskiren</td><td>Lisinopril raises it (upstream of ACE); aliskiren lowers it (downstream of renin)</td><td>Saying both lower it</td><td>RAAS s8, 12, 29; T 10/8</td><td data-q="L12-063">L12-063</td></tr>
<tr><td>Angiotensin II: lisinopril</td><td>Lisinopril lowers angiotensin II; renin and angiotensin I are upstream and do not fall</td><td>“Decreases renin plasma level”</td><td>RAAS s12, 29; T 10/8</td><td data-q="PE2-054">PE2-054</td></tr>
<tr><td>Angiotensin II: losartan</td><td>With AT1 blocked, angiotensin II and angiotensin I rise; AT1 activation falls, AT2 activation rises</td><td>Expecting angiotensin II to fall as with an ACE inhibitor</td><td>RAAS s13, 27, 29; T 10/8</td><td data-q="L12-033">L12-033</td></tr>
<tr><td>AT2: ARB vs ACE inhibitor</td><td>ARB: AT2 left open, so its activation rises. ACE inhibitor: less angiotensin II, so AT1 and AT2 activation both fall</td><td>Crediting the ACE inhibitor with the AT2 bonus</td><td>RAAS s26–27; T 10/8</td><td data-q="PE2-055">PE2-055</td></tr>
<tr><td>Bradykinin</td><td>Only the ACE inhibitor raises it (ACE breaks it down): dry cough, angioedema</td><td>Giving the ARB or aliskiren the bradykinin rise</td><td>RAAS s9, 12, 19; T 10/8</td><td data-q="L12-061">L12-061</td></tr>
<tr><td>Cough on lisinopril</td><td>Switch to an ARB: no bradykinin rise</td><td>Switching for hyperkalemia or pregnancy, which all classes share</td><td>RAAS s19; T 10/8</td><td data-q="L12-037">L12-037</td></tr>
<tr><td>Hyperkalemia</td><td>All four: captopril, losartan, aliskiren, spironolactone</td><td>Picking spironolactone alone</td><td>RAAS s19, 22; T 10/8</td><td data-q="PE2-056">PE2-056</td></tr>
<tr><td>Aldosterone vs spironolactone</td><td>Aldosterone retains Na+ and wastes K+; spironolactone blocks it at its receptor: Na+ lost, K+ spared</td><td>Thinking it activates the receptor or makes more pumps</td><td>RAAS s20–21; T 10/8</td><td data-q="L12-054">L12-054</td></tr>
<tr><td>Spironolactone vs eplerenone</td><td>Both MR antagonists; eplerenone is more selective for the kidney MR, so no gynecomastia</td><td>Giving eplerenone the gynecomastia</td><td>RAAS s22; T 10/8</td><td data-q="L12-057">L12-057</td></tr>
<tr><td>Metoprolol vs aliskiren</td><td>Metoprolol lowers renin release (β1 on the juxtaglomerular cells), suppressed not abolished; aliskiren blocks renin itself</td><td>Saying it abolishes renin release</td><td>RAAS s7–8, 24–25; T 10/8</td><td data-q="L12-060">L12-060</td></tr>
</tbody></table>
<p class="sub">“So downstream goes down, upstream goes up.” “I guarantee you you’re gonna have at least 1 to 2 questions on the effects of these drugs in the cascade.” (T 10/8)</p>

<h3 id="tell2-nitrate-pde">Nitrate vs PDE inhibitor</h3>
<p class="sub">Both raise cyclic GMP (cGMP) in vascular smooth muscle: a nitrate donates nitric oxide (NO), so more cGMP is made; a phosphodiesterase (PDE) inhibitor (sildenafil, tadalafil) stops cGMP from being broken down.</p>
<table class="reftab"><thead><tr><th style="width:20%">Looks alike</th><th>What separates them</th><th style="width:24%">The trap</th><th style="width:12%">Source</th><th style="width:9%">Question</th></tr></thead><tbody>
<tr><td>Nitroglycerin’s mechanism</td><td>Donates NO that activates soluble guanylyl cyclase (sGC) directly, bypassing endothelial M3 and NO synthase</td><td>Thinking it acts on endothelial M3</td><td>Adr s62, 67–74; T 10/7</td><td data-q="L11-055">L11-055</td></tr>
<tr><td>Sildenafil’s mechanism</td><td>Blocks PDE, so cGMP rises</td><td>Calling sildenafil an NO donor</td><td>Adr s68–74; T 10/7</td><td data-q="DL2-047">DL2-047</td></tr>
<tr><td>Together</td><td>The effects add: marked hypotension</td><td>Picking phenylephrine or amphetamine</td><td>Adr s74; T 10/7</td><td data-q="PE2-043">PE2-043</td></tr>
<tr><td>Potency of NO with a PDE inhibitor</td><td>It increases: each NO signal leaves more cGMP</td><td>Expecting no change, since the inhibitor makes no NO</td><td>Adr s74; T 10/7</td><td data-q="L11-060">L11-060</td></tr>
<tr><td>β2 (cAMP) vs NO (cGMP)</td><td>Different second messengers, both dilate vessels, and PDE breaks down both</td><td>Thinking NO raises cAMP</td><td>Adr s67–74; T 10/7</td><td data-q="L11-059">L11-059</td></tr>
<tr><td>Endothelial M3 vs smooth-muscle α1 (both Gq)</td><td>M3 on the endothelium → Ca++ → NO synthase → NO → dilation; α1 on smooth muscle → Ca++ → constriction</td><td>Predicting constriction from vascular M3</td><td>Adr s17, 74; ANS s4; T 10/7</td><td data-q="L11-054">L11-054</td></tr>
<tr><td>Which raise cGMP</td><td>Nitroprusside, isosorbide, tadalafil</td><td>Adding albuterol, which dilates through cAMP</td><td>List p4; Adr s62, 74; T 10/7</td><td data-q="DL2-048">DL2-048</td></tr>
</tbody></table>
<p class="sub">“nitroglycerin over here is going to give away its nitric oxide which is going to bypass all of this and go straight into the [soluble guanylyl] cyclase and produce cyclic GMP”; “I would like for you to tell me on an exam is why it’s bad to take [sildenafil] with a nitric oxide donor, right? Because you have this additive effect” (T 10/7).</p>
`;
